SmartMouse_2018: AbstractMaze.cpp File Reference
AbstractMaze.cpp File Reference
#include "AbstractMaze.h"
#include <string.h>
#include <string>
#include <algorithm>
#include <random>
#include <sstream>
Functions
std::string route_to_string (route_t &route)
void insert_motion_primitive_back (route_t *route, motion_primitive_t prim)
void insert_motion_primitive_front (route_t *route, motion_primitive_t prim)
Function Documentation
void insert_motion_primitive_back (route_t * route, motion_primitive_t prim)
References motion_primitive_t::d, and motion_primitive_t::n.
Referenced by WallFollow::solve(), TEST(), and AbstractMaze::truncate().
void insert_motion_primitive_front (route_t * route, motion_primitive_t prim)
References motion_primitive_t::d, and motion_primitive_t::n.
Referenced by AbstractMaze::flood_fill(), and TEST().
std::string route_to_string (route_t & route)
References dir_to_char().
Referenced by TEST().