SmartMouse_2018: AbstractMaze.h File Reference
AbstractMaze.h File Reference
#include <stdio.h>
#include <fstream>
#include "SensorReading.h"
#include "Node.h"
#include "Direction.h"
#include <vector>
Classes
struct motion_primitive_t
Contains functions for creating and using the AbstractMaze and Node structs.
class AbstractMaze
Namespaces
smartmouse
smartmouse::maze
Typedefs
typedef std::vector< motion_primitive_t > route_t
Functions
std::string route_to_string (route_t &route)
void insert_motion_primitive_front (route_t *route, motion_primitive_t prim)
void insert_motion_primitive_back (route_t *route, motion_primitive_t prim)
constexpr double smartmouse::maze::toMeters (double cu)
constexpr double smartmouse::maze::toCellUnits (double meters)
Variables
static constexpr unsigned int smartmouse::maze::SIZE = 16
const unsigned long smartmouse::maze::BUFF_SIZE = (SIZE * 2 + 3) * SIZE
static constexpr unsigned int smartmouse::maze::CENTER = SIZE / 2
static constexpr double smartmouse::maze::UNIT_DIST_M = 0.18
static constexpr double smartmouse::maze::WALL_THICKNESS_M = 0.012
static constexpr double smartmouse::maze::HALF_WALL_THICKNESS_M = WALL_THICKNESS_M / 2.0
static constexpr double smartmouse::maze::HALF_UNIT_DIST = UNIT_DIST_M / 2.0
static constexpr double smartmouse::maze::SIZE_M = SIZE * UNIT_DIST_M
constexpr double smartmouse::maze::WALL_THICKNESS_CU = toCellUnits(WALL_THICKNESS_M)
constexpr double smartmouse::maze::HALF_WALL_THICKNESS_CU = toCellUnits(HALF_WALL_THICKNESS_M)
constexpr double smartmouse::maze::SIZE_CU = toCellUnits(SIZE_M)
Typedef Documentation
typedef std::vector<motion_primitive_t> route_t
Function Documentation
void insert_motion_primitive_back (route_t * route, motion_primitive_t prim)
References motion_primitive_t::d, and motion_primitive_t::n.
Referenced by WallFollow::solve(), TEST(), and AbstractMaze::truncate().
void insert_motion_primitive_front (route_t * route, motion_primitive_t prim)
References motion_primitive_t::d, and motion_primitive_t::n.
Referenced by AbstractMaze::flood_fill(), and TEST().
std::string route_to_string (route_t & route)
References dir_to_char().
Referenced by TEST().