SmartMouse_2018: Animate.cpp File Reference
Animate.cpp File Reference
#include <console/ConsoleMouse.h>
#include <iostream>
#include "WinGetOpt.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
References char_to_dir(), getopt(), i, in, ConsoleMouse::inst(), Mouse::internalForward(), Mouse::internalTurnToFace(), maze, optarg, opterr, optind, optopt, Mouse::print_maze_mouse(), and ConsoleMouse::seedMaze().