SmartMouse_2018: ArrayCwiseUnaryOps.h File Reference
ArrayCwiseUnaryOps.h File Reference
Typedefs
typedef CwiseUnaryOp< internal::scalar_abs_op< Scalar >, const Derived > AbsReturnType
typedef CwiseUnaryOp< internal::scalar_arg_op< Scalar >, const Derived > ArgReturnType
typedef CwiseUnaryOp< internal::scalar_abs2_op< Scalar >, const Derived > Abs2ReturnType
typedef CwiseUnaryOp< internal::scalar_sqrt_op< Scalar >, const Derived > SqrtReturnType
typedef CwiseUnaryOp< internal::scalar_rsqrt_op< Scalar >, const Derived > RsqrtReturnType
typedef CwiseUnaryOp< internal::scalar_sign_op< Scalar >, const Derived > SignReturnType
typedef CwiseUnaryOp< internal::scalar_inverse_op< Scalar >, const Derived > InverseReturnType
typedef CwiseUnaryOp< internal::scalar_boolean_not_op< Scalar >, const Derived > BooleanNotReturnType
typedef CwiseUnaryOp< internal::scalar_exp_op< Scalar >, const Derived > ExpReturnType
typedef CwiseUnaryOp< internal::scalar_expm1_op< Scalar >, const Derived > Expm1ReturnType
typedef CwiseUnaryOp< internal::scalar_log_op< Scalar >, const Derived > LogReturnType
typedef CwiseUnaryOp< internal::scalar_log1p_op< Scalar >, const Derived > Log1pReturnType
typedef CwiseUnaryOp< internal::scalar_log10_op< Scalar >, const Derived > Log10ReturnType
typedef CwiseUnaryOp< internal::scalar_cos_op< Scalar >, const Derived > CosReturnType
typedef CwiseUnaryOp< internal::scalar_sin_op< Scalar >, const Derived > SinReturnType
typedef CwiseUnaryOp< internal::scalar_tan_op< Scalar >, const Derived > TanReturnType
typedef CwiseUnaryOp< internal::scalar_acos_op< Scalar >, const Derived > AcosReturnType
typedef CwiseUnaryOp< internal::scalar_asin_op< Scalar >, const Derived > AsinReturnType
typedef CwiseUnaryOp< internal::scalar_atan_op< Scalar >, const Derived > AtanReturnType
typedef CwiseUnaryOp< internal::scalar_tanh_op< Scalar >, const Derived > TanhReturnType
typedef CwiseUnaryOp< internal::scalar_sinh_op< Scalar >, const Derived > SinhReturnType
typedef CwiseUnaryOp< internal::scalar_cosh_op< Scalar >, const Derived > CoshReturnType
typedef CwiseUnaryOp< internal::scalar_square_op< Scalar >, const Derived > SquareReturnType
typedef CwiseUnaryOp< internal::scalar_cube_op< Scalar >, const Derived > CubeReturnType
typedef CwiseUnaryOp< internal::scalar_round_op< Scalar >, const Derived > RoundReturnType
typedef CwiseUnaryOp< internal::scalar_floor_op< Scalar >, const Derived > FloorReturnType
typedef CwiseUnaryOp< internal::scalar_ceil_op< Scalar >, const Derived > CeilReturnType
typedef CwiseUnaryOp< internal::scalar_isnan_op< Scalar >, const Derived > IsNaNReturnType
typedef CwiseUnaryOp< internal::scalar_isinf_op< Scalar >, const Derived > IsInfReturnType
typedef CwiseUnaryOp< internal::scalar_isfinite_op< Scalar >, const Derived > IsFiniteReturnType
typedef CwiseUnaryOp< internal::scalar_lgamma_op< Scalar >, const Derived > LgammaReturnType
typedef CwiseUnaryOp< internal::scalar_digamma_op< Scalar >, const Derived > DigammaReturnType
typedef CwiseUnaryOp< internal::scalar_erf_op< Scalar >, const Derived > ErfReturnType
typedef CwiseUnaryOp< internal::scalar_erfc_op< Scalar >, const Derived > ErfcReturnType
Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const AbsReturnType abs () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const ArgReturnType arg () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Abs2ReturnType abs2 () const
EIGEN_DEVICE_FUNC const ExpReturnType exp () const
EIGEN_DEVICE_FUNC const Expm1ReturnType expm1 () const
EIGEN_DEVICE_FUNC const LogReturnType log () const
EIGEN_DEVICE_FUNC const Log1pReturnType log1p () const
EIGEN_DEVICE_FUNC const Log10ReturnType log10 () const
EIGEN_DEVICE_FUNC const SqrtReturnType sqrt () const
EIGEN_DEVICE_FUNC const RsqrtReturnType rsqrt () const
EIGEN_DEVICE_FUNC const SignReturnType sign () const
EIGEN_DEVICE_FUNC const CosReturnType cos () const
EIGEN_DEVICE_FUNC const SinReturnType sin () const
EIGEN_DEVICE_FUNC const TanReturnType tan () const
EIGEN_DEVICE_FUNC const AtanReturnType atan () const
EIGEN_DEVICE_FUNC const AcosReturnType acos () const
EIGEN_DEVICE_FUNC const AsinReturnType asin () const
EIGEN_DEVICE_FUNC const TanhReturnType tanh () const
EIGEN_DEVICE_FUNC const SinhReturnType sinh () const
EIGEN_DEVICE_FUNC const CoshReturnType cosh () const
EIGEN_DEVICE_FUNC const InverseReturnType inverse () const
EIGEN_DEVICE_FUNC const SquareReturnType square () const
EIGEN_DEVICE_FUNC const CubeReturnType cube () const
EIGEN_DEVICE_FUNC const RoundReturnType round () const
EIGEN_DEVICE_FUNC const FloorReturnType floor () const
EIGEN_DEVICE_FUNC const CeilReturnType ceil () const
EIGEN_DEVICE_FUNC const IsNaNReturnType isNaN () const
EIGEN_DEVICE_FUNC const IsInfReturnType isInf () const
EIGEN_DEVICE_FUNC const IsFiniteReturnType isFinite () const
EIGEN_DEVICE_FUNC const BooleanNotReturnType operator! () const
EIGEN_DEVICE_FUNC const LgammaReturnType lgamma () const
EIGEN_DEVICE_FUNC const DigammaReturnType digamma () const
EIGEN_DEVICE_FUNC const ErfReturnType erf () const
EIGEN_DEVICE_FUNC const ErfcReturnType erfc () const
Typedef Documentation
typedef CwiseUnaryOp<internal::scalar_abs2_op<Scalar>, const Derived> Abs2ReturnType
typedef CwiseUnaryOp<internal::scalar_abs_op<Scalar>, const Derived> AbsReturnType
typedef CwiseUnaryOp<internal::scalar_acos_op<Scalar>, const Derived> AcosReturnType
typedef CwiseUnaryOp<internal::scalar_arg_op<Scalar>, const Derived> ArgReturnType
typedef CwiseUnaryOp<internal::scalar_asin_op<Scalar>, const Derived> AsinReturnType
typedef CwiseUnaryOp<internal::scalar_atan_op<Scalar>, const Derived> AtanReturnType
typedef CwiseUnaryOp<internal::scalar_boolean_not_op<Scalar>, const Derived> BooleanNotReturnType
typedef CwiseUnaryOp<internal::scalar_ceil_op<Scalar>, const Derived> CeilReturnType
typedef CwiseUnaryOp<internal::scalar_cosh_op<Scalar>, const Derived> CoshReturnType
typedef CwiseUnaryOp<internal::scalar_cos_op<Scalar>, const Derived> CosReturnType
typedef CwiseUnaryOp<internal::scalar_cube_op<Scalar>, const Derived> CubeReturnType
typedef CwiseUnaryOp<internal::scalar_digamma_op<Scalar>, const Derived> DigammaReturnType
typedef CwiseUnaryOp<internal::scalar_erfc_op<Scalar>, const Derived> ErfcReturnType
typedef CwiseUnaryOp<internal::scalar_erf_op<Scalar>, const Derived> ErfReturnType
typedef CwiseUnaryOp<internal::scalar_expm1_op<Scalar>, const Derived> Expm1ReturnType
typedef CwiseUnaryOp<internal::scalar_exp_op<Scalar>, const Derived> ExpReturnType
typedef CwiseUnaryOp<internal::scalar_floor_op<Scalar>, const Derived> FloorReturnType
typedef CwiseUnaryOp<internal::scalar_inverse_op<Scalar>, const Derived> InverseReturnType
typedef CwiseUnaryOp<internal::scalar_isfinite_op<Scalar>, const Derived> IsFiniteReturnType
typedef CwiseUnaryOp<internal::scalar_isinf_op<Scalar>, const Derived> IsInfReturnType
typedef CwiseUnaryOp<internal::scalar_isnan_op<Scalar>, const Derived> IsNaNReturnType
typedef CwiseUnaryOp<internal::scalar_lgamma_op<Scalar>, const Derived> LgammaReturnType
typedef CwiseUnaryOp<internal::scalar_log10_op<Scalar>, const Derived> Log10ReturnType
typedef CwiseUnaryOp<internal::scalar_log1p_op<Scalar>, const Derived> Log1pReturnType
typedef CwiseUnaryOp<internal::scalar_log_op<Scalar>, const Derived> LogReturnType
typedef CwiseUnaryOp<internal::scalar_round_op<Scalar>, const Derived> RoundReturnType
typedef CwiseUnaryOp<internal::scalar_rsqrt_op<Scalar>, const Derived> RsqrtReturnType
typedef CwiseUnaryOp<internal::scalar_sign_op<Scalar>, const Derived> SignReturnType
typedef CwiseUnaryOp<internal::scalar_sinh_op<Scalar>, const Derived> SinhReturnType
typedef CwiseUnaryOp<internal::scalar_sin_op<Scalar>, const Derived> SinReturnType
typedef CwiseUnaryOp<internal::scalar_sqrt_op<Scalar>, const Derived> SqrtReturnType
typedef CwiseUnaryOp<internal::scalar_square_op<Scalar>, const Derived> SquareReturnType
typedef CwiseUnaryOp<internal::scalar_tanh_op<Scalar>, const Derived> TanhReturnType
typedef CwiseUnaryOp<internal::scalar_tan_op<Scalar>, const Derived> TanReturnType
Function Documentation
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const AbsReturnType abs () const
Returns
an expression of the coefficient-wise absolute value of *this
Example:
Output:
See also
Math functions, abs2()
References EIGEN_STRONG_INLINE.
Referenced by Eigen::LDLT< _MatrixType, _UpLo >::_solve_impl(), Eigen::HouseholderQR< _MatrixType >::absDeterminant(), Eigen::FullPivHouseholderQR< _MatrixType >::absDeterminant(), Eigen::ColPivHouseholderQR< _MatrixType >::absDeterminant(), Eigen::SparseLU< _MatrixType, _OrderingType >::absDeterminant(), Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::absDistance(), Eigen::QuaternionBase< Derived >::angularDistance(), Eigen::internal::bicgstab(), Eigen::internal::blueNorm_impl(), Eigen::BDCSVD< _MatrixType >::compute(), Eigen::GeneralizedEigenSolver< _MatrixType >::compute(), Eigen::EigenSolver< _MatrixType >::compute(), Eigen::SelfAdjointEigenSolver< _MatrixType >::compute(), Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::compute(), Eigen::RealSchur< _MatrixType >::computeFromHessenberg(), Eigen::internal::computeFromTridiagonal_impl(), Eigen::FullPivHouseholderQR< _MatrixType >::computeInPlace(), Eigen::ColPivHouseholderQR< _MatrixType >::computeInPlace(), Eigen::RealSchur< _MatrixType >::computeShift(), Eigen::ComplexSchur< _MatrixType >::computeShift(), Eigen::BDCSVD< _MatrixType >::computeSingVals(), Eigen::BDCSVD< _MatrixType >::computeSVDofM(), Eigen::internal::conjugate_gradient(), Time::Correct(), Eigen::BDCSVD< _MatrixType >::deflation(), Eigen::BDCSVD< _MatrixType >::deflation43(), Eigen::BDCSVD< _MatrixType >::deflation44(), Eigen::BDCSVD< _MatrixType >::divide(), Eigen::EigenSolver< _MatrixType >::doComputeEigenvectors(), Eigen::internal::kernel_retval< FullPivLU< _MatrixType > >::evalTo(), Eigen::internal::image_retval< FullPivLU< _MatrixType > >::evalTo(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 3, false >::extract_kernel(), Eigen::SparseQR< _MatrixType, _OrderingType >::factorize(), Eigen::IncompleteLUT< _Scalar, _StorageIndex >::factorize(), Eigen::RealQZ< _MatrixType >::findSmallDiagEntry(), Eigen::RealQZ< _MatrixType >::findSmallSubdiagEntry(), Eigen::RealSchur< _MatrixType >::findSmallSubdiagEntry(), Eigen::RealSchur< _MatrixType >::initFrancisQRStep(), Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::intersection(), Eigen::MatrixBase< Derived >::isDiagonal(), Eigen::MatrixBase< Derived >::isLowerTriangular(), Eigen::MatrixBase< Derived >::isUpperTriangular(), Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::Iterator::Iterator(), Eigen::internal::least_square_conjugate_gradient(), Eigen::SparseLU< _MatrixType, _OrderingType >::logAbsDeterminant(), Eigen::JacobiRotation< Scalar >::makeGivens(), Eigen::JacobiRotation< Scalar >::makeJacobi(), Eigen::internal::scalar_abs_op< Scalar >::operator()(), Eigen::internal::abs_knowing_score< Scalar, typename >::operator()(), Eigen::internal::scalar_sign_op< Scalar, true >::operator()(), Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::Iterator::operator++(), Eigen::AngleAxis< _Scalar >::operator=(), Eigen::internal::pabs(), Eigen::PardisoImpl< PardisoLU< MatrixType > >::pardisoInit(), Eigen::BDCSVD< _MatrixType >::perturbCol0(), Eigen::internal::SparseLUImpl< Scalar, StorageIndex >::pivotL(), Eigen::internal::QuickSplit(), Eigen::SVDBase< BDCSVD< _MatrixType > >::rank(), Eigen::FullPivHouseholderQR< TransposeTypeWithSameStorageOrder >::rank(), Eigen::ColPivHouseholderQR< TransposeTypeWithSameStorageOrder >::rank(), Eigen::FullPivLU< _MatrixType >::rank(), Eigen::internal::real_2x2_jacobi_svd(), Eigen::internal::compute_inverse_and_det_with_check< MatrixType, ResultType, 1 >::run(), Eigen::internal::compute_inverse_and_det_with_check< MatrixType, ResultType, 2 >::run(), Eigen::internal::compute_inverse_and_det_with_check< MatrixType, ResultType, 3 >::run(), Eigen::internal::compute_inverse_and_det_with_check< MatrixType, ResultType, 4 >::run(), Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::run(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 2, false >::run(), Eigen::QuaternionBase< Derived >::slerp(), Eigen::RealQZ< _MatrixType >::splitOffTwoRows(), Eigen::RealSchur< _MatrixType >::splitOffTwoRows(), Eigen::MatrixBase< Derived >::stableNorm(), Eigen::RealQZ< _MatrixType >::step(), Eigen::internal::tridiagonal_qr_step(), Eigen::internal::unary_evaluator< SparseView< Product< Lhs, Rhs, Options > >, IteratorBased >::unary_evaluator(), and Eigen::internal::ldlt_inplace< Lower >::unblocked().
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Abs2ReturnType abs2 () const
Returns
an expression of the coefficient-wise squared absolute value of *this
Example:
Output:
See also
Math functions, abs(), square()
Referenced by Eigen::internal::blueNorm_impl(), Eigen::ColPivHouseholderQR< _MatrixType >::computeInPlace(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 2, false >::computeRoots(), Eigen::BDCSVD< _MatrixType >::deflation43(), Eigen::BDCSVD< _MatrixType >::deflation44(), Eigen::SimplicialLLT< _MatrixType, _UpLo, _Ordering >::determinant(), Eigen::SimplicialCholesky< _MatrixType, _UpLo, _Ordering >::determinant(), Eigen::SparseQR< _MatrixType, _OrderingType >::factorize(), Eigen::LeastSquareDiagonalPreconditioner< _Scalar >::factorize(), Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::factorize(), Eigen::IncompleteLUT< _Scalar, _StorageIndex >::factorize(), Eigen::MatrixBase< Derived >::isOrthogonal(), Eigen::internal::llt_rank_update_lower(), Eigen::JacobiRotation< Scalar >::makeGivens(), Eigen::MatrixBase< Derived >::makeHouseholder(), Eigen::JacobiRotation< Scalar >::makeJacobi(), Eigen::internal::scalar_abs2_op< Scalar >::operator()(), Eigen::internal::real_2x2_jacobi_svd(), Eigen::internal::isMuchSmallerThan_object_selector< Derived, OtherDerived, is_integer >::run(), Eigen::internal::isMuchSmallerThan_scalar_selector< Derived, is_integer >::run(), Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::run(), Eigen::internal::tridiagonalization_inplace_selector< MatrixType, 3, false >::run(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 2, false >::run(), Eigen::BDCSVD< _MatrixType >::secularEq(), Eigen::internal::stable_norm_kernel(), Eigen::internal::tridiagonal_qr_step(), and Eigen::internal::ldlt_inplace< Lower >::updateInPlace().
EIGEN_DEVICE_FUNC const AcosReturnType acos () const inline
Returns
an expression of the coefficient-wise arc cosine of *this.
Example:
Output:
See also
Math functions, cos(), asin()
Referenced by Eigen::internal::scalar_acos_op< Scalar >::operator()(), Eigen::internal::pacos(), and Eigen::QuaternionBase< Derived >::slerp().
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const ArgReturnType arg () const
Returns
an expression of the coefficient-wise phase angle of *this
Example:
Output:
See also
abs()
References EIGEN_STRONG_INLINE.
Referenced by ArgumentParser::addArgument(), ArgumentParser::addFinalArgument(), ArgumentParser::count(), Eigen::internal::scalar_arg_op< Scalar >::operator()(), Eigen::internal::parg(), Encoder::update(), and ArgumentParser::usage().
EIGEN_DEVICE_FUNC const AsinReturnType asin () const inline
Returns
an expression of the coefficient-wise arc sine of *this.
Example:
Output:
See also
Math functions, sin(), acos()
Referenced by Eigen::internal::scalar_asin_op< Scalar >::operator()(), and Eigen::internal::pasin().
EIGEN_DEVICE_FUNC const AtanReturnType atan () const inline
Returns
an expression of the coefficient-wise arc tan of *this.
Example:
Output:
See also
Math functions, tan(), asin(), acos()
Referenced by Eigen::internal::scalar_atan_op< Scalar >::operator()(), and Eigen::internal::patan().
EIGEN_DEVICE_FUNC const CeilReturnType ceil () const inline
Returns
an expression of the coefficient-wise ceil of *this.
Example:
Output:
See also
Math functions, floor(), round()
Referenced by Server::ComputeMaxSensorRange(), KinematicController::getLocalPose(), Eigen::internal::scalar_ceil_op< Scalar >::operator()(), Eigen::internal::pceil(), and Eigen::internal::default_digits10_impl< T, false, false >::run().
EIGEN_DEVICE_FUNC const CosReturnType cos () const inline
Returns
an expression of the coefficient-wise cosine of *this.
This function computes the coefficient-wise cosine. The function MatrixBase::cos() in the unsupported module MatrixFunctions computes the matrix cosine.
Example:
Output:
See also
Math functions, sin(), acos()
Referenced by Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 3, false >::computeRoots(), Server::ComputeSensorDistToWall(), Server::ComputeSensorRange(), KinematicController::estimate_pose(), Eigen::MatrixBase< Derived >::eulerAngles(), KinematicController::forwardKinematics(), main(), TrajectoryPlanner::non_holonomic_constraint(), Eigen::internal::scalar_cos_op< Scalar >::operator()(), Eigen::QuaternionBase< Derived >::operator=(), Eigen::internal::pcos(), KinematicController::poseOfToNthEdge(), KinematicController::run(), Eigen::Rotation2D< _Scalar >::toRotationMatrix(), Eigen::AngleAxis< _Scalar >::toRotationMatrix(), TrajectoryPlanner::trig_constraint(), and Eigen::Quaternion< _Scalar, _Options >::UnitRandom().
EIGEN_DEVICE_FUNC const CoshReturnType cosh () const inline
Returns
an expression of the coefficient-wise hyperbolic cos of *this.
Example:
Output:
See also
Math functions, tan(), sinh(), cosh()
Referenced by Eigen::internal::scalar_cosh_op< Scalar >::operator()(), and Eigen::internal::pcosh().
EIGEN_DEVICE_FUNC const CubeReturnType cube () const inline
Returns
an expression of the coefficient-wise cube of *this.
Example:
Output:
See also
Math functions, square(), pow()
EIGEN_DEVICE_FUNC const DigammaReturnType digamma () const inline
Returns
an expression of the coefficient-wise digamma (psi, derivative of lgamma).
Note
This function supports only float and double scalar types. To support other scalar types, the user has to provide implementations of digamma(T) for any scalar type T to be supported.
See also
Math functions, Eigen::digamma(), Eigen::polygamma(), lgamma()
EIGEN_DEVICE_FUNC const ErfReturnType erf () const inline
Returns
an expression of the coefficient-wise Gauss error function of *this.
Example:
Output:
Note
This function supports only float and double scalar types in c++11 mode. To support other scalar types, or float/double in non c++11 mode, the user has to provide implementations of erf(T) for any scalar type T to be supported.
See also
Math functions, erfc()
EIGEN_DEVICE_FUNC const ErfcReturnType erfc () const inline
Returns
an expression of the coefficient-wise Complementary error function of *this.
Example:
Output:
Note
This function supports only float and double scalar types in c++11 mode. To support other scalar types, or float/double in non c++11 mode, the user has to provide implementations of erfc(T) for any scalar type T to be supported.
See also
Math functions, erf()
EIGEN_DEVICE_FUNC const ExpReturnType exp () const inline
Returns
an expression of the coefficient-wise exponential of *this.
This function computes the coefficient-wise exponential. The function MatrixBase::exp() in the unsupported module MatrixFunctions computes the matrix exponential.
Example:
Output:
See also
Math functions, pow(), log(), sin(), cos()
Referenced by Eigen::CholmodBase< _MatrixType, _UpLo, CholmodSimplicialLLT< _MatrixType, _UpLo > >::determinant(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::from_cbor_internal(), Eigen::internal::scalar_exp_op< Scalar >::operator()(), and Eigen::internal::pexp().
EIGEN_DEVICE_FUNC const Expm1ReturnType expm1 () const inline
Returns
an expression of the coefficient-wise exponential of *this minus 1.
In exact arithmetic, x.expm1() is equivalent to x.exp() - 1, however, with finite precision, this function is much more accurate when x is close to zero.
See also
Math functions, exp()
Referenced by Eigen::half_impl::expm1(), Eigen::internal::scalar_expm1_op< Scalar >::operator()(), and Eigen::internal::pexpm1().
EIGEN_DEVICE_FUNC const FloorReturnType floor () const inline
Returns
an expression of the coefficient-wise floor of *this.
Example:
Output:
See also
Math functions, ceil(), round()
Referenced by KinematicController::getLocalPose(), Time::GetWallTime(), smartmouse::math::MyMod(), Eigen::internal::scalar_floor_op< Scalar >::operator()(), Eigen::internal::pfloor(), Time::Set(), and Time::Time().
EIGEN_DEVICE_FUNC const InverseReturnType inverse () const inline
Returns
an expression of the coefficient-wise inverse of *this.
Example:
Output:
See also
operator/(), operator*()
Referenced by cwiseSign(), Eigen::QuaternionBase< Quaternion< _Scalar, _Options > >::dot(), and Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator*=().
EIGEN_DEVICE_FUNC const IsFiniteReturnType isFinite () const inline
Returns
an expression of the coefficient-wise isfinite of *this.
Example:
Output:
See also
isnan(), isinf()
EIGEN_DEVICE_FUNC const IsInfReturnType isInf () const inline
Returns
an expression of the coefficient-wise isinf of *this.
Example:
Output:
See also
isnan(), isfinite()
EIGEN_DEVICE_FUNC const IsNaNReturnType isNaN () const inline
Returns
an expression of the coefficient-wise isnan of *this.
Example:
Output:
See also
isfinite(), isinf()
EIGEN_DEVICE_FUNC const LgammaReturnType lgamma () const inline
Returns
an expression of the coefficient-wise ln(|gamma(*this)|).
Example:
Output:
Note
This function supports only float and double scalar types in c++11 mode. To support other scalar types, or float/double in non c++11 mode, the user has to provide implementations of lgamma(T) for any scalar type T to be supported.
See also
Math functions, digamma()
EIGEN_DEVICE_FUNC const LogReturnType log () const inline
Returns
an expression of the coefficient-wise logarithm of *this.
This function computes the coefficient-wise logarithm. The function MatrixBase::log() in the unsupported module MatrixFunctions computes the matrix logarithm.
Example:
Output:
See also
Math functions, log()
Referenced by Eigen::SparseLU< _MatrixType, _OrderingType >::logAbsDeterminant(), Eigen::CholmodBase< _MatrixType, _UpLo, CholmodSimplicialLLT< _MatrixType, _UpLo > >::logDeterminant(), Eigen::internal::scalar_log_op< Scalar >::operator()(), and Eigen::internal::plog().
EIGEN_DEVICE_FUNC const Log10ReturnType log10 () const inline
Returns
an expression of the coefficient-wise base-10 logarithm of *this.
This function computes the coefficient-wise base-10 logarithm.
Example:
Output:
See also
Math functions, log()
Referenced by Eigen::internal::scalar_log10_op< Scalar >::operator()(), Eigen::internal::plog10(), and Eigen::internal::default_digits10_impl< T, false, false >::run().
EIGEN_DEVICE_FUNC const Log1pReturnType log1p () const inline
Returns
an expression of the coefficient-wise logarithm of 1 plus *this.
In exact arithmetic, x.log() is equivalent to (x+1).log(), however, with finite precision, this function is much more accurate when x is close to zero.
See also
Math functions, log()
Referenced by Eigen::half_impl::log1p(), Eigen::internal::scalar_log1p_op< Scalar >::operator()(), and Eigen::internal::plog1p().
EIGEN_DEVICE_FUNC const BooleanNotReturnType operator! () const inline
Returns
an expression of the coefficient-wise ! operator of *this
Warning
this operator is for expression of bool only.
Example:
Output:
See also
operator!=()
References EIGEN_STATIC_ASSERT.
EIGEN_DEVICE_FUNC const RoundReturnType round () const inline
Returns
an expression of the coefficient-wise round of *this.
Example:
Output:
See also
Math functions, ceil(), floor()
Referenced by Time::GetWallTime(), Eigen::internal::scalar_round_op< Scalar >::operator()(), Eigen::internal::pround(), and Time::Set().
EIGEN_DEVICE_FUNC const RsqrtReturnType rsqrt () const inline
Returns
an expression of the coefficient-wise inverse square root of *this.
This function computes the coefficient-wise inverse square root.
Example:
Output:
See also
pow(), square()
EIGEN_DEVICE_FUNC const SignReturnType sign () const inline
Returns
an expression of the coefficient-wise signum of *this.
This function computes the coefficient-wise signum.
Example:
Output:
See also
pow(), square()
Referenced by cwiseSqrt(), and Eigen::half_impl::float_to_half_rtne().
EIGEN_DEVICE_FUNC const SinReturnType sin () const inline
Returns
an expression of the coefficient-wise sine of *this.
This function computes the coefficient-wise sine. The function MatrixBase::sin() in the unsupported module MatrixFunctions computes the matrix sine.
Example:
Output:
See also
Math functions, cos(), asin()
Referenced by IRConverter::calibrate(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 3, false >::computeRoots(), Server::ComputeSensorDistToWall(), Server::ComputeSensorRange(), KinematicController::estimate_pose(), Eigen::MatrixBase< Derived >::eulerAngles(), KinematicController::forwardKinematics(), main(), TrajectoryPlanner::non_holonomic_constraint(), Eigen::internal::scalar_sin_op< Scalar >::operator()(), Eigen::QuaternionBase< Derived >::operator=(), KinematicController::poseOfToNthEdge(), Eigen::internal::psin(), Eigen::QuaternionBase< Derived >::slerp(), Eigen::Rotation2D< _Scalar >::toRotationMatrix(), Eigen::AngleAxis< _Scalar >::toRotationMatrix(), TrajectoryPlanner::TrajectoryPlanner(), TrajectoryPlanner::trig_constraint(), and Eigen::Quaternion< _Scalar, _Options >::UnitRandom().
EIGEN_DEVICE_FUNC const SinhReturnType sinh () const inline
Returns
an expression of the coefficient-wise hyperbolic sin of *this.
Example:
Output:
See also
Math functions, sin(), tanh(), cosh()
Referenced by Eigen::internal::scalar_sinh_op< Scalar >::operator()(), and Eigen::internal::psinh().
EIGEN_DEVICE_FUNC const SqrtReturnType sqrt () const inline
Returns
an expression of the coefficient-wise square root of *this.
This function computes the coefficient-wise square root. The function MatrixBase::sqrt() in the unsupported module MatrixFunctions computes the matrix square root.
Example:
Output:
See also
Math functions, pow(), square()
Referenced by Eigen::internal::bicgstab(), Eigen::internal::blueNorm_impl(), Eigen::GeneralizedEigenSolver< _MatrixType >::compute(), Eigen::EigenSolver< _MatrixType >::compute(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 3, false >::computeRoots(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 2, false >::computeRoots(), Eigen::RealSchur< _MatrixType >::computeShift(), Eigen::ComplexSchur< _MatrixType >::computeShift(), Eigen::internal::conjugate_gradient(), Eigen::BDCSVD< _MatrixType >::deflation(), Eigen::BDCSVD< _MatrixType >::deflation43(), Eigen::BDCSVD< _MatrixType >::deflation44(), Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::distance(), distance_needed(), Eigen::BDCSVD< _MatrixType >::divide(), KinematicController::estimate_pose(), Eigen::AlignedBox< _Scalar, _AmbientDim >::exteriorDistance(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 3, false >::extract_kernel(), Eigen::SparseQR< _MatrixType, _OrderingType >::factorize(), Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::factorize(), Eigen::IncompleteLUT< _Scalar, _StorageIndex >::factorize(), Eigen::SimplicialCholeskyBase< Derived >::factorize_preordered(), Eigen::internal::least_square_conjugate_gradient(), Eigen::internal::llt_rank_update_lower(), Eigen::JacobiRotation< Scalar >::makeGivens(), Eigen::MatrixBase< Derived >::makeHouseholder(), Eigen::JacobiRotation< Scalar >::makeJacobi(), Eigen::internal::minimum_degree_ordering(), Eigen::SparseMatrixBase< Derived >::norm(), Eigen::internal::scalar_hypot_op< Scalar, Scalar >::operator()(), Eigen::MatrixBase< Derived >::operatorNorm(), Eigen::BDCSVD< _MatrixType >::perturbCol0(), Eigen::internal::psqrt(), Eigen::internal::real_2x2_jacobi_svd(), Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::run(), Eigen::internal::tridiagonalization_inplace_selector< MatrixType, 3, false >::run(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 2, false >::run(), Eigen::internal::quaternionbase_assign_impl< Other, 3, 3 >::run(), Eigen::QuaternionBase< Derived >::setFromTwoVectors(), Eigen::RealQZ< _MatrixType >::splitOffTwoRows(), Eigen::RealSchur< _MatrixType >::splitOffTwoRows(), Eigen::MatrixBase< Derived >::stableNorm(), Eigen::internal::llt_inplace< Scalar, Lower >::unblocked(), and Eigen::Quaternion< _Scalar, _Options >::UnitRandom().
EIGEN_DEVICE_FUNC const SquareReturnType square () const inline
Returns
an expression of the coefficient-wise square of *this.
Example:
Output:
See also
Math functions, abs2(), cube(), pow()
Referenced by cwiseAbs2().
EIGEN_DEVICE_FUNC const TanReturnType tan () const inline
Returns
an expression of the coefficient-wise tan of *this.
Example:
Output:
See also
Math functions, cos(), sin()
Referenced by KinematicController::estimate_pose(), Eigen::internal::scalar_tan_op< Scalar >::operator()(), and Eigen::internal::ptan().
EIGEN_DEVICE_FUNC const TanhReturnType tanh () const inline
Returns
an expression of the coefficient-wise hyperbolic tan of *this.
Example:
Output:
See also
Math functions, tan(), sinh(), cosh()
Referenced by Eigen::internal::scalar_tanh_op< Scalar >::operator()(), and Eigen::internal::ptanh().