SmartMouse_2018: BlockMethods.h File Reference
BlockMethods.h File Reference
Classes
struct NColsBlockXpr< N >
struct ConstNColsBlockXpr< N >
struct NRowsBlockXpr< N >
struct ConstNRowsBlockXpr< N >
struct FixedBlockXpr< Rows, Cols >
struct ConstFixedBlockXpr< Rows, Cols >
struct FixedSegmentReturnType< Size >
struct ConstFixedSegmentReturnType< Size >
Typedefs
typedef Block< Derived, internal::traits< Derived >::RowsAtCompileTime, 1,!IsRowMajor > ColXpr
typedef const Block< const Derived, internal::traits< Derived >::RowsAtCompileTime, 1,!IsRowMajor > ConstColXpr
typedef Block< Derived, 1, internal::traits< Derived >::ColsAtCompileTime, IsRowMajor > RowXpr
typedef const Block< const Derived, 1, internal::traits< Derived >::ColsAtCompileTime, IsRowMajor > ConstRowXpr
typedef Block< Derived, internal::traits< Derived >::RowsAtCompileTime, Dynamic,!IsRowMajor > ColsBlockXpr
typedef const Block< const Derived, internal::traits< Derived >::RowsAtCompileTime, Dynamic,!IsRowMajor > ConstColsBlockXpr
typedef Block< Derived, Dynamic, internal::traits< Derived >::ColsAtCompileTime, IsRowMajor > RowsBlockXpr
typedef const Block< const Derived, Dynamic, internal::traits< Derived >::ColsAtCompileTime, IsRowMajor > ConstRowsBlockXpr
typedef Block< Derived > BlockXpr
typedef const Block< const Derived > ConstBlockXpr
typedef VectorBlock< Derived > SegmentReturnType
typedef const VectorBlock< const Derived > ConstSegmentReturnType
Functions
template<typename NRowsType , typename NColsType >
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type block (Index startRow, Index startCol, NRowsType blockRows, NColsType blockCols)
template<typename NRowsType , typename NColsType >
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type block (Index startRow, Index startCol, NRowsType blockRows, NColsType blockCols) const
This is the const version of block(Index,Index,NRowsType,NColsType)
template<typename NRowsType , typename NColsType >
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type topRightCorner (NRowsType cRows, NColsType cCols)
template<typename NRowsType , typename NColsType >
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type topRightCorner (NRowsType cRows, NColsType cCols) const
This is the const version of topRightCorner(NRowsType, NColsType).
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type topRightCorner ()
template<int CRows, int CCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type topRightCorner () const
This is the const version of topRightCorner<int, int>().
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type topRightCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
const ConstFixedBlockXpr< CRows, CCols >::Type topRightCorner (Index cRows, Index cCols) const
This is the const version of topRightCorner<int, int>(Index, Index).
template<typename NRowsType , typename NColsType >
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type topLeftCorner (NRowsType cRows, NColsType cCols)
template<typename NRowsType , typename NColsType >
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type topLeftCorner (NRowsType cRows, NColsType cCols) const
This is the const version of topLeftCorner(Index, Index).
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type topLeftCorner ()
template<int CRows, int CCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type topLeftCorner () const
This is the const version of topLeftCorner<int, int>().
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type topLeftCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
const ConstFixedBlockXpr< CRows, CCols >::Type topLeftCorner (Index cRows, Index cCols) const
This is the const version of topLeftCorner<int, int>(Index, Index).
template<typename NRowsType , typename NColsType >
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type bottomRightCorner (NRowsType cRows, NColsType cCols)
template<typename NRowsType , typename NColsType >
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type bottomRightCorner (NRowsType cRows, NColsType cCols) const
This is the const version of bottomRightCorner(NRowsType, NColsType).
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type bottomRightCorner ()
template<int CRows, int CCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type bottomRightCorner () const
This is the const version of bottomRightCorner<int, int>().
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type bottomRightCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
const ConstFixedBlockXpr< CRows, CCols >::Type bottomRightCorner (Index cRows, Index cCols) const
This is the const version of bottomRightCorner<int, int>(Index, Index).
template<typename NRowsType , typename NColsType >
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type bottomLeftCorner (NRowsType cRows, NColsType cCols)
template<typename NRowsType , typename NColsType >
EIGEN_DEVICE_FUNC ConstFixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type bottomLeftCorner (NRowsType cRows, NColsType cCols) const
This is the const version of bottomLeftCorner(NRowsType, NColsType).
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type bottomLeftCorner ()
template<int CRows, int CCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type bottomLeftCorner () const
This is the const version of bottomLeftCorner<int, int>().
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type bottomLeftCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
const ConstFixedBlockXpr< CRows, CCols >::Type bottomLeftCorner (Index cRows, Index cCols) const
This is the const version of bottomLeftCorner<int, int>(Index, Index).
template<typename NRowsType >
EIGEN_DEVICE_FUNC NRowsBlockXpr< internal::get_fixed_value< NRowsType >::value >::Type topRows (NRowsType n)
template<typename NRowsType >
EIGEN_DEVICE_FUNC const ConstNRowsBlockXpr< internal::get_fixed_value< NRowsType >::value >::Type topRows (NRowsType n) const
This is the const version of topRows(NRowsType).
template<int N>
EIGEN_DEVICE_FUNC NRowsBlockXpr< N >::Type topRows (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNRowsBlockXpr< N >::Type topRows (Index n=N) const
This is the const version of topRows<int>().
template<typename NRowsType >
EIGEN_DEVICE_FUNC NRowsBlockXpr< internal::get_fixed_value< NRowsType >::value >::Type bottomRows (NRowsType n)
template<typename NRowsType >
EIGEN_DEVICE_FUNC const ConstNRowsBlockXpr< internal::get_fixed_value< NRowsType >::value >::Type bottomRows (NRowsType n) const
This is the const version of bottomRows(NRowsType).
template<int N>
EIGEN_DEVICE_FUNC NRowsBlockXpr< N >::Type bottomRows (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNRowsBlockXpr< N >::Type bottomRows (Index n=N) const
This is the const version of bottomRows<int>().
template<typename NRowsType >
EIGEN_DEVICE_FUNC NRowsBlockXpr< internal::get_fixed_value< NRowsType >::value >::Type middleRows (Index startRow, NRowsType n)
template<typename NRowsType >
EIGEN_DEVICE_FUNC const ConstNRowsBlockXpr< internal::get_fixed_value< NRowsType >::value >::Type middleRows (Index startRow, NRowsType n) const
This is the const version of middleRows(Index,NRowsType).
template<int N>
EIGEN_DEVICE_FUNC NRowsBlockXpr< N >::Type middleRows (Index startRow, Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNRowsBlockXpr< N >::Type middleRows (Index startRow, Index n=N) const
This is the const version of middleRows<int>().
template<typename NColsType >
EIGEN_DEVICE_FUNC NColsBlockXpr< internal::get_fixed_value< NColsType >::value >::Type leftCols (NColsType n)
template<typename NColsType >
EIGEN_DEVICE_FUNC const ConstNColsBlockXpr< internal::get_fixed_value< NColsType >::value >::Type leftCols (NColsType n) const
This is the const version of leftCols(NColsType).
template<int N>
EIGEN_DEVICE_FUNC NColsBlockXpr< N >::Type leftCols (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNColsBlockXpr< N >::Type leftCols (Index n=N) const
This is the const version of leftCols<int>().
template<typename NColsType >
EIGEN_DEVICE_FUNC NColsBlockXpr< internal::get_fixed_value< NColsType >::value >::Type rightCols (NColsType n)
template<typename NColsType >
EIGEN_DEVICE_FUNC const ConstNColsBlockXpr< internal::get_fixed_value< NColsType >::value >::Type rightCols (NColsType n) const
This is the const version of rightCols(NColsType).
template<int N>
EIGEN_DEVICE_FUNC NColsBlockXpr< N >::Type rightCols (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNColsBlockXpr< N >::Type rightCols (Index n=N) const
This is the const version of rightCols<int>().
template<typename NColsType >
EIGEN_DEVICE_FUNC NColsBlockXpr< internal::get_fixed_value< NColsType >::value >::Type middleCols (Index startCol, NColsType numCols)
template<typename NColsType >
EIGEN_DEVICE_FUNC const ConstNColsBlockXpr< internal::get_fixed_value< NColsType >::value >::Type middleCols (Index startCol, NColsType numCols) const
This is the const version of middleCols(Index,NColsType).
template<int N>
EIGEN_DEVICE_FUNC NColsBlockXpr< N >::Type middleCols (Index startCol, Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNColsBlockXpr< N >::Type middleCols (Index startCol, Index n=N) const
This is the const version of middleCols<int>().
template<int NRows, int NCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol)
template<int NRows, int NCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol) const
This is the const version of block<>(Index, Index). */.
template<int NRows, int NCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol, Index blockRows, Index blockCols)
template<int NRows, int NCols>
const ConstFixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol, Index blockRows, Index blockCols) const
This is the const version of block<>(Index, Index, Index, Index).
EIGEN_DEVICE_FUNC ColXpr col (Index i) const
This is the const version of col().
EIGEN_DEVICE_FUNC RowXpr row (Index i) const
This is the const version of row(). */.
template<typename NType >
EIGEN_DEVICE_FUNC FixedSegmentReturnType< internal::get_fixed_value< NType >::value >::Type segment (Index start, NType n)
template<typename NType >
EIGEN_DEVICE_FUNC const ConstFixedSegmentReturnType< internal::get_fixed_value< NType >::value >::Type segment (Index start, NType n) const
This is the const version of segment(Index,NType).
template<typename NType >
EIGEN_DEVICE_FUNC FixedSegmentReturnType< internal::get_fixed_value< NType >::value >::Type head (NType n)
template<typename NType >
EIGEN_DEVICE_FUNC const ConstFixedSegmentReturnType< internal::get_fixed_value< NType >::value >::Type head (NType n) const
This is the const version of head(NType).
template<typename NType >
EIGEN_DEVICE_FUNC FixedSegmentReturnType< internal::get_fixed_value< NType >::value >::Type tail (NType n)
template<typename NType >
EIGEN_DEVICE_FUNC const ConstFixedSegmentReturnType< internal::get_fixed_value< NType >::value >::Type tail (NType n) const
This is the const version of tail(Index).
template<int N>
EIGEN_DEVICE_FUNC FixedSegmentReturnType< N >::Type segment (Index start, Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType< N >::Type segment (Index start, Index n=N) const
This is the const version of segment<int>(Index).
template<int N>
EIGEN_DEVICE_FUNC FixedSegmentReturnType< N >::Type head (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType< N >::Type head (Index n=N) const
This is the const version of head<int>().
template<int N>
EIGEN_DEVICE_FUNC FixedSegmentReturnType< N >::Type tail (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType< N >::Type tail (Index n=N) const
This is the const version of tail<int>.
Typedef Documentation
typedef Block<Derived> BlockXpr
typedef Block<Derived, internal::traits<Derived>::RowsAtCompileTime, Dynamic, !IsRowMajor> ColsBlockXpr
typedef Block<Derived, internal::traits<Derived>::RowsAtCompileTime, 1, !IsRowMajor> ColXpr
typedef const Block<const Derived> ConstBlockXpr
typedef const Block<const Derived, internal::traits<Derived>::RowsAtCompileTime, Dynamic, !IsRowMajor> ConstColsBlockXpr
typedef const Block<const Derived, internal::traits<Derived>::RowsAtCompileTime, 1, !IsRowMajor> ConstColXpr
typedef const Block<const Derived, Dynamic, internal::traits<Derived>::ColsAtCompileTime, IsRowMajor> ConstRowsBlockXpr
typedef const Block<const Derived, 1, internal::traits<Derived>::ColsAtCompileTime, IsRowMajor> ConstRowXpr
typedef const VectorBlock<const Derived> ConstSegmentReturnType
typedef Block<Derived, Dynamic, internal::traits<Derived>::ColsAtCompileTime, IsRowMajor> RowsBlockXpr
typedef Block<Derived, 1, internal::traits<Derived>::ColsAtCompileTime, IsRowMajor> RowXpr
typedef VectorBlock<Derived> SegmentReturnType
Function Documentation
template<typename NRowsType , typename NColsType > EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<internal::get_fixed_value<NRowsType>::value,internal::get_fixed_value<NColsType>::value>::Type block (Index startRow, Index startCol, NRowsType blockRows, NColsType blockCols) inline
Returns
an expression of a block in *this with either dynamic or fixed sizes.
Parameters
startRow the first row in the block
startCol the first column in the block
blockRows number of rows in the block, specified at either run-time or compile-time
blockCols number of columns in the block, specified at either run-time or compile-time
Template Parameters
NRowsType the type of the value handling the number of rows in the block, typically Index.
NColsType the type of the value handling the number of columns in the block, typically Index.
Example using runtime (aka dynamic) sizes:
Output:
{3.4}:
The number of rows blockRows and columns blockCols can also be specified at compile-time by passing Eigen::fix<N>, or Eigen::fix<N>(n) as arguments. In the later case, n plays the role of a runtime fallback value in case N equals Eigen::Dynamic. Here is an example with a fixed number of rows NRows and dynamic number of columns cols:
 mat.block(i,j,fix<NRows>,cols)
This function thus fully covers the features offered by the following overloads block<NRows,NCols>(Index, Index), and block<NRows,NCols>(Index, Index, Index, Index) that are thus obsolete. Indeed, this generic version avoids redundancy, it preserves the argument order, and prevents the need to rely on the template keyword in templated code.
but with less redundancy and more consistency as it does not modify the argument order and seamlessly enable hybrid fixed/dynamic sizes.
Note
Even in the case that the returned expression has dynamic size, in the case when it is applied to a fixed-size matrix, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See also
class Block, fix, fix<N>(int)
References Eigen::internal::get_runtime_value().
Referenced by Eigen::internal::kernel_retval< FullPivLU< _MatrixType > >::evalTo().
template<typename NRowsType , typename NColsType > EIGEN_DEVICE_FUNC const ConstFixedBlockXpr<internal::get_fixed_value<NRowsType>::value,internal::get_fixed_value<NColsType>::value>::Type block (Index startRow, Index startCol, NRowsType blockRows, NColsType blockCols) const inline
This is the const version of block(Index,Index,NRowsType,NColsType)
References EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL, and Eigen::internal::get_runtime_value().
template<int NRows, int NCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<NRows,NCols>::Type block (Index startRow, Index startCol) inline
Returns
a fixed-size expression of a block of *this.
The template parameters NRows and NCols are the number of rows and columns in the block.
Parameters
startRow the first row in the block
startCol the first column in the block
Example:
Output:
Note
The usage of of this overload is discouraged from Eigen 3.4, better used the generic block(Index,Index,NRowsType,NColsType), here is the one-to-one equivalence:
 mat.template block<NRows,NCols>(i,j)  <-->  mat.block(i,j,fix<NRows>,fix<NCols>)
since block is a templated member, the keyword template has to be used if the matrix type is also a template parameter:
 m.template block<3,3>(1,1);
See also
block(Index,Index,NRowsType,NColsType), class Block
template<int NRows, int NCols> EIGEN_DEVICE_FUNC const ConstFixedBlockXpr<NRows,NCols>::Type block (Index startRow, Index startCol) const inline
This is the const version of block<>(Index, Index). */.
References EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL.
template<int NRows, int NCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr<NRows,NCols>::Type block (Index startRow, Index startCol, Index blockRows, Index blockCols) inline
Returns
an expression of a block of *this.
Template Parameters
NRows number of rows in block as specified at compile-time
NCols number of columns in block as specified at compile-time
Parameters
startRow the first row in the block
startCol the first column in the block
blockRows number of rows in block as specified at run-time
blockCols number of columns in block as specified at run-time
This function is mainly useful for blocks where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, blockRows should equal NRows unless NRows is Dynamic, and the same for the number of columns.
Example:
Output:
Note
The usage of of this overload is discouraged from Eigen 3.4, better used the generic block(Index,Index,NRowsType,NColsType), here is the one-to-one complete equivalence:
 mat.template block<NRows,NCols>(i,j,rows,cols)     <-->  mat.block(i,j,fix<NRows>(rows),fix<NCols>(cols))
If we known that, e.g., NRows==Dynamic and NCols!=Dynamic, then the equivalence becomes:
 mat.template block<Dynamic,NCols>(i,j,rows,NCols)  <-->  mat.block(i,j,rows,fix<NCols>)
See also
block(Index,Index,NRowsType,NColsType), class Block
template<int NRows, int NCols> const ConstFixedBlockXpr<NRows,NCols>::Type block (Index startRow, Index startCol, Index blockRows, Index blockCols) const inline
This is the const version of block<>(Index, Index, Index, Index).
References EIGEN_DOC_BLOCK_ADDONS_INNER_PANEL_IF.
template<typename NRowsType , typename NColsType > EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<internal::get_fixed_value<NRowsType>::value,internal::get_fixed_value<NColsType>::value>::Type bottomLeftCorner (NRowsType cRows, NColsType cCols) inline
Returns
an expression of a bottom-left corner of *this with either dynamic or fixed sizes.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Template Parameters
NRowsType the type of the value handling the number of rows in the block, typically Index.
NColsType the type of the value handling the number of columns in the block, typically Index.
Example:
Output:
The number of rows blockRows and columns blockCols can also be specified at compile-time by passing Eigen::fix<N>, or Eigen::fix<N>(n) as arguments. See block() for the details.
See also
block(Index,Index,NRowsType,NColsType), class Block
References Eigen::internal::get_runtime_value().
template<typename NRowsType , typename NColsType > EIGEN_DEVICE_FUNC ConstFixedBlockXpr<internal::get_fixed_value<NRowsType>::value,internal::get_fixed_value<NColsType>::value>::Type bottomLeftCorner (NRowsType cRows, NColsType cCols) const inline
This is the const version of bottomLeftCorner(NRowsType, NColsType).
References EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL, and Eigen::internal::get_runtime_value().
template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<CRows,CCols>::Type bottomLeftCorner () inline
Returns
an expression of a fixed-size bottom-left corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Output:
See also
block(Index,Index,NRowsType,NColsType), class Block
template<int CRows, int CCols> EIGEN_DEVICE_FUNC const ConstFixedBlockXpr<CRows,CCols>::Type bottomLeftCorner () const inline
This is the const version of bottomLeftCorner<int, int>().
References EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL.
template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr<CRows,CCols>::Type bottomLeftCorner (Index cRows, Index cCols) inline
Returns
an expression of a bottom-left corner of *this.
Template Parameters
CRows number of rows in corner as specified at compile-time
CCols number of columns in corner as specified at compile-time
Parameters
cRows number of rows in corner as specified at run-time
cCols number of columns in corner as specified at run-time
This function is mainly useful for corners where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, cRows should equal CRows unless CRows is Dynamic, and the same for the number of columns.
Example:
Output:
See also
class Block
template<int CRows, int CCols> const ConstFixedBlockXpr<CRows,CCols>::Type bottomLeftCorner (Index cRows, Index cCols) const inline
This is the const version of bottomLeftCorner<int, int>(Index, Index).
References EIGEN_DOC_BLOCK_ADDONS_INNER_PANEL_IF, and row().
template<typename NRowsType , typename NColsType > EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<internal::get_fixed_value<NRowsType>::value,internal::get_fixed_value<NColsType>::value>::Type bottomRightCorner (NRowsType cRows, NColsType cCols) inline
Returns
an expression of a bottom-right corner of *this with either dynamic or fixed sizes.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Template Parameters
NRowsType the type of the value handling the number of rows in the block, typically Index.
NColsType the type of the value handling the number of columns in the block, typically Index.
Example:
Output:
The number of rows blockRows and columns blockCols can also be specified at compile-time by passing Eigen::fix<N>, or Eigen::fix<N>(n) as arguments. See block() for the details.
See also
block(Index,Index,NRowsType,NColsType), class Block
References Eigen::internal::get_runtime_value().
template<typename NRowsType , typename NColsType > EIGEN_DEVICE_FUNC const ConstFixedBlockXpr<internal::get_fixed_value<NRowsType>::value,internal::get_fixed_value<NColsType>::value>::Type bottomRightCorner (NRowsType cRows, NColsType cCols) const inline
This is the const version of bottomRightCorner(NRowsType, NColsType).
References EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL, and Eigen::internal::get_runtime_value().
template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<CRows,CCols>::Type bottomRightCorner () inline
Returns
an expression of a fixed-size bottom-right corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Output:
See also
block(Index,Index,NRowsType,NColsType), class Block
template<int CRows, int CCols> EIGEN_DEVICE_FUNC const ConstFixedBlockXpr<CRows,CCols>::Type bottomRightCorner () const inline
This is the const version of bottomRightCorner<int, int>().
References EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL.
template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr<CRows,CCols>::Type bottomRightCorner (Index cRows, Index cCols) inline
Returns
an expression of a bottom-right corner of *this.
Template Parameters
CRows number of rows in corner as specified at compile-time
CCols number of columns in corner as specified at compile-time
Parameters
cRows number of rows in corner as specified at run-time
cCols number of columns in corner as specified at run-time
This function is mainly useful for corners where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, cRows should equal CRows unless CRows is Dynamic, and the same for the number of columns.
Example:
Output:
See also
class Block
template<int CRows, int CCols> const ConstFixedBlockXpr<CRows,CCols>::Type bottomRightCorner (Index cRows, Index cCols) const inline
This is the const version of bottomRightCorner<int, int>(Index, Index).
References EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL.
template<typename NRowsType > EIGEN_DEVICE_FUNC NRowsBlockXpr<internal::get_fixed_value<NRowsType>::value>::Type bottomRows (NRowsType n) inline
Returns
a block consisting of the bottom rows of *this.
Parameters
n the number of rows in the block
Template Parameters
NRowsType the type of the value handling the number of rows in the block, typically Index.
Example:
Output:
The number of rows n can also be specified at compile-time by passing Eigen::fix<N>, or Eigen::fix<N>(n) as arguments. See block() for the details.
See also
block(Index,Index,NRowsType,NColsType), class Block
References Eigen::internal::get_runtime_value().
Referenced by Eigen::DenseBase< Derived >::reverseInPlace().
template<typename NRowsType > EIGEN_DEVICE_FUNC const ConstNRowsBlockXpr<internal::get_fixed_value<NRowsType>::value>::Type bottomRows (NRowsType n) const inline
This is the const version of bottomRows(NRowsType).
References EIGEN_DOC_BLOCK_ADDONS_INNER_PANEL_IF, Eigen::internal::get_runtime_value(), and row().
template<int N> EIGEN_DEVICE_FUNC NRowsBlockXpr<N>::Type bottomRows (Index n = N) inline
Returns
a block consisting of the bottom rows of *this.
Template Parameters
N the number of rows in the block as specified at compile-time
Parameters
n the number of rows in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
block(Index,Index,NRowsType,NColsType), class Block
template<int N> EIGEN_DEVICE_FUNC ConstNRowsBlockXpr<N>::Type bottomRows (Index n = N) const inline
This is the const version of bottomRows<int>().
References EIGEN_DOC_BLOCK_ADDONS_INNER_PANEL_IF, and row().
EIGEN_DEVICE_FUNC ConstColXpr col (Index i) inline
This is the const version of col().
Returns
an expression of the i-th column of *this. Note that the numbering starts at 0.
Example:
Output:
See also
row(), class Block
References EIGEN_DOC_BLOCK_ADDONS_INNER_PANEL_IF, i, and row().
Referenced by Eigen::MatrixBase< Derived >::applyHouseholderOnTheRight(), Eigen::MatrixBase< Derived >::applyOnTheRight(), Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar >, BuiltIn >::assignCoeffByOuterInner(), Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized >::assignPacket(), Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar >, BuiltIn >::assignPacket(), Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized >::assignPacketByOuterInner(), Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar >, BuiltIn >::assignPacketByOuterInner(), Eigen::TriangularBase< SelfAdjointView< _MatrixType, UpLo > >::check_coordinates(), Eigen::SparseMapBase< Derived, ReadOnlyAccessors >::coeff(), Eigen::internal::unary_evaluator< IndexedView< ArgType, RowIndices, ColIndices >, IndexBased >::coeff(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::coeff(), Eigen::internal::evaluator< PlainObjectBase< Derived > >::coeff(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >::coeff(), Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::coeff(), Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::coeff(), Eigen::SparseMapBase< Derived, WriteAccessors >::coeffRef(), Eigen::internal::unary_evaluator< IndexedView< ArgType, RowIndices, ColIndices >, IndexBased >::coeffRef(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::coeffRef(), Eigen::internal::evaluator< PlainObjectBase< Derived > >::coeffRef(), Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::coeffRef(), Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::coeffRef(), Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IteratorBased >::InnerVectorInnerIterator::col(), internal::colamd_r(), Eigen::internal::coletree(), Eigen::SPQR< _MatrixType >::compute(), Eigen::LLT< _MatrixType, _UpLo >::compute(), Eigen::LDLT< _MatrixType, _UpLo >::compute(), Server::ComputeSensorDistToWall(), internal::detect_super_cols(), Eigen::SparseQR< _MatrixType, _OrderingType >::factorize(), Eigen::internal::evaluator< SparseCompressedBase< Derived > >::find(), internal::find_ordering(), AbstractMaze::gen_random_legal_maze(), AbstractMaze::get_node(), internal::init_rows_cols(), Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::insert(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insert(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::insertBackUncompressed(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertCompressed(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertUncompressed(), Eigen::MatrixBase< Derived >::isUnitary(), main(), AbstractMaze::mark_position_visited(), Eigen::IncompleteLUT< _Scalar, _StorageIndex >::keep_diag::operator()(), Eigen::internal::gemm_functor< Scalar, Index, Gemm, Lhs, Rhs, Dest, BlockingType >::operator()(), Eigen::SimplicialCholeskyBase< Derived >::keep_diag::operator()(), Eigen::ForceAlignedAccess< ExpressionType >::packet(), Eigen::NestByValue< ExpressionType >::packet(), Eigen::internal::evaluator< PlainObjectBase< Derived > >::packet(), Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::packet(), Eigen::internal::redux_evaluator< _XprType >::packet(), Eigen::internal::evaluator< CwiseNullaryOp< NullaryOp, PlainObjectType > >::packet(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >::packet(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DiagonalShape, DenseShape >::packet(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DenseShape, DiagonalShape >::packet(), Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::packet(), Eigen::internal::evaluator_wrapper_base< ArrayWrapper< TArgType > >::packet(), Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::packet(), MazeWidget::PaintWalls(), Eigen::internal::sparse_time_dense_product_impl< SparseLhsType, DenseRhsType, DenseResType, typename DenseResType::Scalar, RowMajor, true >::processRow(), Eigen::DenseBase< Derived >::reverseInPlace(), Eigen::internal::unary_evaluator< Transpose< ArgType >, IteratorBased >::InnerIterator::row(), Eigen::internal::sparse_solve_triangular_selector< Lhs, Rhs, Mode, Lower, RowMajor >::run(), Eigen::internal::sparse_solve_triangular_selector< Lhs, Rhs, Mode, Upper, RowMajor >::run(), Eigen::internal::sparse_solve_triangular_selector< Lhs, Rhs, Mode, Lower, ColMajor >::run(), Eigen::internal::sparse_solve_triangular_selector< Lhs, Rhs, Mode, Upper, ColMajor >::run(), Eigen::internal::sparse_solve_triangular_sparse_selector< Lhs, Rhs, Mode, UpLo, ColMajor >::run(), Eigen::internal::etor_product_packet_impl< RowMajor, UnrollingIndex, Lhs, Rhs, Packet, LoadMode >::run(), Eigen::internal::etor_product_packet_impl< RowMajor, 1, Lhs, Rhs, Packet, LoadMode >::run(), Eigen::internal::triangular_assignment_loop< Kernel, Mode, UnrollCount, SetOpposite >::run(), Eigen::internal::triangular_dense_assignment_kernel< UpLo, Mode, SetOpposite, DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::triangular_dense_assignment_kernel(), AbstractMaze::truncate(), Server::UpdateRobotState(), Eigen::NestByValue< ExpressionType >::writePacket(), Eigen::ForceAlignedAccess< ExpressionType >::writePacket(), Eigen::internal::evaluator< PlainObjectBase< Derived > >::writePacket(), Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::writePacket(), Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::writePacket(), Eigen::internal::evaluator_wrapper_base< ArrayWrapper< TArgType > >::writePacket(), and Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::writePacket().
template<typename NType > EIGEN_DEVICE_FUNC FixedSegmentReturnType<internal::get_fixed_value<NType>::value>::Type head (NType n) inline
Returns
an expression of the first coefficients of *this with either dynamic or fixed sizes.
Parameters
n the number of coefficients in the segment
Template Parameters
NType the type of the value handling the number of coefficients in the segment, typically Index.
Example:
Output:
The number of coefficients n can also be specified at compile-time by passing Eigen::fix<N>, or Eigen::fix<N>(n) as arguments. See block() for the details.
Note
Even in the case that the returned expression has dynamic size, in the case when it is applied to a fixed-size vector, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See also
class Block, block(Index,Index)
References EIGEN_STATIC_ASSERT_VECTOR_ONLY, and Eigen::internal::get_runtime_value().
Referenced by internal::colamd_r(), Eigen::BDCSVD< _MatrixType >::computeSVDofM(), and Eigen::internal::minimum_degree_ordering().
template<typename NType > EIGEN_DEVICE_FUNC const ConstFixedSegmentReturnType<internal::get_fixed_value<NType>::value>::Type head (NType n) const inline
This is the const version of head(NType).
References EIGEN_STATIC_ASSERT_VECTOR_ONLY, and Eigen::internal::get_runtime_value().
template<int N> EIGEN_DEVICE_FUNC FixedSegmentReturnType<N>::Type head (Index n = N) inline
Returns
a fixed-size expression of the first coefficients of *this.
Template Parameters
N the number of coefficients in the segment as specified at compile-time
Parameters
n the number of coefficients in the segment as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
head(NType), class Block
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
template<int N> EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType<N>::Type head (Index n = N) const inline
This is the const version of head<int>().
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
template<typename NColsType > EIGEN_DEVICE_FUNC NColsBlockXpr<internal::get_fixed_value<NColsType>::value>::Type leftCols (NColsType n) inline
Returns
a block consisting of the left columns of *this.
Parameters
n the number of columns in the block
Template Parameters
NColsType the type of the value handling the number of columns in the block, typically Index.
Example:
Output:
The number of columns n can also be specified at compile-time by passing Eigen::fix<N>, or Eigen::fix<N>(n) as arguments. See block() for the details.
See also
block(Index,Index,NRowsType,NColsType), class Block
References Eigen::internal::get_runtime_value().
Referenced by Eigen::DenseBase< Derived >::reverseInPlace().
template<typename NColsType > EIGEN_DEVICE_FUNC const ConstNColsBlockXpr<internal::get_fixed_value<NColsType>::value>::Type leftCols (NColsType n) const inline
This is the const version of leftCols(NColsType).
References EIGEN_DOC_BLOCK_ADDONS_INNER_PANEL_IF, and Eigen::internal::get_runtime_value().
template<int N> EIGEN_DEVICE_FUNC NColsBlockXpr<N>::Type leftCols (Index n = N) inline
Returns
a block consisting of the left columns of *this.
Template Parameters
N the number of columns in the block as specified at compile-time
Parameters
n the number of columns in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
block(Index,Index,NRowsType,NColsType), class Block
template<int N> EIGEN_DEVICE_FUNC ConstNColsBlockXpr<N>::Type leftCols (Index n = N) const inline
This is the const version of leftCols<int>().
References EIGEN_DOC_BLOCK_ADDONS_INNER_PANEL_IF.
template<typename NColsType > EIGEN_DEVICE_FUNC NColsBlockXpr<internal::get_fixed_value<NColsType>::value>::Type middleCols (Index startCol, NColsType numCols) inline
Returns
a block consisting of a range of columns of *this.
Parameters
startCol the index of the first column in the block
numCols the number of columns in the block
Template Parameters
NColsType the type of the value handling the number of columns in the block, typically Index.
Example:
Output:
The number of columns n can also be specified at compile-time by passing Eigen::fix<N>, or Eigen::fix<N>(n) as arguments. See block() for the details.
See also
block(Index,Index,NRowsType,NColsType), class Block
References Eigen::internal::get_runtime_value().
template<typename NColsType > EIGEN_DEVICE_FUNC const ConstNColsBlockXpr<internal::get_fixed_value<NColsType>::value>::Type middleCols (Index startCol, NColsType numCols) const inline
This is the const version of middleCols(Index,NColsType).
References EIGEN_DOC_BLOCK_ADDONS_INNER_PANEL_IF, and Eigen::internal::get_runtime_value().
template<int N> EIGEN_DEVICE_FUNC NColsBlockXpr<N>::Type middleCols (Index startCol, Index n = N) inline
Returns
a block consisting of a range of columns of *this.
Template Parameters
N the number of columns in the block as specified at compile-time
Parameters
startCol the index of the first column in the block
n the number of columns in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
block(Index,Index,NRowsType,NColsType), class Block
template<int N> EIGEN_DEVICE_FUNC ConstNColsBlockXpr<N>::Type middleCols (Index startCol, Index n = N) const inline
This is the const version of middleCols<int>().
References EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL.
template<typename NRowsType > EIGEN_DEVICE_FUNC NRowsBlockXpr<internal::get_fixed_value<NRowsType>::value>::Type middleRows (Index startRow, NRowsType n) inline
Returns
a block consisting of a range of rows of *this.
Parameters
startRow the index of the first row in the block
n the number of rows in the block
Template Parameters
NRowsType the type of the value handling the number of rows in the block, typically Index.
Example:
Output:
The number of rows n can also be specified at compile-time by passing Eigen::fix<N>, or Eigen::fix<N>(n) as arguments. See block() for the details.
See also
block(Index,Index,NRowsType,NColsType), class Block
References Eigen::internal::get_runtime_value().
template<typename NRowsType > EIGEN_DEVICE_FUNC const ConstNRowsBlockXpr<internal::get_fixed_value<NRowsType>::value>::Type middleRows (Index startRow, NRowsType n) const inline
This is the const version of middleRows(Index,NRowsType).
References EIGEN_DOC_BLOCK_ADDONS_INNER_PANEL_IF, Eigen::internal::get_runtime_value(), and row().
template<int N> EIGEN_DEVICE_FUNC NRowsBlockXpr<N>::Type middleRows (Index startRow, Index n = N) inline
Returns
a block consisting of a range of rows of *this.
Template Parameters
N the number of rows in the block as specified at compile-time
Parameters
startRow the index of the first row in the block
n the number of rows in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
block(Index,Index,NRowsType,NColsType), class Block
template<int N> EIGEN_DEVICE_FUNC ConstNRowsBlockXpr<N>::Type middleRows (Index startRow, Index n = N) const inline
This is the const version of middleRows<int>().
References EIGEN_DOC_BLOCK_ADDONS_INNER_PANEL_IF.
template<typename NColsType > EIGEN_DEVICE_FUNC NColsBlockXpr<internal::get_fixed_value<NColsType>::value>::Type rightCols (NColsType n) inline
Returns
a block consisting of the right columns of *this.
Parameters
n the number of columns in the block
Template Parameters
NColsType the type of the value handling the number of columns in the block, typically Index.
Example:
Output:
The number of columns n can also be specified at compile-time by passing Eigen::fix<N>, or Eigen::fix<N>(n) as arguments. See block() for the details.
See also
block(Index,Index,NRowsType,NColsType), class Block
References Eigen::internal::get_runtime_value().
Referenced by Eigen::DenseBase< Derived >::reverseInPlace(), and Eigen::RealQZ< _MatrixType >::step().
template<typename NColsType > EIGEN_DEVICE_FUNC const ConstNColsBlockXpr<internal::get_fixed_value<NColsType>::value>::Type rightCols (NColsType n) const inline
This is the const version of rightCols(NColsType).
References EIGEN_DOC_BLOCK_ADDONS_INNER_PANEL_IF, and Eigen::internal::get_runtime_value().
template<int N> EIGEN_DEVICE_FUNC NColsBlockXpr<N>::Type rightCols (Index n = N) inline
Returns
a block consisting of the right columns of *this.
Template Parameters
N the number of columns in the block as specified at compile-time
Parameters
n the number of columns in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
block(Index,Index,NRowsType,NColsType), class Block
template<int N> EIGEN_DEVICE_FUNC ConstNColsBlockXpr<N>::Type rightCols (Index n = N) const inline
This is the const version of rightCols<int>().
References EIGEN_DOC_BLOCK_ADDONS_INNER_PANEL_IF.
EIGEN_DEVICE_FUNC ConstRowXpr row (Index i) inline
This is the const version of row(). */.
Returns
an expression of the i-th row of *this. Note that the numbering starts at 0.
Example:
Output:
See also
col(), class Block
References i.
Referenced by Eigen::MatrixBase< Derived >::applyHouseholderOnTheLeft(), Eigen::MatrixBase< Derived >::applyOnTheLeft(), Eigen::CompleteOrthogonalDecomposition< _MatrixType >::applyZAdjointOnTheLeftInPlace(), Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar >, BuiltIn >::assignCoeffByOuterInner(), Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized >::assignPacket(), Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar >, BuiltIn >::assignPacket(), Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized >::assignPacketByOuterInner(), Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar >, BuiltIn >::assignPacketByOuterInner(), bottomLeftCorner(), bottomRows(), Eigen::TriangularBase< SelfAdjointView< _MatrixType, UpLo > >::check_coordinates(), Eigen::SparseMapBase< Derived, ReadOnlyAccessors >::coeff(), Eigen::internal::unary_evaluator< IndexedView< ArgType, RowIndices, ColIndices >, IndexBased >::coeff(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::coeff(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >::coeff(), Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::coeff(), Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::coeff(), Eigen::SparseMapBase< Derived, WriteAccessors >::coeffRef(), Eigen::internal::unary_evaluator< IndexedView< ArgType, RowIndices, ColIndices >, IndexBased >::coeffRef(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::coeffRef(), Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::coeffRef(), Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::coeffRef(), Eigen::internal::unary_evaluator< Transpose< ArgType >, IteratorBased >::InnerIterator::col(), col(), Eigen::internal::coletree(), Server::ComputeSensorDistToWall(), Eigen::internal::evaluator< SparseCompressedBase< Derived > >::find(), internal::find_ordering(), AbstractMaze::gen_random_legal_maze(), AbstractMaze::get_node(), internal::init_rows_cols(), internal::init_scoring(), Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::insert(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insert(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::insertBackUncompressed(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertCompressed(), main(), AbstractMaze::mark_position_visited(), middleRows(), Eigen::NestByValue< ExpressionType >::packet(), Eigen::ForceAlignedAccess< ExpressionType >::packet(), Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::packet(), Eigen::internal::redux_evaluator< _XprType >::packet(), Eigen::internal::evaluator< CwiseNullaryOp< NullaryOp, PlainObjectType > >::packet(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >::packet(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DiagonalShape, DenseShape >::packet(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DenseShape, DiagonalShape >::packet(), Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::packet(), Eigen::internal::evaluator_wrapper_base< ArrayWrapper< TArgType > >::packet(), Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::packet(), MazeWidget::PaintWalls(), Eigen::internal::QuickSplit(), Eigen::DenseBase< Derived >::reverseInPlace(), Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IteratorBased >::InnerVectorInnerIterator::row(), Eigen::internal::triangular_assignment_loop< Kernel, Mode, UnrollCount, SetOpposite >::run(), topRows(), Eigen::internal::triangular_dense_assignment_kernel< UpLo, Mode, SetOpposite, DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::triangular_dense_assignment_kernel(), AbstractMaze::truncate(), Server::UpdateRobotState(), Eigen::ForceAlignedAccess< ExpressionType >::writePacket(), Eigen::NestByValue< ExpressionType >::writePacket(), Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::writePacket(), Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::writePacket(), Eigen::internal::evaluator_wrapper_base< ArrayWrapper< TArgType > >::writePacket(), and Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::writePacket().
template<typename NType > EIGEN_DEVICE_FUNC FixedSegmentReturnType<internal::get_fixed_value<NType>::value>::Type segment (Index start, NType n) inline
Returns
an expression of a segment (i.e. a vector block) in *this with either dynamic or fixed sizes.
Parameters
start the first coefficient in the segment
n the number of coefficients in the segment
Template Parameters
NType the type of the value handling the number of coefficients in the segment, typically Index.
Example:
Output:
The number of coefficients n can also be specified at compile-time by passing Eigen::fix<N>, or Eigen::fix<N>(n) as arguments. See block() for the details.
Note
Even in the case that the returned expression has dynamic size, in the case when it is applied to a fixed-size vector, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See also
block(Index,Index,NRowsType,NColsType), fix<N>, fix<N>(int), class Block
References EIGEN_STATIC_ASSERT_VECTOR_ONLY, and Eigen::internal::get_runtime_value().
template<typename NType > EIGEN_DEVICE_FUNC const ConstFixedSegmentReturnType<internal::get_fixed_value<NType>::value>::Type segment (Index start, NType n) const inline
This is the const version of segment(Index,NType).
References EIGEN_STATIC_ASSERT_VECTOR_ONLY, and Eigen::internal::get_runtime_value().
template<int N> EIGEN_DEVICE_FUNC FixedSegmentReturnType<N>::Type segment (Index start, Index n = N) inline
Returns
a fixed-size expression of a segment (i.e. a vector block) in *this
Template Parameters
N the number of coefficients in the segment as specified at compile-time
Parameters
start the index of the first element in the segment
n the number of coefficients in the segment as specified at compile-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
segment(Index,NType), class Block
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
template<int N> EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType<N>::Type segment (Index start, Index n = N) const inline
This is the const version of segment<int>(Index).
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
template<typename NType > EIGEN_DEVICE_FUNC FixedSegmentReturnType<internal::get_fixed_value<NType>::value>::Type tail (NType n) inline
Returns
an expression of a last coefficients of *this with either dynamic or fixed sizes.
Parameters
n the number of coefficients in the segment
Template Parameters
NType the type of the value handling the number of coefficients in the segment, typically Index.
Example:
Output:
The number of coefficients n can also be specified at compile-time by passing Eigen::fix<N>, or Eigen::fix<N>(n) as arguments. See block() for the details.
Note
Even in the case that the returned expression has dynamic size, in the case when it is applied to a fixed-size vector, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See also
class Block, block(Index,Index)
References EIGEN_STATIC_ASSERT_VECTOR_ONLY, Eigen::internal::get_runtime_value(), and Eigen::internal::size().
Referenced by Eigen::CompleteOrthogonalDecomposition< _MatrixType >::applyZAdjointOnTheLeftInPlace(), Eigen::internal::kernel_retval< FullPivLU< _MatrixType > >::evalTo(), Eigen::MatrixBase< Derived >::makeHouseholder(), and Eigen::DenseBase< Derived >::reverseInPlace().
template<typename NType > EIGEN_DEVICE_FUNC const ConstFixedSegmentReturnType<internal::get_fixed_value<NType>::value>::Type tail (NType n) const inline
This is the const version of tail(Index).
References EIGEN_STATIC_ASSERT_VECTOR_ONLY, Eigen::internal::get_runtime_value(), and Eigen::internal::size().
template<int N> EIGEN_DEVICE_FUNC FixedSegmentReturnType<N>::Type tail (Index n = N) inline
Returns
a fixed-size expression of the last coefficients of *this.
Template Parameters
N the number of coefficients in the segment as specified at compile-time
Parameters
n the number of coefficients in the segment as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
tail(NType), class Block
References EIGEN_STATIC_ASSERT_VECTOR_ONLY, and Eigen::internal::size().
template<int N> EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType<N>::Type tail (Index n = N) const inline
This is the const version of tail<int>.
References EIGEN_STATIC_ASSERT_VECTOR_ONLY, and Eigen::internal::size().
template<typename NRowsType , typename NColsType > EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<internal::get_fixed_value<NRowsType>::value,internal::get_fixed_value<NColsType>::value>::Type topLeftCorner (NRowsType cRows, NColsType cCols) inline
Returns
an expression of a top-left corner of *this with either dynamic or fixed sizes.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Template Parameters
NRowsType the type of the value handling the number of rows in the block, typically Index.
NColsType the type of the value handling the number of columns in the block, typically Index.
Example:
Output:
The number of rows blockRows and columns blockCols can also be specified at compile-time by passing Eigen::fix<N>, or Eigen::fix<N>(n) as arguments. See block() for the details.
See also
block(Index,Index,NRowsType,NColsType), class Block
References Eigen::internal::get_runtime_value().
Referenced by Eigen::BDCSVD< _MatrixType >::copyUV().
template<typename NRowsType , typename NColsType > EIGEN_DEVICE_FUNC const ConstFixedBlockXpr<internal::get_fixed_value<NRowsType>::value,internal::get_fixed_value<NColsType>::value>::Type topLeftCorner (NRowsType cRows, NColsType cCols) const inline
This is the const version of topLeftCorner(Index, Index).
References EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL, and Eigen::internal::get_runtime_value().
template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<CRows,CCols>::Type topLeftCorner () inline
Returns
an expression of a fixed-size top-left corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Output:
See also
block(Index,Index,NRowsType,NColsType), class Block
template<int CRows, int CCols> EIGEN_DEVICE_FUNC const ConstFixedBlockXpr<CRows,CCols>::Type topLeftCorner () const inline
This is the const version of topLeftCorner<int, int>().
References EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL.
template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr<CRows,CCols>::Type topLeftCorner (Index cRows, Index cCols) inline
Returns
an expression of a top-left corner of *this.
Template Parameters
CRows number of rows in corner as specified at compile-time
CCols number of columns in corner as specified at compile-time
Parameters
cRows number of rows in corner as specified at run-time
cCols number of columns in corner as specified at run-time
This function is mainly useful for corners where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, cRows should equal CRows unless CRows is Dynamic, and the same for the number of columns.
Example:
Output:
See also
class Block
template<int CRows, int CCols> const ConstFixedBlockXpr<CRows,CCols>::Type topLeftCorner (Index cRows, Index cCols) const inline
This is the const version of topLeftCorner<int, int>(Index, Index).
References EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL.
template<typename NRowsType , typename NColsType > EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<internal::get_fixed_value<NRowsType>::value,internal::get_fixed_value<NColsType>::value>::Type topRightCorner (NRowsType cRows, NColsType cCols) inline
Returns
a expression of a top-right corner of *this with either dynamic or fixed sizes.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Template Parameters
NRowsType the type of the value handling the number of rows in the block, typically Index.
NColsType the type of the value handling the number of columns in the block, typically Index.
Example with dynamic sizes:
Output:
The number of rows blockRows and columns blockCols can also be specified at compile-time by passing Eigen::fix<N>, or Eigen::fix<N>(n) as arguments. See block() for the details.
See also
block(Index,Index,NRowsType,NColsType), class Block
References Eigen::internal::get_runtime_value().
template<typename NRowsType , typename NColsType > EIGEN_DEVICE_FUNC const ConstFixedBlockXpr<internal::get_fixed_value<NRowsType>::value,internal::get_fixed_value<NColsType>::value>::Type topRightCorner (NRowsType cRows, NColsType cCols) const inline
This is the const version of topRightCorner(NRowsType, NColsType).
References EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL, and Eigen::internal::get_runtime_value().
template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<CRows,CCols>::Type topRightCorner () inline
Returns
an expression of a fixed-size top-right corner of *this.
Template Parameters
CRows the number of rows in the corner
CCols the number of columns in the corner
Example:
Output:
See also
class Block, block<int,int>(Index,Index)
template<int CRows, int CCols> EIGEN_DEVICE_FUNC const ConstFixedBlockXpr<CRows,CCols>::Type topRightCorner () const inline
This is the const version of topRightCorner<int, int>().
References EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL.
template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr<CRows,CCols>::Type topRightCorner (Index cRows, Index cCols) inline
Returns
an expression of a top-right corner of *this.
Template Parameters
CRows number of rows in corner as specified at compile-time
CCols number of columns in corner as specified at compile-time
Parameters
cRows number of rows in corner as specified at run-time
cCols number of columns in corner as specified at run-time
This function is mainly useful for corners where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, cRows should equal CRows unless CRows is Dynamic, and the same for the number of columns.
Example:
Output:
See also
class Block
template<int CRows, int CCols> const ConstFixedBlockXpr<CRows,CCols>::Type topRightCorner (Index cRows, Index cCols) const inline
This is the const version of topRightCorner<int, int>(Index, Index).
References EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL.
template<typename NRowsType > EIGEN_DEVICE_FUNC NRowsBlockXpr<internal::get_fixed_value<NRowsType>::value>::Type topRows (NRowsType n) inline
Returns
a block consisting of the top rows of *this.
Parameters
n the number of rows in the block
Template Parameters
NRowsType the type of the value handling the number of rows in the block, typically Index.
Example:
Output:
The number of rows n can also be specified at compile-time by passing Eigen::fix<N>, or Eigen::fix<N>(n) as arguments. See block() for the details.
See also
block(Index,Index,NRowsType,NColsType), class Block
References Eigen::internal::get_runtime_value().
Referenced by Eigen::DenseBase< Derived >::reverseInPlace(), and Eigen::RealQZ< _MatrixType >::step().
template<typename NRowsType > EIGEN_DEVICE_FUNC const ConstNRowsBlockXpr<internal::get_fixed_value<NRowsType>::value>::Type topRows (NRowsType n) const inline
This is the const version of topRows(NRowsType).
References EIGEN_DOC_BLOCK_ADDONS_INNER_PANEL_IF, Eigen::internal::get_runtime_value(), and row().
template<int N> EIGEN_DEVICE_FUNC NRowsBlockXpr<N>::Type topRows (Index n = N) inline
Returns
a block consisting of the top rows of *this.
Template Parameters
N the number of rows in the block as specified at compile-time
Parameters
n the number of rows in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
block(Index,Index,NRowsType,NColsType), class Block
template<int N> EIGEN_DEVICE_FUNC ConstNRowsBlockXpr<N>::Type topRows (Index n = N) const inline
This is the const version of topRows<int>().
References EIGEN_DOC_BLOCK_ADDONS_INNER_PANEL_IF, and row().