SmartMouse_2018: CommandGroup Class Reference
CommandGroup Class Reference
grouping commands is a useful abstraction. Commands groups execute commands in parallel or series
#include <CommandGroup.h>
Public Member Functions
CommandGroup (const char *name)
CommandGroup ()=default
void addSequential (Command *command)
void addParallel (Command *command)
virtual void _initialize ()
virtual void _execute ()
virtual void _end ()
virtual void initialize ()
run once in the first iteration of the command's life. this will be overrided by individual commands
virtual void execute ()
stuff to do over and over each iteration. this will be overrided by individual commands
virtual void end ()
called once at the end, once isFinished() returned true. this will be overrided by individual commands.
virtual bool isFinished ()
checked every iteration to see if we're done here. this will be overrided by individual commands
Public Member Functions inherited from Command
Command ()
Command (const char *name)
virtual ~Command ()
void setTimeout (unsigned long timeout)
unsigned long getTime ()
bool isTimedOut ()
bool cycle ()
actually does the excuting.
bool isRunning ()
check if the command is running.
bool operator!= (const Command &other)
comparator overload for !=. used when checking if command is in list
Public Attributes
LinkedList< Command * > commands
Public Attributes inherited from Command
bool inParallel
used by command group to organize commands
const char * name
for convenient printing
bool initialized
bool running
unsigned long timeout
unsigned long startTime
Private Attributes
int currentCommandIndex
Additional Inherited Members
Static Public Member Functions inherited from Command
static void setTimerImplementation (TimerInterface *timer)
static TimerInterface * getTimerImplementation ()
Static Public Attributes inherited from Command
static TimerInterface * timer
Detailed Description
grouping commands is a useful abstraction. Commands groups execute commands in parallel or series
Constructor & Destructor Documentation
CommandGroup::CommandGroup (const char * name)
CommandGroup::CommandGroup () default
Member Function Documentation
void CommandGroup::_end () virtual
Reimplemented from Command.
References currentCommandIndex.
void CommandGroup::_execute () virtual
Reimplemented from Command.
References commands, currentCommandIndex, Command::cycle(), done, LinkedList< T >::get(), Command::inParallel, isFinished(), LinkedList< T >::remove(), and LinkedList< T >::size().
void CommandGroup::_initialize () virtual
Reimplemented from Command.
References Command::_initialize(), and currentCommandIndex.
void CommandGroup::addParallel (Command * command)
References LinkedList< T >::add(), commands, and Command::inParallel.
void CommandGroup::addSequential (Command * command)
References LinkedList< T >::add(), commands, and Command::inParallel.
Referenced by SolveCommand::initialize(), Turn::initialize(), SolveCommand::isFinished(), SpeedRun::isFinished(), ReturnToStart::isFinished(), SolveMaze::isFinished(), NavTestCommand::NavTestCommand(), RepeatCommand< CommandType, CommandArgs >::RepeatCommand(), and WaitForStart::WaitForStart().
void CommandGroup::end () virtual
called once at the end, once isFinished() returned true. this will be overrided by individual commands.
Reimplemented from Command.
Reimplemented in Turn, SolveMaze, SolveMaze, WaitForStart, SolveMaze, WaitForStart, and WaitForStart.
void CommandGroup::execute () virtual
stuff to do over and over each iteration. this will be overrided by individual commands
Reimplemented from Command.
Reimplemented in Turn, WaitForStart, WaitForStart, and WaitForStart.
Referenced by WaitForStart::execute().
void CommandGroup::initialize () virtual
run once in the first iteration of the command's life. this will be overrided by individual commands
Reimplemented from Command.
Reimplemented in ReturnToStart, SpeedRun, SolveMaze, SolveMaze, SolveMaze, SolveCommand, Turn, Turn, Turn, WaitForStart, WaitForStart, and WaitForStart.
bool CommandGroup::isFinished () virtual
checked every iteration to see if we're done here. this will be overrided by individual commands
Returns
is the function finished
Implements Command.
Reimplemented in Turn, ReturnToStart, SpeedRun, SolveMaze, SolveMaze, WaitForStart, SolveMaze, WaitForStart, SolveCommand, and WaitForStart.
References commands, and LinkedList< T >::size().
Referenced by _execute(), WaitForStart::isFinished(), SolveCommand::isFinished(), SolveMaze::isFinished(), SpeedRun::isFinished(), and ReturnToStart::isFinished().
Member Data Documentation
LinkedList<Command *> CommandGroup::commands
Referenced by _execute(), addParallel(), addSequential(), and isFinished().
int CommandGroup::currentCommandIndex private
Referenced by _end(), _execute(), and _initialize().
The documentation for this class was generated from the following files:
CommandGroup.h
CommandGroup.cpp