SmartMouse_2018: TurnInPlace Class Reference
TurnInPlace Class Reference
#include <TurnInPlace.h>
Public Member Functions
TurnInPlace (Direction dir)
void initialize ()
run once in the first iteration of the command's life. this will be overrided by individual commands
void execute ()
stuff to do over and over each iteration. this will be overrided by individual commands
bool isFinished ()
checked every iteration to see if we're done here. this will be overrided by individual commands
void end ()
called once at the end, once isFinished() returned true. this will be overrided by individual commands.
TurnInPlace (Direction dir)
void initialize ()
run once in the first iteration of the command's life. this will be overrided by individual commands
void execute ()
stuff to do over and over each iteration. this will be overrided by individual commands
bool isFinished ()
checked every iteration to see if we're done here. this will be overrided by individual commands
void end ()
called once at the end, once isFinished() returned true. this will be overrided by individual commands.
Public Member Functions inherited from Command
Command ()
Command (const char *name)
virtual ~Command ()
void setTimeout (unsigned long timeout)
unsigned long getTime ()
bool isTimedOut ()
virtual void _initialize ()
virtual void _execute ()
virtual void _end ()
bool cycle ()
actually does the excuting.
bool isRunning ()
check if the command is running.
bool operator!= (const Command &other)
comparator overload for !=. used when checking if command is in list
Private Attributes
double goalYaw
double dYaw
RealMouse * mouse
Direction dir
const double kP = 0.15
SimMouse * mouse
Additional Inherited Members
Static Public Member Functions inherited from Command
static void setTimerImplementation (TimerInterface *timer)
static TimerInterface * getTimerImplementation ()
Public Attributes inherited from Command
bool inParallel
used by command group to organize commands
const char * name
for convenient printing
bool initialized
bool running
unsigned long timeout
unsigned long startTime
Static Public Attributes inherited from Command
static TimerInterface * timer
Constructor & Destructor Documentation
TurnInPlace::TurnInPlace (Direction dir)
TurnInPlace::TurnInPlace (Direction dir)
Member Function Documentation
void TurnInPlace::end () virtual
called once at the end, once isFinished() returned true. this will be overrided by individual commands.
Reimplemented from Command.
References dir, Mouse::internalTurnToFace(), RealMouse::LED_2, and mouse.
void TurnInPlace::end () virtual
called once at the end, once isFinished() returned true. this will be overrided by individual commands.
Reimplemented from Command.
void TurnInPlace::execute () virtual
stuff to do over and over each iteration. this will be overrided by individual commands
Reimplemented from Command.
References dYaw, kP, mouse, and RealMouse::setSpeedCps().
void TurnInPlace::execute () virtual
stuff to do over and over each iteration. this will be overrided by individual commands
Reimplemented from Command.
void TurnInPlace::initialize () virtual
run once in the first iteration of the command's life. this will be overrided by individual commands
Reimplemented from Command.
void TurnInPlace::initialize () virtual
run once in the first iteration of the command's life. this will be overrided by individual commands
Reimplemented from Command.
References dir, dir_to_yaw(), goalYaw, RealMouse::LED_2, and Command::setTimeout().
bool TurnInPlace::isFinished () virtual
checked every iteration to see if we're done here. this will be overrided by individual commands
Returns
is the function finished
Implements Command.
References dYaw, RealMouse::getGlobalPose(), RealMouse::getWheelVelocities(), goalYaw, Command::isTimedOut(), mouse, smartmouse::kc::ROT_TOLERANCE, GlobalPose::yaw, and smartmouse::math::yaw_diff().
bool TurnInPlace::isFinished () virtual
checked every iteration to see if we're done here. this will be overrided by individual commands
Returns
is the function finished
Implements Command.
Member Data Documentation
Direction TurnInPlace::dir private
Referenced by end(), and initialize().
double TurnInPlace::dYaw private
Referenced by execute(), and isFinished().
double TurnInPlace::goalYaw private
Referenced by initialize(), and isFinished().
const double TurnInPlace::kP = 0.15 private
Referenced by execute().
RealMouse* TurnInPlace::mouse private
Referenced by end(), execute(), and isFinished().
SimMouse* TurnInPlace::mouse private
The documentation for this class was generated from the following files:
real/commands/TurnInPlace.h
real/commands/TurnInPlace.cpp