SmartMouse_2018: ArcTurn Class Reference
ArcTurn Class Reference
#include <ArcTurn.h>
Public Member Functions
ArcTurn (Direction dir)
void initialize ()
run once in the first iteration of the command's life. this will be overrided by individual commands
void execute ()
stuff to do over and over each iteration. this will be overrided by individual commands
bool isFinished ()
checked every iteration to see if we're done here. this will be overrided by individual commands
void end ()
called once at the end, once isFinished() returned true. this will be overrided by individual commands.
ArcTurn (Direction dir)
void initialize ()
run once in the first iteration of the command's life. this will be overrided by individual commands
void execute ()
stuff to do over and over each iteration. this will be overrided by individual commands
bool isFinished ()
checked every iteration to see if we're done here. this will be overrided by individual commands
void end ()
called once at the end, once isFinished() returned true. this will be overrided by individual commands.
Public Member Functions inherited from Command
Command ()
Command (const char *name)
virtual ~Command ()
void setTimeout (unsigned long timeout)
unsigned long getTime ()
bool isTimedOut ()
virtual void _initialize ()
virtual void _execute ()
virtual void _end ()
bool cycle ()
actually does the excuting.
bool isRunning ()
check if the command is running.
bool operator!= (const Command &other)
comparator overload for !=. used when checking if command is in list
Private Member Functions
double pose_dist (GlobalPose pose, double x, double y)
double pose_dist (GlobalPose pose, double x, double y)
Private Attributes
RealMouse * mouse
Direction dir
GlobalPose curPose
unsigned int curCol
unsigned int curRow
Direction curDir
GlobalPose startPose
unsigned int startCol
unsigned int startRow
double dYaw
double goalYaw
double vtc_x
double vtc_y
double SLOW_ARC_SPEED
double FAST_ARC_SPEED = speed_scale * (smartmouse::kc::MAX_SPEED_CUPS)
double dDisp
double end_x
double end_y
SimMouse * mouse
Static Private Attributes
static constexpr double speed_scale = 0.75
static constexpr double kp_turn = 3.00
static constexpr double ang_weight = 1.00
static constexpr double arc_weight = 1.00
Additional Inherited Members
Static Public Member Functions inherited from Command
static void setTimerImplementation (TimerInterface *timer)
static TimerInterface * getTimerImplementation ()
Public Attributes inherited from Command
bool inParallel
used by command group to organize commands
const char * name
for convenient printing
bool initialized
bool running
unsigned long timeout
unsigned long startTime
Static Public Attributes inherited from Command
static TimerInterface * timer
Constructor & Destructor Documentation
ArcTurn::ArcTurn (Direction dir)
ArcTurn::ArcTurn (Direction dir)
Member Function Documentation
void ArcTurn::end () virtual
called once at the end, once isFinished() returned true. this will be overrided by individual commands.
Reimplemented from Command.
void ArcTurn::end () virtual
called once at the end, once isFinished() returned true. this will be overrided by individual commands.
Reimplemented from Command.
References dir, Mouse::internalTurnToFace(), and mouse.
void ArcTurn::execute () virtual
stuff to do over and over each iteration. this will be overrided by individual commands
Reimplemented from Command.
void ArcTurn::execute () virtual
stuff to do over and over each iteration. this will be overrided by individual commands
Reimplemented from Command.
References ang_weight, arc_weight, GlobalPose::col, curDir, curPose, dir, dir_to_yaw(), FAST_ARC_SPEED, smartmouse::maze::HALF_UNIT_DIST, kp_turn, mouse, N, pose_dist(), right_of_dir(), GlobalPose::row, S, RealMouse::setSpeedCps(), SLOW_ARC_SPEED, vtc_x, vtc_y, GlobalPose::yaw, and smartmouse::math::yaw_diff().
void ArcTurn::initialize () virtual
run once in the first iteration of the command's life. this will be overrided by individual commands
Reimplemented from Command.
void ArcTurn::initialize () virtual
run once in the first iteration of the command's life. this will be overrided by individual commands
Reimplemented from Command.
References curCol, curDir, curPose, curRow, dir, dir_to_yaw(), E, Mouse::getCol(), Mouse::getDir(), RealMouse::getGlobalPose(), Mouse::getRow(), goalYaw, smartmouse::maze::HALF_UNIT_DIST, mouse, N, S, startCol, startPose, startRow, smartmouse::maze::UNIT_DIST_M, vtc_x, vtc_y, and W.
bool ArcTurn::isFinished () virtual
checked every iteration to see if we're done here. this will be overrided by individual commands
Returns
is the function finished
Implements Command.
bool ArcTurn::isFinished () virtual
checked every iteration to see if we're done here. this will be overrided by individual commands
Returns
is the function finished
Implements Command.
References curCol, curDir, curPose, curRow, dYaw, Mouse::getCol(), Mouse::getDir(), RealMouse::getGlobalPose(), Mouse::getRow(), goalYaw, mouse, startCol, startRow, GlobalPose::yaw, and smartmouse::math::yaw_diff().
double ArcTurn::pose_dist (GlobalPose pose, double x, double y) private
double ArcTurn::pose_dist (GlobalPose pose, double x, double y) private
References GlobalPose::col, and GlobalPose::row.
Referenced by execute().
Member Data Documentation
constexpr double ArcTurn::ang_weight = 1.00 static private
Referenced by execute().
constexpr double ArcTurn::arc_weight = 1.00 static private
Referenced by execute().
unsigned int ArcTurn::curCol private
Referenced by initialize(), and isFinished().
Direction ArcTurn::curDir private
Referenced by execute(), initialize(), and isFinished().
GlobalPose ArcTurn::curPose private
Referenced by execute(), initialize(), and isFinished().
unsigned int ArcTurn::curRow private
Referenced by initialize(), and isFinished().
double ArcTurn::dDisp private
Direction ArcTurn::dir private
Referenced by end(), execute(), and initialize().
double ArcTurn::dYaw private
Referenced by isFinished().
double ArcTurn::end_x private
double ArcTurn::end_y private
double ArcTurn::FAST_ARC_SPEED = speed_scale * (smartmouse::kc::MAX_SPEED_CUPS) private
Referenced by execute().
double ArcTurn::goalYaw private
Referenced by initialize(), and isFinished().
constexpr double ArcTurn::kp_turn = 3.00 static private
Referenced by execute().
RealMouse* ArcTurn::mouse private
Referenced by end(), execute(), initialize(), and isFinished().
SimMouse* ArcTurn::mouse private
double ArcTurn::SLOW_ARC_SPEED private
Initial value:
=
      speed_scale * (smartmouse::kc::MAX_SPEED_CUPS / (smartmouse::maze::HALF_UNIT_DIST + (smartmouse::kc::TRACK_WIDTH_M / 2)))
          *
              (smartmouse::maze::HALF_UNIT_DIST - (smartmouse::kc::TRACK_WIDTH_M / 2))
Referenced by execute().
constexpr double ArcTurn::speed_scale = 0.75 static private
unsigned int ArcTurn::startCol private
Referenced by initialize(), and isFinished().
GlobalPose ArcTurn::startPose private
Referenced by initialize().
unsigned int ArcTurn::startRow private
Referenced by initialize(), and isFinished().
double ArcTurn::vtc_x private
Referenced by execute(), and initialize().
double ArcTurn::vtc_y private
Referenced by execute(), and initialize().
The documentation for this class was generated from the following files:
real/commands/ArcTurn.h
real/commands/ArcTurn.cpp