SmartMouse_2018: Eigen::FullPivHouseholderQR< _MatrixType > Class Template Reference
Eigen::FullPivHouseholderQR< _MatrixType > Class Template Reference
Householder rank-revealing QR decomposition of a matrix with full pivoting.
#include <ForwardDeclarations.h>
Public Types
enum { RowsAtCompileTime = MatrixType::RowsAtCompileTime, ColsAtCompileTime = MatrixType::ColsAtCompileTime, MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime, MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime }
typedef _MatrixType MatrixType
typedef MatrixType::Scalar Scalar
typedef MatrixType::RealScalar RealScalar
typedef MatrixType::StorageIndex StorageIndex
typedef internal::FullPivHouseholderQRMatrixQReturnType< MatrixType > MatrixQReturnType
typedef internal::plain_diag_type< MatrixType >::type HCoeffsType
typedef Matrix< StorageIndex, 1, EIGEN_SIZE_MIN_PREFER_DYNAMIC(ColsAtCompileTime, RowsAtCompileTime), RowMajor, 1, EIGEN_SIZE_MIN_PREFER_FIXED(MaxColsAtCompileTime, MaxRowsAtCompileTime)> IntDiagSizeVectorType
typedef PermutationMatrix< ColsAtCompileTime, MaxColsAtCompileTime > PermutationType
typedef internal::plain_row_type< MatrixType >::type RowVectorType
typedef internal::plain_col_type< MatrixType >::type ColVectorType
typedef MatrixType::PlainObject PlainObject
Public Member Functions
FullPivHouseholderQR ()
Default Constructor.
FullPivHouseholderQR (Index rows, Index cols)
Default Constructor with memory preallocation.
template<typename InputType >
FullPivHouseholderQR (const EigenBase< InputType > &matrix)
Constructs a QR factorization from a given matrix.
template<typename InputType >
FullPivHouseholderQR (EigenBase< InputType > &matrix)
Constructs a QR factorization from a given matrix.
template<typename Rhs >
const Solve< FullPivHouseholderQR, Rhs > solve (const MatrixBase< Rhs > &b) const
MatrixQReturnType matrixQ (void) const
const MatrixType & matrixQR () const
template<typename InputType >
FullPivHouseholderQR & compute (const EigenBase< InputType > &matrix)
const PermutationType & colsPermutation () const
const IntDiagSizeVectorType & rowsTranspositions () const
MatrixType::RealScalar absDeterminant () const
MatrixType::RealScalar logAbsDeterminant () const
Index rank () const
Index dimensionOfKernel () const
bool isInjective () const
bool isSurjective () const
bool isInvertible () const
const Inverse< FullPivHouseholderQR > inverse () const
Index rows () const
Index cols () const
const HCoeffsType & hCoeffs () const
FullPivHouseholderQR & setThreshold (const RealScalar &threshold)
FullPivHouseholderQR & setThreshold (Default_t)
RealScalar threshold () const
Index nonzeroPivots () const
RealScalar maxPivot () const
template<typename RhsType , typename DstType >
void _solve_impl (const RhsType &rhs, DstType &dst) const
template<typename InputType >
FullPivHouseholderQR< MatrixType > & compute (const EigenBase< InputType > &matrix)
Protected Member Functions
void computeInPlace ()
Static Protected Member Functions
static void check_template_parameters ()
Protected Attributes
MatrixType m_qr
HCoeffsType m_hCoeffs
IntDiagSizeVectorType m_rows_transpositions
IntDiagSizeVectorType m_cols_transpositions
PermutationType m_cols_permutation
RowVectorType m_temp
bool m_isInitialized
bool m_usePrescribedThreshold
RealScalar m_prescribedThreshold
RealScalar m_maxpivot
Index m_nonzero_pivots
RealScalar m_precision
Index m_det_pq
Detailed Description
template<typename _MatrixType>
class Eigen::FullPivHouseholderQR< _MatrixType >
Householder rank-revealing QR decomposition of a matrix with full pivoting.
Template Parameters
_MatrixType the type of the matrix of which we are computing the QR decomposition
This class performs a rank-revealing QR decomposition of a matrix A into matrices P, P', Q and R such that
by using Householder transformations. Here, P and P' are permutation matrices, Q a unitary matrix and R an upper triangular matrix.
This decomposition performs a very prudent full pivoting in order to be rank-revealing and achieve optimal numerical stability. The trade-off is that it is slower than HouseholderQR and ColPivHouseholderQR.
This class supports the inplace decomposition mechanism.
See also
MatrixBase::fullPivHouseholderQr()
Member Typedef Documentation
template<typename _MatrixType> typedef internal::plain_col_type<MatrixType>::type Eigen::FullPivHouseholderQR< _MatrixType >::ColVectorType
template<typename _MatrixType> typedef internal::plain_diag_type<MatrixType>::type Eigen::FullPivHouseholderQR< _MatrixType >::HCoeffsType
template<typename _MatrixType> typedef Matrix<StorageIndex, 1, EIGEN_SIZE_MIN_PREFER_DYNAMIC(ColsAtCompileTime,RowsAtCompileTime), RowMajor, 1, EIGEN_SIZE_MIN_PREFER_FIXED(MaxColsAtCompileTime,MaxRowsAtCompileTime)> Eigen::FullPivHouseholderQR< _MatrixType >::IntDiagSizeVectorType
template<typename _MatrixType> typedef internal::FullPivHouseholderQRMatrixQReturnType<MatrixType> Eigen::FullPivHouseholderQR< _MatrixType >::MatrixQReturnType
template<typename _MatrixType> typedef _MatrixType Eigen::FullPivHouseholderQR< _MatrixType >::MatrixType
template<typename _MatrixType> typedef PermutationMatrix<ColsAtCompileTime, MaxColsAtCompileTime> Eigen::FullPivHouseholderQR< _MatrixType >::PermutationType
template<typename _MatrixType> typedef MatrixType::PlainObject Eigen::FullPivHouseholderQR< _MatrixType >::PlainObject
template<typename _MatrixType> typedef MatrixType::RealScalar Eigen::FullPivHouseholderQR< _MatrixType >::RealScalar
template<typename _MatrixType> typedef internal::plain_row_type<MatrixType>::type Eigen::FullPivHouseholderQR< _MatrixType >::RowVectorType
template<typename _MatrixType> typedef MatrixType::Scalar Eigen::FullPivHouseholderQR< _MatrixType >::Scalar
template<typename _MatrixType> typedef MatrixType::StorageIndex Eigen::FullPivHouseholderQR< _MatrixType >::StorageIndex
Member Enumeration Documentation
template<typename _MatrixType> anonymous enum
Enumerator
RowsAtCompileTime
ColsAtCompileTime
MaxRowsAtCompileTime
MaxColsAtCompileTime
Constructor & Destructor Documentation
template<typename _MatrixType> Eigen::FullPivHouseholderQR< _MatrixType >::FullPivHouseholderQR () inline
Default Constructor.
The default constructor is useful in cases in which the user intends to perform decompositions via FullPivHouseholderQR::compute(const MatrixType&).
template<typename _MatrixType> Eigen::FullPivHouseholderQR< _MatrixType >::FullPivHouseholderQR (Index rows, Index cols) inline
Default Constructor with memory preallocation.
Like the default constructor but with preallocation of the internal data according to the specified problem size.
See also
FullPivHouseholderQR()
template<typename _MatrixType> template<typename InputType > Eigen::FullPivHouseholderQR< _MatrixType >::FullPivHouseholderQR (const EigenBase< InputType > & matrix) inline explicit
Constructs a QR factorization from a given matrix.
This constructor computes the QR factorization of the matrix matrix by calling the method compute(). It is a short cut for:
FullPivHouseholderQR<MatrixType> qr(matrix.rows(), matrix.cols());
qr.compute(matrix);
See also
compute()
template<typename _MatrixType> template<typename InputType > Eigen::FullPivHouseholderQR< _MatrixType >::FullPivHouseholderQR (EigenBase< InputType > & matrix) inline explicit
Constructs a QR factorization from a given matrix.
This overloaded constructor is provided for inplace decomposition when MatrixType is a Eigen::Ref.
See also
FullPivHouseholderQR(const EigenBase&)
Member Function Documentation
template<typename _MatrixType > template<typename RhsType , typename DstType > void Eigen::FullPivHouseholderQR< _MatrixType >::_solve_impl (const RhsType & rhs, DstType & dst) const
References eigen_assert, i, and Eigen::PlainObjectBase< Derived >::swap().
template<typename MatrixType > MatrixType::RealScalar Eigen::FullPivHouseholderQR< MatrixType >::absDeterminant () const
Returns
the absolute value of the determinant of the matrix of which *this is the QR decomposition. It has only linear complexity (that is, O(n) where n is the dimension of the square matrix) as the QR decomposition has already been computed.
Note
This is only for square matrices.
Warning
a determinant can be very big or small, so for matrices of large enough dimension, there is a risk of overflow/underflow. One way to work around that is to use logAbsDeterminant() instead.
See also
logAbsDeterminant(), MatrixBase::determinant()
References abs(), and eigen_assert.
template<typename _MatrixType> static void Eigen::FullPivHouseholderQR< _MatrixType >::check_template_parameters () inline static protected
template<typename _MatrixType> Index Eigen::FullPivHouseholderQR< _MatrixType >::cols (void) const inline
template<typename _MatrixType> const PermutationType& Eigen::FullPivHouseholderQR< _MatrixType >::colsPermutation () const inline
Returns
a const reference to the column permutation matrix
template<typename _MatrixType> template<typename InputType > FullPivHouseholderQR& Eigen::FullPivHouseholderQR< _MatrixType >::compute (const EigenBase< InputType > & matrix)
template<typename _MatrixType> template<typename InputType > FullPivHouseholderQR<MatrixType>& Eigen::FullPivHouseholderQR< _MatrixType >::compute (const EigenBase< InputType > & matrix)
Performs the QR factorization of the given matrix matrix. The result of the factorization is stored into *this, and a reference to *this is returned.
See also
class FullPivHouseholderQR, FullPivHouseholderQR(const MatrixType&)
References Eigen::EigenBase< Derived >::derived().
template<typename MatrixType > void Eigen::FullPivHouseholderQR< MatrixType >::computeInPlace () protected
References abs(), i, Eigen::half_impl::min(), and Eigen::internal::size().
template<typename _MatrixType> Index Eigen::FullPivHouseholderQR< _MatrixType >::dimensionOfKernel () const inline
Returns
the dimension of the kernel of the matrix of which *this is the QR decomposition.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
template<typename _MatrixType> const HCoeffsType& Eigen::FullPivHouseholderQR< _MatrixType >::hCoeffs () const inline
Returns
a const reference to the vector of Householder coefficients used to represent the factor Q.
For advanced uses only.
template<typename _MatrixType> const Inverse<FullPivHouseholderQR> Eigen::FullPivHouseholderQR< _MatrixType >::inverse () const inline
Returns
the inverse of the matrix of which *this is the QR decomposition.
Note
If this matrix is not invertible, the returned matrix has undefined coefficients. Use isInvertible() to first determine whether this matrix is invertible.
template<typename _MatrixType> bool Eigen::FullPivHouseholderQR< _MatrixType >::isInjective () const inline
Returns
true if the matrix of which *this is the QR decomposition represents an injective linear map, i.e. has trivial kernel; false otherwise.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
template<typename _MatrixType> bool Eigen::FullPivHouseholderQR< _MatrixType >::isInvertible () const inline
Returns
true if the matrix of which *this is the QR decomposition is invertible.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
template<typename _MatrixType> bool Eigen::FullPivHouseholderQR< _MatrixType >::isSurjective () const inline
Returns
true if the matrix of which *this is the QR decomposition represents a surjective linear map; false otherwise.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
template<typename MatrixType > MatrixType::RealScalar Eigen::FullPivHouseholderQR< MatrixType >::logAbsDeterminant () const
Returns
the natural log of the absolute value of the determinant of the matrix of which *this is the QR decomposition. It has only linear complexity (that is, O(n) where n is the dimension of the square matrix) as the QR decomposition has already been computed.
Note
This is only for square matrices.
This method is useful to work around the risk of overflow/underflow that's inherent to determinant computation.
See also
absDeterminant(), MatrixBase::determinant()
References eigen_assert.
template<typename MatrixType > FullPivHouseholderQR< MatrixType >::MatrixQReturnType Eigen::FullPivHouseholderQR< MatrixType >::matrixQ (void) const inline
Returns
Expression object representing the matrix Q
References eigen_assert.
template<typename _MatrixType> const MatrixType& Eigen::FullPivHouseholderQR< _MatrixType >::matrixQR () const inline
Returns
a reference to the matrix where the Householder QR decomposition is stored
template<typename _MatrixType> RealScalar Eigen::FullPivHouseholderQR< _MatrixType >::maxPivot () const inline
Returns
the absolute value of the biggest pivot, i.e. the biggest diagonal coefficient of U.
template<typename _MatrixType> Index Eigen::FullPivHouseholderQR< _MatrixType >::nonzeroPivots () const inline
Returns
the number of nonzero pivots in the QR decomposition. Here nonzero is meant in the exact sense, not in a fuzzy sense. So that notion isn't really intrinsically interesting, but it is still useful when implementing algorithms.
See also
rank()
template<typename _MatrixType> Index Eigen::FullPivHouseholderQR< _MatrixType >::rank () const inline
Returns
the rank of the matrix of which *this is the QR decomposition.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
template<typename _MatrixType> Index Eigen::FullPivHouseholderQR< _MatrixType >::rows (void) const inline
template<typename _MatrixType> const IntDiagSizeVectorType& Eigen::FullPivHouseholderQR< _MatrixType >::rowsTranspositions () const inline
Returns
a const reference to the vector of indices representing the rows transpositions
template<typename _MatrixType> FullPivHouseholderQR& Eigen::FullPivHouseholderQR< _MatrixType >::setThreshold (const RealScalar & threshold) inline
Allows to prescribe a threshold to be used by certain methods, such as rank(), who need to determine when pivots are to be considered nonzero. This is not used for the QR decomposition itself.
When it needs to get the threshold value, Eigen calls threshold(). By default, this uses a formula to automatically determine a reasonable threshold. Once you have called the present method setThreshold(const RealScalar&), your value is used instead.
Parameters
threshold The new value to use as the threshold.
A pivot will be considered nonzero if its absolute value is strictly greater than where maxpivot is the biggest pivot.
If you want to come back to the default behavior, call setThreshold(Default_t)
template<typename _MatrixType> FullPivHouseholderQR& Eigen::FullPivHouseholderQR< _MatrixType >::setThreshold (Default_t) inline
Allows to come back to the default behavior, letting Eigen use its default formula for determining the threshold.
You should pass the special object Eigen::Default as parameter here.
qr.setThreshold(Eigen::Default);
See the documentation of setThreshold(const RealScalar&).
template<typename _MatrixType> template<typename Rhs > const Solve<FullPivHouseholderQR, Rhs> Eigen::FullPivHouseholderQR< _MatrixType >::solve (const MatrixBase< Rhs > & b) const inline
This method finds a solution x to the equation Ax=b, where A is the matrix of which *this is the QR decomposition.
Parameters
b the right-hand-side of the equation to solve.
Returns
the exact or least-square solution if the rank is greater or equal to the number of columns of A, and an arbitrary solution otherwise.
Example:
Output:
template<typename _MatrixType> RealScalar Eigen::FullPivHouseholderQR< _MatrixType >::threshold () const inline
Returns the threshold that will be used by certain methods such as rank().
See the documentation of setThreshold(const RealScalar&).
Member Data Documentation
template<typename _MatrixType> PermutationType Eigen::FullPivHouseholderQR< _MatrixType >::m_cols_permutation protected
template<typename _MatrixType> IntDiagSizeVectorType Eigen::FullPivHouseholderQR< _MatrixType >::m_cols_transpositions protected
template<typename _MatrixType> Index Eigen::FullPivHouseholderQR< _MatrixType >::m_det_pq protected
template<typename _MatrixType> HCoeffsType Eigen::FullPivHouseholderQR< _MatrixType >::m_hCoeffs protected
template<typename _MatrixType> bool Eigen::FullPivHouseholderQR< _MatrixType >::m_isInitialized protected
template<typename _MatrixType> RealScalar Eigen::FullPivHouseholderQR< _MatrixType >::m_maxpivot protected
template<typename _MatrixType> Index Eigen::FullPivHouseholderQR< _MatrixType >::m_nonzero_pivots protected
template<typename _MatrixType> RealScalar Eigen::FullPivHouseholderQR< _MatrixType >::m_precision protected
template<typename _MatrixType> RealScalar Eigen::FullPivHouseholderQR< _MatrixType >::m_prescribedThreshold protected
template<typename _MatrixType> MatrixType Eigen::FullPivHouseholderQR< _MatrixType >::m_qr protected
template<typename _MatrixType> IntDiagSizeVectorType Eigen::FullPivHouseholderQR< _MatrixType >::m_rows_transpositions protected
template<typename _MatrixType> RowVectorType Eigen::FullPivHouseholderQR< _MatrixType >::m_temp protected
template<typename _MatrixType> bool Eigen::FullPivHouseholderQR< _MatrixType >::m_usePrescribedThreshold protected
The documentation for this class was generated from the following files:
ForwardDeclarations.h
FullPivHouseholderQR.h