SmartMouse_2018: Eigen::SimplicialCholeskyBase< Derived > Class Template Reference
Eigen::SimplicialCholeskyBase< Derived > Class Template Reference
A base class for direct sparse Cholesky factorizations.
#include <SimplicialCholesky.h>
Classes
struct keep_diag
Public Types
enum { UpLo = internal::traits<Derived>::UpLo }
enum { ColsAtCompileTime = MatrixType::ColsAtCompileTime, MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime }
typedef internal::traits< Derived >::MatrixType MatrixType
typedef internal::traits< Derived >::OrderingType OrderingType
typedef MatrixType::Scalar Scalar
typedef MatrixType::RealScalar RealScalar
typedef MatrixType::StorageIndex StorageIndex
typedef SparseMatrix< Scalar, ColMajor, StorageIndex > CholMatrixType
typedef CholMatrixType const * ConstCholMatrixPtr
typedef Matrix< Scalar, Dynamic, 1 > VectorType
typedef Matrix< StorageIndex, Dynamic, 1 > VectorI
Public Member Functions
SimplicialCholeskyBase ()
SimplicialCholeskyBase (const MatrixType &matrix)
~SimplicialCholeskyBase ()
Derived & derived ()
const Derived & derived () const
Index cols () const
Index rows () const
ComputationInfo info () const
Reports whether previous computation was successful.
const PermutationMatrix< Dynamic, Dynamic, StorageIndex > & permutationP () const
const PermutationMatrix< Dynamic, Dynamic, StorageIndex > & permutationPinv () const
Derived & setShift (const RealScalar &offset, const RealScalar &scale=1)
template<typename Stream >
void dumpMemory (Stream &s)
template<typename Rhs , typename Dest >
void _solve_impl (const MatrixBase< Rhs > &b, MatrixBase< Dest > &dest) const
template<typename Rhs , typename Dest >
void _solve_impl (const SparseMatrixBase< Rhs > &b, SparseMatrixBase< Dest > &dest) const
Public Member Functions inherited from Eigen::SparseSolverBase< Derived >
SparseSolverBase ()
~SparseSolverBase ()
Derived & derived ()
const Derived & derived () const
template<typename Rhs >
const Solve< Derived, Rhs > solve (const MatrixBase< Rhs > &b) const
template<typename Rhs >
const Solve< Derived, Rhs > solve (const SparseMatrixBase< Rhs > &b) const
template<typename Rhs , typename Dest >
void _solve_impl (const SparseMatrixBase< Rhs > &b, SparseMatrixBase< Dest > &dest) const
Protected Member Functions
template<bool DoLDLT>
void compute (const MatrixType &matrix)
template<bool DoLDLT>
void factorize (const MatrixType &a)
template<bool DoLDLT>
void factorize_preordered (const CholMatrixType &a)
void analyzePattern (const MatrixType &a, bool doLDLT)
void analyzePattern_preordered (const CholMatrixType &a, bool doLDLT)
void ordering (const MatrixType &a, ConstCholMatrixPtr &pmat, CholMatrixType &ap)
Protected Attributes
ComputationInfo m_info
bool m_factorizationIsOk
bool m_analysisIsOk
CholMatrixType m_matrix
VectorType m_diag
VectorI m_parent
VectorI m_nonZerosPerCol
PermutationMatrix< Dynamic, Dynamic, StorageIndex > m_P
PermutationMatrix< Dynamic, Dynamic, StorageIndex > m_Pinv
RealScalar m_shiftOffset
RealScalar m_shiftScale
Protected Attributes inherited from Eigen::SparseSolverBase< Derived >
bool m_isInitialized
Private Types
typedef SparseSolverBase< Derived > Base
Detailed Description
template<typename Derived>
class Eigen::SimplicialCholeskyBase< Derived >
A base class for direct sparse Cholesky factorizations.
This is a base class for LL^T and LDL^T Cholesky factorizations of sparse matrices that are selfadjoint and positive definite. These factorizations allow for solving A.X = B where X and B can be either dense or sparse.
In order to reduce the fill-in, a symmetric permutation P is applied prior to the factorization such that the factorized matrix is P A P^-1.
Template Parameters
Derived the type of the derived class, that is the actual factorization type.
Member Typedef Documentation
template<typename Derived> typedef SparseSolverBase<Derived> Eigen::SimplicialCholeskyBase< Derived >::Base private
template<typename Derived> typedef SparseMatrix<Scalar,ColMajor,StorageIndex> Eigen::SimplicialCholeskyBase< Derived >::CholMatrixType
template<typename Derived> typedef CholMatrixType const* Eigen::SimplicialCholeskyBase< Derived >::ConstCholMatrixPtr
template<typename Derived> typedef internal::traits<Derived>::MatrixType Eigen::SimplicialCholeskyBase< Derived >::MatrixType
template<typename Derived> typedef internal::traits<Derived>::OrderingType Eigen::SimplicialCholeskyBase< Derived >::OrderingType
template<typename Derived> typedef MatrixType::RealScalar Eigen::SimplicialCholeskyBase< Derived >::RealScalar
template<typename Derived> typedef MatrixType::Scalar Eigen::SimplicialCholeskyBase< Derived >::Scalar
template<typename Derived> typedef MatrixType::StorageIndex Eigen::SimplicialCholeskyBase< Derived >::StorageIndex
template<typename Derived> typedef Matrix<StorageIndex,Dynamic,1> Eigen::SimplicialCholeskyBase< Derived >::VectorI
template<typename Derived> typedef Matrix<Scalar,Dynamic,1> Eigen::SimplicialCholeskyBase< Derived >::VectorType
Member Enumeration Documentation
template<typename Derived> anonymous enum
Enumerator
UpLo
template<typename Derived> anonymous enum
Enumerator
ColsAtCompileTime
MaxColsAtCompileTime
Constructor & Destructor Documentation
template<typename Derived> Eigen::SimplicialCholeskyBase< Derived >::SimplicialCholeskyBase () inline
Default constructor
template<typename Derived> Eigen::SimplicialCholeskyBase< Derived >::SimplicialCholeskyBase (const MatrixType & matrix) inline explicit
template<typename Derived> Eigen::SimplicialCholeskyBase< Derived >::~SimplicialCholeskyBase () inline
Member Function Documentation
template<typename Derived> template<typename Rhs , typename Dest > void Eigen::SimplicialCholeskyBase< Derived >::_solve_impl (const MatrixBase< Rhs > & b, MatrixBase< Dest > & dest) const inline
template<typename Derived> template<typename Rhs , typename Dest > void Eigen::SimplicialCholeskyBase< Derived >::_solve_impl (const SparseMatrixBase< Rhs > & b, SparseMatrixBase< Dest > & dest) const inline
template<typename Derived> void Eigen::SimplicialCholeskyBase< Derived >::analyzePattern (const MatrixType & a, bool doLDLT) inline protected
template<typename Derived > void Eigen::SimplicialCholeskyBase< Derived >::analyzePattern_preordered (const CholMatrixType & a, bool doLDLT) protected
References ei_declare_aligned_stack_constructed_variable, i, it, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::rows(), Eigen::internal::size(), and Eigen::Success.
template<typename Derived> Index Eigen::SimplicialCholeskyBase< Derived >::cols (void) const inline
template<typename Derived> template<bool DoLDLT> void Eigen::SimplicialCholeskyBase< Derived >::compute (const MatrixType & matrix) inline protected
Computes the sparse Cholesky decomposition of matrix
template<typename Derived> Derived& Eigen::SimplicialCholeskyBase< Derived >::derived () inline
template<typename Derived> const Derived& Eigen::SimplicialCholeskyBase< Derived >::derived () const inline
template<typename Derived> template<typename Stream > void Eigen::SimplicialCholeskyBase< Derived >::dumpMemory (Stream & s) inline
template<typename Derived> template<bool DoLDLT> void Eigen::SimplicialCholeskyBase< Derived >::factorize (const MatrixType & a) inline protected
template<typename Derived > template<bool DoLDLT> void Eigen::SimplicialCholeskyBase< Derived >::factorize_preordered (const CholMatrixType & a) protected
References Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::cols(), ei_declare_aligned_stack_constructed_variable, eigen_assert, i, it, Eigen::NumericalIssue, real(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::rows(), Eigen::internal::size(), sqrt(), and Eigen::Success.
template<typename Derived> ComputationInfo Eigen::SimplicialCholeskyBase< Derived >::info () const inline
Reports whether previous computation was successful.
Returns
Success if computation was succesful, NumericalIssue if the matrix.appears to be negative.
template<typename Derived > void Eigen::SimplicialCholeskyBase< Derived >::ordering (const MatrixType & a, ConstCholMatrixPtr & pmat, CholMatrixType & ap) protected
References eigen_assert, Eigen::Lower, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::resize(), Eigen::internal::simplicial_cholesky_grab_input< CholMatrixType, InputMatrixType >::run(), Eigen::internal::size(), and Eigen::SparseMatrixBase< Derived >::twistedBy().
template<typename Derived> const PermutationMatrix<Dynamic,Dynamic,StorageIndex>& Eigen::SimplicialCholeskyBase< Derived >::permutationP () const inline
Returns
the permutation P
See also
permutationPinv()
template<typename Derived> const PermutationMatrix<Dynamic,Dynamic,StorageIndex>& Eigen::SimplicialCholeskyBase< Derived >::permutationPinv () const inline
Returns
the inverse P^-1 of the permutation P
See also
permutationP()
template<typename Derived> Index Eigen::SimplicialCholeskyBase< Derived >::rows (void) const inline
template<typename Derived> Derived& Eigen::SimplicialCholeskyBase< Derived >::setShift (const RealScalar & offset, const RealScalar & scale = 1) inline
Sets the shift parameters that will be used to adjust the diagonal coefficients during the numerical factorization.
During the numerical factorization, the diagonal coefficients are transformed by the following linear model:
d_ii = offset + scale * d_ii
The default is the identity transformation with offset=0, and scale=1.
Returns
a reference to *this.
Member Data Documentation
template<typename Derived> bool Eigen::SimplicialCholeskyBase< Derived >::m_analysisIsOk protected
template<typename Derived> VectorType Eigen::SimplicialCholeskyBase< Derived >::m_diag protected
template<typename Derived> bool Eigen::SimplicialCholeskyBase< Derived >::m_factorizationIsOk protected
template<typename Derived> ComputationInfo Eigen::SimplicialCholeskyBase< Derived >::m_info mutable protected
template<typename Derived> CholMatrixType Eigen::SimplicialCholeskyBase< Derived >::m_matrix protected
template<typename Derived> VectorI Eigen::SimplicialCholeskyBase< Derived >::m_nonZerosPerCol protected
template<typename Derived> PermutationMatrix<Dynamic,Dynamic,StorageIndex> Eigen::SimplicialCholeskyBase< Derived >::m_P protected
template<typename Derived> VectorI Eigen::SimplicialCholeskyBase< Derived >::m_parent protected
template<typename Derived> PermutationMatrix<Dynamic,Dynamic,StorageIndex> Eigen::SimplicialCholeskyBase< Derived >::m_Pinv protected
template<typename Derived> RealScalar Eigen::SimplicialCholeskyBase< Derived >::m_shiftOffset protected
template<typename Derived> RealScalar Eigen::SimplicialCholeskyBase< Derived >::m_shiftScale protected
The documentation for this class was generated from the following files:
SimplicialCholesky.h
SimplicialCholesky_impl.h