SmartMouse_2018: Eigen::SVDBase< Derived > Class Template Reference
Eigen::SVDBase< Derived > Class Template Reference
Base class of SVD algorithms.
#include <SVDBase.h>
Public Types
enum {
RowsAtCompileTime = MatrixType::RowsAtCompileTime, ColsAtCompileTime = MatrixType::ColsAtCompileTime, DiagSizeAtCompileTime = EIGEN_SIZE_MIN_PREFER_DYNAMIC(RowsAtCompileTime,ColsAtCompileTime), MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime,
MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime, MaxDiagSizeAtCompileTime = EIGEN_SIZE_MIN_PREFER_FIXED(MaxRowsAtCompileTime,MaxColsAtCompileTime), MatrixOptions = MatrixType::Options
}
typedef internal::traits< Derived >::MatrixType MatrixType
typedef MatrixType::Scalar Scalar
typedef NumTraits< typename MatrixType::Scalar >::Real RealScalar
typedef MatrixType::StorageIndex StorageIndex
typedef Eigen::Index Index
typedef Matrix< Scalar, RowsAtCompileTime, RowsAtCompileTime, MatrixOptions, MaxRowsAtCompileTime, MaxRowsAtCompileTime > MatrixUType
typedef Matrix< Scalar, ColsAtCompileTime, ColsAtCompileTime, MatrixOptions, MaxColsAtCompileTime, MaxColsAtCompileTime > MatrixVType
typedef internal::plain_diag_type< MatrixType, RealScalar >::type SingularValuesType
Public Member Functions
Derived & derived ()
const Derived & derived () const
const MatrixUType & matrixU () const
const MatrixVType & matrixV () const
const SingularValuesType & singularValues () const
Index nonzeroSingularValues () const
Index rank () const
Derived & setThreshold (const RealScalar &threshold)
Derived & setThreshold (Default_t)
RealScalar threshold () const
bool computeU () const
bool computeV () const
Index rows () const
Index cols () const
template<typename Rhs >
const Solve< Derived, Rhs > solve (const MatrixBase< Rhs > &b) const
template<typename RhsType , typename DstType >
void _solve_impl (const RhsType &rhs, DstType &dst) const
Protected Member Functions
bool allocate (Index rows, Index cols, unsigned int computationOptions)
SVDBase ()
Default Constructor.
Static Protected Member Functions
static void check_template_parameters ()
Protected Attributes
MatrixUType m_matrixU
MatrixVType m_matrixV
SingularValuesType m_singularValues
bool m_isInitialized
bool m_isAllocated
bool m_usePrescribedThreshold
bool m_computeFullU
bool m_computeThinU
bool m_computeFullV
bool m_computeThinV
unsigned int m_computationOptions
Index m_nonzeroSingularValues
Index m_rows
Index m_cols
Index m_diagSize
RealScalar m_prescribedThreshold
Detailed Description
template<typename Derived>
class Eigen::SVDBase< Derived >
Base class of SVD algorithms.
Template Parameters
Derived the type of the actual SVD decomposition
SVD decomposition consists in decomposing any n-by-p matrix A as a product
where U is a n-by-n unitary, V is a p-by-p unitary, and S is a n-by-p real positive matrix which is zero outside of its main diagonal; the diagonal entries of S are known as the singular values of A and the columns of U and V are known as the left and right singular vectors of A respectively.
Singular values are always sorted in decreasing order.
You can ask for only thin U or V to be computed, meaning the following. In case of a rectangular n-by-p matrix, letting m be the smaller value among n and p, there are only m singular vectors; the remaining columns of U and V do not correspond to actual singular vectors. Asking for thin U or V means asking for only their m first columns to be formed. So U is then a n-by-m matrix, and V is then a p-by-m matrix. Notice that thin U and V are all you need for (least squares) solving.
If the input matrix has inf or nan coefficients, the result of the computation is undefined, but the computation is guaranteed to terminate in finite (and reasonable) time.
See also
class BDCSVD, class JacobiSVD
Member Typedef Documentation
template<typename Derived> typedef Eigen::Index Eigen::SVDBase< Derived >::Index
Deprecated:
since Eigen 3.3
template<typename Derived> typedef internal::traits<Derived>::MatrixType Eigen::SVDBase< Derived >::MatrixType
template<typename Derived> typedef Matrix<Scalar, RowsAtCompileTime, RowsAtCompileTime, MatrixOptions, MaxRowsAtCompileTime, MaxRowsAtCompileTime> Eigen::SVDBase< Derived >::MatrixUType
template<typename Derived> typedef Matrix<Scalar, ColsAtCompileTime, ColsAtCompileTime, MatrixOptions, MaxColsAtCompileTime, MaxColsAtCompileTime> Eigen::SVDBase< Derived >::MatrixVType
template<typename Derived> typedef NumTraits<typename MatrixType::Scalar>::Real Eigen::SVDBase< Derived >::RealScalar
template<typename Derived> typedef MatrixType::Scalar Eigen::SVDBase< Derived >::Scalar
template<typename Derived> typedef internal::plain_diag_type<MatrixType, RealScalar>::type Eigen::SVDBase< Derived >::SingularValuesType
template<typename Derived> typedef MatrixType::StorageIndex Eigen::SVDBase< Derived >::StorageIndex
Member Enumeration Documentation
template<typename Derived> anonymous enum
Enumerator
RowsAtCompileTime
ColsAtCompileTime
DiagSizeAtCompileTime
MaxRowsAtCompileTime
MaxColsAtCompileTime
MaxDiagSizeAtCompileTime
MatrixOptions
Constructor & Destructor Documentation
template<typename Derived> Eigen::SVDBase< Derived >::SVDBase () inline protected
Default Constructor.
Default constructor of SVDBase
Member Function Documentation
template<typename Derived > template<typename RhsType , typename DstType > void Eigen::SVDBase< Derived >::_solve_impl (const RhsType & rhs, DstType & dst) const
References eigen_assert, Eigen::SVDBase< Derived >::m_matrixU, Eigen::SVDBase< Derived >::m_matrixV, Eigen::SVDBase< Derived >::m_singularValues, Eigen::SVDBase< Derived >::rank(), and Eigen::SVDBase< Derived >::rows().
Referenced by Eigen::SVDBase< BDCSVD< _MatrixType > >::solve().
template<typename MatrixType > bool Eigen::SVDBase< MatrixType >::allocate (Index rows, Index cols, unsigned int computationOptions) protected
References Eigen::SVDBase< Derived >::cols(), Eigen::SVDBase< Derived >::ColsAtCompileTime, Eigen::ComputeFullU, Eigen::ComputeFullV, Eigen::ComputeThinU, Eigen::ComputeThinV, Eigen::Dynamic, eigen_assert, EIGEN_IMPLIES, Eigen::SVDBase< Derived >::m_cols, Eigen::SVDBase< Derived >::m_computationOptions, Eigen::SVDBase< Derived >::m_computeFullU, Eigen::SVDBase< Derived >::m_computeFullV, Eigen::SVDBase< Derived >::m_computeThinU, Eigen::SVDBase< Derived >::m_computeThinV, Eigen::SVDBase< Derived >::m_diagSize, Eigen::SVDBase< Derived >::m_isAllocated, Eigen::SVDBase< Derived >::m_isInitialized, Eigen::SVDBase< Derived >::m_matrixU, Eigen::SVDBase< Derived >::m_matrixV, Eigen::SVDBase< Derived >::m_rows, Eigen::SVDBase< Derived >::m_singularValues, Eigen::half_impl::min(), Eigen::PlainObjectBase< Derived >::resize(), Eigen::SVDBase< Derived >::rows(), and Eigen::SVDBase< Derived >::RowsAtCompileTime.
Referenced by Eigen::SVDBase< BDCSVD< _MatrixType > >::check_template_parameters().
template<typename Derived> static void Eigen::SVDBase< Derived >::check_template_parameters () inline static protected
Referenced by Eigen::SVDBase< BDCSVD< _MatrixType > >::SVDBase().
template<typename Derived> Index Eigen::SVDBase< Derived >::cols (void) const inline
Referenced by Eigen::SVDBase< Derived >::allocate(), and Eigen::SVDBase< BDCSVD< _MatrixType > >::check_template_parameters().
template<typename Derived> bool Eigen::SVDBase< Derived >::computeU () const inline
Returns
true if U (full or thin) is asked for in this SVD decomposition
Referenced by Eigen::SVDBase< BDCSVD< _MatrixType > >::matrixU(), Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::run(), and Eigen::SVDBase< BDCSVD< _MatrixType > >::solve().
template<typename Derived> bool Eigen::SVDBase< Derived >::computeV () const inline
Returns
true if V (full or thin) is asked for in this SVD decomposition
Referenced by Eigen::SVDBase< BDCSVD< _MatrixType > >::matrixV(), Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::run(), and Eigen::SVDBase< BDCSVD< _MatrixType > >::solve().
template<typename Derived> Derived& Eigen::SVDBase< Derived >::derived () inline
Referenced by Eigen::SVDBase< BDCSVD< _MatrixType > >::setThreshold(), and Eigen::SVDBase< BDCSVD< _MatrixType > >::solve().
template<typename Derived> const Derived& Eigen::SVDBase< Derived >::derived () const inline
template<typename Derived> const MatrixUType& Eigen::SVDBase< Derived >::matrixU () const inline
Returns
the U matrix.
For the SVD decomposition of a n-by-p matrix, letting m be the minimum of n and p, the U matrix is n-by-n if you asked for ComputeFullU , and is n-by-m if you asked for ComputeThinU .
The m first columns of U are the left singular vectors of the matrix being decomposed.
This method asserts that you asked for U to be computed.
template<typename Derived> const MatrixVType& Eigen::SVDBase< Derived >::matrixV () const inline
Returns
the V matrix.
For the SVD decomposition of a n-by-p matrix, letting m be the minimum of n and p, the V matrix is p-by-p if you asked for ComputeFullV , and is p-by-m if you asked for ComputeThinV .
The m first columns of V are the right singular vectors of the matrix being decomposed.
This method asserts that you asked for V to be computed.
template<typename Derived> Index Eigen::SVDBase< Derived >::nonzeroSingularValues () const inline
Returns
the number of singular values that are not exactly 0
template<typename Derived> Index Eigen::SVDBase< Derived >::rank () const inline
Returns
the rank of the matrix of which *this is the SVD.
Note
This method has to determine which singular values should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
Referenced by Eigen::SVDBase< Derived >::_solve_impl().
template<typename Derived> Index Eigen::SVDBase< Derived >::rows (void) const inline
Referenced by Eigen::SVDBase< Derived >::_solve_impl(), Eigen::SVDBase< Derived >::allocate(), and Eigen::SVDBase< BDCSVD< _MatrixType > >::check_template_parameters().
template<typename Derived> Derived& Eigen::SVDBase< Derived >::setThreshold (const RealScalar & threshold) inline
Allows to prescribe a threshold to be used by certain methods, such as rank() and solve(), which need to determine when singular values are to be considered nonzero. This is not used for the SVD decomposition itself.
When it needs to get the threshold value, Eigen calls threshold(). The default is NumTraits<Scalar>::epsilon()
Parameters
threshold The new value to use as the threshold.
A singular value will be considered nonzero if its value is strictly greater than .
If you want to come back to the default behavior, call setThreshold(Default_t)
template<typename Derived> Derived& Eigen::SVDBase< Derived >::setThreshold (Default_t) inline
Allows to come back to the default behavior, letting Eigen use its default formula for determining the threshold.
You should pass the special object Eigen::Default as parameter here.
svd.setThreshold(Eigen::Default);
See the documentation of setThreshold(const RealScalar&).
template<typename Derived> const SingularValuesType& Eigen::SVDBase< Derived >::singularValues () const inline
Returns
the vector of singular values.
For the SVD decomposition of a n-by-p matrix, letting m be the minimum of n and p, the returned vector has size m. Singular values are always sorted in decreasing order.
template<typename Derived> template<typename Rhs > const Solve<Derived, Rhs> Eigen::SVDBase< Derived >::solve (const MatrixBase< Rhs > & b) const inline
Returns
a (least squares) solution of using the current SVD decomposition of A.
Parameters
b the right-hand-side of the equation to solve.
Note
Solving requires both U and V to be computed. Thin U and V are enough, there is no need for full U or V.
SVD solving is implicitly least-squares. Thus, this method serves both purposes of exact solving and least-squares solving. In other words, the returned solution is guaranteed to minimize the Euclidean norm .
template<typename Derived> RealScalar Eigen::SVDBase< Derived >::threshold () const inline
Returns the threshold that will be used by certain methods such as rank().
See the documentation of setThreshold(const RealScalar&).
Referenced by Eigen::SVDBase< BDCSVD< _MatrixType > >::rank(), and Eigen::SVDBase< BDCSVD< _MatrixType > >::setThreshold().
Member Data Documentation
template<typename Derived> Index Eigen::SVDBase< Derived >::m_cols protected
Referenced by Eigen::SVDBase< Derived >::allocate(), and Eigen::SVDBase< BDCSVD< _MatrixType > >::cols().
template<typename Derived> unsigned int Eigen::SVDBase< Derived >::m_computationOptions protected
Referenced by Eigen::SVDBase< Derived >::allocate().
template<typename Derived> bool Eigen::SVDBase< Derived >::m_computeFullU protected
Referenced by Eigen::SVDBase< Derived >::allocate(), and Eigen::SVDBase< BDCSVD< _MatrixType > >::computeU().
template<typename Derived> bool Eigen::SVDBase< Derived >::m_computeFullV protected
Referenced by Eigen::SVDBase< Derived >::allocate(), and Eigen::SVDBase< BDCSVD< _MatrixType > >::computeV().
template<typename Derived> bool Eigen::SVDBase< Derived >::m_computeThinU protected
Referenced by Eigen::SVDBase< Derived >::allocate(), and Eigen::SVDBase< BDCSVD< _MatrixType > >::computeU().
template<typename Derived> bool Eigen::SVDBase< Derived >::m_computeThinV protected
Referenced by Eigen::SVDBase< Derived >::allocate(), and Eigen::SVDBase< BDCSVD< _MatrixType > >::computeV().
template<typename Derived> Index Eigen::SVDBase< Derived >::m_diagSize protected
Referenced by Eigen::SVDBase< Derived >::allocate(), and Eigen::SVDBase< BDCSVD< _MatrixType > >::threshold().
template<typename Derived> bool Eigen::SVDBase< Derived >::m_isAllocated protected
Referenced by Eigen::SVDBase< Derived >::allocate().
template<typename Derived> bool Eigen::SVDBase< Derived >::m_isInitialized protected
Referenced by Eigen::SVDBase< Derived >::allocate(), Eigen::SVDBase< BDCSVD< _MatrixType > >::matrixU(), Eigen::SVDBase< BDCSVD< _MatrixType > >::matrixV(), Eigen::SVDBase< BDCSVD< _MatrixType > >::nonzeroSingularValues(), Eigen::SVDBase< BDCSVD< _MatrixType > >::rank(), Eigen::SVDBase< BDCSVD< _MatrixType > >::singularValues(), Eigen::SVDBase< BDCSVD< _MatrixType > >::solve(), and Eigen::SVDBase< BDCSVD< _MatrixType > >::threshold().
template<typename Derived> MatrixUType Eigen::SVDBase< Derived >::m_matrixU protected
Referenced by Eigen::SVDBase< Derived >::_solve_impl(), Eigen::SVDBase< Derived >::allocate(), Eigen::SVDBase< BDCSVD< _MatrixType > >::matrixU(), and Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::run().
template<typename Derived> MatrixVType Eigen::SVDBase< Derived >::m_matrixV protected
Referenced by Eigen::SVDBase< Derived >::_solve_impl(), Eigen::SVDBase< Derived >::allocate(), Eigen::SVDBase< BDCSVD< _MatrixType > >::matrixV(), and Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::run().
template<typename Derived> Index Eigen::SVDBase< Derived >::m_nonzeroSingularValues protected
Referenced by Eigen::SVDBase< BDCSVD< _MatrixType > >::nonzeroSingularValues(), and Eigen::SVDBase< BDCSVD< _MatrixType > >::rank().
template<typename Derived> RealScalar Eigen::SVDBase< Derived >::m_prescribedThreshold protected
Referenced by Eigen::SVDBase< BDCSVD< _MatrixType > >::setThreshold(), and Eigen::SVDBase< BDCSVD< _MatrixType > >::threshold().
template<typename Derived> Index Eigen::SVDBase< Derived >::m_rows protected
Referenced by Eigen::SVDBase< Derived >::allocate(), and Eigen::SVDBase< BDCSVD< _MatrixType > >::rows().
template<typename Derived> SingularValuesType Eigen::SVDBase< Derived >::m_singularValues protected
Referenced by Eigen::SVDBase< Derived >::_solve_impl(), Eigen::SVDBase< Derived >::allocate(), Eigen::SVDBase< BDCSVD< _MatrixType > >::rank(), and Eigen::SVDBase< BDCSVD< _MatrixType > >::singularValues().
template<typename Derived> bool Eigen::SVDBase< Derived >::m_usePrescribedThreshold protected
Referenced by Eigen::SVDBase< BDCSVD< _MatrixType > >::setThreshold(), and Eigen::SVDBase< BDCSVD< _MatrixType > >::threshold().
The documentation for this class was generated from the following file:
SVDBase.h