SmartMouse_2018: SpeedRun Class Reference
SpeedRun Class Reference
#include <SpeedRun.h>
Public Member Functions
SpeedRun (Mouse *mouse)
void initialize ()
run once in the first iteration of the command's life. this will be overrided by individual commands
bool isFinished ()
checked every iteration to see if we're done here. this will be overrided by individual commands
Public Member Functions inherited from CommandGroup
CommandGroup (const char *name)
CommandGroup ()=default
void addSequential (Command *command)
void addParallel (Command *command)
virtual void _initialize ()
virtual void _execute ()
virtual void _end ()
virtual void execute ()
stuff to do over and over each iteration. this will be overrided by individual commands
virtual void end ()
called once at the end, once isFinished() returned true. this will be overrided by individual commands.
Public Member Functions inherited from Command
Command ()
Command (const char *name)
virtual ~Command ()
void setTimeout (unsigned long timeout)
unsigned long getTime ()
bool isTimedOut ()
bool cycle ()
actually does the excuting.
bool isRunning ()
check if the command is running.
bool operator!= (const Command &other)
comparator overload for !=. used when checking if command is in list
Private Attributes
Mouse * mouse
route_t * path
int index
Additional Inherited Members
Static Public Member Functions inherited from Command
static void setTimerImplementation (TimerInterface *timer)
static TimerInterface * getTimerImplementation ()
Public Attributes inherited from CommandGroup
LinkedList< Command * > commands
Public Attributes inherited from Command
bool inParallel
used by command group to organize commands
const char * name
for convenient printing
bool initialized
bool running
unsigned long timeout
unsigned long startTime
Static Public Attributes inherited from Command
static TimerInterface * timer
Constructor & Destructor Documentation
SpeedRun::SpeedRun (Mouse * mouse)
Member Function Documentation
void SpeedRun::initialize () virtual
run once in the first iteration of the command's life. this will be overrided by individual commands
Reimplemented from CommandGroup.
References AbstractMaze::fastest_route, index, Mouse::maze, mouse, and path.
bool SpeedRun::isFinished () virtual
checked every iteration to see if we're done here. this will be overrided by individual commands
Returns
is the function finished
Reimplemented from CommandGroup.
References CommandGroup::addSequential(), motion_primitive_t::d, Mouse::getCol(), Mouse::getRow(), index, CommandGroup::isFinished(), mouse, path, Mouse::print_maze_mouse(), and smartmouse::maze::SIZE.
Member Data Documentation
int SpeedRun::index private
Referenced by initialize(), and isFinished().
Mouse* SpeedRun::mouse private
Referenced by initialize(), and isFinished().
route_t* SpeedRun::path private
Referenced by initialize(), and isFinished().
The documentation for this class was generated from the following files:
SpeedRun.h
SpeedRun.cpp