SmartMouse_2018: AbstractMaze Class Reference
AbstractMaze Class Reference
#include <AbstractMaze.h>
Public Member Functions
AbstractMaze ()
allocates and initializes a node allocates a maze of the given size and sets all links in graph to be null. Naturally, it's column major.
AbstractMaze (std::ifstream &fs)
void mark_origin_known ()
void mark_position_visited (unsigned int row, unsigned int col)
void connect_neighbor (unsigned int row, unsigned int col, const Direction dir)
add the neighbor in the given direction
void reset ()
void update (SensorReading sr)
uses the information from a sensor read and correctly adds or removes walls from nodes
bool flood_fill_from_point (route_t *path, unsigned int r0, unsigned int c0, unsigned int r1, unsigned int c1)
bool flood_fill_from_origin (route_t *path, unsigned int r1, unsigned int c1)
bool flood_fill_from_origin_to_center (route_t *path)
void connect_all_neighbors_in_maze ()
connect all neighbors in the whole maze
int get_node (Node **out, unsigned int r, unsigned int c)
get node by its position
int get_node_in_direction (Node **out, unsigned int row, unsigned int col, const Direction dir)
get neighbor node in a direction from a position
void connect_all_neighbors (unsigned int row, unsigned int col)
add all the neighbors
void disconnect_neighbor (unsigned int row, unsigned int col, const Direction dir)
disconnect any neighbor in the given direction
route_t truncate (unsigned int row, unsigned int col, Direction dir, route_t route)
walks along a route in the maze and return the longest valid path Valid means you don't walk through any walls.
void print_maze ()
void print_maze_str (char *buff)
void print_pointer_maze ()
void print_neighbor_maze ()
void print_weight_maze ()
void print_dist_maze ()
bool flood_fill (route_t *path, unsigned int r0, unsigned int c0, unsigned int r1, unsigned int c1)
bool operator== (const AbstractMaze &other) const
Static Public Member Functions
static AbstractMaze gen_random_legal_maze ()
static void _make_connections (AbstractMaze *maze, Node *node)
Public Attributes
bool solved
route_t fastest_route
route_t fastest_theoretical_route
route_t path_to_next_goal
Node * nodes [smartmouse::maze::SIZE][smartmouse::maze::SIZE]
Friends
class Mouse
Constructor & Destructor Documentation
AbstractMaze::AbstractMaze ()
allocates and initializes a node allocates a maze of the given size and sets all links in graph to be null. Naturally, it's column major.
maze.c implements the functions used to create, free, and manipulate maze
Author
Peter Mitrano
References i, nodes, and smartmouse::maze::SIZE.
AbstractMaze::AbstractMaze (std::ifstream & fs)
References connect_neighbor(), i, print(), S, smartmouse::maze::SIZE, and W.
Member Function Documentation
void AbstractMaze::_make_connections (AbstractMaze * maze, Node * node) static
References Node::col(), connect_neighbor(), E, get_node_in_direction(), mark_position_visited(), N, Node::OUT_OF_BOUNDS, Node::row(), S, Node::visited, and W.
Referenced by gen_random_legal_maze().
void AbstractMaze::connect_all_neighbors (unsigned int row, unsigned int col)
add all the neighbors
References connect_neighbor(), First, and Last.
Referenced by connect_all_neighbors_in_maze(), and TEST().
void AbstractMaze::connect_all_neighbors_in_maze ()
connect all neighbors in the whole maze
Parameters
i row
j col
References connect_all_neighbors(), i, and smartmouse::maze::SIZE.
Referenced by smartmouse::msgs::Convert(), Flood::setup(), and TEST().
void AbstractMaze::connect_neighbor (unsigned int row, unsigned int col, const Direction dir)
add the neighbor in the given direction
Parameters
dir direction connect in
References get_node(), get_node_in_direction(), Node::neighbors, opposite_direction(), and Node::OUT_OF_BOUNDS.
Referenced by _make_connections(), AbstractMaze(), connect_all_neighbors(), gen_random_legal_maze(), Flood::setup(), TEST(), and update().
void AbstractMaze::disconnect_neighbor (unsigned int row, unsigned int col, const Direction dir)
disconnect any neighbor in the given direction
Parameters
dir direction connect in
References get_node(), get_node_in_direction(), Node::neighbors, opposite_direction(), and Node::OUT_OF_BOUNDS.
Referenced by smartmouse::msgs::Convert(), TEST(), and update().
bool AbstractMaze::flood_fill (route_t * path, unsigned int r0, unsigned int c0, unsigned int r1, unsigned int c1)
References Node::assign_weights_to_neighbors(), First, insert_motion_primitive_front(), Last, N, Node::neighbor(), nodes, opposite_direction(), reset(), and Node::weight.
Referenced by flood_fill_from_origin(), flood_fill_from_origin_to_center(), and flood_fill_from_point().
bool AbstractMaze::flood_fill_from_origin (route_t * path, unsigned int r1, unsigned int c1)
References flood_fill().
bool AbstractMaze::flood_fill_from_origin_to_center (route_t * path)
References flood_fill(), and smartmouse::maze::SIZE.
Referenced by Flood::planNextStep().
bool AbstractMaze::flood_fill_from_point (route_t * path, unsigned int r0, unsigned int c0, unsigned int r1, unsigned int c1)
References flood_fill().
Referenced by ReturnToStart::initialize(), and Flood::planNextStep().
AbstractMaze AbstractMaze::gen_random_legal_maze () static
References _make_connections(), above, connect_neighbor(), E, get_node(), i, int_to_dir(), mark_position_visited(), maze, N, S, smartmouse::maze::SIZE, W, and Node::wall().
Referenced by Client::LoadRandomMaze(), main(), and TEST().
int AbstractMaze::get_node (Node ** out, unsigned int r, unsigned int c)
get node by its position
Returns
0 on success, OUT_OF_BOUNDS, or -1 on NULL
References nodes, Node::OUT_OF_BOUNDS, and smartmouse::maze::SIZE.
Referenced by connect_neighbor(), disconnect_neighbor(), gen_random_legal_maze(), get_node_in_direction(), Mouse::isWallInDirection(), and TEST().
int AbstractMaze::get_node_in_direction (Node ** out, unsigned int row, unsigned int col, const Direction dir)
get neighbor node in a direction from a position
Parameters
the adress of the node to set
row starting row
col starting col
dir the direction of the neighbor you want
Returns
0 on success, OUT_OF_BOUNDS, or -1 on NULL
References E, get_node(), N, S, and W.
Referenced by _make_connections(), connect_neighbor(), disconnect_neighbor(), and TEST().
void AbstractMaze::mark_origin_known ()
References Node::known, and nodes.
Referenced by WallFollow::setup().
void AbstractMaze::mark_position_visited (unsigned int row, unsigned int col)
References nodes, and Node::visited.
Referenced by _make_connections(), gen_random_legal_maze(), and Flood::planNextStep().
bool AbstractMaze::operator== (const AbstractMaze & other) const
References First, i, Last, Node::neighbor(), nodes, and smartmouse::maze::SIZE.
void AbstractMaze::print_dist_maze ()
duh
References Node::distance, i, nodes, print(), and smartmouse::maze::SIZE.
void AbstractMaze::print_maze ()
prints a maze
Parameters
maze the maze
References smartmouse::maze::BUFF_SIZE, print(), and print_maze_str().
Referenced by main().
void AbstractMaze::print_maze_str (char * buff)
References i, Node::neighbor(), nodes, S, smartmouse::maze::SIZE, and W.
Referenced by main(), and print_maze().
void AbstractMaze::print_neighbor_maze ()
prints each node as a list of booleans EX) 0010 would mean on wall South 1011 would mean walls to the North, South, and West
References First, i, Last, Node::neighbor(), nodes, print(), and smartmouse::maze::SIZE.
void AbstractMaze::print_pointer_maze ()
duh
References i, nodes, print(), and smartmouse::maze::SIZE.
void AbstractMaze::print_weight_maze ()
duh
References i, nodes, print(), smartmouse::maze::SIZE, and Node::weight.
void AbstractMaze::reset ()
References i, Node::known, nodes, smartmouse::maze::SIZE, and Node::weight.
Referenced by flood_fill(), WallFollow::setup(), and Flood::setup().
route_t AbstractMaze::truncate (unsigned int row, unsigned int col, Direction dir, route_t route)
walks along a route in the maze and return the longest valid path Valid means you don't walk through any walls.
References done, i, insert_motion_primitive_back(), Node::neighbor(), nodes, and Node::wall().
Referenced by Flood::planNextStep().
void AbstractMaze::update (SensorReading sr)
uses the information from a sensor read and correctly adds or removes walls from nodes
Parameters
row row
col col
walls the array of walls
n the node to update the neighbors of
References SensorReading::col, connect_neighbor(), disconnect_neighbor(), First, SensorReading::isWall(), Last, and SensorReading::row.
Referenced by Flood::planNextStep().
Friends And Related Function Documentation
friend class Mouse friend
Member Data Documentation
route_t AbstractMaze::fastest_route
Referenced by SpeedRun::initialize(), Flood::planNextStep(), WallFollow::solve(), Flood::solve(), and Flood::teardown().
route_t AbstractMaze::fastest_theoretical_route
Referenced by Flood::planNextStep().
Node* AbstractMaze::nodes[smartmouse::maze::SIZE][smartmouse::maze::SIZE]
Referenced by AbstractMaze(), ConsoleMouse::checkWalls(), smartmouse::msgs::Convert(), flood_fill(), get_node(), Mouse::mark_mouse_position_visited(), mark_origin_known(), mark_position_visited(), Mouse::maze_mouse_string(), operator==(), print_dist_maze(), print_maze_str(), print_neighbor_maze(), print_pointer_maze(), print_weight_maze(), reset(), and truncate().
route_t AbstractMaze::path_to_next_goal
Referenced by Flood::planNextStep().
bool AbstractMaze::solved
The documentation for this class was generated from the following files:
AbstractMaze.h
AbstractMaze.cpp