SmartMouse_2018: Eigen::JacobiRotation< Scalar > Class Template Reference
Eigen::JacobiRotation< Scalar > Class Template Reference
Rotation given by a cosine-sine pair.
#include <ForwardDeclarations.h>
Public Types
typedef NumTraits< Scalar >::Real RealScalar
Public Member Functions
EIGEN_DEVICE_FUNC JacobiRotation ()
EIGEN_DEVICE_FUNC JacobiRotation (const Scalar &c, const Scalar &s)
EIGEN_DEVICE_FUNC Scalar & c ()
EIGEN_DEVICE_FUNC Scalar c () const
EIGEN_DEVICE_FUNC Scalar & s ()
EIGEN_DEVICE_FUNC Scalar s () const
EIGEN_DEVICE_FUNC JacobiRotation operator* (const JacobiRotation &other)
EIGEN_DEVICE_FUNC JacobiRotation transpose () const
EIGEN_DEVICE_FUNC JacobiRotation adjoint () const
template<typename Derived >
EIGEN_DEVICE_FUNC bool makeJacobi (const MatrixBase< Derived > &, Index p, Index q)
EIGEN_DEVICE_FUNC bool makeJacobi (const RealScalar &x, const Scalar &y, const RealScalar &z)
EIGEN_DEVICE_FUNC void makeGivens (const Scalar &p, const Scalar &q, Scalar *z=0)
template<typename Derived >
bool makeJacobi (const MatrixBase< Derived > &m, Index p, Index q)
Protected Member Functions
EIGEN_DEVICE_FUNC void makeGivens (const Scalar &p, const Scalar &q, Scalar *z, internal::true_type)
EIGEN_DEVICE_FUNC void makeGivens (const Scalar &p, const Scalar &q, Scalar *z, internal::false_type)
Protected Attributes
Scalar m_c
Scalar m_s
Detailed Description
template<typename Scalar>
class Eigen::JacobiRotation< Scalar >
Rotation given by a cosine-sine pair.
This class represents a Jacobi or Givens rotation. This is a 2D rotation in the plane J of angle defined by its cosine c and sine s as follow:
You can apply the respective counter-clockwise rotation to a column vector v by applying its adjoint on the left: that translates to the following Eigen code:
v.applyOnTheLeft(J.adjoint());
See also
MatrixBase::applyOnTheLeft(), MatrixBase::applyOnTheRight()
Member Typedef Documentation
template<typename Scalar> typedef NumTraits<Scalar>::Real Eigen::JacobiRotation< Scalar >::RealScalar
Constructor & Destructor Documentation
template<typename Scalar> EIGEN_DEVICE_FUNC Eigen::JacobiRotation< Scalar >::JacobiRotation () inline
Default constructor without any initialization.
Referenced by Eigen::JacobiRotation< Scalar >::adjoint(), Eigen::JacobiRotation< Scalar >::operator*(), and Eigen::JacobiRotation< Scalar >::transpose().
template<typename Scalar> EIGEN_DEVICE_FUNC Eigen::JacobiRotation< Scalar >::JacobiRotation (const Scalar & c, const Scalar & s) inline
Construct a planar rotation from a cosine-sine pair (c, s).
Member Function Documentation
template<typename Scalar> EIGEN_DEVICE_FUNC JacobiRotation Eigen::JacobiRotation< Scalar >::adjoint () const inline
Returns the adjoint transformation
References Eigen::JacobiRotation< Scalar >::JacobiRotation(), Eigen::JacobiRotation< Scalar >::m_c, Eigen::JacobiRotation< Scalar >::m_s, Eigen::JacobiRotation< Scalar >::makeGivens(), and Eigen::JacobiRotation< Scalar >::makeJacobi().
Referenced by Eigen::RealQZ< _MatrixType >::hessenbergTriangular(), Eigen::RealQZ< _MatrixType >::pushDownZero(), Eigen::ComplexSchur< _MatrixType >::reduceToTriangularForm(), Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::run(), Eigen::RealQZ< _MatrixType >::splitOffTwoRows(), Eigen::RealSchur< _MatrixType >::splitOffTwoRows(), and Eigen::RealQZ< _MatrixType >::step().
template<typename Scalar> EIGEN_DEVICE_FUNC Scalar& Eigen::JacobiRotation< Scalar >::c () inline
References Eigen::JacobiRotation< Scalar >::m_c.
Referenced by Eigen::internal::apply_rotation_in_the_plane(), Eigen::internal::apply_rotation_in_the_plane_selector< Scalar, OtherScalar, SizeAtCompileTime, MinAlignment, true >::run(), Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::run(), and Eigen::internal::tridiagonal_qr_step().
template<typename Scalar> EIGEN_DEVICE_FUNC Scalar Eigen::JacobiRotation< Scalar >::c () const inline
References Eigen::JacobiRotation< Scalar >::m_c.
template<typename Scalar > void Eigen::JacobiRotation< Scalar >::makeGivens (const Scalar & p, const Scalar & q, Scalar * z = 0)
Makes *this as a Givens rotation G such that applying to the left of the vector yields: .
The value of z is returned if z is not null (the default is null). Also note that G is built such that the cosine is always real.
Example:
Output:
This function implements the continuous Givens rotation generation algorithm found in Anderson (2000), Discontinuous Plane Rotations and the Symmetric Eigenvalue Problem. LAPACK Working Note 150, University of Tennessee, UT-CS-00-454, December 4, 2000.
See also
MatrixBase::applyOnTheLeft(), MatrixBase::applyOnTheRight()
References type.
Referenced by Eigen::JacobiRotation< Scalar >::adjoint(), Eigen::RealQZ< _MatrixType >::hessenbergTriangular(), Eigen::internal::llt_rank_update_lower(), Eigen::RealQZ< _MatrixType >::pushDownZero(), Eigen::ComplexSchur< _MatrixType >::reduceToTriangularForm(), Eigen::RealQZ< _MatrixType >::splitOffTwoRows(), Eigen::RealSchur< _MatrixType >::splitOffTwoRows(), Eigen::RealQZ< _MatrixType >::step(), and Eigen::internal::tridiagonal_qr_step().
template<typename Scalar > void Eigen::JacobiRotation< Scalar >::makeGivens (const Scalar & p, const Scalar & q, Scalar * z, internal::true_type) protected
References abs(), abs2(), Eigen::JacobiRotation< Scalar >::m_c, Eigen::JacobiRotation< Scalar >::m_s, real(), and sqrt().
template<typename Scalar > void Eigen::JacobiRotation< Scalar >::makeGivens (const Scalar & p, const Scalar & q, Scalar * z, internal::false_type) protected
References abs(), abs2(), Eigen::internal::apply_rotation_in_the_plane(), Eigen::JacobiRotation< Scalar >::m_c, Eigen::JacobiRotation< Scalar >::m_s, and sqrt().
template<typename Scalar> template<typename Derived > EIGEN_DEVICE_FUNC bool Eigen::JacobiRotation< Scalar >::makeJacobi (const MatrixBase< Derived > & , Index p, Index q)
Referenced by Eigen::JacobiRotation< Scalar >::adjoint(), Eigen::JacobiRotation< Scalar >::makeJacobi(), and Eigen::internal::real_2x2_jacobi_svd().
template<typename Scalar > bool Eigen::JacobiRotation< Scalar >::makeJacobi (const RealScalar & x, const Scalar & y, const RealScalar & z)
Makes *this as a Jacobi rotation J such that applying J on both the right and left sides of the selfadjoint 2x2 matrix yields a diagonal matrix
See also
MatrixBase::makeJacobi(const MatrixBase<Derived>&, Index, Index), MatrixBase::applyOnTheLeft(), MatrixBase::applyOnTheRight()
References abs(), abs2(), Eigen::JacobiRotation< Scalar >::m_c, Eigen::JacobiRotation< Scalar >::m_s, Eigen::half_impl::min(), and sqrt().
template<typename Scalar> template<typename Derived > bool Eigen::JacobiRotation< Scalar >::makeJacobi (const MatrixBase< Derived > & m, Index p, Index q) inline
Makes *this as a Jacobi rotation J such that applying J on both the right and left sides of the 2x2 selfadjoint matrix yields a diagonal matrix
Example:
Output:
See also
JacobiRotation::makeJacobi(RealScalar, Scalar, RealScalar), MatrixBase::applyOnTheLeft(), MatrixBase::applyOnTheRight()
References Eigen::JacobiRotation< Scalar >::makeJacobi(), and real().
template<typename Scalar> EIGEN_DEVICE_FUNC JacobiRotation Eigen::JacobiRotation< Scalar >::operator* (const JacobiRotation< Scalar > & other) inline
Concatenates two planar rotation
References Eigen::JacobiRotation< Scalar >::JacobiRotation(), Eigen::JacobiRotation< Scalar >::m_c, and Eigen::JacobiRotation< Scalar >::m_s.
template<typename Scalar> EIGEN_DEVICE_FUNC Scalar& Eigen::JacobiRotation< Scalar >::s () inline
References Eigen::JacobiRotation< Scalar >::m_s.
Referenced by Eigen::internal::apply_rotation_in_the_plane(), Eigen::internal::apply_rotation_in_the_plane_selector< Scalar, OtherScalar, SizeAtCompileTime, MinAlignment, true >::run(), Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::run(), and Eigen::internal::tridiagonal_qr_step().
template<typename Scalar> EIGEN_DEVICE_FUNC Scalar Eigen::JacobiRotation< Scalar >::s () const inline
References Eigen::JacobiRotation< Scalar >::m_s.
template<typename Scalar> EIGEN_DEVICE_FUNC JacobiRotation Eigen::JacobiRotation< Scalar >::transpose () const inline
Returns the transposed transformation
References Eigen::JacobiRotation< Scalar >::JacobiRotation(), Eigen::JacobiRotation< Scalar >::m_c, and Eigen::JacobiRotation< Scalar >::m_s.
Referenced by Eigen::RealQZ< _MatrixType >::compute(), Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::compute(), and Eigen::internal::real_2x2_jacobi_svd().
Member Data Documentation
template<typename Scalar> Scalar Eigen::JacobiRotation< Scalar >::m_c protected
Referenced by Eigen::JacobiRotation< Scalar >::adjoint(), Eigen::JacobiRotation< Scalar >::c(), Eigen::JacobiRotation< Scalar >::makeGivens(), Eigen::JacobiRotation< Scalar >::makeJacobi(), Eigen::JacobiRotation< Scalar >::operator*(), and Eigen::JacobiRotation< Scalar >::transpose().
template<typename Scalar> Scalar Eigen::JacobiRotation< Scalar >::m_s protected
Referenced by Eigen::JacobiRotation< Scalar >::adjoint(), Eigen::JacobiRotation< Scalar >::makeGivens(), Eigen::JacobiRotation< Scalar >::makeJacobi(), Eigen::JacobiRotation< Scalar >::operator*(), Eigen::JacobiRotation< Scalar >::s(), and Eigen::JacobiRotation< Scalar >::transpose().
The documentation for this class was generated from the following files:
ForwardDeclarations.h
Jacobi.h