SmartMouse_2018: KinematicController Class Reference
KinematicController Class Reference
#include <KinematicController.h>
Public Member Functions
KinematicController (Mouse *mouse)
void planTraj (Waypoints waypoints)
std::tuple< double, double, bool > estimate_pose (RangeData range_data, Mouse &mouse)
GlobalPose getGlobalPose ()
LocalPose getLocalPose ()
std::pair< double, double > getWheelVelocities ()
bool isStopped ()
void reset_col_to (double new_col)
void reset_row_to (double new_row)
void reset_yaw_to (double new_yaw)
std::pair< double, double > run (double dt_s, double left_angle_rad, double right_angle_rad, RangeData range_data)
void setAccelerationCpss (double acceleration_mpss)
void setSpeedCps (double left_setpoint_mps, double right_setpoint_mps)
void setParams (double kP, double kI, double kD, double ff_scale, double ff_offset)
double getCurrentForwardSpeedCUPS ()
Static Public Member Functions
static double dispToNextEdge (Mouse &mouse)
static double dispToNthEdge (Mouse &mouse, unsigned int n)
static GlobalPose poseOfToNthEdge (Mouse &mouse, unsigned int n)
static double fwdDispToCenter (Mouse &mouse)
static double fwdDisp (Direction dir, GlobalPose current_pose, GlobalPose start_pose)
static GlobalPose forwardKinematics (double vl, double vr, double yaw, double dt)
static double sidewaysDispToCenter (Mouse &mouse)
Public Attributes
RegulatedMotor left_motor
RegulatedMotor right_motor
bool enable_sensor_pose_estimate
bool enabled
bool kinematics_enabled
unsigned int row
unsigned int col
Static Public Attributes
static const double kPWall
static const double kDWall
static const double kPYaw
Private Attributes
bool initialized
bool ignoring_left
bool ignoring_right
GlobalPose current_pose_estimate_cu
Mouse * mouse
double d_until_left_drop
double d_until_right_drop
double acceleration_cellpss
double dt_s
Static Private Attributes
static const double kDropSafety = 0.8
Constructor & Destructor Documentation
KinematicController::KinematicController (Mouse * mouse)
References GlobalPose::col, current_pose_estimate_cu, GlobalPose::row, and GlobalPose::yaw.
Member Function Documentation
double KinematicController::dispToNextEdge (Mouse & mouse) static
References GlobalPose::col, E, Mouse::getCol(), Mouse::getDir(), Mouse::getGlobalPose(), Mouse::getRow(), N, GlobalPose::row, S, and W.
Referenced by dispToNthEdge(), and Forward::initialize().
double KinematicController::dispToNthEdge (Mouse & mouse, unsigned int n) static
References dispToNextEdge().
Referenced by ForwardN::initialize(), and poseOfToNthEdge().
std::tuple< double, double, bool > KinematicController::estimate_pose (RangeData range_data, Mouse & mouse)
References smartmouse::kc::BACK_ANALOG_ANGLE, RangeData::back_left, RangeData::back_right, smartmouse::kc::BACK_SIDE_ANALOG_X, smartmouse::kc::BACK_SIDE_ANALOG_Y, d_until_left_drop, d_until_right_drop, dir_to_yaw(), smartmouse::kc::FRONT_ANALOG_ANGLE, RangeData::front_left, RangeData::front_right, smartmouse::kc::FRONT_SIDE_ANALOG_X, smartmouse::kc::FRONT_SIDE_ANALOG_Y, smartmouse::kc::GERALD_ANGLE, RangeData::gerald_left, RangeData::gerald_right, smartmouse::kc::GERALD_WALL_THRESHOLD, Mouse::getDir(), smartmouse::maze::HALF_WALL_THICKNESS_M, Mouse::isWallInDirection(), kDropSafety, left_of_dir(), right_of_dir(), smartmouse::kc::SIDE_WALL_THRESHOLD, smartmouse::maze::UNIT_DIST_M, and smartmouse::kc::WALL_CHANGED_THRESHOLD.
Referenced by run().
GlobalPose KinematicController::forwardKinematics (double vl, double vr, double yaw, double dt) static
References e, and smartmouse::kc::TRACK_WIDTH_CU.
Referenced by run(), TEST(), and Server::UpdateRobotState().
double KinematicController::fwdDisp (Direction dir, GlobalPose current_pose, GlobalPose start_pose) static
References GlobalPose::col, E, N, GlobalPose::row, S, and W.
Referenced by smartmouse::kc::DriveStraightState::compute_wheel_velocities().
double KinematicController::fwdDispToCenter (Mouse & mouse) static
References Mouse::getLocalPose(), and LocalPose::to_back.
Referenced by ForwardToCenter::initialize().
double KinematicController::getCurrentForwardSpeedCUPS ()
References left_motor, smartmouse::kc::radToCU(), right_motor, and RegulatedMotor::velocity_rps.
GlobalPose KinematicController::getGlobalPose ()
References current_pose_estimate_cu.
Referenced by SimMouse::getGlobalPose(), RealMouse::getGlobalPose(), and SimMouse::run().
LocalPose KinematicController::getLocalPose ()
References GlobalPose::col, current_pose_estimate_cu, dir_to_yaw(), E, Mouse::getDir(), mouse, N, GlobalPose::row, S, LocalPose::to_back, LocalPose::to_left, W, GlobalPose::yaw, smartmouse::math::yaw_diff(), and LocalPose::yaw_from_straight.
Referenced by SimMouse::getLocalPose(), and RealMouse::getLocalPose().
std::pair< double, double > KinematicController::getWheelVelocities ()
References left_motor, right_motor, and RegulatedMotor::velocity_rps.
Referenced by SimMouse::getWheelVelocities(), and RealMouse::getWheelVelocities().
bool KinematicController::isStopped ()
References RegulatedMotor::isStopped(), and left_motor.
Referenced by SimMouse::isStopped().
void KinematicController::planTraj (Waypoints waypoints)
References TrajectoryPlanner::plan().
GlobalPose KinematicController::poseOfToNthEdge (Mouse & mouse, unsigned int n) static
References GlobalPose::col, dispToNthEdge(), Mouse::getGlobalPose(), GlobalPose::row, and GlobalPose::yaw.
void KinematicController::reset_col_to (double new_col)
References GlobalPose::col, and current_pose_estimate_cu.
Referenced by SimMouse::resetToStartPose(), and RealMouse::resetToStartPose().
void KinematicController::reset_row_to (double new_row)
References current_pose_estimate_cu, and GlobalPose::row.
Referenced by SimMouse::resetToStartPose(), and RealMouse::resetToStartPose().
void KinematicController::reset_yaw_to (double new_yaw)
References current_pose_estimate_cu, and GlobalPose::yaw.
Referenced by SimMouse::resetToStartPose(), and RealMouse::resetToStartPose().
std::pair< double, double > KinematicController::run (double dt_s, double left_angle_rad, double right_angle_rad, RangeData range_data)
References GlobalPose::col, col, current_pose_estimate_cu, dir_to_yaw(), dt_s, E, enable_sensor_pose_estimate, enabled, estimate_pose(), forwardKinematics(), RangeData::front, smartmouse::kc::FRONT_ANALOG_X, Mouse::getDir(), smartmouse::maze::HALF_WALL_THICKNESS_CU, initialized, kinematics_enabled, left_motor, mouse, N, smartmouse::kc::radToCU(), right_motor, GlobalPose::row, row, RegulatedMotor::runPid(), S, smartmouse::maze::toCellUnits(), RegulatedMotor::velocity_rps, W, smartmouse::math::wrapAngleRadInPlace(), GlobalPose::yaw, and smartmouse::math::yaw_diff().
Referenced by SimMouse::run(), and RealMouse::run().
void KinematicController::setAccelerationCpss (double acceleration_mpss)
References acceleration_cellpss, left_motor, right_motor, and RegulatedMotor::setAccelerationCpss().
Referenced by RealMouse::setup(), and SimMouse::simInit().
void KinematicController::setParams (double kP, double kI, double kD, double ff_scale, double ff_offset)
References left_motor, right_motor, and RegulatedMotor::setParams().
Referenced by SimMouse::pidConstantsCallback().
void KinematicController::setSpeedCps (double left_setpoint_mps, double right_setpoint_mps)
References left_motor, right_motor, and RegulatedMotor::setSetpointCps().
Referenced by SimMouse::setSpeedCps(), and RealMouse::setSpeedCps().
double KinematicController::sidewaysDispToCenter (Mouse & mouse) static
References Mouse::getLocalPose(), and LocalPose::to_left.
Referenced by smartmouse::kc::DriveStraightState::compute_wheel_velocities().
Member Data Documentation
double KinematicController::acceleration_cellpss private
Referenced by setAccelerationCpss().
unsigned int KinematicController::col
Referenced by SimMouse::run(), run(), and RealMouse::run().
GlobalPose KinematicController::current_pose_estimate_cu private
Referenced by getGlobalPose(), getLocalPose(), KinematicController(), reset_col_to(), reset_row_to(), reset_yaw_to(), and run().
double KinematicController::d_until_left_drop private
Referenced by estimate_pose().
double KinematicController::d_until_right_drop private
Referenced by estimate_pose().
double KinematicController::dt_s private
Referenced by run().
bool KinematicController::enable_sensor_pose_estimate
Referenced by ForwardToCenter::end(), ForwardN::end(), Forward::end(), ForwardToCenter::initialize(), Forward::initialize(), ForwardN::initialize(), and run().
bool KinematicController::enabled
Referenced by WaitForStart::end(), run(), setup(), and WaitForStart::WaitForStart().
bool KinematicController::ignoring_left private
bool KinematicController::ignoring_right private
bool KinematicController::initialized private
Referenced by run().
const double KinematicController::kDropSafety = 0.8 static private
Referenced by estimate_pose().
const double KinematicController::kDWall static
bool KinematicController::kinematics_enabled
Referenced by run(), and SimMouse::serverCallback().
const double KinematicController::kPWall static
const double KinematicController::kPYaw static
RegulatedMotor KinematicController::left_motor
Referenced by getCurrentForwardSpeedCUPS(), getWheelVelocities(), isStopped(), RealMouse::resetToStartPose(), SimMouse::run(), run(), setAccelerationCpss(), setParams(), and setSpeedCps().
Mouse* KinematicController::mouse private
Referenced by getLocalPose(), and run().
RegulatedMotor KinematicController::right_motor
Referenced by getCurrentForwardSpeedCUPS(), getWheelVelocities(), RealMouse::resetToStartPose(), SimMouse::run(), run(), setAccelerationCpss(), setParams(), and setSpeedCps().
unsigned int KinematicController::row
Referenced by SimMouse::run(), run(), and RealMouse::run().
The documentation for this class was generated from the following files:
KinematicController.h
KinematicController.cpp