SmartMouse_2018: ConsoleMouse Class Reference
ConsoleMouse Class Reference
#include <ConsoleMouse.h>
Public Member Functions
virtual SensorReading checkWalls () override
virtual GlobalPose getGlobalPose () override
virtual LocalPose getLocalPose () override
void seedMaze (AbstractMaze *maze)
Public Member Functions inherited from Mouse
Mouse ()
Mouse (AbstractMaze *maze)
Mouse (unsigned int starting_row, unsigned int starting_col)
Mouse (AbstractMaze *maze, unsigned int starting_row, unsigned int starting_col)
void reset ()
unsigned int getCol ()
return the current column. Guaranteed to be between 0 and MAZE_SIZE
unsigned int getRow ()
return the current row. Guaranteed to be between 0 and MAZE_SIZE
Direction getDir ()
return the current direction.
bool inBounds ()
bool atCenter ()
is the mouse at the center of the maze?
void mark_mouse_position_visited ()
void internalTurnToFace (Direction dir)
void internalForward ()
void print_maze_mouse ()
void maze_mouse_string (char *)
bool isWallInDirection (Direction d)
Static Public Member Functions
static ConsoleMouse * inst ()
Private Member Functions
ConsoleMouse ()
ConsoleMouse (int starting_row, int starting_col)
Private Attributes
AbstractMaze * true_maze
Static Private Attributes
static ConsoleMouse * instance = nullptr
Additional Inherited Members
Public Attributes inherited from Mouse
AbstractMaze * maze
Protected Attributes inherited from Mouse
unsigned int row
unsigned int col
Direction dir
Constructor & Destructor Documentation
ConsoleMouse::ConsoleMouse () private
Referenced by inst().
ConsoleMouse::ConsoleMouse (int starting_row, int starting_col) private
Member Function Documentation
SensorReading ConsoleMouse::checkWalls () override virtual
Implements Mouse.
References Mouse::col, i, Node::neighbors, AbstractMaze::nodes, Mouse::row, true_maze, and SensorReading::walls.
GlobalPose ConsoleMouse::getGlobalPose () override virtual
Implements Mouse.
References GlobalPose::col, Mouse::col, Mouse::dir, dir_to_yaw(), GlobalPose::row, Mouse::row, and GlobalPose::yaw.
LocalPose ConsoleMouse::getLocalPose () override virtual
Implements Mouse.
References Mouse::dir, dir_to_yaw(), LocalPose::to_back, LocalPose::to_left, and LocalPose::yaw_from_straight.
ConsoleMouse * ConsoleMouse::inst () static
References ConsoleMouse(), instance, and NULL.
Referenced by main(), and TEST().
void ConsoleMouse::seedMaze (AbstractMaze * maze)
References Mouse::maze, and true_maze.
Referenced by main(), and TEST().
Member Data Documentation
ConsoleMouse * ConsoleMouse::instance = nullptr static private
Referenced by inst().
AbstractMaze* ConsoleMouse::true_maze private
Referenced by checkWalls(), and seedMaze().
The documentation for this class was generated from the following files:
ConsoleMouse.h
ConsoleMouse.cpp