SmartMouse_2018: PlotSeriesData Class Reference
PlotSeriesData Class Reference
#include <PlotSeriesData.h>
Public Member Functions
PlotSeriesData (std::string label, QColor color=Qt::black, const unsigned int capacity=1000)
virtual QRectF boundingRect () const override
virtual size_t size () const override
void Append (double x, double y)
void Clear ()
void Hide ()
void Attach (QwtPlot *plot_)
Private Attributes
QMutex * data_mutex_
unsigned int capacity_
int num_points_to_remove_
QwtPlotCurve * curve
Constructor & Destructor Documentation
PlotSeriesData::PlotSeriesData (std::string label, QColor color = Qt::black, const unsigned int capacity = 1000)
References curve, and data_mutex_.
Member Function Documentation
void PlotSeriesData::Append (double x, double y)
References capacity_, and data_mutex_.
Referenced by ControlPlotWidget::ControlCallback(), and PIDPlotWidget::PIDCallback().
void PlotSeriesData::Attach (QwtPlot * plot_)
References curve.
Referenced by ControlPlotWidget::ControlPlotWidget(), ControlPlotWidget::LeftChecked(), PIDPlotWidget::LeftChecked(), PIDPlotWidget::LeftSetpointChecked(), PIDPlotWidget::PIDPlotWidget(), ControlPlotWidget::RightChecked(), PIDPlotWidget::RightChecked(), and PIDPlotWidget::RightSetpointChecked().
QRectF PlotSeriesData::boundingRect () const override virtual
void PlotSeriesData::Clear ()
Referenced by ControlPlotWidget::Clear(), and PIDPlotWidget::Clear().
void PlotSeriesData::Hide ()
References curve.
Referenced by ControlPlotWidget::LeftChecked(), PIDPlotWidget::LeftChecked(), PIDPlotWidget::LeftSetpointChecked(), ControlPlotWidget::RightChecked(), PIDPlotWidget::RightChecked(), and PIDPlotWidget::RightSetpointChecked().
size_t PlotSeriesData::size () const override virtual
References data_mutex_.
Member Data Documentation
unsigned int PlotSeriesData::capacity_ private
Referenced by Append().
QwtPlotCurve* PlotSeriesData::curve private
Referenced by Attach(), Hide(), and PlotSeriesData().
QMutex* PlotSeriesData::data_mutex_ private
Referenced by Append(), PlotSeriesData(), and size().
int PlotSeriesData::num_points_to_remove_ private
The documentation for this class was generated from the following files:
PlotSeriesData.h
PlotSeriesData.cpp