SmartMouse_2018: Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs > Class Template Reference
Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs > Class Template Reference
#include <GeneralBlockPanelKernel.h>
Public Types
enum {
ConjLhs = _ConjLhs, ConjRhs = _ConjRhs, Vectorizable, RealPacketSize = Vectorizable ? packet_traits<RealScalar>::size : 1,
ResPacketSize = Vectorizable ? packet_traits<ResScalar>::size : 1, LhsPacketSize = Vectorizable ? packet_traits<LhsScalar>::size : 1, RhsPacketSize = Vectorizable ? packet_traits<RhsScalar>::size : 1, nr = 4,
mr = ResPacketSize, LhsProgress = ResPacketSize, RhsProgress = 1
}
typedef std::complex< RealScalar > Scalar
typedef std::complex< RealScalar > LhsScalar
typedef std::complex< RealScalar > RhsScalar
typedef std::complex< RealScalar > ResScalar
typedef packet_traits< RealScalar >::type RealPacket
typedef packet_traits< Scalar >::type ScalarPacket
typedef DoublePacket< RealPacket > DoublePacketType
typedef conditional< Vectorizable, RealPacket, Scalar >::type LhsPacket
typedef conditional< Vectorizable, DoublePacketType, Scalar >::type RhsPacket
typedef conditional< Vectorizable, ScalarPacket, Scalar >::type ResPacket
typedef conditional< Vectorizable, DoublePacketType, Scalar >::type AccPacket
Public Member Functions
EIGEN_STRONG_INLINE void initAcc (Scalar &p)
EIGEN_STRONG_INLINE void initAcc (DoublePacketType &p)
EIGEN_STRONG_INLINE void loadRhs (const RhsScalar *b, ResPacket &dest) const
EIGEN_STRONG_INLINE void loadRhs (const RhsScalar *b, DoublePacketType &dest) const
EIGEN_STRONG_INLINE void loadRhsQuad (const RhsScalar *b, ResPacket &dest) const
EIGEN_STRONG_INLINE void loadRhsQuad (const RhsScalar *b, DoublePacketType &dest) const
EIGEN_STRONG_INLINE void broadcastRhs (const RhsScalar *b, RhsPacket &b0, RhsPacket &b1, RhsPacket &b2, RhsPacket &b3)
EIGEN_STRONG_INLINE void broadcastRhs (const RhsScalar *b, DoublePacketType &b0, DoublePacketType &b1)
EIGEN_STRONG_INLINE void broadcastRhs (const RhsScalar *b, RhsScalar &b0, RhsScalar &b1)
EIGEN_STRONG_INLINE void loadLhs (const LhsScalar *a, LhsPacket &dest) const
EIGEN_STRONG_INLINE void loadLhsUnaligned (const LhsScalar *a, LhsPacket &dest) const
EIGEN_STRONG_INLINE void madd (const LhsPacket &a, const RhsPacket &b, DoublePacketType &c, RhsPacket &) const
EIGEN_STRONG_INLINE void madd (const LhsPacket &a, const RhsPacket &b, ResPacket &c, RhsPacket &) const
EIGEN_STRONG_INLINE void acc (const Scalar &c, const Scalar &alpha, Scalar &r) const
EIGEN_STRONG_INLINE void acc (const DoublePacketType &c, const ResPacket &alpha, ResPacket &r) const
Protected Attributes
conj_helper< LhsScalar, RhsScalar, ConjLhs, ConjRhs > cj
Member Typedef Documentation
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef conditional<Vectorizable,DoublePacketType,Scalar>::type Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::AccPacket
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef DoublePacket<RealPacket> Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::DoublePacketType
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef conditional<Vectorizable,RealPacket, Scalar>::type Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::LhsPacket
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef std::complex<RealScalar> Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::LhsScalar
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef packet_traits<RealScalar>::type Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::RealPacket
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef conditional<Vectorizable,ScalarPacket,Scalar>::type Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::ResPacket
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef std::complex<RealScalar> Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::ResScalar
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef conditional<Vectorizable,DoublePacketType,Scalar>::type Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::RhsPacket
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef std::complex<RealScalar> Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::RhsScalar
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef std::complex<RealScalar> Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::Scalar
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef packet_traits<Scalar>::type Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::ScalarPacket
Member Enumeration Documentation
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> anonymous enum
Enumerator
ConjLhs
ConjRhs
Vectorizable
RealPacketSize
ResPacketSize
LhsPacketSize
RhsPacketSize
nr
mr
LhsProgress
RhsProgress
Member Function Documentation
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::acc (const Scalar & c, const Scalar & alpha, Scalar & r) const inline
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::acc (const DoublePacketType & c, const ResPacket & alpha, ResPacket & r) const inline
References Eigen::internal::DoublePacket< Packet >::first, Eigen::internal::padd(), Eigen::internal::pconj(), Eigen::internal::pcplxflip(), Eigen::internal::pmadd(), Eigen::internal::psub(), and Eigen::internal::DoublePacket< Packet >::second.
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::broadcastRhs (const RhsScalar * b, RhsPacket & b0, RhsPacket & b1, RhsPacket & b2, RhsPacket & b3) inline
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::broadcastRhs (const RhsScalar * b, DoublePacketType & b0, DoublePacketType & b1) inline
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::broadcastRhs (const RhsScalar * b, RhsScalar & b0, RhsScalar & b1) inline
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::initAcc (Scalar & p) inline
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::initAcc (DoublePacketType & p) inline
References Eigen::internal::DoublePacket< Packet >::first, and Eigen::internal::DoublePacket< Packet >::second.
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::loadLhs (const LhsScalar * a, LhsPacket & dest) const inline
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::loadLhsUnaligned (const LhsScalar * a, LhsPacket & dest) const inline
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::loadRhs (const RhsScalar * b, ResPacket & dest) const inline
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::loadRhs (const RhsScalar * b, DoublePacketType & dest) const inline
References Eigen::internal::DoublePacket< Packet >::first, imag(), real(), and Eigen::internal::DoublePacket< Packet >::second.
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::loadRhsQuad (const RhsScalar * b, ResPacket & dest) const inline
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::loadRhsQuad (const RhsScalar * b, DoublePacketType & dest) const inline
References eigen_internal_assert.
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::madd (const LhsPacket & a, const RhsPacket & b, DoublePacketType & c, RhsPacket &) const inline
References Eigen::internal::DoublePacket< Packet >::first, Eigen::internal::padd(), Eigen::internal::pmul(), and Eigen::internal::DoublePacket< Packet >::second.
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::madd (const LhsPacket & a, const RhsPacket & b, ResPacket & c, RhsPacket &) const inline
Member Data Documentation
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> conj_helper<LhsScalar,RhsScalar,ConjLhs,ConjRhs> Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::cj protected
The documentation for this class was generated from the following file:
GeneralBlockPanelKernel.h