SmartMouse_2018: Eigen::CompleteOrthogonalDecomposition< _MatrixType > Class Template Reference
Eigen::CompleteOrthogonalDecomposition< _MatrixType > Class Template Reference
Complete orthogonal decomposition (COD) of a matrix.
#include <ForwardDeclarations.h>
Public Types
enum { RowsAtCompileTime = MatrixType::RowsAtCompileTime, ColsAtCompileTime = MatrixType::ColsAtCompileTime, MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime, MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime }
typedef _MatrixType MatrixType
typedef MatrixType::Scalar Scalar
typedef MatrixType::RealScalar RealScalar
typedef MatrixType::StorageIndex StorageIndex
typedef internal::plain_diag_type< MatrixType >::type HCoeffsType
typedef PermutationMatrix< ColsAtCompileTime, MaxColsAtCompileTime > PermutationType
typedef internal::plain_row_type< MatrixType, Index >::type IntRowVectorType
typedef internal::plain_row_type< MatrixType >::type RowVectorType
typedef internal::plain_row_type< MatrixType, RealScalar >::type RealRowVectorType
typedef HouseholderSequence< MatrixType, typename internal::remove_all< typename HCoeffsType::ConjugateReturnType >::type > HouseholderSequenceType
typedef MatrixType::PlainObject PlainObject
Public Member Functions
CompleteOrthogonalDecomposition ()
Default Constructor.
CompleteOrthogonalDecomposition (Index rows, Index cols)
Default Constructor with memory preallocation.
template<typename InputType >
CompleteOrthogonalDecomposition (const EigenBase< InputType > &matrix)
Constructs a complete orthogonal decomposition from a given matrix.
template<typename InputType >
CompleteOrthogonalDecomposition (EigenBase< InputType > &matrix)
Constructs a complete orthogonal decomposition from a given matrix.
template<typename Rhs >
const Solve< CompleteOrthogonalDecomposition, Rhs > solve (const MatrixBase< Rhs > &b) const
HouseholderSequenceType householderQ (void) const
HouseholderSequenceType matrixQ (void) const
MatrixType matrixZ () const
const MatrixType & matrixQTZ () const
const MatrixType & matrixT () const
template<typename InputType >
CompleteOrthogonalDecomposition & compute (const EigenBase< InputType > &matrix)
const PermutationType & colsPermutation () const
MatrixType::RealScalar absDeterminant () const
MatrixType::RealScalar logAbsDeterminant () const
Index rank () const
Index dimensionOfKernel () const
bool isInjective () const
bool isSurjective () const
bool isInvertible () const
const Inverse< CompleteOrthogonalDecomposition > pseudoInverse () const
Index rows () const
Index cols () const
const HCoeffsType & hCoeffs () const
const HCoeffsType & zCoeffs () const
CompleteOrthogonalDecomposition & setThreshold (const RealScalar &threshold)
CompleteOrthogonalDecomposition & setThreshold (Default_t)
RealScalar threshold () const
Index nonzeroPivots () const
RealScalar maxPivot () const
ComputationInfo info () const
Reports whether the complete orthogonal decomposition was succesful.
template<typename RhsType , typename DstType >
void _solve_impl (const RhsType &rhs, DstType &dst) const
Protected Member Functions
void computeInPlace ()
template<typename Rhs >
void applyZAdjointOnTheLeftInPlace (Rhs &rhs) const
Static Protected Member Functions
static void check_template_parameters ()
Protected Attributes
ColPivHouseholderQR< MatrixType > m_cpqr
HCoeffsType m_zCoeffs
RowVectorType m_temp
Private Types
typedef PermutationType::Index PermIndexType
Detailed Description
template<typename _MatrixType>
class Eigen::CompleteOrthogonalDecomposition< _MatrixType >
Complete orthogonal decomposition (COD) of a matrix.
Parameters
MatrixType the type of the matrix of which we are computing the COD.
This class performs a rank-revealing complete orthogonal decomposition of a matrix A into matrices P, Q, T, and Z such that
by using Householder transformations. Here, P is a permutation matrix, Q and Z are unitary matrices and T an upper triangular matrix of size rank-by-rank. A may be rank deficient.
This class supports the inplace decomposition mechanism.
See also
MatrixBase::completeOrthogonalDecomposition()
Member Typedef Documentation
template<typename _MatrixType> typedef internal::plain_diag_type<MatrixType>::type Eigen::CompleteOrthogonalDecomposition< _MatrixType >::HCoeffsType
template<typename _MatrixType> typedef HouseholderSequence< MatrixType, typename internal::remove_all< typename HCoeffsType::ConjugateReturnType>::type> Eigen::CompleteOrthogonalDecomposition< _MatrixType >::HouseholderSequenceType
template<typename _MatrixType> typedef internal::plain_row_type<MatrixType, Index>::type Eigen::CompleteOrthogonalDecomposition< _MatrixType >::IntRowVectorType
template<typename _MatrixType> typedef _MatrixType Eigen::CompleteOrthogonalDecomposition< _MatrixType >::MatrixType
template<typename _MatrixType> typedef PermutationType::Index Eigen::CompleteOrthogonalDecomposition< _MatrixType >::PermIndexType private
template<typename _MatrixType> typedef PermutationMatrix<ColsAtCompileTime, MaxColsAtCompileTime> Eigen::CompleteOrthogonalDecomposition< _MatrixType >::PermutationType
template<typename _MatrixType> typedef MatrixType::PlainObject Eigen::CompleteOrthogonalDecomposition< _MatrixType >::PlainObject
template<typename _MatrixType> typedef internal::plain_row_type<MatrixType, RealScalar>::type Eigen::CompleteOrthogonalDecomposition< _MatrixType >::RealRowVectorType
template<typename _MatrixType> typedef MatrixType::RealScalar Eigen::CompleteOrthogonalDecomposition< _MatrixType >::RealScalar
template<typename _MatrixType> typedef internal::plain_row_type<MatrixType>::type Eigen::CompleteOrthogonalDecomposition< _MatrixType >::RowVectorType
template<typename _MatrixType> typedef MatrixType::Scalar Eigen::CompleteOrthogonalDecomposition< _MatrixType >::Scalar
template<typename _MatrixType> typedef MatrixType::StorageIndex Eigen::CompleteOrthogonalDecomposition< _MatrixType >::StorageIndex
Member Enumeration Documentation
template<typename _MatrixType> anonymous enum
Enumerator
RowsAtCompileTime
ColsAtCompileTime
MaxRowsAtCompileTime
MaxColsAtCompileTime
Constructor & Destructor Documentation
template<typename _MatrixType> Eigen::CompleteOrthogonalDecomposition< _MatrixType >::CompleteOrthogonalDecomposition () inline
Default Constructor.
The default constructor is useful in cases in which the user intends to perform decompositions via CompleteOrthogonalDecomposition::compute(const* MatrixType&).
template<typename _MatrixType> Eigen::CompleteOrthogonalDecomposition< _MatrixType >::CompleteOrthogonalDecomposition (Index rows, Index cols) inline
Default Constructor with memory preallocation.
Like the default constructor but with preallocation of the internal data according to the specified problem size.
See also
CompleteOrthogonalDecomposition()
template<typename _MatrixType> template<typename InputType > Eigen::CompleteOrthogonalDecomposition< _MatrixType >::CompleteOrthogonalDecomposition (const EigenBase< InputType > & matrix) inline explicit
Constructs a complete orthogonal decomposition from a given matrix.
This constructor computes the complete orthogonal decomposition of the matrix matrix by calling the method compute(). The default threshold for rank determination will be used. It is a short cut for:
CompleteOrthogonalDecomposition<MatrixType> cod(matrix.rows(),
                                                matrix.cols());
cod.setThreshold(Default);
cod.compute(matrix);
See also
compute()
References Eigen::EigenBase< Derived >::derived().
template<typename _MatrixType> template<typename InputType > Eigen::CompleteOrthogonalDecomposition< _MatrixType >::CompleteOrthogonalDecomposition (EigenBase< InputType > & matrix) inline explicit
Constructs a complete orthogonal decomposition from a given matrix.
This overloaded constructor is provided for inplace decomposition when MatrixType is a Eigen::Ref.
See also
CompleteOrthogonalDecomposition(const EigenBase&)
Member Function Documentation
template<typename _MatrixType > template<typename RhsType , typename DstType > void Eigen::CompleteOrthogonalDecomposition< _MatrixType >::_solve_impl (const RhsType & rhs, DstType & dst) const
References eigen_assert, and Eigen::householderSequence().
template<typename MatrixType > MatrixType::RealScalar Eigen::CompleteOrthogonalDecomposition< MatrixType >::absDeterminant () const
Returns
the absolute value of the determinant of the matrix of which *this is the complete orthogonal decomposition. It has only linear complexity (that is, O(n) where n is the dimension of the square matrix) as the complete orthogonal decomposition has already been computed.
Note
This is only for square matrices.
Warning
a determinant can be very big or small, so for matrices of large enough dimension, there is a risk of overflow/underflow. One way to work around that is to use logAbsDeterminant() instead.
See also
logAbsDeterminant(), MatrixBase::determinant()
template<typename MatrixType > template<typename Rhs > void Eigen::CompleteOrthogonalDecomposition< MatrixType >::applyZAdjointOnTheLeftInPlace (Rhs & rhs) const protected
Overwrites rhs with .
References Eigen::half_impl::max(), row(), and tail().
template<typename _MatrixType> static void Eigen::CompleteOrthogonalDecomposition< _MatrixType >::check_template_parameters () inline static protected
References EIGEN_STATIC_ASSERT_NON_INTEGER.
template<typename _MatrixType> Index Eigen::CompleteOrthogonalDecomposition< _MatrixType >::cols (void) const inline
template<typename _MatrixType> const PermutationType& Eigen::CompleteOrthogonalDecomposition< _MatrixType >::colsPermutation () const inline
Returns
a const reference to the column permutation matrix
template<typename _MatrixType> template<typename InputType > CompleteOrthogonalDecomposition& Eigen::CompleteOrthogonalDecomposition< _MatrixType >::compute (const EigenBase< InputType > & matrix) inline
References Eigen::CompleteOrthogonalDecomposition< _MatrixType >::compute().
Referenced by Eigen::CompleteOrthogonalDecomposition< _MatrixType >::compute().
template<typename MatrixType > void Eigen::CompleteOrthogonalDecomposition< MatrixType >::computeInPlace () protected
Performs the complete orthogonal decomposition of the given matrix matrix. The result of the factorization is stored into *this, and a reference to *this is returned.
See also
class CompleteOrthogonalDecomposition, CompleteOrthogonalDecomposition(const MatrixType&)
References eigen_assert, and Eigen::half_impl::min().
template<typename _MatrixType> Index Eigen::CompleteOrthogonalDecomposition< _MatrixType >::dimensionOfKernel () const inline
Returns
the dimension of the kernel of the matrix of which *this is the complete orthogonal decomposition.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
template<typename _MatrixType> const HCoeffsType& Eigen::CompleteOrthogonalDecomposition< _MatrixType >::hCoeffs () const inline
Returns
a const reference to the vector of Householder coefficients used to represent the factor Q.
For advanced uses only.
template<typename MatrixType > CompleteOrthogonalDecomposition< MatrixType >::HouseholderSequenceType Eigen::CompleteOrthogonalDecomposition< MatrixType >::householderQ (void) const
Returns
the matrix Q as a sequence of householder transformations
template<typename _MatrixType> ComputationInfo Eigen::CompleteOrthogonalDecomposition< _MatrixType >::info () const inline
Reports whether the complete orthogonal decomposition was succesful.
Note
This function always returns Success. It is provided for compatibility with other factorization routines.
Returns
Success
References eigen_assert, and Eigen::Success.
template<typename _MatrixType> bool Eigen::CompleteOrthogonalDecomposition< _MatrixType >::isInjective () const inline
Returns
true if the matrix of which *this is the decomposition represents an injective linear map, i.e. has trivial kernel; false otherwise.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
template<typename _MatrixType> bool Eigen::CompleteOrthogonalDecomposition< _MatrixType >::isInvertible () const inline
Returns
true if the matrix of which *this is the complete orthogonal decomposition is invertible.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
template<typename _MatrixType> bool Eigen::CompleteOrthogonalDecomposition< _MatrixType >::isSurjective () const inline
Returns
true if the matrix of which *this is the decomposition represents a surjective linear map; false otherwise.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
template<typename MatrixType > MatrixType::RealScalar Eigen::CompleteOrthogonalDecomposition< MatrixType >::logAbsDeterminant () const
Returns
the natural log of the absolute value of the determinant of the matrix of which *this is the complete orthogonal decomposition. It has only linear complexity (that is, O(n) where n is the dimension of the square matrix) as the complete orthogonal decomposition has already been computed.
Note
This is only for square matrices.
This method is useful to work around the risk of overflow/underflow that's inherent to determinant computation.
See also
absDeterminant(), MatrixBase::determinant()
template<typename _MatrixType> HouseholderSequenceType Eigen::CompleteOrthogonalDecomposition< _MatrixType >::matrixQ (void) const inline
template<typename _MatrixType> const MatrixType& Eigen::CompleteOrthogonalDecomposition< _MatrixType >::matrixQTZ () const inline
Returns
a reference to the matrix where the complete orthogonal decomposition is stored
template<typename _MatrixType> const MatrixType& Eigen::CompleteOrthogonalDecomposition< _MatrixType >::matrixT () const inline
Returns
a reference to the matrix where the complete orthogonal decomposition is stored.
Warning
The strict lower part and
cols() - rank()
right columns of this matrix contains internal values. Only the upper triangular part should be referenced. To get it, use
matrixT().template triangularView<Upper>()
For rank-deficient matrices, use
matrixR().topLeftCorner(rank(), rank()).template triangularView<Upper>()
template<typename _MatrixType> MatrixType Eigen::CompleteOrthogonalDecomposition< _MatrixType >::matrixZ () const inline
Returns
the matrix Z.
template<typename _MatrixType> RealScalar Eigen::CompleteOrthogonalDecomposition< _MatrixType >::maxPivot () const inline
Returns
the absolute value of the biggest pivot, i.e. the biggest diagonal coefficient of R.
template<typename _MatrixType> Index Eigen::CompleteOrthogonalDecomposition< _MatrixType >::nonzeroPivots () const inline
Returns
the number of nonzero pivots in the complete orthogonal decomposition. Here nonzero is meant in the exact sense, not in a fuzzy sense. So that notion isn't really intrinsically interesting, but it is still useful when implementing algorithms.
See also
rank()
template<typename _MatrixType> const Inverse<CompleteOrthogonalDecomposition> Eigen::CompleteOrthogonalDecomposition< _MatrixType >::pseudoInverse () const inline
Returns
the pseudo-inverse of the matrix of which *this is the complete orthogonal decomposition.
Warning
: Do not compute this->pseudoInverse()*rhs to solve a linear systems. It is more efficient and numerically stable to call this->solve(rhs).
template<typename _MatrixType> Index Eigen::CompleteOrthogonalDecomposition< _MatrixType >::rank () const inline
Returns
the rank of the matrix of which *this is the complete orthogonal decomposition.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
template<typename _MatrixType> Index Eigen::CompleteOrthogonalDecomposition< _MatrixType >::rows (void) const inline
template<typename _MatrixType> CompleteOrthogonalDecomposition& Eigen::CompleteOrthogonalDecomposition< _MatrixType >::setThreshold (const RealScalar & threshold) inline
Allows to prescribe a threshold to be used by certain methods, such as rank(), who need to determine when pivots are to be considered nonzero. Most be called before calling compute().
When it needs to get the threshold value, Eigen calls threshold(). By default, this uses a formula to automatically determine a reasonable threshold. Once you have called the present method setThreshold(const RealScalar&), your value is used instead.
Parameters
threshold The new value to use as the threshold.
A pivot will be considered nonzero if its absolute value is strictly greater than where maxpivot is the biggest pivot.
If you want to come back to the default behavior, call setThreshold(Default_t)
References Eigen::CompleteOrthogonalDecomposition< _MatrixType >::setThreshold().
Referenced by Eigen::CompleteOrthogonalDecomposition< _MatrixType >::setThreshold().
template<typename _MatrixType> CompleteOrthogonalDecomposition& Eigen::CompleteOrthogonalDecomposition< _MatrixType >::setThreshold (Default_t) inline
Allows to come back to the default behavior, letting Eigen use its default formula for determining the threshold.
You should pass the special object Eigen::Default as parameter here.
qr.setThreshold(Eigen::Default);
See the documentation of setThreshold(const RealScalar&).
References Eigen::Default, and Eigen::CompleteOrthogonalDecomposition< _MatrixType >::setThreshold().
template<typename _MatrixType> template<typename Rhs > const Solve<CompleteOrthogonalDecomposition, Rhs> Eigen::CompleteOrthogonalDecomposition< _MatrixType >::solve (const MatrixBase< Rhs > & b) const inline
This method computes the minimum-norm solution X to a least squares problem
where A is the matrix of which *this is the complete orthogonal decomposition.
Parameters
b the right-hand sides of the problem to solve.
Returns
a solution.
References eigen_assert.
template<typename _MatrixType> RealScalar Eigen::CompleteOrthogonalDecomposition< _MatrixType >::threshold () const inline
Returns the threshold that will be used by certain methods such as rank().
See the documentation of setThreshold(const RealScalar&).
template<typename _MatrixType> const HCoeffsType& Eigen::CompleteOrthogonalDecomposition< _MatrixType >::zCoeffs () const inline
Returns
a const reference to the vector of Householder coefficients used to represent the factor Z.
For advanced uses only.
Member Data Documentation
template<typename _MatrixType> ColPivHouseholderQR<MatrixType> Eigen::CompleteOrthogonalDecomposition< _MatrixType >::m_cpqr protected
template<typename _MatrixType> RowVectorType Eigen::CompleteOrthogonalDecomposition< _MatrixType >::m_temp protected
template<typename _MatrixType> HCoeffsType Eigen::CompleteOrthogonalDecomposition< _MatrixType >::m_zCoeffs protected
The documentation for this class was generated from the following files:
ForwardDeclarations.h
CompleteOrthogonalDecomposition.h