SmartMouse_2018: Eigen::Hyperplane< _Scalar, _AmbientDim, _Options > Class Template Reference
Eigen::Hyperplane< _Scalar, _AmbientDim, _Options > Class Template Reference
Geometry_Module
A hyperplane.
#include <ForwardDeclarations.h>
Public Types
enum { AmbientDimAtCompileTime = _AmbientDim, Options = _Options }
typedef _Scalar Scalar
typedef NumTraits< Scalar >::Real RealScalar
typedef Eigen::Index Index
typedef Matrix< Scalar, AmbientDimAtCompileTime, 1 > VectorType
typedef Matrix< Scalar, Index(AmbientDimAtCompileTime)==Dynamic?Dynamic:Index(AmbientDimAtCompileTime)+1, 1, Options > Coefficients
typedef Block< Coefficients, AmbientDimAtCompileTime, 1 > NormalReturnType
typedef const Block< const Coefficients, AmbientDimAtCompileTime, 1 > ConstNormalReturnType
Public Member Functions
EIGEN_DEVICE_FUNC Hyperplane ()
template<int OtherOptions>
EIGEN_DEVICE_FUNC Hyperplane (const Hyperplane< Scalar, AmbientDimAtCompileTime, OtherOptions > &other)
EIGEN_DEVICE_FUNC Hyperplane (Index _dim)
EIGEN_DEVICE_FUNC Hyperplane (const VectorType &n, const VectorType &e)
EIGEN_DEVICE_FUNC Hyperplane (const VectorType &n, const Scalar &d)
EIGEN_DEVICE_FUNC Hyperplane (const ParametrizedLine< Scalar, AmbientDimAtCompileTime > &parametrized)
EIGEN_DEVICE_FUNC ~Hyperplane ()
EIGEN_DEVICE_FUNC Index dim () const
EIGEN_DEVICE_FUNC void normalize (void)
EIGEN_DEVICE_FUNC Scalar signedDistance (const VectorType &p) const
EIGEN_DEVICE_FUNC Scalar absDistance (const VectorType &p) const
EIGEN_DEVICE_FUNC VectorType projection (const VectorType &p) const
EIGEN_DEVICE_FUNC ConstNormalReturnType normal () const
EIGEN_DEVICE_FUNC NormalReturnType normal ()
EIGEN_DEVICE_FUNC const Scalar & offset () const
EIGEN_DEVICE_FUNC Scalar & offset ()
EIGEN_DEVICE_FUNC const Coefficients & coeffs () const
EIGEN_DEVICE_FUNC Coefficients & coeffs ()
EIGEN_DEVICE_FUNC VectorType intersection (const Hyperplane &other) const
template<typename XprType >
EIGEN_DEVICE_FUNC Hyperplane & transform (const MatrixBase< XprType > &mat, TransformTraits traits=Affine)
template<int TrOptions>
EIGEN_DEVICE_FUNC Hyperplane & transform (const Transform< Scalar, AmbientDimAtCompileTime, Affine, TrOptions > &t, TransformTraits traits=Affine)
template<typename NewScalarType >
EIGEN_DEVICE_FUNC internal::cast_return_type< Hyperplane, Hyperplane< NewScalarType, AmbientDimAtCompileTime, Options > >::type cast () const
template<typename OtherScalarType , int OtherOptions>
EIGEN_DEVICE_FUNC Hyperplane (const Hyperplane< OtherScalarType, AmbientDimAtCompileTime, OtherOptions > &other)
template<int OtherOptions>
EIGEN_DEVICE_FUNC bool isApprox (const Hyperplane< Scalar, AmbientDimAtCompileTime, OtherOptions > &other, const typename NumTraits< Scalar >::Real &prec=NumTraits< Scalar >::dummy_precision()) const
Static Public Member Functions
static EIGEN_DEVICE_FUNC Hyperplane Through (const VectorType &p0, const VectorType &p1)
static EIGEN_DEVICE_FUNC Hyperplane Through (const VectorType &p0, const VectorType &p1, const VectorType &p2)
Protected Attributes
Coefficients m_coeffs
Detailed Description
template<typename _Scalar, int _AmbientDim, int _Options>
class Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >
A hyperplane.
A hyperplane is an affine subspace of dimension n-1 in a space of dimension n. For example, a hyperplane in a plane is a line; a hyperplane in 3-space is a plane.
Template Parameters
_Scalar the scalar type, i.e., the type of the coefficients
_AmbientDim the dimension of the ambient space, can be a compile time value or Dynamic. Notice that the dimension of the hyperplane is _AmbientDim-1.
This class represents an hyperplane as the zero set of the implicit equation where is a unit normal vector of the plane (linear part) and is the distance (offset) to the origin.
Member Typedef Documentation
template<typename _Scalar, int _AmbientDim, int _Options> typedef Matrix<Scalar,Index(AmbientDimAtCompileTime)==Dynamic ? Dynamic : Index(AmbientDimAtCompileTime)+1,1,Options> Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::Coefficients
template<typename _Scalar, int _AmbientDim, int _Options> typedef const Block<const Coefficients,AmbientDimAtCompileTime,1> Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::ConstNormalReturnType
template<typename _Scalar, int _AmbientDim, int _Options> typedef Eigen::Index Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::Index
Deprecated:
since Eigen 3.3
template<typename _Scalar, int _AmbientDim, int _Options> typedef Block<Coefficients,AmbientDimAtCompileTime,1> Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::NormalReturnType
template<typename _Scalar, int _AmbientDim, int _Options> typedef NumTraits<Scalar>::Real Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::RealScalar
template<typename _Scalar, int _AmbientDim, int _Options> typedef _Scalar Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::Scalar
template<typename _Scalar, int _AmbientDim, int _Options> typedef Matrix<Scalar,AmbientDimAtCompileTime,1> Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::VectorType
Member Enumeration Documentation
template<typename _Scalar, int _AmbientDim, int _Options> anonymous enum
Enumerator
AmbientDimAtCompileTime
Options
Constructor & Destructor Documentation
template<typename _Scalar, int _AmbientDim, int _Options> EIGEN_DEVICE_FUNC Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::Hyperplane () inline
Default constructor without initialization
Referenced by Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::cast(), and Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::transform().
template<typename _Scalar, int _AmbientDim, int _Options> template<int OtherOptions> EIGEN_DEVICE_FUNC Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::Hyperplane (const Hyperplane< Scalar, AmbientDimAtCompileTime, OtherOptions > & other) inline
template<typename _Scalar, int _AmbientDim, int _Options> EIGEN_DEVICE_FUNC Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::Hyperplane (Index _dim) inline explicit
Constructs a dynamic-size hyperplane with _dim the dimension of the ambient space
template<typename _Scalar, int _AmbientDim, int _Options> EIGEN_DEVICE_FUNC Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::Hyperplane (const VectorType & n, const VectorType & e) inline
Construct a plane from its normal n and a point e onto the plane.
Warning
the vector normal is assumed to be normalized.
References Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::normal(), and Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::offset().
template<typename _Scalar, int _AmbientDim, int _Options> EIGEN_DEVICE_FUNC Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::Hyperplane (const VectorType & n, const Scalar & d) inline
Constructs a plane from its normal n and distance to the origin d such that the algebraic equation of the plane is .
Warning
the vector normal is assumed to be normalized.
References Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::normal(), and Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::offset().
template<typename _Scalar, int _AmbientDim, int _Options> EIGEN_DEVICE_FUNC Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::Hyperplane (const ParametrizedLine< Scalar, AmbientDimAtCompileTime > & parametrized) inline explicit
Constructs a hyperplane passing through the parametrized line parametrized. If the dimension of the ambient space is greater than 2, then there isn't uniqueness, so an arbitrary choice is made.
References Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::direction(), Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::normal(), Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::offset(), and Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::origin().
template<typename _Scalar, int _AmbientDim, int _Options> EIGEN_DEVICE_FUNC Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::~Hyperplane () inline
template<typename _Scalar, int _AmbientDim, int _Options> template<typename OtherScalarType , int OtherOptions> EIGEN_DEVICE_FUNC Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::Hyperplane (const Hyperplane< OtherScalarType, AmbientDimAtCompileTime, OtherOptions > & other) inline explicit
Copy constructor with scalar type conversion
References Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::m_coeffs.
Member Function Documentation
template<typename _Scalar, int _AmbientDim, int _Options> EIGEN_DEVICE_FUNC Scalar Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::absDistance (const VectorType & p) const inline
Returns
the absolute distance between the plane *this and a point p.
See also
signedDistance()
References abs(), and Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::signedDistance().
template<typename _Scalar, int _AmbientDim, int _Options> template<typename NewScalarType > EIGEN_DEVICE_FUNC internal::cast_return_type<Hyperplane, Hyperplane<NewScalarType,AmbientDimAtCompileTime,Options> >::type Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::cast () const inline
Returns
*this with scalar type casted to NewScalarType
Note that if NewScalarType is equal to the current scalar type of *this then this function smartly returns a const reference to *this.
References Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::Hyperplane(), and type.
template<typename _Scalar, int _AmbientDim, int _Options> EIGEN_DEVICE_FUNC const Coefficients& Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::coeffs () const inline
Returns
a constant reference to the coefficients c_i of the plane equation:
References Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::m_coeffs.
Referenced by Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::intersection().
template<typename _Scalar, int _AmbientDim, int _Options> EIGEN_DEVICE_FUNC Coefficients& Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::coeffs () inline
Returns
a non-constant reference to the coefficients c_i of the plane equation:
References Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::m_coeffs.
template<typename _Scalar, int _AmbientDim, int _Options> EIGEN_DEVICE_FUNC Index Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::dim () const inline
Returns
the dimension in which the plane holds
References Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::AmbientDimAtCompileTime, Eigen::Dynamic, and Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::m_coeffs.
Referenced by Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::normal(), and Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::offset().
template<typename _Scalar, int _AmbientDim, int _Options> EIGEN_DEVICE_FUNC VectorType Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::intersection (const Hyperplane< _Scalar, _AmbientDim, _Options > & other) const inline
Returns
the intersection of *this with other.
Warning
The ambient space must be a plane, i.e. have dimension 2, so that *this and other are lines.
Note
If other is approximately parallel to *this, this method will return any point on *this.
References abs(), Eigen::PlainObjectBase< Derived >::coeff(), Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::coeffs(), and EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE.
template<typename _Scalar, int _AmbientDim, int _Options> template<int OtherOptions> EIGEN_DEVICE_FUNC bool Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::isApprox (const Hyperplane< Scalar, AmbientDimAtCompileTime, OtherOptions > & other, const typename NumTraits< Scalar >::Real & prec = NumTraits<Scalar>::dummy_precision()) const inline
Returns
true if *this is approximately equal to other, within the precision determined by prec.
See also
MatrixBase::isApprox()
References Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::m_coeffs.
template<typename _Scalar, int _AmbientDim, int _Options> EIGEN_DEVICE_FUNC ConstNormalReturnType Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::normal () const inline
Returns
a constant reference to the unit normal vector of the plane, which corresponds to the linear part of the implicit equation.
References Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::dim(), and Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::m_coeffs.
Referenced by Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::Hyperplane(), Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::intersectionParameter(), Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::normalize(), Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::ParametrizedLine(), Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::projection(), Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::signedDistance(), Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::Through(), and Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::transform().
template<typename _Scalar, int _AmbientDim, int _Options> EIGEN_DEVICE_FUNC NormalReturnType Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::normal () inline
Returns
a non-constant reference to the unit normal vector of the plane, which corresponds to the linear part of the implicit equation.
References Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::dim(), and Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::m_coeffs.
template<typename _Scalar, int _AmbientDim, int _Options> EIGEN_DEVICE_FUNC void Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::normalize (void) inline
normalizes *this
References Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::m_coeffs, and Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::normal().
template<typename _Scalar, int _AmbientDim, int _Options> EIGEN_DEVICE_FUNC const Scalar& Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::offset () const inline
Returns
the distance to the origin, which is also the "constant term" of the implicit equation
Warning
the vector normal is assumed to be normalized.
References Eigen::PlainObjectBase< Derived >::coeff(), Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::dim(), and Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::m_coeffs.
Referenced by Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::Hyperplane(), Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::intersectionParameter(), Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::ParametrizedLine(), Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::signedDistance(), and Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::transform().
template<typename _Scalar, int _AmbientDim, int _Options> EIGEN_DEVICE_FUNC Scalar& Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::offset () inline
Returns
a non-constant reference to the distance to the origin, which is also the constant part of the implicit equation
References Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::dim(), and Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::m_coeffs.
template<typename _Scalar, int _AmbientDim, int _Options> EIGEN_DEVICE_FUNC VectorType Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::projection (const VectorType & p) const inline
Returns
the projection of a point p onto the plane *this.
References Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::normal(), and Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::signedDistance().
template<typename _Scalar, int _AmbientDim, int _Options> EIGEN_DEVICE_FUNC Scalar Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::signedDistance (const VectorType & p) const inline
Returns
the signed distance between the plane *this and a point p.
See also
absDistance()
References Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::normal(), and Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::offset().
Referenced by Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::absDistance(), and Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::projection().
template<typename _Scalar, int _AmbientDim, int _Options> static EIGEN_DEVICE_FUNC Hyperplane Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::Through (const VectorType & p0, const VectorType & p1) inline static
Constructs a hyperplane passing through the two points. If the dimension of the ambient space is greater than 2, then there isn't uniqueness, so an arbitrary choice is made.
References Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::normal().
template<typename _Scalar, int _AmbientDim, int _Options> static EIGEN_DEVICE_FUNC Hyperplane Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::Through (const VectorType & p0, const VectorType & p1, const VectorType & p2) inline static
Constructs a hyperplane passing through the three points. The dimension of the ambient space is required to be exactly 3.
References Eigen::ComputeFullV, EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE, m, and Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::matrixV().
template<typename _Scalar, int _AmbientDim, int _Options> template<typename XprType > EIGEN_DEVICE_FUNC Hyperplane& Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::transform (const MatrixBase< XprType > & mat, TransformTraits traits = Affine) inline
Applies the transformation matrix mat to *this and returns a reference to *this.
Parameters
mat the Dim x Dim transformation matrix
traits specifies whether the matrix mat represents an Isometry or a more generic Affine transformation. The default is Affine.
References Eigen::Affine, eigen_assert, Eigen::MatrixBase< Derived >::inverse(), Eigen::Isometry, Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::m_coeffs, and Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::normal().
Referenced by Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::transform().
template<typename _Scalar, int _AmbientDim, int _Options> template<int TrOptions> EIGEN_DEVICE_FUNC Hyperplane& Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::transform (const Transform< Scalar, AmbientDimAtCompileTime, Affine, TrOptions > & t, TransformTraits traits = Affine) inline
Applies the transformation t to *this and returns a reference to *this.
Parameters
t the transformation of dimension Dim
traits specifies whether the transformation t represents an Isometry or a more generic Affine transformation. The default is Affine. Other kind of transformations are not supported.
References Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::Hyperplane(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::linear(), Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::normal(), Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::offset(), Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::transform(), and Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translation().
Member Data Documentation
template<typename _Scalar, int _AmbientDim, int _Options> Coefficients Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::m_coeffs protected
Referenced by Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::coeffs(), Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::dim(), Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::Hyperplane(), Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::isApprox(), Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::normal(), Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::normalize(), Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::offset(), and Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::transform().
The documentation for this class was generated from the following files:
ForwardDeclarations.h
Hyperplane.h