SmartMouse_2018: WallFollow Class Reference
WallFollow Class Reference
starts at 0,0 and explores the whole maze. simply fallows the left hand wall. We know this won't solve the competition maze.
#include <WallFollow.h>
Public Member Functions
WallFollow (Mouse *mouse)
virtual void setup () override
virtual motion_primitive_t planNextStep () override
virtual route_t solve () override
virtual void teardown () override
virtual bool isFinished () override
virtual void setGoal (Solver::Goal goal) override
Public Member Functions inherited from Solver
Solver (Mouse *mouse)
bool isSolvable ()
Private Attributes
Solver::Goal goal
Additional Inherited Members
Public Types inherited from Solver
enum Goal { Goal::CENTER, Goal::START }
Public Attributes inherited from Solver
bool solvable
Mouse * mouse
Detailed Description
starts at 0,0 and explores the whole maze. simply fallows the left hand wall. We know this won't solve the competition maze.
Constructor & Destructor Documentation
WallFollow::WallFollow (Mouse * mouse)
Member Function Documentation
bool WallFollow::isFinished () override virtual
Implements Solver.
References Solver::CENTER, Mouse::getCol(), Mouse::getRow(), goal, Solver::mouse, smartmouse::maze::SIZE, Solver::solvable, and Solver::START.
Referenced by solve().
motion_primitive_t WallFollow::planNextStep () override virtual
Implements Solver.
References Mouse::checkWalls(), Mouse::getDir(), INVALID, SensorReading::isWall(), left_of_dir(), Mouse::mark_mouse_position_visited(), Solver::mouse, opposite_direction(), and Solver::solvable.
Referenced by solve().
void WallFollow::setGoal (Solver::Goal goal) override virtual
Implements Solver.
References goal.
void WallFollow::setup () override virtual
Implements Solver.
References Solver::CENTER, goal, AbstractMaze::mark_origin_known(), Mouse::maze, Solver::mouse, Mouse::reset(), and AbstractMaze::reset().
Referenced by TEST().
route_t WallFollow::solve () override virtual
Implements Solver.
References motion_primitive_t::d, AbstractMaze::fastest_route, insert_motion_primitive_back(), Mouse::internalForward(), Mouse::internalTurnToFace(), INVALID, isFinished(), Mouse::maze, Solver::mouse, planNextStep(), and teardown().
Referenced by TEST().
void WallFollow::teardown () override virtual
Implements Solver.
Referenced by solve(), and TEST().
Member Data Documentation
Solver::Goal WallFollow::goal private
Referenced by isFinished(), setGoal(), and setup().
The documentation for this class was generated from the following files:
WallFollow.h
WallFollow.cpp