SmartMouse_2018: Eigen::PermutationBase< Derived > Class Template Reference
Eigen::PermutationBase< Derived > Class Template Reference
Base class for permutations.
#include <PermutationMatrix.h>
Public Types
enum {
Flags = Traits::Flags, RowsAtCompileTime = Traits::RowsAtCompileTime, ColsAtCompileTime = Traits::ColsAtCompileTime, MaxRowsAtCompileTime = Traits::MaxRowsAtCompileTime,
MaxColsAtCompileTime = Traits::MaxColsAtCompileTime
}
typedef Traits::IndicesType IndicesType
typedef Traits::StorageIndex StorageIndex
typedef Matrix< StorageIndex, RowsAtCompileTime, ColsAtCompileTime, 0, MaxRowsAtCompileTime, MaxColsAtCompileTime > DenseMatrixType
typedef PermutationMatrix< IndicesType::SizeAtCompileTime, IndicesType::MaxSizeAtCompileTime, StorageIndex > PlainPermutationType
typedef PlainPermutationType PlainObject
typedef Inverse< Derived > InverseReturnType
typedef void Scalar
Public Types inherited from Eigen::EigenBase< Derived >
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< Derived >::StorageKind StorageKind
Public Member Functions
template<typename OtherDerived >
Derived & operator= (const PermutationBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator= (const TranspositionsBase< OtherDerived > &tr)
Derived & operator= (const PermutationBase &other)
Index rows () const
Index cols () const
Index size () const
template<typename DenseDerived >
void evalTo (MatrixBase< DenseDerived > &other) const
DenseMatrixType toDenseMatrix () const
const IndicesType & indices () const
IndicesType & indices ()
void resize (Index newSize)
void setIdentity ()
void setIdentity (Index newSize)
Derived & applyTranspositionOnTheLeft (Index i, Index j)
Derived & applyTranspositionOnTheRight (Index i, Index j)
InverseReturnType inverse () const
InverseReturnType transpose () const
template<typename Other >
PlainPermutationType operator* (const PermutationBase< Other > &other) const
template<typename Other >
PlainPermutationType operator* (const InverseImpl< Other, PermutationStorage > &other) const
Index determinant () const
Public Member Functions inherited from Eigen::EigenBase< Derived >
EIGEN_DEVICE_FUNC Derived & derived ()
EIGEN_DEVICE_FUNC const Derived & derived () const
EIGEN_DEVICE_FUNC Derived & const_cast_derived () const
EIGEN_DEVICE_FUNC const Derived & const_derived () const
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
EIGEN_DEVICE_FUNC Index size () const
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
Protected Member Functions
template<typename OtherDerived >
void assignTranspose (const PermutationBase< OtherDerived > &other)
template<typename Lhs , typename Rhs >
void assignProduct (const Lhs &lhs, const Rhs &rhs)
Private Types
typedef internal::traits< Derived > Traits
typedef EigenBase< Derived > Base
Friends
template<typename Other >
PlainPermutationType operator* (const InverseImpl< Other, PermutationStorage > &other, const PermutationBase &perm)
Detailed Description
template<typename Derived>
class Eigen::PermutationBase< Derived >
Base class for permutations.
Template Parameters
Derived the derived class
This class is the base class for all expressions representing a permutation matrix, internally stored as a vector of integers. The convention followed here is that if is a permutation, the corresponding permutation matrix is such that if is the canonical basis, we have:
This convention ensures that for any two permutations , we have:
Permutation matrices are square and invertible.
Notice that in addition to the member functions and operators listed here, there also are non-member operator* to multiply any kind of permutation object with any kind of matrix expression (MatrixBase) on either side.
See also
class PermutationMatrix, class PermutationWrapper
Member Typedef Documentation
template<typename Derived> typedef EigenBase<Derived> Eigen::PermutationBase< Derived >::Base private
template<typename Derived> typedef Matrix<StorageIndex,RowsAtCompileTime,ColsAtCompileTime,0,MaxRowsAtCompileTime,MaxColsAtCompileTime> Eigen::PermutationBase< Derived >::DenseMatrixType
template<typename Derived> typedef Traits::IndicesType Eigen::PermutationBase< Derived >::IndicesType
template<typename Derived> typedef Inverse<Derived> Eigen::PermutationBase< Derived >::InverseReturnType
template<typename Derived> typedef PlainPermutationType Eigen::PermutationBase< Derived >::PlainObject
template<typename Derived> typedef PermutationMatrix<IndicesType::SizeAtCompileTime,IndicesType::MaxSizeAtCompileTime,StorageIndex> Eigen::PermutationBase< Derived >::PlainPermutationType
template<typename Derived> typedef void Eigen::PermutationBase< Derived >::Scalar
template<typename Derived> typedef Traits::StorageIndex Eigen::PermutationBase< Derived >::StorageIndex
template<typename Derived> typedef internal::traits<Derived> Eigen::PermutationBase< Derived >::Traits private
Member Enumeration Documentation
template<typename Derived> anonymous enum
Enumerator
Flags
RowsAtCompileTime
ColsAtCompileTime
MaxRowsAtCompileTime
MaxColsAtCompileTime
Member Function Documentation
template<typename Derived> Derived& Eigen::PermutationBase< Derived >::applyTranspositionOnTheLeft (Index i, Index j) inline
Multiplies *this by the transposition on the left.
Returns
a reference to *this.
Warning
This is much slower than applyTranspositionOnTheRight(Index,Index): this has linear complexity and requires a lot of branching.
See also
applyTranspositionOnTheRight(Index,Index)
template<typename Derived> Derived& Eigen::PermutationBase< Derived >::applyTranspositionOnTheRight (Index i, Index j) inline
Multiplies *this by the transposition on the right.
Returns
a reference to *this.
This is a fast operation, it only consists in swapping two indices.
See also
applyTranspositionOnTheLeft(Index,Index)
Referenced by Eigen::FullPivLU< _MatrixType >::computeInPlace().
template<typename Derived> template<typename Lhs , typename Rhs > void Eigen::PermutationBase< Derived >::assignProduct (const Lhs & lhs, const Rhs & rhs) inline protected
template<typename Derived> template<typename OtherDerived > void Eigen::PermutationBase< Derived >::assignTranspose (const PermutationBase< OtherDerived > & other) inline protected
template<typename Derived> Index Eigen::PermutationBase< Derived >::cols (void) const inline
Returns
the number of columns
template<typename Derived> Index Eigen::PermutationBase< Derived >::determinant () const inline
Returns
the determinant of the permutation matrix, which is either 1 or -1 depending on the parity of the permutation.
This function is O(n) procedure allocating a buffer of n booleans.
Referenced by Eigen::SparseLU< _MatrixType, _OrderingType >::factorize().
template<typename Derived> template<typename DenseDerived > void Eigen::PermutationBase< Derived >::evalTo (MatrixBase< DenseDerived > & other) const inline
template<typename Derived> const IndicesType& Eigen::PermutationBase< Derived >::indices () const inline
const version of indices().
Referenced by Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex > >::assignTranspose(), Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex > >::operator=(), and Eigen::PermutationMatrix< RowsAtCompileTime, MaxRowsAtCompileTime >::operator=().
template<typename Derived> IndicesType& Eigen::PermutationBase< Derived >::indices () inline
Returns
a reference to the stored array representing the permutation.
template<typename Derived> InverseReturnType Eigen::PermutationBase< Derived >::inverse () const inline
Returns
the inverse permutation matrix.
Note
Referenced by Eigen::SparseLU< _MatrixType, _OrderingType >::_solve_impl(), Eigen::FullPivLU< _MatrixType >::_solve_impl_transposed(), Eigen::SparseLU< _MatrixType, _OrderingType >::factorize(), Eigen::PartialPivLU< _MatrixType >::reconstructedMatrix(), and Eigen::FullPivLU< _MatrixType >::reconstructedMatrix().
template<typename Derived> template<typename Other > PlainPermutationType Eigen::PermutationBase< Derived >::operator* (const PermutationBase< Other > & other) const inline
Returns
the product permutation matrix.
Note
template<typename Derived> template<typename Other > PlainPermutationType Eigen::PermutationBase< Derived >::operator* (const InverseImpl< Other, PermutationStorage > & other) const inline
Returns
the product of a permutation with another inverse permutation.
Note
template<typename Derived> template<typename OtherDerived > Derived& Eigen::PermutationBase< Derived >::operator= (const PermutationBase< OtherDerived > & other) inline
Copies the other permutation into *this
template<typename Derived> template<typename OtherDerived > Derived& Eigen::PermutationBase< Derived >::operator= (const TranspositionsBase< OtherDerived > & tr) inline
Assignment from the Transpositions tr
template<typename Derived> Derived& Eigen::PermutationBase< Derived >::operator= (const PermutationBase< Derived > & other) inline
This is a special case of the templated operator=. Its purpose is to prevent a default operator= from hiding the templated operator=.
template<typename Derived> void Eigen::PermutationBase< Derived >::resize (Index newSize) inline
Resizes to given size.
Referenced by Eigen::SparseLU< _MatrixType, _OrderingType >::factorize(), Eigen::PardisoLLT< MatrixType, _UpLo >::getMatrix(), Eigen::PardisoLDLT< MatrixType, Options >::getMatrix(), Eigen::internal::minimum_degree_ordering(), and Eigen::MetisOrdering< StorageIndex >::operator()().
template<typename Derived> Index Eigen::PermutationBase< Derived >::rows (void) const inline
Returns
the number of rows
template<typename Derived> void Eigen::PermutationBase< Derived >::setIdentity () inline
Sets *this to be the identity permutation matrix
Referenced by Eigen::FullPivLU< _MatrixType >::computeInPlace().
template<typename Derived> void Eigen::PermutationBase< Derived >::setIdentity (Index newSize) inline
Sets *this to be the identity permutation matrix of given size.
template<typename Derived> Index Eigen::PermutationBase< Derived >::size () const inline
Returns
the size of a side of the respective square matrix, i.e., the number of indices
Referenced by Eigen::SparseLU< _MatrixType, _OrderingType >::analyzePattern(), Eigen::SparseLU< _MatrixType, _OrderingType >::factorize(), and Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex > >::size().
template<typename Derived> DenseMatrixType Eigen::PermutationBase< Derived >::toDenseMatrix () const inline
Returns
a Matrix object initialized from this permutation matrix. Notice that it is inefficient to return this Matrix object by value. For efficiency, favor using the Matrix constructor taking EigenBase objects.
template<typename Derived> InverseReturnType Eigen::PermutationBase< Derived >::transpose () const inline
Returns
the tranpose permutation matrix.
Note
Referenced by Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, SparseShape >::run().
Friends And Related Function Documentation
template<typename Derived> template<typename Other > PlainPermutationType operator* (const InverseImpl< Other, PermutationStorage > & other, const PermutationBase< Derived > & perm) friend
Returns
the product of an inverse permutation with another permutation.
Note
The documentation for this class was generated from the following file:
PermutationMatrix.h