SmartMouse_2018: Eigen::ArithmeticSequence< FirstType, SizeType, IncrType > Class Template Reference
Eigen::ArithmeticSequence< FirstType, SizeType, IncrType > Class Template Reference
#include <ArithmeticSequence.h>
Public Types
enum { SizeAtCompileTime = internal::get_fixed_value<SizeType>::value, IncrAtCompileTime = internal::get_fixed_value<IncrType,DynamicIndex>::value }
Public Member Functions
ArithmeticSequence (FirstType first, SizeType size)
ArithmeticSequence (FirstType first, SizeType size, IncrType incr)
Index size () const
Index first () const
Index operator[] (Index i) const
const FirstType & firstObject () const
const SizeType & sizeObject () const
const IncrType & incrObject () const
ArithmeticSequence< ReverseFirstType, SizeType, ReverseIncrType > reverse () const
Protected Types
typedef internal::aseq_negate< IncrType >::type ReverseIncrType
typedef internal::aseq_reverse_first_type< FirstType, SizeType, IncrType >::type ReverseFirstType
Protected Attributes
FirstType m_first
SizeType m_size
IncrType m_incr
Detailed Description
template<typename FirstType, typename SizeType, typename IncrType>
class Eigen::ArithmeticSequence< FirstType, SizeType, IncrType >
This class represents an arithmetic progression defined by its first value , its size (aka length) n, and the increment (aka stride) that is equal to for any i.
It is internally used as the return type of the Eigen::seq and Eigen::seqN functions, and as the input arguments of DenseBase::operator()(const RowIndices&, const ColIndices&), and most of the time this is the only way it is used.
Template Parameters
FirstType type of the first element, usually an Index, but internally it can be a symbolic expression
SizeType type representing the size of the sequence, usually an Index or a compile time integral constant. Internally, it can also be a symbolic expression
IncrType type of the increment, can be a runtime Index, or a compile time integral constant (default is compile-time 1)
See also
Eigen::seq, Eigen::seqN, DenseBase::operator()(const RowIndices&, const ColIndices&), class IndexedView
Member Typedef Documentation
template<typename FirstType, typename SizeType, typename IncrType> typedef internal::aseq_reverse_first_type<FirstType,SizeType,IncrType>::type Eigen::ArithmeticSequence< FirstType, SizeType, IncrType >::ReverseFirstType protected
template<typename FirstType, typename SizeType, typename IncrType> typedef internal::aseq_negate<IncrType>::type Eigen::ArithmeticSequence< FirstType, SizeType, IncrType >::ReverseIncrType protected
Member Enumeration Documentation
template<typename FirstType, typename SizeType, typename IncrType> anonymous enum
Enumerator
SizeAtCompileTime
IncrAtCompileTime
Constructor & Destructor Documentation
template<typename FirstType, typename SizeType, typename IncrType> Eigen::ArithmeticSequence< FirstType, SizeType, IncrType >::ArithmeticSequence (FirstType first, SizeType size) inline
template<typename FirstType, typename SizeType, typename IncrType> Eigen::ArithmeticSequence< FirstType, SizeType, IncrType >::ArithmeticSequence (FirstType first, SizeType size, IncrType incr) inline
Member Function Documentation
template<typename FirstType, typename SizeType, typename IncrType> Index Eigen::ArithmeticSequence< FirstType, SizeType, IncrType >::first () const inline
Returns
the first element in the sequence
template<typename FirstType, typename SizeType, typename IncrType> const FirstType& Eigen::ArithmeticSequence< FirstType, SizeType, IncrType >::firstObject () const inline
Referenced by Eigen::internal::makeIndexedViewCompatible().
template<typename FirstType, typename SizeType, typename IncrType> const IncrType& Eigen::ArithmeticSequence< FirstType, SizeType, IncrType >::incrObject () const inline
Referenced by Eigen::internal::makeIndexedViewCompatible().
template<typename FirstType, typename SizeType, typename IncrType> Index Eigen::ArithmeticSequence< FirstType, SizeType, IncrType >::operator[] (Index i) const inline
Returns
the value at index i in the sequence.
template<typename FirstType, typename SizeType, typename IncrType> ArithmeticSequence<ReverseFirstType,SizeType,ReverseIncrType> Eigen::ArithmeticSequence< FirstType, SizeType, IncrType >::reverse () const inline
References Eigen::seqN().
template<typename FirstType, typename SizeType, typename IncrType> Index Eigen::ArithmeticSequence< FirstType, SizeType, IncrType >::size () const inline
Returns
the size, i.e., number of elements, of the sequence
template<typename FirstType, typename SizeType, typename IncrType> const SizeType& Eigen::ArithmeticSequence< FirstType, SizeType, IncrType >::sizeObject () const inline
Referenced by Eigen::internal::makeIndexedViewCompatible().
Member Data Documentation
template<typename FirstType, typename SizeType, typename IncrType> FirstType Eigen::ArithmeticSequence< FirstType, SizeType, IncrType >::m_first protected
template<typename FirstType, typename SizeType, typename IncrType> IncrType Eigen::ArithmeticSequence< FirstType, SizeType, IncrType >::m_incr protected
template<typename FirstType, typename SizeType, typename IncrType> SizeType Eigen::ArithmeticSequence< FirstType, SizeType, IncrType >::m_size protected
The documentation for this class was generated from the following file:
ArithmeticSequence.h