SmartMouse_2018: Scheduler Class Reference
Scheduler Class Reference
is the master of all commands. It knows executes the inialize, execute, and end functions Right now, it only supports parallel commands Sequential commands could be added by copying the logic from CommandGroups
#include <Scheduler.h>
Public Member Functions
Scheduler (Command *command)
pass the master command to the constructor
void addCommand (Command *command)
adds a command to the command group
bool run ()
runs all the commands. Iterates through the list of commands and runs them. If they are done, it removes them from the list of commands.
Private Attributes
LinkedList< Command * > commands
list of commands
Static Private Attributes
static Scheduler * instance
singleton instance
Detailed Description
is the master of all commands. It knows executes the inialize, execute, and end functions Right now, it only supports parallel commands Sequential commands could be added by copying the logic from CommandGroups
Constructor & Destructor Documentation
Scheduler::Scheduler (Command * command)
pass the master command to the constructor
Parameters
References addCommand().
Member Function Documentation
void Scheduler::addCommand (Command * command)
adds a command to the command group
Parameters
References LinkedList< T >::add(), and commands.
Referenced by Scheduler().
bool Scheduler::run ()
runs all the commands. Iterates through the list of commands and runs them. If they are done, it removes them from the list of commands.
Returns
returns true if there are no commands left
References commands, Command::cycle(), LinkedList< T >::get(), i, LinkedList< T >::remove(), and LinkedList< T >::size().
Referenced by loop(), and main().
Member Data Documentation
LinkedList<Command *> Scheduler::commands private
list of commands
Referenced by addCommand(), and run().
Scheduler* Scheduler::instance static private
singleton instance
The documentation for this class was generated from the following files:
Scheduler.h
Scheduler.cpp