SmartMouse_2018: Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > Class Template Reference
Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > Class Template Reference
Represents a diagonal matrix with its storage.
#include <DiagonalMatrix.h>
Public Types
typedef internal::traits< DiagonalMatrix >::DiagonalVectorType DiagonalVectorType
typedef const DiagonalMatrix & Nested
typedef _Scalar Scalar
typedef internal::traits< DiagonalMatrix >::StorageKind StorageKind
typedef internal::traits< DiagonalMatrix >::StorageIndex StorageIndex
Public Types inherited from Eigen::DiagonalBase< DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > >
enum
typedef internal::traits< DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > >::DiagonalVectorType DiagonalVectorType
typedef DiagonalVectorType::Scalar Scalar
typedef DiagonalVectorType::RealScalar RealScalar
typedef internal::traits< DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > >::StorageKind StorageKind
typedef internal::traits< DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > >::StorageIndex StorageIndex
typedef Matrix< Scalar, RowsAtCompileTime, ColsAtCompileTime, 0, MaxRowsAtCompileTime, MaxColsAtCompileTime > DenseMatrixType
typedef DenseMatrixType DenseType
typedef DiagonalMatrix< Scalar, DiagonalVectorType::SizeAtCompileTime, DiagonalVectorType::MaxSizeAtCompileTime > PlainObject
typedef DiagonalWrapper< const CwiseUnaryOp< internal::scalar_inverse_op< Scalar >, const DiagonalVectorType > > InverseReturnType
Public Types inherited from Eigen::EigenBase< Derived >
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< Derived >::StorageKind StorageKind
Public Member Functions
EIGEN_DEVICE_FUNC const DiagonalVectorType & diagonal () const
EIGEN_DEVICE_FUNC DiagonalVectorType & diagonal ()
EIGEN_DEVICE_FUNC DiagonalMatrix ()
EIGEN_DEVICE_FUNC DiagonalMatrix (Index dim)
EIGEN_DEVICE_FUNC DiagonalMatrix (const Scalar &x, const Scalar &y)
EIGEN_DEVICE_FUNC DiagonalMatrix (const Scalar &x, const Scalar &y, const Scalar &z)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC DiagonalMatrix (const DiagonalBase< OtherDerived > &other)
DiagonalMatrix (const DiagonalMatrix &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC DiagonalMatrix (const MatrixBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC DiagonalMatrix & operator= (const DiagonalBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC DiagonalMatrix & operator= (const DiagonalMatrix &other)
EIGEN_DEVICE_FUNC void resize (Index size)
EIGEN_DEVICE_FUNC void setZero ()
EIGEN_DEVICE_FUNC void setZero (Index size)
EIGEN_DEVICE_FUNC void setIdentity ()
EIGEN_DEVICE_FUNC void setIdentity (Index size)
Public Member Functions inherited from Eigen::DiagonalBase< DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > >
EIGEN_DEVICE_FUNC const DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > & derived () const
EIGEN_DEVICE_FUNC DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > & derived ()
EIGEN_DEVICE_FUNC DenseMatrixType toDenseMatrix () const
EIGEN_DEVICE_FUNC const DiagonalVectorType & diagonal () const
EIGEN_DEVICE_FUNC DiagonalVectorType & diagonal ()
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
EIGEN_DEVICE_FUNC const Product< DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >, MatrixDerived, LazyProduct > operator* (const MatrixBase< MatrixDerived > &matrix) const
EIGEN_DEVICE_FUNC const DiagonalWrapper< const EIGEN_EXPR_BINARYOP_SCALAR_RETURN_TYPE(DiagonalVectorType, Scalar, product) > operator* (const Scalar &scalar) const
EIGEN_DEVICE_FUNC const InverseReturnType inverse () const
Public Member Functions inherited from Eigen::EigenBase< Derived >
EIGEN_DEVICE_FUNC Derived & derived ()
EIGEN_DEVICE_FUNC const Derived & derived () const
EIGEN_DEVICE_FUNC Derived & const_cast_derived () const
EIGEN_DEVICE_FUNC const Derived & const_derived () const
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
EIGEN_DEVICE_FUNC Index size () const
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
Protected Attributes
DiagonalVectorType m_diagonal
Detailed Description
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime>
class Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >
Represents a diagonal matrix with its storage.
Parameters
_Scalar the type of coefficients
SizeAtCompileTime the dimension of the matrix, or Dynamic
MaxSizeAtCompileTime the dimension of the matrix, or Dynamic. This parameter is optional and defaults to SizeAtCompileTime. Most of the time, you do not need to specify it.
See also
class DiagonalWrapper
Member Typedef Documentation
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> typedef internal::traits<DiagonalMatrix>::DiagonalVectorType Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::DiagonalVectorType
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> typedef const DiagonalMatrix& Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::Nested
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> typedef _Scalar Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::Scalar
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> typedef internal::traits<DiagonalMatrix>::StorageIndex Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::StorageIndex
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> typedef internal::traits<DiagonalMatrix>::StorageKind Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::StorageKind
Constructor & Destructor Documentation
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> EIGEN_DEVICE_FUNC Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::DiagonalMatrix () inline
Default constructor without initialization
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> EIGEN_DEVICE_FUNC Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::DiagonalMatrix (Index dim) inline explicit
Constructs a diagonal matrix with given dimension
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> EIGEN_DEVICE_FUNC Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::DiagonalMatrix (const Scalar & x, const Scalar & y) inline
2D constructor.
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> EIGEN_DEVICE_FUNC Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::DiagonalMatrix (const Scalar & x, const Scalar & y, const Scalar & z) inline
3D constructor.
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> template<typename OtherDerived > EIGEN_DEVICE_FUNC Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::DiagonalMatrix (const DiagonalBase< OtherDerived > & other) inline
Copy constructor.
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::DiagonalMatrix (const DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > & other) inline
copy constructor. prevent a default copy constructor from hiding the other templated constructor
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> template<typename OtherDerived > EIGEN_DEVICE_FUNC Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::DiagonalMatrix (const MatrixBase< OtherDerived > & other) inline explicit
generic constructor from expression of the diagonal coefficients
Member Function Documentation
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> EIGEN_DEVICE_FUNC const DiagonalVectorType& Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::diagonal () const inline
const version of diagonal().
Referenced by Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::operator=().
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> EIGEN_DEVICE_FUNC DiagonalVectorType& Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::diagonal () inline
Returns
a reference to the stored vector of diagonal coefficients.
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> template<typename OtherDerived > EIGEN_DEVICE_FUNC DiagonalMatrix& Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::operator= (const DiagonalBase< OtherDerived > & other) inline
Copy operator.
References Eigen::DiagonalBase< Derived >::diagonal().
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> EIGEN_DEVICE_FUNC DiagonalMatrix& Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::operator= (const DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > & other) inline
This is a special case of the templated operator=. Its purpose is to prevent a default operator= from hiding the templated operator=.
References Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::diagonal().
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> EIGEN_DEVICE_FUNC void Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::resize (Index size) inline
Resizes to given size.
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> EIGEN_DEVICE_FUNC void Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::setIdentity () inline
Sets this matrix to be the identity matrix of the current size.
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> EIGEN_DEVICE_FUNC void Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::setIdentity (Index size) inline
Sets this matrix to be the identity matrix of the given size.
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> EIGEN_DEVICE_FUNC void Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::setZero () inline
Sets all coefficients to zero.
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> EIGEN_DEVICE_FUNC void Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::setZero (Index size) inline
Resizes and sets all coefficients to zero.
Member Data Documentation
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> DiagonalVectorType Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::m_diagonal protected
The documentation for this class was generated from the following file:
DiagonalMatrix.h