SmartMouse_2018: Eigen::AngleAxis< _Scalar > Class Template Reference
Eigen::AngleAxis< _Scalar > Class Template Reference
Geometry_Module
Represents a 3D rotation as a rotation angle around an arbitrary 3D axis.
#include <ForwardDeclarations.h>
Public Types
enum { Dim = 3 }
typedef _Scalar Scalar
typedef Matrix< Scalar, 3, 3 > Matrix3
typedef Matrix< Scalar, 3, 1 > Vector3
typedef Quaternion< Scalar > QuaternionType
Public Types inherited from Eigen::RotationBase< AngleAxis< _Scalar >, 3 >
enum
typedef internal::traits< AngleAxis< _Scalar > >::Scalar Scalar
typedef Matrix< Scalar, Dim, Dim > RotationMatrixType
typedef Matrix< Scalar, Dim, 1 > VectorType
Public Member Functions
EIGEN_DEVICE_FUNC AngleAxis ()
template<typename Derived >
EIGEN_DEVICE_FUNC AngleAxis (const Scalar &angle, const MatrixBase< Derived > &axis)
template<typename QuatDerived >
EIGEN_DEVICE_FUNC AngleAxis (const QuaternionBase< QuatDerived > &q)
template<typename Derived >
EIGEN_DEVICE_FUNC AngleAxis (const MatrixBase< Derived > &m)
EIGEN_DEVICE_FUNC Scalar angle () const
EIGEN_DEVICE_FUNC Scalar & angle ()
EIGEN_DEVICE_FUNC const Vector3 & axis () const
EIGEN_DEVICE_FUNC Vector3 & axis ()
EIGEN_DEVICE_FUNC QuaternionType operator* (const AngleAxis &other) const
EIGEN_DEVICE_FUNC QuaternionType operator* (const QuaternionType &other) const
EIGEN_DEVICE_FUNC AngleAxis inverse () const
template<class QuatDerived >
EIGEN_DEVICE_FUNC AngleAxis & operator= (const QuaternionBase< QuatDerived > &q)
template<typename Derived >
EIGEN_DEVICE_FUNC AngleAxis & operator= (const MatrixBase< Derived > &m)
template<typename Derived >
EIGEN_DEVICE_FUNC AngleAxis & fromRotationMatrix (const MatrixBase< Derived > &m)
EIGEN_DEVICE_FUNC Matrix3 toRotationMatrix (void) const
template<typename NewScalarType >
EIGEN_DEVICE_FUNC internal::cast_return_type< AngleAxis, AngleAxis< NewScalarType > >::type cast () const
template<typename OtherScalarType >
EIGEN_DEVICE_FUNC AngleAxis (const AngleAxis< OtherScalarType > &other)
EIGEN_DEVICE_FUNC bool isApprox (const AngleAxis &other, const typename NumTraits< Scalar >::Real &prec=NumTraits< Scalar >::dummy_precision()) const
template<typename QuatDerived >
EIGEN_DEVICE_FUNC AngleAxis< Scalar > & operator= (const QuaternionBase< QuatDerived > &q)
template<typename Derived >
EIGEN_DEVICE_FUNC AngleAxis< Scalar > & operator= (const MatrixBase< Derived > &mat)
template<typename Derived >
EIGEN_DEVICE_FUNC AngleAxis< Scalar > & fromRotationMatrix (const MatrixBase< Derived > &mat)
Sets *this from a 3x3 rotation matrix.
Public Member Functions inherited from Eigen::RotationBase< AngleAxis< _Scalar >, 3 >
EIGEN_DEVICE_FUNC const AngleAxis< _Scalar > & derived () const
EIGEN_DEVICE_FUNC AngleAxis< _Scalar > & derived ()
EIGEN_DEVICE_FUNC RotationMatrixType toRotationMatrix () const
EIGEN_DEVICE_FUNC RotationMatrixType matrix () const
EIGEN_DEVICE_FUNC AngleAxis< _Scalar > inverse () const
EIGEN_DEVICE_FUNC Transform< Scalar, Dim, Isometry > operator* (const Translation< Scalar, Dim > &t) const
EIGEN_DEVICE_FUNC RotationMatrixType operator* (const UniformScaling< Scalar > &s) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::rotation_base_generic_product_selector< AngleAxis< _Scalar >, OtherDerived, OtherDerived::IsVectorAtCompileTime >::ReturnType operator* (const EigenBase< OtherDerived > &e) const
EIGEN_DEVICE_FUNC Transform< Scalar, Dim, Mode > operator* (const Transform< Scalar, Dim, Mode, Options > &t) const
EIGEN_DEVICE_FUNC VectorType _transformVector (const OtherVectorType &v) const
Static Public Member Functions
static EIGEN_DEVICE_FUNC const AngleAxis Identity ()
Protected Attributes
Vector3 m_axis
Scalar m_angle
Private Types
typedef RotationBase< AngleAxis< _Scalar >, 3 > Base
Friends
EIGEN_DEVICE_FUNC QuaternionType operator* (const QuaternionType &a, const AngleAxis &b)
Detailed Description
template<typename _Scalar>
class Eigen::AngleAxis< _Scalar >
Represents a 3D rotation as a rotation angle around an arbitrary 3D axis.
Parameters
_Scalar the scalar type, i.e., the type of the coefficients.
Warning
When setting up an AngleAxis object, the axis vector must be normalized.
The following two typedefs are provided for convenience:
AngleAxisf for float
AngleAxisd for double
Combined with MatrixBase::Unit{X,Y,Z}, AngleAxis can be used to easily mimic Euler-angles. Here is an example:
Output:
Note
This class is not aimed to be used to store a rotation transformation, but rather to make easier the creation of other rotation (Quaternion, rotation Matrix) and transformation objects.
See also
class Quaternion, class Transform, MatrixBase::UnitX()
Member Typedef Documentation
template<typename _Scalar> typedef RotationBase<AngleAxis<_Scalar>,3> Eigen::AngleAxis< _Scalar >::Base private
template<typename _Scalar> typedef Matrix<Scalar,3,3> Eigen::AngleAxis< _Scalar >::Matrix3
template<typename _Scalar> typedef Quaternion<Scalar> Eigen::AngleAxis< _Scalar >::QuaternionType
template<typename _Scalar> typedef _Scalar Eigen::AngleAxis< _Scalar >::Scalar
the scalar type of the coefficients
template<typename _Scalar> typedef Matrix<Scalar,3,1> Eigen::AngleAxis< _Scalar >::Vector3
Member Enumeration Documentation
template<typename _Scalar> anonymous enum
Enumerator
Dim
Constructor & Destructor Documentation
template<typename _Scalar> EIGEN_DEVICE_FUNC Eigen::AngleAxis< _Scalar >::AngleAxis () inline
Default constructor without initialization.
template<typename _Scalar> template<typename Derived > EIGEN_DEVICE_FUNC Eigen::AngleAxis< _Scalar >::AngleAxis (const Scalar & angle, const MatrixBase< Derived > & axis) inline
Constructs and initialize the angle-axis rotation from an angle in radian and an axis which must be normalized.
Warning
If the axis vector is not normalized, then the angle-axis object represents an invalid rotation.
template<typename _Scalar> template<typename QuatDerived > EIGEN_DEVICE_FUNC Eigen::AngleAxis< _Scalar >::AngleAxis (const QuaternionBase< QuatDerived > & q) inline explicit
Constructs and initialize the angle-axis rotation from a quaternion q. This function implicitly normalizes the quaternion q.
template<typename _Scalar> template<typename Derived > EIGEN_DEVICE_FUNC Eigen::AngleAxis< _Scalar >::AngleAxis (const MatrixBase< Derived > & m) inline explicit
Constructs and initialize the angle-axis rotation from a 3x3 rotation matrix.
References m.
template<typename _Scalar> template<typename OtherScalarType > EIGEN_DEVICE_FUNC Eigen::AngleAxis< _Scalar >::AngleAxis (const AngleAxis< OtherScalarType > & other) inline explicit
Copy constructor with scalar type conversion
References Eigen::AngleAxis< _Scalar >::angle(), and Eigen::AngleAxis< _Scalar >::axis().
Member Function Documentation
template<typename _Scalar> EIGEN_DEVICE_FUNC Scalar Eigen::AngleAxis< _Scalar >::angle () const inline
Returns
the value of the rotation angle in radian
Referenced by Eigen::AngleAxis< _Scalar >::AngleAxis(), and Eigen::QuaternionBase< Derived >::operator=().
template<typename _Scalar> EIGEN_DEVICE_FUNC Scalar& Eigen::AngleAxis< _Scalar >::angle () inline
Returns
a read-write reference to the stored angle in radian
template<typename _Scalar> EIGEN_DEVICE_FUNC const Vector3& Eigen::AngleAxis< _Scalar >::axis () const inline
Returns
the rotation axis
Referenced by Eigen::AngleAxis< _Scalar >::AngleAxis(), and Eigen::QuaternionBase< Derived >::operator=().
template<typename _Scalar> EIGEN_DEVICE_FUNC Vector3& Eigen::AngleAxis< _Scalar >::axis () inline
Returns
a read-write reference to the stored rotation axis.
Warning
The rotation axis must remain a unit vector.
template<typename _Scalar> template<typename NewScalarType > EIGEN_DEVICE_FUNC internal::cast_return_type<AngleAxis,AngleAxis<NewScalarType> >::type Eigen::AngleAxis< _Scalar >::cast () const inline
Returns
*this with scalar type casted to NewScalarType
Note that if NewScalarType is equal to the current scalar type of *this then this function smartly returns a const reference to *this.
References type.
template<typename _Scalar> template<typename Derived > EIGEN_DEVICE_FUNC AngleAxis& Eigen::AngleAxis< _Scalar >::fromRotationMatrix (const MatrixBase< Derived > & m)
template<typename _Scalar> template<typename Derived > EIGEN_DEVICE_FUNC AngleAxis<Scalar>& Eigen::AngleAxis< _Scalar >::fromRotationMatrix (const MatrixBase< Derived > & mat)
Sets *this from a 3x3 rotation matrix.
template<typename _Scalar> static EIGEN_DEVICE_FUNC const AngleAxis Eigen::AngleAxis< _Scalar >::Identity () inline static
template<typename _Scalar> EIGEN_DEVICE_FUNC AngleAxis Eigen::AngleAxis< _Scalar >::inverse () const inline
Returns
the inverse rotation, i.e., an angle-axis with opposite rotation angle
References m, and Eigen::internal::toRotationMatrix().
template<typename _Scalar> EIGEN_DEVICE_FUNC bool Eigen::AngleAxis< _Scalar >::isApprox (const AngleAxis< _Scalar > & other, const typename NumTraits< Scalar >::Real & prec = NumTraits<Scalar>::dummy_precision()) const inline
Returns
true if *this is approximately equal to other, within the precision determined by prec.
See also
MatrixBase::isApprox()
References Eigen::AngleAxis< _Scalar >::m_angle, and Eigen::AngleAxis< _Scalar >::m_axis.
template<typename _Scalar> EIGEN_DEVICE_FUNC QuaternionType Eigen::AngleAxis< _Scalar >::operator* (const AngleAxis< _Scalar > & other) const inline
Concatenates two rotations
template<typename _Scalar> EIGEN_DEVICE_FUNC QuaternionType Eigen::AngleAxis< _Scalar >::operator* (const QuaternionType & other) const inline
Concatenates two rotations
template<typename _Scalar> template<class QuatDerived > EIGEN_DEVICE_FUNC AngleAxis& Eigen::AngleAxis< _Scalar >::operator= (const QuaternionBase< QuatDerived > & q)
template<typename _Scalar> template<typename Derived > EIGEN_DEVICE_FUNC AngleAxis& Eigen::AngleAxis< _Scalar >::operator= (const MatrixBase< Derived > & m)
template<typename _Scalar> template<typename QuatDerived > EIGEN_DEVICE_FUNC AngleAxis<Scalar>& Eigen::AngleAxis< _Scalar >::operator= (const QuaternionBase< QuatDerived > & q)
Set *this from a unit quaternion.
The resulting axis is normalized, and the computed angle is in the [0,pi] range.
This function implicitly normalizes the quaternion q.
References abs(), Eigen::QuaternionBase< Derived >::vec(), and Eigen::QuaternionBase< Derived >::w().
template<typename _Scalar> template<typename Derived > EIGEN_DEVICE_FUNC AngleAxis<Scalar>& Eigen::AngleAxis< _Scalar >::operator= (const MatrixBase< Derived > & mat)
Set *this from a 3x3 rotation matrix mat.
template<typename Scalar > AngleAxis< Scalar >::Matrix3 EIGEN_DEVICE_FUNC Eigen::AngleAxis< Scalar >::toRotationMatrix (void) const
Constructs and
Returns
an equivalent 3x3 rotation matrix.
References Eigen::PlainObjectBase< Derived >::coeffRef(), cos(), and sin().
Friends And Related Function Documentation
template<typename _Scalar> EIGEN_DEVICE_FUNC QuaternionType operator* (const QuaternionType & a, const AngleAxis< _Scalar > & b) friend
Concatenates two rotations
Member Data Documentation
template<typename _Scalar> Scalar Eigen::AngleAxis< _Scalar >::m_angle protected
Referenced by Eigen::AngleAxis< _Scalar >::isApprox().
template<typename _Scalar> Vector3 Eigen::AngleAxis< _Scalar >::m_axis protected
Referenced by Eigen::AngleAxis< _Scalar >::isApprox().
The documentation for this class was generated from the following files:
ForwardDeclarations.h
AngleAxis.h