SmartMouse_2018: Flood Class Reference
Flood Class Reference
starts at 0,0 and explores the whole maze. kmaze is the known maze, and is used to "read the sensors". The mouse solves the maze after sensing each new square. solves assuming ALL walls, and assuming NO walls. when the solution for those two mazes are the same, then it knows the fastest route.
#include <Flood.h>
Public Member Functions
Flood (Mouse *mouse)
virtual void setup () override
virtual motion_primitive_t planNextStep () override
virtual route_t solve () override
virtual void teardown () override
virtual bool isFinished () override
virtual void setGoal (Solver::Goal goal) override
Public Member Functions inherited from Solver
Solver (Mouse *mouse)
bool isSolvable ()
Public Attributes
bool done
Public Attributes inherited from Solver
bool solvable
Mouse * mouse
Private Attributes
AbstractMaze no_wall_maze
this maze is initially no walls, and walls are filled out every time the mouse moves
AbstractMaze * all_wall_maze
this maze is initially all walls, and walls are removed every time the mouse moves
route_t no_wall_path
route_t all_wall_path
Solver::Goal goal
bool solved
Additional Inherited Members
Public Types inherited from Solver
enum Goal { Goal::CENTER, Goal::START }
Detailed Description
starts at 0,0 and explores the whole maze. kmaze is the known maze, and is used to "read the sensors". The mouse solves the maze after sensing each new square. solves assuming ALL walls, and assuming NO walls. when the solution for those two mazes are the same, then it knows the fastest route.
Constructor & Destructor Documentation
Flood::Flood (Mouse * mouse)
Member Function Documentation
bool Flood::isFinished () override virtual
Implements Solver.
References Solver::CENTER, Mouse::getCol(), Mouse::getRow(), goal, Solver::mouse, smartmouse::maze::SIZE, Solver::solvable, and Solver::START.
Referenced by solve().
motion_primitive_t Flood::planNextStep () override virtual
Implements Solver.
References all_wall_maze, all_wall_path, Solver::CENTER, smartmouse::maze::CENTER, Mouse::checkWalls(), AbstractMaze::fastest_route, AbstractMaze::fastest_theoretical_route, AbstractMaze::flood_fill_from_origin_to_center(), AbstractMaze::flood_fill_from_point(), Mouse::getCol(), Mouse::getDir(), Mouse::getRow(), goal, AbstractMaze::mark_position_visited(), Mouse::maze, Solver::mouse, no_wall_maze, no_wall_path, AbstractMaze::path_to_next_goal, Solver::solvable, Solver::START, AbstractMaze::truncate(), and AbstractMaze::update().
Referenced by solve().
void Flood::setGoal (Solver::Goal goal) override virtual
Implements Solver.
References goal.
void Flood::setup () override virtual
Implements Solver.
References all_wall_maze, Solver::CENTER, smartmouse::maze::CENTER, AbstractMaze::connect_all_neighbors_in_maze(), AbstractMaze::connect_neighbor(), E, goal, Mouse::maze, Solver::mouse, N, no_wall_maze, Mouse::reset(), AbstractMaze::reset(), S, and W.
Referenced by TEST().
route_t Flood::solve () override virtual
Implements Solver.
References all_wall_maze, AbstractMaze::fastest_route, Mouse::internalForward(), Mouse::internalTurnToFace(), isFinished(), Solver::mouse, and planNextStep().
Referenced by TEST().
void Flood::teardown () override virtual
Implements Solver.
References all_wall_maze, Solver::CENTER, AbstractMaze::fastest_route, goal, Mouse::maze, and Solver::mouse.
Referenced by TEST().
Member Data Documentation
AbstractMaze* Flood::all_wall_maze private
this maze is initially all walls, and walls are removed every time the mouse moves
Referenced by planNextStep(), setup(), solve(), and teardown().
route_t Flood::all_wall_path private
Referenced by planNextStep().
bool Flood::done
Solver::Goal Flood::goal private
Referenced by isFinished(), planNextStep(), setGoal(), setup(), and teardown().
AbstractMaze Flood::no_wall_maze private
this maze is initially no walls, and walls are filled out every time the mouse moves
Referenced by planNextStep(), and setup().
route_t Flood::no_wall_path private
Referenced by planNextStep().
bool Flood::solved private
The documentation for this class was generated from the following files:
Flood.h
Flood.cpp