SmartMouse_2018: Node Class Reference
Node Class Reference
holds its location & neighbors, as well as a bool for indicating if it has been discovered you don't need to free nodes in a maze, just use free_maze however, be sure to free nodes allocated not in mazes I finally gave in an added row and col attributes the node....be very careful you dont get fuck with those. Don't ever move a node around in maze because you risk getting the actual row/col off from the nodes row/col visited is meant for ACTUALLY visiting, known is just used for searching/solving
#include <Node.h>
Public Member Functions
Node (unsigned int row, unsigned int col)
intializes a node
Node ()
unsigned int row ()
unsigned int col ()
Node * neighbor (const Direction dir)
get the neighbor in the given direction
bool wall (const Direction dir)
void assign_weights_to_neighbors (Node *goal, int weight, bool *success)
Public Attributes
int weight
int distance
bool known
bool visited
std::array< Node *, 4 > neighbors
Static Public Attributes
static const int OUT_OF_BOUNDS = -2
Private Attributes
unsigned int r
unsigned int c
Detailed Description
holds its location & neighbors, as well as a bool for indicating if it has been discovered you don't need to free nodes in a maze, just use free_maze however, be sure to free nodes allocated not in mazes I finally gave in an added row and col attributes the node....be very careful you dont get fuck with those. Don't ever move a node around in maze because you risk getting the actual row/col off from the nodes row/col visited is meant for ACTUALLY visiting, known is just used for searching/solving
Constructor & Destructor Documentation
Node::Node (unsigned int row, unsigned int col)
intializes a node
References c, col(), r, and row().
Node::Node ()
Member Function Documentation
void Node::assign_weights_to_neighbors (Node * goal, int weight, bool * success)
References i, known, neighbors, and weight.
Referenced by AbstractMaze::flood_fill(), and TEST().
unsigned int Node::col ()
References c.
Referenced by AbstractMaze::_make_connections(), and Node().
Node * Node::neighbor (const Direction dir)
get the neighbor in the given direction
References E, N, neighbors, S, and W.
Referenced by smartmouse::msgs::Convert(), AbstractMaze::flood_fill(), Mouse::isWallInDirection(), Mouse::maze_mouse_string(), AbstractMaze::operator==(), AbstractMaze::print_maze_str(), AbstractMaze::print_neighbor_maze(), TEST(), AbstractMaze::truncate(), and wall().
unsigned int Node::row ()
References r.
Referenced by AbstractMaze::_make_connections(), and Node().
bool Node::wall (const Direction dir)
References neighbor().
Referenced by AbstractMaze::gen_random_legal_maze(), and AbstractMaze::truncate().
Member Data Documentation
unsigned int Node::c private
Referenced by col(), and Node().
int Node::distance
Referenced by AbstractMaze::print_dist_maze().
bool Node::known
Referenced by assign_weights_to_neighbors(), AbstractMaze::mark_origin_known(), and AbstractMaze::reset().
std::array<Node *, 4> Node::neighbors
Referenced by assign_weights_to_neighbors(), ConsoleMouse::checkWalls(), AbstractMaze::connect_neighbor(), AbstractMaze::disconnect_neighbor(), and neighbor().
const int Node::OUT_OF_BOUNDS = -2 static
Referenced by AbstractMaze::_make_connections(), AbstractMaze::connect_neighbor(), AbstractMaze::disconnect_neighbor(), AbstractMaze::get_node(), and TEST().
unsigned int Node::r private
Referenced by Node(), and row().
bool Node::visited
Referenced by AbstractMaze::_make_connections(), Mouse::mark_mouse_position_visited(), and AbstractMaze::mark_position_visited().
int Node::weight
Referenced by assign_weights_to_neighbors(), AbstractMaze::flood_fill(), AbstractMaze::print_weight_maze(), AbstractMaze::reset(), and TEST().
The documentation for this class was generated from the following files:
Node.h
Node.cpp