SmartMouse_2018: ArduinoTimer Class Reference
ArduinoTimer Class Reference
#include <ArduinoTimer.h>
Public Member Functions
virtual unsigned long programTimeMs () override
the time since the start of the program in milliseconds
Member Function Documentation
unsigned long ArduinoTimer::programTimeMs () override virtual
the time since the start of the program in milliseconds
Implements TimerInterface.
Referenced by loop(), main(), and setup().
The documentation for this class was generated from the following files:
ArduinoTimer.h
ArduinoTimer.cpp