SmartMouse_2018: Eigen::ComplexSchur< _MatrixType > Class Template Reference
Eigen::ComplexSchur< _MatrixType > Class Template Reference
Performs a complex Schur decomposition of a real or complex square matrix.
#include <ComplexSchur.h>
Public Types
enum {
RowsAtCompileTime = MatrixType::RowsAtCompileTime, ColsAtCompileTime = MatrixType::ColsAtCompileTime, Options = MatrixType::Options, MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime,
MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime
}
typedef _MatrixType MatrixType
typedef MatrixType::Scalar Scalar
Scalar type for matrices of type _MatrixType.
typedef NumTraits< Scalar >::Real RealScalar
typedef Eigen::Index Index
typedef std::complex< RealScalar > ComplexScalar
Complex scalar type for _MatrixType.
typedef Matrix< ComplexScalar, RowsAtCompileTime, ColsAtCompileTime, Options, MaxRowsAtCompileTime, MaxColsAtCompileTime > ComplexMatrixType
Type for the matrices in the Schur decomposition.
Public Member Functions
ComplexSchur (Index size=RowsAtCompileTime==Dynamic?1:RowsAtCompileTime)
Default constructor.
template<typename InputType >
ComplexSchur (const EigenBase< InputType > &matrix, bool computeU=true)
Constructor; computes Schur decomposition of given matrix.
const ComplexMatrixType & matrixU () const
Returns the unitary matrix in the Schur decomposition.
const ComplexMatrixType & matrixT () const
Returns the triangular matrix in the Schur decomposition.
template<typename InputType >
ComplexSchur & compute (const EigenBase< InputType > &matrix, bool computeU=true)
Computes Schur decomposition of given matrix.
template<typename HessMatrixType , typename OrthMatrixType >
ComplexSchur & computeFromHessenberg (const HessMatrixType &matrixH, const OrthMatrixType &matrixQ, bool computeU=true)
Compute Schur decomposition from a given Hessenberg matrix.
ComputationInfo info () const
Reports whether previous computation was successful.
ComplexSchur & setMaxIterations (Index maxIters)
Sets the maximum number of iterations allowed.
Index getMaxIterations ()
Returns the maximum number of iterations.
template<typename InputType >
ComplexSchur< MatrixType > & compute (const EigenBase< InputType > &matrix, bool computeU)
template<typename HessMatrixType , typename OrthMatrixType >
ComplexSchur< MatrixType > & computeFromHessenberg (const HessMatrixType &matrixH, const OrthMatrixType &matrixQ, bool computeU)
Static Public Attributes
static const int m_maxIterationsPerRow = 30
Maximum number of iterations per row.
Protected Attributes
ComplexMatrixType m_matT
ComplexMatrixType m_matU
HessenbergDecomposition< MatrixType > m_hess
ComputationInfo m_info
bool m_isInitialized
bool m_matUisUptodate
Index m_maxIters
Private Member Functions
bool subdiagonalEntryIsNeglegible (Index i)
ComplexScalar computeShift (Index iu, Index iter)
void reduceToTriangularForm (bool computeU)
Friends
struct internal::complex_schur_reduce_to_hessenberg< MatrixType, NumTraits< Scalar >::IsComplex >
Detailed Description
template<typename _MatrixType>
class Eigen::ComplexSchur< _MatrixType >
Performs a complex Schur decomposition of a real or complex square matrix.
Template Parameters
_MatrixType the type of the matrix of which we are computing the Schur decomposition; this is expected to be an instantiation of the Matrix class template.
Given a real or complex square matrix A, this class computes the Schur decomposition: where U is a unitary complex matrix, and T is a complex upper triangular matrix. The diagonal of the matrix T corresponds to the eigenvalues of the matrix A.
Call the function compute() to compute the Schur decomposition of a given matrix. Alternatively, you can use the ComplexSchur(const MatrixType&, bool) constructor which computes the Schur decomposition at construction time. Once the decomposition is computed, you can use the matrixU() and matrixT() functions to retrieve the matrices U and V in the decomposition.
Note
This code is inspired from Jampack
See also
class RealSchur, class EigenSolver, class ComplexEigenSolver
Member Typedef Documentation
template<typename _MatrixType> typedef Matrix<ComplexScalar, RowsAtCompileTime, ColsAtCompileTime, Options, MaxRowsAtCompileTime, MaxColsAtCompileTime> Eigen::ComplexSchur< _MatrixType >::ComplexMatrixType
Type for the matrices in the Schur decomposition.
This is a square matrix with entries of type ComplexScalar. The size is the same as the size of _MatrixType.
template<typename _MatrixType> typedef std::complex<RealScalar> Eigen::ComplexSchur< _MatrixType >::ComplexScalar
Complex scalar type for _MatrixType.
This is std::complex<Scalar> if Scalar is real (e.g., float or double) and just Scalar if Scalar is complex.
template<typename _MatrixType> typedef Eigen::Index Eigen::ComplexSchur< _MatrixType >::Index
Deprecated:
since Eigen 3.3
template<typename _MatrixType> typedef _MatrixType Eigen::ComplexSchur< _MatrixType >::MatrixType
template<typename _MatrixType> typedef NumTraits<Scalar>::Real Eigen::ComplexSchur< _MatrixType >::RealScalar
template<typename _MatrixType> typedef MatrixType::Scalar Eigen::ComplexSchur< _MatrixType >::Scalar
Scalar type for matrices of type _MatrixType.
Member Enumeration Documentation
template<typename _MatrixType> anonymous enum
Enumerator
RowsAtCompileTime
ColsAtCompileTime
Options
MaxRowsAtCompileTime
MaxColsAtCompileTime
Constructor & Destructor Documentation
template<typename _MatrixType> Eigen::ComplexSchur< _MatrixType >::ComplexSchur (Index size = RowsAtCompileTime==Dynamic ? 1 : RowsAtCompileTime) inline explicit
Default constructor.
Parameters
[in] size Positive integer, size of the matrix whose Schur decomposition will be computed.
The default constructor is useful in cases in which the user intends to perform decompositions via compute(). The size parameter is only used as a hint. It is not an error to give a wrong size, but it may impair performance.
See also
compute() for an example.
template<typename _MatrixType> template<typename InputType > Eigen::ComplexSchur< _MatrixType >::ComplexSchur (const EigenBase< InputType > & matrix, bool computeU = true) inline explicit
Constructor; computes Schur decomposition of given matrix.
Parameters
[in] matrix Square matrix whose Schur decomposition is to be computed.
[in] computeU If true, both T and U are computed; if false, only T is computed.
This constructor calls compute() to compute the Schur decomposition.
See also
matrixT() and matrixU() for examples.
Member Function Documentation
template<typename _MatrixType> template<typename InputType > ComplexSchur& Eigen::ComplexSchur< _MatrixType >::compute (const EigenBase< InputType > & matrix, bool computeU = true)
Computes Schur decomposition of given matrix.
Parameters
[in] matrix Square matrix whose Schur decomposition is to be computed.
[in] computeU If true, both T and U are computed; if false, only T is computed.
Returns
Reference to *this
The Schur decomposition is computed by first reducing the matrix to Hessenberg form using the class HessenbergDecomposition. The Hessenberg matrix is then reduced to triangular form by performing QR iterations with a single shift. The cost of computing the Schur decomposition depends on the number of iterations; as a rough guide, it may be taken on the number of iterations; as a rough guide, it may be taken to be complex flops, or complex flops if computeU is false.
Example:
Output:
See also
compute(const MatrixType&, bool, Index)
Referenced by Eigen::ComplexEigenSolver< _MatrixType >::compute().
template<typename _MatrixType> template<typename InputType > ComplexSchur<MatrixType>& Eigen::ComplexSchur< _MatrixType >::compute (const EigenBase< InputType > & matrix, bool computeU)
References Eigen::EigenBase< Derived >::cols(), Eigen::EigenBase< Derived >::derived(), eigen_assert, Eigen::EigenBase< Derived >::rows(), and Eigen::Success.
template<typename _MatrixType> template<typename HessMatrixType , typename OrthMatrixType > ComplexSchur& Eigen::ComplexSchur< _MatrixType >::computeFromHessenberg (const HessMatrixType & matrixH, const OrthMatrixType & matrixQ, bool computeU = true)
Compute Schur decomposition from a given Hessenberg matrix.
Parameters
[in] matrixH Matrix in Hessenberg form H
[in] matrixQ orthogonal matrix Q that transform a matrix A to H : A = Q H Q^T
computeU Computes the matriX U of the Schur vectors
Returns
Reference to *this
This routine assumes that the matrix is already reduced in Hessenberg form matrixH using either the class HessenbergDecomposition or another mean. It computes the upper quasi-triangular matrix T of the Schur decomposition of H When computeU is true, this routine computes the matrix U such that A = U T U^T = (QZ) T (QZ)^T = Q H Q^T where A is the initial matrix
NOTE Q is referenced if computeU is true; so, if the initial orthogonal matrix is not available, the user should give an identity matrix (Q.setIdentity())
See also
compute(const MatrixType&, bool)
template<typename _MatrixType> template<typename HessMatrixType , typename OrthMatrixType > ComplexSchur<MatrixType>& Eigen::ComplexSchur< _MatrixType >::computeFromHessenberg (const HessMatrixType & matrixH, const OrthMatrixType & matrixQ, bool computeU)
template<typename MatrixType > ComplexSchur< MatrixType >::ComplexScalar Eigen::ComplexSchur< MatrixType >::computeShift (Index iu, Index iter) private
Compute the shift in the current QR iteration.
References abs(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::coeff(), Eigen::PlainObjectBase< Derived >::coeff(), real(), and sqrt().
template<typename _MatrixType> Index Eigen::ComplexSchur< _MatrixType >::getMaxIterations () inline
Returns the maximum number of iterations.
Referenced by Eigen::ComplexEigenSolver< _MatrixType >::getMaxIterations().
template<typename _MatrixType> ComputationInfo Eigen::ComplexSchur< _MatrixType >::info () const inline
Reports whether previous computation was successful.
Returns
Success if computation was succesful, NoConvergence otherwise.
Referenced by Eigen::ComplexEigenSolver< _MatrixType >::compute(), and Eigen::ComplexEigenSolver< _MatrixType >::info().
template<typename _MatrixType> const ComplexMatrixType& Eigen::ComplexSchur< _MatrixType >::matrixT () const inline
Returns the triangular matrix in the Schur decomposition.
Returns
A const reference to the matrix T.
It is assumed that either the constructor ComplexSchur(const MatrixType& matrix, bool computeU) or the member function compute(const MatrixType& matrix, bool computeU) has been called before to compute the Schur decomposition of a matrix.
Note that this function returns a plain square matrix. If you want to reference only the upper triangular part, use:
schur.matrixT().triangularView<Upper>()
Example:
Output:
Referenced by Eigen::ComplexEigenSolver< _MatrixType >::compute(), and Eigen::ComplexEigenSolver< _MatrixType >::doComputeEigenvectors().
template<typename _MatrixType> const ComplexMatrixType& Eigen::ComplexSchur< _MatrixType >::matrixU () const inline
Returns the unitary matrix in the Schur decomposition.
Returns
A const reference to the matrix U.
It is assumed that either the constructor ComplexSchur(const MatrixType& matrix, bool computeU) or the member function compute(const MatrixType& matrix, bool computeU) has been called before to compute the Schur decomposition of a matrix, and that computeU was set to true (the default value).
Example:
Output:
Referenced by Eigen::ComplexEigenSolver< _MatrixType >::doComputeEigenvectors().
template<typename MatrixType > void Eigen::ComplexSchur< MatrixType >::reduceToTriangularForm (bool computeU) private
References Eigen::JacobiRotation< Scalar >::adjoint(), Eigen::PlainObjectBase< Derived >::coeff(), Eigen::PlainObjectBase< Derived >::coeffRef(), Eigen::PlainObjectBase< Derived >::cols(), i, Eigen::JacobiRotation< Scalar >::makeGivens(), Eigen::half_impl::min(), Eigen::NoConvergence, Eigen::PlainObjectBase< Derived >::rows(), and Eigen::Success.
template<typename _MatrixType> ComplexSchur& Eigen::ComplexSchur< _MatrixType >::setMaxIterations (Index maxIters) inline
Sets the maximum number of iterations allowed.
If not specified by the user, the maximum number of iterations is m_maxIterationsPerRow times the size of the matrix.
Referenced by Eigen::ComplexEigenSolver< _MatrixType >::setMaxIterations().
template<typename MatrixType > bool Eigen::ComplexSchur< MatrixType >::subdiagonalEntryIsNeglegible (Index i) inline private
If m_matT(i+1,i) is neglegible in floating point arithmetic compared to m_matT(i,i) and m_matT(j,j), then set it to zero and return true, else return false.
References Eigen::PlainObjectBase< Derived >::coeff(), Eigen::PlainObjectBase< Derived >::coeffRef(), and i.
Friends And Related Function Documentation
template<typename _MatrixType> friend struct internal::complex_schur_reduce_to_hessenberg< MatrixType, NumTraits< Scalar >::IsComplex > friend
Member Data Documentation
template<typename _MatrixType> HessenbergDecomposition<MatrixType> Eigen::ComplexSchur< _MatrixType >::m_hess protected
Referenced by Eigen::internal::complex_schur_reduce_to_hessenberg< MatrixType, IsComplex >::run(), and Eigen::internal::complex_schur_reduce_to_hessenberg< MatrixType, false >::run().
template<typename _MatrixType> ComputationInfo Eigen::ComplexSchur< _MatrixType >::m_info protected
template<typename _MatrixType> bool Eigen::ComplexSchur< _MatrixType >::m_isInitialized protected
template<typename _MatrixType> ComplexMatrixType Eigen::ComplexSchur< _MatrixType >::m_matT protected
Referenced by Eigen::internal::complex_schur_reduce_to_hessenberg< MatrixType, IsComplex >::run(), and Eigen::internal::complex_schur_reduce_to_hessenberg< MatrixType, false >::run().
template<typename _MatrixType> ComplexMatrixType Eigen::ComplexSchur< _MatrixType >::m_matU protected
Referenced by Eigen::internal::complex_schur_reduce_to_hessenberg< MatrixType, IsComplex >::run(), and Eigen::internal::complex_schur_reduce_to_hessenberg< MatrixType, false >::run().
template<typename _MatrixType> bool Eigen::ComplexSchur< _MatrixType >::m_matUisUptodate protected
template<typename _MatrixType> const int Eigen::ComplexSchur< _MatrixType >::m_maxIterationsPerRow = 30 static
Maximum number of iterations per row.
If not otherwise specified, the maximum number of iterations is this number times the size of the matrix. It is currently set to 30.
template<typename _MatrixType> Index Eigen::ComplexSchur< _MatrixType >::m_maxIters protected
The documentation for this class was generated from the following file:
ComplexSchur.h