SmartMouse_2018: ArgumentParser::Any::PlaceHolder Class Reference
ArgumentParser::Any::PlaceHolder Class Reference abstract
Public Member Functions
virtual ~PlaceHolder ()
virtual const std::type_info & type_info () const =0
virtual PlaceHolder * clone () const =0
Constructor & Destructor Documentation
virtual ArgumentParser::Any::PlaceHolder::~PlaceHolder () inline virtual
References clone(), and type_info().
Member Function Documentation
virtual PlaceHolder* ArgumentParser::Any::PlaceHolder::clone () const pure virtual
Implemented in ArgumentParser::Any::Holder< ValueType >.
Referenced by ~PlaceHolder().
virtual const std::type_info& ArgumentParser::Any::PlaceHolder::type_info () const pure virtual
Implemented in ArgumentParser::Any::Holder< ValueType >.
Referenced by ArgumentParser::Any::toPtr(), and ~PlaceHolder().
The documentation for this class was generated from the following file:
argparse.hpp