SmartMouse_2018: Eigen::ArrayBase< Derived > Class Template Reference
Eigen::ArrayBase< Derived > Class Template Reference
Base class for all 1D and 2D array, and related expressions.
#include <ArrayBase.h>
Public Types
typedef ArrayBase StorageBaseType
typedef ArrayBase Eigen_BaseClassForSpecializationOfGlobalMathFuncImpl
typedef internal::traits< Derived >::StorageKind StorageKind
typedef internal::traits< Derived >::Scalar Scalar
typedef internal::packet_traits< Scalar >::type PacketScalar
typedef NumTraits< Scalar >::Real RealScalar
typedef DenseBase< Derived > Base
typedef Base::CoeffReturnType CoeffReturnType
typedef Base::PlainObject PlainObject
typedef CwiseNullaryOp< internal::scalar_constant_op< Scalar >, PlainObject > ConstantReturnType
typedef CwiseUnaryOp< internal::scalar_abs_op< Scalar >, const Derived > CwiseAbsReturnType
typedef CwiseUnaryOp< internal::scalar_abs2_op< Scalar >, const Derived > CwiseAbs2ReturnType
typedef CwiseUnaryOp< internal::scalar_sqrt_op< Scalar >, const Derived > CwiseSqrtReturnType
typedef CwiseUnaryOp< internal::scalar_sign_op< Scalar >, const Derived > CwiseSignReturnType
typedef CwiseUnaryOp< internal::scalar_inverse_op< Scalar >, const Derived > CwiseInverseReturnType
typedef CwiseUnaryOp< internal::scalar_abs_op< Scalar >, const Derived > AbsReturnType
typedef CwiseUnaryOp< internal::scalar_arg_op< Scalar >, const Derived > ArgReturnType
typedef CwiseUnaryOp< internal::scalar_abs2_op< Scalar >, const Derived > Abs2ReturnType
typedef CwiseUnaryOp< internal::scalar_sqrt_op< Scalar >, const Derived > SqrtReturnType
typedef CwiseUnaryOp< internal::scalar_rsqrt_op< Scalar >, const Derived > RsqrtReturnType
typedef CwiseUnaryOp< internal::scalar_sign_op< Scalar >, const Derived > SignReturnType
typedef CwiseUnaryOp< internal::scalar_inverse_op< Scalar >, const Derived > InverseReturnType
typedef CwiseUnaryOp< internal::scalar_boolean_not_op< Scalar >, const Derived > BooleanNotReturnType
typedef CwiseUnaryOp< internal::scalar_exp_op< Scalar >, const Derived > ExpReturnType
typedef CwiseUnaryOp< internal::scalar_expm1_op< Scalar >, const Derived > Expm1ReturnType
typedef CwiseUnaryOp< internal::scalar_log_op< Scalar >, const Derived > LogReturnType
typedef CwiseUnaryOp< internal::scalar_log1p_op< Scalar >, const Derived > Log1pReturnType
typedef CwiseUnaryOp< internal::scalar_log10_op< Scalar >, const Derived > Log10ReturnType
typedef CwiseUnaryOp< internal::scalar_cos_op< Scalar >, const Derived > CosReturnType
typedef CwiseUnaryOp< internal::scalar_sin_op< Scalar >, const Derived > SinReturnType
typedef CwiseUnaryOp< internal::scalar_tan_op< Scalar >, const Derived > TanReturnType
typedef CwiseUnaryOp< internal::scalar_acos_op< Scalar >, const Derived > AcosReturnType
typedef CwiseUnaryOp< internal::scalar_asin_op< Scalar >, const Derived > AsinReturnType
typedef CwiseUnaryOp< internal::scalar_atan_op< Scalar >, const Derived > AtanReturnType
typedef CwiseUnaryOp< internal::scalar_tanh_op< Scalar >, const Derived > TanhReturnType
typedef CwiseUnaryOp< internal::scalar_sinh_op< Scalar >, const Derived > SinhReturnType
typedef CwiseUnaryOp< internal::scalar_cosh_op< Scalar >, const Derived > CoshReturnType
typedef CwiseUnaryOp< internal::scalar_square_op< Scalar >, const Derived > SquareReturnType
typedef CwiseUnaryOp< internal::scalar_cube_op< Scalar >, const Derived > CubeReturnType
typedef CwiseUnaryOp< internal::scalar_round_op< Scalar >, const Derived > RoundReturnType
typedef CwiseUnaryOp< internal::scalar_floor_op< Scalar >, const Derived > FloorReturnType
typedef CwiseUnaryOp< internal::scalar_ceil_op< Scalar >, const Derived > CeilReturnType
typedef CwiseUnaryOp< internal::scalar_isnan_op< Scalar >, const Derived > IsNaNReturnType
typedef CwiseUnaryOp< internal::scalar_isinf_op< Scalar >, const Derived > IsInfReturnType
typedef CwiseUnaryOp< internal::scalar_isfinite_op< Scalar >, const Derived > IsFiniteReturnType
typedef CwiseUnaryOp< internal::scalar_lgamma_op< Scalar >, const Derived > LgammaReturnType
typedef CwiseUnaryOp< internal::scalar_digamma_op< Scalar >, const Derived > DigammaReturnType
typedef CwiseUnaryOp< internal::scalar_erf_op< Scalar >, const Derived > ErfReturnType
typedef CwiseUnaryOp< internal::scalar_erfc_op< Scalar >, const Derived > ErfcReturnType
typedef CwiseBinaryOp< internal::scalar_cmp_op< Scalar, Scalar, internal::cmp_EQ >, const Derived, const ConstantReturnType > CwiseScalarEqualReturnType
Public Types inherited from Eigen::DenseBase< Derived >
enum {
RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime, ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime, SizeAtCompileTime, MaxRowsAtCompileTime = internal::traits<Derived>::MaxRowsAtCompileTime,
MaxColsAtCompileTime = internal::traits<Derived>::MaxColsAtCompileTime, MaxSizeAtCompileTime, IsVectorAtCompileTime, Flags = internal::traits<Derived>::Flags,
IsRowMajor = int(Flags) & RowMajorBit, InnerSizeAtCompileTime, InnerStrideAtCompileTime = internal::inner_stride_at_compile_time<Derived>::ret, OuterStrideAtCompileTime = internal::outer_stride_at_compile_time<Derived>::ret
}
enum { IsPlainObjectBase = 0 }
typedef Eigen::InnerIterator< Derived > InnerIterator
typedef internal::traits< Derived >::StorageKind StorageKind
typedef internal::traits< Derived >::StorageIndex StorageIndex
The type used to store indices.
typedef internal::traits< Derived >::Scalar Scalar
typedef Scalar value_type
typedef NumTraits< Scalar >::Real RealScalar
typedef DenseCoeffsBase< Derived > Base
typedef Base::CoeffReturnType CoeffReturnType
typedef internal::find_best_packet< Scalar, SizeAtCompileTime >::type PacketScalar
typedef Matrix< typename internal::traits< Derived >::Scalar, internal::traits< Derived >::RowsAtCompileTime, internal::traits< Derived >::ColsAtCompileTime, AutoAlign|(internal::traits< Derived >::Flags &RowMajorBit?RowMajor:ColMajor), internal::traits< Derived >::MaxRowsAtCompileTime, internal::traits< Derived >::MaxColsAtCompileTime > PlainMatrix
typedef Array< typename internal::traits< Derived >::Scalar, internal::traits< Derived >::RowsAtCompileTime, internal::traits< Derived >::ColsAtCompileTime, AutoAlign|(internal::traits< Derived >::Flags &RowMajorBit?RowMajor:ColMajor), internal::traits< Derived >::MaxRowsAtCompileTime, internal::traits< Derived >::MaxColsAtCompileTime > PlainArray
typedef internal::conditional< internal::is_same< typename internal::traits< Derived >::XprKind, MatrixXpr >::value, PlainMatrix, PlainArray >::type PlainObject
The plain matrix or array type corresponding to this expression.
typedef CwiseNullaryOp< internal::scalar_constant_op< Scalar >, PlainObject > ConstantReturnType
typedef CwiseNullaryOp< internal::linspaced_op< Scalar, PacketScalar >, PlainObject > SequentialLinSpacedReturnType
typedef CwiseNullaryOp< internal::linspaced_op< Scalar, PacketScalar >, PlainObject > RandomAccessLinSpacedReturnType
typedef Matrix< typename NumTraits< typename internal::traits< Derived >::Scalar >::Real, internal::traits< Derived >::ColsAtCompileTime, 1 > EigenvaluesReturnType
typedef Transpose< Derived > TransposeReturnType
typedef internal::add_const< Transpose< const Derived > >::type ConstTransposeReturnType
typedef internal::add_const_on_value_type< typename internal::eval< Derived >::type >::type EvalReturnType
typedef VectorwiseOp< Derived, Horizontal > RowwiseReturnType
typedef const VectorwiseOp< const Derived, Horizontal > ConstRowwiseReturnType
typedef VectorwiseOp< Derived, Vertical > ColwiseReturnType
typedef const VectorwiseOp< const Derived, Vertical > ConstColwiseReturnType
typedef CwiseNullaryOp< internal::scalar_random_op< Scalar >, PlainObject > RandomReturnType
typedef Reverse< Derived, BothDirections > ReverseReturnType
typedef const Reverse< const Derived, BothDirections > ConstReverseReturnType
typedef internal::conditional< NumTraits< Scalar >::IsComplex, const CwiseUnaryOp< internal::scalar_conjugate_op< Scalar >, const Derived >, const Derived & >::type ConjugateReturnType
typedef internal::conditional< NumTraits< Scalar >::IsComplex, const CwiseUnaryOp< internal::scalar_real_op< Scalar >, const Derived >, const Derived & >::type RealReturnType
typedef internal::conditional< NumTraits< Scalar >::IsComplex, CwiseUnaryView< internal::scalar_real_ref_op< Scalar >, Derived >, Derived & >::type NonConstRealReturnType
typedef CwiseUnaryOp< internal::scalar_imag_op< Scalar >, const Derived > ImagReturnType
typedef CwiseUnaryView< internal::scalar_imag_ref_op< Scalar >, Derived > NonConstImagReturnType
typedef CwiseUnaryOp< internal::scalar_opposite_op< Scalar >, const Derived > NegativeReturnType
typedef Block< Derived, internal::traits< Derived >::RowsAtCompileTime, 1,!IsRowMajor > ColXpr
typedef const Block< const Derived, internal::traits< Derived >::RowsAtCompileTime, 1,!IsRowMajor > ConstColXpr
typedef Block< Derived, 1, internal::traits< Derived >::ColsAtCompileTime, IsRowMajor > RowXpr
typedef const Block< const Derived, 1, internal::traits< Derived >::ColsAtCompileTime, IsRowMajor > ConstRowXpr
typedef Block< Derived, internal::traits< Derived >::RowsAtCompileTime, Dynamic,!IsRowMajor > ColsBlockXpr
typedef const Block< const Derived, internal::traits< Derived >::RowsAtCompileTime, Dynamic,!IsRowMajor > ConstColsBlockXpr
typedef Block< Derived, Dynamic, internal::traits< Derived >::ColsAtCompileTime, IsRowMajor > RowsBlockXpr
typedef const Block< const Derived, Dynamic, internal::traits< Derived >::ColsAtCompileTime, IsRowMajor > ConstRowsBlockXpr
typedef Block< Derived > BlockXpr
typedef const Block< const Derived > ConstBlockXpr
typedef VectorBlock< Derived > SegmentReturnType
typedef const VectorBlock< const Derived > ConstSegmentReturnType
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseAbsReturnType cwiseAbs () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseAbs2ReturnType cwiseAbs2 () const
EIGEN_DEVICE_FUNC const CwiseSqrtReturnType cwiseSqrt () const
EIGEN_DEVICE_FUNC const CwiseSignReturnType cwiseSign () const
EIGEN_DEVICE_FUNC const CwiseInverseReturnType cwiseInverse () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const AbsReturnType abs () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const ArgReturnType arg () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Abs2ReturnType abs2 () const
EIGEN_DEVICE_FUNC const ExpReturnType exp () const
EIGEN_DEVICE_FUNC const Expm1ReturnType expm1 () const
EIGEN_DEVICE_FUNC const LogReturnType log () const
EIGEN_DEVICE_FUNC const Log1pReturnType log1p () const
EIGEN_DEVICE_FUNC const Log10ReturnType log10 () const
EIGEN_DEVICE_FUNC const SqrtReturnType sqrt () const
EIGEN_DEVICE_FUNC const RsqrtReturnType rsqrt () const
EIGEN_DEVICE_FUNC const SignReturnType sign () const
EIGEN_DEVICE_FUNC const CosReturnType cos () const
EIGEN_DEVICE_FUNC const SinReturnType sin () const
EIGEN_DEVICE_FUNC const TanReturnType tan () const
EIGEN_DEVICE_FUNC const AtanReturnType atan () const
EIGEN_DEVICE_FUNC const AcosReturnType acos () const
EIGEN_DEVICE_FUNC const AsinReturnType asin () const
EIGEN_DEVICE_FUNC const TanhReturnType tanh () const
EIGEN_DEVICE_FUNC const SinhReturnType sinh () const
EIGEN_DEVICE_FUNC const CoshReturnType cosh () const
EIGEN_DEVICE_FUNC const InverseReturnType inverse () const
EIGEN_DEVICE_FUNC const SquareReturnType square () const
EIGEN_DEVICE_FUNC const CubeReturnType cube () const
EIGEN_DEVICE_FUNC const RoundReturnType round () const
EIGEN_DEVICE_FUNC const FloorReturnType floor () const
EIGEN_DEVICE_FUNC const CeilReturnType ceil () const
EIGEN_DEVICE_FUNC const IsNaNReturnType isNaN () const
EIGEN_DEVICE_FUNC const IsInfReturnType isInf () const
EIGEN_DEVICE_FUNC const IsFiniteReturnType isFinite () const
EIGEN_DEVICE_FUNC const BooleanNotReturnType operator! () const
EIGEN_DEVICE_FUNC const LgammaReturnType lgamma () const
EIGEN_DEVICE_FUNC const DigammaReturnType digamma () const
EIGEN_DEVICE_FUNC const ErfReturnType erf () const
EIGEN_DEVICE_FUNC const ErfcReturnType erfc () const
template<typename CustomBinaryOp , typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp< CustomBinaryOp, const Derived, const OtherDerived > binaryExpr (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other, const CustomBinaryOp &func=CustomBinaryOp()) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC const CwiseBinaryOp< internal::scalar_boolean_and_op, const Derived, const OtherDerived > operator&& (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC const CwiseBinaryOp< internal::scalar_boolean_or_op, const Derived, const OtherDerived > operator|| (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const EIGEN_CWISE_BINARY_RETURN_TYPE (Derived, OtherDerived, product) cwiseProduct(const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC const CwiseBinaryOp< std::equal_to< Scalar >, const Derived, const OtherDerived > cwiseEqual (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC const CwiseBinaryOp< std::not_equal_to< Scalar >, const Derived, const OtherDerived > cwiseNotEqual (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp< internal::scalar_min_op< Scalar, Scalar >, const Derived, const OtherDerived > cwiseMin (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp< internal::scalar_min_op< Scalar, Scalar >, const Derived, const ConstantReturnType > cwiseMin (const Scalar &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp< internal::scalar_max_op< Scalar, Scalar >, const Derived, const OtherDerived > cwiseMax (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp< internal::scalar_max_op< Scalar, Scalar >, const Derived, const ConstantReturnType > cwiseMax (const Scalar &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp< internal::scalar_quotient_op< Scalar >, const Derived, const OtherDerived > cwiseQuotient (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
EIGEN_DEVICE_FUNC const CwiseScalarEqualReturnType cwiseEqual (const Scalar &s) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const EIGEN_CWISE_BINARY_RETURN_TYPE (Derived, OtherDerived, product) operator*(const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp< internal::scalar_quotient_op< Scalar, typename OtherDerived::Scalar >, const Derived, const OtherDerived > operator/ (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp (min)(const Scalar &other) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp (max)(const Scalar &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC const CwiseBinaryOp< internal::scalar_boolean_xor_op, const Derived, const OtherDerived > operator^ (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
template<typename DerivedQ >
const CwiseBinaryOp< internal::scalar_zeta_op< Scalar >, const Derived, const DerivedQ > zeta (const EIGEN_CURRENT_STORAGE_BASE_CLASS< DerivedQ > &q) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator= (const ArrayBase &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator= (const Scalar &value)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator+= (const Scalar &scalar)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator-= (const Scalar &scalar)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator+= (const ArrayBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator-= (const ArrayBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator*= (const ArrayBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator/= (const ArrayBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC ArrayBase< Derived > & array ()
EIGEN_DEVICE_FUNC const ArrayBase< Derived > & array () const
EIGEN_DEVICE_FUNC MatrixWrapper< Derived > matrix ()
EIGEN_DEVICE_FUNC const MatrixWrapper< const Derived > matrix () const
Public Member Functions inherited from Eigen::DenseBase< Derived >
EIGEN_DEVICE_FUNC Index nonZeros () const
EIGEN_DEVICE_FUNC Index outerSize () const
EIGEN_DEVICE_FUNC Index innerSize () const
EIGEN_DEVICE_FUNC void resize (Index newSize)
EIGEN_DEVICE_FUNC void resize (Index rows, Index cols)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator= (const DenseBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator= (const DenseBase &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator= (const EigenBase< OtherDerived > &other)
Copies the generic expression other into *this.
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator+= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator-= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator= (const ReturnByValue< OtherDerived > &func)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & lazyAssign (const DenseBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC CommaInitializer< Derived > operator<< (const Scalar &s)
template<unsigned int Added, unsigned int Removed>
EIGEN_DEPRECATED const Derived & flagged () const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC CommaInitializer< Derived > operator<< (const DenseBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC TransposeReturnType transpose ()
EIGEN_DEVICE_FUNC ConstTransposeReturnType transpose () const
EIGEN_DEVICE_FUNC void transposeInPlace ()
EIGEN_DEVICE_FUNC void fill (const Scalar &value)
EIGEN_DEVICE_FUNC Derived & setConstant (const Scalar &value)
EIGEN_DEVICE_FUNC Derived & setLinSpaced (Index size, const Scalar &low, const Scalar &high)
Sets a linearly spaced vector.
EIGEN_DEVICE_FUNC Derived & setLinSpaced (const Scalar &low, const Scalar &high)
Sets a linearly spaced vector.
EIGEN_DEVICE_FUNC Derived & setZero ()
EIGEN_DEVICE_FUNC Derived & setOnes ()
EIGEN_DEVICE_FUNC Derived & setRandom ()
template<typename OtherDerived >
EIGEN_DEVICE_FUNC bool isApprox (const DenseBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isMuchSmallerThan (const RealScalar &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC bool isMuchSmallerThan (const DenseBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isApproxToConstant (const Scalar &value, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isConstant (const Scalar &value, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isZero (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isOnes (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool hasNaN () const
bool allFinite () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator*= (const Scalar &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator/= (const Scalar &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EvalReturnType eval () const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC void swap (const DenseBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC void swap (PlainObjectBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC const NestByValue< Derived > nestByValue () const
EIGEN_DEVICE_FUNC const ForceAlignedAccess< Derived > forceAlignedAccess () const
EIGEN_DEVICE_FUNC ForceAlignedAccess< Derived > forceAlignedAccess ()
template<bool Enable>
EIGEN_DEVICE_FUNC const internal::conditional< Enable, ForceAlignedAccess< Derived >, Derived & >::type forceAlignedAccessIf () const
template<bool Enable>
EIGEN_DEVICE_FUNC internal::conditional< Enable, ForceAlignedAccess< Derived >, Derived & >::type forceAlignedAccessIf ()
EIGEN_DEVICE_FUNC Scalar sum () const
EIGEN_DEVICE_FUNC Scalar mean () const
EIGEN_DEVICE_FUNC Scalar trace () const
EIGEN_DEVICE_FUNC Scalar prod () const
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar minCoeff () const
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar maxCoeff () const
template<typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar minCoeff (IndexType *row, IndexType *col) const
template<typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar maxCoeff (IndexType *row, IndexType *col) const
template<typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar minCoeff (IndexType *index) const
template<typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar maxCoeff (IndexType *index) const
template<typename BinaryOp >
EIGEN_DEVICE_FUNC Scalar redux (const BinaryOp &func) const
template<typename Visitor >
EIGEN_DEVICE_FUNC void visit (Visitor &func) const
const WithFormat< Derived > format (const IOFormat &fmt) const
EIGEN_DEVICE_FUNC CoeffReturnType value () const
EIGEN_DEVICE_FUNC bool all () const
EIGEN_DEVICE_FUNC bool any () const
EIGEN_DEVICE_FUNC Index count () const
EIGEN_DEVICE_FUNC ConstRowwiseReturnType rowwise () const
EIGEN_DEVICE_FUNC RowwiseReturnType rowwise ()
EIGEN_DEVICE_FUNC ConstColwiseReturnType colwise () const
EIGEN_DEVICE_FUNC ColwiseReturnType colwise ()
template<typename ThenDerived , typename ElseDerived >
const Select< Derived, ThenDerived, ElseDerived > select (const DenseBase< ThenDerived > &thenMatrix, const DenseBase< ElseDerived > &elseMatrix) const
template<typename ThenDerived >
const Select< Derived, ThenDerived, typename ThenDerived::ConstantReturnType > select (const DenseBase< ThenDerived > &thenMatrix, const typename ThenDerived::Scalar &elseScalar) const
template<typename ElseDerived >
const Select< Derived, typename ElseDerived::ConstantReturnType, ElseDerived > select (const typename ElseDerived::Scalar &thenScalar, const DenseBase< ElseDerived > &elseMatrix) const
template<int p>
RealScalar lpNorm () const
template<int RowFactor, int ColFactor>
EIGEN_DEVICE_FUNC const Replicate< Derived, RowFactor, ColFactor > replicate () const
EIGEN_DEVICE_FUNC const Replicate< Derived, Dynamic, Dynamic > replicate (Index rowFactor, Index colFactor) const
EIGEN_DEVICE_FUNC ReverseReturnType reverse ()
EIGEN_DEVICE_FUNC ConstReverseReturnType reverse () const
EIGEN_DEVICE_FUNC void reverseInPlace ()
EIGEN_DEVICE_FUNC const NegativeReturnType operator- () const
template<typename NewType >
EIGEN_DEVICE_FUNC CastXpr< NewType >::Type cast () const
EIGEN_DEVICE_FUNC ConjugateReturnType conjugate () const
EIGEN_DEVICE_FUNC RealReturnType real () const
EIGEN_DEVICE_FUNC const ImagReturnType imag () const
template<typename CustomUnaryOp >
EIGEN_DEVICE_FUNC const CwiseUnaryOp< CustomUnaryOp, const Derived > unaryExpr (const CustomUnaryOp &func=CustomUnaryOp()) const
Apply a unary operator coefficient-wise.
template<typename CustomViewOp >
EIGEN_DEVICE_FUNC const CwiseUnaryView< CustomViewOp, const Derived > unaryViewExpr (const CustomViewOp &func=CustomViewOp()) const
EIGEN_DEVICE_FUNC NonConstRealReturnType real ()
EIGEN_DEVICE_FUNC NonConstImagReturnType imag ()
template<typename NRowsType , typename NColsType >
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type block (Index startRow, Index startCol, NRowsType blockRows, NColsType blockCols)
template<typename NRowsType , typename NColsType >
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type block (Index startRow, Index startCol, NRowsType blockRows, NColsType blockCols) const
This is the const version of block(Index,Index,NRowsType,NColsType)
template<typename NRowsType , typename NColsType >
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type topRightCorner (NRowsType cRows, NColsType cCols)
template<typename NRowsType , typename NColsType >
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type topRightCorner (NRowsType cRows, NColsType cCols) const
This is the const version of topRightCorner(NRowsType, NColsType).
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type topRightCorner ()
template<int CRows, int CCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type topRightCorner () const
This is the const version of topRightCorner<int, int>().
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type topRightCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
const ConstFixedBlockXpr< CRows, CCols >::Type topRightCorner (Index cRows, Index cCols) const
This is the const version of topRightCorner<int, int>(Index, Index).
template<typename NRowsType , typename NColsType >
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type topLeftCorner (NRowsType cRows, NColsType cCols)
template<typename NRowsType , typename NColsType >
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type topLeftCorner (NRowsType cRows, NColsType cCols) const
This is the const version of topLeftCorner(Index, Index).
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type topLeftCorner ()
template<int CRows, int CCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type topLeftCorner () const
This is the const version of topLeftCorner<int, int>().
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type topLeftCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
const ConstFixedBlockXpr< CRows, CCols >::Type topLeftCorner (Index cRows, Index cCols) const
This is the const version of topLeftCorner<int, int>(Index, Index).
template<typename NRowsType , typename NColsType >
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type bottomRightCorner (NRowsType cRows, NColsType cCols)
template<typename NRowsType , typename NColsType >
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type bottomRightCorner (NRowsType cRows, NColsType cCols) const
This is the const version of bottomRightCorner(NRowsType, NColsType).
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type bottomRightCorner ()
template<int CRows, int CCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type bottomRightCorner () const
This is the const version of bottomRightCorner<int, int>().
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type bottomRightCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
const ConstFixedBlockXpr< CRows, CCols >::Type bottomRightCorner (Index cRows, Index cCols) const
This is the const version of bottomRightCorner<int, int>(Index, Index).
template<typename NRowsType , typename NColsType >
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type bottomLeftCorner (NRowsType cRows, NColsType cCols)
template<typename NRowsType , typename NColsType >
EIGEN_DEVICE_FUNC ConstFixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type bottomLeftCorner (NRowsType cRows, NColsType cCols) const
This is the const version of bottomLeftCorner(NRowsType, NColsType).
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type bottomLeftCorner ()
template<int CRows, int CCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type bottomLeftCorner () const
This is the const version of bottomLeftCorner<int, int>().
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type bottomLeftCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
const ConstFixedBlockXpr< CRows, CCols >::Type bottomLeftCorner (Index cRows, Index cCols) const
This is the const version of bottomLeftCorner<int, int>(Index, Index).
template<typename NRowsType >
EIGEN_DEVICE_FUNC NRowsBlockXpr< internal::get_fixed_value< NRowsType >::value >::Type topRows (NRowsType n)
template<typename NRowsType >
EIGEN_DEVICE_FUNC const ConstNRowsBlockXpr< internal::get_fixed_value< NRowsType >::value >::Type topRows (NRowsType n) const
This is the const version of topRows(NRowsType).
template<int N>
EIGEN_DEVICE_FUNC NRowsBlockXpr< N >::Type topRows (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNRowsBlockXpr< N >::Type topRows (Index n=N) const
This is the const version of topRows<int>().
template<typename NRowsType >
EIGEN_DEVICE_FUNC NRowsBlockXpr< internal::get_fixed_value< NRowsType >::value >::Type bottomRows (NRowsType n)
template<typename NRowsType >
EIGEN_DEVICE_FUNC const ConstNRowsBlockXpr< internal::get_fixed_value< NRowsType >::value >::Type bottomRows (NRowsType n) const
This is the const version of bottomRows(NRowsType).
template<int N>
EIGEN_DEVICE_FUNC NRowsBlockXpr< N >::Type bottomRows (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNRowsBlockXpr< N >::Type bottomRows (Index n=N) const
This is the const version of bottomRows<int>().
template<typename NRowsType >
EIGEN_DEVICE_FUNC NRowsBlockXpr< internal::get_fixed_value< NRowsType >::value >::Type middleRows (Index startRow, NRowsType n)
template<typename NRowsType >
EIGEN_DEVICE_FUNC const ConstNRowsBlockXpr< internal::get_fixed_value< NRowsType >::value >::Type middleRows (Index startRow, NRowsType n) const
This is the const version of middleRows(Index,NRowsType).
template<int N>
EIGEN_DEVICE_FUNC NRowsBlockXpr< N >::Type middleRows (Index startRow, Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNRowsBlockXpr< N >::Type middleRows (Index startRow, Index n=N) const
This is the const version of middleRows<int>().
template<typename NColsType >
EIGEN_DEVICE_FUNC NColsBlockXpr< internal::get_fixed_value< NColsType >::value >::Type leftCols (NColsType n)
template<typename NColsType >
EIGEN_DEVICE_FUNC const ConstNColsBlockXpr< internal::get_fixed_value< NColsType >::value >::Type leftCols (NColsType n) const
This is the const version of leftCols(NColsType).
template<int N>
EIGEN_DEVICE_FUNC NColsBlockXpr< N >::Type leftCols (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNColsBlockXpr< N >::Type leftCols (Index n=N) const
This is the const version of leftCols<int>().
template<typename NColsType >
EIGEN_DEVICE_FUNC NColsBlockXpr< internal::get_fixed_value< NColsType >::value >::Type rightCols (NColsType n)
template<typename NColsType >
EIGEN_DEVICE_FUNC const ConstNColsBlockXpr< internal::get_fixed_value< NColsType >::value >::Type rightCols (NColsType n) const
This is the const version of rightCols(NColsType).
template<int N>
EIGEN_DEVICE_FUNC NColsBlockXpr< N >::Type rightCols (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNColsBlockXpr< N >::Type rightCols (Index n=N) const
This is the const version of rightCols<int>().
template<typename NColsType >
EIGEN_DEVICE_FUNC NColsBlockXpr< internal::get_fixed_value< NColsType >::value >::Type middleCols (Index startCol, NColsType numCols)
template<typename NColsType >
EIGEN_DEVICE_FUNC const ConstNColsBlockXpr< internal::get_fixed_value< NColsType >::value >::Type middleCols (Index startCol, NColsType numCols) const
This is the const version of middleCols(Index,NColsType).
template<int N>
EIGEN_DEVICE_FUNC NColsBlockXpr< N >::Type middleCols (Index startCol, Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNColsBlockXpr< N >::Type middleCols (Index startCol, Index n=N) const
This is the const version of middleCols<int>().
template<int NRows, int NCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol)
template<int NRows, int NCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol) const
This is the const version of block<>(Index, Index). */.
template<int NRows, int NCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol, Index blockRows, Index blockCols)
template<int NRows, int NCols>
const ConstFixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol, Index blockRows, Index blockCols) const
This is the const version of block<>(Index, Index, Index, Index).
EIGEN_DEVICE_FUNC ColXpr col (Index i)
EIGEN_DEVICE_FUNC ConstColXpr col (Index i) const
This is the const version of col().
EIGEN_DEVICE_FUNC RowXpr row (Index i)
EIGEN_DEVICE_FUNC ConstRowXpr row (Index i) const
This is the const version of row(). */.
template<typename NType >
EIGEN_DEVICE_FUNC FixedSegmentReturnType< internal::get_fixed_value< NType >::value >::Type segment (Index start, NType n)
template<typename NType >
EIGEN_DEVICE_FUNC const ConstFixedSegmentReturnType< internal::get_fixed_value< NType >::value >::Type segment (Index start, NType n) const
This is the const version of segment(Index,NType).
template<typename NType >
EIGEN_DEVICE_FUNC FixedSegmentReturnType< internal::get_fixed_value< NType >::value >::Type head (NType n)
template<typename NType >
EIGEN_DEVICE_FUNC const ConstFixedSegmentReturnType< internal::get_fixed_value< NType >::value >::Type head (NType n) const
This is the const version of head(NType).
template<typename NType >
EIGEN_DEVICE_FUNC FixedSegmentReturnType< internal::get_fixed_value< NType >::value >::Type tail (NType n)
template<typename NType >
EIGEN_DEVICE_FUNC const ConstFixedSegmentReturnType< internal::get_fixed_value< NType >::value >::Type tail (NType n) const
This is the const version of tail(Index).
template<int N>
EIGEN_DEVICE_FUNC FixedSegmentReturnType< N >::Type segment (Index start, Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType< N >::Type segment (Index start, Index n=N) const
This is the const version of segment<int>(Index).
template<int N>
EIGEN_DEVICE_FUNC FixedSegmentReturnType< N >::Type head (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType< N >::Type head (Index n=N) const
This is the const version of head<int>().
template<int N>
EIGEN_DEVICE_FUNC FixedSegmentReturnType< N >::Type tail (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType< N >::Type tail (Index n=N) const
This is the const version of tail<int>.
template<typename RowIndices , typename ColIndices >
internal::enable_if< valid_indexed_view_overload< RowIndices, ColIndices >::value &&internal::traits< typename EIGEN_INDEXED_VIEW_METHOD_TYPE< RowIndices, ColIndices >::type >::ReturnAsIndexedView, typename EIGEN_INDEXED_VIEW_METHOD_TYPE< RowIndices, ColIndices >::type >::type operator() (const RowIndices &rowIndices, const ColIndices &colIndices) EIGEN_INDEXED_VIEW_METHOD_CONST
template<typename RowIndices , typename ColIndices >
internal::enable_if< valid_indexed_view_overload< RowIndices, ColIndices >::value &&internal::traits< typename EIGEN_INDEXED_VIEW_METHOD_TYPE< RowIndices, ColIndices >::type >::ReturnAsBlock, typename internal::traits< typename EIGEN_INDEXED_VIEW_METHOD_TYPE< RowIndices, ColIndices >::type >::BlockType >::type operator() (const RowIndices &rowIndices, const ColIndices &colIndices) EIGEN_INDEXED_VIEW_METHOD_CONST
template<typename RowIndices , typename ColIndices >
internal::enable_if< valid_indexed_view_overload< RowIndices, ColIndices >::value &&internal::traits< typename EIGEN_INDEXED_VIEW_METHOD_TYPE< RowIndices, ColIndices >::type >::ReturnAsScalar, CoeffReturnType >::type operator() (const RowIndices &rowIndices, const ColIndices &colIndices) EIGEN_INDEXED_VIEW_METHOD_CONST
template<typename Indices >
internal::enable_if< IsRowMajor &&(!(internal::get_compile_time_incr< typename IvcType< Indices >::type >::value==1||internal::is_valid_index_type< Indices >::value)), IndexedView< EIGEN_INDEXED_VIEW_METHOD_CONST Derived, IvcIndex, typename IvcType< Indices >::type > >::type operator() (const Indices &indices) EIGEN_INDEXED_VIEW_METHOD_CONST
template<typename Indices >
internal::enable_if< (!IsRowMajor)&&(!(internal::get_compile_time_incr< typename IvcType< Indices >::type >::value==1||internal::is_valid_index_type< Indices >::value)), IndexedView< EIGEN_INDEXED_VIEW_METHOD_CONST Derived, typename IvcType< Indices >::type, IvcIndex > >::type operator() (const Indices &indices) EIGEN_INDEXED_VIEW_METHOD_CONST
template<typename Indices >
internal::enable_if< (internal::get_compile_time_incr< typename IvcType< Indices >::type >::value==1)&&(!internal::is_valid_index_type< Indices >::value)&&(!Symbolic::is_symbolic< Indices >::value), VectorBlock< EIGEN_INDEXED_VIEW_METHOD_CONST Derived, internal::array_size< Indices >::value > >::type operator() (const Indices &indices) EIGEN_INDEXED_VIEW_METHOD_CONST
template<typename IndexType >
internal::enable_if< Symbolic::is_symbolic< IndexType >::value, CoeffReturnType >::type operator() (const IndexType &id) EIGEN_INDEXED_VIEW_METHOD_CONST
template<typename RowIndices , typename ColIndices >
internal::enable_if< valid_indexed_view_overload< RowIndices, ColIndices >::value &&internal::traits< typename EIGEN_INDEXED_VIEW_METHOD_TYPE< RowIndices, ColIndices >::type >::ReturnAsIndexedView, typename EIGEN_INDEXED_VIEW_METHOD_TYPE< RowIndices, ColIndices >::type >::type operator() (const RowIndices &rowIndices, const ColIndices &colIndices) EIGEN_INDEXED_VIEW_METHOD_CONST
template<typename RowIndices , typename ColIndices >
internal::enable_if< valid_indexed_view_overload< RowIndices, ColIndices >::value &&internal::traits< typename EIGEN_INDEXED_VIEW_METHOD_TYPE< RowIndices, ColIndices >::type >::ReturnAsBlock, typename internal::traits< typename EIGEN_INDEXED_VIEW_METHOD_TYPE< RowIndices, ColIndices >::type >::BlockType >::type operator() (const RowIndices &rowIndices, const ColIndices &colIndices) EIGEN_INDEXED_VIEW_METHOD_CONST
template<typename RowIndices , typename ColIndices >
internal::enable_if< valid_indexed_view_overload< RowIndices, ColIndices >::value &&internal::traits< typename EIGEN_INDEXED_VIEW_METHOD_TYPE< RowIndices, ColIndices >::type >::ReturnAsScalar, CoeffReturnType >::type operator() (const RowIndices &rowIndices, const ColIndices &colIndices) EIGEN_INDEXED_VIEW_METHOD_CONST
template<typename Indices >
internal::enable_if< IsRowMajor &&(!(internal::get_compile_time_incr< typename IvcType< Indices >::type >::value==1||internal::is_valid_index_type< Indices >::value)), IndexedView< EIGEN_INDEXED_VIEW_METHOD_CONST Derived, IvcIndex, typename IvcType< Indices >::type > >::type operator() (const Indices &indices) EIGEN_INDEXED_VIEW_METHOD_CONST
template<typename Indices >
internal::enable_if< (!IsRowMajor)&&(!(internal::get_compile_time_incr< typename IvcType< Indices >::type >::value==1||internal::is_valid_index_type< Indices >::value)), IndexedView< EIGEN_INDEXED_VIEW_METHOD_CONST Derived, typename IvcType< Indices >::type, IvcIndex > >::type operator() (const Indices &indices) EIGEN_INDEXED_VIEW_METHOD_CONST
template<typename Indices >
internal::enable_if< (internal::get_compile_time_incr< typename IvcType< Indices >::type >::value==1)&&(!internal::is_valid_index_type< Indices >::value)&&(!Symbolic::is_symbolic< Indices >::value), VectorBlock< EIGEN_INDEXED_VIEW_METHOD_CONST Derived, internal::array_size< Indices >::value > >::type operator() (const Indices &indices) EIGEN_INDEXED_VIEW_METHOD_CONST
template<typename IndexType >
internal::enable_if< Symbolic::is_symbolic< IndexType >::value, CoeffReturnType >::type operator() (const IndexType &id) EIGEN_INDEXED_VIEW_METHOD_CONST
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & lazyAssign (const DenseBase< OtherDerived > &other)
template<typename CustomNullaryOp >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseNullaryOp< CustomNullaryOp, typename DenseBase< Derived >::PlainObject > NullaryExpr (Index rows, Index cols, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseNullaryOp< CustomNullaryOp, typename DenseBase< Derived >::PlainObject > NullaryExpr (Index size, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseNullaryOp< CustomNullaryOp, typename DenseBase< Derived >::PlainObject > NullaryExpr (const CustomNullaryOp &func)
template<typename Derived >
EIGEN_DEVICE_FUNC bool isMuchSmallerThan (const typename NumTraits< Scalar >::Real &other, const RealScalar &prec) const
template<typename Func >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar redux (const Func &func) const
Protected Member Functions
EIGEN_DEVICE_FUNC ArrayBase ()
template<typename OtherDerived >
Derived & operator+= (const MatrixBase< OtherDerived > &)
template<typename OtherDerived >
Derived & operator-= (const MatrixBase< OtherDerived > &)
Protected Member Functions inherited from Eigen::DenseBase< Derived >
template<typename Indices >
IvcRowType< Indices >::type ivcRow (const Indices &indices) const
template<typename Indices >
IvcColType< Indices >::type ivcCol (const Indices &indices) const
template<typename Indices >
IvcColType< Indices >::type ivcSize (const Indices &indices) const
EIGEN_DEVICE_FUNC DenseBase ()
Private Member Functions
ArrayBase (Index)
ArrayBase (Index, Index)
template<typename OtherDerived >
ArrayBase (const ArrayBase< OtherDerived > &)
Related Functions
(Note that these are not member functions.)
template<typename Derived , typename ScalarExponent >
#define EIGEN_MSVC10_WORKAROUND_BINARYOP_RETURN_TYPE(X) X
template<typename Derived , typename ExponentDerived >
const Eigen::CwiseBinaryOp< Eigen::internal::scalar_pow_op< typename Derived::Scalar, typename ExponentDerived::Scalar >, const Derived, const ExponentDerived > pow (const Eigen::ArrayBase< Derived > &x, const Eigen::ArrayBase< ExponentDerived > &exponents)
template<typename Scalar , typename Derived >
#define EIGEN_MSVC10_WORKAROUND_BINARYOP_RETURN_TYPE(X) X
Related Functions inherited from Eigen::DenseBase< Derived >
template<typename Derived >
std::ostream & operator<< (std::ostream &s, const DenseBase< Derived > &m)
Additional Inherited Members
Static Public Member Functions inherited from Eigen::DenseBase< Derived >
static EIGEN_DEVICE_FUNC const ConstantReturnType Constant (Index rows, Index cols, const Scalar &value)
static EIGEN_DEVICE_FUNC const ConstantReturnType Constant (Index size, const Scalar &value)
static EIGEN_DEVICE_FUNC const ConstantReturnType Constant (const Scalar &value)
static EIGEN_DEVICE_FUNC const SequentialLinSpacedReturnType LinSpaced (Sequential_t, Index size, const Scalar &low, const Scalar &high)
static EIGEN_DEVICE_FUNC const RandomAccessLinSpacedReturnType LinSpaced (Index size, const Scalar &low, const Scalar &high)
Sets a linearly spaced vector.
static EIGEN_DEVICE_FUNC const SequentialLinSpacedReturnType LinSpaced (Sequential_t, const Scalar &low, const Scalar &high)
static EIGEN_DEVICE_FUNC const RandomAccessLinSpacedReturnType LinSpaced (const Scalar &low, const Scalar &high)
Sets a linearly spaced vector.
template<typename CustomNullaryOp >
static EIGEN_DEVICE_FUNC const CwiseNullaryOp< CustomNullaryOp, PlainObject > NullaryExpr (Index rows, Index cols, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
static EIGEN_DEVICE_FUNC const CwiseNullaryOp< CustomNullaryOp, PlainObject > NullaryExpr (Index size, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
static EIGEN_DEVICE_FUNC const CwiseNullaryOp< CustomNullaryOp, PlainObject > NullaryExpr (const CustomNullaryOp &func)
static EIGEN_DEVICE_FUNC const ConstantReturnType Zero (Index rows, Index cols)
static EIGEN_DEVICE_FUNC const ConstantReturnType Zero (Index size)
static EIGEN_DEVICE_FUNC const ConstantReturnType Zero ()
static EIGEN_DEVICE_FUNC const ConstantReturnType Ones (Index rows, Index cols)
static EIGEN_DEVICE_FUNC const ConstantReturnType Ones (Index size)
static EIGEN_DEVICE_FUNC const ConstantReturnType Ones ()
static const RandomReturnType Random (Index rows, Index cols)
static const RandomReturnType Random (Index size)
static const RandomReturnType Random ()
Protected Types inherited from Eigen::DenseBase< Derived >
typedef internal::IndexedViewCompatibleType< Index, 1 >::type IvcIndex
Detailed Description
template<typename Derived>
class Eigen::ArrayBase< Derived >
Base class for all 1D and 2D array, and related expressions.
An array is similar to a dense vector or matrix. While matrices are mathematical objects with well defined linear algebra operators, an array is just a collection of scalar values arranged in a one or two dimensionnal fashion. As the main consequence, all operations applied to an array are performed coefficient wise. Furthermore, arrays support scalar math functions of the c++ standard library (e.g., std::sin(x)), and convenient constructors allowing to easily write generic code working for both scalar values and arrays.
This class is the base that is inherited by all array expression types.
Template Parameters
Derived is the derived type, e.g., an array or an expression type.
This class can be extended with the help of the plugin mechanism described on the page TopicCustomizing_Plugins by defining the preprocessor symbol EIGEN_ARRAYBASE_PLUGIN.
See also
class MatrixBase, TopicClassHierarchy
Member Typedef Documentation
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_abs2_op<Scalar>, const Derived> Eigen::ArrayBase< Derived >::Abs2ReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_abs_op<Scalar>, const Derived> Eigen::ArrayBase< Derived >::AbsReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_acos_op<Scalar>, const Derived> Eigen::ArrayBase< Derived >::AcosReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_arg_op<Scalar>, const Derived> Eigen::ArrayBase< Derived >::ArgReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_asin_op<Scalar>, const Derived> Eigen::ArrayBase< Derived >::AsinReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_atan_op<Scalar>, const Derived> Eigen::ArrayBase< Derived >::AtanReturnType
template<typename Derived> typedef DenseBase<Derived> Eigen::ArrayBase< Derived >::Base
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_boolean_not_op<Scalar>, const Derived> Eigen::ArrayBase< Derived >::BooleanNotReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_ceil_op<Scalar>, const Derived> Eigen::ArrayBase< Derived >::CeilReturnType
template<typename Derived> typedef Base::CoeffReturnType Eigen::ArrayBase< Derived >::CoeffReturnType
template<typename Derived> typedef CwiseNullaryOp<internal::scalar_constant_op<Scalar>,PlainObject> Eigen::ArrayBase< Derived >::ConstantReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_cosh_op<Scalar>, const Derived> Eigen::ArrayBase< Derived >::CoshReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_cos_op<Scalar>, const Derived> Eigen::ArrayBase< Derived >::CosReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_cube_op<Scalar>, const Derived> Eigen::ArrayBase< Derived >::CubeReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_abs2_op<Scalar>, const Derived> Eigen::ArrayBase< Derived >::CwiseAbs2ReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_abs_op<Scalar>, const Derived> Eigen::ArrayBase< Derived >::CwiseAbsReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_inverse_op<Scalar>, const Derived> Eigen::ArrayBase< Derived >::CwiseInverseReturnType
template<typename Derived> typedef CwiseBinaryOp<internal::scalar_cmp_op<Scalar,Scalar,internal::cmp_EQ>, const Derived, const ConstantReturnType> Eigen::ArrayBase< Derived >::CwiseScalarEqualReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_sign_op<Scalar>, const Derived> Eigen::ArrayBase< Derived >::CwiseSignReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_sqrt_op<Scalar>, const Derived> Eigen::ArrayBase< Derived >::CwiseSqrtReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_digamma_op<Scalar>, const Derived> Eigen::ArrayBase< Derived >::DigammaReturnType
template<typename Derived> typedef ArrayBase Eigen::ArrayBase< Derived >::Eigen_BaseClassForSpecializationOfGlobalMathFuncImpl
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_erfc_op<Scalar>, const Derived> Eigen::ArrayBase< Derived >::ErfcReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_erf_op<Scalar>, const Derived> Eigen::ArrayBase< Derived >::ErfReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_expm1_op<Scalar>, const Derived> Eigen::ArrayBase< Derived >::Expm1ReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_exp_op<Scalar>, const Derived> Eigen::ArrayBase< Derived >::ExpReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_floor_op<Scalar>, const Derived> Eigen::ArrayBase< Derived >::FloorReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_inverse_op<Scalar>, const Derived> Eigen::ArrayBase< Derived >::InverseReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_isfinite_op<Scalar>, const Derived> Eigen::ArrayBase< Derived >::IsFiniteReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_isinf_op<Scalar>, const Derived> Eigen::ArrayBase< Derived >::IsInfReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_isnan_op<Scalar>, const Derived> Eigen::ArrayBase< Derived >::IsNaNReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_lgamma_op<Scalar>, const Derived> Eigen::ArrayBase< Derived >::LgammaReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_log10_op<Scalar>, const Derived> Eigen::ArrayBase< Derived >::Log10ReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_log1p_op<Scalar>, const Derived> Eigen::ArrayBase< Derived >::Log1pReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_log_op<Scalar>, const Derived> Eigen::ArrayBase< Derived >::LogReturnType
template<typename Derived> typedef internal::packet_traits<Scalar>::type Eigen::ArrayBase< Derived >::PacketScalar
template<typename Derived> typedef Base::PlainObject Eigen::ArrayBase< Derived >::PlainObject
template<typename Derived> typedef NumTraits<Scalar>::Real Eigen::ArrayBase< Derived >::RealScalar
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_round_op<Scalar>, const Derived> Eigen::ArrayBase< Derived >::RoundReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_rsqrt_op<Scalar>, const Derived> Eigen::ArrayBase< Derived >::RsqrtReturnType
template<typename Derived> typedef internal::traits<Derived>::Scalar Eigen::ArrayBase< Derived >::Scalar
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_sign_op<Scalar>, const Derived> Eigen::ArrayBase< Derived >::SignReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_sinh_op<Scalar>, const Derived> Eigen::ArrayBase< Derived >::SinhReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_sin_op<Scalar>, const Derived> Eigen::ArrayBase< Derived >::SinReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_sqrt_op<Scalar>, const Derived> Eigen::ArrayBase< Derived >::SqrtReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_square_op<Scalar>, const Derived> Eigen::ArrayBase< Derived >::SquareReturnType
template<typename Derived> typedef ArrayBase Eigen::ArrayBase< Derived >::StorageBaseType
The base class for a given storage type.
template<typename Derived> typedef internal::traits<Derived>::StorageKind Eigen::ArrayBase< Derived >::StorageKind
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_tanh_op<Scalar>, const Derived> Eigen::ArrayBase< Derived >::TanhReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_tan_op<Scalar>, const Derived> Eigen::ArrayBase< Derived >::TanReturnType
Constructor & Destructor Documentation
template<typename Derived> EIGEN_DEVICE_FUNC Eigen::ArrayBase< Derived >::ArrayBase () inline protected
Referenced by Eigen::ArrayBase< ArrayWrapper< ExpressionType > >::ArrayBase().
template<typename Derived> Eigen::ArrayBase< Derived >::ArrayBase (Index) explicit private
template<typename Derived> Eigen::ArrayBase< Derived >::ArrayBase (Index , Index) private
template<typename Derived> template<typename OtherDerived > Eigen::ArrayBase< Derived >::ArrayBase (const ArrayBase< OtherDerived > &) explicit private
Member Function Documentation
template<typename Derived> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const AbsReturnType Eigen::ArrayBase< Derived >::abs () const inline
Returns
an expression of the coefficient-wise absolute value of *this
Example:
Output:
See also
Math functions, abs2()
template<typename Derived> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Abs2ReturnType Eigen::ArrayBase< Derived >::abs2 () const inline
Returns
an expression of the coefficient-wise squared absolute value of *this
Example:
Output:
See also
Math functions, abs(), square()
template<typename Derived> EIGEN_DEVICE_FUNC const AcosReturnType Eigen::ArrayBase< Derived >::acos () const inline
Returns
an expression of the coefficient-wise arc cosine of *this.
Example:
Output:
See also
Math functions, cos(), asin()
template<typename Derived> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const ArgReturnType Eigen::ArrayBase< Derived >::arg () const inline
Returns
an expression of the coefficient-wise phase angle of *this
Example:
Output:
See also
abs()
template<typename Derived> EIGEN_DEVICE_FUNC ArrayBase<Derived>& Eigen::ArrayBase< Derived >::array () inline
template<typename Derived> EIGEN_DEVICE_FUNC const ArrayBase<Derived>& Eigen::ArrayBase< Derived >::array () const inline
template<typename Derived> EIGEN_DEVICE_FUNC const AsinReturnType Eigen::ArrayBase< Derived >::asin () const inline
Returns
an expression of the coefficient-wise arc sine of *this.
Example:
Output:
See also
Math functions, sin(), acos()
template<typename Derived> EIGEN_DEVICE_FUNC const AtanReturnType Eigen::ArrayBase< Derived >::atan () const inline
Returns
an expression of the coefficient-wise arc tan of *this.
Example:
Output:
See also
Math functions, tan(), asin(), acos()
template<typename Derived> template<typename CustomBinaryOp , typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp<CustomBinaryOp, const Derived, const OtherDerived> Eigen::ArrayBase< Derived >::binaryExpr (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > & other, const CustomBinaryOp & func = CustomBinaryOp()) const inline
Returns
an expression of the difference of *this and other
Note
If you want to substract a given scalar from all coefficients, see Cwise::operator-().
See also
class CwiseBinaryOp, operator-=()
Returns
an expression of the sum of *this and other
Note
If you want to add a given scalar to all coefficients, see Cwise::operator+().
See also
class CwiseBinaryOp, operator+=()
Returns
an expression of a custom coefficient-wise operator func of *this and other
The template parameter CustomBinaryOp is the type of the functor of the custom operator (see class CwiseBinaryOp for an example)
Here is an example illustrating the use of custom functors:
Output:
See also
class CwiseBinaryOp, operator+(), operator-(), cwiseProduct()
template<typename Derived> EIGEN_DEVICE_FUNC const CeilReturnType Eigen::ArrayBase< Derived >::ceil () const inline
Returns
an expression of the coefficient-wise ceil of *this.
Example:
Output:
See also
Math functions, floor(), round()
template<typename Derived> EIGEN_DEVICE_FUNC const CosReturnType Eigen::ArrayBase< Derived >::cos () const inline
Returns
an expression of the coefficient-wise cosine of *this.
This function computes the coefficient-wise cosine. The function MatrixBase::cos() in the unsupported module MatrixFunctions computes the matrix cosine.
Example:
Output:
See also
Math functions, sin(), acos()
template<typename Derived> EIGEN_DEVICE_FUNC const CoshReturnType Eigen::ArrayBase< Derived >::cosh () const inline
Returns
an expression of the coefficient-wise hyperbolic cos of *this.
Example:
Output:
See also
Math functions, tan(), sinh(), cosh()
template<typename Derived> EIGEN_DEVICE_FUNC const CubeReturnType Eigen::ArrayBase< Derived >::cube () const inline
Returns
an expression of the coefficient-wise cube of *this.
Example:
Output:
See also
Math functions, square(), pow()
template<typename Derived> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseAbsReturnType Eigen::ArrayBase< Derived >::cwiseAbs () const inline
Returns
an expression of the coefficient-wise absolute value of *this
Example:
Output:
See also
cwiseAbs2()
template<typename Derived> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseAbs2ReturnType Eigen::ArrayBase< Derived >::cwiseAbs2 () const inline
Returns
an expression of the coefficient-wise squared absolute value of *this
Example:
Output:
See also
cwiseAbs()
template<typename Derived> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Eigen::ArrayBase< Derived >::CwiseBinaryOp (min) const inline
Returns
an expression of the coefficient-wise min of *this and other
Example:
Output:
See also
max()
Returns
an expression of the coefficient-wise min of *this and scalar other
See also
max()
template<typename Derived> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Eigen::ArrayBase< Derived >::CwiseBinaryOp (max) const inline
Returns
an expression of the coefficient-wise max of *this and other
Example:
Output:
See also
min()
Returns
an expression of the coefficient-wise max of *this and scalar other
See also
min()
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC const CwiseBinaryOp<std::equal_to<Scalar>, const Derived, const OtherDerived> Eigen::ArrayBase< Derived >::cwiseEqual (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > & other) const inline
Returns
an expression of the coefficient-wise == operator of *this and other
Warning
this performs an exact comparison, which is generally a bad idea with floating-point types. In order to check for equality between two vectors or matrices with floating-point coefficients, it is generally a far better idea to use a fuzzy comparison as provided by isApprox() and isMuchSmallerThan().
Example:
Output:
See also
cwiseNotEqual(), isApprox(), isMuchSmallerThan()
template<typename Derived> EIGEN_DEVICE_FUNC const CwiseScalarEqualReturnType Eigen::ArrayBase< Derived >::cwiseEqual (const Scalar & s) const inline
Returns
an expression of the coefficient-wise == operator of *this and a scalar s
Warning
this performs an exact comparison, which is generally a bad idea with floating-point types. In order to check for equality between two vectors or matrices with floating-point coefficients, it is generally a far better idea to use a fuzzy comparison as provided by isApprox() and isMuchSmallerThan().
See also
cwiseEqual(const MatrixBase<OtherDerived> &) const
template<typename Derived> EIGEN_DEVICE_FUNC const CwiseInverseReturnType Eigen::ArrayBase< Derived >::cwiseInverse () const inline
Returns
an expression of the coefficient-wise inverse of *this.
Example:
Output:
See also
cwiseProduct()
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp<internal::scalar_max_op<Scalar,Scalar>, const Derived, const OtherDerived> Eigen::ArrayBase< Derived >::cwiseMax (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > & other) const inline
Returns
an expression of the coefficient-wise max of *this and other
Example:
Output:
See also
class CwiseBinaryOp, min()
template<typename Derived> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp<internal::scalar_max_op<Scalar,Scalar>, const Derived, const ConstantReturnType> Eigen::ArrayBase< Derived >::cwiseMax (const Scalar & other) const inline
Returns
an expression of the coefficient-wise max of *this and scalar other
See also
class CwiseBinaryOp, min()
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp<internal::scalar_min_op<Scalar,Scalar>, const Derived, const OtherDerived> Eigen::ArrayBase< Derived >::cwiseMin (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > & other) const inline
Returns
an expression of the coefficient-wise min of *this and other
Example:
Output:
See also
class CwiseBinaryOp, max()
template<typename Derived> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp<internal::scalar_min_op<Scalar,Scalar>, const Derived, const ConstantReturnType> Eigen::ArrayBase< Derived >::cwiseMin (const Scalar & other) const inline
Returns
an expression of the coefficient-wise min of *this and scalar other
See also
class CwiseBinaryOp, min()
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC const CwiseBinaryOp<std::not_equal_to<Scalar>, const Derived, const OtherDerived> Eigen::ArrayBase< Derived >::cwiseNotEqual (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > & other) const inline
Returns
an expression of the coefficient-wise != operator of *this and other
Warning
this performs an exact comparison, which is generally a bad idea with floating-point types. In order to check for equality between two vectors or matrices with floating-point coefficients, it is generally a far better idea to use a fuzzy comparison as provided by isApprox() and isMuchSmallerThan().
Example:
Output:
See also
cwiseEqual(), isApprox(), isMuchSmallerThan()
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp<internal::scalar_quotient_op<Scalar>, const Derived, const OtherDerived> Eigen::ArrayBase< Derived >::cwiseQuotient (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > & other) const inline
Returns
an expression of the coefficient-wise quotient of *this and other
Example:
Output:
See also
class CwiseBinaryOp, cwiseProduct(), cwiseInverse()
template<typename Derived> EIGEN_DEVICE_FUNC const CwiseSignReturnType Eigen::ArrayBase< Derived >::cwiseSign () const inline
Returns
an expression of the coefficient-wise signum of *this.
Example:
Output:
template<typename Derived> EIGEN_DEVICE_FUNC const CwiseSqrtReturnType Eigen::ArrayBase< Derived >::cwiseSqrt () const inline
Returns
an expression of the coefficient-wise square root of *this.
Example:
Output:
See also
cwisePow(), cwiseSquare()
template<typename Derived> EIGEN_DEVICE_FUNC const DigammaReturnType Eigen::ArrayBase< Derived >::digamma () const inline
Returns
an expression of the coefficient-wise digamma (psi, derivative of lgamma).
Note
This function supports only float and double scalar types. To support other scalar types, the user has to provide implementations of digamma(T) for any scalar type T to be supported.
See also
Math functions, Eigen::digamma(), Eigen::polygamma(), lgamma()
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Eigen::ArrayBase< Derived >::EIGEN_CWISE_BINARY_RETURN_TYPE (Derived , OtherDerived , product) const inline
Returns
an expression of the coefficient wise product of *this and other
See also
MatrixBase::cwiseProduct
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Eigen::ArrayBase< Derived >::EIGEN_CWISE_BINARY_RETURN_TYPE (Derived , OtherDerived , product) const inline
Returns
an expression of the Schur product (coefficient wise product) of *this and other
Example:
Output:
See also
class CwiseBinaryOp, cwiseAbs2
template<typename Derived> EIGEN_DEVICE_FUNC const ErfReturnType Eigen::ArrayBase< Derived >::erf () const inline
Returns
an expression of the coefficient-wise Gauss error function of *this.
Example:
Output:
Note
This function supports only float and double scalar types in c++11 mode. To support other scalar types, or float/double in non c++11 mode, the user has to provide implementations of erf(T) for any scalar type T to be supported.
See also
Math functions, erfc()
template<typename Derived> EIGEN_DEVICE_FUNC const ErfcReturnType Eigen::ArrayBase< Derived >::erfc () const inline
Returns
an expression of the coefficient-wise Complementary error function of *this.
Example:
Output:
Note
This function supports only float and double scalar types in c++11 mode. To support other scalar types, or float/double in non c++11 mode, the user has to provide implementations of erfc(T) for any scalar type T to be supported.
See also
Math functions, erf()
template<typename Derived> EIGEN_DEVICE_FUNC const ExpReturnType Eigen::ArrayBase< Derived >::exp () const inline
Returns
an expression of the coefficient-wise exponential of *this.
This function computes the coefficient-wise exponential. The function MatrixBase::exp() in the unsupported module MatrixFunctions computes the matrix exponential.
Example:
Output:
See also
Math functions, pow(), log(), sin(), cos()
template<typename Derived> EIGEN_DEVICE_FUNC const Expm1ReturnType Eigen::ArrayBase< Derived >::expm1 () const inline
Returns
an expression of the coefficient-wise exponential of *this minus 1.
In exact arithmetic, x.expm1() is equivalent to x.exp() - 1, however, with finite precision, this function is much more accurate when x is close to zero.
See also
Math functions, exp()
template<typename Derived> EIGEN_DEVICE_FUNC const FloorReturnType Eigen::ArrayBase< Derived >::floor () const inline
Returns
an expression of the coefficient-wise floor of *this.
Example:
Output:
See also
Math functions, ceil(), round()
template<typename Derived> EIGEN_DEVICE_FUNC const InverseReturnType Eigen::ArrayBase< Derived >::inverse () const inline
Returns
an expression of the coefficient-wise inverse of *this.
Example:
Output:
See also
operator/(), operator*()
template<typename Derived> EIGEN_DEVICE_FUNC const IsFiniteReturnType Eigen::ArrayBase< Derived >::isFinite () const inline
Returns
an expression of the coefficient-wise isfinite of *this.
Example:
Output:
See also
isnan(), isinf()
template<typename Derived> EIGEN_DEVICE_FUNC const IsInfReturnType Eigen::ArrayBase< Derived >::isInf () const inline
Returns
an expression of the coefficient-wise isinf of *this.
Example:
Output:
See also
isnan(), isfinite()
template<typename Derived> EIGEN_DEVICE_FUNC const IsNaNReturnType Eigen::ArrayBase< Derived >::isNaN () const inline
Returns
an expression of the coefficient-wise isnan of *this.
Example:
Output:
See also
isfinite(), isinf()
template<typename Derived> EIGEN_DEVICE_FUNC const LgammaReturnType Eigen::ArrayBase< Derived >::lgamma () const inline
Returns
an expression of the coefficient-wise ln(|gamma(*this)|).
Example:
Output:
Note
This function supports only float and double scalar types in c++11 mode. To support other scalar types, or float/double in non c++11 mode, the user has to provide implementations of lgamma(T) for any scalar type T to be supported.
See also
Math functions, digamma()
template<typename Derived> EIGEN_DEVICE_FUNC const LogReturnType Eigen::ArrayBase< Derived >::log () const inline
Returns
an expression of the coefficient-wise logarithm of *this.
This function computes the coefficient-wise logarithm. The function MatrixBase::log() in the unsupported module MatrixFunctions computes the matrix logarithm.
Example:
Output:
See also
Math functions, log()
template<typename Derived> EIGEN_DEVICE_FUNC const Log10ReturnType Eigen::ArrayBase< Derived >::log10 () const inline
Returns
an expression of the coefficient-wise base-10 logarithm of *this.
This function computes the coefficient-wise base-10 logarithm.
Example:
Output:
See also
Math functions, log()
template<typename Derived> EIGEN_DEVICE_FUNC const Log1pReturnType Eigen::ArrayBase< Derived >::log1p () const inline
Returns
an expression of the coefficient-wise logarithm of 1 plus *this.
In exact arithmetic, x.log() is equivalent to (x+1).log(), however, with finite precision, this function is much more accurate when x is close to zero.
See also
Math functions, log()
template<typename Derived> EIGEN_DEVICE_FUNC MatrixWrapper<Derived> Eigen::ArrayBase< Derived >::matrix () inline
Returns
an Matrix expression of this array
See also
MatrixBase::array()
template<typename Derived> EIGEN_DEVICE_FUNC const MatrixWrapper<const Derived> Eigen::ArrayBase< Derived >::matrix () const inline
template<typename Derived> EIGEN_DEVICE_FUNC const BooleanNotReturnType Eigen::ArrayBase< Derived >::operator! () const inline
Returns
an expression of the coefficient-wise ! operator of *this
Warning
this operator is for expression of bool only.
Example:
Output:
See also
operator!=()
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC const CwiseBinaryOp<internal::scalar_boolean_and_op, const Derived, const OtherDerived> Eigen::ArrayBase< Derived >::operator&& (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > & other) const inline
Returns
an expression of the coefficient-wise boolean and operator of *this and other
Warning
this operator is for expression of bool only.
Example:
Output:
See also
operator||(), select()
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::ArrayBase< Derived >::operator*= (const ArrayBase< OtherDerived > & other)
replaces *this by *this * other coefficient wise.
Returns
a reference to *this
References Eigen::internal::call_assignment(), and EIGEN_STRONG_INLINE.
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::ArrayBase< Derived >::operator+= (const Scalar & scalar)
References Eigen::internal::call_assignment().
Referenced by Eigen::ArrayBase< ArrayWrapper< ExpressionType > >::operator=().
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::ArrayBase< Derived >::operator+= (const ArrayBase< OtherDerived > & other)
replaces *this by *this + other.
Returns
a reference to *this
References Eigen::internal::call_assignment(), and EIGEN_STRONG_INLINE.
template<typename Derived> template<typename OtherDerived > Derived& Eigen::ArrayBase< Derived >::operator+= (const MatrixBase< OtherDerived > &) inline protected
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::ArrayBase< Derived >::operator-= (const Scalar & scalar)
References Eigen::internal::call_assignment().
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::ArrayBase< Derived >::operator-= (const ArrayBase< OtherDerived > & other)
replaces *this by *this - other.
Returns
a reference to *this
References Eigen::internal::call_assignment().
template<typename Derived> template<typename OtherDerived > Derived& Eigen::ArrayBase< Derived >::operator-= (const MatrixBase< OtherDerived > &) inline protected
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp<internal::scalar_quotient_op<Scalar,typename OtherDerived::Scalar>, const Derived, const OtherDerived> Eigen::ArrayBase< Derived >::operator/ (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > & other) const inline
Returns
an expression of the coefficient wise quotient of *this and other
See also
MatrixBase::cwiseQuotient
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::ArrayBase< Derived >::operator/= (const ArrayBase< OtherDerived > & other)
replaces *this by *this / other coefficient wise.
Returns
a reference to *this
References Eigen::internal::call_assignment().
template<typename Derived> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived& Eigen::ArrayBase< Derived >::operator= (const ArrayBase< Derived > & other) inline
Special case of the template operator=, in order to prevent the compiler from generating a default operator= (issue hit with g++ 4.1)
template<typename Derived> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived& Eigen::ArrayBase< Derived >::operator= (const Scalar & value) inline
Set all the entries to value.
See also
DenseBase::setConstant(), DenseBase::fill()
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC const CwiseBinaryOp<internal::scalar_boolean_xor_op, const Derived, const OtherDerived> Eigen::ArrayBase< Derived >::operator^ (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > & other) const inline
Returns
an expression of the coefficient-wise < operator of *this and other
Example:
Output:
See also
all(), any(), operator>(), operator<=()
Returns
an expression of the coefficient-wise <= operator of *this and other
Example:
Output:
See also
all(), any(), operator>=(), operator<()
Returns
an expression of the coefficient-wise > operator of *this and other
Example:
Output:
See also
all(), any(), operator>=(), operator<()
Returns
an expression of the coefficient-wise >= operator of *this and other
Example:
Output:
See also
all(), any(), operator>(), operator<=()
Returns
an expression of the coefficient-wise == operator of *this and other
Warning
this performs an exact comparison, which is generally a bad idea with floating-point types. In order to check for equality between two vectors or matrices with floating-point coefficients, it is generally a far better idea to use a fuzzy comparison as provided by isApprox() and isMuchSmallerThan().
Example:
Output:
See also
all(), any(), isApprox(), isMuchSmallerThan()
Returns
an expression of the coefficient-wise != operator of *this and other
Warning
this performs an exact comparison, which is generally a bad idea with floating-point types. In order to check for equality between two vectors or matrices with floating-point coefficients, it is generally a far better idea to use a fuzzy comparison as provided by isApprox() and isMuchSmallerThan().
Example:
Output:
See also
all(), any(), isApprox(), isMuchSmallerThan()
Returns
an expression of the coefficient-wise ^ operator of *this and other
Warning
this operator is for expression of bool only.
Example:
Output:
See also
operator&&(), select()
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC const CwiseBinaryOp<internal::scalar_boolean_or_op, const Derived, const OtherDerived> Eigen::ArrayBase< Derived >::operator|| (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > & other) const inline
Returns
an expression of the coefficient-wise boolean or operator of *this and other
Warning
this operator is for expression of bool only.
Example:
Output:
See also
operator&&(), select()
template<typename Derived> EIGEN_DEVICE_FUNC const RoundReturnType Eigen::ArrayBase< Derived >::round () const inline
Returns
an expression of the coefficient-wise round of *this.
Example:
Output:
See also
Math functions, ceil(), floor()
template<typename Derived> EIGEN_DEVICE_FUNC const RsqrtReturnType Eigen::ArrayBase< Derived >::rsqrt () const inline
Returns
an expression of the coefficient-wise inverse square root of *this.
This function computes the coefficient-wise inverse square root.
Example:
Output:
See also
pow(), square()
template<typename Derived> EIGEN_DEVICE_FUNC const SignReturnType Eigen::ArrayBase< Derived >::sign () const inline
Returns
an expression of the coefficient-wise signum of *this.
This function computes the coefficient-wise signum.
Example:
Output:
See also
pow(), square()
template<typename Derived> EIGEN_DEVICE_FUNC const SinReturnType Eigen::ArrayBase< Derived >::sin () const inline
Returns
an expression of the coefficient-wise sine of *this.
This function computes the coefficient-wise sine. The function MatrixBase::sin() in the unsupported module MatrixFunctions computes the matrix sine.
Example:
Output:
See also
Math functions, cos(), asin()
template<typename Derived> EIGEN_DEVICE_FUNC const SinhReturnType Eigen::ArrayBase< Derived >::sinh () const inline
Returns
an expression of the coefficient-wise hyperbolic sin of *this.
Example:
Output:
See also
Math functions, sin(), tanh(), cosh()
template<typename Derived> EIGEN_DEVICE_FUNC const SqrtReturnType Eigen::ArrayBase< Derived >::sqrt () const inline
Returns
an expression of the coefficient-wise square root of *this.
This function computes the coefficient-wise square root. The function MatrixBase::sqrt() in the unsupported module MatrixFunctions computes the matrix square root.
Example:
Output:
See also
Math functions, pow(), square()
template<typename Derived> EIGEN_DEVICE_FUNC const SquareReturnType Eigen::ArrayBase< Derived >::square () const inline
Returns
an expression of the coefficient-wise square of *this.
Example:
Output:
See also
Math functions, abs2(), cube(), pow()
template<typename Derived> EIGEN_DEVICE_FUNC const TanReturnType Eigen::ArrayBase< Derived >::tan () const inline
Returns
an expression of the coefficient-wise tan of *this.
Example:
Output:
See also
Math functions, cos(), sin()
template<typename Derived> EIGEN_DEVICE_FUNC const TanhReturnType Eigen::ArrayBase< Derived >::tanh () const inline
Returns
an expression of the coefficient-wise hyperbolic tan of *this.
Example:
Output:
See also
Math functions, tan(), sinh(), cosh()
template<typename Derived> template<typename DerivedQ > const CwiseBinaryOp<internal::scalar_zeta_op<Scalar>, const Derived, const DerivedQ> Eigen::ArrayBase< Derived >::zeta (const EIGEN_CURRENT_STORAGE_BASE_CLASS< DerivedQ > & q) const inline
Returns
an expression of the coefficient-wise zeta function.
It returns the Riemann zeta function of two arguments *this and q:
Parameters
*this is the exposent, it must be > 1
q is the shift, it must be > 0
Note
This function supports only float and double scalar types. To support other scalar types, the user has to provide implementations of zeta(T,T) for any scalar type T to be supported.
This method is an alias for zeta(*this,q);
See also
Eigen::zeta()
Friends And Related Function Documentation
template<typename Derived , typename ScalarExponent > #define EIGEN_MSVC10_WORKAROUND_BINARYOP_RETURN_TYPE (const EIGEN_EXPR_BINARYOP_SCALAR_RETURN_TYPEDerived, typename internal::promote_scalar_arg< typename Derived::ScalarEIGEN_COMMA ScalarExponent EIGEN_COMMAEIGEN_SCALAR_BINARY_SUPPORTED(pow, typename Derived::Scalar, ScalarExponent)>::type, pow) const X related
Returns
an expression of the coefficient-wise power of x to the given constant exponent.
Template Parameters
ScalarExponent is the scalar type of exponent. It must be compatible with the scalar type of the given expression (Derived::Scalar).
See also
ArrayBase::pow()
template<typename Scalar , typename Derived > #define EIGEN_MSVC10_WORKAROUND_BINARYOP_RETURN_TYPE (const EIGEN_SCALAR_BINARYOP_EXPR_RETURN_TYPEtypename internal::promote_scalar_arg< typename Derived::ScalarEIGEN_COMMA Scalar EIGEN_COMMAEIGEN_SCALAR_BINARY_SUPPORTED(pow, Scalar, typename Derived::Scalar)>::type, Derived, pow) const X related
Returns
an expression of the coefficient-wise power of the scalar x to the given array of exponents.
This function computes the coefficient-wise power between a scalar and an array of exponents.
Template Parameters
Scalar is the scalar type of x. It must be compatible with the scalar type of the given array expression (Derived::Scalar).
Example:
Output:
See also
ArrayBase::pow()
template<typename Derived , typename ExponentDerived > const Eigen::CwiseBinaryOp< Eigen::internal::scalar_pow_op< typename Derived::Scalar, typename ExponentDerived::Scalar >, const Derived, const ExponentDerived > pow (const Eigen::ArrayBase< Derived > & x, const Eigen::ArrayBase< ExponentDerived > & exponents) related
Returns
an expression of the coefficient-wise power of x to the given array of exponents.
This function computes the coefficient-wise power.
Example:
Output:
See also
ArrayBase::pow()
References EIGEN_COMMA, EIGEN_SCALAR_BINARY_SUPPORTED, EIGEN_SCALAR_BINARYOP_EXPR_RETURN_TYPE, Eigen::half_impl::pow(), and type.
Referenced by operator/().
The documentation for this class was generated from the following files:
ArrayBase.h
GlobalFunctions.h
SelfCwiseBinaryOp.h