SmartMouse_2018: std::deque< T, EIGEN_ALIGNED_ALLOCATOR< T > > Class Template Reference
std::deque< T, EIGEN_ALIGNED_ALLOCATOR< T > > Class Template Reference
#include <StdDeque.h>
Private Types
typedef deque< EIGEN_WORKAROUND_MSVC_STL_SUPPORT(T), Eigen::aligned_allocator_indirection< EIGEN_WORKAROUND_MSVC_STL_SUPPORT(T)> > deque_base
Private Member Functions
EIGEN_STD_DEQUE_SPECIALIZATION_BODY void resize (size_type new_size)
void resize (size_type new_size, const value_type &x)
Member Typedef Documentation
template<typename T > typedef deque<EIGEN_WORKAROUND_MSVC_STL_SUPPORT(T), Eigen::aligned_allocator_indirection<EIGEN_WORKAROUND_MSVC_STL_SUPPORT(T)> > std::deque< T, EIGEN_ALIGNED_ALLOCATOR< T > >::deque_base private
Member Function Documentation
template<typename T > EIGEN_STD_DEQUE_SPECIALIZATION_BODY void std::deque< T, EIGEN_ALIGNED_ALLOCATOR< T > >::resize (size_type new_size) inline private
References Eigen::placeholders::end(), and Eigen::internal::size().
template<typename T > void std::deque< T, EIGEN_ALIGNED_ALLOCATOR< T > >::resize (size_type new_size, const value_type & x) inline private
References Eigen::placeholders::end(), and Eigen::internal::size().
The documentation for this class was generated from the following file:
StdDeque.h