SmartMouse_2018: Eigen::Diagonal< MatrixType, _DiagIndex > Class Template Reference
Eigen::Diagonal< MatrixType, _DiagIndex > Class Template Reference
Expression of a diagonal/subdiagonal/superdiagonal in a matrix.
#include <Diagonal.h>
Public Types
enum { DiagIndex = _DiagIndex }
typedef internal::dense_xpr_base< Diagonal >::type Base
typedef internal::conditional< internal::is_lvalue< MatrixType >::value, Scalar, const Scalar >::type ScalarWithConstIfNotLvalue
Public Member Functions
EIGEN_DEVICE_FUNC Diagonal (MatrixType &matrix, Index a_index=DiagIndex)
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
EIGEN_DEVICE_FUNC Index innerStride () const
EIGEN_DEVICE_FUNC Index outerStride () const
EIGEN_DEVICE_FUNC ScalarWithConstIfNotLvalue * data ()
EIGEN_DEVICE_FUNC const Scalar * data () const
EIGEN_DEVICE_FUNC Scalar & coeffRef (Index row, Index)
EIGEN_DEVICE_FUNC const Scalar & coeffRef (Index row, Index) const
EIGEN_DEVICE_FUNC CoeffReturnType coeff (Index row, Index) const
EIGEN_DEVICE_FUNC Scalar & coeffRef (Index idx)
EIGEN_DEVICE_FUNC const Scalar & coeffRef (Index idx) const
EIGEN_DEVICE_FUNC CoeffReturnType coeff (Index idx) const
EIGEN_DEVICE_FUNC const internal::remove_all< typename MatrixType::Nested >::type & nestedExpression () const
EIGEN_DEVICE_FUNC Index index () const
Protected Attributes
internal::ref_selector< MatrixType >::non_const_type m_matrix
const internal::variable_if_dynamicindex< Index, DiagIndex > m_index
Private Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index absDiagIndex () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index rowOffset () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index colOffset () const
template<int LoadMode>
MatrixType::PacketReturnType packet (Index) const
template<int LoadMode>
MatrixType::PacketReturnType packet (Index, Index) const
Detailed Description
template<typename MatrixType, int _DiagIndex>
class Eigen::Diagonal< MatrixType, _DiagIndex >
Expression of a diagonal/subdiagonal/superdiagonal in a matrix.
Parameters
MatrixType the type of the object in which we are taking a sub/main/super diagonal
DiagIndex the index of the sub/super diagonal. The default is 0 and it means the main diagonal. A positive value means a superdiagonal, a negative value means a subdiagonal. You can also use DynamicIndex so the index can be set at runtime.
The matrix is not required to be square.
This class represents an expression of the main diagonal, or any sub/super diagonal of a square matrix. It is the return type of MatrixBase::diagonal() and MatrixBase::diagonal(Index) and most of the time this is the only way it is used.
See also
MatrixBase::diagonal(), MatrixBase::diagonal(Index)
Member Typedef Documentation
template<typename MatrixType, int _DiagIndex> typedef internal::dense_xpr_base<Diagonal>::type Eigen::Diagonal< MatrixType, _DiagIndex >::Base
template<typename MatrixType, int _DiagIndex> typedef internal::conditional< internal::is_lvalue<MatrixType>::value, Scalar, const Scalar >::type Eigen::Diagonal< MatrixType, _DiagIndex >::ScalarWithConstIfNotLvalue
Member Enumeration Documentation
template<typename MatrixType, int _DiagIndex> anonymous enum
Enumerator
DiagIndex
Constructor & Destructor Documentation
template<typename MatrixType, int _DiagIndex> EIGEN_DEVICE_FUNC Eigen::Diagonal< MatrixType, _DiagIndex >::Diagonal (MatrixType & matrix, Index a_index = DiagIndex) inline explicit
References EIGEN_INHERIT_ASSIGNMENT_OPERATORS.
Member Function Documentation
template<typename MatrixType, int _DiagIndex> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::Diagonal< MatrixType, _DiagIndex >::absDiagIndex () const inline private
References Eigen::internal::variable_if_dynamicindex< T, Value >::value().
template<typename MatrixType, int _DiagIndex> EIGEN_DEVICE_FUNC CoeffReturnType Eigen::Diagonal< MatrixType, _DiagIndex >::coeff (Index row, Index) const inline
template<typename MatrixType, int _DiagIndex> EIGEN_DEVICE_FUNC CoeffReturnType Eigen::Diagonal< MatrixType, _DiagIndex >::coeff (Index idx) const inline
template<typename MatrixType, int _DiagIndex> EIGEN_DEVICE_FUNC Scalar& Eigen::Diagonal< MatrixType, _DiagIndex >::coeffRef (Index row, Index) inline
References EIGEN_STATIC_ASSERT_LVALUE.
template<typename MatrixType, int _DiagIndex> EIGEN_DEVICE_FUNC const Scalar& Eigen::Diagonal< MatrixType, _DiagIndex >::coeffRef (Index row, Index) const inline
template<typename MatrixType, int _DiagIndex> EIGEN_DEVICE_FUNC Scalar& Eigen::Diagonal< MatrixType, _DiagIndex >::coeffRef (Index idx) inline
References EIGEN_STATIC_ASSERT_LVALUE.
template<typename MatrixType, int _DiagIndex> EIGEN_DEVICE_FUNC const Scalar& Eigen::Diagonal< MatrixType, _DiagIndex >::coeffRef (Index idx) const inline
template<typename MatrixType, int _DiagIndex> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::Diagonal< MatrixType, _DiagIndex >::colOffset () const inline private
References Eigen::internal::variable_if_dynamicindex< T, Value >::value().
template<typename MatrixType, int _DiagIndex> EIGEN_DEVICE_FUNC Index Eigen::Diagonal< MatrixType, _DiagIndex >::cols (void) const inline
Referenced by Eigen::internal::trmv_selector< Mode, RowMajor >::run(), and Eigen::internal::gemv_dense_selector< OnTheRight, RowMajor, true >::run().
template<typename MatrixType, int _DiagIndex> EIGEN_DEVICE_FUNC ScalarWithConstIfNotLvalue* Eigen::Diagonal< MatrixType, _DiagIndex >::data () inline
Referenced by Eigen::internal::trmv_selector< Mode, RowMajor >::run(), and Eigen::internal::gemv_dense_selector< OnTheRight, RowMajor, true >::run().
template<typename MatrixType, int _DiagIndex> EIGEN_DEVICE_FUNC const Scalar* Eigen::Diagonal< MatrixType, _DiagIndex >::data () const inline
template<typename MatrixType, int _DiagIndex> EIGEN_DEVICE_FUNC Index Eigen::Diagonal< MatrixType, _DiagIndex >::index () const inline
template<typename MatrixType, int _DiagIndex> EIGEN_DEVICE_FUNC Index Eigen::Diagonal< MatrixType, _DiagIndex >::innerStride () const inline
template<typename MatrixType, int _DiagIndex> EIGEN_DEVICE_FUNC const internal::remove_all<typename MatrixType::Nested>::type& Eigen::Diagonal< MatrixType, _DiagIndex >::nestedExpression () const inline
template<typename MatrixType, int _DiagIndex> EIGEN_DEVICE_FUNC Index Eigen::Diagonal< MatrixType, _DiagIndex >::outerStride () const inline
Referenced by Eigen::internal::trmv_selector< Mode, RowMajor >::run(), and Eigen::internal::gemv_dense_selector< OnTheRight, RowMajor, true >::run().
template<typename MatrixType, int _DiagIndex> template<int LoadMode> MatrixType::PacketReturnType Eigen::Diagonal< MatrixType, _DiagIndex >::packet (Index) const private
template<typename MatrixType, int _DiagIndex> template<int LoadMode> MatrixType::PacketReturnType Eigen::Diagonal< MatrixType, _DiagIndex >::packet (Index , Index) const private
template<typename MatrixType, int _DiagIndex> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::Diagonal< MatrixType, _DiagIndex >::rowOffset () const inline private
References Eigen::internal::variable_if_dynamicindex< T, Value >::value().
template<typename MatrixType, int _DiagIndex> EIGEN_DEVICE_FUNC Index Eigen::Diagonal< MatrixType, _DiagIndex >::rows (void) const inline
Referenced by Eigen::internal::trmv_selector< Mode, RowMajor >::run(), and Eigen::internal::gemv_dense_selector< OnTheRight, RowMajor, true >::run().
Member Data Documentation
template<typename MatrixType, int _DiagIndex> const internal::variable_if_dynamicindex<Index, DiagIndex> Eigen::Diagonal< MatrixType, _DiagIndex >::m_index protected
template<typename MatrixType, int _DiagIndex> internal::ref_selector<MatrixType>::non_const_type Eigen::Diagonal< MatrixType, _DiagIndex >::m_matrix protected
The documentation for this class was generated from the following file:
Diagonal.h