SmartMouse_2018: Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true > Class Template Reference
Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true > Class Template Reference
#include <JacobiSVD.h>
Public Types
enum {
RowsAtCompileTime = MatrixType::RowsAtCompileTime, ColsAtCompileTime = MatrixType::ColsAtCompileTime, MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime, MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime,
Options = MatrixType::Options
}
typedef MatrixType::Scalar Scalar
typedef Matrix< Scalar, ColsAtCompileTime, RowsAtCompileTime, Options, MaxColsAtCompileTime, MaxRowsAtCompileTime > TransposeTypeWithSameStorageOrder
Public Member Functions
void allocate (const JacobiSVD< MatrixType, HouseholderQRPreconditioner > &svd)
bool run (JacobiSVD< MatrixType, HouseholderQRPreconditioner > &svd, const MatrixType &matrix)
Private Types
typedef HouseholderQR< TransposeTypeWithSameStorageOrder > QRType
Private Attributes
QRType m_qr
TransposeTypeWithSameStorageOrder m_adjoint
internal::plain_row_type< MatrixType >::type m_workspace
Member Typedef Documentation
template<typename MatrixType > typedef HouseholderQR<TransposeTypeWithSameStorageOrder> Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::QRType private
template<typename MatrixType > typedef MatrixType::Scalar Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::Scalar
template<typename MatrixType > typedef Matrix<Scalar, ColsAtCompileTime, RowsAtCompileTime, Options, MaxColsAtCompileTime, MaxRowsAtCompileTime> Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::TransposeTypeWithSameStorageOrder
Member Enumeration Documentation
template<typename MatrixType > anonymous enum
Enumerator
RowsAtCompileTime
ColsAtCompileTime
MaxRowsAtCompileTime
MaxColsAtCompileTime
Options
Member Function Documentation
template<typename MatrixType > void Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::allocate (const JacobiSVD< MatrixType, HouseholderQRPreconditioner > & svd) inline
References Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::cols(), Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::m_computeFullV, Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::m_computeThinV, and Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::rows().
template<typename MatrixType > bool Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run (JacobiSVD< MatrixType, HouseholderQRPreconditioner > & svd, const MatrixType & matrix) inline
References Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::computeU(), Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::m_computeFullV, Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::m_computeThinV, Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::m_matrixU, Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::m_matrixV, and Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::m_workMatrix.
Member Data Documentation
template<typename MatrixType > TransposeTypeWithSameStorageOrder Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::m_adjoint private
template<typename MatrixType > QRType Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::m_qr private
template<typename MatrixType > internal::plain_row_type<MatrixType>::type Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::m_workspace private
The documentation for this class was generated from the following file:
JacobiSVD.h