SmartMouse_2018: Stop Class Reference
Stop Class Reference
#include <Stop.h>
Public Member Functions
Stop ()
Stop (unsigned long stop_time)
void initialize ()
run once in the first iteration of the command's life. this will be overrided by individual commands
bool isFinished ()
checked every iteration to see if we're done here. this will be overrided by individual commands
void end ()
called once at the end, once isFinished() returned true. this will be overrided by individual commands.
Stop ()
Stop (unsigned long stop_time)
void initialize ()
run once in the first iteration of the command's life. this will be overrided by individual commands
void execute ()
stuff to do over and over each iteration. this will be overrided by individual commands
bool isFinished ()
checked every iteration to see if we're done here. this will be overrided by individual commands
void end ()
called once at the end, once isFinished() returned true. this will be overrided by individual commands.
Stop (unsigned long stop_time)
Stop ()
void initialize ()
run once in the first iteration of the command's life. this will be overrided by individual commands
void execute ()
stuff to do over and over each iteration. this will be overrided by individual commands
bool isFinished ()
checked every iteration to see if we're done here. this will be overrided by individual commands
void end ()
called once at the end, once isFinished() returned true. this will be overrided by individual commands.
Public Member Functions inherited from Command
Command ()
Command (const char *name)
virtual ~Command ()
void setTimeout (unsigned long timeout)
unsigned long getTime ()
bool isTimedOut ()
virtual void _initialize ()
virtual void _execute ()
virtual void _end ()
bool cycle ()
actually does the excuting.
bool isRunning ()
check if the command is running.
bool operator!= (const Command &other)
comparator overload for !=. used when checking if command is in list
Private Attributes
unsigned long stop_time
SimMouse * mouse
double initial_velocity
unsigned long stop_time_ms = 500
ConsoleMouse * mouse
Additional Inherited Members
Static Public Member Functions inherited from Command
static void setTimerImplementation (TimerInterface *timer)
static TimerInterface * getTimerImplementation ()
Public Attributes inherited from Command
bool inParallel
used by command group to organize commands
const char * name
for convenient printing
bool initialized
bool running
unsigned long timeout
unsigned long startTime
Static Public Attributes inherited from Command
static TimerInterface * timer
Constructor & Destructor Documentation
Stop::Stop ()
Stop::Stop (unsigned long stop_time)
Stop::Stop ()
Stop::Stop (unsigned long stop_time)
Stop::Stop (unsigned long stop_time)
Stop::Stop ()
Member Function Documentation
void Stop::end () virtual
called once at the end, once isFinished() returned true. this will be overrided by individual commands.
Reimplemented from Command.
References RealMouse::LED_7.
Referenced by execute().
void Stop::end () virtual
called once at the end, once isFinished() returned true. this will be overrided by individual commands.
Reimplemented from Command.
void Stop::end () virtual
called once at the end, once isFinished() returned true. this will be overrided by individual commands.
Reimplemented from Command.
void Stop::execute () virtual
stuff to do over and over each iteration. this will be overrided by individual commands
Reimplemented from Command.
References end(), isFinished(), Command::isTimedOut(), mouse, and SimMouse::setSpeedCps().
void Stop::execute () virtual
stuff to do over and over each iteration. this will be overrided by individual commands
Reimplemented from Command.
void Stop::initialize () virtual
run once in the first iteration of the command's life. this will be overrided by individual commands
Reimplemented from Command.
References RealMouse::inst(), RealMouse::LED_7, RealMouse::setSpeedCps(), Command::setTimeout(), and stop_time.
void Stop::initialize () virtual
run once in the first iteration of the command's life. this will be overrided by individual commands
Reimplemented from Command.
void Stop::initialize () virtual
run once in the first iteration of the command's life. this will be overrided by individual commands
Reimplemented from Command.
bool Stop::isFinished () virtual
checked every iteration to see if we're done here. this will be overrided by individual commands
Returns
is the function finished
Implements Command.
References Command::isTimedOut().
Referenced by execute().
bool Stop::isFinished () virtual
checked every iteration to see if we're done here. this will be overrided by individual commands
Returns
is the function finished
Implements Command.
bool Stop::isFinished () virtual
checked every iteration to see if we're done here. this will be overrided by individual commands
Returns
is the function finished
Implements Command.
Member Data Documentation
double Stop::initial_velocity private
SimMouse* Stop::mouse private
Referenced by execute().
ConsoleMouse* Stop::mouse private
unsigned long Stop::stop_time private
Referenced by initialize().
unsigned long Stop::stop_time_ms = 500 private
The documentation for this class was generated from the following files:
real/commands/Stop.h
real/commands/Stop.cpp