SmartMouse_2018: ArgumentParser Class Reference
ArgumentParser Class Reference
A simple command-line argument parser based on the design of python's parser of the same name.
#include <argparse.hpp>
Classes
class Any
struct Argument
Public Member Functions
ArgumentParser ()
void appName (const String &name)
void addArgument (const String &name, char nargs=0, bool optional=true)
void addArgument (const String &short_name, const String &name, char nargs=0, bool optional=true)
void addFinalArgument (const String &name, char nargs=1, bool optional=false)
void ignoreFirstArgument (bool ignore_first)
String verify (const String &name)
void parse (size_t argc, const char **argv)
void parse (const StringVector &argv)
template<typename T >
T retrieve (const String &name)
template<typename T >
T retrieve2 (const String &name)
String usage ()
void useExceptions (bool state)
bool empty () const
void clear ()
bool exists (const String &name) const
size_t count (const String &name)
Private Types
typedef std::string String
typedef std::vector< Any > AnyVector
typedef std::vector< String > StringVector
typedef std::vector< Argument > ArgumentVector
Private Member Functions
void insertArgument (const Argument &arg)
void argumentError (const std::string &msg, bool show_usage=false)
Static Private Member Functions
static String delimit (const String &name)
static String strip (const String &name)
static String upper (const String &in)
static String escape (const String &in)
Private Attributes
IndexMap index_
bool ignore_first_
bool use_exceptions_
size_t required_
String app_name_
String final_name_
ArgumentVector arguments_
AnyVector variables_
Detailed Description
A simple command-line argument parser based on the design of python's parser of the same name.
ArgumentParser is a simple C++ class that can parse arguments from the command-line or any array of strings. The syntax is familiar to anyone who has used python's ArgumentParser:
// create a parser and add the options
ArgumentParser parser;
parser.addArgument("-n", "--name");
parser.addArgument("--inputs", '+');
// parse the command-line arguments
parser.parse(argc, argv);
// get the inputs and iterate over them
string name = parser.retrieve("name");
vector<string> inputs = parser.retrieve<vector<string>>("inputs");
Member Typedef Documentation
typedef std::vector<Any> ArgumentParser::AnyVector private
typedef std::vector<Argument> ArgumentParser::ArgumentVector private
typedef std::string ArgumentParser::String private
typedef std::vector<String> ArgumentParser::StringVector private
Constructor & Destructor Documentation
ArgumentParser::ArgumentParser () inline
Member Function Documentation
void ArgumentParser::addArgument (const String & name, char nargs = 0, bool optional = true) inline
References arg(), insertArgument(), and verify().
void ArgumentParser::addArgument (const String & short_name, const String & name, char nargs = 0, bool optional = true) inline
References arg(), insertArgument(), and verify().
void ArgumentParser::addFinalArgument (const String & name, char nargs = 1, bool optional = false) inline
References arg(), delimit(), and insertArgument().
void ArgumentParser::appName (const String & name) inline
void ArgumentParser::argumentError (const std::string & msg, bool show_usage = false) inline private
References usage(), and use_exceptions_.
Referenced by parse(), and verify().
void ArgumentParser::clear () inline
size_t ArgumentParser::count (const String & name) inline
References arg(), ArgumentParser::Any::castTo(), delimit(), empty(), ArgumentParser::Argument::fixed, N, and Eigen::internal::size().
static String ArgumentParser::delimit (const String & name) inline static private
References Eigen::half_impl::min().
Referenced by addFinalArgument(), count(), exists(), and retrieve().
bool ArgumentParser::empty () const inline
Referenced by count().
static String ArgumentParser::escape (const String & in) inline static private
Referenced by usage().
bool ArgumentParser::exists (const String & name) const inline
References delimit().
void ArgumentParser::ignoreFirstArgument (bool ignore_first) inline
void ArgumentParser::insertArgument (const Argument & arg) inline private
References arguments_, ArgumentParser::Argument::fixed, ArgumentParser::Argument::fixed_nargs, if(), index_, N, ArgumentParser::Argument::name, ArgumentParser::Argument::optional, required_, ArgumentParser::Argument::short_name, and variables_.
Referenced by addArgument(), and addFinalArgument().
void ArgumentParser::parse (size_t argc, const char ** argv) inline
References parse().
Referenced by parse().
void ArgumentParser::parse (const StringVector & argv) inline
References argumentError(), ArgumentParser::Argument::canonicalName(), final_name_, ArgumentParser::Argument::fixed, ArgumentParser::Argument::fixed_nargs, ignore_first_, in, Eigen::half_impl::max(), ArgumentParser::Argument::optional, and ArgumentParser::Argument::variable_nargs.
template<typename T > T ArgumentParser::retrieve (const String & name) inline
References delimit(), and N.
template<typename T > T ArgumentParser::retrieve2 (const String & name) inline
static String ArgumentParser::strip (const String & name) inline static private
Referenced by ArgumentParser::Argument::toString().
static String ArgumentParser::upper (const String & in) inline static private
Referenced by ArgumentParser::Argument::toString().
String ArgumentParser::usage () inline
References arg(), escape(), final_name_, help(), it, ArgumentParser::Argument::name, ArgumentParser::Argument::optional, and ArgumentParser::Argument::toString().
Referenced by argumentError().
void ArgumentParser::useExceptions (bool state) inline
String ArgumentParser::verify (const String & name) inline
References argumentError().
Referenced by addArgument().
Member Data Documentation
String ArgumentParser::app_name_ private
ArgumentVector ArgumentParser::arguments_ private
Referenced by insertArgument().
String ArgumentParser::final_name_ private
Referenced by parse(), and usage().
bool ArgumentParser::ignore_first_ private
Referenced by parse().
IndexMap ArgumentParser::index_ private
Referenced by insertArgument().
size_t ArgumentParser::required_ private
Referenced by insertArgument().
bool ArgumentParser::use_exceptions_ private
Referenced by argumentError().
AnyVector ArgumentParser::variables_ private
Referenced by insertArgument().
The documentation for this class was generated from the following file:
argparse.hpp