SmartMouse_2018: Eigen::internal::CompressedStorage< _Scalar, _StorageIndex > Class Template Reference
Eigen::internal::CompressedStorage< _Scalar, _StorageIndex > Class Template Reference
#include <CompressedStorage.h>
Public Types
typedef _Scalar Scalar
typedef _StorageIndex StorageIndex
Public Member Functions
CompressedStorage ()
CompressedStorage (Index size)
CompressedStorage (const CompressedStorage &other)
CompressedStorage & operator= (const CompressedStorage &other)
void swap (CompressedStorage &other)
~CompressedStorage ()
void reserve (Index size)
void squeeze ()
void resize (Index size, double reserveSizeFactor=0)
void append (const Scalar &v, Index i)
Index size () const
Index allocatedSize () const
void clear ()
const Scalar * valuePtr () const
Scalar * valuePtr ()
const StorageIndex * indexPtr () const
StorageIndex * indexPtr ()
Scalar & value (Index i)
const Scalar & value (Index i) const
StorageIndex & index (Index i)
const StorageIndex & index (Index i) const
Index searchLowerIndex (Index key) const
Index searchLowerIndex (Index start, Index end, Index key) const
Scalar at (Index key, const Scalar &defaultValue=Scalar(0)) const
Scalar atInRange (Index start, Index end, Index key, const Scalar &defaultValue=Scalar(0)) const
Scalar & atWithInsertion (Index key, const Scalar &defaultValue=Scalar(0))
void prune (const Scalar &reference, const RealScalar &epsilon=NumTraits< RealScalar >::dummy_precision())
Protected Types
typedef NumTraits< Scalar >::Real RealScalar
Protected Member Functions
void reallocate (Index size)
Protected Attributes
Scalar * m_values
StorageIndex * m_indices
Index m_size
Index m_allocatedSize
Member Typedef Documentation
template<typename _Scalar, typename _StorageIndex> typedef NumTraits<Scalar>::Real Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::RealScalar protected
template<typename _Scalar, typename _StorageIndex> typedef _Scalar Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::Scalar
template<typename _Scalar, typename _StorageIndex> typedef _StorageIndex Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::StorageIndex
Constructor & Destructor Documentation
template<typename _Scalar, typename _StorageIndex> Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::CompressedStorage () inline
template<typename _Scalar, typename _StorageIndex> Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::CompressedStorage (Index size) inline explicit
template<typename _Scalar, typename _StorageIndex> Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::CompressedStorage (const CompressedStorage< _Scalar, _StorageIndex > & other) inline
template<typename _Scalar, typename _StorageIndex> Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::~CompressedStorage () inline
Member Function Documentation
template<typename _Scalar, typename _StorageIndex> Index Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::allocatedSize () const inline
Referenced by Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insert(), and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertCompressed().
template<typename _Scalar, typename _StorageIndex> void Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::append (const Scalar & v, Index i) inline
Referenced by Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insert(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::insertBackByOuterInner(), and Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::insertBackByOuterInnerUnordered().
template<typename _Scalar, typename _StorageIndex> Scalar Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::at (Index key, const Scalar & defaultValue = Scalar(0)) const inline
Returns
the stored value at index key If the value does not exist, then the value defaultValue is returned without any insertion.
template<typename _Scalar, typename _StorageIndex> Scalar Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::atInRange (Index start, Index end, Index key, const Scalar & defaultValue = Scalar(0)) const inline
Like at(), but the search is performed in the range [start,end)
Referenced by Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::coeff().
template<typename _Scalar, typename _StorageIndex> Scalar& Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::atWithInsertion (Index key, const Scalar & defaultValue = Scalar(0)) inline
Returns
a reference to the value at index key If the value does not exist, then the value defaultValue is inserted such that the keys are sorted.
template<typename _Scalar, typename _StorageIndex> void Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::clear () inline
Referenced by Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::resize(), and Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::setZero().
template<typename _Scalar, typename _StorageIndex> StorageIndex& Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::index (Index i) inline
Referenced by Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::coeffRef(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::collapseDuplicates(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::conservativeResize(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insert(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::insertBackByOuterInner(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::insertBackUncompressed(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertCompressed(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertUncompressed(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::makeCompressed(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::prune(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::prune(), and Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::reserveInnerVectors().
template<typename _Scalar, typename _StorageIndex> const StorageIndex& Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::index (Index i) const inline
template<typename _Scalar, typename _StorageIndex> const StorageIndex* Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::indexPtr () const inline
Referenced by Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::innerIndexPtr(), and Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::setIdentity().
template<typename _Scalar, typename _StorageIndex> StorageIndex* Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::indexPtr () inline
template<typename _Scalar, typename _StorageIndex> CompressedStorage& Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::operator= (const CompressedStorage< _Scalar, _StorageIndex > & other) inline
template<typename _Scalar, typename _StorageIndex> void Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::prune (const Scalar & reference, const RealScalar & epsilon = NumTraits<RealScalar>::dummy_precision()) inline
template<typename _Scalar, typename _StorageIndex> void Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::reallocate (Index size) inline protected
Referenced by Eigen::internal::CompressedStorage< Scalar, StorageIndex >::reserve(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::resize(), and Eigen::internal::CompressedStorage< Scalar, StorageIndex >::squeeze().
template<typename _Scalar, typename _StorageIndex> void Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::reserve (Index size) inline
Referenced by Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insert(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertCompressed(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::reserve(), and Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::reserveInnerVectors().
template<typename _Scalar, typename _StorageIndex> void Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::resize (Index size, double reserveSizeFactor = 0) inline
Referenced by Eigen::internal::CompressedStorage< Scalar, StorageIndex >::append(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::collapseDuplicates(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::CompressedStorage(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insert(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertCompressed(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::makeCompressed(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::operator=(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::prune(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::prune(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::reserveInnerVectors(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::resizeNonZeros(), and Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::setIdentity().
template<typename _Scalar, typename _StorageIndex> Index Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::searchLowerIndex (Index key) const inline
Returns
the largest k such that for all j in [0,k) index[j]<key
Referenced by Eigen::internal::CompressedStorage< Scalar, StorageIndex >::at(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::atInRange(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::atWithInsertion(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::coeffRef(), and Eigen::internal::CompressedStorage< Scalar, StorageIndex >::searchLowerIndex().
template<typename _Scalar, typename _StorageIndex> Index Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::searchLowerIndex (Index start, Index end, Index key) const inline
Returns
the largest k in [start,end) such that for all j in [start,k) index[j]<key
template<typename _Scalar, typename _StorageIndex> Index Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::size () const inline
Referenced by Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::finalize(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insert(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::insertBackByOuterInner(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertCompressed(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::operator=(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::prune(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::reallocate(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::reserve(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::resize(), and Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::startVec().
template<typename _Scalar, typename _StorageIndex> void Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::squeeze () inline
Referenced by Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::makeCompressed().
template<typename _Scalar, typename _StorageIndex> void Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::swap (CompressedStorage< _Scalar, _StorageIndex > & other) inline
Referenced by Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::swap().
template<typename _Scalar, typename _StorageIndex> Scalar& Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::value (Index i) inline
Referenced by Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::coeffRef(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::collapseDuplicates(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insert(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::insertBackByOuterInner(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::insertBackByOuterInnerUnordered(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::insertBackUncompressed(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertCompressed(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertUncompressed(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::makeCompressed(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::prune(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::prune(), and Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::reserveInnerVectors().
template<typename _Scalar, typename _StorageIndex> const Scalar& Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::value (Index i) const inline
template<typename _Scalar, typename _StorageIndex> const Scalar* Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::valuePtr () const inline
Referenced by Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::setIdentity(), and Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::valuePtr().
template<typename _Scalar, typename _StorageIndex> Scalar* Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::valuePtr () inline
Member Data Documentation
template<typename _Scalar, typename _StorageIndex> Index Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_allocatedSize protected
Referenced by Eigen::internal::CompressedStorage< Scalar, StorageIndex >::allocatedSize(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::atWithInsertion(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::reallocate(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::reserve(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::resize(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::squeeze(), and Eigen::internal::CompressedStorage< Scalar, StorageIndex >::swap().
template<typename _Scalar, typename _StorageIndex> StorageIndex* Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_indices protected
Referenced by Eigen::internal::CompressedStorage< Scalar, StorageIndex >::append(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::at(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::atInRange(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::atWithInsertion(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::index(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::indexPtr(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::operator=(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::reallocate(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::searchLowerIndex(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::swap(), and Eigen::internal::CompressedStorage< Scalar, StorageIndex >::~CompressedStorage().
template<typename _Scalar, typename _StorageIndex> Index Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_size protected
Referenced by Eigen::internal::CompressedStorage< Scalar, StorageIndex >::append(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::at(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::atWithInsertion(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::clear(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::operator=(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::reallocate(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::reserve(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::resize(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::searchLowerIndex(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::size(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::squeeze(), and Eigen::internal::CompressedStorage< Scalar, StorageIndex >::swap().
template<typename _Scalar, typename _StorageIndex> Scalar* Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_values protected
Referenced by Eigen::internal::CompressedStorage< Scalar, StorageIndex >::append(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::at(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::atInRange(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::atWithInsertion(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::operator=(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::reallocate(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::swap(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::value(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::valuePtr(), and Eigen::internal::CompressedStorage< Scalar, StorageIndex >::~CompressedStorage().
The documentation for this class was generated from the following file:
CompressedStorage.h