SmartMouse_2018: Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options > Class Template Reference
Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options > Class Template Reference
#include <DenseStorage.h>
Public Member Functions
EIGEN_DEVICE_FUNC DenseStorage ()
EIGEN_DEVICE_FUNC DenseStorage (internal::constructor_without_unaligned_array_assert)
EIGEN_DEVICE_FUNC DenseStorage (const DenseStorage &other)
EIGEN_DEVICE_FUNC DenseStorage & operator= (const DenseStorage &other)
EIGEN_DEVICE_FUNC DenseStorage (Index size, Index rows, Index cols)
EIGEN_DEVICE_FUNC void swap (DenseStorage &other)
EIGEN_DEVICE_FUNC void conservativeResize (Index, Index, Index)
EIGEN_DEVICE_FUNC void resize (Index, Index, Index)
EIGEN_DEVICE_FUNC const T * data () const
EIGEN_DEVICE_FUNC T * data ()
Static Public Member Functions
static EIGEN_DEVICE_FUNC Index rows (void)
static EIGEN_DEVICE_FUNC Index cols (void)
Private Attributes
internal::plain_array< T, Size, _Options > m_data
Constructor & Destructor Documentation
template<typename T, int Size, int _Rows, int _Cols, int _Options> EIGEN_DEVICE_FUNC Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::DenseStorage () inline
template<typename T, int Size, int _Rows, int _Cols, int _Options> EIGEN_DEVICE_FUNC Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::DenseStorage (internal::constructor_without_unaligned_array_assert) inline explicit
template<typename T, int Size, int _Rows, int _Cols, int _Options> EIGEN_DEVICE_FUNC Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::DenseStorage (const DenseStorage< T, Size, _Rows, _Cols, _Options > & other) inline
template<typename T, int Size, int _Rows, int _Cols, int _Options> EIGEN_DEVICE_FUNC Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::DenseStorage (Index size, Index rows, Index cols) inline
Member Function Documentation
template<typename T, int Size, int _Rows, int _Cols, int _Options> static EIGEN_DEVICE_FUNC Index Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::cols (void) inline static
Referenced by Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::coeff(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::coeffRef(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::cols(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::packet(), and Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::writePacket().
template<typename T, int Size, int _Rows, int _Cols, int _Options> EIGEN_DEVICE_FUNC void Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::conservativeResize (Index , Index , Index) inline
template<typename T, int Size, int _Rows, int _Cols, int _Options> EIGEN_DEVICE_FUNC const T* Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::data () const inline
Referenced by Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_init1(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_init2(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::coeff(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::coeffRef(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::data(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::packet(), and Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::writePacket().
template<typename T, int Size, int _Rows, int _Cols, int _Options> EIGEN_DEVICE_FUNC T* Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::data () inline
template<typename T, int Size, int _Rows, int _Cols, int _Options> EIGEN_DEVICE_FUNC DenseStorage& Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::operator= (const DenseStorage< T, Size, _Rows, _Cols, _Options > & other) inline
template<typename T, int Size, int _Rows, int _Cols, int _Options> EIGEN_DEVICE_FUNC void Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::resize (Index , Index , Index) inline
Referenced by Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::resize().
template<typename T, int Size, int _Rows, int _Cols, int _Options> static EIGEN_DEVICE_FUNC Index Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::rows (void) inline static
Referenced by Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::coeff(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::coeffRef(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::packet(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::rows(), and Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::writePacket().
template<typename T, int Size, int _Rows, int _Cols, int _Options> EIGEN_DEVICE_FUNC void Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::swap (DenseStorage< T, Size, _Rows, _Cols, _Options > & other) inline
Referenced by Eigen::internal::matrix_swap_impl< MatrixTypeA, MatrixTypeB, true >::run().
Member Data Documentation
template<typename T, int Size, int _Rows, int _Cols, int _Options> internal::plain_array<T,Size,_Options> Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::m_data private
Referenced by Eigen::DenseStorage< T, Dynamic, Dynamic, Dynamic, _Options >::DenseStorage(), Eigen::DenseStorage< T, Dynamic, _Rows, Dynamic, _Options >::DenseStorage(), Eigen::DenseStorage< T, Dynamic, Dynamic, _Cols, _Options >::DenseStorage(), Eigen::DenseStorage< Scalar, Base::MaxSizeAtCompileTime, Base::RowsAtCompileTime, Base::ColsAtCompileTime, Options >::operator=(), Eigen::DenseStorage< T, Size, Dynamic, Dynamic, _Options >::operator=(), Eigen::DenseStorage< T, Size, Dynamic, _Cols, _Options >::operator=(), Eigen::DenseStorage< T, Size, _Rows, Dynamic, _Options >::operator=(), Eigen::DenseStorage< Scalar, Base::MaxSizeAtCompileTime, Base::RowsAtCompileTime, Base::ColsAtCompileTime, Options >::swap(), Eigen::DenseStorage< T, Size, Dynamic, Dynamic, _Options >::swap(), Eigen::DenseStorage< T, Size, Dynamic, _Cols, _Options >::swap(), Eigen::DenseStorage< T, Size, _Rows, Dynamic, _Options >::swap(), Eigen::DenseStorage< T, Dynamic, Dynamic, Dynamic, _Options >::swap(), Eigen::DenseStorage< T, Dynamic, _Rows, Dynamic, _Options >::swap(), and Eigen::DenseStorage< T, Dynamic, Dynamic, _Cols, _Options >::swap().
The documentation for this class was generated from the following file:
DenseStorage.h