SmartMouse_2018: Eigen::Symbolic::BaseExpr< Derived > Class Template Reference
Eigen::Symbolic::BaseExpr< Derived > Class Template Reference
#include <SymbolicIndex.h>
Public Member Functions
const Derived & derived () const
template<typename T >
Index eval (const T &values) const
NegateExpr< Derived > operator- () const
AddExpr< Derived, ValueExpr<> > operator+ (Index b) const
AddExpr< Derived, ValueExpr<> > operator- (Index a) const
ProductExpr< Derived, ValueExpr<> > operator* (Index a) const
QuotientExpr< Derived, ValueExpr<> > operator/ (Index a) const
template<int N>
AddExpr< Derived, ValueExpr< internal::FixedInt< N > > > operator+ (internal::FixedInt< N >) const
template<int N>
AddExpr< Derived, ValueExpr< internal::FixedInt<-N > > > operator- (internal::FixedInt< N >) const
template<int N>
ProductExpr< Derived, ValueExpr< internal::FixedInt< N > > > operator* (internal::FixedInt< N >) const
template<int N>
QuotientExpr< Derived, ValueExpr< internal::FixedInt< N > > > operator/ (internal::FixedInt< N >) const
template<int N>
AddExpr< Derived, ValueExpr< internal::FixedInt< N > > > operator+ (internal::FixedInt< N >(*)()) const
template<int N>
AddExpr< Derived, ValueExpr< internal::FixedInt<-N > > > operator- (internal::FixedInt< N >(*)()) const
template<int N>
ProductExpr< Derived, ValueExpr< internal::FixedInt< N > > > operator* (internal::FixedInt< N >(*)()) const
template<int N>
QuotientExpr< Derived, ValueExpr< internal::FixedInt< N > > > operator/ (internal::FixedInt< N >(*)()) const
template<typename OtherDerived >
AddExpr< Derived, OtherDerived > operator+ (const BaseExpr< OtherDerived > &b) const
template<typename OtherDerived >
AddExpr< Derived, NegateExpr< OtherDerived > > operator- (const BaseExpr< OtherDerived > &b) const
template<typename OtherDerived >
ProductExpr< Derived, OtherDerived > operator* (const BaseExpr< OtherDerived > &b) const
template<typename OtherDerived >
QuotientExpr< Derived, OtherDerived > operator/ (const BaseExpr< OtherDerived > &b) const
Friends
AddExpr< Derived, ValueExpr<> > operator+ (Index a, const BaseExpr &b)
AddExpr< NegateExpr< Derived >, ValueExpr<> > operator- (Index a, const BaseExpr &b)
ProductExpr< ValueExpr<>, Derived > operator* (Index a, const BaseExpr &b)
QuotientExpr< ValueExpr<>, Derived > operator/ (Index a, const BaseExpr &b)
template<int N>
AddExpr< Derived, ValueExpr< internal::FixedInt< N > > > operator+ (internal::FixedInt< N >, const BaseExpr &b)
template<int N>
AddExpr< NegateExpr< Derived >, ValueExpr< internal::FixedInt< N > > > operator- (internal::FixedInt< N >, const BaseExpr &b)
template<int N>
ProductExpr< ValueExpr< internal::FixedInt< N > >, Derived > operator* (internal::FixedInt< N >, const BaseExpr &b)
template<int N>
QuotientExpr< ValueExpr< internal::FixedInt< N > >, Derived > operator/ (internal::FixedInt< N >, const BaseExpr &b)
template<int N>
AddExpr< Derived, ValueExpr< internal::FixedInt< N > > > operator+ (internal::FixedInt< N >(*)(), const BaseExpr &b)
template<int N>
AddExpr< NegateExpr< Derived >, ValueExpr< internal::FixedInt< N > > > operator- (internal::FixedInt< N >(*)(), const BaseExpr &b)
template<int N>
ProductExpr< ValueExpr< internal::FixedInt< N > >, Derived > operator* (internal::FixedInt< N >(*)(), const BaseExpr &b)
template<int N>
QuotientExpr< ValueExpr< internal::FixedInt< N > >, Derived > operator/ (internal::FixedInt< N >(*)(), const BaseExpr &b)
Detailed Description
template<typename Derived>
class Eigen::Symbolic::BaseExpr< Derived >
Common base class of any symbolic expressions
Member Function Documentation
template<typename Derived> const Derived& Eigen::Symbolic::BaseExpr< Derived >::derived () const inline
Referenced by Eigen::internal::eval_expr_given_size(), Eigen::Symbolic::BaseExpr< NegateExpr< Arg0 > >::operator*(), Eigen::Symbolic::BaseExpr< NegateExpr< Arg0 > >::operator+(), Eigen::Symbolic::BaseExpr< NegateExpr< Arg0 > >::operator-(), Eigen::Symbolic::BaseExpr< NegateExpr< Arg0 > >::operator/(), and Eigen::seq().
template<typename Derived> template<typename T > Index Eigen::Symbolic::BaseExpr< Derived >::eval (const T & values) const inline
Evaluate the expression given the values of the symbols.
Parameters
values defines the values of the symbols, it can either be a SymbolValue or a std::tuple of SymbolValue as constructed by SymbolExpr::operator= operator.
template<typename Derived> ProductExpr<Derived,ValueExpr<> > Eigen::Symbolic::BaseExpr< Derived >::operator* (Index a) const inline
template<typename Derived> template<int N> ProductExpr<Derived,ValueExpr<internal::FixedInt<N> > > Eigen::Symbolic::BaseExpr< Derived >::operator* (internal::FixedInt< N >) const inline
template<typename Derived> template<int N> ProductExpr<Derived,ValueExpr<internal::FixedInt<N> > > Eigen::Symbolic::BaseExpr< Derived >::operator* (internal::FixedInt< N > *)() const inline
template<typename Derived> template<typename OtherDerived > ProductExpr<Derived,OtherDerived> Eigen::Symbolic::BaseExpr< Derived >::operator* (const BaseExpr< OtherDerived > & b) const inline
template<typename Derived> AddExpr<Derived,ValueExpr<> > Eigen::Symbolic::BaseExpr< Derived >::operator+ (Index b) const inline
template<typename Derived> template<int N> AddExpr<Derived,ValueExpr<internal::FixedInt<N> > > Eigen::Symbolic::BaseExpr< Derived >::operator+ (internal::FixedInt< N >) const inline
template<typename Derived> template<int N> AddExpr<Derived,ValueExpr<internal::FixedInt<N> > > Eigen::Symbolic::BaseExpr< Derived >::operator+ (internal::FixedInt< N > *)() const inline
template<typename Derived> template<typename OtherDerived > AddExpr<Derived,OtherDerived> Eigen::Symbolic::BaseExpr< Derived >::operator+ (const BaseExpr< OtherDerived > & b) const inline
template<typename Derived> NegateExpr<Derived> Eigen::Symbolic::BaseExpr< Derived >::operator- () const inline
template<typename Derived> AddExpr<Derived,ValueExpr<> > Eigen::Symbolic::BaseExpr< Derived >::operator- (Index a) const inline
template<typename Derived> template<int N> AddExpr<Derived,ValueExpr<internal::FixedInt<-N> > > Eigen::Symbolic::BaseExpr< Derived >::operator- (internal::FixedInt< N >) const inline
template<typename Derived> template<int N> AddExpr<Derived,ValueExpr<internal::FixedInt<-N> > > Eigen::Symbolic::BaseExpr< Derived >::operator- (internal::FixedInt< N > *)() const inline
template<typename Derived> template<typename OtherDerived > AddExpr<Derived,NegateExpr<OtherDerived> > Eigen::Symbolic::BaseExpr< Derived >::operator- (const BaseExpr< OtherDerived > & b) const inline
template<typename Derived> QuotientExpr<Derived,ValueExpr<> > Eigen::Symbolic::BaseExpr< Derived >::operator/ (Index a) const inline
template<typename Derived> template<int N> QuotientExpr<Derived,ValueExpr<internal::FixedInt<N> > > Eigen::Symbolic::BaseExpr< Derived >::operator/ (internal::FixedInt< N >) const inline
template<typename Derived> template<int N> QuotientExpr<Derived,ValueExpr<internal::FixedInt<N> > > Eigen::Symbolic::BaseExpr< Derived >::operator/ (internal::FixedInt< N > *)() const inline
template<typename Derived> template<typename OtherDerived > QuotientExpr<Derived,OtherDerived> Eigen::Symbolic::BaseExpr< Derived >::operator/ (const BaseExpr< OtherDerived > & b) const inline
Friends And Related Function Documentation
template<typename Derived> ProductExpr<ValueExpr<>,Derived> operator* (Index a, const BaseExpr< Derived > & b) friend
template<typename Derived> template<int N> ProductExpr<ValueExpr<internal::FixedInt<N> >,Derived> operator* (internal::FixedInt< N > , const BaseExpr< Derived > & b) friend
template<typename Derived> template<int N> ProductExpr<ValueExpr<internal::FixedInt<N> >,Derived> operator* (internal::FixedInt< N > *)(, const BaseExpr< Derived > & b) friend
template<typename Derived> AddExpr<Derived,ValueExpr<> > operator+ (Index a, const BaseExpr< Derived > & b) friend
template<typename Derived> template<int N> AddExpr<Derived,ValueExpr<internal::FixedInt<N> > > operator+ (internal::FixedInt< N > , const BaseExpr< Derived > & b) friend
template<typename Derived> template<int N> AddExpr<Derived,ValueExpr<internal::FixedInt<N> > > operator+ (internal::FixedInt< N > *)(, const BaseExpr< Derived > & b) friend
template<typename Derived> AddExpr<NegateExpr<Derived>,ValueExpr<> > operator- (Index a, const BaseExpr< Derived > & b) friend
template<typename Derived> template<int N> AddExpr<NegateExpr<Derived>,ValueExpr<internal::FixedInt<N> > > operator- (internal::FixedInt< N > , const BaseExpr< Derived > & b) friend
template<typename Derived> template<int N> AddExpr<NegateExpr<Derived>,ValueExpr<internal::FixedInt<N> > > operator- (internal::FixedInt< N > *)(, const BaseExpr< Derived > & b) friend
template<typename Derived> QuotientExpr<ValueExpr<>,Derived> operator/ (Index a, const BaseExpr< Derived > & b) friend
template<typename Derived> template<int N> QuotientExpr<ValueExpr<internal::FixedInt<N> >,Derived> operator/ (internal::FixedInt< N > , const BaseExpr< Derived > & b) friend
template<typename Derived> template<int N> QuotientExpr<ValueExpr<internal::FixedInt<N> >,Derived> operator/ (internal::FixedInt< N > *)(, const BaseExpr< Derived > & b) friend
The documentation for this class was generated from the following file:
SymbolicIndex.h