SmartMouse_2018: Eigen::PastixBase< Derived > Class Template Reference
Eigen::PastixBase< Derived > Class Template Reference
#include <PaStiXSupport.h>
Public Types
enum { ColsAtCompileTime = MatrixType::ColsAtCompileTime, MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime }
typedef internal::pastix_traits< Derived >::MatrixType _MatrixType
typedef _MatrixType MatrixType
typedef MatrixType::Scalar Scalar
typedef MatrixType::RealScalar RealScalar
typedef MatrixType::StorageIndex StorageIndex
typedef Matrix< Scalar, Dynamic, 1 > Vector
typedef SparseMatrix< Scalar, ColMajor > ColSpMatrix
Public Member Functions
PastixBase ()
~PastixBase ()
template<typename Rhs , typename Dest >
bool _solve_impl (const MatrixBase< Rhs > &b, MatrixBase< Dest > &x) const
Array< StorageIndex, IPARM_SIZE, 1 > & iparm ()
int & iparm (int idxparam)
Array< double, DPARM_SIZE, 1 > & dparm ()
double & dparm (int idxparam)
Index cols () const
Index rows () const
ComputationInfo info () const
Reports whether previous computation was successful.
Public Member Functions inherited from Eigen::SparseSolverBase< Derived >
SparseSolverBase ()
~SparseSolverBase ()
Derived & derived ()
const Derived & derived () const
template<typename Rhs >
const Solve< Derived, Rhs > solve (const MatrixBase< Rhs > &b) const
template<typename Rhs >
const Solve< Derived, Rhs > solve (const SparseMatrixBase< Rhs > &b) const
template<typename Rhs , typename Dest >
void _solve_impl (const SparseMatrixBase< Rhs > &b, SparseMatrixBase< Dest > &dest) const
Protected Types
typedef SparseSolverBase< Derived > Base
Protected Member Functions
void init ()
void analyzePattern (ColSpMatrix &mat)
void factorize (ColSpMatrix &mat)
void clean ()
void compute (ColSpMatrix &mat)
Protected Attributes
int m_initisOk
int m_analysisIsOk
int m_factorizationIsOk
ComputationInfo m_info
pastix_data_t * m_pastixdata
int m_comm
Array< int, IPARM_SIZE, 1 > m_iparm
Array< double, DPARM_SIZE, 1 > m_dparm
Matrix< StorageIndex, Dynamic, 1 > m_perm
Matrix< StorageIndex, Dynamic, 1 > m_invp
int m_size
Protected Attributes inherited from Eigen::SparseSolverBase< Derived >
bool m_isInitialized
Member Typedef Documentation
template<class Derived> typedef internal::pastix_traits<Derived>::MatrixType Eigen::PastixBase< Derived >::_MatrixType
template<class Derived> typedef SparseSolverBase<Derived> Eigen::PastixBase< Derived >::Base protected
template<class Derived> typedef SparseMatrix<Scalar, ColMajor> Eigen::PastixBase< Derived >::ColSpMatrix
template<class Derived> typedef _MatrixType Eigen::PastixBase< Derived >::MatrixType
template<class Derived> typedef MatrixType::RealScalar Eigen::PastixBase< Derived >::RealScalar
template<class Derived> typedef MatrixType::Scalar Eigen::PastixBase< Derived >::Scalar
template<class Derived> typedef MatrixType::StorageIndex Eigen::PastixBase< Derived >::StorageIndex
template<class Derived> typedef Matrix<Scalar,Dynamic,1> Eigen::PastixBase< Derived >::Vector
Member Enumeration Documentation
template<class Derived> anonymous enum
Enumerator
ColsAtCompileTime
MaxColsAtCompileTime
Constructor & Destructor Documentation
template<class Derived> Eigen::PastixBase< Derived >::PastixBase () inline
template<class Derived> Eigen::PastixBase< Derived >::~PastixBase () inline
Member Function Documentation
template<typename Base > template<typename Rhs , typename Dest > bool Eigen::PastixBase< Base >::_solve_impl (const MatrixBase< Rhs > & b, MatrixBase< Dest > & x) const
References eigen_assert, Eigen::internal::eigen_pastix(), EIGEN_STATIC_ASSERT, i, Eigen::NumericalIssue, Eigen::RowMajorBit, and Eigen::Success.
template<class Derived > void Eigen::PastixBase< Derived >::analyzePattern (ColSpMatrix & mat) protected
References eigen_assert, Eigen::internal::eigen_pastix(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::innerIndexPtr(), Eigen::NumericalIssue, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::outerIndexPtr(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::rows(), Eigen::Success, and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::valuePtr().
template<class Derived> void Eigen::PastixBase< Derived >::clean () inline protected
template<class Derived> Index Eigen::PastixBase< Derived >::cols (void) const inline
template<class Derived > void Eigen::PastixBase< Derived >::compute (ColSpMatrix & mat) protected
References Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::cols(), eigen_assert, and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::rows().
template<class Derived> Array<double,DPARM_SIZE,1>& Eigen::PastixBase< Derived >::dparm () inline
Returns a reference to the double vector DPARM of PaStiX parameters The statistics related to the different phases of factorization and solve are saved here as well
See also
analyzePattern() factorize()
template<class Derived> double& Eigen::PastixBase< Derived >::dparm (int idxparam) inline
Return a reference to a particular index parameter of the DPARM vector
See also
dparm()
template<class Derived > void Eigen::PastixBase< Derived >::factorize (ColSpMatrix & mat) protected
References eigen_assert, Eigen::internal::eigen_pastix(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::innerIndexPtr(), Eigen::NumericalIssue, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::outerIndexPtr(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::rows(), Eigen::Success, and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::valuePtr().
template<class Derived> ComputationInfo Eigen::PastixBase< Derived >::info () const inline
Reports whether previous computation was successful.
Returns
Success if computation was succesful, NumericalIssue if the PaStiX reports a problem InvalidInput if the input matrix is invalid
See also
iparm()
template<class Derived > void Eigen::PastixBase< Derived >::init () protected
Initialize the PaStiX data structure. A first call to this function fills iparm and dparm with the default PaStiX parameters
See also
iparm() dparm()
References Eigen::internal::eigen_pastix(), Eigen::InvalidInput, and Eigen::Success.
template<class Derived> Array<StorageIndex,IPARM_SIZE,1>& Eigen::PastixBase< Derived >::iparm () inline
Returns a reference to the integer vector IPARM of PaStiX parameters to modify the default parameters. The statistics related to the different phases of factorization and solve are saved here as well
See also
analyzePattern() factorize()
template<class Derived> int& Eigen::PastixBase< Derived >::iparm (int idxparam) inline
Return a reference to a particular index parameter of the IPARM vector
See also
iparm()
template<class Derived> Index Eigen::PastixBase< Derived >::rows (void) const inline
Member Data Documentation
template<class Derived> int Eigen::PastixBase< Derived >::m_analysisIsOk protected
template<class Derived> int Eigen::PastixBase< Derived >::m_comm mutable protected
template<class Derived> Array<double,DPARM_SIZE,1> Eigen::PastixBase< Derived >::m_dparm mutable protected
template<class Derived> int Eigen::PastixBase< Derived >::m_factorizationIsOk protected
template<class Derived> ComputationInfo Eigen::PastixBase< Derived >::m_info mutable protected
template<class Derived> int Eigen::PastixBase< Derived >::m_initisOk protected
template<class Derived> Matrix<StorageIndex,Dynamic,1> Eigen::PastixBase< Derived >::m_invp mutable protected
template<class Derived> Array<int,IPARM_SIZE,1> Eigen::PastixBase< Derived >::m_iparm mutable protected
template<class Derived> pastix_data_t* Eigen::PastixBase< Derived >::m_pastixdata mutable protected
template<class Derived> Matrix<StorageIndex,Dynamic,1> Eigen::PastixBase< Derived >::m_perm mutable protected
template<class Derived> int Eigen::PastixBase< Derived >::m_size mutable protected
The documentation for this class was generated from the following file:
PaStiXSupport.h