SmartMouse_2018: Eigen::SparseSelfAdjointView< MatrixType, _Mode > Class Template Reference
Eigen::SparseSelfAdjointView< MatrixType, _Mode > Class Template Reference
Pseudo expression to manipulate a triangular sparse matrix as a selfadjoint matrix.
#include <SparseSelfAdjointView.h>
Public Types
enum { Mode = _Mode, TransposeMode = ((Mode & Upper) ? Lower : 0) | ((Mode & Lower) ? Upper : 0), RowsAtCompileTime = internal::traits<SparseSelfAdjointView>::RowsAtCompileTime, ColsAtCompileTime = internal::traits<SparseSelfAdjointView>::ColsAtCompileTime }
typedef EigenBase< SparseSelfAdjointView > Base
typedef MatrixType::Scalar Scalar
typedef MatrixType::StorageIndex StorageIndex
typedef Matrix< StorageIndex, Dynamic, 1 > VectorI
typedef internal::ref_selector< MatrixType >::non_const_type MatrixTypeNested
typedef internal::remove_all< MatrixTypeNested >::type _MatrixTypeNested
Public Types inherited from Eigen::EigenBase< SparseSelfAdjointView< MatrixType, _Mode > >
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< SparseSelfAdjointView< MatrixType, _Mode > >::StorageKind StorageKind
Public Member Functions
SparseSelfAdjointView (MatrixType &matrix)
Index rows () const
Index cols () const
const _MatrixTypeNested & matrix () const
internal::remove_reference< MatrixTypeNested >::type & matrix ()
template<typename OtherDerived >
Product< SparseSelfAdjointView, OtherDerived > operator* (const SparseMatrixBase< OtherDerived > &rhs) const
template<typename OtherDerived >
Product< SparseSelfAdjointView, OtherDerived > operator* (const MatrixBase< OtherDerived > &rhs) const
template<typename DerivedU >
SparseSelfAdjointView & rankUpdate (const SparseMatrixBase< DerivedU > &u, const Scalar &alpha=Scalar(1))
SparseSymmetricPermutationProduct< _MatrixTypeNested, Mode > twistedBy (const PermutationMatrix< Dynamic, Dynamic, StorageIndex > &perm) const
template<typename SrcMatrixType , int SrcMode>
SparseSelfAdjointView & operator= (const SparseSymmetricPermutationProduct< SrcMatrixType, SrcMode > &permutedMatrix)
SparseSelfAdjointView & operator= (const SparseSelfAdjointView &src)
template<typename SrcMatrixType , unsigned int SrcMode>
SparseSelfAdjointView & operator= (const SparseSelfAdjointView< SrcMatrixType, SrcMode > &src)
void resize (Index rows, Index cols)
template<typename DerivedU >
SparseSelfAdjointView< MatrixType, Mode > & rankUpdate (const SparseMatrixBase< DerivedU > &u, const Scalar &alpha)
Public Member Functions inherited from Eigen::EigenBase< SparseSelfAdjointView< MatrixType, _Mode > >
EIGEN_DEVICE_FUNC SparseSelfAdjointView< MatrixType, _Mode > & derived ()
EIGEN_DEVICE_FUNC const SparseSelfAdjointView< MatrixType, _Mode > & derived () const
EIGEN_DEVICE_FUNC SparseSelfAdjointView< MatrixType, _Mode > & const_cast_derived () const
EIGEN_DEVICE_FUNC const SparseSelfAdjointView< MatrixType, _Mode > & const_derived () const
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
EIGEN_DEVICE_FUNC Index size () const
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
Protected Attributes
MatrixTypeNested m_matrix
Private Member Functions
template<typename Dest >
void evalTo (Dest &) const
Friends
template<typename OtherDerived >
Product< OtherDerived, SparseSelfAdjointView > operator* (const SparseMatrixBase< OtherDerived > &lhs, const SparseSelfAdjointView &rhs)
template<typename OtherDerived >
Product< OtherDerived, SparseSelfAdjointView > operator* (const MatrixBase< OtherDerived > &lhs, const SparseSelfAdjointView &rhs)
Detailed Description
template<typename MatrixType, unsigned int _Mode>
class Eigen::SparseSelfAdjointView< MatrixType, _Mode >
Pseudo expression to manipulate a triangular sparse matrix as a selfadjoint matrix.
Parameters
MatrixType the type of the dense matrix storing the coefficients
Mode can be either Lower or Upper
This class is an expression of a sefladjoint matrix from a triangular part of a matrix with given dense storage of the coefficients. It is the return type of MatrixBase::selfadjointView() and most of the time this is the only way that it is used.
See also
SparseMatrixBase::selfadjointView()
Member Typedef Documentation
template<typename MatrixType, unsigned int _Mode> typedef internal::remove_all<MatrixTypeNested>::type Eigen::SparseSelfAdjointView< MatrixType, _Mode >::_MatrixTypeNested
template<typename MatrixType, unsigned int _Mode> typedef EigenBase<SparseSelfAdjointView> Eigen::SparseSelfAdjointView< MatrixType, _Mode >::Base
template<typename MatrixType, unsigned int _Mode> typedef internal::ref_selector<MatrixType>::non_const_type Eigen::SparseSelfAdjointView< MatrixType, _Mode >::MatrixTypeNested
template<typename MatrixType, unsigned int _Mode> typedef MatrixType::Scalar Eigen::SparseSelfAdjointView< MatrixType, _Mode >::Scalar
template<typename MatrixType, unsigned int _Mode> typedef MatrixType::StorageIndex Eigen::SparseSelfAdjointView< MatrixType, _Mode >::StorageIndex
template<typename MatrixType, unsigned int _Mode> typedef Matrix<StorageIndex,Dynamic,1> Eigen::SparseSelfAdjointView< MatrixType, _Mode >::VectorI
Member Enumeration Documentation
template<typename MatrixType, unsigned int _Mode> anonymous enum
Enumerator
Mode
TransposeMode
RowsAtCompileTime
ColsAtCompileTime
Constructor & Destructor Documentation
template<typename MatrixType, unsigned int _Mode> Eigen::SparseSelfAdjointView< MatrixType, _Mode >::SparseSelfAdjointView (MatrixType & matrix) inline explicit
References eigen_assert.
Member Function Documentation
template<typename MatrixType, unsigned int _Mode> Index Eigen::SparseSelfAdjointView< MatrixType, _Mode >::cols (void) const inline
template<typename MatrixType, unsigned int _Mode> template<typename Dest > void Eigen::SparseSelfAdjointView< MatrixType, _Mode >::evalTo (Dest &) const private
template<typename MatrixType, unsigned int _Mode> const _MatrixTypeNested& Eigen::SparseSelfAdjointView< MatrixType, _Mode >::matrix () const inline
Referenced by Eigen::internal::Assignment< DstXprType, SparseSymmetricPermutationProduct< MatrixType, Mode >, internal::assign_op< Scalar, typename MatrixType::Scalar >, Sparse2Sparse >::run().
template<typename MatrixType, unsigned int _Mode> internal::remove_reference<MatrixTypeNested>::type& Eigen::SparseSelfAdjointView< MatrixType, _Mode >::matrix () inline
template<typename MatrixType, unsigned int _Mode> template<typename OtherDerived > Product<SparseSelfAdjointView, OtherDerived> Eigen::SparseSelfAdjointView< MatrixType, _Mode >::operator* (const SparseMatrixBase< OtherDerived > & rhs) const inline
Returns
an expression of the matrix product between a sparse self-adjoint matrix *this and a sparse matrix rhs.
Note that there is no algorithmic advantage of performing such a product compared to a general sparse-sparse matrix product. Indeed, the SparseSelfadjointView operand is first copied into a temporary SparseMatrix before computing the product.
References Eigen::SparseMatrixBase< Derived >::derived().
template<typename MatrixType, unsigned int _Mode> template<typename OtherDerived > Product<SparseSelfAdjointView,OtherDerived> Eigen::SparseSelfAdjointView< MatrixType, _Mode >::operator* (const MatrixBase< OtherDerived > & rhs) const inline
Efficient sparse self-adjoint matrix times dense vector/matrix product
template<typename MatrixType, unsigned int _Mode> template<typename SrcMatrixType , int SrcMode> SparseSelfAdjointView& Eigen::SparseSelfAdjointView< MatrixType, _Mode >::operator= (const SparseSymmetricPermutationProduct< SrcMatrixType, SrcMode > & permutedMatrix) inline
References Eigen::internal::call_assignment_no_alias_no_transpose().
template<typename MatrixType, unsigned int _Mode> SparseSelfAdjointView& Eigen::SparseSelfAdjointView< MatrixType, _Mode >::operator= (const SparseSelfAdjointView< MatrixType, _Mode > & src) inline
References Eigen::SparseSelfAdjointView< MatrixType, _Mode >::twistedBy().
template<typename MatrixType, unsigned int _Mode> template<typename SrcMatrixType , unsigned int SrcMode> SparseSelfAdjointView& Eigen::SparseSelfAdjointView< MatrixType, _Mode >::operator= (const SparseSelfAdjointView< SrcMatrixType, SrcMode > & src) inline
References Eigen::SparseSelfAdjointView< MatrixType, _Mode >::twistedBy().
template<typename MatrixType, unsigned int _Mode> template<typename DerivedU > SparseSelfAdjointView& Eigen::SparseSelfAdjointView< MatrixType, _Mode >::rankUpdate (const SparseMatrixBase< DerivedU > & u, const Scalar & alpha = Scalar(1))
Perform a symmetric rank K update of the selfadjoint matrix *this: where u is a vector or matrix.
Returns
a reference to *this
To perform you can simply call this function with u.adjoint().
template<typename MatrixType, unsigned int _Mode> template<typename DerivedU > SparseSelfAdjointView<MatrixType,Mode>& Eigen::SparseSelfAdjointView< MatrixType, _Mode >::rankUpdate (const SparseMatrixBase< DerivedU > & u, const Scalar & alpha)
References Eigen::SparseMatrixBase< Derived >::adjoint().
template<typename MatrixType, unsigned int _Mode> void Eigen::SparseSelfAdjointView< MatrixType, _Mode >::resize (Index rows, Index cols) inline
References eigen_assert, and EIGEN_ONLY_USED_FOR_DEBUG.
template<typename MatrixType, unsigned int _Mode> Index Eigen::SparseSelfAdjointView< MatrixType, _Mode >::rows (void) const inline
template<typename MatrixType, unsigned int _Mode> SparseSymmetricPermutationProduct<_MatrixTypeNested,Mode> Eigen::SparseSelfAdjointView< MatrixType, _Mode >::twistedBy (const PermutationMatrix< Dynamic, Dynamic, StorageIndex > & perm) const inline
Returns
an expression of P H P^-1
Referenced by Eigen::SparseSelfAdjointView< MatrixType, _Mode >::operator=().
Friends And Related Function Documentation
template<typename MatrixType, unsigned int _Mode> template<typename OtherDerived > Product<OtherDerived, SparseSelfAdjointView> operator* (const SparseMatrixBase< OtherDerived > & lhs, const SparseSelfAdjointView< MatrixType, _Mode > & rhs) friend
Returns
an expression of the matrix product between a sparse matrix lhs and a sparse self-adjoint matrix rhs.
Note that there is no algorithmic advantage of performing such a product compared to a general sparse-sparse matrix product. Indeed, the SparseSelfadjointView operand is first copied into a temporary SparseMatrix before computing the product.
template<typename MatrixType, unsigned int _Mode> template<typename OtherDerived > Product<OtherDerived,SparseSelfAdjointView> operator* (const MatrixBase< OtherDerived > & lhs, const SparseSelfAdjointView< MatrixType, _Mode > & rhs) friend
Efficient dense vector/matrix times sparse self-adjoint matrix product
Member Data Documentation
template<typename MatrixType, unsigned int _Mode> MatrixTypeNested Eigen::SparseSelfAdjointView< MatrixType, _Mode >::m_matrix protected
The documentation for this class was generated from the following file:
SparseSelfAdjointView.h