SmartMouse_2018: MazeWidget Class Reference
MazeWidget Class Reference
#include <MazeWidget.h>
Signals
void MyUpdate ()
Public Member Functions
MazeWidget ()
void OnMaze (const smartmouse::msgs::Maze &msg)
void OnRobotDescription (const smartmouse::msgs::RobotDescription &msg)
void OnRobotSimState (const smartmouse::msgs::RobotSimState &msg)
void paintEvent (QPaintEvent *event)
const QString GetTabName () override
Private Member Functions
void PaintWalls (QPainter &painter, QTransform tf)
void PaintMouse (QPainter &painter, QTransform tf)
Private Attributes
ignition::transport::Node node_
smartmouse::msgs::maze_walls_t maze_walls_
smartmouse::msgs::RobotSimState robot_state_
smartmouse::msgs::RobotDescription mouse_
bool mouse_set_
Static Private Attributes
static const int kPaddingPx = 24
static const QBrush kRobotBrush = QBrush(QColor("#F57C00"))
static QBrush kWallBrush = QBrush(Qt::red)
Constructor & Destructor Documentation
MazeWidget::MazeWidget ()
References TopicNames::kMaze, TopicNames::kRobotDescription, TopicNames::kRobotSimState, MyUpdate(), node_, OnMaze(), OnRobotDescription(), and OnRobotSimState().
Member Function Documentation
const QString MazeWidget::GetTabName () override virtual
Implements AbstractTab.
Referenced by Client::ConfigureGui().
void MazeWidget::MyUpdate () signal
Referenced by MazeWidget(), OnMaze(), OnRobotDescription(), and OnRobotSimState().
void MazeWidget::OnMaze (const smartmouse::msgs::Maze & msg)
References smartmouse::msgs::Convert(), maze_walls_, and MyUpdate().
Referenced by MazeWidget().
void MazeWidget::OnRobotDescription (const smartmouse::msgs::RobotDescription & msg)
References mouse_, mouse_set_, and MyUpdate().
Referenced by MazeWidget().
void MazeWidget::OnRobotSimState (const smartmouse::msgs::RobotSimState & msg)
References MyUpdate(), and robot_state_.
Referenced by MazeWidget().
void MazeWidget::paintEvent (QPaintEvent * event)
References i, kPaddingPx, mouse_set_, PaintMouse(), PaintWalls(), smartmouse::maze::SIZE, and smartmouse::maze::SIZE_CU.
void MazeWidget::PaintMouse (QPainter & painter, QTransform tf) private
References kRobotBrush, mouse_, robot_state_, and smartmouse::maze::UNIT_DIST_M.
Referenced by paintEvent().
void MazeWidget::PaintWalls (QPainter & painter, QTransform tf) private
References kWallBrush, maze_walls_, and smartmouse::maze::SIZE.
Referenced by paintEvent().
Member Data Documentation
const int MazeWidget::kPaddingPx = 24 static private
Referenced by paintEvent().
const QBrush MazeWidget::kRobotBrush = QBrush(QColor("#F57C00")) static private
Referenced by PaintMouse().
QBrush MazeWidget::kWallBrush = QBrush(Qt::red) static private
Referenced by PaintWalls().
smartmouse::msgs::maze_walls_t MazeWidget::maze_walls_ private
Referenced by OnMaze(), and PaintWalls().
smartmouse::msgs::RobotDescription MazeWidget::mouse_ private
Referenced by OnRobotDescription(), and PaintMouse().
bool MazeWidget::mouse_set_ private
Referenced by OnRobotDescription(), and paintEvent().
ignition::transport::Node MazeWidget::node_ private
Referenced by MazeWidget().
smartmouse::msgs::RobotSimState MazeWidget::robot_state_ private
Referenced by OnRobotSimState(), and PaintMouse().
The documentation for this class was generated from the following files:
MazeWidget.h
MazeWidget.cpp