SmartMouse_2018: Client Class Reference
Client Class Reference
#include <Client.h>
Public Slots
void Exit ()
Signals
void SetRealTime (QString str)
void SetTime (QString str)
Public Member Functions
Client (QMainWindow *parent=0)
void closeEvent (QCloseEvent *event) override
Static Public Attributes
static const int kRestartCode = 1337
Private Slots
void Restart ()
void Play ()
void Pause ()
void SetStatic ()
void ResetMouse ()
void ResetTime ()
void Step ()
void LoadNewMaze ()
void LoadNewMouse ()
void ShowSourceCode ()
void ShowWiki ()
void RealTimeFactorChanged (double real_time_factor)
void StepCountChanged (int step_time_ms)
void TimePerStepMsChanged (int step_time_ms)
void SendRobotCmd ()
void SendTeleportCmd ()
void PublishPIDConstants ()
void PublishPIDSetpoints ()
Private Member Functions
void ConfigureGui ()
void LoadDefaultMaze ()
void LoadRandomMaze ()
void LoadDefaultMouse ()
void RestoreSettings ()
void SaveSettings ()
void OnWorldStats (const smartmouse::msgs::WorldStatistics &msg)
void OnGuiActions (const smartmouse::msgs::GuiActions &msg)
void OnPhysics (const smartmouse::msgs::PhysicsConfig &msg)
Private Attributes
unsigned int step_count_ = 1u
ignition::transport::Node node_
ignition::transport::Node::Publisher maze_pub_
ignition::transport::Node::Publisher physics_pub_
ignition::transport::Node::Publisher server_control_pub_
ignition::transport::Node::Publisher robot_command_pub_
ignition::transport::Node::Publisher robot_description_pub_
ignition::transport::Node::Publisher pid_setpoints_pub_
ignition::transport::Node::Publisher pid_constants_pub_
MazeWidget * maze_widget_
StateWidget * state_widget_
QSettings * settings_
QString maze_files_dir_
QString mouse_files_dir_
QString default_maze_file_name_
QString default_mouse_file_name_
Ui::MainWindow * ui_
Constructor & Destructor Documentation
Client::Client (QMainWindow * parent = 0)
References ConfigureGui(), TopicNames::kGuiActions, TopicNames::kMaze, TopicNames::kPhysics, TopicNames::kPIDConstants, TopicNames::kPIDSetpoints, TopicNames::kRobotCommand, TopicNames::kRobotDescription, TopicNames::kServerControl, TopicNames::kWorldStatistics, maze_pub_, node_, OnGuiActions(), OnPhysics(), OnWorldStats(), physics_pub_, pid_constants_pub_, pid_setpoints_pub_, RestoreSettings(), robot_command_pub_, robot_description_pub_, server_control_pub_, and ui_.
Member Function Documentation
void Client::closeEvent (QCloseEvent * event) override
References SaveSettings().
void Client::ConfigureGui () private
References Exit(), MazeWidget::GetTabName(), LoadDefaultMouse(), LoadNewMaze(), LoadNewMouse(), LoadRandomMaze(), maze_widget_, Pause(), Play(), PublishPIDConstants(), PublishPIDSetpoints(), RealTimeFactorChanged(), ResetMouse(), ResetTime(), Restart(), SendRobotCmd(), SendTeleportCmd(), SetRealTime(), SetStatic(), SetTime(), ShowSourceCode(), ShowWiki(), state_widget_, Step(), StepCountChanged(), TimePerStepMsChanged(), and ui_.
Referenced by Client().
void Client::Exit () slot
References SaveSettings(), and server_control_pub_.
Referenced by ConfigureGui().
void Client::LoadDefaultMaze () private
References smartmouse::msgs::Convert(), default_maze_file_name_, in, maze, maze_pub_, and ui_.
Referenced by RestoreSettings().
void Client::LoadDefaultMouse () private
References smartmouse::msgs::Convert(), default_mouse_file_name_, in, robot_description_pub_, and ui_.
Referenced by ConfigureGui(), and RestoreSettings().
void Client::LoadNewMaze () private slot
References smartmouse::msgs::Convert(), default_maze_file_name_, in, maze, maze_files_dir_, maze_pub_, settings_, and ui_.
Referenced by ConfigureGui().
void Client::LoadNewMouse () private slot
References smartmouse::msgs::Convert(), default_mouse_file_name_, in, mouse_files_dir_, robot_description_pub_, settings_, and ui_.
Referenced by ConfigureGui().
void Client::LoadRandomMaze () private
References smartmouse::msgs::Convert(), AbstractMaze::gen_random_legal_maze(), maze, and maze_pub_.
Referenced by ConfigureGui().
void Client::OnGuiActions (const smartmouse::msgs::GuiActions & msg) private
References ShowSourceCode().
Referenced by Client().
void Client::OnPhysics (const smartmouse::msgs::PhysicsConfig & msg) private
References ui_.
Referenced by Client().
void Client::OnWorldStats (const smartmouse::msgs::WorldStatistics & msg) private
References SetRealTime(), SetTime(), and time.
Referenced by Client().
void Client::Pause () private slot
References server_control_pub_.
Referenced by ConfigureGui().
void Client::Play () private slot
References server_control_pub_.
Referenced by ConfigureGui().
void Client::PublishPIDConstants () private slot
References pid_constants_pub_, and ui_.
Referenced by ConfigureGui().
void Client::PublishPIDSetpoints () private slot
References pid_setpoints_pub_, and ui_.
Referenced by ConfigureGui().
void Client::RealTimeFactorChanged (double real_time_factor) private slot
References physics_pub_.
Referenced by ConfigureGui().
void Client::ResetMouse () private slot
References server_control_pub_.
Referenced by ConfigureGui().
void Client::ResetTime () private slot
References server_control_pub_.
Referenced by ConfigureGui().
void Client::Restart () private slot
References kRestartCode, and SaveSettings().
Referenced by ConfigureGui().
void Client::RestoreSettings () private
References default_maze_file_name_, default_mouse_file_name_, LoadDefaultMaze(), LoadDefaultMouse(), maze_files_dir_, mouse_files_dir_, settings_, and ui_.
Referenced by Client().
void Client::SaveSettings () private
References settings_, and ui_.
Referenced by closeEvent(), Exit(), and Restart().
void Client::SendRobotCmd () private slot
References robot_command_pub_, and ui_.
Referenced by ConfigureGui().
void Client::SendTeleportCmd () private slot
References server_control_pub_, and ui_.
Referenced by ConfigureGui().
void Client::SetRealTime (QString str) signal
Referenced by ConfigureGui(), and OnWorldStats().
void Client::SetStatic () private slot
References server_control_pub_, and ui_.
Referenced by ConfigureGui().
void Client::SetTime (QString str) signal
Referenced by ConfigureGui(), and OnWorldStats().
void Client::ShowSourceCode () private slot
Referenced by ConfigureGui(), and OnGuiActions().
void Client::ShowWiki () private slot
Referenced by ConfigureGui().
void Client::Step () private slot
References server_control_pub_, and step_count_.
Referenced by ConfigureGui().
void Client::StepCountChanged (int step_time_ms) private slot
References step_count_.
Referenced by ConfigureGui().
void Client::TimePerStepMsChanged (int step_time_ms) private slot
References physics_pub_.
Referenced by ConfigureGui().
Member Data Documentation
QString Client::default_maze_file_name_ private
Referenced by LoadDefaultMaze(), LoadNewMaze(), and RestoreSettings().
QString Client::default_mouse_file_name_ private
Referenced by LoadDefaultMouse(), LoadNewMouse(), and RestoreSettings().
const int Client::kRestartCode = 1337 static
Referenced by main(), and Restart().
QString Client::maze_files_dir_ private
Referenced by LoadNewMaze(), and RestoreSettings().
ignition::transport::Node::Publisher Client::maze_pub_ private
Referenced by Client(), LoadDefaultMaze(), LoadNewMaze(), and LoadRandomMaze().
MazeWidget* Client::maze_widget_ private
Referenced by ConfigureGui().
QString Client::mouse_files_dir_ private
Referenced by LoadNewMouse(), and RestoreSettings().
ignition::transport::Node Client::node_ private
Referenced by Client().
ignition::transport::Node::Publisher Client::physics_pub_ private
Referenced by Client(), RealTimeFactorChanged(), and TimePerStepMsChanged().
ignition::transport::Node::Publisher Client::pid_constants_pub_ private
Referenced by Client(), and PublishPIDConstants().
ignition::transport::Node::Publisher Client::pid_setpoints_pub_ private
Referenced by Client(), and PublishPIDSetpoints().
ignition::transport::Node::Publisher Client::robot_command_pub_ private
Referenced by Client(), and SendRobotCmd().
ignition::transport::Node::Publisher Client::robot_description_pub_ private
Referenced by Client(), LoadDefaultMouse(), and LoadNewMouse().
ignition::transport::Node::Publisher Client::server_control_pub_ private
Referenced by Client(), Exit(), Pause(), Play(), ResetMouse(), ResetTime(), SendTeleportCmd(), SetStatic(), and Step().
QSettings* Client::settings_ private
Referenced by LoadNewMaze(), LoadNewMouse(), RestoreSettings(), and SaveSettings().
StateWidget* Client::state_widget_ private
Referenced by ConfigureGui().
unsigned int Client::step_count_ = 1u private
Referenced by Step(), and StepCountChanged().
Ui::MainWindow* Client::ui_ private
Referenced by Client(), ConfigureGui(), LoadDefaultMaze(), LoadDefaultMouse(), LoadNewMaze(), LoadNewMouse(), OnPhysics(), PublishPIDConstants(), PublishPIDSetpoints(), RestoreSettings(), SaveSettings(), SendRobotCmd(), SendTeleportCmd(), and SetStatic().
The documentation for this class was generated from the following files:
Client.h
Client.cpp