SmartMouse_2018: LinkedList< T > Class Template Reference
LinkedList< T > Class Template Reference
LinkedList.h - V1.1 - Generic LinkedList implementation Works better with FIFO, because LIFO will need to search the entire List to find the last one;.
#include <LinkedList.h>
Public Member Functions
LinkedList ()
~LinkedList ()
virtual int size ()
Returns current size of LinkedList.
virtual bool add (int index, T)
Adds a T object in the specified index; Unlink and link the LinkedList correcly; Increment _size.
virtual bool add (T)
Adds a T object in the end of the LinkedList; Increment _size;.
virtual bool unshift (T)
Adds a T object in the start of the LinkedList; Increment _size;.
virtual bool set (int index, T)
Set the object at index, with T; Increment _size;.
virtual T remove (int index)
Remove object at index; If index is not reachable, returns false; else, decrement _size.
virtual T pop ()
Remove last object;.
virtual T shift ()
Remove first object;.
virtual T get (int index)
Get the index'th element on the list; Return Element if accessible, else, return 0;.
virtual bool contains (T)
virtual void clear ()
Clear the entire array.
Protected Member Functions
ListNode< T > * getNode (int index)
Actualy "logic" coding.
Protected Attributes
int _size
ListNode< T > * root
ListNode< T > * last
ListNode< T > * lastNodeGot
int lastIndexGot
bool isCached
Detailed Description
template<typename T>
class LinkedList< T >
LinkedList.h - V1.1 - Generic LinkedList implementation Works better with FIFO, because LIFO will need to search the entire List to find the last one;.
For instructions, go to https://github.com/ivanseidel/LinkedList
Created by Ivan Seidel Gomes, March, 2013. Released into the public domain.
Constructor & Destructor Documentation
template<typename T > LinkedList< T >::LinkedList ()
template<typename T > LinkedList< T >::~LinkedList ()
References ListNode< T >::next.
Member Function Documentation
template<typename T> bool LinkedList< T >::add (int index, T _t) virtual
Adds a T object in the specified index; Unlink and link the LinkedList correcly; Increment _size.
References ListNode< T >::data, and ListNode< T >::next.
Referenced by Scheduler::addCommand(), CommandGroup::addParallel(), and CommandGroup::addSequential().
template<typename T> bool LinkedList< T >::add (T _t) virtual
Adds a T object in the end of the LinkedList; Increment _size;.
References ListNode< T >::data, and ListNode< T >::next.
template<typename T > void LinkedList< T >::clear () virtual
Clear the entire array.
template<typename T> bool LinkedList< T >::contains (T _t) virtual
iterate over list and check if element exists
References ListNode< T >::data, i, and ListNode< T >::next.
template<typename T > T LinkedList< T >::get (int index) virtual
Get the index'th element on the list; Return Element if accessible, else, return 0;.
References ListNode< T >::data.
Referenced by CommandGroup::_execute(), and Scheduler::run().
template<typename T > ListNode< T > * LinkedList< T >::getNode (int index) protected
Actualy "logic" coding.
References ListNode< T >::next.
template<typename T > T LinkedList< T >::pop () virtual
Remove last object;.
References ListNode< T >::data, and ListNode< T >::next.
template<typename T > T LinkedList< T >::remove (int index) virtual
Remove object at index; If index is not reachable, returns false; else, decrement _size.
References ListNode< T >::data, and ListNode< T >::next.
Referenced by CommandGroup::_execute(), and Scheduler::run().
template<typename T> bool LinkedList< T >::set (int index, T _t) virtual
Set the object at index, with T; Increment _size;.
template<typename T > T LinkedList< T >::shift () virtual
Remove first object;.
References ListNode< T >::next.
template<typename T > int LinkedList< T >::size () virtual
Returns current size of LinkedList.
Referenced by CommandGroup::_execute(), CommandGroup::isFinished(), and Scheduler::run().
template<typename T> bool LinkedList< T >::unshift (T _t) virtual
Adds a T object in the start of the LinkedList; Increment _size;.
References ListNode< T >::data, and ListNode< T >::next.
Member Data Documentation
template<typename T> int LinkedList< T >::_size protected
template<typename T> bool LinkedList< T >::isCached protected
template<typename T> ListNode<T>* LinkedList< T >::last protected
template<typename T> int LinkedList< T >::lastIndexGot protected
template<typename T> ListNode<T>* LinkedList< T >::lastNodeGot protected
template<typename T> ListNode<T>* LinkedList< T >::root protected
The documentation for this class was generated from the following file:
LinkedList.h