SmartMouse_2018: ArgumentParser::Any Class Reference
ArgumentParser::Any Class Reference
Classes
class Holder
class PlaceHolder
Public Member Functions
Any ()
~Any ()
Any (const Any &other)
template<typename ValueType >
Any (const ValueType &other)
Any & swap (Any &other)
Any & operator= (const Any &rhs)
template<typename ValueType >
Any & operator= (const ValueType &rhs)
template<typename ValueType >
ValueType * toPtr () const
template<typename ValueType >
ValueType & castTo ()
template<typename ValueType >
const ValueType & castTo () const
Private Attributes
PlaceHolder * content
Constructor & Destructor Documentation
ArgumentParser::Any::Any () inline
ArgumentParser::Any::~Any () inline
References content.
ArgumentParser::Any::Any (const Any & other) inline
template<typename ValueType > ArgumentParser::Any::Any (const ValueType & other) inline
Member Function Documentation
template<typename ValueType > ValueType& ArgumentParser::Any::castTo () inline
Referenced by ArgumentParser::count().
template<typename ValueType > const ValueType& ArgumentParser::Any::castTo () const inline
Any& ArgumentParser::Any::operator= (const Any & rhs) inline
References swap().
template<typename ValueType > Any& ArgumentParser::Any::operator= (const ValueType & rhs) inline
References swap().
Any& ArgumentParser::Any::swap (Any & other) inline
References content, and std::swap().
Referenced by operator=().
template<typename ValueType > ValueType* ArgumentParser::Any::toPtr () const inline
References content, ArgumentParser::Any::Holder< ValueType >::held_, and ArgumentParser::Any::PlaceHolder::type_info().
Member Data Documentation
PlaceHolder* ArgumentParser::Any::content private
Referenced by swap(), toPtr(), and ~Any().
The documentation for this class was generated from the following file:
argparse.hpp