SmartMouse_2018: Joystick Class Reference
Joystick Class Reference
#include <joystick.hh>
Public Member Functions
~Joystick ()
Joystick ()
Joystick (int joystickNumber)
Joystick (std::string devicePath)
Joystick (std::string devicePath, bool blocking)
bool isFound ()
bool sample (JoystickEvent *event)
Private Member Functions
void openPath (std::string devicePath, bool blocking=false)
Private Attributes
int _fd
Detailed Description
Represents a joystick device. Allows data to be sampled from it.
Constructor & Destructor Documentation
Joystick::~Joystick ()
References _fd.
Joystick::Joystick ()
Initialises an instance for the first joystick: /dev/input/js0
References openPath().
Joystick::Joystick (int joystickNumber)
Initialises an instance for the joystick with the specified, zero-indexed number.
References openPath().
Joystick::Joystick (std::string devicePath)
Initialises an instance for the joystick device specified.
References openPath().
Joystick::Joystick (std::string devicePath, bool blocking)
Initialises an instance for the joystick device specified and provide the option of blocking I/O.
References openPath().
Member Function Documentation
bool Joystick::isFound ()
Returns true if the joystick was found and may be used, otherwise false.
References _fd.
Referenced by main().
void Joystick::openPath (std::string devicePath, bool blocking = false) private
References _fd.
Referenced by Joystick().
bool Joystick::sample (JoystickEvent * event)
Attempts to populate the provided JoystickEvent instance with data from the joystick. Returns true if data is available, otherwise false.
References _fd, and read().
Referenced by main().
Member Data Documentation
int Joystick::_fd private
Referenced by isFound(), openPath(), sample(), and ~Joystick().
The documentation for this class was generated from the following files:
joystick.hh
joystick.cc