SmartMouse_2018: Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true > Class Template Reference
Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true > Class Template Reference
#include <JacobiSVD.h>
Public Types
enum { RowsAtCompileTime = MatrixType::RowsAtCompileTime, MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime }
typedef MatrixType::Scalar Scalar
typedef Matrix< Scalar, 1, RowsAtCompileTime, RowMajor, 1, MaxRowsAtCompileTime > WorkspaceType
Public Member Functions
void allocate (const JacobiSVD< MatrixType, FullPivHouseholderQRPreconditioner > &svd)
bool run (JacobiSVD< MatrixType, FullPivHouseholderQRPreconditioner > &svd, const MatrixType &matrix)
Private Types
typedef FullPivHouseholderQR< MatrixType > QRType
Private Attributes
QRType m_qr
WorkspaceType m_workspace
Member Typedef Documentation
template<typename MatrixType > typedef FullPivHouseholderQR<MatrixType> Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::QRType private
template<typename MatrixType > typedef MatrixType::Scalar Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::Scalar
template<typename MatrixType > typedef Matrix<Scalar, 1, RowsAtCompileTime, RowMajor, 1, MaxRowsAtCompileTime> Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::WorkspaceType
Member Enumeration Documentation
template<typename MatrixType > anonymous enum
Enumerator
RowsAtCompileTime
MaxRowsAtCompileTime
Member Function Documentation
template<typename MatrixType > void Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::allocate (const JacobiSVD< MatrixType, FullPivHouseholderQRPreconditioner > & svd) inline
References Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::cols(), Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::m_computeFullU, and Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::rows().
template<typename MatrixType > bool Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run (JacobiSVD< MatrixType, FullPivHouseholderQRPreconditioner > & svd, const MatrixType & matrix) inline
References Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::computeV(), Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::m_computeFullU, Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::m_matrixU, Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::m_matrixV, and Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::m_workMatrix.
Member Data Documentation
template<typename MatrixType > QRType Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::m_qr private
template<typename MatrixType > WorkspaceType Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::m_workspace private
The documentation for this class was generated from the following file:
JacobiSVD.h