SmartMouse_2018: SimTimer Class Reference
SimTimer Class Reference
#include <SimTimer.h>
Public Member Functions
SimTimer ()
bool isTimeReady ()
virtual unsigned long programTimeMs () override
the time since the start of the program in milliseconds
void worldStatsCallback (const smartmouse::msgs::WorldStatistics &msg)
Private Attributes
bool ready
unsigned long sim_time_ms
std::mutex timeReadyMutex
Constructor & Destructor Documentation
SimTimer::SimTimer ()
References timeReadyMutex.
Member Function Documentation
bool SimTimer::isTimeReady ()
References timeReadyMutex.
Referenced by SimMouse::simInit().
unsigned long SimTimer::programTimeMs () override virtual
the time since the start of the program in milliseconds
Implements TimerInterface.
References sim_time_ms.
Referenced by main().
void SimTimer::worldStatsCallback (const smartmouse::msgs::WorldStatistics & msg)
References smartmouse::msgs::ConvertMSec(), ready, sim_time_ms, and timeReadyMutex.
Referenced by main(), and SimMouse::simInit().
Member Data Documentation
bool SimTimer::ready private
Referenced by worldStatsCallback().
unsigned long SimTimer::sim_time_ms private
Referenced by programTimeMs(), and worldStatsCallback().
std::mutex SimTimer::timeReadyMutex private
Referenced by isTimeReady(), SimTimer(), and worldStatsCallback().
The documentation for this class was generated from the following files:
SimTimer.h
SimTimer.cpp