SmartMouse_2018: Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true > Class Template Reference
Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true > Class Template Reference
#include <JacobiSVD.h>
Public Member Functions
void allocate (const JacobiSVD< MatrixType, ColPivHouseholderQRPreconditioner > &svd)
bool run (JacobiSVD< MatrixType, ColPivHouseholderQRPreconditioner > &svd, const MatrixType &matrix)
Private Types
typedef ColPivHouseholderQR< MatrixType > QRType
Private Attributes
QRType m_qr
internal::plain_col_type< MatrixType >::type m_workspace
Member Typedef Documentation
template<typename MatrixType > typedef ColPivHouseholderQR<MatrixType> Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::QRType private
Member Function Documentation
template<typename MatrixType > void Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::allocate (const JacobiSVD< MatrixType, ColPivHouseholderQRPreconditioner > & svd) inline
References Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::cols(), Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::m_computeFullU, Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::m_computeThinU, and Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::rows().
template<typename MatrixType > bool Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run (JacobiSVD< MatrixType, ColPivHouseholderQRPreconditioner > & svd, const MatrixType & matrix) inline
References Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::computeV(), Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::m_computeFullU, Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::m_computeThinU, Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::m_matrixU, Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::m_matrixV, and Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::m_workMatrix.
Member Data Documentation
template<typename MatrixType > QRType Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::m_qr private
template<typename MatrixType > internal::plain_col_type<MatrixType>::type Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::m_workspace private
The documentation for this class was generated from the following file:
JacobiSVD.h