SmartMouse_2018: TrajectoryPlanner Class Reference
TrajectoryPlanner Class Reference
#include <TrajectoryPlanner.h>
Public Member Functions
TrajectoryPlanner (Waypoints waypoints)
const Eigen::Matrix< double, 10, 1 > plan ()
Static Public Member Functions
static Eigen::Matrix< double, 1, 10 > x_constraint (double t)
static Eigen::Matrix< double, 1, 10 > y_constraint (double t)
static Eigen::Matrix< double, 1, 10 > non_holonomic_constraint (double theta_t, double t)
static Eigen::Matrix< double, 1, 10 > trig_constraint (double theta_t, double t)
static Eigen::Matrix< double, 1, 10 > x_dot_constraint (double t)
static Eigen::Matrix< double, 1, 10 > y_dot_constraint (double t)
Private Attributes
Waypoints waypoints
Eigen::Matrix< double, Eigen::Dynamic, 10 > A
Eigen::Matrix< double, 10, 1 > b
Constructor & Destructor Documentation
TrajectoryPlanner::TrajectoryPlanner (Waypoints waypoints)
References A, b, non_holonomic_constraint(), trig_constraint(), x_constraint(), x_dot_constraint(), y_constraint(), and y_dot_constraint().
Member Function Documentation
Eigen::Matrix< double, 1, 10 > TrajectoryPlanner::non_holonomic_constraint (double theta_t, double t) static
Referenced by TrajectoryPlanner().
const Eigen::Matrix< double, 10, 1 > TrajectoryPlanner::plan ()
References A, and b.
Referenced by KinematicController::planTraj().
Eigen::Matrix< double, 1, 10 > TrajectoryPlanner::trig_constraint (double theta_t, double t) static
Referenced by TrajectoryPlanner().
Eigen::Matrix< double, 1, 10 > TrajectoryPlanner::x_constraint (double t) static
Referenced by TrajectoryPlanner().
Eigen::Matrix< double, 1, 10 > TrajectoryPlanner::x_dot_constraint (double t) static
Referenced by TrajectoryPlanner().
Eigen::Matrix< double, 1, 10 > TrajectoryPlanner::y_constraint (double t) static
Referenced by TrajectoryPlanner().
Eigen::Matrix< double, 1, 10 > TrajectoryPlanner::y_dot_constraint (double t) static
Referenced by TrajectoryPlanner().
Member Data Documentation
Eigen::Matrix<double, Eigen::Dynamic, 10> TrajectoryPlanner::A private
Referenced by plan(), and TrajectoryPlanner().
Eigen::Matrix<double, 10, 1> TrajectoryPlanner::b private
Referenced by plan(), and TrajectoryPlanner().
Waypoints TrajectoryPlanner::waypoints private
The documentation for this class was generated from the following files:
TrajectoryPlanner.h
TrajectoryPlanner.cpp