SmartMouse_2018: Eigen::internal::scoped_array< T > Class Template Reference
Eigen::internal::scoped_array< T > Class Template Reference
#include <Memory.h>
Public Member Functions
scoped_array (std::ptrdiff_t size)
~scoped_array ()
T & operator[] (std::ptrdiff_t i)
const T & operator[] (std::ptrdiff_t i) const
T *& ptr ()
const T * ptr () const
operator const T * () const
Private Attributes
T * m_ptr
Additional Inherited Members
Private Member Functions inherited from Eigen::internal::noncopyable
EIGEN_DEVICE_FUNC noncopyable ()
EIGEN_DEVICE_FUNC ~noncopyable ()
Constructor & Destructor Documentation
template<typename T> Eigen::internal::scoped_array< T >::scoped_array (std::ptrdiff_t size) inline explicit
References Eigen::internal::size().
template<typename T> Eigen::internal::scoped_array< T >::~scoped_array () inline
Member Function Documentation
template<typename T> Eigen::internal::scoped_array< T >::operator const T * () const inline
template<typename T> T& Eigen::internal::scoped_array< T >::operator[] (std::ptrdiff_t i) inline
References i.
template<typename T> const T& Eigen::internal::scoped_array< T >::operator[] (std::ptrdiff_t i) const inline
References i.
template<typename T> T* & Eigen::internal::scoped_array< T >::ptr () inline
Referenced by Eigen::internal::CompressedStorage< Scalar, StorageIndex >::atWithInsertion(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::reallocate(), and Eigen::internal::swap().
template<typename T> const T* Eigen::internal::scoped_array< T >::ptr () const inline
Member Data Documentation
template<typename T> T* Eigen::internal::scoped_array< T >::m_ptr private
The documentation for this class was generated from the following file:
Memory.h