SmartMouse_2018: Eigen::DenseBase< Derived > Class Template Reference
Eigen::DenseBase< Derived > Class Template Reference
Base class for all dense matrices, vectors, and arrays.
#include <DenseBase.h>
Classes
struct CastXpr
struct ConstFixedBlockXpr
struct ConstFixedSegmentReturnType
struct ConstNColsBlockXpr
struct ConstNRowsBlockXpr
struct EIGEN_INDEXED_VIEW_METHOD_TYPE
struct FixedBlockXpr
struct FixedSegmentReturnType
struct IvcColType
struct IvcRowType
struct IvcType
struct NColsBlockXpr
struct NRowsBlockXpr
struct valid_indexed_view_overload
Public Types
enum {
RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime, ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime, SizeAtCompileTime, MaxRowsAtCompileTime = internal::traits<Derived>::MaxRowsAtCompileTime,
MaxColsAtCompileTime = internal::traits<Derived>::MaxColsAtCompileTime, MaxSizeAtCompileTime, IsVectorAtCompileTime, Flags = internal::traits<Derived>::Flags,
IsRowMajor = int(Flags) & RowMajorBit, InnerSizeAtCompileTime, InnerStrideAtCompileTime = internal::inner_stride_at_compile_time<Derived>::ret, OuterStrideAtCompileTime = internal::outer_stride_at_compile_time<Derived>::ret
}
enum { IsPlainObjectBase = 0 }
typedef Eigen::InnerIterator< Derived > InnerIterator
typedef internal::traits< Derived >::StorageKind StorageKind
typedef internal::traits< Derived >::StorageIndex StorageIndex
The type used to store indices.
typedef internal::traits< Derived >::Scalar Scalar
typedef Scalar value_type
typedef NumTraits< Scalar >::Real RealScalar
typedef DenseCoeffsBase< Derived > Base
typedef Base::CoeffReturnType CoeffReturnType
typedef internal::find_best_packet< Scalar, SizeAtCompileTime >::type PacketScalar
typedef Matrix< typename internal::traits< Derived >::Scalar, internal::traits< Derived >::RowsAtCompileTime, internal::traits< Derived >::ColsAtCompileTime, AutoAlign|(internal::traits< Derived >::Flags &RowMajorBit?RowMajor:ColMajor), internal::traits< Derived >::MaxRowsAtCompileTime, internal::traits< Derived >::MaxColsAtCompileTime > PlainMatrix
typedef Array< typename internal::traits< Derived >::Scalar, internal::traits< Derived >::RowsAtCompileTime, internal::traits< Derived >::ColsAtCompileTime, AutoAlign|(internal::traits< Derived >::Flags &RowMajorBit?RowMajor:ColMajor), internal::traits< Derived >::MaxRowsAtCompileTime, internal::traits< Derived >::MaxColsAtCompileTime > PlainArray
typedef internal::conditional< internal::is_same< typename internal::traits< Derived >::XprKind, MatrixXpr >::value, PlainMatrix, PlainArray >::type PlainObject
The plain matrix or array type corresponding to this expression.
typedef CwiseNullaryOp< internal::scalar_constant_op< Scalar >, PlainObject > ConstantReturnType
typedef CwiseNullaryOp< internal::linspaced_op< Scalar, PacketScalar >, PlainObject > SequentialLinSpacedReturnType
typedef CwiseNullaryOp< internal::linspaced_op< Scalar, PacketScalar >, PlainObject > RandomAccessLinSpacedReturnType
typedef Matrix< typename NumTraits< typename internal::traits< Derived >::Scalar >::Real, internal::traits< Derived >::ColsAtCompileTime, 1 > EigenvaluesReturnType
typedef Transpose< Derived > TransposeReturnType
typedef internal::add_const< Transpose< const Derived > >::type ConstTransposeReturnType
typedef internal::add_const_on_value_type< typename internal::eval< Derived >::type >::type EvalReturnType
typedef VectorwiseOp< Derived, Horizontal > RowwiseReturnType
typedef const VectorwiseOp< const Derived, Horizontal > ConstRowwiseReturnType
typedef VectorwiseOp< Derived, Vertical > ColwiseReturnType
typedef const VectorwiseOp< const Derived, Vertical > ConstColwiseReturnType
typedef CwiseNullaryOp< internal::scalar_random_op< Scalar >, PlainObject > RandomReturnType
typedef Reverse< Derived, BothDirections > ReverseReturnType
typedef const Reverse< const Derived, BothDirections > ConstReverseReturnType
typedef internal::conditional< NumTraits< Scalar >::IsComplex, const CwiseUnaryOp< internal::scalar_conjugate_op< Scalar >, const Derived >, const Derived & >::type ConjugateReturnType
typedef internal::conditional< NumTraits< Scalar >::IsComplex, const CwiseUnaryOp< internal::scalar_real_op< Scalar >, const Derived >, const Derived & >::type RealReturnType
typedef internal::conditional< NumTraits< Scalar >::IsComplex, CwiseUnaryView< internal::scalar_real_ref_op< Scalar >, Derived >, Derived & >::type NonConstRealReturnType
typedef CwiseUnaryOp< internal::scalar_imag_op< Scalar >, const Derived > ImagReturnType
typedef CwiseUnaryView< internal::scalar_imag_ref_op< Scalar >, Derived > NonConstImagReturnType
typedef CwiseUnaryOp< internal::scalar_opposite_op< Scalar >, const Derived > NegativeReturnType
typedef Block< Derived, internal::traits< Derived >::RowsAtCompileTime, 1,!IsRowMajor > ColXpr
typedef const Block< const Derived, internal::traits< Derived >::RowsAtCompileTime, 1,!IsRowMajor > ConstColXpr
typedef Block< Derived, 1, internal::traits< Derived >::ColsAtCompileTime, IsRowMajor > RowXpr
typedef const Block< const Derived, 1, internal::traits< Derived >::ColsAtCompileTime, IsRowMajor > ConstRowXpr
typedef Block< Derived, internal::traits< Derived >::RowsAtCompileTime, Dynamic,!IsRowMajor > ColsBlockXpr
typedef const Block< const Derived, internal::traits< Derived >::RowsAtCompileTime, Dynamic,!IsRowMajor > ConstColsBlockXpr
typedef Block< Derived, Dynamic, internal::traits< Derived >::ColsAtCompileTime, IsRowMajor > RowsBlockXpr
typedef const Block< const Derived, Dynamic, internal::traits< Derived >::ColsAtCompileTime, IsRowMajor > ConstRowsBlockXpr
typedef Block< Derived > BlockXpr
typedef const Block< const Derived > ConstBlockXpr
typedef VectorBlock< Derived > SegmentReturnType
typedef const VectorBlock< const Derived > ConstSegmentReturnType
Public Member Functions
EIGEN_DEVICE_FUNC Index nonZeros () const
EIGEN_DEVICE_FUNC Index outerSize () const
EIGEN_DEVICE_FUNC Index innerSize () const
EIGEN_DEVICE_FUNC void resize (Index newSize)
EIGEN_DEVICE_FUNC void resize (Index rows, Index cols)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator= (const DenseBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator= (const DenseBase &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator= (const EigenBase< OtherDerived > &other)
Copies the generic expression other into *this.
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator+= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator-= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator= (const ReturnByValue< OtherDerived > &func)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & lazyAssign (const DenseBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC CommaInitializer< Derived > operator<< (const Scalar &s)
template<unsigned int Added, unsigned int Removed>
EIGEN_DEPRECATED const Derived & flagged () const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC CommaInitializer< Derived > operator<< (const DenseBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC TransposeReturnType transpose ()
EIGEN_DEVICE_FUNC ConstTransposeReturnType transpose () const
EIGEN_DEVICE_FUNC void transposeInPlace ()
EIGEN_DEVICE_FUNC void fill (const Scalar &value)
EIGEN_DEVICE_FUNC Derived & setConstant (const Scalar &value)
EIGEN_DEVICE_FUNC Derived & setLinSpaced (Index size, const Scalar &low, const Scalar &high)
Sets a linearly spaced vector.
EIGEN_DEVICE_FUNC Derived & setLinSpaced (const Scalar &low, const Scalar &high)
Sets a linearly spaced vector.
EIGEN_DEVICE_FUNC Derived & setZero ()
EIGEN_DEVICE_FUNC Derived & setOnes ()
EIGEN_DEVICE_FUNC Derived & setRandom ()
template<typename OtherDerived >
EIGEN_DEVICE_FUNC bool isApprox (const DenseBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isMuchSmallerThan (const RealScalar &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC bool isMuchSmallerThan (const DenseBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isApproxToConstant (const Scalar &value, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isConstant (const Scalar &value, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isZero (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isOnes (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool hasNaN () const
bool allFinite () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator*= (const Scalar &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator/= (const Scalar &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EvalReturnType eval () const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC void swap (const DenseBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC void swap (PlainObjectBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC const NestByValue< Derived > nestByValue () const
EIGEN_DEVICE_FUNC const ForceAlignedAccess< Derived > forceAlignedAccess () const
EIGEN_DEVICE_FUNC ForceAlignedAccess< Derived > forceAlignedAccess ()
template<bool Enable>
EIGEN_DEVICE_FUNC const internal::conditional< Enable, ForceAlignedAccess< Derived >, Derived & >::type forceAlignedAccessIf () const
template<bool Enable>
EIGEN_DEVICE_FUNC internal::conditional< Enable, ForceAlignedAccess< Derived >, Derived & >::type forceAlignedAccessIf ()
EIGEN_DEVICE_FUNC Scalar sum () const
EIGEN_DEVICE_FUNC Scalar mean () const
EIGEN_DEVICE_FUNC Scalar trace () const
EIGEN_DEVICE_FUNC Scalar prod () const
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar minCoeff () const
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar maxCoeff () const
template<typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar minCoeff (IndexType *row, IndexType *col) const
template<typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar maxCoeff (IndexType *row, IndexType *col) const
template<typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar minCoeff (IndexType *index) const
template<typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar maxCoeff (IndexType *index) const
template<typename BinaryOp >
EIGEN_DEVICE_FUNC Scalar redux (const BinaryOp &func) const
template<typename Visitor >
EIGEN_DEVICE_FUNC void visit (Visitor &func) const
const WithFormat< Derived > format (const IOFormat &fmt) const
EIGEN_DEVICE_FUNC CoeffReturnType value () const
EIGEN_DEVICE_FUNC bool all () const
EIGEN_DEVICE_FUNC bool any () const
EIGEN_DEVICE_FUNC Index count () const
EIGEN_DEVICE_FUNC ConstRowwiseReturnType rowwise () const
EIGEN_DEVICE_FUNC RowwiseReturnType rowwise ()
EIGEN_DEVICE_FUNC ConstColwiseReturnType colwise () const
EIGEN_DEVICE_FUNC ColwiseReturnType colwise ()
template<typename ThenDerived , typename ElseDerived >
const Select< Derived, ThenDerived, ElseDerived > select (const DenseBase< ThenDerived > &thenMatrix, const DenseBase< ElseDerived > &elseMatrix) const
template<typename ThenDerived >
const Select< Derived, ThenDerived, typename ThenDerived::ConstantReturnType > select (const DenseBase< ThenDerived > &thenMatrix, const typename ThenDerived::Scalar &elseScalar) const
template<typename ElseDerived >
const Select< Derived, typename ElseDerived::ConstantReturnType, ElseDerived > select (const typename ElseDerived::Scalar &thenScalar, const DenseBase< ElseDerived > &elseMatrix) const
template<int p>
RealScalar lpNorm () const
template<int RowFactor, int ColFactor>
EIGEN_DEVICE_FUNC const Replicate< Derived, RowFactor, ColFactor > replicate () const
EIGEN_DEVICE_FUNC const Replicate< Derived, Dynamic, Dynamic > replicate (Index rowFactor, Index colFactor) const
EIGEN_DEVICE_FUNC ReverseReturnType reverse ()
EIGEN_DEVICE_FUNC ConstReverseReturnType reverse () const
EIGEN_DEVICE_FUNC void reverseInPlace ()
EIGEN_DEVICE_FUNC const NegativeReturnType operator- () const
template<typename NewType >
EIGEN_DEVICE_FUNC CastXpr< NewType >::Type cast () const
EIGEN_DEVICE_FUNC ConjugateReturnType conjugate () const
EIGEN_DEVICE_FUNC RealReturnType real () const
EIGEN_DEVICE_FUNC const ImagReturnType imag () const
template<typename CustomUnaryOp >
EIGEN_DEVICE_FUNC const CwiseUnaryOp< CustomUnaryOp, const Derived > unaryExpr (const CustomUnaryOp &func=CustomUnaryOp()) const
Apply a unary operator coefficient-wise.
template<typename CustomViewOp >
EIGEN_DEVICE_FUNC const CwiseUnaryView< CustomViewOp, const Derived > unaryViewExpr (const CustomViewOp &func=CustomViewOp()) const
EIGEN_DEVICE_FUNC NonConstRealReturnType real ()
EIGEN_DEVICE_FUNC NonConstImagReturnType imag ()
template<typename NRowsType , typename NColsType >
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type block (Index startRow, Index startCol, NRowsType blockRows, NColsType blockCols)
template<typename NRowsType , typename NColsType >
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type block (Index startRow, Index startCol, NRowsType blockRows, NColsType blockCols) const
This is the const version of block(Index,Index,NRowsType,NColsType)
template<typename NRowsType , typename NColsType >
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type topRightCorner (NRowsType cRows, NColsType cCols)
template<typename NRowsType , typename NColsType >
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type topRightCorner (NRowsType cRows, NColsType cCols) const
This is the const version of topRightCorner(NRowsType, NColsType).
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type topRightCorner ()
template<int CRows, int CCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type topRightCorner () const
This is the const version of topRightCorner<int, int>().
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type topRightCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
const ConstFixedBlockXpr< CRows, CCols >::Type topRightCorner (Index cRows, Index cCols) const
This is the const version of topRightCorner<int, int>(Index, Index).
template<typename NRowsType , typename NColsType >
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type topLeftCorner (NRowsType cRows, NColsType cCols)
template<typename NRowsType , typename NColsType >
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type topLeftCorner (NRowsType cRows, NColsType cCols) const
This is the const version of topLeftCorner(Index, Index).
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type topLeftCorner ()
template<int CRows, int CCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type topLeftCorner () const
This is the const version of topLeftCorner<int, int>().
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type topLeftCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
const ConstFixedBlockXpr< CRows, CCols >::Type topLeftCorner (Index cRows, Index cCols) const
This is the const version of topLeftCorner<int, int>(Index, Index).
template<typename NRowsType , typename NColsType >
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type bottomRightCorner (NRowsType cRows, NColsType cCols)
template<typename NRowsType , typename NColsType >
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type bottomRightCorner (NRowsType cRows, NColsType cCols) const
This is the const version of bottomRightCorner(NRowsType, NColsType).
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type bottomRightCorner ()
template<int CRows, int CCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type bottomRightCorner () const
This is the const version of bottomRightCorner<int, int>().
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type bottomRightCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
const ConstFixedBlockXpr< CRows, CCols >::Type bottomRightCorner (Index cRows, Index cCols) const
This is the const version of bottomRightCorner<int, int>(Index, Index).
template<typename NRowsType , typename NColsType >
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type bottomLeftCorner (NRowsType cRows, NColsType cCols)
template<typename NRowsType , typename NColsType >
EIGEN_DEVICE_FUNC ConstFixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type bottomLeftCorner (NRowsType cRows, NColsType cCols) const
This is the const version of bottomLeftCorner(NRowsType, NColsType).
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type bottomLeftCorner ()
template<int CRows, int CCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type bottomLeftCorner () const
This is the const version of bottomLeftCorner<int, int>().
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type bottomLeftCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
const ConstFixedBlockXpr< CRows, CCols >::Type bottomLeftCorner (Index cRows, Index cCols) const
This is the const version of bottomLeftCorner<int, int>(Index, Index).
template<typename NRowsType >
EIGEN_DEVICE_FUNC NRowsBlockXpr< internal::get_fixed_value< NRowsType >::value >::Type topRows (NRowsType n)
template<typename NRowsType >
EIGEN_DEVICE_FUNC const ConstNRowsBlockXpr< internal::get_fixed_value< NRowsType >::value >::Type topRows (NRowsType n) const
This is the const version of topRows(NRowsType).
template<int N>
EIGEN_DEVICE_FUNC NRowsBlockXpr< N >::Type topRows (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNRowsBlockXpr< N >::Type topRows (Index n=N) const
This is the const version of topRows<int>().
template<typename NRowsType >
EIGEN_DEVICE_FUNC NRowsBlockXpr< internal::get_fixed_value< NRowsType >::value >::Type bottomRows (NRowsType n)
template<typename NRowsType >
EIGEN_DEVICE_FUNC const ConstNRowsBlockXpr< internal::get_fixed_value< NRowsType >::value >::Type bottomRows (NRowsType n) const
This is the const version of bottomRows(NRowsType).
template<int N>
EIGEN_DEVICE_FUNC NRowsBlockXpr< N >::Type bottomRows (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNRowsBlockXpr< N >::Type bottomRows (Index n=N) const
This is the const version of bottomRows<int>().
template<typename NRowsType >
EIGEN_DEVICE_FUNC NRowsBlockXpr< internal::get_fixed_value< NRowsType >::value >::Type middleRows (Index startRow, NRowsType n)
template<typename NRowsType >
EIGEN_DEVICE_FUNC const ConstNRowsBlockXpr< internal::get_fixed_value< NRowsType >::value >::Type middleRows (Index startRow, NRowsType n) const
This is the const version of middleRows(Index,NRowsType).
template<int N>
EIGEN_DEVICE_FUNC NRowsBlockXpr< N >::Type middleRows (Index startRow, Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNRowsBlockXpr< N >::Type middleRows (Index startRow, Index n=N) const
This is the const version of middleRows<int>().
template<typename NColsType >
EIGEN_DEVICE_FUNC NColsBlockXpr< internal::get_fixed_value< NColsType >::value >::Type leftCols (NColsType n)
template<typename NColsType >
EIGEN_DEVICE_FUNC const ConstNColsBlockXpr< internal::get_fixed_value< NColsType >::value >::Type leftCols (NColsType n) const
This is the const version of leftCols(NColsType).
template<int N>
EIGEN_DEVICE_FUNC NColsBlockXpr< N >::Type leftCols (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNColsBlockXpr< N >::Type leftCols (Index n=N) const
This is the const version of leftCols<int>().
template<typename NColsType >
EIGEN_DEVICE_FUNC NColsBlockXpr< internal::get_fixed_value< NColsType >::value >::Type rightCols (NColsType n)
template<typename NColsType >
EIGEN_DEVICE_FUNC const ConstNColsBlockXpr< internal::get_fixed_value< NColsType >::value >::Type rightCols (NColsType n) const
This is the const version of rightCols(NColsType).
template<int N>
EIGEN_DEVICE_FUNC NColsBlockXpr< N >::Type rightCols (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNColsBlockXpr< N >::Type rightCols (Index n=N) const
This is the const version of rightCols<int>().
template<typename NColsType >
EIGEN_DEVICE_FUNC NColsBlockXpr< internal::get_fixed_value< NColsType >::value >::Type middleCols (Index startCol, NColsType numCols)
template<typename NColsType >
EIGEN_DEVICE_FUNC const ConstNColsBlockXpr< internal::get_fixed_value< NColsType >::value >::Type middleCols (Index startCol, NColsType numCols) const
This is the const version of middleCols(Index,NColsType).
template<int N>
EIGEN_DEVICE_FUNC NColsBlockXpr< N >::Type middleCols (Index startCol, Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNColsBlockXpr< N >::Type middleCols (Index startCol, Index n=N) const
This is the const version of middleCols<int>().
template<int NRows, int NCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol)
template<int NRows, int NCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol) const
This is the const version of block<>(Index, Index). */.
template<int NRows, int NCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol, Index blockRows, Index blockCols)
template<int NRows, int NCols>
const ConstFixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol, Index blockRows, Index blockCols) const
This is the const version of block<>(Index, Index, Index, Index).
EIGEN_DEVICE_FUNC ColXpr col (Index i)
EIGEN_DEVICE_FUNC ConstColXpr col (Index i) const
This is the const version of col().
EIGEN_DEVICE_FUNC RowXpr row (Index i)
EIGEN_DEVICE_FUNC ConstRowXpr row (Index i) const
This is the const version of row(). */.
template<typename NType >
EIGEN_DEVICE_FUNC FixedSegmentReturnType< internal::get_fixed_value< NType >::value >::Type segment (Index start, NType n)
template<typename NType >
EIGEN_DEVICE_FUNC const ConstFixedSegmentReturnType< internal::get_fixed_value< NType >::value >::Type segment (Index start, NType n) const
This is the const version of segment(Index,NType).
template<typename NType >
EIGEN_DEVICE_FUNC FixedSegmentReturnType< internal::get_fixed_value< NType >::value >::Type head (NType n)
template<typename NType >
EIGEN_DEVICE_FUNC const ConstFixedSegmentReturnType< internal::get_fixed_value< NType >::value >::Type head (NType n) const
This is the const version of head(NType).
template<typename NType >
EIGEN_DEVICE_FUNC FixedSegmentReturnType< internal::get_fixed_value< NType >::value >::Type tail (NType n)
template<typename NType >
EIGEN_DEVICE_FUNC const ConstFixedSegmentReturnType< internal::get_fixed_value< NType >::value >::Type tail (NType n) const
This is the const version of tail(Index).
template<int N>
EIGEN_DEVICE_FUNC FixedSegmentReturnType< N >::Type segment (Index start, Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType< N >::Type segment (Index start, Index n=N) const
This is the const version of segment<int>(Index).
template<int N>
EIGEN_DEVICE_FUNC FixedSegmentReturnType< N >::Type head (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType< N >::Type head (Index n=N) const
This is the const version of head<int>().
template<int N>
EIGEN_DEVICE_FUNC FixedSegmentReturnType< N >::Type tail (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType< N >::Type tail (Index n=N) const
This is the const version of tail<int>.
template<typename RowIndices , typename ColIndices >
internal::enable_if< valid_indexed_view_overload< RowIndices, ColIndices >::value &&internal::traits< typename EIGEN_INDEXED_VIEW_METHOD_TYPE< RowIndices, ColIndices >::type >::ReturnAsIndexedView, typename EIGEN_INDEXED_VIEW_METHOD_TYPE< RowIndices, ColIndices >::type >::type operator() (const RowIndices &rowIndices, const ColIndices &colIndices) EIGEN_INDEXED_VIEW_METHOD_CONST
template<typename RowIndices , typename ColIndices >
internal::enable_if< valid_indexed_view_overload< RowIndices, ColIndices >::value &&internal::traits< typename EIGEN_INDEXED_VIEW_METHOD_TYPE< RowIndices, ColIndices >::type >::ReturnAsBlock, typename internal::traits< typename EIGEN_INDEXED_VIEW_METHOD_TYPE< RowIndices, ColIndices >::type >::BlockType >::type operator() (const RowIndices &rowIndices, const ColIndices &colIndices) EIGEN_INDEXED_VIEW_METHOD_CONST
template<typename RowIndices , typename ColIndices >
internal::enable_if< valid_indexed_view_overload< RowIndices, ColIndices >::value &&internal::traits< typename EIGEN_INDEXED_VIEW_METHOD_TYPE< RowIndices, ColIndices >::type >::ReturnAsScalar, CoeffReturnType >::type operator() (const RowIndices &rowIndices, const ColIndices &colIndices) EIGEN_INDEXED_VIEW_METHOD_CONST
template<typename Indices >
internal::enable_if< IsRowMajor &&(!(internal::get_compile_time_incr< typename IvcType< Indices >::type >::value==1||internal::is_valid_index_type< Indices >::value)), IndexedView< EIGEN_INDEXED_VIEW_METHOD_CONST Derived, IvcIndex, typename IvcType< Indices >::type > >::type operator() (const Indices &indices) EIGEN_INDEXED_VIEW_METHOD_CONST
template<typename Indices >
internal::enable_if< (!IsRowMajor)&&(!(internal::get_compile_time_incr< typename IvcType< Indices >::type >::value==1||internal::is_valid_index_type< Indices >::value)), IndexedView< EIGEN_INDEXED_VIEW_METHOD_CONST Derived, typename IvcType< Indices >::type, IvcIndex > >::type operator() (const Indices &indices) EIGEN_INDEXED_VIEW_METHOD_CONST
template<typename Indices >
internal::enable_if< (internal::get_compile_time_incr< typename IvcType< Indices >::type >::value==1)&&(!internal::is_valid_index_type< Indices >::value)&&(!Symbolic::is_symbolic< Indices >::value), VectorBlock< EIGEN_INDEXED_VIEW_METHOD_CONST Derived, internal::array_size< Indices >::value > >::type operator() (const Indices &indices) EIGEN_INDEXED_VIEW_METHOD_CONST
template<typename IndexType >
internal::enable_if< Symbolic::is_symbolic< IndexType >::value, CoeffReturnType >::type operator() (const IndexType &id) EIGEN_INDEXED_VIEW_METHOD_CONST
template<typename RowIndices , typename ColIndices >
internal::enable_if< valid_indexed_view_overload< RowIndices, ColIndices >::value &&internal::traits< typename EIGEN_INDEXED_VIEW_METHOD_TYPE< RowIndices, ColIndices >::type >::ReturnAsIndexedView, typename EIGEN_INDEXED_VIEW_METHOD_TYPE< RowIndices, ColIndices >::type >::type operator() (const RowIndices &rowIndices, const ColIndices &colIndices) EIGEN_INDEXED_VIEW_METHOD_CONST
template<typename RowIndices , typename ColIndices >
internal::enable_if< valid_indexed_view_overload< RowIndices, ColIndices >::value &&internal::traits< typename EIGEN_INDEXED_VIEW_METHOD_TYPE< RowIndices, ColIndices >::type >::ReturnAsBlock, typename internal::traits< typename EIGEN_INDEXED_VIEW_METHOD_TYPE< RowIndices, ColIndices >::type >::BlockType >::type operator() (const RowIndices &rowIndices, const ColIndices &colIndices) EIGEN_INDEXED_VIEW_METHOD_CONST
template<typename RowIndices , typename ColIndices >
internal::enable_if< valid_indexed_view_overload< RowIndices, ColIndices >::value &&internal::traits< typename EIGEN_INDEXED_VIEW_METHOD_TYPE< RowIndices, ColIndices >::type >::ReturnAsScalar, CoeffReturnType >::type operator() (const RowIndices &rowIndices, const ColIndices &colIndices) EIGEN_INDEXED_VIEW_METHOD_CONST
template<typename Indices >
internal::enable_if< IsRowMajor &&(!(internal::get_compile_time_incr< typename IvcType< Indices >::type >::value==1||internal::is_valid_index_type< Indices >::value)), IndexedView< EIGEN_INDEXED_VIEW_METHOD_CONST Derived, IvcIndex, typename IvcType< Indices >::type > >::type operator() (const Indices &indices) EIGEN_INDEXED_VIEW_METHOD_CONST
template<typename Indices >
internal::enable_if< (!IsRowMajor)&&(!(internal::get_compile_time_incr< typename IvcType< Indices >::type >::value==1||internal::is_valid_index_type< Indices >::value)), IndexedView< EIGEN_INDEXED_VIEW_METHOD_CONST Derived, typename IvcType< Indices >::type, IvcIndex > >::type operator() (const Indices &indices) EIGEN_INDEXED_VIEW_METHOD_CONST
template<typename Indices >
internal::enable_if< (internal::get_compile_time_incr< typename IvcType< Indices >::type >::value==1)&&(!internal::is_valid_index_type< Indices >::value)&&(!Symbolic::is_symbolic< Indices >::value), VectorBlock< EIGEN_INDEXED_VIEW_METHOD_CONST Derived, internal::array_size< Indices >::value > >::type operator() (const Indices &indices) EIGEN_INDEXED_VIEW_METHOD_CONST
template<typename IndexType >
internal::enable_if< Symbolic::is_symbolic< IndexType >::value, CoeffReturnType >::type operator() (const IndexType &id) EIGEN_INDEXED_VIEW_METHOD_CONST
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & lazyAssign (const DenseBase< OtherDerived > &other)
template<typename CustomNullaryOp >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseNullaryOp< CustomNullaryOp, typename DenseBase< Derived >::PlainObject > NullaryExpr (Index rows, Index cols, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseNullaryOp< CustomNullaryOp, typename DenseBase< Derived >::PlainObject > NullaryExpr (Index size, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseNullaryOp< CustomNullaryOp, typename DenseBase< Derived >::PlainObject > NullaryExpr (const CustomNullaryOp &func)
template<typename Derived >
EIGEN_DEVICE_FUNC bool isMuchSmallerThan (const typename NumTraits< Scalar >::Real &other, const RealScalar &prec) const
template<typename Func >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar redux (const Func &func) const
Static Public Member Functions
static EIGEN_DEVICE_FUNC const ConstantReturnType Constant (Index rows, Index cols, const Scalar &value)
static EIGEN_DEVICE_FUNC const ConstantReturnType Constant (Index size, const Scalar &value)
static EIGEN_DEVICE_FUNC const ConstantReturnType Constant (const Scalar &value)
static EIGEN_DEVICE_FUNC const SequentialLinSpacedReturnType LinSpaced (Sequential_t, Index size, const Scalar &low, const Scalar &high)
static EIGEN_DEVICE_FUNC const RandomAccessLinSpacedReturnType LinSpaced (Index size, const Scalar &low, const Scalar &high)
Sets a linearly spaced vector.
static EIGEN_DEVICE_FUNC const SequentialLinSpacedReturnType LinSpaced (Sequential_t, const Scalar &low, const Scalar &high)
static EIGEN_DEVICE_FUNC const RandomAccessLinSpacedReturnType LinSpaced (const Scalar &low, const Scalar &high)
Sets a linearly spaced vector.
template<typename CustomNullaryOp >
static EIGEN_DEVICE_FUNC const CwiseNullaryOp< CustomNullaryOp, PlainObject > NullaryExpr (Index rows, Index cols, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
static EIGEN_DEVICE_FUNC const CwiseNullaryOp< CustomNullaryOp, PlainObject > NullaryExpr (Index size, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
static EIGEN_DEVICE_FUNC const CwiseNullaryOp< CustomNullaryOp, PlainObject > NullaryExpr (const CustomNullaryOp &func)
static EIGEN_DEVICE_FUNC const ConstantReturnType Zero (Index rows, Index cols)
static EIGEN_DEVICE_FUNC const ConstantReturnType Zero (Index size)
static EIGEN_DEVICE_FUNC const ConstantReturnType Zero ()
static EIGEN_DEVICE_FUNC const ConstantReturnType Ones (Index rows, Index cols)
static EIGEN_DEVICE_FUNC const ConstantReturnType Ones (Index size)
static EIGEN_DEVICE_FUNC const ConstantReturnType Ones ()
static const RandomReturnType Random (Index rows, Index cols)
static const RandomReturnType Random (Index size)
static const RandomReturnType Random ()
Protected Types
typedef internal::IndexedViewCompatibleType< Index, 1 >::type IvcIndex
Protected Member Functions
template<typename Indices >
IvcRowType< Indices >::type ivcRow (const Indices &indices) const
template<typename Indices >
IvcColType< Indices >::type ivcCol (const Indices &indices) const
template<typename Indices >
IvcColType< Indices >::type ivcSize (const Indices &indices) const
EIGEN_DEVICE_FUNC DenseBase ()
Private Member Functions
EIGEN_DEVICE_FUNC DenseBase (int)
EIGEN_DEVICE_FUNC DenseBase (int, int)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC DenseBase (const DenseBase< OtherDerived > &)
Related Functions
(Note that these are not member functions.)
template<typename Derived >
std::ostream & operator<< (std::ostream &s, const DenseBase< Derived > &m)
Detailed Description
template<typename Derived>
class Eigen::DenseBase< Derived >
Base class for all dense matrices, vectors, and arrays.
This class is the base that is inherited by all dense objects (matrix, vector, arrays, and related expression types). The common Eigen API for dense objects is contained in this class.
Template Parameters
Derived is the derived type, e.g., a matrix type or an expression.
This class can be extended with the help of the plugin mechanism described on the page TopicCustomizing_Plugins by defining the preprocessor symbol EIGEN_DENSEBASE_PLUGIN.
See also
TopicClassHierarchy
Member Typedef Documentation
template<typename Derived> typedef DenseCoeffsBase<Derived> Eigen::DenseBase< Derived >::Base
template<typename Derived> typedef Block<Derived> Eigen::DenseBase< Derived >::BlockXpr
template<typename Derived> typedef Base::CoeffReturnType Eigen::DenseBase< Derived >::CoeffReturnType
template<typename Derived> typedef Block<Derived, internal::traits<Derived>::RowsAtCompileTime, Dynamic, !IsRowMajor> Eigen::DenseBase< Derived >::ColsBlockXpr
template<typename Derived> typedef VectorwiseOp<Derived, Vertical> Eigen::DenseBase< Derived >::ColwiseReturnType
template<typename Derived> typedef Block<Derived, internal::traits<Derived>::RowsAtCompileTime, 1, !IsRowMajor> Eigen::DenseBase< Derived >::ColXpr
template<typename Derived> typedef internal::conditional<NumTraits<Scalar>::IsComplex, const CwiseUnaryOp<internal::scalar_conjugate_op<Scalar>, const Derived>, const Derived& >::type Eigen::DenseBase< Derived >::ConjugateReturnType
template<typename Derived> typedef CwiseNullaryOp<internal::scalar_constant_op<Scalar>,PlainObject> Eigen::DenseBase< Derived >::ConstantReturnType
template<typename Derived> typedef const Block<const Derived> Eigen::DenseBase< Derived >::ConstBlockXpr
template<typename Derived> typedef const Block<const Derived, internal::traits<Derived>::RowsAtCompileTime, Dynamic, !IsRowMajor> Eigen::DenseBase< Derived >::ConstColsBlockXpr
template<typename Derived> typedef const VectorwiseOp<const Derived, Vertical> Eigen::DenseBase< Derived >::ConstColwiseReturnType
template<typename Derived> typedef const Block<const Derived, internal::traits<Derived>::RowsAtCompileTime, 1, !IsRowMajor> Eigen::DenseBase< Derived >::ConstColXpr
template<typename Derived> typedef const Reverse<const Derived, BothDirections> Eigen::DenseBase< Derived >::ConstReverseReturnType
template<typename Derived> typedef const Block<const Derived, Dynamic, internal::traits<Derived>::ColsAtCompileTime, IsRowMajor> Eigen::DenseBase< Derived >::ConstRowsBlockXpr
template<typename Derived> typedef const VectorwiseOp<const Derived, Horizontal> Eigen::DenseBase< Derived >::ConstRowwiseReturnType
template<typename Derived> typedef const Block<const Derived, 1, internal::traits<Derived>::ColsAtCompileTime, IsRowMajor> Eigen::DenseBase< Derived >::ConstRowXpr
template<typename Derived> typedef const VectorBlock<const Derived> Eigen::DenseBase< Derived >::ConstSegmentReturnType
template<typename Derived> typedef internal::add_const<Transpose<const Derived> >::type Eigen::DenseBase< Derived >::ConstTransposeReturnType
template<typename Derived> typedef Matrix<typename NumTraits<typename internal::traits<Derived>::Scalar>::Real, internal::traits<Derived>::ColsAtCompileTime, 1> Eigen::DenseBase< Derived >::EigenvaluesReturnType
template<typename Derived> typedef internal::add_const_on_value_type<typename internal::eval<Derived>::type>::type Eigen::DenseBase< Derived >::EvalReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_imag_op<Scalar>, const Derived> Eigen::DenseBase< Derived >::ImagReturnType
template<typename Derived> typedef Eigen::InnerIterator<Derived> Eigen::DenseBase< Derived >::InnerIterator
Inner iterator type to iterate over the coefficients of a row or column.
See also
class InnerIterator
template<typename Derived> typedef internal::IndexedViewCompatibleType<Index,1>::type Eigen::DenseBase< Derived >::IvcIndex protected
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_opposite_op<Scalar>, const Derived> Eigen::DenseBase< Derived >::NegativeReturnType
template<typename Derived> typedef CwiseUnaryView<internal::scalar_imag_ref_op<Scalar>, Derived> Eigen::DenseBase< Derived >::NonConstImagReturnType
template<typename Derived> typedef internal::conditional<NumTraits<Scalar>::IsComplex, CwiseUnaryView<internal::scalar_real_ref_op<Scalar>, Derived>, Derived& >::type Eigen::DenseBase< Derived >::NonConstRealReturnType
template<typename Derived> typedef internal::find_best_packet<Scalar,SizeAtCompileTime>::type Eigen::DenseBase< Derived >::PacketScalar
template<typename Derived> typedef Array<typename internal::traits<Derived>::Scalar, internal::traits<Derived>::RowsAtCompileTime, internal::traits<Derived>::ColsAtCompileTime, AutoAlign | (internal::traits<Derived>::Flags&RowMajorBit ? RowMajor : ColMajor), internal::traits<Derived>::MaxRowsAtCompileTime, internal::traits<Derived>::MaxColsAtCompileTime > Eigen::DenseBase< Derived >::PlainArray
The plain array type corresponding to this expression.
See also
PlainObject
template<typename Derived> typedef Matrix<typename internal::traits<Derived>::Scalar, internal::traits<Derived>::RowsAtCompileTime, internal::traits<Derived>::ColsAtCompileTime, AutoAlign | (internal::traits<Derived>::Flags&RowMajorBit ? RowMajor : ColMajor), internal::traits<Derived>::MaxRowsAtCompileTime, internal::traits<Derived>::MaxColsAtCompileTime > Eigen::DenseBase< Derived >::PlainMatrix
The plain matrix type corresponding to this expression.
See also
PlainObject
template<typename Derived> typedef internal::conditional<internal::is_same<typename internal::traits<Derived>::XprKind,MatrixXpr >::value, PlainMatrix, PlainArray>::type Eigen::DenseBase< Derived >::PlainObject
The plain matrix or array type corresponding to this expression.
This is not necessarily exactly the return type of eval(). In the case of plain matrices, the return type of eval() is a const reference to a matrix, not a matrix! It is however guaranteed that the return type of eval() is either PlainObject or const PlainObject&.
template<typename Derived> typedef CwiseNullaryOp<internal::linspaced_op<Scalar,PacketScalar>,PlainObject> Eigen::DenseBase< Derived >::RandomAccessLinSpacedReturnType
template<typename Derived> typedef CwiseNullaryOp<internal::scalar_random_op<Scalar>,PlainObject> Eigen::DenseBase< Derived >::RandomReturnType
template<typename Derived> typedef internal::conditional<NumTraits<Scalar>::IsComplex, const CwiseUnaryOp<internal::scalar_real_op<Scalar>, const Derived>, const Derived& >::type Eigen::DenseBase< Derived >::RealReturnType
template<typename Derived> typedef NumTraits<Scalar>::Real Eigen::DenseBase< Derived >::RealScalar
template<typename Derived> typedef Reverse<Derived, BothDirections> Eigen::DenseBase< Derived >::ReverseReturnType
template<typename Derived> typedef Block<Derived, Dynamic, internal::traits<Derived>::ColsAtCompileTime, IsRowMajor> Eigen::DenseBase< Derived >::RowsBlockXpr
template<typename Derived> typedef VectorwiseOp<Derived, Horizontal> Eigen::DenseBase< Derived >::RowwiseReturnType
template<typename Derived> typedef Block<Derived, 1, internal::traits<Derived>::ColsAtCompileTime, IsRowMajor> Eigen::DenseBase< Derived >::RowXpr
template<typename Derived> typedef internal::traits<Derived>::Scalar Eigen::DenseBase< Derived >::Scalar
The numeric type of the expression' coefficients, e.g. float, double, int or std::complex<float>, etc.
template<typename Derived> typedef VectorBlock<Derived> Eigen::DenseBase< Derived >::SegmentReturnType
template<typename Derived> typedef CwiseNullaryOp<internal::linspaced_op<Scalar,PacketScalar>,PlainObject> Eigen::DenseBase< Derived >::SequentialLinSpacedReturnType
template<typename Derived> typedef internal::traits<Derived>::StorageIndex Eigen::DenseBase< Derived >::StorageIndex
The type used to store indices.
This typedef is relevant for types that store multiple indices such as PermutationMatrix or Transpositions, otherwise it defaults to Eigen::Index
See also
TopicPreprocessorDirectives, Eigen::Index, SparseMatrixBase.
template<typename Derived> typedef internal::traits<Derived>::StorageKind Eigen::DenseBase< Derived >::StorageKind
template<typename Derived> typedef Transpose<Derived> Eigen::DenseBase< Derived >::TransposeReturnType
template<typename Derived> typedef Scalar Eigen::DenseBase< Derived >::value_type
The numeric type of the expression' coefficients, e.g. float, double, int or std::complex<float>, etc.
It is an alias for the Scalar type
Member Enumeration Documentation
template<typename Derived> anonymous enum
Enumerator
RowsAtCompileTime
The number of rows at compile-time. This is just a copy of the value provided by the Derived type. If a value is not known at compile-time, it is set to the Dynamic constant.
See also
MatrixBase::rows(), MatrixBase::cols(), ColsAtCompileTime, SizeAtCompileTime
ColsAtCompileTime
The number of columns at compile-time. This is just a copy of the value provided by the Derived type. If a value is not known at compile-time, it is set to the Dynamic constant.
See also
MatrixBase::rows(), MatrixBase::cols(), RowsAtCompileTime, SizeAtCompileTime
SizeAtCompileTime
This is equal to the number of coefficients, i.e. the number of rows times the number of columns, or to Dynamic if this is not known at compile-time.
See also
RowsAtCompileTime, ColsAtCompileTime
MaxRowsAtCompileTime
This value is equal to the maximum possible number of rows that this expression might have. If this expression might have an arbitrarily high number of rows, this value is set to Dynamic.
This value is useful to know when evaluating an expression, in order to determine whether it is possible to avoid doing a dynamic memory allocation.
See also
RowsAtCompileTime, MaxColsAtCompileTime, MaxSizeAtCompileTime
MaxColsAtCompileTime
This value is equal to the maximum possible number of columns that this expression might have. If this expression might have an arbitrarily high number of columns, this value is set to Dynamic.
This value is useful to know when evaluating an expression, in order to determine whether it is possible to avoid doing a dynamic memory allocation.
See also
ColsAtCompileTime, MaxRowsAtCompileTime, MaxSizeAtCompileTime
MaxSizeAtCompileTime
This value is equal to the maximum possible number of coefficients that this expression might have. If this expression might have an arbitrarily high number of coefficients, this value is set to Dynamic.
This value is useful to know when evaluating an expression, in order to determine whether it is possible to avoid doing a dynamic memory allocation.
See also
SizeAtCompileTime, MaxRowsAtCompileTime, MaxColsAtCompileTime
IsVectorAtCompileTime
This is set to true if either the number of rows or the number of columns is known at compile-time to be equal to 1. Indeed, in that case, we are dealing with a column-vector (if there is only one column) or with a row-vector (if there is only one row).
Flags
This stores expression Flags flags which may or may not be inherited by new expressions constructed from this one. See the list of flags.
IsRowMajor
True if this expression has row-major storage order.
InnerSizeAtCompileTime
InnerStrideAtCompileTime
OuterStrideAtCompileTime
template<typename Derived> anonymous enum
Enumerator
IsPlainObjectBase
Constructor & Destructor Documentation
template<typename Derived> EIGEN_DEVICE_FUNC Eigen::DenseBase< Derived >::DenseBase () inline protected
Default constructor. Do nothing.
template<typename Derived> EIGEN_DEVICE_FUNC Eigen::DenseBase< Derived >::DenseBase (int) explicit private
template<typename Derived> EIGEN_DEVICE_FUNC Eigen::DenseBase< Derived >::DenseBase (int , int) private
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC Eigen::DenseBase< Derived >::DenseBase (const DenseBase< OtherDerived > &) explicit private
Member Function Documentation
template<typename Derived > EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::all () const inline
Returns
true if all coefficients are true
Example:
Output:
See also
any(), Cwise::operator<()
References Eigen::Dynamic, EIGEN_UNROLLING_LIMIT, i, and Eigen::internal::all_unroller< Derived, UnrollCount, Rows >::run().
template<typename Derived > bool Eigen::DenseBase< Derived >::allFinite () const inline
Returns
true if *this contains only finite numbers, i.e., no NaN and no +/-INF values.
See also
hasNaN()
template<typename Derived > EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::any () const inline
Returns
true if at least one coefficient is true
See also
all()
References Eigen::Dynamic, EIGEN_UNROLLING_LIMIT, i, and Eigen::internal::all_unroller< Derived, UnrollCount, Rows >::run().
template<typename Derived> template<typename NRowsType , typename NColsType > EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<internal::get_fixed_value<NRowsType>::value,internal::get_fixed_value<NColsType>::value>::Type Eigen::DenseBase< Derived >::block (Index startRow, Index startCol, NRowsType blockRows, NColsType blockCols) inline
Returns
an expression of a block in *this with either dynamic or fixed sizes.
Parameters
startRow the first row in the block
startCol the first column in the block
blockRows number of rows in the block, specified at either run-time or compile-time
blockCols number of columns in the block, specified at either run-time or compile-time
Template Parameters
NRowsType the type of the value handling the number of rows in the block, typically Index.
NColsType the type of the value handling the number of columns in the block, typically Index.
Example using runtime (aka dynamic) sizes:
Output:
{3.4}:
The number of rows blockRows and columns blockCols can also be specified at compile-time by passing Eigen::fix<N>, or Eigen::fix<N>(n) as arguments. In the later case, n plays the role of a runtime fallback value in case N equals Eigen::Dynamic. Here is an example with a fixed number of rows NRows and dynamic number of columns cols:
mat.block(i,j,fix<NRows>,cols)
This function thus fully covers the features offered by the following overloads block<NRows,NCols>(Index, Index), and block<NRows,NCols>(Index, Index, Index, Index) that are thus obsolete. Indeed, this generic version avoids redundancy, it preserves the argument order, and prevents the need to rely on the template keyword in templated code.
but with less redundancy and more consistency as it does not modify the argument order and seamlessly enable hybrid fixed/dynamic sizes.
Note
Even in the case that the returned expression has dynamic size, in the case when it is applied to a fixed-size matrix, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See also
class Block, fix, fix<N>(int)
Referenced by Eigen::internal::conservative_resize_like_impl< Derived, OtherDerived, false >::run().
template<typename Derived> template<typename NRowsType , typename NColsType > EIGEN_DEVICE_FUNC const ConstFixedBlockXpr<internal::get_fixed_value<NRowsType>::value,internal::get_fixed_value<NColsType>::value>::Type Eigen::DenseBase< Derived >::block (Index startRow, Index startCol, NRowsType blockRows, NColsType blockCols) const inline
This is the const version of block(Index,Index,NRowsType,NColsType)
template<typename Derived> template<int NRows, int NCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<NRows,NCols>::Type Eigen::DenseBase< Derived >::block (Index startRow, Index startCol) inline
Returns
a fixed-size expression of a block of *this.
The template parameters NRows and NCols are the number of rows and columns in the block.
Parameters
startRow the first row in the block
startCol the first column in the block
Example:
Output:
Note
The usage of of this overload is discouraged from Eigen 3.4, better used the generic block(Index,Index,NRowsType,NColsType), here is the one-to-one equivalence:
mat.template block<NRows,NCols>(i,j)  <-->  mat.block(i,j,fix<NRows>,fix<NCols>)
since block is a templated member, the keyword template has to be used if the matrix type is also a template parameter:
m.template block<3,3>(1,1);
See also
block(Index,Index,NRowsType,NColsType), class Block
template<typename Derived> template<int NRows, int NCols> EIGEN_DEVICE_FUNC const ConstFixedBlockXpr<NRows,NCols>::Type Eigen::DenseBase< Derived >::block (Index startRow, Index startCol) const inline
This is the const version of block<>(Index, Index). */.
template<typename Derived> template<int NRows, int NCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr<NRows,NCols>::Type Eigen::DenseBase< Derived >::block (Index startRow, Index startCol, Index blockRows, Index blockCols) inline
Returns
an expression of a block of *this.
Template Parameters
NRows number of rows in block as specified at compile-time
NCols number of columns in block as specified at compile-time
Parameters
startRow the first row in the block
startCol the first column in the block
blockRows number of rows in block as specified at run-time
blockCols number of columns in block as specified at run-time
This function is mainly useful for blocks where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, blockRows should equal NRows unless NRows is Dynamic, and the same for the number of columns.
Example:
Output:
Note
The usage of of this overload is discouraged from Eigen 3.4, better used the generic block(Index,Index,NRowsType,NColsType), here is the one-to-one complete equivalence:
mat.template block<NRows,NCols>(i,j,rows,cols)     <-->  mat.block(i,j,fix<NRows>(rows),fix<NCols>(cols))
If we known that, e.g., NRows==Dynamic and NCols!=Dynamic, then the equivalence becomes:
mat.template block<Dynamic,NCols>(i,j,rows,NCols)  <-->  mat.block(i,j,rows,fix<NCols>)
See also
block(Index,Index,NRowsType,NColsType), class Block
template<typename Derived> template<int NRows, int NCols> const ConstFixedBlockXpr<NRows,NCols>::Type Eigen::DenseBase< Derived >::block (Index startRow, Index startCol, Index blockRows, Index blockCols) const inline
This is the const version of block<>(Index, Index, Index, Index).
template<typename Derived> template<typename NRowsType , typename NColsType > EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<internal::get_fixed_value<NRowsType>::value,internal::get_fixed_value<NColsType>::value>::Type Eigen::DenseBase< Derived >::bottomLeftCorner (NRowsType cRows, NColsType cCols) inline
Returns
an expression of a bottom-left corner of *this with either dynamic or fixed sizes.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Template Parameters
NRowsType the type of the value handling the number of rows in the block, typically Index.
NColsType the type of the value handling the number of columns in the block, typically Index.
Example:
Output:
The number of rows blockRows and columns blockCols can also be specified at compile-time by passing Eigen::fix<N>, or Eigen::fix<N>(n) as arguments. See block() for the details.
See also
block(Index,Index,NRowsType,NColsType), class Block
template<typename Derived> template<typename NRowsType , typename NColsType > EIGEN_DEVICE_FUNC ConstFixedBlockXpr<internal::get_fixed_value<NRowsType>::value,internal::get_fixed_value<NColsType>::value>::Type Eigen::DenseBase< Derived >::bottomLeftCorner (NRowsType cRows, NColsType cCols) const inline
This is the const version of bottomLeftCorner(NRowsType, NColsType).
template<typename Derived> template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<CRows,CCols>::Type Eigen::DenseBase< Derived >::bottomLeftCorner () inline
Returns
an expression of a fixed-size bottom-left corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Output:
See also
block(Index,Index,NRowsType,NColsType), class Block
template<typename Derived> template<int CRows, int CCols> EIGEN_DEVICE_FUNC const ConstFixedBlockXpr<CRows,CCols>::Type Eigen::DenseBase< Derived >::bottomLeftCorner () const inline
This is the const version of bottomLeftCorner<int, int>().
template<typename Derived> template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr<CRows,CCols>::Type Eigen::DenseBase< Derived >::bottomLeftCorner (Index cRows, Index cCols) inline
Returns
an expression of a bottom-left corner of *this.
Template Parameters
CRows number of rows in corner as specified at compile-time
CCols number of columns in corner as specified at compile-time
Parameters
cRows number of rows in corner as specified at run-time
cCols number of columns in corner as specified at run-time
This function is mainly useful for corners where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, cRows should equal CRows unless CRows is Dynamic, and the same for the number of columns.
Example:
Output:
See also
class Block
template<typename Derived> template<int CRows, int CCols> const ConstFixedBlockXpr<CRows,CCols>::Type Eigen::DenseBase< Derived >::bottomLeftCorner (Index cRows, Index cCols) const inline
This is the const version of bottomLeftCorner<int, int>(Index, Index).
template<typename Derived> template<typename NRowsType , typename NColsType > EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<internal::get_fixed_value<NRowsType>::value,internal::get_fixed_value<NColsType>::value>::Type Eigen::DenseBase< Derived >::bottomRightCorner (NRowsType cRows, NColsType cCols) inline
Returns
an expression of a bottom-right corner of *this with either dynamic or fixed sizes.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Template Parameters
NRowsType the type of the value handling the number of rows in the block, typically Index.
NColsType the type of the value handling the number of columns in the block, typically Index.
Example:
Output:
The number of rows blockRows and columns blockCols can also be specified at compile-time by passing Eigen::fix<N>, or Eigen::fix<N>(n) as arguments. See block() for the details.
See also
block(Index,Index,NRowsType,NColsType), class Block
Referenced by Eigen::internal::conservative_resize_like_impl< Derived, OtherDerived, false >::run().
template<typename Derived> template<typename NRowsType , typename NColsType > EIGEN_DEVICE_FUNC const ConstFixedBlockXpr<internal::get_fixed_value<NRowsType>::value,internal::get_fixed_value<NColsType>::value>::Type Eigen::DenseBase< Derived >::bottomRightCorner (NRowsType cRows, NColsType cCols) const inline
This is the const version of bottomRightCorner(NRowsType, NColsType).
template<typename Derived> template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<CRows,CCols>::Type Eigen::DenseBase< Derived >::bottomRightCorner () inline
Returns
an expression of a fixed-size bottom-right corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Output:
See also
block(Index,Index,NRowsType,NColsType), class Block
template<typename Derived> template<int CRows, int CCols> EIGEN_DEVICE_FUNC const ConstFixedBlockXpr<CRows,CCols>::Type Eigen::DenseBase< Derived >::bottomRightCorner () const inline
This is the const version of bottomRightCorner<int, int>().
template<typename Derived> template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr<CRows,CCols>::Type Eigen::DenseBase< Derived >::bottomRightCorner (Index cRows, Index cCols) inline
Returns
an expression of a bottom-right corner of *this.
Template Parameters
CRows number of rows in corner as specified at compile-time
CCols number of columns in corner as specified at compile-time
Parameters
cRows number of rows in corner as specified at run-time
cCols number of columns in corner as specified at run-time
This function is mainly useful for corners where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, cRows should equal CRows unless CRows is Dynamic, and the same for the number of columns.
Example:
Output:
See also
class Block
template<typename Derived> template<int CRows, int CCols> const ConstFixedBlockXpr<CRows,CCols>::Type Eigen::DenseBase< Derived >::bottomRightCorner (Index cRows, Index cCols) const inline
This is the const version of bottomRightCorner<int, int>(Index, Index).
template<typename Derived> template<typename NRowsType > EIGEN_DEVICE_FUNC NRowsBlockXpr<internal::get_fixed_value<NRowsType>::value>::Type Eigen::DenseBase< Derived >::bottomRows (NRowsType n) inline
Returns
a block consisting of the bottom rows of *this.
Parameters
n the number of rows in the block
Template Parameters
NRowsType the type of the value handling the number of rows in the block, typically Index.
Example:
Output:
The number of rows n can also be specified at compile-time by passing Eigen::fix<N>, or Eigen::fix<N>(n) as arguments. See block() for the details.
See also
block(Index,Index,NRowsType,NColsType), class Block
Referenced by Eigen::internal::conservative_resize_like_impl< Derived, OtherDerived, false >::run().
template<typename Derived> template<typename NRowsType > EIGEN_DEVICE_FUNC const ConstNRowsBlockXpr<internal::get_fixed_value<NRowsType>::value>::Type Eigen::DenseBase< Derived >::bottomRows (NRowsType n) const inline
This is the const version of bottomRows(NRowsType).
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC NRowsBlockXpr<N>::Type Eigen::DenseBase< Derived >::bottomRows (Index n = N) inline
Returns
a block consisting of the bottom rows of *this.
Template Parameters
N the number of rows in the block as specified at compile-time
Parameters
n the number of rows in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
block(Index,Index,NRowsType,NColsType), class Block
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC ConstNRowsBlockXpr<N>::Type Eigen::DenseBase< Derived >::bottomRows (Index n = N) const inline
This is the const version of bottomRows<int>().
template<typename Derived> template<typename NewType > EIGEN_DEVICE_FUNC CastXpr<NewType>::Type Eigen::DenseBase< Derived >::cast () const inline
Returns
an expression of *this with the Scalar type casted to NewScalar.
The template parameter NewScalar is the type we are casting the scalars to.
See also
class CwiseUnaryOp
template<typename Derived> EIGEN_DEVICE_FUNC ColXpr Eigen::DenseBase< Derived >::col (Index i) inline
Returns
an expression of the i-th column of *this. Note that the numbering starts at 0.
Example:
Output:
See also
row(), class Block
Referenced by Eigen::SparseLU< _MatrixType, _OrderingType >::_solve_impl(), and Eigen::UmfPackLU< _MatrixType >::_solve_impl().
template<typename Derived> EIGEN_DEVICE_FUNC ConstColXpr Eigen::DenseBase< Derived >::col (Index i) const inline
This is the const version of col().
template<typename Derived> EIGEN_DEVICE_FUNC ConstColwiseReturnType Eigen::DenseBase< Derived >::colwise () const inline
Returns
a VectorwiseOp wrapper of *this providing additional partial reduction operations
Example:
Output:
See also
rowwise(), class VectorwiseOp, TutorialReductionsVisitorsBroadcasting
Referenced by Eigen::umeyama().
template<typename Derived > EIGEN_DEVICE_FUNC DenseBase< Derived >::ColwiseReturnType Eigen::DenseBase< Derived >::colwise () inline
Returns
a writable VectorwiseOp wrapper of *this providing additional partial reduction operations
See also
rowwise(), class VectorwiseOp, TutorialReductionsVisitorsBroadcasting
template<typename Derived> EIGEN_DEVICE_FUNC ConjugateReturnType Eigen::DenseBase< Derived >::conjugate () const inline
Returns
an expression of the complex conjugate of *this.
See also
Math functions, MatrixBase::adjoint()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Constant (Index rows, Index cols, const Scalar & value) static
Returns
an expression of a constant matrix of value value
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this DenseBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Zero() should be used instead.
The template parameter CustomNullaryOp is the type of the functor.
See also
class CwiseNullaryOp
References EIGEN_STRONG_INLINE, and Eigen::DenseBase< Derived >::NullaryExpr().
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Constant (Index size, const Scalar & value) static
Returns
an expression of a constant matrix of value value
The parameter size is the size of the returned vector. Must be compatible with this DenseBase type.
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Zero() should be used instead.
The template parameter CustomNullaryOp is the type of the functor.
See also
class CwiseNullaryOp
References EIGEN_STRONG_INLINE, and Eigen::DenseBase< Derived >::NullaryExpr().
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Constant (const Scalar & value) static
Returns
an expression of a constant matrix of value value
This variant is only for fixed-size DenseBase types. For dynamic-size types, you need to use the variants taking size arguments.
The template parameter CustomNullaryOp is the type of the functor.
See also
class CwiseNullaryOp
References EIGEN_STATIC_ASSERT_FIXED_SIZE, EIGEN_STRONG_INLINE, and Eigen::DenseBase< Derived >::NullaryExpr().
template<typename Derived > EIGEN_DEVICE_FUNC Eigen::Index Eigen::DenseBase< Derived >::count () const inline
Returns
the number of coefficients which evaluate to true
See also
all(), any()
template<typename Derived> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EvalReturnType Eigen::DenseBase< Derived >::eval () const inline
Returns
the matrix or vector obtained by evaluating this expression.
Notice that in the case of a plain matrix or vector (not an expression) this function just returns a const reference, in order to avoid a useless copy.
Warning
Be carefull with eval() and the auto C++ keyword, as detailed in this page .
References type.
Referenced by Eigen::internal::generic_product_impl< Lhs, Homogeneous< RhsArg, Vertical >, TriangularShape, HomogeneousShape, ProductTag >::evalTo().
template<typename Derived> template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::DenseBase< Derived >::evalTo (Dest &) const inline
References EIGEN_STATIC_ASSERT.
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::DenseBase< Derived >::fill (const Scalar & val)
Alias for setConstant(): sets all coefficients in this expression to val.
See also
setConstant(), Constant(), class CwiseNullaryOp
template<typename Derived> template<unsigned int Added, unsigned int Removed> EIGEN_DEPRECATED const Derived& Eigen::DenseBase< Derived >::flagged () const inline
Deprecated:
it now returns *this
template<typename Derived> EIGEN_DEVICE_FUNC const ForceAlignedAccess<Derived> Eigen::DenseBase< Derived >::forceAlignedAccess () const inline
template<typename Derived> EIGEN_DEVICE_FUNC ForceAlignedAccess<Derived> Eigen::DenseBase< Derived >::forceAlignedAccess () inline
template<typename Derived> template<bool Enable> EIGEN_DEVICE_FUNC const internal::conditional<Enable,ForceAlignedAccess<Derived>,Derived&>::type Eigen::DenseBase< Derived >::forceAlignedAccessIf () const inline
template<typename Derived> template<bool Enable> EIGEN_DEVICE_FUNC internal::conditional<Enable,ForceAlignedAccess<Derived>,Derived&>::type Eigen::DenseBase< Derived >::forceAlignedAccessIf () inline
template<typename Derived> const WithFormat<Derived> Eigen::DenseBase< Derived >::format (const IOFormat & fmt) const inline
Returns
a WithFormat proxy object allowing to print a matrix the with given format fmt.
See class IOFormat for some examples.
See also
class IOFormat, class WithFormat
template<typename Derived > bool Eigen::DenseBase< Derived >::hasNaN () const inline
Returns
true is *this contains at least one Not A Number (NaN).
See also
allFinite()
References Eigen::placeholders::all.
template<typename Derived> template<typename NType > EIGEN_DEVICE_FUNC FixedSegmentReturnType<internal::get_fixed_value<NType>::value>::Type Eigen::DenseBase< Derived >::head (NType n) inline
Returns
an expression of the first coefficients of *this with either dynamic or fixed sizes.
Parameters
n the number of coefficients in the segment
Template Parameters
NType the type of the value handling the number of coefficients in the segment, typically Index.
Example:
Output:
The number of coefficients n can also be specified at compile-time by passing Eigen::fix<N>, or Eigen::fix<N>(n) as arguments. See block() for the details.
Note
Even in the case that the returned expression has dynamic size, in the case when it is applied to a fixed-size vector, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See also
class Block, block(Index,Index)
template<typename Derived> template<typename NType > EIGEN_DEVICE_FUNC const ConstFixedSegmentReturnType<internal::get_fixed_value<NType>::value>::Type Eigen::DenseBase< Derived >::head (NType n) const inline
This is the const version of head(NType).
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC FixedSegmentReturnType<N>::Type Eigen::DenseBase< Derived >::head (Index n = N) inline
Returns
a fixed-size expression of the first coefficients of *this.
Template Parameters
N the number of coefficients in the segment as specified at compile-time
Parameters
n the number of coefficients in the segment as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
head(NType), class Block
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType<N>::Type Eigen::DenseBase< Derived >::head (Index n = N) const inline
This is the const version of head<int>().
template<typename Derived> EIGEN_DEVICE_FUNC const ImagReturnType Eigen::DenseBase< Derived >::imag () const inline
Returns
an read-only expression of the imaginary part of *this.
See also
real()
template<typename Derived> EIGEN_DEVICE_FUNC NonConstImagReturnType Eigen::DenseBase< Derived >::imag () inline
Returns
a non const expression of the imaginary part of *this.
See also
real()
template<typename Derived> EIGEN_DEVICE_FUNC Index Eigen::DenseBase< Derived >::innerSize () const inline
Returns
the inner size.
Note
For a vector, this is just the size. For a matrix (non-vector), this is the minor dimension with respect to the storage order, i.e., the number of rows for a column-major matrix, and the number of columns for a row-major matrix.
References Eigen::internal::size().
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::isApprox (const DenseBase< OtherDerived > & other, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if *this is approximately equal to other, within the precision determined by prec.
Note
The fuzzy compares are done multiplicatively. Two vectors and are considered to be approximately equal within precision if
For matrices, the comparison is done using the Hilbert-Schmidt norm (aka Frobenius norm L2 norm).
Because of the multiplicativeness of this comparison, one can't use this function to check whether *this is approximately equal to the zero matrix or vector. Indeed, isApprox(zero) returns false unless *this itself is exactly the zero matrix or vector. If you want to test whether *this is zero, use internal::isMuchSmallerThan(const RealScalar&, RealScalar) instead.
See also
internal::isMuchSmallerThan(const RealScalar&, RealScalar) const
References Eigen::internal::isApprox_selector< Derived, OtherDerived, is_integer >::run().
template<typename Derived > EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::isApproxToConstant (const Scalar & val, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if all coefficients in this matrix are approximately equal to val, to within precision prec
References i, and Eigen::DenseBase< Derived >::isConstant().
Referenced by Eigen::DenseBase< Derived >::LinSpaced().
template<typename Derived > EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::isConstant (const Scalar & val, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
This is just an alias for isApproxToConstant().
Returns
true if all coefficients in this matrix are approximately equal to value, to within precision prec
Referenced by Eigen::DenseBase< Derived >::isApproxToConstant().
template<typename Derived> template<typename Derived > EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::isMuchSmallerThan (const typename NumTraits< Scalar >::Real & other, const RealScalar & prec) const
Returns
true if the norm of *this is much smaller than other, within the precision determined by prec.
Note
The fuzzy compares are done multiplicatively. A vector is considered to be much smaller than within precision if
For matrices, the comparison is done using the Hilbert-Schmidt norm. For this reason, the value of the reference scalar other should come from the Hilbert-Schmidt norm of a reference matrix of same dimensions.
See also
isApprox(), isMuchSmallerThan(const DenseBase<OtherDerived>&, RealScalar) const
References Eigen::internal::isMuchSmallerThan_scalar_selector< Derived, is_integer >::run().
template<typename Derived> EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::isMuchSmallerThan (const RealScalar & other, const RealScalar & prec = NumTraits< Scalar >::dummy_precision()) const
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::isMuchSmallerThan (const DenseBase< OtherDerived > & other, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if the norm of *this is much smaller than the norm of other, within the precision determined by prec.
Note
The fuzzy compares are done multiplicatively. A vector is considered to be much smaller than a vector within precision if
For matrices, the comparison is done using the Hilbert-Schmidt norm.
See also
isApprox(), isMuchSmallerThan(const RealScalar&, RealScalar) const
References Eigen::internal::isMuchSmallerThan_object_selector< Derived, OtherDerived, is_integer >::run().
template<typename Derived > EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::isOnes (const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if *this is approximately equal to the matrix where all coefficients are equal to 1, within the precision given by prec.
Example:
Output:
See also
class CwiseNullaryOp, Ones()
Referenced by Eigen::DenseBase< Derived >::Ones().
template<typename Derived > EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::isZero (const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if *this is approximately equal to the zero matrix, within the precision given by prec.
Example:
Output:
See also
class CwiseNullaryOp, Zero()
References i.
template<typename Derived> template<typename Indices > IvcColType<Indices>::type Eigen::DenseBase< Derived >::ivcCol (const Indices & indices) const inline protected
template<typename Derived> template<typename Indices > IvcRowType<Indices>::type Eigen::DenseBase< Derived >::ivcRow (const Indices & indices) const inline protected
template<typename Derived> template<typename Indices > IvcColType<Indices>::type Eigen::DenseBase< Derived >::ivcSize (const Indices & indices) const inline protected
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived& Eigen::DenseBase< Derived >::lazyAssign (const DenseBase< OtherDerived > & other)
References Eigen::internal::call_assignment_no_alias(), eigen_assert, EIGEN_STATIC_ASSERT, EIGEN_STATIC_ASSERT_LVALUE, and EIGEN_STATIC_ASSERT_SAME_MATRIX_SIZE.
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC Derived& Eigen::DenseBase< Derived >::lazyAssign (const DenseBase< OtherDerived > & other)
template<typename Derived> template<typename NColsType > EIGEN_DEVICE_FUNC NColsBlockXpr<internal::get_fixed_value<NColsType>::value>::Type Eigen::DenseBase< Derived >::leftCols (NColsType n) inline
Returns
a block consisting of the left columns of *this.
Parameters
n the number of columns in the block
Template Parameters
NColsType the type of the value handling the number of columns in the block, typically Index.
Example:
Output:
The number of columns n can also be specified at compile-time by passing Eigen::fix<N>, or Eigen::fix<N>(n) as arguments. See block() for the details.
See also
block(Index,Index,NRowsType,NColsType), class Block
template<typename Derived> template<typename NColsType > EIGEN_DEVICE_FUNC const ConstNColsBlockXpr<internal::get_fixed_value<NColsType>::value>::Type Eigen::DenseBase< Derived >::leftCols (NColsType n) const inline
This is the const version of leftCols(NColsType).
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC NColsBlockXpr<N>::Type Eigen::DenseBase< Derived >::leftCols (Index n = N) inline
Returns
a block consisting of the left columns of *this.
Template Parameters
N the number of columns in the block as specified at compile-time
Parameters
n the number of columns in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
block(Index,Index,NRowsType,NColsType), class Block
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC ConstNColsBlockXpr<N>::Type Eigen::DenseBase< Derived >::leftCols (Index n = N) const inline
This is the const version of leftCols<int>().
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::RandomAccessLinSpacedReturnType Eigen::DenseBase< Derived >::LinSpaced (Sequential_t , Index size, const Scalar & low, const Scalar & high) static
Deprecated:
because of accuracy loss. In Eigen 3.3, it is an alias for LinSpaced(Index,const Scalar&,const Scalar&)
See also
LinSpaced(Index,Scalar,Scalar), setLinSpaced(Index,const Scalar&,const Scalar&)
References EIGEN_STATIC_ASSERT_VECTOR_ONLY, EIGEN_STRONG_INLINE, and Eigen::DenseBase< Derived >::NullaryExpr().
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::RandomAccessLinSpacedReturnType Eigen::DenseBase< Derived >::LinSpaced (Index size, const Scalar & low, const Scalar & high) static
Sets a linearly spaced vector.
The function generates 'size' equally spaced values in the closed interval [low,high]. When size is set to 1, a vector of length 1 containing 'high' is returned.
Example:
Output:
For integer scalar types, an even spacing is possible if and only if the length of the range, i.e., high-low is a scalar multiple of size-1, or if size is a scalar multiple of the number of values high-low+1 (meaning each value can be repeated the same number of time). If one of these two considions is not satisfied, then high is lowered to the largest value satisfying one of this constraint. Here are some examples:
Example:
Output:
See also
setLinSpaced(Index,const Scalar&,const Scalar&), CwiseNullaryOp
References EIGEN_STATIC_ASSERT_VECTOR_ONLY, EIGEN_STRONG_INLINE, and Eigen::DenseBase< Derived >::NullaryExpr().
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::RandomAccessLinSpacedReturnType Eigen::DenseBase< Derived >::LinSpaced (Sequential_t , const Scalar & low, const Scalar & high) static
Deprecated:
because of accuracy loss. In Eigen 3.3, it is an alias for LinSpaced(const Scalar&,const Scalar&)
See also
LinSpaced(Scalar,Scalar)
References EIGEN_STATIC_ASSERT_FIXED_SIZE, EIGEN_STATIC_ASSERT_VECTOR_ONLY, EIGEN_STRONG_INLINE, and Eigen::DenseBase< Derived >::NullaryExpr().
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::RandomAccessLinSpacedReturnType Eigen::DenseBase< Derived >::LinSpaced (const Scalar & low, const Scalar & high) static
Sets a linearly spaced vector.
The function generates 'size' equally spaced values in the closed interval [low,high]. When size is set to 1, a vector of length 1 containing 'high' is returned.
Example:
Output:
For integer scalar types, an even spacing is possible if and only if the length of the range, i.e., high-low is a scalar multiple of size-1, or if size is a scalar multiple of the number of values high-low+1 (meaning each value can be repeated the same number of time). If one of these two considions is not satisfied, then high is lowered to the largest value satisfying one of this constraint. Here are some examples:
Example:
Output:
See also
setLinSpaced(Index,const Scalar&,const Scalar&), CwiseNullaryOp Special version for fixed size types which does not require the size parameter.
References EIGEN_STATIC_ASSERT_FIXED_SIZE, EIGEN_STATIC_ASSERT_VECTOR_ONLY, Eigen::DenseBase< Derived >::isApproxToConstant(), and Eigen::DenseBase< Derived >::NullaryExpr().
template<typename Derived> template<int p> RealScalar Eigen::DenseBase< Derived >::lpNorm () const
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::maxCoeff () const
Returns
the maximum of all coefficients of *this.
Warning
the result is undefined if *this contains NaN.
References EIGEN_STRONG_INLINE.
template<typename Derived > template<typename IndexType > EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::maxCoeff (IndexType * rowId, IndexType * colId) const
Returns
the maximum of all coefficients of *this and puts in *row and *col its location.
Warning
the result is undefined if *this contains NaN.
See also
DenseBase::minCoeff(IndexType*,IndexType*), DenseBase::visit(), DenseBase::maxCoeff()
References Eigen::internal::coeff_visitor< Derived >::col, Eigen::internal::coeff_visitor< Derived >::res, and Eigen::internal::coeff_visitor< Derived >::row.
template<typename Derived > template<typename IndexType > EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::maxCoeff (IndexType * index) const
Returns
the maximum of all coefficients of *this and puts in *index its location.
Warning
the result is undefined if *this contains NaN.
See also
DenseBase::maxCoeff(IndexType*,IndexType*), DenseBase::minCoeff(IndexType*,IndexType*), DenseBase::visitor(), DenseBase::maxCoeff()
References Eigen::internal::coeff_visitor< Derived >::col, EIGEN_STATIC_ASSERT_VECTOR_ONLY, Eigen::internal::coeff_visitor< Derived >::res, and Eigen::internal::coeff_visitor< Derived >::row.
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::mean () const
Returns
the mean of all coefficients of *this
See also
trace(), prod(), sum()
References EIGEN_STRONG_INLINE, and Eigen::internal::size().
template<typename Derived> template<typename NColsType > EIGEN_DEVICE_FUNC NColsBlockXpr<internal::get_fixed_value<NColsType>::value>::Type Eigen::DenseBase< Derived >::middleCols (Index startCol, NColsType numCols) inline
Returns
a block consisting of a range of columns of *this.
Parameters
startCol the index of the first column in the block
numCols the number of columns in the block
Template Parameters
NColsType the type of the value handling the number of columns in the block, typically Index.
Example:
Output:
The number of columns n can also be specified at compile-time by passing Eigen::fix<N>, or Eigen::fix<N>(n) as arguments. See block() for the details.
See also
block(Index,Index,NRowsType,NColsType), class Block
template<typename Derived> template<typename NColsType > EIGEN_DEVICE_FUNC const ConstNColsBlockXpr<internal::get_fixed_value<NColsType>::value>::Type Eigen::DenseBase< Derived >::middleCols (Index startCol, NColsType numCols) const inline
This is the const version of middleCols(Index,NColsType).
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC NColsBlockXpr<N>::Type Eigen::DenseBase< Derived >::middleCols (Index startCol, Index n = N) inline
Returns
a block consisting of a range of columns of *this.
Template Parameters
N the number of columns in the block as specified at compile-time
Parameters
startCol the index of the first column in the block
n the number of columns in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
block(Index,Index,NRowsType,NColsType), class Block
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC ConstNColsBlockXpr<N>::Type Eigen::DenseBase< Derived >::middleCols (Index startCol, Index n = N) const inline
This is the const version of middleCols<int>().
template<typename Derived> template<typename NRowsType > EIGEN_DEVICE_FUNC NRowsBlockXpr<internal::get_fixed_value<NRowsType>::value>::Type Eigen::DenseBase< Derived >::middleRows (Index startRow, NRowsType n) inline
Returns
a block consisting of a range of rows of *this.
Parameters
startRow the index of the first row in the block
n the number of rows in the block
Template Parameters
NRowsType the type of the value handling the number of rows in the block, typically Index.
Example:
Output:
The number of rows n can also be specified at compile-time by passing Eigen::fix<N>, or Eigen::fix<N>(n) as arguments. See block() for the details.
See also
block(Index,Index,NRowsType,NColsType), class Block
template<typename Derived> template<typename NRowsType > EIGEN_DEVICE_FUNC const ConstNRowsBlockXpr<internal::get_fixed_value<NRowsType>::value>::Type Eigen::DenseBase< Derived >::middleRows (Index startRow, NRowsType n) const inline
This is the const version of middleRows(Index,NRowsType).
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC NRowsBlockXpr<N>::Type Eigen::DenseBase< Derived >::middleRows (Index startRow, Index n = N) inline
Returns
a block consisting of a range of rows of *this.
Template Parameters
N the number of rows in the block as specified at compile-time
Parameters
startRow the index of the first row in the block
n the number of rows in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
block(Index,Index,NRowsType,NColsType), class Block
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC ConstNRowsBlockXpr<N>::Type Eigen::DenseBase< Derived >::middleRows (Index startRow, Index n = N) const inline
This is the const version of middleRows<int>().
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::minCoeff () const
Returns
the minimum of all coefficients of *this.
Warning
the result is undefined if *this contains NaN.
References EIGEN_STRONG_INLINE.
template<typename Derived > template<typename IndexType > EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::minCoeff (IndexType * rowId, IndexType * colId) const
Returns
the minimum of all coefficients of *this and puts in *row and *col its location.
Warning
the result is undefined if *this contains NaN.
See also
DenseBase::minCoeff(Index*), DenseBase::maxCoeff(Index*,Index*), DenseBase::visit(), DenseBase::minCoeff()
References Eigen::internal::coeff_visitor< Derived >::col, Eigen::internal::coeff_visitor< Derived >::res, and Eigen::internal::coeff_visitor< Derived >::row.
template<typename Derived > template<typename IndexType > EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::minCoeff (IndexType * index) const
Returns
the minimum of all coefficients of *this and puts in *index its location.
Warning
the result is undefined if *this contains NaN.
See also
DenseBase::minCoeff(IndexType*,IndexType*), DenseBase::maxCoeff(IndexType*,IndexType*), DenseBase::visit(), DenseBase::minCoeff()
References Eigen::internal::coeff_visitor< Derived >::col, EIGEN_STATIC_ASSERT_VECTOR_ONLY, Eigen::internal::coeff_visitor< Derived >::res, and Eigen::internal::coeff_visitor< Derived >::row.
template<typename Derived > EIGEN_DEVICE_FUNC const NestByValue< Derived > Eigen::DenseBase< Derived >::nestByValue () const inline
Returns
an expression of the temporary version of *this.
template<typename Derived> EIGEN_DEVICE_FUNC Index Eigen::DenseBase< Derived >::nonZeros () const inline
Returns
the number of nonzero coefficients which is in practice the number of stored coefficients.
References Eigen::internal::size().
template<typename Derived> template<typename CustomNullaryOp > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseNullaryOp<CustomNullaryOp, typename DenseBase<Derived>::PlainObject> Eigen::DenseBase< Derived >::NullaryExpr (Index rows, Index cols, const CustomNullaryOp & func)
Returns
an expression of a matrix defined by a custom functor func
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Zero() should be used instead.
The template parameter CustomNullaryOp is the type of the functor.
See also
class CwiseNullaryOp
References EIGEN_STRONG_INLINE.
template<typename Derived> template<typename CustomNullaryOp > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseNullaryOp<CustomNullaryOp, typename DenseBase<Derived>::PlainObject> Eigen::DenseBase< Derived >::NullaryExpr (Index size, const CustomNullaryOp & func)
Returns
an expression of a matrix defined by a custom functor func
The parameter size is the size of the returned vector. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Zero() should be used instead.
The template parameter CustomNullaryOp is the type of the functor.
Here is an example with C++11 random generators:
Output:
See also
class CwiseNullaryOp
References EIGEN_STATIC_ASSERT_VECTOR_ONLY, EIGEN_STRONG_INLINE, and Eigen::internal::size().
template<typename Derived> template<typename CustomNullaryOp > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseNullaryOp<CustomNullaryOp, typename DenseBase<Derived>::PlainObject> Eigen::DenseBase< Derived >::NullaryExpr (const CustomNullaryOp & func)
Returns
an expression of a matrix defined by a custom functor func
This variant is only for fixed-size DenseBase types. For dynamic-size types, you need to use the variants taking size arguments.
The template parameter CustomNullaryOp is the type of the functor.
See also
class CwiseNullaryOp
References EIGEN_STRONG_INLINE.
template<typename Derived> template<typename CustomNullaryOp > static EIGEN_DEVICE_FUNC const CwiseNullaryOp<CustomNullaryOp, PlainObject> Eigen::DenseBase< Derived >::NullaryExpr (Index rows, Index cols, const CustomNullaryOp & func) static
Referenced by Eigen::DenseBase< Derived >::Constant(), Eigen::MatrixBase< Derived >::Identity(), and Eigen::DenseBase< Derived >::LinSpaced().
template<typename Derived> template<typename CustomNullaryOp > static EIGEN_DEVICE_FUNC const CwiseNullaryOp<CustomNullaryOp, PlainObject> Eigen::DenseBase< Derived >::NullaryExpr (Index size, const CustomNullaryOp & func) static
template<typename Derived> template<typename CustomNullaryOp > static EIGEN_DEVICE_FUNC const CwiseNullaryOp<CustomNullaryOp, PlainObject> Eigen::DenseBase< Derived >::NullaryExpr (const CustomNullaryOp & func) static
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Ones (Index rows, Index cols) static
Returns
an expression of a matrix where all coefficients equal one.
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Ones() should be used instead.
Example:
Output:
See also
Ones(), Ones(Index), isOnes(), class Ones
References EIGEN_STRONG_INLINE.
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Ones (Index newSize) static
Returns
an expression of a vector where all coefficients equal one.
The parameter newSize is the size of the returned vector. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Ones() should be used instead.
Example:
Output:
See also
Ones(), Ones(Index,Index), isOnes(), class Ones
References EIGEN_STRONG_INLINE.
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Ones () static
Returns
an expression of a fixed-size matrix or vector where all coefficients equal one.
This variant is only for fixed-size MatrixBase types. For dynamic-size types, you need to use the variants taking size arguments.
Example:
Output:
See also
Ones(Index), Ones(Index,Index), isOnes(), class Ones
References Eigen::DenseBase< Derived >::isOnes().
template<typename Derived> template<typename RowIndices , typename ColIndices > internal::enable_if<valid_indexed_view_overload<RowIndices,ColIndices>::value && internal::traits<typename EIGEN_INDEXED_VIEW_METHOD_TYPE<RowIndices,ColIndices>::type>::ReturnAsIndexedView, typename EIGEN_INDEXED_VIEW_METHOD_TYPE<RowIndices,ColIndices>::type >::type Eigen::DenseBase< Derived >::operator() (const RowIndices & rowIndices, const ColIndices & colIndices) inline
template<typename Derived> template<typename RowIndices , typename ColIndices > internal::enable_if<valid_indexed_view_overload<RowIndices,ColIndices>::value && internal::traits<typename EIGEN_INDEXED_VIEW_METHOD_TYPE<RowIndices,ColIndices>::type>::ReturnAsIndexedView, typename EIGEN_INDEXED_VIEW_METHOD_TYPE<RowIndices,ColIndices>::type >::type Eigen::DenseBase< Derived >::operator() (const RowIndices & rowIndices, const ColIndices & colIndices) inline
template<typename Derived> template<typename RowIndices , typename ColIndices > internal::enable_if<valid_indexed_view_overload<RowIndices,ColIndices>::value && internal::traits<typename EIGEN_INDEXED_VIEW_METHOD_TYPE<RowIndices,ColIndices>::type>::ReturnAsBlock, typename internal::traits<typename EIGEN_INDEXED_VIEW_METHOD_TYPE<RowIndices,ColIndices>::type>::BlockType>::type Eigen::DenseBase< Derived >::operator() (const RowIndices & rowIndices, const ColIndices & colIndices) inline
template<typename Derived> template<typename RowIndices , typename ColIndices > internal::enable_if<valid_indexed_view_overload<RowIndices,ColIndices>::value && internal::traits<typename EIGEN_INDEXED_VIEW_METHOD_TYPE<RowIndices,ColIndices>::type>::ReturnAsBlock, typename internal::traits<typename EIGEN_INDEXED_VIEW_METHOD_TYPE<RowIndices,ColIndices>::type>::BlockType>::type Eigen::DenseBase< Derived >::operator() (const RowIndices & rowIndices, const ColIndices & colIndices) inline
template<typename Derived> template<typename RowIndices , typename ColIndices > internal::enable_if<valid_indexed_view_overload<RowIndices,ColIndices>::value && internal::traits<typename EIGEN_INDEXED_VIEW_METHOD_TYPE<RowIndices,ColIndices>::type>::ReturnAsScalar, CoeffReturnType >::type Eigen::DenseBase< Derived >::operator() (const RowIndices & rowIndices, const ColIndices & colIndices) inline
template<typename Derived> template<typename RowIndices , typename ColIndices > internal::enable_if<valid_indexed_view_overload<RowIndices,ColIndices>::value && internal::traits<typename EIGEN_INDEXED_VIEW_METHOD_TYPE<RowIndices,ColIndices>::type>::ReturnAsScalar, CoeffReturnType >::type Eigen::DenseBase< Derived >::operator() (const RowIndices & rowIndices, const ColIndices & colIndices) inline
template<typename Derived> template<typename Indices > internal::enable_if< IsRowMajor && (!(internal::get_compile_time_incr<typename IvcType<Indices>::type>::value==1 || internal::is_valid_index_type<Indices>::value)), IndexedView<EIGEN_INDEXED_VIEW_METHOD_CONST Derived,IvcIndex,typename IvcType<Indices>::type> >::type Eigen::DenseBase< Derived >::operator() (const Indices & indices) inline
template<typename Derived> template<typename Indices > internal::enable_if< IsRowMajor && (!(internal::get_compile_time_incr<typename IvcType<Indices>::type>::value==1 || internal::is_valid_index_type<Indices>::value)), IndexedView<EIGEN_INDEXED_VIEW_METHOD_CONST Derived,IvcIndex,typename IvcType<Indices>::type> >::type Eigen::DenseBase< Derived >::operator() (const Indices & indices) inline
template<typename Derived> template<typename Indices > internal::enable_if< (!IsRowMajor) && (!(internal::get_compile_time_incr<typename IvcType<Indices>::type>::value==1 || internal::is_valid_index_type<Indices>::value)), IndexedView<EIGEN_INDEXED_VIEW_METHOD_CONST Derived,typename IvcType<Indices>::type,IvcIndex> >::type Eigen::DenseBase< Derived >::operator() (const Indices & indices) inline
template<typename Derived> template<typename Indices > internal::enable_if< (!IsRowMajor) && (!(internal::get_compile_time_incr<typename IvcType<Indices>::type>::value==1 || internal::is_valid_index_type<Indices>::value)), IndexedView<EIGEN_INDEXED_VIEW_METHOD_CONST Derived,typename IvcType<Indices>::type,IvcIndex> >::type Eigen::DenseBase< Derived >::operator() (const Indices & indices) inline
template<typename Derived> template<typename Indices > internal::enable_if< (internal::get_compile_time_incr<typename IvcType<Indices>::type>::value==1) && (!internal::is_valid_index_type<Indices>::value) && (!Symbolic::is_symbolic<Indices>::value), VectorBlock<EIGEN_INDEXED_VIEW_METHOD_CONST Derived,internal::array_size<Indices>::value> >::type Eigen::DenseBase< Derived >::operator() (const Indices & indices) inline
template<typename Derived> template<typename Indices > internal::enable_if< (internal::get_compile_time_incr<typename IvcType<Indices>::type>::value==1) && (!internal::is_valid_index_type<Indices>::value) && (!Symbolic::is_symbolic<Indices>::value), VectorBlock<EIGEN_INDEXED_VIEW_METHOD_CONST Derived,internal::array_size<Indices>::value> >::type Eigen::DenseBase< Derived >::operator() (const Indices & indices) inline
template<typename Derived> template<typename IndexType > internal::enable_if<Symbolic::is_symbolic<IndexType>::value, CoeffReturnType >::type Eigen::DenseBase< Derived >::operator() (const IndexType & id) inline
template<typename Derived> template<typename IndexType > internal::enable_if<Symbolic::is_symbolic<IndexType>::value, CoeffReturnType >::type Eigen::DenseBase< Derived >::operator() (const IndexType & id) inline
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::operator*= (const Scalar & other)
References Eigen::internal::call_assignment().
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC Derived & Eigen::DenseBase< Derived >::operator+= (const EigenBase< OtherDerived > & other)
References Eigen::internal::call_assignment(), and Eigen::EigenBase< Derived >::derived().
template<typename Derived> EIGEN_DEVICE_FUNC const NegativeReturnType Eigen::DenseBase< Derived >::operator- () const inline
Returns
an expression of the opposite of *this
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC Derived & Eigen::DenseBase< Derived >::operator-= (const EigenBase< OtherDerived > & other)
References Eigen::internal::call_assignment(), and Eigen::EigenBase< Derived >::derived().
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::operator/= (const Scalar & other)
References Eigen::internal::call_assignment().
template<typename Derived > EIGEN_DEVICE_FUNC CommaInitializer< Derived > Eigen::DenseBase< Derived >::operator<< (const Scalar & s) inline
Convenient operator to set the coefficients of a matrix.
The coefficients must be provided in a row major order and exactly match the size of the matrix. Otherwise an assertion is raised.
Example:
Output:
Note
According the c++ standard, the argument expressions of this comma initializer are evaluated in arbitrary order.
See also
CommaInitializer::finished(), class CommaInitializer
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC CommaInitializer< Derived > Eigen::DenseBase< Derived >::operator<< (const DenseBase< OtherDerived > & other) inline
See also
operator<<(const Scalar&)
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::operator= (const DenseBase< OtherDerived > & other)
Copies other into *this.
Returns
a reference to *this.
References Eigen::internal::call_assignment().
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::operator= (const DenseBase< Derived > & other)
Special case of the template operator=, in order to prevent the compiler from generating a default operator= (issue hit with g++ 4.1)
References Eigen::internal::call_assignment().
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC Derived & Eigen::DenseBase< Derived >::operator= (const EigenBase< OtherDerived > & other)
Copies the generic expression other into *this.
The expression must provide a (templated) evalTo(Derived& dst) const function which does the actual job. In practice, this allows any user to write its own special matrix without having to modify MatrixBase
Returns
a reference to *this.
References Eigen::internal::call_assignment(), and Eigen::EigenBase< Derived >::derived().
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC Derived & Eigen::DenseBase< Derived >::operator= (const ReturnByValue< OtherDerived > & func)
References Eigen::ReturnByValue< Derived >::evalTo().
template<typename Derived> EIGEN_DEVICE_FUNC Index Eigen::DenseBase< Derived >::outerSize () const inline
Returns
the outer size.
Note
For a vector, this returns just 1. For a matrix (non-vector), this is the major dimension with respect to the storage order, i.e., the number of columns for a column-major matrix, and the number of rows for a row-major matrix.
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::prod () const
Returns
the product of all coefficients of *this
Example:
Output:
See also
sum(), mean(), trace()
References Eigen::Dynamic, EIGEN_STRONG_INLINE, and Eigen::internal::size().
template<typename Derived > const DenseBase< Derived >::RandomReturnType Eigen::DenseBase< Derived >::Random (Index rows, Index cols) inline static
Returns
a random matrix expression
Numbers are uniformly spread through their whole definition range for integer types, and in the [-1:1] range for floating point scalar types.
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Random() should be used instead.
Example:
Output:
This expression has the "evaluate before nesting" flag so that it will be evaluated into a temporary matrix whenever it is nested in a larger expression. This prevents unexpected behavior with expressions involving random matrices.
See DenseBase::NullaryExpr(Index, const CustomNullaryOp&) for an example using C++11 random generators.
See also
DenseBase::setRandom(), DenseBase::Random(Index), DenseBase::Random()
template<typename Derived > const DenseBase< Derived >::RandomReturnType Eigen::DenseBase< Derived >::Random (Index size) inline static
Returns
a random vector expression
Numbers are uniformly spread through their whole definition range for integer types, and in the [-1:1] range for floating point scalar types.
The parameter size is the size of the returned vector. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Random() should be used instead.
Example:
Output:
This expression has the "evaluate before nesting" flag so that it will be evaluated into a temporary vector whenever it is nested in a larger expression. This prevents unexpected behavior with expressions involving random matrices.
See also
DenseBase::setRandom(), DenseBase::Random(Index,Index), DenseBase::Random()
template<typename Derived > const DenseBase< Derived >::RandomReturnType Eigen::DenseBase< Derived >::Random () inline static
Returns
a fixed-size random matrix or vector expression
Numbers are uniformly spread through their whole definition range for integer types, and in the [-1:1] range for floating point scalar types.
This variant is only for fixed-size MatrixBase types. For dynamic-size types, you need to use the variants taking size arguments.
Example:
Output:
This expression has the "evaluate before nesting" flag so that it will be evaluated into a temporary matrix whenever it is nested in a larger expression. This prevents unexpected behavior with expressions involving random matrices.
See also
DenseBase::setRandom(), DenseBase::Random(Index,Index), DenseBase::Random(Index)
template<typename Derived> EIGEN_DEVICE_FUNC RealReturnType Eigen::DenseBase< Derived >::real () const inline
Returns
a read-only expression of the real part of *this.
See also
imag()
template<typename Derived> EIGEN_DEVICE_FUNC NonConstRealReturnType Eigen::DenseBase< Derived >::real () inline
Returns
a non const expression of the real part of *this.
See also
imag()
template<typename Derived> template<typename Func > EIGEN_DEVICE_FUNC internal::traits<Derived>::Scalar Eigen::DenseBase< Derived >::redux (const Func & func) const
Returns
the result of a full redux operation on the whole matrix or vector using func
The template parameter BinaryOp is the type of the functor func which must be an associative operator. Both current C++98 and C++11 functor styles are handled.
See also
DenseBase::sum(), DenseBase::minCoeff(), DenseBase::maxCoeff(), MatrixBase::colwise(), MatrixBase::rowwise()
References eigen_assert, and EIGEN_STRONG_INLINE.
template<typename Derived> template<typename BinaryOp > EIGEN_DEVICE_FUNC Scalar Eigen::DenseBase< Derived >::redux (const BinaryOp & func) const
Referenced by Eigen::internal::member_redux< BinaryOp, Scalar >::operator()().
template<typename Derived > template<int RowFactor, int ColFactor> EIGEN_DEVICE_FUNC const Replicate< Derived, RowFactor, ColFactor > Eigen::DenseBase< Derived >::replicate () const
Returns
an expression of the replication of *this
Example:
Output:
See also
VectorwiseOp::replicate(), DenseBase::replicate(Index,Index), class Replicate
template<typename Derived> EIGEN_DEVICE_FUNC const Replicate<Derived, Dynamic, Dynamic> Eigen::DenseBase< Derived >::replicate (Index rowFactor, Index colFactor) const inline
Returns
an expression of the replication of *this
Example:
Output:
See also
VectorwiseOp::replicate(), DenseBase::replicate<int,int>(), class Replicate
template<typename Derived> EIGEN_DEVICE_FUNC void Eigen::DenseBase< Derived >::resize (Index newSize) inline
Only plain matrices/arrays, not expressions, may be resized; therefore the only useful resize methods are Matrix::resize() and Array::resize(). The present method only asserts that the new size equals the old size, and does nothing else.
References eigen_assert, EIGEN_ONLY_USED_FOR_DEBUG, and Eigen::internal::size().
Referenced by Eigen::SparseQR< _MatrixType, _OrderingType >::_solve_impl(), and Eigen::TriangularBase< Derived >::evalToLazy().
template<typename Derived> EIGEN_DEVICE_FUNC void Eigen::DenseBase< Derived >::resize (Index rows, Index cols) inline
Only plain matrices/arrays, not expressions, may be resized; therefore the only useful resize methods are Matrix::resize() and Array::resize(). The present method only asserts that the new size equals the old size, and does nothing else.
template<typename Derived > EIGEN_DEVICE_FUNC DenseBase< Derived >::ReverseReturnType Eigen::DenseBase< Derived >::reverse () inline
Returns
an expression of the reverse of *this.
Example:
Output:
template<typename Derived> EIGEN_DEVICE_FUNC ConstReverseReturnType Eigen::DenseBase< Derived >::reverse () const inline
This is the const version of reverse().
template<typename Derived > EIGEN_DEVICE_FUNC void Eigen::DenseBase< Derived >::reverseInPlace () inline
This is the "in place" version of reverse: it reverses *this.
In most cases it is probably better to simply use the reversed expression of a matrix. However, when reversing the matrix data itself is really needed, then this "in-place" version is probably the right choice because it provides the following additional benefits:
less error prone: doing the same operation with .reverse() requires special care:
m = m.reverse().eval();
this API enables reverse operations without the need for a temporary
it allows future optimizations (cache friendliness, etc.)
See also
VectorwiseOp::reverseInPlace(), reverse()
References bottomRows(), col(), leftCols(), rightCols(), row(), tail(), and topRows().
template<typename Derived> template<typename NColsType > EIGEN_DEVICE_FUNC NColsBlockXpr<internal::get_fixed_value<NColsType>::value>::Type Eigen::DenseBase< Derived >::rightCols (NColsType n) inline
Returns
a block consisting of the right columns of *this.
Parameters
n the number of columns in the block
Template Parameters
NColsType the type of the value handling the number of columns in the block, typically Index.
Example:
Output:
The number of columns n can also be specified at compile-time by passing Eigen::fix<N>, or Eigen::fix<N>(n) as arguments. See block() for the details.
See also
block(Index,Index,NRowsType,NColsType), class Block
Referenced by Eigen::internal::conservative_resize_like_impl< Derived, OtherDerived, false >::run().
template<typename Derived> template<typename NColsType > EIGEN_DEVICE_FUNC const ConstNColsBlockXpr<internal::get_fixed_value<NColsType>::value>::Type Eigen::DenseBase< Derived >::rightCols (NColsType n) const inline
This is the const version of rightCols(NColsType).
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC NColsBlockXpr<N>::Type Eigen::DenseBase< Derived >::rightCols (Index n = N) inline
Returns
a block consisting of the right columns of *this.
Template Parameters
N the number of columns in the block as specified at compile-time
Parameters
n the number of columns in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
block(Index,Index,NRowsType,NColsType), class Block
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC ConstNColsBlockXpr<N>::Type Eigen::DenseBase< Derived >::rightCols (Index n = N) const inline
This is the const version of rightCols<int>().
template<typename Derived> EIGEN_DEVICE_FUNC RowXpr Eigen::DenseBase< Derived >::row (Index i) inline
Returns
an expression of the i-th row of *this. Note that the numbering starts at 0.
Example:
Output:
See also
col(), class Block
Referenced by Eigen::SPQR< _MatrixType >::_solve_impl().
template<typename Derived> EIGEN_DEVICE_FUNC ConstRowXpr Eigen::DenseBase< Derived >::row (Index i) const inline
This is the const version of row(). */.
template<typename Derived> EIGEN_DEVICE_FUNC ConstRowwiseReturnType Eigen::DenseBase< Derived >::rowwise () const inline
Returns
a VectorwiseOp wrapper of *this providing additional partial reduction operations
Example:
Output:
See also
colwise(), class VectorwiseOp, TutorialReductionsVisitorsBroadcasting
Referenced by Eigen::umeyama().
template<typename Derived > EIGEN_DEVICE_FUNC DenseBase< Derived >::RowwiseReturnType Eigen::DenseBase< Derived >::rowwise () inline
Returns
a writable VectorwiseOp wrapper of *this providing additional partial reduction operations
See also
colwise(), class VectorwiseOp, TutorialReductionsVisitorsBroadcasting
template<typename Derived> template<typename NType > EIGEN_DEVICE_FUNC FixedSegmentReturnType<internal::get_fixed_value<NType>::value>::Type Eigen::DenseBase< Derived >::segment (Index start, NType n) inline
Returns
an expression of a segment (i.e. a vector block) in *this with either dynamic or fixed sizes.
Parameters
start the first coefficient in the segment
n the number of coefficients in the segment
Template Parameters
NType the type of the value handling the number of coefficients in the segment, typically Index.
Example:
Output:
The number of coefficients n can also be specified at compile-time by passing Eigen::fix<N>, or Eigen::fix<N>(n) as arguments. See block() for the details.
Note
Even in the case that the returned expression has dynamic size, in the case when it is applied to a fixed-size vector, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See also
block(Index,Index,NRowsType,NColsType), fix<N>, fix<N>(int), class Block
template<typename Derived> template<typename NType > EIGEN_DEVICE_FUNC const ConstFixedSegmentReturnType<internal::get_fixed_value<NType>::value>::Type Eigen::DenseBase< Derived >::segment (Index start, NType n) const inline
This is the const version of segment(Index,NType).
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC FixedSegmentReturnType<N>::Type Eigen::DenseBase< Derived >::segment (Index start, Index n = N) inline
Returns
a fixed-size expression of a segment (i.e. a vector block) in *this
Template Parameters
N the number of coefficients in the segment as specified at compile-time
Parameters
start the index of the first element in the segment
n the number of coefficients in the segment as specified at compile-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
segment(Index,NType), class Block
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType<N>::Type Eigen::DenseBase< Derived >::segment (Index start, Index n = N) const inline
This is the const version of segment<int>(Index).
template<typename Derived > template<typename ThenDerived , typename ElseDerived > const Select< Derived, ThenDerived, ElseDerived > Eigen::DenseBase< Derived >::select (const DenseBase< ThenDerived > & thenMatrix, const DenseBase< ElseDerived > & elseMatrix) const inline
Returns
a matrix where each coefficient (i,j) is equal to thenMatrix(i,j) if *this(i,j), and elseMatrix(i,j) otherwise.
Example:
Output:
See also
class Select
template<typename Derived > template<typename ThenDerived > const Select< Derived, ThenDerived, typename ThenDerived::ConstantReturnType > Eigen::DenseBase< Derived >::select (const DenseBase< ThenDerived > & thenMatrix, const typename ThenDerived::Scalar & elseScalar) const inline
Version of DenseBase::select(const DenseBase&, const DenseBase&) with the else expression being a scalar value.
See also
DenseBase::select(const DenseBase<ThenDerived>&, const DenseBase<ElseDerived>&) const, class Select
template<typename Derived > template<typename ElseDerived > const Select< Derived, typename ElseDerived::ConstantReturnType, ElseDerived > Eigen::DenseBase< Derived >::select (const typename ElseDerived::Scalar & thenScalar, const DenseBase< ElseDerived > & elseMatrix) const inline
Version of DenseBase::select(const DenseBase&, const DenseBase&) with the then expression being a scalar value.
See also
DenseBase::select(const DenseBase<ThenDerived>&, const DenseBase<ElseDerived>&) const, class Select
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::setConstant (const Scalar & val)
Sets all coefficients in this expression to value val.
See also
fill(), setConstant(Index,const Scalar&), setConstant(Index,Index,const Scalar&), setZero(), setOnes(), Constant(), class CwiseNullaryOp, setZero(), setOnes()
References EIGEN_STRONG_INLINE.
Referenced by Eigen::ArrayBase< ArrayWrapper< ExpressionType > >::operator=().
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::setLinSpaced (Index newSize, const Scalar & low, const Scalar & high)
Sets a linearly spaced vector.
The function generates 'size' equally spaced values in the closed interval [low,high]. When size is set to 1, a vector of length 1 containing 'high' is returned.
Example:
Output:
For integer scalar types, do not miss the explanations on the definition of even spacing .
See also
LinSpaced(Index,const Scalar&,const Scalar&), CwiseNullaryOp
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::setLinSpaced (const Scalar & low, const Scalar & high)
Sets a linearly spaced vector.
The function fills *this with equally spaced values in the closed interval [low,high]. When size is set to 1, a vector of length 1 containing 'high' is returned.
For integer scalar types, do not miss the explanations on the definition of even spacing .
See also
LinSpaced(Index,const Scalar&,const Scalar&), setLinSpaced(Index, const Scalar&, const Scalar&), CwiseNullaryOp
References EIGEN_STATIC_ASSERT_VECTOR_ONLY, EIGEN_STRONG_INLINE, and Eigen::internal::size().
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::setOnes ()
Sets all coefficients in this expression to one.
Example:
Output:
See also
class CwiseNullaryOp, Ones()
References EIGEN_STRONG_INLINE.
template<typename Derived > EIGEN_DEVICE_FUNC Derived & Eigen::DenseBase< Derived >::setRandom () inline
Sets all coefficients in this expression to random values.
Numbers are uniformly spread through their whole definition range for integer types, and in the [-1:1] range for floating point scalar types.
Example:
Output:
See also
class CwiseNullaryOp, setRandom(Index), setRandom(Index,Index)
References EIGEN_STRONG_INLINE.
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::setZero ()
Sets all coefficients in this expression to zero.
Example:
Output:
See also
class CwiseNullaryOp, Zero()
References EIGEN_STRONG_INLINE.
Referenced by Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex > >::evalTo(), and Eigen::InverseImpl< PermutationType, PermutationStorage >::evalTo().
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::sum () const
Returns
the sum of all coefficients of *this
If *this is empty, then the value 0 is returned.
See also
trace(), prod(), mean()
References Eigen::Dynamic, EIGEN_STRONG_INLINE, and Eigen::internal::size().
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC void Eigen::DenseBase< Derived >::swap (const DenseBase< OtherDerived > & other) inline
swaps *this with the expression other.
References Eigen::internal::call_assignment(), eigen_assert, and EIGEN_STATIC_ASSERT.
Referenced by Eigen::internal::conservative_resize_like_impl< Derived, OtherDerived, false >::run().
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC void Eigen::DenseBase< Derived >::swap (PlainObjectBase< OtherDerived > & other) inline
swaps *this with the matrix or array other.
References Eigen::internal::call_assignment(), Eigen::PlainObjectBase< Derived >::cols(), eigen_assert, Eigen::PlainObjectBase< Derived >::rows(), and type.
template<typename Derived> template<typename NType > EIGEN_DEVICE_FUNC FixedSegmentReturnType<internal::get_fixed_value<NType>::value>::Type Eigen::DenseBase< Derived >::tail (NType n) inline
Returns
an expression of a last coefficients of *this with either dynamic or fixed sizes.
Parameters
n the number of coefficients in the segment
Template Parameters
NType the type of the value handling the number of coefficients in the segment, typically Index.
Example:
Output:
The number of coefficients n can also be specified at compile-time by passing Eigen::fix<N>, or Eigen::fix<N>(n) as arguments. See block() for the details.
Note
Even in the case that the returned expression has dynamic size, in the case when it is applied to a fixed-size vector, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See also
class Block, block(Index,Index)
Referenced by Eigen::internal::conservative_resize_like_impl< Derived, OtherDerived, true >::run(), and Eigen::internal::ldlt_inplace< Lower >::updateInPlace().
template<typename Derived> template<typename NType > EIGEN_DEVICE_FUNC const ConstFixedSegmentReturnType<internal::get_fixed_value<NType>::value>::Type Eigen::DenseBase< Derived >::tail (NType n) const inline
This is the const version of tail(Index).
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC FixedSegmentReturnType<N>::Type Eigen::DenseBase< Derived >::tail (Index n = N) inline
Returns
a fixed-size expression of the last coefficients of *this.
Template Parameters
N the number of coefficients in the segment as specified at compile-time
Parameters
n the number of coefficients in the segment as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
tail(NType), class Block
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType<N>::Type Eigen::DenseBase< Derived >::tail (Index n = N) const inline
This is the const version of tail<int>.
template<typename Derived> template<typename NRowsType , typename NColsType > EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<internal::get_fixed_value<NRowsType>::value,internal::get_fixed_value<NColsType>::value>::Type Eigen::DenseBase< Derived >::topLeftCorner (NRowsType cRows, NColsType cCols) inline
Returns
an expression of a top-left corner of *this with either dynamic or fixed sizes.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Template Parameters
NRowsType the type of the value handling the number of rows in the block, typically Index.
NColsType the type of the value handling the number of columns in the block, typically Index.
Example:
Output:
The number of rows blockRows and columns blockCols can also be specified at compile-time by passing Eigen::fix<N>, or Eigen::fix<N>(n) as arguments. See block() for the details.
See also
block(Index,Index,NRowsType,NColsType), class Block
template<typename Derived> template<typename NRowsType , typename NColsType > EIGEN_DEVICE_FUNC const ConstFixedBlockXpr<internal::get_fixed_value<NRowsType>::value,internal::get_fixed_value<NColsType>::value>::Type Eigen::DenseBase< Derived >::topLeftCorner (NRowsType cRows, NColsType cCols) const inline
This is the const version of topLeftCorner(Index, Index).
template<typename Derived> template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<CRows,CCols>::Type Eigen::DenseBase< Derived >::topLeftCorner () inline
Returns
an expression of a fixed-size top-left corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Output:
See also
block(Index,Index,NRowsType,NColsType), class Block
template<typename Derived> template<int CRows, int CCols> EIGEN_DEVICE_FUNC const ConstFixedBlockXpr<CRows,CCols>::Type Eigen::DenseBase< Derived >::topLeftCorner () const inline
This is the const version of topLeftCorner<int, int>().
template<typename Derived> template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr<CRows,CCols>::Type Eigen::DenseBase< Derived >::topLeftCorner (Index cRows, Index cCols) inline
Returns
an expression of a top-left corner of *this.
Template Parameters
CRows number of rows in corner as specified at compile-time
CCols number of columns in corner as specified at compile-time
Parameters
cRows number of rows in corner as specified at run-time
cCols number of columns in corner as specified at run-time
This function is mainly useful for corners where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, cRows should equal CRows unless CRows is Dynamic, and the same for the number of columns.
Example:
Output:
See also
class Block
template<typename Derived> template<int CRows, int CCols> const ConstFixedBlockXpr<CRows,CCols>::Type Eigen::DenseBase< Derived >::topLeftCorner (Index cRows, Index cCols) const inline
This is the const version of topLeftCorner<int, int>(Index, Index).
template<typename Derived> template<typename NRowsType , typename NColsType > EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<internal::get_fixed_value<NRowsType>::value,internal::get_fixed_value<NColsType>::value>::Type Eigen::DenseBase< Derived >::topRightCorner (NRowsType cRows, NColsType cCols) inline
Returns
a expression of a top-right corner of *this with either dynamic or fixed sizes.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Template Parameters
NRowsType the type of the value handling the number of rows in the block, typically Index.
NColsType the type of the value handling the number of columns in the block, typically Index.
Example with dynamic sizes:
Output:
The number of rows blockRows and columns blockCols can also be specified at compile-time by passing Eigen::fix<N>, or Eigen::fix<N>(n) as arguments. See block() for the details.
See also
block(Index,Index,NRowsType,NColsType), class Block
template<typename Derived> template<typename NRowsType , typename NColsType > EIGEN_DEVICE_FUNC const ConstFixedBlockXpr<internal::get_fixed_value<NRowsType>::value,internal::get_fixed_value<NColsType>::value>::Type Eigen::DenseBase< Derived >::topRightCorner (NRowsType cRows, NColsType cCols) const inline
This is the const version of topRightCorner(NRowsType, NColsType).
template<typename Derived> template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<CRows,CCols>::Type Eigen::DenseBase< Derived >::topRightCorner () inline
Returns
an expression of a fixed-size top-right corner of *this.
Template Parameters
CRows the number of rows in the corner
CCols the number of columns in the corner
Example:
Output:
See also
class Block, block<int,int>(Index,Index)
template<typename Derived> template<int CRows, int CCols> EIGEN_DEVICE_FUNC const ConstFixedBlockXpr<CRows,CCols>::Type Eigen::DenseBase< Derived >::topRightCorner () const inline
This is the const version of topRightCorner<int, int>().
template<typename Derived> template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr<CRows,CCols>::Type Eigen::DenseBase< Derived >::topRightCorner (Index cRows, Index cCols) inline
Returns
an expression of a top-right corner of *this.
Template Parameters
CRows number of rows in corner as specified at compile-time
CCols number of columns in corner as specified at compile-time
Parameters
cRows number of rows in corner as specified at run-time
cCols number of columns in corner as specified at run-time
This function is mainly useful for corners where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, cRows should equal CRows unless CRows is Dynamic, and the same for the number of columns.
Example:
Output:
See also
class Block
template<typename Derived> template<int CRows, int CCols> const ConstFixedBlockXpr<CRows,CCols>::Type Eigen::DenseBase< Derived >::topRightCorner (Index cRows, Index cCols) const inline
This is the const version of topRightCorner<int, int>(Index, Index).
template<typename Derived> template<typename NRowsType > EIGEN_DEVICE_FUNC NRowsBlockXpr<internal::get_fixed_value<NRowsType>::value>::Type Eigen::DenseBase< Derived >::topRows (NRowsType n) inline
Returns
a block consisting of the top rows of *this.
Parameters
n the number of rows in the block
Template Parameters
NRowsType the type of the value handling the number of rows in the block, typically Index.
Example:
Output:
The number of rows n can also be specified at compile-time by passing Eigen::fix<N>, or Eigen::fix<N>(n) as arguments. See block() for the details.
See also
block(Index,Index,NRowsType,NColsType), class Block
Referenced by Eigen::SparseQR< _MatrixType, _OrderingType >::_solve_impl().
template<typename Derived> template<typename NRowsType > EIGEN_DEVICE_FUNC const ConstNRowsBlockXpr<internal::get_fixed_value<NRowsType>::value>::Type Eigen::DenseBase< Derived >::topRows (NRowsType n) const inline
This is the const version of topRows(NRowsType).
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC NRowsBlockXpr<N>::Type Eigen::DenseBase< Derived >::topRows (Index n = N) inline
Returns
a block consisting of the top rows of *this.
Template Parameters
N the number of rows in the block as specified at compile-time
Parameters
n the number of rows in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
block(Index,Index,NRowsType,NColsType), class Block
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC ConstNRowsBlockXpr<N>::Type Eigen::DenseBase< Derived >::topRows (Index n = N) const inline
This is the const version of topRows<int>().
template<typename Derived> EIGEN_DEVICE_FUNC Scalar Eigen::DenseBase< Derived >::trace () const
template<typename Derived > EIGEN_DEVICE_FUNC Transpose< Derived > Eigen::DenseBase< Derived >::transpose () inline
Returns
an expression of the transpose of *this.
Example:
Output:
Warning
If you want to replace a matrix by its own transpose, do NOT do this:
m = m.transpose(); // bug!!! caused by aliasing effect
Instead, use the transposeInPlace() method:
m.transposeInPlace();
which gives Eigen good opportunities for optimization, or alternatively you can also do:
m = m.transpose().eval();
See also
transposeInPlace(), adjoint()
Referenced by Eigen::internal::dot_nocheck< T, U, true >::run().
template<typename Derived > EIGEN_DEVICE_FUNC DenseBase< Derived >::ConstTransposeReturnType Eigen::DenseBase< Derived >::transpose () const inline
This is the const version of transpose().
Make sure you read the warning for transpose() !
See also
transposeInPlace(), adjoint()
template<typename Derived > EIGEN_DEVICE_FUNC void Eigen::DenseBase< Derived >::transposeInPlace () inline
This is the "in place" version of transpose(): it replaces *this by its own transpose. Thus, doing
m.transposeInPlace();
has the same effect on m as doing
m = m.transpose().eval();
and is faster and also safer because in the latter line of code, forgetting the eval() results in a bug caused by aliasing.
Notice however that this method is only useful if you want to replace a matrix by its own transpose. If you just need the transpose of a matrix, use transpose().
Note
if the matrix is not square, then *this must be a resizable matrix. This excludes (non-square) fixed-size matrices, block-expressions and maps.
See also
transpose(), adjoint(), adjointInPlace()
References Eigen::Dynamic, and eigen_assert.
template<typename Derived> template<typename CustomUnaryOp > EIGEN_DEVICE_FUNC const CwiseUnaryOp<CustomUnaryOp, const Derived> Eigen::DenseBase< Derived >::unaryExpr (const CustomUnaryOp & func = CustomUnaryOp()) const inline
Apply a unary operator coefficient-wise.
Parameters
[in] func Functor implementing the unary operator
Template Parameters
CustomUnaryOp Type of func
Returns
An expression of a custom coefficient-wise unary operator func of *this
The function ptr_fun() from the C++ standard library can be used to make functors out of normal functions.
Example:
Output:
Genuine functors allow for more possibilities, for instance it may contain a state.
Example:
Output:
See also
unaryViewExpr, binaryExpr, class CwiseUnaryOp
template<typename Derived> template<typename CustomViewOp > EIGEN_DEVICE_FUNC const CwiseUnaryView<CustomViewOp, const Derived> Eigen::DenseBase< Derived >::unaryViewExpr (const CustomViewOp & func = CustomViewOp()) const inline
Returns
an expression of a custom coefficient-wise unary operator func of *this
The template parameter CustomUnaryOp is the type of the functor of the custom unary operator.
Example:
Output:
See also
unaryExpr, binaryExpr class CwiseUnaryOp
template<typename Derived> EIGEN_DEVICE_FUNC CoeffReturnType Eigen::DenseBase< Derived >::value () const inline
Returns
the unique coefficient of a 1x1 expression
References eigen_assert, and EIGEN_STATIC_ASSERT_SIZE_1x1.
Referenced by Eigen::SparseLUMatrixUReturnType< MatrixLType, MatrixUType >::solveInPlace().
template<typename Derived > template<typename Visitor > EIGEN_DEVICE_FUNC void Eigen::DenseBase< Derived >::visit (Visitor & visitor) const
Applies the visitor visitor to the whole coefficients of the matrix or vector.
The template parameter Visitor is the type of the visitor and provides the following interface:
struct MyVisitor {
  // called for the first coefficient
  void init(const Scalar& value, Index i, Index j);
  // called for all other coefficients
  void operator() (const Scalar& value, Index i, Index j);
};
Note
compared to one or two for loops, visitors offer automatic unrolling for small fixed size matrix.
See also
minCoeff(Index*,Index*), maxCoeff(Index*,Index*), DenseBase::redux()
References Eigen::Dynamic, and EIGEN_UNROLLING_LIMIT.
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Zero (Index rows, Index cols) static
Returns
an expression of a zero matrix.
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Zero() should be used instead.
Example:
Output:
See also
Zero(), Zero(Index)
References EIGEN_STRONG_INLINE.
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Zero (Index size) static
Returns
an expression of a zero vector.
The parameter size is the size of the returned vector. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Zero() should be used instead.
Example:
Output:
See also
Zero(), Zero(Index,Index)
References EIGEN_STRONG_INLINE.
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Zero () static
Returns
an expression of a fixed-size zero matrix or vector.
This variant is only for fixed-size MatrixBase types. For dynamic-size types, you need to use the variants taking size arguments.
Example:
Output:
See also
Zero(Index), Zero(Index,Index)
Friends And Related Function Documentation
template<typename Derived > std::ostream & operator<< (std::ostream & s, const DenseBase< Derived > & m) related
Outputs the matrix, to the given stream.
If you wish to print the matrix with a format different than the default, use DenseBase::format().
It is also possible to change the default format by defining EIGEN_DEFAULT_IO_FORMAT before including Eigen headers. If not defined, this will automatically be defined to Eigen::IOFormat(), that is the Eigen::IOFormat with default parameters.
See also
DenseBase::format()
References EIGEN_DEFAULT_IO_FORMAT, m, and Eigen::internal::print_matrix().
The documentation for this class was generated from the following files:
DenseBase.h
Assign.h
BooleanRedux.h
CommaInitializer.h
CwiseNullaryOp.h
EigenBase.h
Fuzzy.h
IO.h
NestByValue.h
Random.h
Redux.h
Replicate.h
ReturnByValue.h
Reverse.h
Select.h
SelfCwiseBinaryOp.h
Transpose.h
VectorwiseOp.h
Visitor.h