SmartMouse_2018: Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator Class Reference
Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator Class Reference
#include <SparseCompressedBase.h>
Public Member Functions
ReverseInnerIterator (const SparseCompressedBase &mat, Index outer)
ReverseInnerIterator (const SparseCompressedBase &mat)
ReverseInnerIterator (const internal::CompressedStorage< Scalar, StorageIndex > &data)
ReverseInnerIterator & operator-- ()
ReverseInnerIterator & operator-= (Index i)
ReverseInnerIterator operator- (Index i)
const Scalar & value () const
Scalar & valueRef ()
StorageIndex index () const
Index outer () const
Index row () const
Index col () const
operator bool () const
Protected Types
typedef internal::variable_if_dynamic< Index, Derived::IsVectorAtCompileTime?0:Dynamic > OuterType
Protected Attributes
const Scalar * m_values
const StorageIndex * m_indices
const OuterType m_outer
Index m_start
Index m_id
Member Typedef Documentation
template<typename Derived> typedef internal::variable_if_dynamic<Index,Derived::IsVectorAtCompileTime?0:Dynamic> Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator::OuterType protected
Constructor & Destructor Documentation
template<typename Derived> Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator::ReverseInnerIterator (const SparseCompressedBase & mat, Index outer) inline
References Eigen::SparseCompressedBase< Derived >::innerNonZeroPtr(), Eigen::SparseCompressedBase< Derived >::isCompressed(), Eigen::SparseCompressedBase< Derived >::nonZeros(), and Eigen::SparseCompressedBase< Derived >::outerIndexPtr().
template<typename Derived> Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator::ReverseInnerIterator (const SparseCompressedBase & mat) inline explicit
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
template<typename Derived> Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator::ReverseInnerIterator (const internal::CompressedStorage< Scalar, StorageIndex > & data) inline explicit
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
Member Function Documentation
template<typename Derived> Index Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator::col () const inline
template<typename Derived> StorageIndex Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator::index () const inline
template<typename Derived> Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator::operator bool () const inline
template<typename Derived> ReverseInnerIterator Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator::operator- (Index i) inline
References i.
template<typename Derived> ReverseInnerIterator& Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator::operator-- () inline
template<typename Derived> ReverseInnerIterator& Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator::operator-= (Index i) inline
References i.
template<typename Derived> Index Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator::outer () const inline
template<typename Derived> Index Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator::row () const inline
template<typename Derived> const Scalar& Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator::value () const inline
template<typename Derived> Scalar& Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator::valueRef () inline
Member Data Documentation
template<typename Derived> Index Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator::m_id protected
template<typename Derived> const StorageIndex* Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator::m_indices protected
template<typename Derived> const OuterType Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator::m_outer protected
template<typename Derived> Index Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator::m_start protected
template<typename Derived> const Scalar* Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator::m_values protected
The documentation for this class was generated from the following file:
SparseCompressedBase.h