SmartMouse_2018: SimMouse Class Reference
SimMouse Class Reference
#include <SimMouse.h>
Public Member Functions
virtual SensorReading checkWalls () override
GlobalPose getGlobalPose ()
LocalPose getLocalPose ()
std::pair< double, double > getWheelVelocities ()
bool isStopped ()
void robotSimStateCallback (const smartmouse::msgs::RobotSimState &msg)
void pidConstantsCallback (const smartmouse::msgs::PIDConstants &msg)
void serverCallback (const smartmouse::msgs::ServerControl &msg)
void speedCallback (const ignition::msgs::Vector2d &msg)
void run ()
void setSpeedCps (double left, double right)
bool simInit ()
void pauseSim ()
void resetToStartPose ()
Public Member Functions inherited from Mouse
Mouse ()
Mouse (AbstractMaze *maze)
Mouse (unsigned int starting_row, unsigned int starting_col)
Mouse (AbstractMaze *maze, unsigned int starting_row, unsigned int starting_col)
void reset ()
unsigned int getCol ()
return the current column. Guaranteed to be between 0 and MAZE_SIZE
unsigned int getRow ()
return the current row. Guaranteed to be between 0 and MAZE_SIZE
Direction getDir ()
return the current direction.
bool inBounds ()
bool atCenter ()
is the mouse at the center of the maze?
void mark_mouse_position_visited ()
void internalTurnToFace (Direction dir)
void internalForward ()
void print_maze_mouse ()
void maze_mouse_string (char *)
bool isWallInDirection (Direction d)
Static Public Member Functions
static SimMouse * inst ()
Public Attributes
SimTimer * timer
ignition::transport::Node::Publisher cmd_pub
ignition::transport::Node::Publisher debug_state_pub
ignition::transport::Node::Publisher server_control_pub
ignition::transport::Node node
KinematicController kinematic_controller
Public Attributes inherited from Mouse
AbstractMaze * maze
Private Member Functions
SimMouse ()
Private Attributes
double abstract_left_force
double abstract_right_force
double left_wheel_angle_rad
double right_wheel_angle_rad
RangeData range_data
std::condition_variable dataCond
std::mutex dataMutex
GlobalPose true_pose
Time state_stamp
Time last_state_stamp
Static Private Attributes
static SimMouse * instance = nullptr
Additional Inherited Members
Protected Attributes inherited from Mouse
unsigned int row
unsigned int col
Direction dir
Constructor & Destructor Documentation
SimMouse::SimMouse () private
References Mouse::dir, and N.
Referenced by inst().
Member Function Documentation
SensorReading SimMouse::checkWalls () override virtual
Implements Mouse.
References Mouse::col, dataCond, dataMutex, Mouse::dir, RangeData::front, RangeData::front_left, RangeData::front_right, smartmouse::kc::FRONT_WALL_THRESHOLD, left_of_dir(), opposite_direction(), range_data, right_of_dir(), Mouse::row, smartmouse::kc::SIDE_WALL_THRESHOLD, and SensorReading::walls.
GlobalPose SimMouse::getGlobalPose () virtual
Implements Mouse.
References KinematicController::getGlobalPose(), and kinematic_controller.
LocalPose SimMouse::getLocalPose () virtual
Implements Mouse.
References KinematicController::getLocalPose(), and kinematic_controller.
std::pair< double, double > SimMouse::getWheelVelocities ()
References KinematicController::getWheelVelocities(), and kinematic_controller.
SimMouse * SimMouse::inst () static
References instance, NULL, and SimMouse().
Referenced by main().
bool SimMouse::isStopped ()
References abstract_left_force, abstract_right_force, KinematicController::isStopped(), kinematic_controller, and smartmouse::kc::MIN_ABSTRACT_FORCE.
void SimMouse::pauseSim ()
References server_control_pub.
void SimMouse::pidConstantsCallback (const smartmouse::msgs::PIDConstants & msg)
References kinematic_controller, and KinematicController::setParams().
Referenced by simInit().
void SimMouse::resetToStartPose ()
References kinematic_controller, Mouse::reset(), KinematicController::reset_col_to(), KinematicController::reset_row_to(), and KinematicController::reset_yaw_to().
Referenced by simInit().
void SimMouse::robotSimStateCallback (const smartmouse::msgs::RobotSimState & msg)
References RangeData::back_left, RangeData::back_right, GlobalPose::col, dataCond, dataMutex, RangeData::front, RangeData::front_left, RangeData::front_right, RangeData::gerald_left, RangeData::gerald_right, left_wheel_angle_rad, range_data, right_wheel_angle_rad, GlobalPose::row, state_stamp, true_pose, and GlobalPose::yaw.
Referenced by simInit().
void SimMouse::run ()
References abstract_left_force, abstract_right_force, cmd_pub, KinematicController::col, Mouse::col, smartmouse::msgs::Convert(), dataCond, dataMutex, debug_state_pub, KinematicController::getGlobalPose(), Command::getTimerImplementation(), kinematic_controller, last_state_stamp, KinematicController::left_motor, left_wheel_angle_rad, TimerInterface::programTimeMs(), smartmouse::kc::radToCU(), range_data, KinematicController::right_motor, right_wheel_angle_rad, KinematicController::row, Mouse::row, KinematicController::run(), RegulatedMotor::setpoint_rps, state_stamp, and RegulatedMotor::velocity_rps.
Referenced by main().
void SimMouse::serverCallback (const smartmouse::msgs::ServerControl & msg)
References kinematic_controller, and KinematicController::kinematics_enabled.
Referenced by simInit().
void SimMouse::setSpeedCps (double left, double right)
References kinematic_controller, and KinematicController::setSpeedCps().
Referenced by Stop::execute(), and speedCallback().
bool SimMouse::simInit ()
References cmd_pub, debug_state_pub, SimTimer::isTimeReady(), TopicNames::kDebugState, kinematic_controller, TopicNames::kPIDConstants, TopicNames::kPIDSetpoints, TopicNames::kRobotCommand, TopicNames::kRobotSimState, TopicNames::kServerControl, TopicNames::kWorldStatistics, node, pidConstantsCallback(), print(), resetToStartPose(), robotSimStateCallback(), server_control_pub, serverCallback(), KinematicController::setAccelerationCpss(), Command::setTimerImplementation(), speedCallback(), timer, and SimTimer::worldStatsCallback().
Referenced by main().
void SimMouse::speedCallback (const ignition::msgs::Vector2d & msg)
References setSpeedCps().
Referenced by simInit().
Member Data Documentation
double SimMouse::abstract_left_force private
Referenced by isStopped(), and run().
double SimMouse::abstract_right_force private
Referenced by isStopped(), and run().
ignition::transport::Node::Publisher SimMouse::cmd_pub
Referenced by run(), and simInit().
std::condition_variable SimMouse::dataCond private
Referenced by checkWalls(), robotSimStateCallback(), and run().
std::mutex SimMouse::dataMutex private
Referenced by checkWalls(), robotSimStateCallback(), and run().
ignition::transport::Node::Publisher SimMouse::debug_state_pub
Referenced by run(), and simInit().
SimMouse * SimMouse::instance = nullptr static private
Referenced by inst().
KinematicController SimMouse::kinematic_controller
Referenced by getGlobalPose(), getLocalPose(), getWheelVelocities(), isStopped(), pidConstantsCallback(), resetToStartPose(), run(), serverCallback(), setSpeedCps(), and simInit().
Time SimMouse::last_state_stamp private
Referenced by run().
double SimMouse::left_wheel_angle_rad private
Referenced by robotSimStateCallback(), and run().
ignition::transport::Node SimMouse::node
Referenced by simInit().
RangeData SimMouse::range_data private
Referenced by checkWalls(), robotSimStateCallback(), and run().
double SimMouse::right_wheel_angle_rad private
Referenced by robotSimStateCallback(), and run().
ignition::transport::Node::Publisher SimMouse::server_control_pub
Referenced by pauseSim(), and simInit().
Time SimMouse::state_stamp private
Referenced by robotSimStateCallback(), and run().
SimTimer* SimMouse::timer
Referenced by main(), and simInit().
GlobalPose SimMouse::true_pose private
Referenced by robotSimStateCallback().
The documentation for this class was generated from the following files:
SimMouse.h
SimMouse.cpp