SmartMouse_2018: Eigen::RealSchur< _MatrixType > Class Template Reference
Eigen::RealSchur< _MatrixType > Class Template Reference
Performs a real Schur decomposition of a square matrix.
#include <RealSchur.h>
Public Types
enum {
RowsAtCompileTime = MatrixType::RowsAtCompileTime, ColsAtCompileTime = MatrixType::ColsAtCompileTime, Options = MatrixType::Options, MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime,
MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime
}
typedef _MatrixType MatrixType
typedef MatrixType::Scalar Scalar
typedef std::complex< typename NumTraits< Scalar >::Real > ComplexScalar
typedef Eigen::Index Index
typedef Matrix< ComplexScalar, ColsAtCompileTime, 1, Options &~RowMajor, MaxColsAtCompileTime, 1 > EigenvalueType
typedef Matrix< Scalar, ColsAtCompileTime, 1, Options &~RowMajor, MaxColsAtCompileTime, 1 > ColumnVectorType
Public Member Functions
RealSchur (Index size=RowsAtCompileTime==Dynamic?1:RowsAtCompileTime)
Default constructor.
template<typename InputType >
RealSchur (const EigenBase< InputType > &matrix, bool computeU=true)
Constructor; computes real Schur decomposition of given matrix.
const MatrixType & matrixU () const
Returns the orthogonal matrix in the Schur decomposition.
const MatrixType & matrixT () const
Returns the quasi-triangular matrix in the Schur decomposition.
template<typename InputType >
RealSchur & compute (const EigenBase< InputType > &matrix, bool computeU=true)
Computes Schur decomposition of given matrix.
template<typename HessMatrixType , typename OrthMatrixType >
RealSchur & computeFromHessenberg (const HessMatrixType &matrixH, const OrthMatrixType &matrixQ, bool computeU)
Computes Schur decomposition of a Hessenberg matrix H = Z T Z^T.
ComputationInfo info () const
Reports whether previous computation was successful.
RealSchur & setMaxIterations (Index maxIters)
Sets the maximum number of iterations allowed.
Index getMaxIterations ()
Returns the maximum number of iterations.
template<typename InputType >
RealSchur< MatrixType > & compute (const EigenBase< InputType > &matrix, bool computeU)
template<typename HessMatrixType , typename OrthMatrixType >
RealSchur< MatrixType > & computeFromHessenberg (const HessMatrixType &matrixH, const OrthMatrixType &matrixQ, bool computeU)
Static Public Attributes
static const int m_maxIterationsPerRow = 40
Maximum number of iterations per row.
Private Types
typedef Matrix< Scalar, 3, 1 > Vector3s
Private Member Functions
Scalar computeNormOfT ()
Index findSmallSubdiagEntry (Index iu)
void splitOffTwoRows (Index iu, bool computeU, const Scalar &exshift)
void computeShift (Index iu, Index iter, Scalar &exshift, Vector3s &shiftInfo)
void initFrancisQRStep (Index il, Index iu, const Vector3s &shiftInfo, Index &im, Vector3s &firstHouseholderVector)
void performFrancisQRStep (Index il, Index im, Index iu, bool computeU, const Vector3s &firstHouseholderVector, Scalar *workspace)
Private Attributes
MatrixType m_matT
MatrixType m_matU
ColumnVectorType m_workspaceVector
HessenbergDecomposition< MatrixType > m_hess
ComputationInfo m_info
bool m_isInitialized
bool m_matUisUptodate
Index m_maxIters
Detailed Description
template<typename _MatrixType>
class Eigen::RealSchur< _MatrixType >
Performs a real Schur decomposition of a square matrix.
Template Parameters
_MatrixType the type of the matrix of which we are computing the real Schur decomposition; this is expected to be an instantiation of the Matrix class template.
Given a real square matrix A, this class computes the real Schur decomposition: where U is a real orthogonal matrix and T is a real quasi-triangular matrix. An orthogonal matrix is a matrix whose inverse is equal to its transpose, . A quasi-triangular matrix is a block-triangular matrix whose diagonal consists of 1-by-1 blocks and 2-by-2 blocks with complex eigenvalues. The eigenvalues of the blocks on the diagonal of T are the same as the eigenvalues of the matrix A, and thus the real Schur decomposition is used in EigenSolver to compute the eigendecomposition of a matrix.
Call the function compute() to compute the real Schur decomposition of a given matrix. Alternatively, you can use the RealSchur(const MatrixType&, bool) constructor which computes the real Schur decomposition at construction time. Once the decomposition is computed, you can use the matrixU() and matrixT() functions to retrieve the matrices U and T in the decomposition.
The documentation of RealSchur(const MatrixType&, bool) contains an example of the typical use of this class.
Note
The implementation is adapted from JAMA (public domain). Their code is based on EISPACK.
See also
class ComplexSchur, class EigenSolver, class ComplexEigenSolver
Member Typedef Documentation
template<typename _MatrixType> typedef Matrix<Scalar, ColsAtCompileTime, 1, Options & ~RowMajor, MaxColsAtCompileTime, 1> Eigen::RealSchur< _MatrixType >::ColumnVectorType
template<typename _MatrixType> typedef std::complex<typename NumTraits<Scalar>::Real> Eigen::RealSchur< _MatrixType >::ComplexScalar
template<typename _MatrixType> typedef Matrix<ComplexScalar, ColsAtCompileTime, 1, Options & ~RowMajor, MaxColsAtCompileTime, 1> Eigen::RealSchur< _MatrixType >::EigenvalueType
template<typename _MatrixType> typedef Eigen::Index Eigen::RealSchur< _MatrixType >::Index
Deprecated:
since Eigen 3.3
template<typename _MatrixType> typedef _MatrixType Eigen::RealSchur< _MatrixType >::MatrixType
template<typename _MatrixType> typedef MatrixType::Scalar Eigen::RealSchur< _MatrixType >::Scalar
template<typename _MatrixType> typedef Matrix<Scalar,3,1> Eigen::RealSchur< _MatrixType >::Vector3s private
Member Enumeration Documentation
template<typename _MatrixType> anonymous enum
Enumerator
RowsAtCompileTime
ColsAtCompileTime
Options
MaxRowsAtCompileTime
MaxColsAtCompileTime
Constructor & Destructor Documentation
template<typename _MatrixType> Eigen::RealSchur< _MatrixType >::RealSchur (Index size = RowsAtCompileTime==Dynamic ? 1 : RowsAtCompileTime) inline explicit
Default constructor.
Parameters
[in] size Positive integer, size of the matrix whose Schur decomposition will be computed.
The default constructor is useful in cases in which the user intends to perform decompositions via compute(). The size parameter is only used as a hint. It is not an error to give a wrong size, but it may impair performance.
See also
compute() for an example.
template<typename _MatrixType> template<typename InputType > Eigen::RealSchur< _MatrixType >::RealSchur (const EigenBase< InputType > & matrix, bool computeU = true) inline explicit
Constructor; computes real Schur decomposition of given matrix.
Parameters
[in] matrix Square matrix whose Schur decomposition is to be computed.
[in] computeU If true, both T and U are computed; if false, only T is computed.
This constructor calls compute() to compute the Schur decomposition.
Example:
Output:
Member Function Documentation
template<typename _MatrixType> template<typename InputType > RealSchur& Eigen::RealSchur< _MatrixType >::compute (const EigenBase< InputType > & matrix, bool computeU = true)
Computes Schur decomposition of given matrix.
Parameters
[in] matrix Square matrix whose Schur decomposition is to be computed.
[in] computeU If true, both T and U are computed; if false, only T is computed.
Returns
Reference to *this
The Schur decomposition is computed by first reducing the matrix to Hessenberg form using the class HessenbergDecomposition. The Hessenberg matrix is then reduced to triangular form by performing Francis QR iterations with implicit double shift. The cost of computing the Schur decomposition depends on the number of iterations; as a rough guide, it may be taken to be flops if computeU is true and flops if computeU is false.
Example:
Output:
See also
compute(const MatrixType&, bool, Index)
Referenced by Eigen::EigenSolver< _MatrixType >::compute(), Eigen::RealSchur< MatrixType >::matrixT(), and Eigen::RealSchur< MatrixType >::RealSchur().
template<typename _MatrixType> template<typename InputType > RealSchur<MatrixType>& Eigen::RealSchur< _MatrixType >::compute (const EigenBase< InputType > & matrix, bool computeU)
References Eigen::EigenBase< Derived >::cols(), Eigen::HessenbergDecomposition< _MatrixType >::compute(), Eigen::RealSchur< _MatrixType >::computeFromHessenberg(), Eigen::EigenBase< Derived >::derived(), eigen_assert, Eigen::RealSchur< _MatrixType >::m_hess, Eigen::RealSchur< _MatrixType >::m_info, Eigen::RealSchur< _MatrixType >::m_isInitialized, Eigen::RealSchur< _MatrixType >::m_matT, Eigen::RealSchur< _MatrixType >::m_matU, Eigen::RealSchur< _MatrixType >::m_matUisUptodate, Eigen::RealSchur< _MatrixType >::m_maxIterationsPerRow, Eigen::RealSchur< _MatrixType >::m_maxIters, Eigen::HessenbergDecomposition< _MatrixType >::matrixH(), Eigen::HessenbergDecomposition< _MatrixType >::matrixQ(), Eigen::half_impl::min(), Eigen::EigenBase< Derived >::rows(), and Eigen::Success.
template<typename _MatrixType> template<typename HessMatrixType , typename OrthMatrixType > RealSchur& Eigen::RealSchur< _MatrixType >::computeFromHessenberg (const HessMatrixType & matrixH, const OrthMatrixType & matrixQ, bool computeU)
Computes Schur decomposition of a Hessenberg matrix H = Z T Z^T.
Parameters
[in] matrixH Matrix in Hessenberg form H
[in] matrixQ orthogonal matrix Q that transform a matrix A to H : A = Q H Q^T
computeU Computes the matriX U of the Schur vectors
Returns
Reference to *this
This routine assumes that the matrix is already reduced in Hessenberg form matrixH using either the class HessenbergDecomposition or another mean. It computes the upper quasi-triangular matrix T of the Schur decomposition of H When computeU is true, this routine computes the matrix U such that A = U T U^T = (QZ) T (QZ)^T = Q H Q^T where A is the initial matrix
NOTE Q is referenced if computeU is true; so, if the initial orthogonal matrix is not available, the user should give an identity matrix (Q.setIdentity())
See also
compute(const MatrixType&, bool)
Referenced by Eigen::RealSchur< _MatrixType >::compute(), and Eigen::RealSchur< MatrixType >::matrixT().
template<typename _MatrixType> template<typename HessMatrixType , typename OrthMatrixType > RealSchur<MatrixType>& Eigen::RealSchur< _MatrixType >::computeFromHessenberg (const HessMatrixType & matrixH, const OrthMatrixType & matrixQ, bool computeU)
References abs(), Eigen::PlainObjectBase< Derived >::coeffRef(), Eigen::RealSchur< _MatrixType >::computeNormOfT(), Eigen::RealSchur< _MatrixType >::computeShift(), Eigen::RealSchur< _MatrixType >::findSmallSubdiagEntry(), Eigen::RealSchur< _MatrixType >::initFrancisQRStep(), Eigen::RealSchur< _MatrixType >::m_info, Eigen::RealSchur< _MatrixType >::m_isInitialized, Eigen::RealSchur< _MatrixType >::m_matT, Eigen::RealSchur< _MatrixType >::m_matU, Eigen::RealSchur< _MatrixType >::m_matUisUptodate, Eigen::RealSchur< _MatrixType >::m_maxIterationsPerRow, Eigen::RealSchur< _MatrixType >::m_maxIters, Eigen::RealSchur< _MatrixType >::m_workspaceVector, Eigen::NoConvergence, Eigen::RealSchur< _MatrixType >::performFrancisQRStep(), Eigen::PlainObjectBase< Derived >::resize(), Eigen::RealSchur< _MatrixType >::splitOffTwoRows(), and Eigen::Success.
template<typename MatrixType > MatrixType::Scalar Eigen::RealSchur< MatrixType >::computeNormOfT () inline private
References Eigen::RealSchur< _MatrixType >::m_matT, Eigen::half_impl::min(), and Eigen::internal::size().
Referenced by Eigen::RealSchur< _MatrixType >::computeFromHessenberg().
template<typename MatrixType > void Eigen::RealSchur< MatrixType >::computeShift (Index iu, Index iter, Scalar & exshift, Vector3s & shiftInfo) inline private
References abs(), Eigen::PlainObjectBase< Derived >::coeff(), Eigen::PlainObjectBase< Derived >::coeffRef(), i, Eigen::RealSchur< _MatrixType >::m_matT, Eigen::PlainObjectBase< Derived >::setConstant(), and sqrt().
Referenced by Eigen::RealSchur< _MatrixType >::computeFromHessenberg().
template<typename MatrixType > Index Eigen::RealSchur< MatrixType >::findSmallSubdiagEntry (Index iu) inline private
References abs(), and Eigen::RealSchur< _MatrixType >::m_matT.
Referenced by Eigen::RealSchur< _MatrixType >::computeFromHessenberg().
template<typename _MatrixType> Index Eigen::RealSchur< _MatrixType >::getMaxIterations () inline
Returns the maximum number of iterations.
Referenced by Eigen::EigenSolver< _MatrixType >::getMaxIterations().
template<typename _MatrixType> ComputationInfo Eigen::RealSchur< _MatrixType >::info () const inline
Reports whether previous computation was successful.
Returns
Success if computation was succesful, NoConvergence otherwise.
Referenced by Eigen::EigenSolver< _MatrixType >::compute().
template<typename MatrixType > void Eigen::RealSchur< MatrixType >::initFrancisQRStep (Index il, Index iu, const Vector3s & shiftInfo, Index & im, Vector3s & firstHouseholderVector) inline private
References abs(), Eigen::PlainObjectBase< Derived >::coeff(), Eigen::PlainObjectBase< Derived >::coeffRef(), and Eigen::RealSchur< _MatrixType >::m_matT.
Referenced by Eigen::RealSchur< _MatrixType >::computeFromHessenberg().
template<typename _MatrixType> const MatrixType& Eigen::RealSchur< _MatrixType >::matrixT () const inline
Returns the quasi-triangular matrix in the Schur decomposition.
Returns
A const reference to the matrix T.
Precondition
Either the constructor RealSchur(const MatrixType&, bool) or the member function compute(const MatrixType&, bool) has been called before to compute the Schur decomposition of a matrix.
See also
RealSchur(const MatrixType&, bool) for an example
Referenced by Eigen::EigenSolver< _MatrixType >::compute().
template<typename _MatrixType> const MatrixType& Eigen::RealSchur< _MatrixType >::matrixU () const inline
Returns the orthogonal matrix in the Schur decomposition.
Returns
A const reference to the matrix U.
Precondition
Either the constructor RealSchur(const MatrixType&, bool) or the member function compute(const MatrixType&, bool) has been called before to compute the Schur decomposition of a matrix, and computeU was set to true (the default value).
See also
RealSchur(const MatrixType&, bool) for an example
Referenced by Eigen::EigenSolver< _MatrixType >::compute().
template<typename MatrixType > void Eigen::RealSchur< MatrixType >::performFrancisQRStep (Index il, Index im, Index iu, bool computeU, const Vector3s & firstHouseholderVector, Scalar * workspace) inline private
References eigen_assert, i, Eigen::RealSchur< _MatrixType >::m_matT, Eigen::RealSchur< _MatrixType >::m_matU, Eigen::half_impl::min(), and Eigen::internal::size().
Referenced by Eigen::RealSchur< _MatrixType >::computeFromHessenberg().
template<typename _MatrixType> RealSchur& Eigen::RealSchur< _MatrixType >::setMaxIterations (Index maxIters) inline
Sets the maximum number of iterations allowed.
If not specified by the user, the maximum number of iterations is m_maxIterationsPerRow times the size of the matrix.
Referenced by Eigen::EigenSolver< _MatrixType >::setMaxIterations().
template<typename MatrixType > void Eigen::RealSchur< MatrixType >::splitOffTwoRows (Index iu, bool computeU, const Scalar & exshift) inline private
References abs(), Eigen::JacobiRotation< Scalar >::adjoint(), Eigen::RealSchur< _MatrixType >::m_matT, Eigen::RealSchur< _MatrixType >::m_matU, Eigen::JacobiRotation< Scalar >::makeGivens(), Eigen::internal::size(), and sqrt().
Referenced by Eigen::RealSchur< _MatrixType >::computeFromHessenberg().
Member Data Documentation
template<typename _MatrixType> HessenbergDecomposition<MatrixType> Eigen::RealSchur< _MatrixType >::m_hess private
Referenced by Eigen::RealSchur< _MatrixType >::compute().
template<typename _MatrixType> ComputationInfo Eigen::RealSchur< _MatrixType >::m_info private
Referenced by Eigen::RealSchur< _MatrixType >::compute(), Eigen::RealSchur< _MatrixType >::computeFromHessenberg(), and Eigen::RealSchur< MatrixType >::info().
template<typename _MatrixType> bool Eigen::RealSchur< _MatrixType >::m_isInitialized private
Referenced by Eigen::RealSchur< _MatrixType >::compute(), Eigen::RealSchur< _MatrixType >::computeFromHessenberg(), Eigen::RealSchur< MatrixType >::info(), Eigen::RealSchur< MatrixType >::matrixT(), and Eigen::RealSchur< MatrixType >::matrixU().
template<typename _MatrixType> MatrixType Eigen::RealSchur< _MatrixType >::m_matT private
Referenced by Eigen::RealSchur< _MatrixType >::compute(), Eigen::RealSchur< _MatrixType >::computeFromHessenberg(), Eigen::RealSchur< _MatrixType >::computeNormOfT(), Eigen::RealSchur< _MatrixType >::computeShift(), Eigen::RealSchur< _MatrixType >::findSmallSubdiagEntry(), Eigen::RealSchur< _MatrixType >::initFrancisQRStep(), Eigen::RealSchur< MatrixType >::matrixT(), Eigen::RealSchur< _MatrixType >::performFrancisQRStep(), and Eigen::RealSchur< _MatrixType >::splitOffTwoRows().
template<typename _MatrixType> MatrixType Eigen::RealSchur< _MatrixType >::m_matU private
Referenced by Eigen::RealSchur< _MatrixType >::compute(), Eigen::RealSchur< _MatrixType >::computeFromHessenberg(), Eigen::RealSchur< MatrixType >::matrixU(), Eigen::RealSchur< _MatrixType >::performFrancisQRStep(), and Eigen::RealSchur< _MatrixType >::splitOffTwoRows().
template<typename _MatrixType> bool Eigen::RealSchur< _MatrixType >::m_matUisUptodate private
Referenced by Eigen::RealSchur< _MatrixType >::compute(), Eigen::RealSchur< _MatrixType >::computeFromHessenberg(), and Eigen::RealSchur< MatrixType >::matrixU().
template<typename _MatrixType> const int Eigen::RealSchur< _MatrixType >::m_maxIterationsPerRow = 40 static
Maximum number of iterations per row.
If not otherwise specified, the maximum number of iterations is this number times the size of the matrix. It is currently set to 40.
Referenced by Eigen::RealSchur< _MatrixType >::compute(), and Eigen::RealSchur< _MatrixType >::computeFromHessenberg().
template<typename _MatrixType> Index Eigen::RealSchur< _MatrixType >::m_maxIters private
Referenced by Eigen::RealSchur< _MatrixType >::compute(), Eigen::RealSchur< _MatrixType >::computeFromHessenberg(), Eigen::RealSchur< MatrixType >::getMaxIterations(), and Eigen::RealSchur< MatrixType >::setMaxIterations().
template<typename _MatrixType> ColumnVectorType Eigen::RealSchur< _MatrixType >::m_workspaceVector private
Referenced by Eigen::RealSchur< _MatrixType >::computeFromHessenberg().
The documentation for this class was generated from the following file:
RealSchur.h