SmartMouse_2018: Forward Class Reference
Forward Class Reference
#include <Forward.h>
Public Member Functions
Forward ()
void initialize ()
run once in the first iteration of the command's life. this will be overrided by individual commands
void execute ()
stuff to do over and over each iteration. this will be overrided by individual commands
bool isFinished ()
checked every iteration to see if we're done here. this will be overrided by individual commands
void end ()
called once at the end, once isFinished() returned true. this will be overrided by individual commands.
Forward ()
void initialize ()
run once in the first iteration of the command's life. this will be overrided by individual commands
void execute ()
stuff to do over and over each iteration. this will be overrided by individual commands
bool isFinished ()
checked every iteration to see if we're done here. this will be overrided by individual commands
void end ()
called once at the end, once isFinished() returned true. this will be overrided by individual commands.
Forward ()
void initialize ()
run once in the first iteration of the command's life. this will be overrided by individual commands
void execute ()
stuff to do over and over each iteration. this will be overrided by individual commands
bool isFinished ()
checked every iteration to see if we're done here. this will be overrided by individual commands
void end ()
called once at the end, once isFinished() returned true. this will be overrided by individual commands.
Public Member Functions inherited from Command
Command ()
Command (const char *name)
virtual ~Command ()
void setTimeout (unsigned long timeout)
unsigned long getTime ()
bool isTimedOut ()
virtual void _initialize ()
virtual void _execute ()
virtual void _end ()
bool cycle ()
actually does the excuting.
bool isRunning ()
check if the command is running.
bool operator!= (const Command &other)
comparator overload for !=. used when checking if command is in list
Private Attributes
GlobalPose start
RealMouse * mouse
SimMouse * mouse
RangeData range_data
smartmouse::kc::DriveStraightState * drive_straight_state
Mouse * mouse
Additional Inherited Members
Static Public Member Functions inherited from Command
static void setTimerImplementation (TimerInterface *timer)
static TimerInterface * getTimerImplementation ()
Public Attributes inherited from Command
bool inParallel
used by command group to organize commands
const char * name
for convenient printing
bool initialized
bool running
unsigned long timeout
unsigned long startTime
Static Public Attributes inherited from Command
static TimerInterface * timer
Constructor & Destructor Documentation
Forward::Forward ()
Forward::Forward ()
Forward::Forward ()
Member Function Documentation
void Forward::end () virtual
called once at the end, once isFinished() returned true. this will be overrided by individual commands.
Reimplemented from Command.
void Forward::end () virtual
called once at the end, once isFinished() returned true. this will be overrided by individual commands.
Reimplemented from Command.
References KinematicController::enable_sensor_pose_estimate, RealMouse::kinematic_controller, RealMouse::LED_1, and mouse.
void Forward::end () virtual
called once at the end, once isFinished() returned true. this will be overrided by individual commands.
Reimplemented from Command.
void Forward::execute () virtual
stuff to do over and over each iteration. this will be overrided by individual commands
Reimplemented from Command.
void Forward::execute () virtual
stuff to do over and over each iteration. this will be overrided by individual commands
Reimplemented from Command.
References RealMouse::kinematic_controller, mouse, and RealMouse::setSpeedCps().
void Forward::execute () virtual
stuff to do over and over each iteration. this will be overrided by individual commands
Reimplemented from Command.
void Forward::initialize () virtual
run once in the first iteration of the command's life. this will be overrided by individual commands
Reimplemented from Command.
void Forward::initialize () virtual
run once in the first iteration of the command's life. this will be overrided by individual commands
Reimplemented from Command.
References KinematicController::dispToNextEdge(), KinematicController::enable_sensor_pose_estimate, RealMouse::getGlobalPose(), RealMouse::kinematic_controller, RealMouse::LED_1, mouse, and start.
void Forward::initialize () virtual
run once in the first iteration of the command's life. this will be overrided by individual commands
Reimplemented from Command.
bool Forward::isFinished () virtual
checked every iteration to see if we're done here. this will be overrided by individual commands
Returns
is the function finished
Implements Command.
bool Forward::isFinished () virtual
checked every iteration to see if we're done here. this will be overrided by individual commands
Returns
is the function finished
Implements Command.
References RealMouse::kinematic_controller, and mouse.
bool Forward::isFinished () virtual
checked every iteration to see if we're done here. this will be overrided by individual commands
Returns
is the function finished
Implements Command.
Member Data Documentation
smartmouse::kc::DriveStraightState* Forward::drive_straight_state private
Mouse* Forward::mouse private
RealMouse* Forward::mouse private
Referenced by end(), execute(), initialize(), and isFinished().
SimMouse* Forward::mouse private
RangeData Forward::range_data private
GlobalPose Forward::start private
Referenced by initialize().
The documentation for this class was generated from the following files:
real/commands/Forward.h
real/commands/Forward.cpp