SmartMouse_2018: PIDPlotWidget Class Reference
PIDPlotWidget Class Reference
#include <PIDPlotWidget.h>
Signals
void Replot ()
Public Member Functions
PIDPlotWidget ()
void Clear ()
const QString GetTabName () override
void PIDCallback (const smartmouse::msgs::DebugState &msg)
Private Slots
void LeftChecked ()
void LeftSetpointChecked ()
void RightChecked ()
void RightSetpointChecked ()
Private Attributes
Ui::PIDPlotWidget * ui_
ignition::transport::Node node_
QwtPlot * plot_
PlotSeriesData * left_setpoint_
PlotSeriesData * left_actual_
PlotSeriesData * right_setpoint_
PlotSeriesData * right_actual_
const unsigned int capacity_
Constructor & Destructor Documentation
PIDPlotWidget::PIDPlotWidget ()
References PlotSeriesData::Attach(), capacity_, Clear(), TopicNames::kDebugState, left_actual_, left_setpoint_, LeftChecked(), LeftSetpointChecked(), node_, PIDCallback(), plot_, Replot(), right_actual_, right_setpoint_, RightChecked(), RightSetpointChecked(), and ui_.
Member Function Documentation
void PIDPlotWidget::Clear ()
References PlotSeriesData::Clear(), left_actual_, left_setpoint_, right_actual_, and right_setpoint_.
Referenced by PIDPlotWidget().
const QString PIDPlotWidget::GetTabName () override virtual
Implements AbstractTab.
Referenced by StateWidget::StateWidget().
void PIDPlotWidget::LeftChecked () private slot
References PlotSeriesData::Attach(), PlotSeriesData::Hide(), left_actual_, plot_, and ui_.
Referenced by PIDPlotWidget().
void PIDPlotWidget::LeftSetpointChecked () private slot
References PlotSeriesData::Attach(), PlotSeriesData::Hide(), left_setpoint_, plot_, and ui_.
Referenced by PIDPlotWidget().
void PIDPlotWidget::PIDCallback (const smartmouse::msgs::DebugState & msg)
References PlotSeriesData::Append(), smartmouse::msgs::ConvertSec(), left_actual_, left_setpoint_, Replot(), right_actual_, and right_setpoint_.
Referenced by PIDPlotWidget().
void PIDPlotWidget::Replot () signal
Referenced by PIDCallback(), and PIDPlotWidget().
void PIDPlotWidget::RightChecked () private slot
References PlotSeriesData::Attach(), PlotSeriesData::Hide(), plot_, right_actual_, and ui_.
Referenced by PIDPlotWidget().
void PIDPlotWidget::RightSetpointChecked () private slot
References PlotSeriesData::Attach(), PlotSeriesData::Hide(), plot_, right_setpoint_, and ui_.
Referenced by PIDPlotWidget().
Member Data Documentation
const unsigned int PIDPlotWidget::capacity_ private
Referenced by PIDPlotWidget().
PlotSeriesData* PIDPlotWidget::left_actual_ private
Referenced by Clear(), LeftChecked(), PIDCallback(), and PIDPlotWidget().
PlotSeriesData* PIDPlotWidget::left_setpoint_ private
Referenced by Clear(), LeftSetpointChecked(), PIDCallback(), and PIDPlotWidget().
ignition::transport::Node PIDPlotWidget::node_ private
Referenced by PIDPlotWidget().
QwtPlot* PIDPlotWidget::plot_ private
Referenced by LeftChecked(), LeftSetpointChecked(), PIDPlotWidget(), RightChecked(), and RightSetpointChecked().
PlotSeriesData* PIDPlotWidget::right_actual_ private
Referenced by Clear(), PIDCallback(), PIDPlotWidget(), and RightChecked().
PlotSeriesData* PIDPlotWidget::right_setpoint_ private
Referenced by Clear(), PIDCallback(), PIDPlotWidget(), and RightSetpointChecked().
Ui::PIDPlotWidget* PIDPlotWidget::ui_ private
Referenced by LeftChecked(), LeftSetpointChecked(), PIDPlotWidget(), RightChecked(), and RightSetpointChecked().
The documentation for this class was generated from the following files:
PIDPlotWidget.h
PIDPlotWidget.cpp