SmartMouse_2018: Command Class Reference
Command Class Reference abstract
this class is the very core of the framework commands are initialized once, then run until they're done completed commands are removed the scheduler
#include <Command.h>
Public Member Functions
Command ()
Command (const char *name)
virtual ~Command ()
void setTimeout (unsigned long timeout)
unsigned long getTime ()
bool isTimedOut ()
virtual void initialize ()
run once in the first iteration of the command's life. this will be overrided by individual commands
virtual void _initialize ()
virtual void execute ()
stuff to do over and over each iteration. this will be overrided by individual commands
virtual void _execute ()
virtual bool isFinished ()=0
checked every iteration to see if we're done here. this will be overrided by individual commands
virtual void end ()
called once at the end, once isFinished() returned true. this will be overrided by individual commands.
virtual void _end ()
bool cycle ()
actually does the excuting.
bool isRunning ()
check if the command is running.
bool operator!= (const Command &other)
comparator overload for !=. used when checking if command is in list
Static Public Member Functions
static void setTimerImplementation (TimerInterface *timer)
static TimerInterface * getTimerImplementation ()
Public Attributes
bool inParallel
used by command group to organize commands
const char * name
for convenient printing
bool initialized
bool running
unsigned long timeout
unsigned long startTime
Static Public Attributes
static TimerInterface * timer
Detailed Description
this class is the very core of the framework commands are initialized once, then run until they're done completed commands are removed the scheduler
Constructor & Destructor Documentation
Command::Command ()
Command::Command (const char * name)
Command::~Command () virtual
Member Function Documentation
void Command::_end () virtual
Reimplemented in CommandGroup.
References running.
Referenced by cycle().
void Command::_execute () virtual
Reimplemented in CommandGroup.
Referenced by cycle().
void Command::_initialize () virtual
Reimplemented in CommandGroup.
References TimerInterface::programTimeMs(), running, startTime, and timer.
Referenced by CommandGroup::_initialize(), and cycle().
bool Command::cycle ()
actually does the excuting.
Returns
if command is finished
References _end(), _execute(), _initialize(), end(), execute(), initialize(), initialized, and isFinished().
Referenced by CommandGroup::_execute(), and Scheduler::run().
void Command::end () virtual
called once at the end, once isFinished() returned true. this will be overrided by individual commands.
Reimplemented in CommandGroup, ArcTurn, ArcTurn, Forward, ForwardN, Stop, Forward, ForwardN, Stop, ForwardToCenter, TurnInPlace, ForwardToCenter, TurnInPlace, ForwardN, Delay, LEDBlink, Forward, Turn, SolveMaze, Stop, SolveMaze, WaitForStart, SolveMaze, WaitForStart, Calibrate, WaitForStart, and End.
Referenced by cycle().
void Command::execute () virtual
stuff to do over and over each iteration. this will be overrided by individual commands
Reimplemented in CommandGroup, ArcTurn, ArcTurn, Forward, ForwardN, Stop, Forward, ForwardN, Stop, ForwardToCenter, TurnInPlace, ForwardToCenter, TurnInPlace, ForwardN, Delay, Finish, LEDBlink, Forward, Turn, WaitForStart, Calibrate, WaitForStart, and WaitForStart.
Referenced by cycle().
unsigned long Command::getTime ()
References TimerInterface::programTimeMs(), startTime, and timer.
Referenced by SolveMaze::end(), LEDBlink::execute(), Finish::execute(), Finish::initialize(), and isTimedOut().
TimerInterface * Command::getTimerImplementation () static
References timer.
Referenced by SimMouse::run().
void Command::initialize () virtual
run once in the first iteration of the command's life. this will be overrided by individual commands
Reimplemented in CommandGroup, ArcTurn, ArcTurn, Forward, ForwardN, Stop, Forward, ForwardN, Stop, ForwardToCenter, ReturnToStart, SpeedRun, Finish, SolveMaze, Stop, TurnInPlace, ForwardToCenter, SolveMaze, TurnInPlace, ForwardN, SolveMaze, Delay, SolveCommand, LEDBlink, Turn, Turn, Finish, Forward, Turn, Calibrate, WaitForStart, Finish, WaitForStart, and WaitForStart.
Referenced by cycle().
virtual bool Command::isFinished () pure virtual
checked every iteration to see if we're done here. this will be overrided by individual commands
Returns
is the function finished
Implemented in CommandGroup, ArcTurn, ArcTurn, Forward, ForwardN, Stop, Forward, ForwardN, Stop, ForwardToCenter, TurnInPlace, ForwardToCenter, TurnInPlace, ForwardN, Delay, LEDBlink, Forward, Turn, ReturnToStart, SpeedRun, Finish, SolveMaze, Stop, SolveMaze, WaitForStart, SolveMaze, Finish, WaitForStart, SolveCommand, Calibrate, WaitForStart, Finish, and End.
Referenced by cycle().
bool Command::isRunning ()
check if the command is running.
Returns
if command is still running
References running.
bool Command::isTimedOut ()
References getTime(), and timeout.
Referenced by Stop::execute(), Finish::isFinished(), Stop::isFinished(), Delay::isFinished(), LEDBlink::isFinished(), and TurnInPlace::isFinished().
bool Command::operator!= (const Command & other)
comparator overload for !=. used when checking if command is in list
References name.
void Command::setTimeout (unsigned long timeout)
References timeout.
Referenced by Delay::initialize(), LEDBlink::initialize(), Stop::initialize(), TurnInPlace::initialize(), and Finish::initialize().
void Command::setTimerImplementation (TimerInterface * timer) static
References timer.
Referenced by main(), setup(), and SimMouse::simInit().
Member Data Documentation
bool Command::initialized
Referenced by cycle().
bool Command::inParallel
used by command group to organize commands
Referenced by CommandGroup::_execute(), CommandGroup::addParallel(), and CommandGroup::addSequential().
const char* Command::name
for convenient printing
Referenced by operator!=().
bool Command::running
Referenced by _end(), _initialize(), and isRunning().
unsigned long Command::startTime
Referenced by _initialize(), and getTime().
unsigned long Command::timeout
Referenced by isTimedOut(), and setTimeout().
TimerInterface * Command::timer static
Referenced by _initialize(), getTime(), getTimerImplementation(), and setTimerImplementation().
The documentation for this class was generated from the following files:
Command.h
Command.cpp