SmartMouse_2018: Eigen::ColPivHouseholderQR< _MatrixType > Class Template Reference
Eigen::ColPivHouseholderQR< _MatrixType > Class Template Reference
Householder rank-revealing QR decomposition of a matrix with column-pivoting.
#include <ForwardDeclarations.h>
Public Types
enum { RowsAtCompileTime = MatrixType::RowsAtCompileTime, ColsAtCompileTime = MatrixType::ColsAtCompileTime, MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime, MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime }
typedef _MatrixType MatrixType
typedef MatrixType::Scalar Scalar
typedef MatrixType::RealScalar RealScalar
typedef MatrixType::StorageIndex StorageIndex
typedef internal::plain_diag_type< MatrixType >::type HCoeffsType
typedef PermutationMatrix< ColsAtCompileTime, MaxColsAtCompileTime > PermutationType
typedef internal::plain_row_type< MatrixType, Index >::type IntRowVectorType
typedef internal::plain_row_type< MatrixType >::type RowVectorType
typedef internal::plain_row_type< MatrixType, RealScalar >::type RealRowVectorType
typedef HouseholderSequence< MatrixType, typename internal::remove_all< typename HCoeffsType::ConjugateReturnType >::type > HouseholderSequenceType
typedef MatrixType::PlainObject PlainObject
Public Member Functions
ColPivHouseholderQR ()
Default Constructor.
ColPivHouseholderQR (Index rows, Index cols)
Default Constructor with memory preallocation.
template<typename InputType >
ColPivHouseholderQR (const EigenBase< InputType > &matrix)
Constructs a QR factorization from a given matrix.
template<typename InputType >
ColPivHouseholderQR (EigenBase< InputType > &matrix)
Constructs a QR factorization from a given matrix.
template<typename Rhs >
const Solve< ColPivHouseholderQR, Rhs > solve (const MatrixBase< Rhs > &b) const
HouseholderSequenceType householderQ () const
HouseholderSequenceType matrixQ () const
const MatrixType & matrixQR () const
const MatrixType & matrixR () const
template<typename InputType >
ColPivHouseholderQR & compute (const EigenBase< InputType > &matrix)
const PermutationType & colsPermutation () const
MatrixType::RealScalar absDeterminant () const
MatrixType::RealScalar logAbsDeterminant () const
Index rank () const
Index dimensionOfKernel () const
bool isInjective () const
bool isSurjective () const
bool isInvertible () const
const Inverse< ColPivHouseholderQR > inverse () const
Index rows () const
Index cols () const
const HCoeffsType & hCoeffs () const
ColPivHouseholderQR & setThreshold (const RealScalar &threshold)
ColPivHouseholderQR & setThreshold (Default_t)
RealScalar threshold () const
Index nonzeroPivots () const
RealScalar maxPivot () const
ComputationInfo info () const
Reports whether the QR factorization was succesful.
template<typename RhsType , typename DstType >
void _solve_impl (const RhsType &rhs, DstType &dst) const
template<typename InputType >
ColPivHouseholderQR< MatrixType > & compute (const EigenBase< InputType > &matrix)
Protected Member Functions
void computeInPlace ()
Static Protected Member Functions
static void check_template_parameters ()
Protected Attributes
MatrixType m_qr
HCoeffsType m_hCoeffs
PermutationType m_colsPermutation
IntRowVectorType m_colsTranspositions
RowVectorType m_temp
RealRowVectorType m_colNormsUpdated
RealRowVectorType m_colNormsDirect
bool m_isInitialized
bool m_usePrescribedThreshold
RealScalar m_prescribedThreshold
RealScalar m_maxpivot
Index m_nonzero_pivots
Index m_det_pq
Private Types
typedef PermutationType::StorageIndex PermIndexType
Friends
class CompleteOrthogonalDecomposition< MatrixType >
Detailed Description
template<typename _MatrixType>
class Eigen::ColPivHouseholderQR< _MatrixType >
Householder rank-revealing QR decomposition of a matrix with column-pivoting.
Template Parameters
_MatrixType the type of the matrix of which we are computing the QR decomposition
This class performs a rank-revealing QR decomposition of a matrix A into matrices P, Q and R such that
by using Householder transformations. Here, P is a permutation matrix, Q a unitary matrix and R an upper triangular matrix.
This decomposition performs column pivoting in order to be rank-revealing and improve numerical stability. It is slower than HouseholderQR, and faster than FullPivHouseholderQR.
This class supports the inplace decomposition mechanism.
See also
MatrixBase::colPivHouseholderQr()
Member Typedef Documentation
template<typename _MatrixType> typedef internal::plain_diag_type<MatrixType>::type Eigen::ColPivHouseholderQR< _MatrixType >::HCoeffsType
template<typename _MatrixType> typedef HouseholderSequence<MatrixType,typename internal::remove_all<typename HCoeffsType::ConjugateReturnType>::type> Eigen::ColPivHouseholderQR< _MatrixType >::HouseholderSequenceType
template<typename _MatrixType> typedef internal::plain_row_type<MatrixType, Index>::type Eigen::ColPivHouseholderQR< _MatrixType >::IntRowVectorType
template<typename _MatrixType> typedef _MatrixType Eigen::ColPivHouseholderQR< _MatrixType >::MatrixType
template<typename _MatrixType> typedef PermutationType::StorageIndex Eigen::ColPivHouseholderQR< _MatrixType >::PermIndexType private
template<typename _MatrixType> typedef PermutationMatrix<ColsAtCompileTime, MaxColsAtCompileTime> Eigen::ColPivHouseholderQR< _MatrixType >::PermutationType
template<typename _MatrixType> typedef MatrixType::PlainObject Eigen::ColPivHouseholderQR< _MatrixType >::PlainObject
template<typename _MatrixType> typedef internal::plain_row_type<MatrixType, RealScalar>::type Eigen::ColPivHouseholderQR< _MatrixType >::RealRowVectorType
template<typename _MatrixType> typedef MatrixType::RealScalar Eigen::ColPivHouseholderQR< _MatrixType >::RealScalar
template<typename _MatrixType> typedef internal::plain_row_type<MatrixType>::type Eigen::ColPivHouseholderQR< _MatrixType >::RowVectorType
template<typename _MatrixType> typedef MatrixType::Scalar Eigen::ColPivHouseholderQR< _MatrixType >::Scalar
template<typename _MatrixType> typedef MatrixType::StorageIndex Eigen::ColPivHouseholderQR< _MatrixType >::StorageIndex
Member Enumeration Documentation
template<typename _MatrixType> anonymous enum
Enumerator
RowsAtCompileTime
ColsAtCompileTime
MaxRowsAtCompileTime
MaxColsAtCompileTime
Constructor & Destructor Documentation
template<typename _MatrixType> Eigen::ColPivHouseholderQR< _MatrixType >::ColPivHouseholderQR () inline
Default Constructor.
The default constructor is useful in cases in which the user intends to perform decompositions via ColPivHouseholderQR::compute(const MatrixType&).
template<typename _MatrixType> Eigen::ColPivHouseholderQR< _MatrixType >::ColPivHouseholderQR (Index rows, Index cols) inline
Default Constructor with memory preallocation.
Like the default constructor but with preallocation of the internal data according to the specified problem size.
See also
ColPivHouseholderQR()
template<typename _MatrixType> template<typename InputType > Eigen::ColPivHouseholderQR< _MatrixType >::ColPivHouseholderQR (const EigenBase< InputType > & matrix) inline explicit
Constructs a QR factorization from a given matrix.
This constructor computes the QR factorization of the matrix matrix by calling the method compute(). It is a short cut for:
ColPivHouseholderQR<MatrixType> qr(matrix.rows(), matrix.cols());
qr.compute(matrix);
See also
compute()
template<typename _MatrixType> template<typename InputType > Eigen::ColPivHouseholderQR< _MatrixType >::ColPivHouseholderQR (EigenBase< InputType > & matrix) inline explicit
Constructs a QR factorization from a given matrix.
This overloaded constructor is provided for inplace decomposition when MatrixType is a Eigen::Ref.
See also
ColPivHouseholderQR(const EigenBase&)
Member Function Documentation
template<typename _MatrixType > template<typename RhsType , typename DstType > void Eigen::ColPivHouseholderQR< _MatrixType >::_solve_impl (const RhsType & rhs, DstType & dst) const
References eigen_assert, Eigen::householderSequence(), and i.
template<typename MatrixType > MatrixType::RealScalar Eigen::ColPivHouseholderQR< MatrixType >::absDeterminant () const
Returns
the absolute value of the determinant of the matrix of which *this is the QR decomposition. It has only linear complexity (that is, O(n) where n is the dimension of the square matrix) as the QR decomposition has already been computed.
Note
This is only for square matrices.
Warning
a determinant can be very big or small, so for matrices of large enough dimension, there is a risk of overflow/underflow. One way to work around that is to use logAbsDeterminant() instead.
See also
logAbsDeterminant(), MatrixBase::determinant()
References abs(), and eigen_assert.
template<typename _MatrixType> static void Eigen::ColPivHouseholderQR< _MatrixType >::check_template_parameters () inline static protected
template<typename _MatrixType> Index Eigen::ColPivHouseholderQR< _MatrixType >::cols (void) const inline
template<typename _MatrixType> const PermutationType& Eigen::ColPivHouseholderQR< _MatrixType >::colsPermutation () const inline
Returns
a const reference to the column permutation matrix
template<typename _MatrixType> template<typename InputType > ColPivHouseholderQR& Eigen::ColPivHouseholderQR< _MatrixType >::compute (const EigenBase< InputType > & matrix)
template<typename _MatrixType> template<typename InputType > ColPivHouseholderQR<MatrixType>& Eigen::ColPivHouseholderQR< _MatrixType >::compute (const EigenBase< InputType > & matrix)
Performs the QR factorization of the given matrix matrix. The result of the factorization is stored into *this, and a reference to *this is returned.
See also
class ColPivHouseholderQR, ColPivHouseholderQR(const MatrixType&)
References Eigen::EigenBase< Derived >::derived().
template<typename MatrixType > void Eigen::ColPivHouseholderQR< MatrixType >::computeInPlace () protected
References abs(), abs2(), eigen_assert, Eigen::internal::size(), Eigen::numext::sqrt(), and std::swap().
template<typename _MatrixType> Index Eigen::ColPivHouseholderQR< _MatrixType >::dimensionOfKernel () const inline
Returns
the dimension of the kernel of the matrix of which *this is the QR decomposition.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
template<typename _MatrixType> const HCoeffsType& Eigen::ColPivHouseholderQR< _MatrixType >::hCoeffs () const inline
Returns
a const reference to the vector of Householder coefficients used to represent the factor Q.
For advanced uses only.
template<typename MatrixType > ColPivHouseholderQR< MatrixType >::HouseholderSequenceType Eigen::ColPivHouseholderQR< MatrixType >::householderQ () const
Returns
the matrix Q as a sequence of householder transformations. You can extract the meaningful part only by using:
qr.householderQ().setLength(qr.nonzeroPivots())
References eigen_assert.
Referenced by Eigen::internal::Assignment< DstXprType, Inverse< ColPivHouseholderQR< MatrixType > >, internal::assign_op< typename DstXprType::Scalar, typename ColPivHouseholderQR< MatrixType >::Scalar >, Dense2Dense >::run().
template<typename _MatrixType> ComputationInfo Eigen::ColPivHouseholderQR< _MatrixType >::info () const inline
Reports whether the QR factorization was succesful.
Note
This function always returns Success. It is provided for compatibility with other factorization routines.
Returns
Success
template<typename _MatrixType> const Inverse<ColPivHouseholderQR> Eigen::ColPivHouseholderQR< _MatrixType >::inverse () const inline
Returns
the inverse of the matrix of which *this is the QR decomposition.
Note
If this matrix is not invertible, the returned matrix has undefined coefficients. Use isInvertible() to first determine whether this matrix is invertible.
template<typename _MatrixType> bool Eigen::ColPivHouseholderQR< _MatrixType >::isInjective () const inline
Returns
true if the matrix of which *this is the QR decomposition represents an injective linear map, i.e. has trivial kernel; false otherwise.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
template<typename _MatrixType> bool Eigen::ColPivHouseholderQR< _MatrixType >::isInvertible () const inline
Returns
true if the matrix of which *this is the QR decomposition is invertible.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
template<typename _MatrixType> bool Eigen::ColPivHouseholderQR< _MatrixType >::isSurjective () const inline
Returns
true if the matrix of which *this is the QR decomposition represents a surjective linear map; false otherwise.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
template<typename MatrixType > MatrixType::RealScalar Eigen::ColPivHouseholderQR< MatrixType >::logAbsDeterminant () const
Returns
the natural log of the absolute value of the determinant of the matrix of which *this is the QR decomposition. It has only linear complexity (that is, O(n) where n is the dimension of the square matrix) as the QR decomposition has already been computed.
Note
This is only for square matrices.
This method is useful to work around the risk of overflow/underflow that's inherent to determinant computation.
See also
absDeterminant(), MatrixBase::determinant()
References eigen_assert.
template<typename _MatrixType> HouseholderSequenceType Eigen::ColPivHouseholderQR< _MatrixType >::matrixQ () const inline
template<typename _MatrixType> const MatrixType& Eigen::ColPivHouseholderQR< _MatrixType >::matrixQR () const inline
Returns
a reference to the matrix where the Householder QR decomposition is stored
template<typename _MatrixType> const MatrixType& Eigen::ColPivHouseholderQR< _MatrixType >::matrixR () const inline
Returns
a reference to the matrix where the result Householder QR is stored
Warning
The strict lower part of this matrix contains internal values. Only the upper triangular part should be referenced. To get it, use
matrixR().template triangularView<Upper>()
For rank-deficient matrices, use
matrixR().topLeftCorner(rank(), rank()).template triangularView<Upper>()
template<typename _MatrixType> RealScalar Eigen::ColPivHouseholderQR< _MatrixType >::maxPivot () const inline
Returns
the absolute value of the biggest pivot, i.e. the biggest diagonal coefficient of R.
template<typename _MatrixType> Index Eigen::ColPivHouseholderQR< _MatrixType >::nonzeroPivots () const inline
Returns
the number of nonzero pivots in the QR decomposition. Here nonzero is meant in the exact sense, not in a fuzzy sense. So that notion isn't really intrinsically interesting, but it is still useful when implementing algorithms.
See also
rank()
template<typename _MatrixType> Index Eigen::ColPivHouseholderQR< _MatrixType >::rank () const inline
Returns
the rank of the matrix of which *this is the QR decomposition.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
template<typename _MatrixType> Index Eigen::ColPivHouseholderQR< _MatrixType >::rows (void) const inline
template<typename _MatrixType> ColPivHouseholderQR& Eigen::ColPivHouseholderQR< _MatrixType >::setThreshold (const RealScalar & threshold) inline
Allows to prescribe a threshold to be used by certain methods, such as rank(), who need to determine when pivots are to be considered nonzero. This is not used for the QR decomposition itself.
When it needs to get the threshold value, Eigen calls threshold(). By default, this uses a formula to automatically determine a reasonable threshold. Once you have called the present method setThreshold(const RealScalar&), your value is used instead.
Parameters
threshold The new value to use as the threshold.
A pivot will be considered nonzero if its absolute value is strictly greater than where maxpivot is the biggest pivot.
If you want to come back to the default behavior, call setThreshold(Default_t)
template<typename _MatrixType> ColPivHouseholderQR& Eigen::ColPivHouseholderQR< _MatrixType >::setThreshold (Default_t) inline
Allows to come back to the default behavior, letting Eigen use its default formula for determining the threshold.
You should pass the special object Eigen::Default as parameter here.
qr.setThreshold(Eigen::Default);
See the documentation of setThreshold(const RealScalar&).
template<typename _MatrixType> template<typename Rhs > const Solve<ColPivHouseholderQR, Rhs> Eigen::ColPivHouseholderQR< _MatrixType >::solve (const MatrixBase< Rhs > & b) const inline
This method finds a solution x to the equation Ax=b, where A is the matrix of which *this is the QR decomposition, if any exists.
Parameters
b the right-hand-side of the equation to solve.
Returns
a solution.
Example:
Output:
template<typename _MatrixType> RealScalar Eigen::ColPivHouseholderQR< _MatrixType >::threshold () const inline
Returns the threshold that will be used by certain methods such as rank().
See the documentation of setThreshold(const RealScalar&).
Friends And Related Function Documentation
template<typename _MatrixType> friend class CompleteOrthogonalDecomposition< MatrixType > friend
Member Data Documentation
template<typename _MatrixType> RealRowVectorType Eigen::ColPivHouseholderQR< _MatrixType >::m_colNormsDirect protected
template<typename _MatrixType> RealRowVectorType Eigen::ColPivHouseholderQR< _MatrixType >::m_colNormsUpdated protected
template<typename _MatrixType> PermutationType Eigen::ColPivHouseholderQR< _MatrixType >::m_colsPermutation protected
template<typename _MatrixType> IntRowVectorType Eigen::ColPivHouseholderQR< _MatrixType >::m_colsTranspositions protected
template<typename _MatrixType> Index Eigen::ColPivHouseholderQR< _MatrixType >::m_det_pq protected
template<typename _MatrixType> HCoeffsType Eigen::ColPivHouseholderQR< _MatrixType >::m_hCoeffs protected
template<typename _MatrixType> bool Eigen::ColPivHouseholderQR< _MatrixType >::m_isInitialized protected
template<typename _MatrixType> RealScalar Eigen::ColPivHouseholderQR< _MatrixType >::m_maxpivot protected
template<typename _MatrixType> Index Eigen::ColPivHouseholderQR< _MatrixType >::m_nonzero_pivots protected
template<typename _MatrixType> RealScalar Eigen::ColPivHouseholderQR< _MatrixType >::m_prescribedThreshold protected
template<typename _MatrixType> MatrixType Eigen::ColPivHouseholderQR< _MatrixType >::m_qr protected
template<typename _MatrixType> RowVectorType Eigen::ColPivHouseholderQR< _MatrixType >::m_temp protected
template<typename _MatrixType> bool Eigen::ColPivHouseholderQR< _MatrixType >::m_usePrescribedThreshold protected
The documentation for this class was generated from the following files:
ForwardDeclarations.h
ColPivHouseholderQR.h