SmartMouse_2018: TimerInterface Class Reference
TimerInterface Class Reference abstract
#include <TimerInterface.h>
Public Member Functions
virtual unsigned long programTimeMs ()=0
the time since the start of the program in milliseconds
Member Function Documentation
virtual unsigned long TimerInterface::programTimeMs () pure virtual
the time since the start of the program in milliseconds
Implemented in SimTimer, ArduinoTimer, and ConsoleTimer.
Referenced by Command::_initialize(), Command::getTime(), and SimMouse::run().
The documentation for this class was generated from the following file:
TimerInterface.h