SmartMouse_2018: ForwardN Class Reference
ForwardN Class Reference
#include <ForwardN.h>
Public Member Functions
ForwardN (unsigned int n)
void initialize ()
run once in the first iteration of the command's life. this will be overrided by individual commands
void execute ()
stuff to do over and over each iteration. this will be overrided by individual commands
bool isFinished ()
checked every iteration to see if we're done here. this will be overrided by individual commands
void end ()
called once at the end, once isFinished() returned true. this will be overrided by individual commands.
ForwardN (unsigned int n)
void initialize ()
run once in the first iteration of the command's life. this will be overrided by individual commands
void execute ()
stuff to do over and over each iteration. this will be overrided by individual commands
bool isFinished ()
checked every iteration to see if we're done here. this will be overrided by individual commands
void end ()
called once at the end, once isFinished() returned true. this will be overrided by individual commands.
ForwardN (unsigned int n)
void initialize ()
run once in the first iteration of the command's life. this will be overrided by individual commands
void execute ()
stuff to do over and over each iteration. this will be overrided by individual commands
bool isFinished ()
checked every iteration to see if we're done here. this will be overrided by individual commands
void end ()
called once at the end, once isFinished() returned true. this will be overrided by individual commands.
Public Member Functions inherited from Command
Command ()
Command (const char *name)
virtual ~Command ()
void setTimeout (unsigned long timeout)
unsigned long getTime ()
bool isTimedOut ()
virtual void _initialize ()
virtual void _execute ()
virtual void _end ()
bool cycle ()
actually does the excuting.
bool isRunning ()
check if the command is running.
bool operator!= (const Command &other)
comparator overload for !=. used when checking if command is in list
Private Attributes
unsigned int n
GlobalPose start
RealMouse * mouse
SimMouse * mouse
smartmouse::kc::DriveStraightState * drive_straight_state
unsigned int i
Mouse * mouse
Additional Inherited Members
Static Public Member Functions inherited from Command
static void setTimerImplementation (TimerInterface *timer)
static TimerInterface * getTimerImplementation ()
Public Attributes inherited from Command
bool inParallel
used by command group to organize commands
const char * name
for convenient printing
bool initialized
bool running
unsigned long timeout
unsigned long startTime
Static Public Attributes inherited from Command
static TimerInterface * timer
Constructor & Destructor Documentation
ForwardN::ForwardN (unsigned int n)
ForwardN::ForwardN (unsigned int n)
ForwardN::ForwardN (unsigned int n)
Member Function Documentation
void ForwardN::end () virtual
called once at the end, once isFinished() returned true. this will be overrided by individual commands.
Reimplemented from Command.
void ForwardN::end () virtual
called once at the end, once isFinished() returned true. this will be overrided by individual commands.
Reimplemented from Command.
References KinematicController::enable_sensor_pose_estimate, RealMouse::kinematic_controller, RealMouse::LED_4, and mouse.
void ForwardN::end () virtual
called once at the end, once isFinished() returned true. this will be overrided by individual commands.
Reimplemented from Command.
void ForwardN::execute () virtual
stuff to do over and over each iteration. this will be overrided by individual commands
Reimplemented from Command.
void ForwardN::execute () virtual
stuff to do over and over each iteration. this will be overrided by individual commands
Reimplemented from Command.
References RealMouse::kinematic_controller, mouse, and RealMouse::setSpeedCps().
void ForwardN::execute () virtual
stuff to do over and over each iteration. this will be overrided by individual commands
Reimplemented from Command.
void ForwardN::initialize () virtual
run once in the first iteration of the command's life. this will be overrided by individual commands
Reimplemented from Command.
void ForwardN::initialize () virtual
run once in the first iteration of the command's life. this will be overrided by individual commands
Reimplemented from Command.
References KinematicController::dispToNthEdge(), KinematicController::enable_sensor_pose_estimate, RealMouse::getGlobalPose(), RealMouse::kinematic_controller, RealMouse::LED_4, mouse, n, and start.
void ForwardN::initialize () virtual
run once in the first iteration of the command's life. this will be overrided by individual commands
Reimplemented from Command.
bool ForwardN::isFinished () virtual
checked every iteration to see if we're done here. this will be overrided by individual commands
Returns
is the function finished
Implements Command.
bool ForwardN::isFinished () virtual
checked every iteration to see if we're done here. this will be overrided by individual commands
Returns
is the function finished
Implements Command.
References RealMouse::kinematic_controller, and mouse.
bool ForwardN::isFinished () virtual
checked every iteration to see if we're done here. this will be overrided by individual commands
Returns
is the function finished
Implements Command.
Member Data Documentation
smartmouse::kc::DriveStraightState* ForwardN::drive_straight_state private
unsigned int ForwardN::i private
Mouse* ForwardN::mouse private
SimMouse* ForwardN::mouse private
RealMouse* ForwardN::mouse private
Referenced by end(), execute(), initialize(), and isFinished().
unsigned int ForwardN::n private
Referenced by initialize().
GlobalPose ForwardN::start private
Referenced by initialize().
The documentation for this class was generated from the following files:
real/commands/ForwardN.h
real/commands/ForwardN.cpp