SmartMouse_2018: Eigen::Rotation2D< _Scalar > Class Template Reference
Eigen::Rotation2D< _Scalar > Class Template Reference
Geometry_Module
Represents a rotation/orientation in a 2 dimensional space.
#include <ForwardDeclarations.h>
Public Types
enum { Dim = 2 }
typedef _Scalar Scalar
typedef Matrix< Scalar, 2, 1 > Vector2
typedef Matrix< Scalar, 2, 2 > Matrix2
Public Types inherited from Eigen::RotationBase< Rotation2D< _Scalar >, 2 >
enum
typedef internal::traits< Rotation2D< _Scalar > >::Scalar Scalar
typedef Matrix< Scalar, Dim, Dim > RotationMatrixType
typedef Matrix< Scalar, Dim, 1 > VectorType
Public Member Functions
EIGEN_DEVICE_FUNC Rotation2D (const Scalar &a)
EIGEN_DEVICE_FUNC Rotation2D ()
template<typename Derived >
EIGEN_DEVICE_FUNC Rotation2D (const MatrixBase< Derived > &m)
EIGEN_DEVICE_FUNC Scalar angle () const
EIGEN_DEVICE_FUNC Scalar & angle ()
EIGEN_DEVICE_FUNC Scalar smallestPositiveAngle () const
EIGEN_DEVICE_FUNC Scalar smallestAngle () const
EIGEN_DEVICE_FUNC Rotation2D inverse () const
EIGEN_DEVICE_FUNC Rotation2D operator* (const Rotation2D &other) const
EIGEN_DEVICE_FUNC Rotation2D & operator*= (const Rotation2D &other)
EIGEN_DEVICE_FUNC Vector2 operator* (const Vector2 &vec) const
template<typename Derived >
EIGEN_DEVICE_FUNC Rotation2D & fromRotationMatrix (const MatrixBase< Derived > &m)
EIGEN_DEVICE_FUNC Matrix2 toRotationMatrix () const
template<typename Derived >
EIGEN_DEVICE_FUNC Rotation2D & operator= (const MatrixBase< Derived > &m)
EIGEN_DEVICE_FUNC Rotation2D slerp (const Scalar &t, const Rotation2D &other) const
template<typename NewScalarType >
EIGEN_DEVICE_FUNC internal::cast_return_type< Rotation2D, Rotation2D< NewScalarType > >::type cast () const
template<typename OtherScalarType >
EIGEN_DEVICE_FUNC Rotation2D (const Rotation2D< OtherScalarType > &other)
EIGEN_DEVICE_FUNC bool isApprox (const Rotation2D &other, const typename NumTraits< Scalar >::Real &prec=NumTraits< Scalar >::dummy_precision()) const
template<typename Derived >
EIGEN_DEVICE_FUNC Rotation2D< Scalar > & fromRotationMatrix (const MatrixBase< Derived > &mat)
Public Member Functions inherited from Eigen::RotationBase< Rotation2D< _Scalar >, 2 >
EIGEN_DEVICE_FUNC const Rotation2D< _Scalar > & derived () const
EIGEN_DEVICE_FUNC Rotation2D< _Scalar > & derived ()
EIGEN_DEVICE_FUNC RotationMatrixType toRotationMatrix () const
EIGEN_DEVICE_FUNC RotationMatrixType matrix () const
EIGEN_DEVICE_FUNC Rotation2D< _Scalar > inverse () const
EIGEN_DEVICE_FUNC Transform< Scalar, Dim, Isometry > operator* (const Translation< Scalar, Dim > &t) const
EIGEN_DEVICE_FUNC RotationMatrixType operator* (const UniformScaling< Scalar > &s) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::rotation_base_generic_product_selector< Rotation2D< _Scalar >, OtherDerived, OtherDerived::IsVectorAtCompileTime >::ReturnType operator* (const EigenBase< OtherDerived > &e) const
EIGEN_DEVICE_FUNC Transform< Scalar, Dim, Mode > operator* (const Transform< Scalar, Dim, Mode, Options > &t) const
EIGEN_DEVICE_FUNC VectorType _transformVector (const OtherVectorType &v) const
Static Public Member Functions
static EIGEN_DEVICE_FUNC Rotation2D Identity ()
Protected Attributes
Scalar m_angle
Private Types
typedef RotationBase< Rotation2D< _Scalar >, 2 > Base
Detailed Description
template<typename _Scalar>
class Eigen::Rotation2D< _Scalar >
Represents a rotation/orientation in a 2 dimensional space.
Template Parameters
_Scalar the scalar type, i.e., the type of the coefficients
This class is equivalent to a single scalar representing a counter clock wise rotation as a single angle in radian. It provides some additional features such as the automatic conversion from/to a 2x2 rotation matrix. Moreover this class aims to provide a similar interface to Quaternion in order to facilitate the writing of generic algorithms dealing with rotations.
See also
class Quaternion, class Transform
Member Typedef Documentation
template<typename _Scalar> typedef RotationBase<Rotation2D<_Scalar>,2> Eigen::Rotation2D< _Scalar >::Base private
template<typename _Scalar> typedef Matrix<Scalar,2,2> Eigen::Rotation2D< _Scalar >::Matrix2
template<typename _Scalar> typedef _Scalar Eigen::Rotation2D< _Scalar >::Scalar
the scalar type of the coefficients
template<typename _Scalar> typedef Matrix<Scalar,2,1> Eigen::Rotation2D< _Scalar >::Vector2
Member Enumeration Documentation
template<typename _Scalar> anonymous enum
Enumerator
Dim
Constructor & Destructor Documentation
template<typename _Scalar> EIGEN_DEVICE_FUNC Eigen::Rotation2D< _Scalar >::Rotation2D (const Scalar & a) inline explicit
Construct a 2D counter clock wise rotation from the angle a in radian.
template<typename _Scalar> EIGEN_DEVICE_FUNC Eigen::Rotation2D< _Scalar >::Rotation2D () inline
Default constructor wihtout initialization. The represented rotation is undefined.
template<typename _Scalar> template<typename Derived > EIGEN_DEVICE_FUNC Eigen::Rotation2D< _Scalar >::Rotation2D (const MatrixBase< Derived > & m) inline explicit
Construct a 2D rotation from a 2x2 rotation matrix mat.
See also
fromRotationMatrix()
template<typename _Scalar> template<typename OtherScalarType > EIGEN_DEVICE_FUNC Eigen::Rotation2D< _Scalar >::Rotation2D (const Rotation2D< OtherScalarType > & other) inline explicit
Copy constructor with scalar type conversion
References Eigen::Rotation2D< _Scalar >::angle().
Member Function Documentation
template<typename _Scalar> EIGEN_DEVICE_FUNC Scalar Eigen::Rotation2D< _Scalar >::angle () const inline
Returns
the rotation angle
Referenced by Eigen::Rotation2D< _Scalar >::Rotation2D().
template<typename _Scalar> EIGEN_DEVICE_FUNC Scalar& Eigen::Rotation2D< _Scalar >::angle () inline
Returns
a read-write reference to the rotation angle
template<typename _Scalar> template<typename NewScalarType > EIGEN_DEVICE_FUNC internal::cast_return_type<Rotation2D,Rotation2D<NewScalarType> >::type Eigen::Rotation2D< _Scalar >::cast () const inline
Returns
*this with scalar type casted to NewScalarType
Note that if NewScalarType is equal to the current scalar type of *this then this function smartly returns a const reference to *this.
References type.
template<typename _Scalar> template<typename Derived > EIGEN_DEVICE_FUNC Rotation2D& Eigen::Rotation2D< _Scalar >::fromRotationMatrix (const MatrixBase< Derived > & m)
template<typename _Scalar> template<typename Derived > EIGEN_DEVICE_FUNC Rotation2D<Scalar>& Eigen::Rotation2D< _Scalar >::fromRotationMatrix (const MatrixBase< Derived > & mat)
Set *this from a 2x2 rotation matrix mat. In other words, this function extract the rotation angle from the rotation matrix.
References EIGEN_STATIC_ASSERT.
template<typename _Scalar> static EIGEN_DEVICE_FUNC Rotation2D Eigen::Rotation2D< _Scalar >::Identity () inline static
template<typename _Scalar> EIGEN_DEVICE_FUNC Rotation2D Eigen::Rotation2D< _Scalar >::inverse () const inline
Returns
the inverse rotation
template<typename _Scalar> EIGEN_DEVICE_FUNC bool Eigen::Rotation2D< _Scalar >::isApprox (const Rotation2D< _Scalar > & other, const typename NumTraits< Scalar >::Real & prec = NumTraits<Scalar>::dummy_precision()) const inline
Returns
true if *this is approximately equal to other, within the precision determined by prec.
See also
MatrixBase::isApprox()
References Eigen::Rotation2D< _Scalar >::m_angle.
template<typename _Scalar> EIGEN_DEVICE_FUNC Rotation2D Eigen::Rotation2D< _Scalar >::operator* (const Rotation2D< _Scalar > & other) const inline
Concatenates two rotations
References Eigen::Rotation2D< _Scalar >::m_angle.
template<typename _Scalar> EIGEN_DEVICE_FUNC Vector2 Eigen::Rotation2D< _Scalar >::operator* (const Vector2 & vec) const inline
Applies the rotation to a 2D vector
References m, and Eigen::internal::toRotationMatrix().
template<typename _Scalar> EIGEN_DEVICE_FUNC Rotation2D& Eigen::Rotation2D< _Scalar >::operator*= (const Rotation2D< _Scalar > & other) inline
Concatenates two rotations
References Eigen::Rotation2D< _Scalar >::m_angle.
template<typename _Scalar> template<typename Derived > EIGEN_DEVICE_FUNC Rotation2D& Eigen::Rotation2D< _Scalar >::operator= (const MatrixBase< Derived > & m) inline
Set *this from a 2x2 rotation matrix mat. In other words, this function extract the rotation angle from the rotation matrix.
This method is an alias for fromRotationMatrix()
See also
fromRotationMatrix()
template<typename _Scalar> EIGEN_DEVICE_FUNC Rotation2D Eigen::Rotation2D< _Scalar >::slerp (const Scalar & t, const Rotation2D< _Scalar > & other) const inline
Returns
the spherical interpolation between *this and other using parameter t. It is in fact equivalent to a linear interpolation.
References Eigen::Rotation2D< _Scalar >::m_angle, and Eigen::Rotation2D< _Scalar >::smallestAngle().
template<typename _Scalar> EIGEN_DEVICE_FUNC Scalar Eigen::Rotation2D< _Scalar >::smallestAngle () const inline
Returns
the rotation angle in [-pi,pi]
References EIGEN_PI.
Referenced by Eigen::Rotation2D< _Scalar >::slerp().
template<typename _Scalar> EIGEN_DEVICE_FUNC Scalar Eigen::Rotation2D< _Scalar >::smallestPositiveAngle () const inline
Returns
the rotation angle in [0,2pi]
References EIGEN_PI.
template<typename Scalar > Rotation2D< Scalar >::Matrix2 EIGEN_DEVICE_FUNC Eigen::Rotation2D< Scalar >::toRotationMatrix (void) const
Constructs and
Returns
an equivalent 2x2 rotation matrix.
References cos(), and sin().
Member Data Documentation
template<typename _Scalar> Scalar Eigen::Rotation2D< _Scalar >::m_angle protected
Referenced by Eigen::Rotation2D< _Scalar >::isApprox(), Eigen::Rotation2D< _Scalar >::operator*(), Eigen::Rotation2D< _Scalar >::operator*=(), and Eigen::Rotation2D< _Scalar >::slerp().
The documentation for this class was generated from the following files:
ForwardDeclarations.h
Rotation2D.h