SmartMouse_2018: Turn Class Reference
Turn Class Reference
#include <Turn.h>
Public Member Functions
Turn (Direction dir)
void initialize ()
run once in the first iteration of the command's life. this will be overrided by individual commands
Turn (Direction dir)
void initialize ()
run once in the first iteration of the command's life. this will be overrided by individual commands
Turn (Direction dir)
void initialize ()
run once in the first iteration of the command's life. this will be overrided by individual commands
void execute ()
stuff to do over and over each iteration. this will be overrided by individual commands
bool isFinished ()
checked every iteration to see if we're done here. this will be overrided by individual commands
void end ()
called once at the end, once isFinished() returned true. this will be overrided by individual commands.
Public Member Functions inherited from Command
Command ()
Command (const char *name)
virtual ~Command ()
void setTimeout (unsigned long timeout)
unsigned long getTime ()
bool isTimedOut ()
bool cycle ()
actually does the excuting.
bool isRunning ()
check if the command is running.
bool operator!= (const Command &other)
comparator overload for !=. used when checking if command is in list
Public Member Functions inherited from CommandGroup
CommandGroup (const char *name)
CommandGroup ()=default
void addSequential (Command *command)
void addParallel (Command *command)
virtual void _initialize ()
virtual void _execute ()
virtual void _end ()
Private Attributes
RealMouse * mouse
Direction dir
SimMouse * mouse
Mouse * mouse
Additional Inherited Members
Static Public Member Functions inherited from Command
static void setTimerImplementation (TimerInterface *timer)
static TimerInterface * getTimerImplementation ()
Public Attributes inherited from Command
bool inParallel
used by command group to organize commands
const char * name
for convenient printing
bool initialized
bool running
unsigned long timeout
unsigned long startTime
Public Attributes inherited from CommandGroup
LinkedList< Command * > commands
Static Public Attributes inherited from Command
static TimerInterface * timer
Constructor & Destructor Documentation
Turn::Turn (Direction dir)
Turn::Turn (Direction dir)
Turn::Turn (Direction dir)
Member Function Documentation
void Turn::end () virtual
called once at the end, once isFinished() returned true. this will be overrided by individual commands.
Reimplemented from Command.
void Turn::execute () virtual
stuff to do over and over each iteration. this will be overrided by individual commands
Reimplemented from Command.
void Turn::initialize () virtual
run once in the first iteration of the command's life. this will be overrided by individual commands
Reimplemented from Command.
References CommandGroup::addSequential(), smartmouse::kc::ARC_TURN, dir, Mouse::getDir(), mouse, and opposite_direction().
void Turn::initialize () virtual
run once in the first iteration of the command's life. this will be overrided by individual commands
Reimplemented from Command.
void Turn::initialize () virtual
run once in the first iteration of the command's life. this will be overrided by individual commands
Reimplemented from Command.
bool Turn::isFinished () virtual
checked every iteration to see if we're done here. this will be overrided by individual commands
Returns
is the function finished
Implements Command.
Member Data Documentation
Direction Turn::dir private
Referenced by initialize().
RealMouse* Turn::mouse private
Referenced by initialize().
SimMouse* Turn::mouse private
Mouse* Turn::mouse private
The documentation for this class was generated from the following files:
real/commands/Turn.h
real/commands/Turn.cpp