SmartMouse_2018: Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex > Class Template Reference
Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex > Class Template Reference
a class to manipulate the L supernodal factor from the SparseLU factorization
#include <SparseLU_SupernodalMatrix.h>
Classes
class InnerIterator
InnerIterator class to iterate over nonzero values of the current column in the supernodal matrix L.
Public Types
typedef _Scalar Scalar
typedef _StorageIndex StorageIndex
typedef Matrix< StorageIndex, Dynamic, 1 > IndexVector
typedef Matrix< Scalar, Dynamic, 1 > ScalarVector
Public Member Functions
MappedSuperNodalMatrix ()
MappedSuperNodalMatrix (Index m, Index n, ScalarVector &nzval, IndexVector &nzval_colptr, IndexVector &rowind, IndexVector &rowind_colptr, IndexVector &col_to_sup, IndexVector &sup_to_col)
~MappedSuperNodalMatrix ()
void setInfos (Index m, Index n, ScalarVector &nzval, IndexVector &nzval_colptr, IndexVector &rowind, IndexVector &rowind_colptr, IndexVector &col_to_sup, IndexVector &sup_to_col)
Index rows ()
Index cols ()
Scalar * valuePtr ()
const Scalar * valuePtr () const
StorageIndex * colIndexPtr ()
const StorageIndex * colIndexPtr () const
StorageIndex * rowIndex ()
const StorageIndex * rowIndex () const
StorageIndex * rowIndexPtr ()
const StorageIndex * rowIndexPtr () const
StorageIndex * colToSup ()
const StorageIndex * colToSup () const
StorageIndex * supToCol ()
const StorageIndex * supToCol () const
Index nsuper () const
template<typename Dest >
void solveInPlace (MatrixBase< Dest > &X) const
Solve with the supernode triangular matrix.
Protected Attributes
Index m_row
Index m_col
Index m_nsuper
Scalar * m_nzval
StorageIndex * m_nzval_colptr
StorageIndex * m_rowind
StorageIndex * m_rowind_colptr
StorageIndex * m_col_to_sup
StorageIndex * m_sup_to_col
Detailed Description
template<typename _Scalar, typename _StorageIndex>
class Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >
a class to manipulate the L supernodal factor from the SparseLU factorization
This class contain the data to easily store and manipulate the supernodes during the factorization and solution phase of Sparse LU. Only the lower triangular matrix has supernodes.
NOTE : This class corresponds to the SCformat structure in SuperLU
Member Typedef Documentation
template<typename _Scalar, typename _StorageIndex> typedef Matrix<StorageIndex,Dynamic,1> Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::IndexVector
template<typename _Scalar, typename _StorageIndex> typedef _Scalar Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::Scalar
template<typename _Scalar, typename _StorageIndex> typedef Matrix<Scalar,Dynamic,1> Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::ScalarVector
template<typename _Scalar, typename _StorageIndex> typedef _StorageIndex Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::StorageIndex
Constructor & Destructor Documentation
template<typename _Scalar, typename _StorageIndex> Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::MappedSuperNodalMatrix () inline
template<typename _Scalar, typename _StorageIndex> Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::MappedSuperNodalMatrix (Index m, Index n, ScalarVector & nzval, IndexVector & nzval_colptr, IndexVector & rowind, IndexVector & rowind_colptr, IndexVector & col_to_sup, IndexVector & sup_to_col) inline
template<typename _Scalar, typename _StorageIndex> Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::~MappedSuperNodalMatrix () inline
Member Function Documentation
template<typename _Scalar, typename _StorageIndex> StorageIndex* Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::colIndexPtr () inline
Return the pointers to the beginning of each column in valuePtr()
Referenced by Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::solveInPlace().
template<typename _Scalar, typename _StorageIndex> const StorageIndex* Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::colIndexPtr () const inline
template<typename _Scalar, typename _StorageIndex> Index Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::cols (void) inline
Number of columns
template<typename _Scalar, typename _StorageIndex> StorageIndex* Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::colToSup () inline
Return the array of column-to-supernode mapping
template<typename _Scalar, typename _StorageIndex> const StorageIndex* Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::colToSup () const inline
template<typename _Scalar, typename _StorageIndex> Index Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::nsuper () const inline
Return the number of supernodes
Referenced by Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::solveInPlace().
template<typename _Scalar, typename _StorageIndex> StorageIndex* Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::rowIndex () inline
Return the array of compressed row indices of all supernodes
Referenced by Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::solveInPlace().
template<typename _Scalar, typename _StorageIndex> const StorageIndex* Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::rowIndex () const inline
template<typename _Scalar, typename _StorageIndex> StorageIndex* Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::rowIndexPtr () inline
Return the location in rowvaluePtr() which starts each column
Referenced by Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::solveInPlace().
template<typename _Scalar, typename _StorageIndex> const StorageIndex* Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::rowIndexPtr () const inline
template<typename _Scalar, typename _StorageIndex> Index Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::rows (void) inline
Number of rows
template<typename _Scalar, typename _StorageIndex> void Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::setInfos (Index m, Index n, ScalarVector & nzval, IndexVector & nzval_colptr, IndexVector & rowind, IndexVector & rowind_colptr, IndexVector & col_to_sup, IndexVector & sup_to_col) inline
Set appropriate pointers for the lower triangular supernodal matrix These infos are available at the end of the numerical factorization FIXME This class will be modified such that it can be use in the course of the factorization.
Referenced by Eigen::SparseLU< _MatrixType, _OrderingType >::factorize(), and Eigen::internal::MappedSuperNodalMatrix< Scalar, StorageIndex >::MappedSuperNodalMatrix().
template<typename Scalar , typename Index_ > template<typename Dest > void Eigen::internal::MappedSuperNodalMatrix< Scalar, Index_ >::solveInPlace (MatrixBase< Dest > & X) const
Solve with the supernode triangular matrix.
References Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::colIndexPtr(), i, it, Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::nsuper(), Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::InnerIterator::row(), Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::rowIndex(), Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::rowIndexPtr(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::setZero(), Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::supToCol(), Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::InnerIterator::value(), and Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::valuePtr().
Referenced by Eigen::internal::MappedSuperNodalMatrix< Scalar, StorageIndex >::nsuper().
template<typename _Scalar, typename _StorageIndex> StorageIndex* Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::supToCol () inline
Return the array of supernode-to-column mapping
Referenced by Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::solveInPlace().
template<typename _Scalar, typename _StorageIndex> const StorageIndex* Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::supToCol () const inline
template<typename _Scalar, typename _StorageIndex> Scalar* Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::valuePtr () inline
Return the array of nonzero values packed by column
The size is nnz
Referenced by Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::solveInPlace().
template<typename _Scalar, typename _StorageIndex> const Scalar* Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::valuePtr () const inline
Member Data Documentation
template<typename _Scalar, typename _StorageIndex> Index Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::m_col protected
Referenced by Eigen::internal::MappedSuperNodalMatrix< Scalar, StorageIndex >::cols(), and Eigen::internal::MappedSuperNodalMatrix< Scalar, StorageIndex >::setInfos().
template<typename _Scalar, typename _StorageIndex> StorageIndex* Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::m_col_to_sup protected
Referenced by Eigen::internal::MappedSuperNodalMatrix< Scalar, StorageIndex >::colToSup(), and Eigen::internal::MappedSuperNodalMatrix< Scalar, StorageIndex >::setInfos().
template<typename _Scalar, typename _StorageIndex> Index Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::m_nsuper protected
Referenced by Eigen::internal::MappedSuperNodalMatrix< Scalar, StorageIndex >::nsuper(), and Eigen::internal::MappedSuperNodalMatrix< Scalar, StorageIndex >::setInfos().
template<typename _Scalar, typename _StorageIndex> Scalar* Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::m_nzval protected
Referenced by Eigen::internal::MappedSuperNodalMatrix< Scalar, StorageIndex >::setInfos(), and Eigen::internal::MappedSuperNodalMatrix< Scalar, StorageIndex >::valuePtr().
template<typename _Scalar, typename _StorageIndex> StorageIndex* Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::m_nzval_colptr protected
Referenced by Eigen::internal::MappedSuperNodalMatrix< Scalar, StorageIndex >::colIndexPtr(), and Eigen::internal::MappedSuperNodalMatrix< Scalar, StorageIndex >::setInfos().
template<typename _Scalar, typename _StorageIndex> Index Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::m_row protected
Referenced by Eigen::internal::MappedSuperNodalMatrix< Scalar, StorageIndex >::rows(), and Eigen::internal::MappedSuperNodalMatrix< Scalar, StorageIndex >::setInfos().
template<typename _Scalar, typename _StorageIndex> StorageIndex* Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::m_rowind protected
Referenced by Eigen::internal::MappedSuperNodalMatrix< Scalar, StorageIndex >::rowIndex(), and Eigen::internal::MappedSuperNodalMatrix< Scalar, StorageIndex >::setInfos().
template<typename _Scalar, typename _StorageIndex> StorageIndex* Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::m_rowind_colptr protected
Referenced by Eigen::internal::MappedSuperNodalMatrix< Scalar, StorageIndex >::rowIndexPtr(), and Eigen::internal::MappedSuperNodalMatrix< Scalar, StorageIndex >::setInfos().
template<typename _Scalar, typename _StorageIndex> StorageIndex* Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::m_sup_to_col protected
Referenced by Eigen::internal::MappedSuperNodalMatrix< Scalar, StorageIndex >::setInfos(), and Eigen::internal::MappedSuperNodalMatrix< Scalar, StorageIndex >::supToCol().
The documentation for this class was generated from the following file:
SparseLU_SupernodalMatrix.h