SmartMouse_2018: StateWidget Class Reference
StateWidget Class Reference
#include <StateWidget.h>
Signals
void SetLeftVelocity (QString str)
void SetRightVelocity (QString str)
void SetLeftCurrent (QString str)
void SetRightCurrent (QString str)
void SetLeftAcceleration (QString str)
void SetRightAcceleration (QString str)
void SetLeftForce (QString str)
void SetRightForce (QString str)
void SetRow (QString str)
void SetCol (QString str)
void SetDir (QString str)
void SetTrueCol (QString str)
void SetTrueRow (QString str)
void SetTrueYaw (QString str)
void SetEstimatedCol (QString str)
void SetEstimatedRow (QString str)
void SetEstimatedYaw (QString str)
void HighlightCol (QString str)
void HighlightRow (QString str)
void HighlightYaw (QString str)
Public Member Functions
StateWidget ()
const QString GetTabName () override
Private Member Functions
void RobotCommandCallback (const smartmouse::msgs::RobotCommand &msg)
void DebugStateCallback (const smartmouse::msgs::DebugState &msg)
void StateCallback (const smartmouse::msgs::RobotSimState &msg)
Private Attributes
double true_col
double true_row
double true_yaw
ignition::transport::Node node_
Ui::StateWidget * ui_
PIDPlotWidget * pid_widget_
ControlPlotWidget * control_widget_
Constructor & Destructor Documentation
StateWidget::StateWidget ()
References control_widget_, DebugStateCallback(), PIDPlotWidget::GetTabName(), ControlPlotWidget::GetTabName(), TopicNames::kDebugState, TopicNames::kRobotCommand, TopicNames::kRobotSimState, node_, pid_widget_, RobotCommandCallback(), SetCol(), SetDir(), SetEstimatedCol(), SetEstimatedRow(), SetEstimatedYaw(), SetLeftAcceleration(), SetLeftCurrent(), SetLeftForce(), SetLeftVelocity(), SetRightAcceleration(), SetRightCurrent(), SetRightForce(), SetRightVelocity(), SetRow(), SetTrueCol(), SetTrueRow(), SetTrueYaw(), StateCallback(), and ui_.
Member Function Documentation
void StateWidget::DebugStateCallback (const smartmouse::msgs::DebugState & msg) private
References M_PI, SetEstimatedCol(), SetEstimatedRow(), SetEstimatedYaw(), and smartmouse::maze::toMeters().
Referenced by StateWidget().
const QString StateWidget::GetTabName () override virtual
Implements AbstractTab.
void StateWidget::HighlightCol (QString str) signal
void StateWidget::HighlightRow (QString str) signal
void StateWidget::HighlightYaw (QString str) signal
void StateWidget::RobotCommandCallback (const smartmouse::msgs::RobotCommand & msg) private
References SetLeftForce(), and SetRightForce().
Referenced by StateWidget().
void StateWidget::SetCol (QString str) signal
Referenced by StateCallback(), and StateWidget().
void StateWidget::SetDir (QString str) signal
Referenced by StateCallback(), and StateWidget().
void StateWidget::SetEstimatedCol (QString str) signal
Referenced by DebugStateCallback(), and StateWidget().
void StateWidget::SetEstimatedRow (QString str) signal
Referenced by DebugStateCallback(), and StateWidget().
void StateWidget::SetEstimatedYaw (QString str) signal
Referenced by DebugStateCallback(), and StateWidget().
void StateWidget::SetLeftAcceleration (QString str) signal
Referenced by StateCallback(), and StateWidget().
void StateWidget::SetLeftCurrent (QString str) signal
Referenced by StateCallback(), and StateWidget().
void StateWidget::SetLeftForce (QString str) signal
Referenced by RobotCommandCallback(), and StateWidget().
void StateWidget::SetLeftVelocity (QString str) signal
Referenced by StateCallback(), and StateWidget().
void StateWidget::SetRightAcceleration (QString str) signal
Referenced by StateCallback(), and StateWidget().
void StateWidget::SetRightCurrent (QString str) signal
Referenced by StateCallback(), and StateWidget().
void StateWidget::SetRightForce (QString str) signal
Referenced by RobotCommandCallback(), and StateWidget().
void StateWidget::SetRightVelocity (QString str) signal
Referenced by StateCallback(), and StateWidget().
void StateWidget::SetRow (QString str) signal
Referenced by StateCallback(), and StateWidget().
void StateWidget::SetTrueCol (QString str) signal
Referenced by StateCallback(), and StateWidget().
void StateWidget::SetTrueRow (QString str) signal
Referenced by StateCallback(), and StateWidget().
void StateWidget::SetTrueYaw (QString str) signal
Referenced by StateCallback(), and StateWidget().
void StateWidget::StateCallback (const smartmouse::msgs::RobotSimState & msg) private
References M_PI, smartmouse::kc::radToCU(), SetCol(), SetDir(), SetLeftAcceleration(), SetLeftCurrent(), SetLeftVelocity(), SetRightAcceleration(), SetRightCurrent(), SetRightVelocity(), SetRow(), SetTrueCol(), SetTrueRow(), SetTrueYaw(), smartmouse::maze::toMeters(), and yaw_to_char().
Referenced by StateWidget().
Member Data Documentation
ControlPlotWidget* StateWidget::control_widget_ private
Referenced by StateWidget().
ignition::transport::Node StateWidget::node_ private
Referenced by StateWidget().
PIDPlotWidget* StateWidget::pid_widget_ private
Referenced by StateWidget().
double StateWidget::true_col private
double StateWidget::true_row private
double StateWidget::true_yaw private
Ui::StateWidget* StateWidget::ui_ private
Referenced by StateWidget().
The documentation for this class was generated from the following files:
StateWidget.h
StateWidget.cpp