SmartMouse_2018: Eigen::DiagonalPreconditioner< _Scalar > Class Template Reference
Eigen::DiagonalPreconditioner< _Scalar > Class Template Reference
A preconditioner based on the digonal entries.
#include <BasicPreconditioners.h>
Public Types
enum { ColsAtCompileTime = Dynamic, MaxColsAtCompileTime = Dynamic }
typedef Vector::StorageIndex StorageIndex
Public Member Functions
DiagonalPreconditioner ()
template<typename MatType >
DiagonalPreconditioner (const MatType &mat)
Index rows () const
Index cols () const
template<typename MatType >
DiagonalPreconditioner & analyzePattern (const MatType &)
template<typename MatType >
DiagonalPreconditioner & factorize (const MatType &mat)
template<typename MatType >
DiagonalPreconditioner & compute (const MatType &mat)
template<typename Rhs , typename Dest >
void _solve_impl (const Rhs &b, Dest &x) const
template<typename Rhs >
const Solve< DiagonalPreconditioner, Rhs > solve (const MatrixBase< Rhs > &b) const
ComputationInfo info ()
Protected Attributes
Vector m_invdiag
bool m_isInitialized
Private Types
typedef _Scalar Scalar
typedef Matrix< Scalar, Dynamic, 1 > Vector
Detailed Description
template<typename _Scalar>
class Eigen::DiagonalPreconditioner< _Scalar >
A preconditioner based on the digonal entries.
This class allows to approximately solve for A.x = b problems assuming A is a diagonal matrix. In other words, this preconditioner neglects all off diagonal entries and, in Eigen's language, solves for:
A.diagonal().asDiagonal() . x = b
Template Parameters
_Scalar the type of the scalar.
This preconditioner is suitable for both selfadjoint and general problems. The diagonal entries are pre-inverted and stored into a dense vector.
Note
A variant that has yet to be implemented would attempt to preserve the norm of each column.
See also
class LeastSquareDiagonalPreconditioner, class ConjugateGradient
Member Typedef Documentation
template<typename _Scalar > typedef _Scalar Eigen::DiagonalPreconditioner< _Scalar >::Scalar private
template<typename _Scalar > typedef Vector::StorageIndex Eigen::DiagonalPreconditioner< _Scalar >::StorageIndex
template<typename _Scalar > typedef Matrix<Scalar,Dynamic,1> Eigen::DiagonalPreconditioner< _Scalar >::Vector private
Member Enumeration Documentation
template<typename _Scalar > anonymous enum
Enumerator
ColsAtCompileTime
MaxColsAtCompileTime
Constructor & Destructor Documentation
template<typename _Scalar > Eigen::DiagonalPreconditioner< _Scalar >::DiagonalPreconditioner () inline
template<typename _Scalar > template<typename MatType > Eigen::DiagonalPreconditioner< _Scalar >::DiagonalPreconditioner (const MatType & mat) inline explicit
References Eigen::DiagonalPreconditioner< _Scalar >::compute().
Member Function Documentation
template<typename _Scalar > template<typename Rhs , typename Dest > void Eigen::DiagonalPreconditioner< _Scalar >::_solve_impl (const Rhs & b, Dest & x) const inline
References Eigen::DiagonalPreconditioner< _Scalar >::m_invdiag.
template<typename _Scalar > template<typename MatType > DiagonalPreconditioner& Eigen::DiagonalPreconditioner< _Scalar >::analyzePattern (const MatType &) inline
template<typename _Scalar > Index Eigen::DiagonalPreconditioner< _Scalar >::cols (void) const inline
References Eigen::DiagonalPreconditioner< _Scalar >::m_invdiag.
template<typename _Scalar > template<typename MatType > DiagonalPreconditioner& Eigen::DiagonalPreconditioner< _Scalar >::compute (const MatType & mat) inline
References Eigen::DiagonalPreconditioner< _Scalar >::factorize().
Referenced by Eigen::DiagonalPreconditioner< _Scalar >::DiagonalPreconditioner(), and Eigen::LeastSquareDiagonalPreconditioner< _Scalar >::LeastSquareDiagonalPreconditioner().
template<typename _Scalar > template<typename MatType > DiagonalPreconditioner& Eigen::DiagonalPreconditioner< _Scalar >::factorize (const MatType & mat) inline
References it, Eigen::DiagonalPreconditioner< _Scalar >::m_invdiag, Eigen::DiagonalPreconditioner< _Scalar >::m_isInitialized, and Eigen::PlainObjectBase< Derived >::resize().
Referenced by Eigen::DiagonalPreconditioner< _Scalar >::compute(), and Eigen::LeastSquareDiagonalPreconditioner< _Scalar >::compute().
template<typename _Scalar > ComputationInfo Eigen::DiagonalPreconditioner< _Scalar >::info () inline
References Eigen::Success.
template<typename _Scalar > Index Eigen::DiagonalPreconditioner< _Scalar >::rows (void) const inline
References Eigen::DiagonalPreconditioner< _Scalar >::m_invdiag.
template<typename _Scalar > template<typename Rhs > const Solve<DiagonalPreconditioner, Rhs> Eigen::DiagonalPreconditioner< _Scalar >::solve (const MatrixBase< Rhs > & b) const inline
References eigen_assert, Eigen::DiagonalPreconditioner< _Scalar >::m_invdiag, and Eigen::DiagonalPreconditioner< _Scalar >::m_isInitialized.
Member Data Documentation
template<typename _Scalar > Vector Eigen::DiagonalPreconditioner< _Scalar >::m_invdiag protected
Referenced by Eigen::DiagonalPreconditioner< _Scalar >::_solve_impl(), Eigen::DiagonalPreconditioner< _Scalar >::cols(), Eigen::DiagonalPreconditioner< _Scalar >::factorize(), Eigen::LeastSquareDiagonalPreconditioner< _Scalar >::factorize(), Eigen::DiagonalPreconditioner< _Scalar >::rows(), and Eigen::DiagonalPreconditioner< _Scalar >::solve().
template<typename _Scalar > bool Eigen::DiagonalPreconditioner< _Scalar >::m_isInitialized protected
Referenced by Eigen::DiagonalPreconditioner< _Scalar >::factorize(), and Eigen::DiagonalPreconditioner< _Scalar >::solve().
The documentation for this class was generated from the following file:
BasicPreconditioners.h