SmartMouse_2018: JoystickEvent Class Reference
JoystickEvent Class Reference
#include <joystick.hh>
Public Member Functions
bool isButton ()
bool isAxis ()
bool isInitialState ()
Public Attributes
unsigned int time
short value
unsigned char type
unsigned char number
Static Public Attributes
static const short MIN_AXES_VALUE = -32768
static const short MAX_AXES_VALUE = 32767
Friends
std::ostream & operator<< (std::ostream &os, const JoystickEvent &e)
Detailed Description
Encapsulates all data relevant to a sampled joystick event.
Member Function Documentation
bool JoystickEvent::isAxis () inline
Returns true if this event is the result of an axis movement.
References JS_EVENT_AXIS.
Referenced by main().
bool JoystickEvent::isButton () inline
Returns true if this event is the result of a button press.
References JS_EVENT_BUTTON.
Referenced by main().
bool JoystickEvent::isInitialState () inline
Returns true if this event is part of the initial state obtained when the joystick is first connected to.
References e, JS_EVENT_INIT, and operator<<.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const JoystickEvent & e) friend
The ostream inserter needs to be a friend so it can access the internal data structures.
Stream insertion function so you can do this: cout << event << endl;
Referenced by isInitialState().
Member Data Documentation
const short JoystickEvent::MAX_AXES_VALUE = 32767 static
Minimum value of axes range
const short JoystickEvent::MIN_AXES_VALUE = -32768 static
Minimum value of axes range
unsigned char JoystickEvent::number
The axis/button number.
Referenced by main(), and operator<<().
unsigned int JoystickEvent::time
The timestamp of the event, in milliseconds.
unsigned char JoystickEvent::type
The event type.
Referenced by main(), and operator<<().
short JoystickEvent::value
The value associated with this joystick event. For buttons this will be either 1 (down) or 0 (up). For axes, this will range between MIN_AXES_VALUE and MAX_AXES_VALUE.
Referenced by main(), and operator<<().
The documentation for this class was generated from the following file:
joystick.hh