SmartMouse_2018: Eigen::SparseMatrixBase< Derived > Class Template Reference
Eigen::SparseMatrixBase< Derived > Class Template Reference
Base class of any sparse matrices or sparse expressions.
#include <ForwardDeclarations.h>
Classes
struct CastXpr
struct ConstFixedBlockXpr
struct ConstFixedSegmentReturnType
struct ConstNColsBlockXpr
struct ConstNRowsBlockXpr
struct ConstSelfAdjointViewReturnType
struct CwiseProductDenseReturnType
struct FixedBlockXpr
struct FixedSegmentReturnType
struct NColsBlockXpr
struct NRowsBlockXpr
struct SelfAdjointViewReturnType
Public Types
enum {
RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime, ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime, SizeAtCompileTime, MaxRowsAtCompileTime = RowsAtCompileTime,
MaxColsAtCompileTime = ColsAtCompileTime, MaxSizeAtCompileTime, IsVectorAtCompileTime = RowsAtCompileTime == 1 || ColsAtCompileTime == 1, Flags = internal::traits<Derived>::Flags,
IsRowMajor = Flags&RowMajorBit ? 1 : 0, InnerSizeAtCompileTime, _HasDirectAccess = (int(Flags)&DirectAccessBit) ? 1 : 0
}
typedef internal::traits< Derived >::Scalar Scalar
typedef Scalar value_type
typedef internal::packet_traits< Scalar >::type PacketScalar
typedef internal::traits< Derived >::StorageKind StorageKind
typedef internal::traits< Derived >::StorageIndex StorageIndex
typedef internal::add_const_on_value_type_if_arithmetic< typename internal::packet_traits< Scalar >::type >::type PacketReturnType
typedef SparseMatrixBase StorageBaseType
typedef Matrix< StorageIndex, Dynamic, 1 > IndexVector
typedef Matrix< Scalar, Dynamic, 1 > ScalarVector
typedef internal::conditional< NumTraits< Scalar >::IsComplex, CwiseUnaryOp< internal::scalar_conjugate_op< Scalar >, Eigen::Transpose< const Derived > >, Transpose< const Derived > >::type AdjointReturnType
typedef Transpose< Derived > TransposeReturnType
typedef internal::add_const< Transpose< const Derived > >::type ConstTransposeReturnType
typedef SparseMatrix< Scalar, Flags &RowMajorBit?RowMajor:ColMajor, StorageIndex > PlainObject
typedef NumTraits< Scalar >::Real RealScalar
typedef internal::conditional< _HasDirectAccess, const Scalar &, Scalar >::type CoeffReturnType
typedef CwiseNullaryOp< internal::scalar_constant_op< Scalar >, Matrix< Scalar, Dynamic, Dynamic > > ConstantReturnType
typedef Matrix< Scalar, RowsAtCompileTime, ColsAtCompileTime > DenseMatrixType
typedef Matrix< Scalar, EIGEN_SIZE_MAX(RowsAtCompileTime, ColsAtCompileTime), EIGEN_SIZE_MAX(RowsAtCompileTime, ColsAtCompileTime)> SquareMatrixType
typedef EigenBase< Derived > Base
typedef internal::conditional< NumTraits< Scalar >::IsComplex, const CwiseUnaryOp< internal::scalar_conjugate_op< Scalar >, const Derived >, const Derived & >::type ConjugateReturnType
typedef internal::conditional< NumTraits< Scalar >::IsComplex, const CwiseUnaryOp< internal::scalar_real_op< Scalar >, const Derived >, const Derived & >::type RealReturnType
typedef internal::conditional< NumTraits< Scalar >::IsComplex, CwiseUnaryView< internal::scalar_real_ref_op< Scalar >, Derived >, Derived & >::type NonConstRealReturnType
typedef CwiseUnaryOp< internal::scalar_imag_op< Scalar >, const Derived > ImagReturnType
typedef CwiseUnaryView< internal::scalar_imag_ref_op< Scalar >, Derived > NonConstImagReturnType
typedef CwiseUnaryOp< internal::scalar_opposite_op< Scalar >, const Derived > NegativeReturnType
typedef CwiseUnaryOp< internal::scalar_abs_op< Scalar >, const Derived > CwiseAbsReturnType
typedef CwiseUnaryOp< internal::scalar_abs2_op< Scalar >, const Derived > CwiseAbs2ReturnType
typedef CwiseUnaryOp< internal::scalar_sqrt_op< Scalar >, const Derived > CwiseSqrtReturnType
typedef CwiseUnaryOp< internal::scalar_sign_op< Scalar >, const Derived > CwiseSignReturnType
typedef CwiseUnaryOp< internal::scalar_inverse_op< Scalar >, const Derived > CwiseInverseReturnType
typedef CwiseBinaryOp< internal::scalar_cmp_op< Scalar, Scalar, internal::cmp_EQ >, const Derived, const ConstantReturnType > CwiseScalarEqualReturnType
typedef Block< Derived, internal::traits< Derived >::RowsAtCompileTime, 1,!IsRowMajor > ColXpr
typedef const Block< const Derived, internal::traits< Derived >::RowsAtCompileTime, 1,!IsRowMajor > ConstColXpr
typedef Block< Derived, 1, internal::traits< Derived >::ColsAtCompileTime, IsRowMajor > RowXpr
typedef const Block< const Derived, 1, internal::traits< Derived >::ColsAtCompileTime, IsRowMajor > ConstRowXpr
typedef Block< Derived, internal::traits< Derived >::RowsAtCompileTime, Dynamic,!IsRowMajor > ColsBlockXpr
typedef const Block< const Derived, internal::traits< Derived >::RowsAtCompileTime, Dynamic,!IsRowMajor > ConstColsBlockXpr
typedef Block< Derived, Dynamic, internal::traits< Derived >::ColsAtCompileTime, IsRowMajor > RowsBlockXpr
typedef const Block< const Derived, Dynamic, internal::traits< Derived >::ColsAtCompileTime, IsRowMajor > ConstRowsBlockXpr
typedef Block< Derived > BlockXpr
typedef const Block< const Derived > ConstBlockXpr
typedef VectorBlock< Derived > SegmentReturnType
typedef const VectorBlock< const Derived > ConstSegmentReturnType
typedef Block< Derived, IsRowMajor?1:Dynamic, IsRowMajor?Dynamic:1, true > InnerVectorReturnType
typedef Block< const Derived, IsRowMajor?1:Dynamic, IsRowMajor?Dynamic:1, true > ConstInnerVectorReturnType
typedef Block< Derived, Dynamic, Dynamic, true > InnerVectorsReturnType
typedef Block< const Derived, Dynamic, Dynamic, true > ConstInnerVectorsReturnType
Public Types inherited from Eigen::EigenBase< Derived >
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< Derived >::StorageKind StorageKind
Public Member Functions
template<typename OtherDerived >
Derived & operator= (const EigenBase< OtherDerived > &other)
const Derived & derived () const
Derived & derived ()
Derived & const_cast_derived () const
EIGEN_DEVICE_FUNC const NegativeReturnType operator- () const
template<typename NewType >
EIGEN_DEVICE_FUNC CastXpr< NewType >::Type cast () const
EIGEN_DEVICE_FUNC ConjugateReturnType conjugate () const
EIGEN_DEVICE_FUNC RealReturnType real () const
EIGEN_DEVICE_FUNC const ImagReturnType imag () const
template<typename CustomUnaryOp >
EIGEN_DEVICE_FUNC const CwiseUnaryOp< CustomUnaryOp, const Derived > unaryExpr (const CustomUnaryOp &func=CustomUnaryOp()) const
Apply a unary operator coefficient-wise.
template<typename CustomViewOp >
EIGEN_DEVICE_FUNC const CwiseUnaryView< CustomViewOp, const Derived > unaryViewExpr (const CustomViewOp &func=CustomViewOp()) const
EIGEN_DEVICE_FUNC NonConstRealReturnType real ()
EIGEN_DEVICE_FUNC NonConstImagReturnType imag ()
template<typename CustomBinaryOp , typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp< CustomBinaryOp, const Derived, const OtherDerived > binaryExpr (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other, const CustomBinaryOp &func=CustomBinaryOp()) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC const CwiseBinaryOp< internal::scalar_boolean_and_op, const Derived, const OtherDerived > operator&& (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC const CwiseBinaryOp< internal::scalar_boolean_or_op, const Derived, const OtherDerived > operator|| (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseAbsReturnType cwiseAbs () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseAbs2ReturnType cwiseAbs2 () const
EIGEN_DEVICE_FUNC const CwiseSqrtReturnType cwiseSqrt () const
EIGEN_DEVICE_FUNC const CwiseSignReturnType cwiseSign () const
EIGEN_DEVICE_FUNC const CwiseInverseReturnType cwiseInverse () const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const EIGEN_CWISE_BINARY_RETURN_TYPE (Derived, OtherDerived, product) cwiseProduct(const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC const CwiseBinaryOp< std::equal_to< Scalar >, const Derived, const OtherDerived > cwiseEqual (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC const CwiseBinaryOp< std::not_equal_to< Scalar >, const Derived, const OtherDerived > cwiseNotEqual (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp< internal::scalar_min_op< Scalar, Scalar >, const Derived, const OtherDerived > cwiseMin (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp< internal::scalar_min_op< Scalar, Scalar >, const Derived, const ConstantReturnType > cwiseMin (const Scalar &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp< internal::scalar_max_op< Scalar, Scalar >, const Derived, const OtherDerived > cwiseMax (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp< internal::scalar_max_op< Scalar, Scalar >, const Derived, const ConstantReturnType > cwiseMax (const Scalar &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp< internal::scalar_quotient_op< Scalar >, const Derived, const OtherDerived > cwiseQuotient (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
EIGEN_DEVICE_FUNC const CwiseScalarEqualReturnType cwiseEqual (const Scalar &s) const
template<typename NRowsType , typename NColsType >
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type block (Index startRow, Index startCol, NRowsType blockRows, NColsType blockCols)
template<typename NRowsType , typename NColsType >
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type block (Index startRow, Index startCol, NRowsType blockRows, NColsType blockCols) const
This is the const version of block(Index,Index,NRowsType,NColsType)
template<typename NRowsType , typename NColsType >
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type topRightCorner (NRowsType cRows, NColsType cCols)
template<typename NRowsType , typename NColsType >
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type topRightCorner (NRowsType cRows, NColsType cCols) const
This is the const version of topRightCorner(NRowsType, NColsType).
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type topRightCorner ()
template<int CRows, int CCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type topRightCorner () const
This is the const version of topRightCorner<int, int>().
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type topRightCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
const ConstFixedBlockXpr< CRows, CCols >::Type topRightCorner (Index cRows, Index cCols) const
This is the const version of topRightCorner<int, int>(Index, Index).
template<typename NRowsType , typename NColsType >
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type topLeftCorner (NRowsType cRows, NColsType cCols)
template<typename NRowsType , typename NColsType >
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type topLeftCorner (NRowsType cRows, NColsType cCols) const
This is the const version of topLeftCorner(Index, Index).
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type topLeftCorner ()
template<int CRows, int CCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type topLeftCorner () const
This is the const version of topLeftCorner<int, int>().
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type topLeftCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
const ConstFixedBlockXpr< CRows, CCols >::Type topLeftCorner (Index cRows, Index cCols) const
This is the const version of topLeftCorner<int, int>(Index, Index).
template<typename NRowsType , typename NColsType >
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type bottomRightCorner (NRowsType cRows, NColsType cCols)
template<typename NRowsType , typename NColsType >
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type bottomRightCorner (NRowsType cRows, NColsType cCols) const
This is the const version of bottomRightCorner(NRowsType, NColsType).
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type bottomRightCorner ()
template<int CRows, int CCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type bottomRightCorner () const
This is the const version of bottomRightCorner<int, int>().
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type bottomRightCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
const ConstFixedBlockXpr< CRows, CCols >::Type bottomRightCorner (Index cRows, Index cCols) const
This is the const version of bottomRightCorner<int, int>(Index, Index).
template<typename NRowsType , typename NColsType >
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type bottomLeftCorner (NRowsType cRows, NColsType cCols)
template<typename NRowsType , typename NColsType >
EIGEN_DEVICE_FUNC ConstFixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type bottomLeftCorner (NRowsType cRows, NColsType cCols) const
This is the const version of bottomLeftCorner(NRowsType, NColsType).
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type bottomLeftCorner ()
template<int CRows, int CCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type bottomLeftCorner () const
This is the const version of bottomLeftCorner<int, int>().
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type bottomLeftCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
const ConstFixedBlockXpr< CRows, CCols >::Type bottomLeftCorner (Index cRows, Index cCols) const
This is the const version of bottomLeftCorner<int, int>(Index, Index).
template<typename NRowsType >
EIGEN_DEVICE_FUNC NRowsBlockXpr< internal::get_fixed_value< NRowsType >::value >::Type topRows (NRowsType n)
template<typename NRowsType >
EIGEN_DEVICE_FUNC const ConstNRowsBlockXpr< internal::get_fixed_value< NRowsType >::value >::Type topRows (NRowsType n) const
This is the const version of topRows(NRowsType).
template<int N>
EIGEN_DEVICE_FUNC NRowsBlockXpr< N >::Type topRows (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNRowsBlockXpr< N >::Type topRows (Index n=N) const
This is the const version of topRows<int>().
template<typename NRowsType >
EIGEN_DEVICE_FUNC NRowsBlockXpr< internal::get_fixed_value< NRowsType >::value >::Type bottomRows (NRowsType n)
template<typename NRowsType >
EIGEN_DEVICE_FUNC const ConstNRowsBlockXpr< internal::get_fixed_value< NRowsType >::value >::Type bottomRows (NRowsType n) const
This is the const version of bottomRows(NRowsType).
template<int N>
EIGEN_DEVICE_FUNC NRowsBlockXpr< N >::Type bottomRows (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNRowsBlockXpr< N >::Type bottomRows (Index n=N) const
This is the const version of bottomRows<int>().
template<typename NRowsType >
EIGEN_DEVICE_FUNC NRowsBlockXpr< internal::get_fixed_value< NRowsType >::value >::Type middleRows (Index startRow, NRowsType n)
template<typename NRowsType >
EIGEN_DEVICE_FUNC const ConstNRowsBlockXpr< internal::get_fixed_value< NRowsType >::value >::Type middleRows (Index startRow, NRowsType n) const
This is the const version of middleRows(Index,NRowsType).
template<int N>
EIGEN_DEVICE_FUNC NRowsBlockXpr< N >::Type middleRows (Index startRow, Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNRowsBlockXpr< N >::Type middleRows (Index startRow, Index n=N) const
This is the const version of middleRows<int>().
template<typename NColsType >
EIGEN_DEVICE_FUNC NColsBlockXpr< internal::get_fixed_value< NColsType >::value >::Type leftCols (NColsType n)
template<typename NColsType >
EIGEN_DEVICE_FUNC const ConstNColsBlockXpr< internal::get_fixed_value< NColsType >::value >::Type leftCols (NColsType n) const
This is the const version of leftCols(NColsType).
template<int N>
EIGEN_DEVICE_FUNC NColsBlockXpr< N >::Type leftCols (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNColsBlockXpr< N >::Type leftCols (Index n=N) const
This is the const version of leftCols<int>().
template<typename NColsType >
EIGEN_DEVICE_FUNC NColsBlockXpr< internal::get_fixed_value< NColsType >::value >::Type rightCols (NColsType n)
template<typename NColsType >
EIGEN_DEVICE_FUNC const ConstNColsBlockXpr< internal::get_fixed_value< NColsType >::value >::Type rightCols (NColsType n) const
This is the const version of rightCols(NColsType).
template<int N>
EIGEN_DEVICE_FUNC NColsBlockXpr< N >::Type rightCols (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNColsBlockXpr< N >::Type rightCols (Index n=N) const
This is the const version of rightCols<int>().
template<typename NColsType >
EIGEN_DEVICE_FUNC NColsBlockXpr< internal::get_fixed_value< NColsType >::value >::Type middleCols (Index startCol, NColsType numCols)
template<typename NColsType >
EIGEN_DEVICE_FUNC const ConstNColsBlockXpr< internal::get_fixed_value< NColsType >::value >::Type middleCols (Index startCol, NColsType numCols) const
This is the const version of middleCols(Index,NColsType).
template<int N>
EIGEN_DEVICE_FUNC NColsBlockXpr< N >::Type middleCols (Index startCol, Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNColsBlockXpr< N >::Type middleCols (Index startCol, Index n=N) const
This is the const version of middleCols<int>().
template<int NRows, int NCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol)
template<int NRows, int NCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol) const
This is the const version of block<>(Index, Index). */.
template<int NRows, int NCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol, Index blockRows, Index blockCols)
template<int NRows, int NCols>
const ConstFixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol, Index blockRows, Index blockCols) const
This is the const version of block<>(Index, Index, Index, Index).
EIGEN_DEVICE_FUNC ColXpr col (Index i)
EIGEN_DEVICE_FUNC ConstColXpr col (Index i) const
This is the const version of col().
EIGEN_DEVICE_FUNC RowXpr row (Index i)
EIGEN_DEVICE_FUNC ConstRowXpr row (Index i) const
This is the const version of row(). */.
template<typename NType >
EIGEN_DEVICE_FUNC FixedSegmentReturnType< internal::get_fixed_value< NType >::value >::Type segment (Index start, NType n)
template<typename NType >
EIGEN_DEVICE_FUNC const ConstFixedSegmentReturnType< internal::get_fixed_value< NType >::value >::Type segment (Index start, NType n) const
This is the const version of segment(Index,NType).
template<typename NType >
EIGEN_DEVICE_FUNC FixedSegmentReturnType< internal::get_fixed_value< NType >::value >::Type head (NType n)
template<typename NType >
EIGEN_DEVICE_FUNC const ConstFixedSegmentReturnType< internal::get_fixed_value< NType >::value >::Type head (NType n) const
This is the const version of head(NType).
template<typename NType >
EIGEN_DEVICE_FUNC FixedSegmentReturnType< internal::get_fixed_value< NType >::value >::Type tail (NType n)
template<typename NType >
EIGEN_DEVICE_FUNC const ConstFixedSegmentReturnType< internal::get_fixed_value< NType >::value >::Type tail (NType n) const
This is the const version of tail(Index).
template<int N>
EIGEN_DEVICE_FUNC FixedSegmentReturnType< N >::Type segment (Index start, Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType< N >::Type segment (Index start, Index n=N) const
This is the const version of segment<int>(Index).
template<int N>
EIGEN_DEVICE_FUNC FixedSegmentReturnType< N >::Type head (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType< N >::Type head (Index n=N) const
This is the const version of head<int>().
template<int N>
EIGEN_DEVICE_FUNC FixedSegmentReturnType< N >::Type tail (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType< N >::Type tail (Index n=N) const
This is the const version of tail<int>.
Index rows () const
Index cols () const
Index size () const
bool isVector () const
Index outerSize () const
Index innerSize () const
bool isRValue () const
Derived & markAsRValue ()
SparseMatrixBase ()
template<typename OtherDerived >
Derived & operator= (const ReturnByValue< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator= (const SparseMatrixBase< OtherDerived > &other)
Derived & operator= (const Derived &other)
template<typename OtherDerived >
Derived & operator+= (const SparseMatrixBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator-= (const SparseMatrixBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator+= (const DiagonalBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator-= (const DiagonalBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator+= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator-= (const EigenBase< OtherDerived > &other)
Derived & operator*= (const Scalar &other)
Derived & operator/= (const Scalar &other)
template<typename OtherDerived >
EIGEN_STRONG_INLINE const CwiseProductDenseReturnType< OtherDerived >::Type cwiseProduct (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
const Product< Derived, OtherDerived > operator* (const DiagonalBase< OtherDerived > &other) const
template<typename OtherDerived >
const Product< Derived, OtherDerived, AliasFreeProduct > operator* (const SparseMatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
const Product< Derived, OtherDerived > operator* (const MatrixBase< OtherDerived > &other) const
SparseSymmetricPermutationProduct< Derived, Upper|Lower > twistedBy (const PermutationMatrix< Dynamic, Dynamic, StorageIndex > &perm) const
template<typename OtherDerived >
Derived & operator*= (const SparseMatrixBase< OtherDerived > &other)
template<int Mode>
const TriangularView< const Derived, Mode > triangularView () const
template<unsigned int UpLo>
ConstSelfAdjointViewReturnType< UpLo >::Type selfadjointView () const
template<unsigned int UpLo>
SelfAdjointViewReturnType< UpLo >::Type selfadjointView ()
template<typename OtherDerived >
Scalar dot (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
Scalar dot (const SparseMatrixBase< OtherDerived > &other) const
RealScalar squaredNorm () const
RealScalar norm () const
RealScalar blueNorm () const
TransposeReturnType transpose ()
const ConstTransposeReturnType transpose () const
const AdjointReturnType adjoint () const
InnerVectorReturnType innerVector (Index outer)
const ConstInnerVectorReturnType innerVector (Index outer) const
InnerVectorsReturnType innerVectors (Index outerStart, Index outerSize)
const ConstInnerVectorsReturnType innerVectors (Index outerStart, Index outerSize) const
DenseMatrixType toDense () const
template<typename OtherDerived >
bool isApprox (const SparseMatrixBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
template<typename OtherDerived >
bool isApprox (const MatrixBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
const internal::eval< Derived >::type eval () const
Scalar sum () const
const SparseView< Derived > pruned (const Scalar &reference=Scalar(0), const RealScalar &epsilon=NumTraits< Scalar >::dummy_precision()) const
template<typename OtherDerived >
EIGEN_STRONG_INLINE Derived & operator-= (const SparseMatrixBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_STRONG_INLINE Derived & operator+= (const SparseMatrixBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_STRONG_INLINE const SparseMatrixBase< Derived >::template CwiseProductDenseReturnType< OtherDerived >::Type cwiseProduct (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
internal::traits< Derived >::Scalar dot (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
internal::traits< Derived >::Scalar dot (const SparseMatrixBase< OtherDerived > &other) const
template<unsigned int UpLo>
SparseMatrixBase< Derived >::template ConstSelfAdjointViewReturnType< UpLo >::Type selfadjointView () const
template<unsigned int UpLo>
SparseMatrixBase< Derived >::template SelfAdjointViewReturnType< UpLo >::Type selfadjointView ()
Public Member Functions inherited from Eigen::EigenBase< Derived >
EIGEN_DEVICE_FUNC Derived & derived ()
EIGEN_DEVICE_FUNC const Derived & derived () const
EIGEN_DEVICE_FUNC Derived & const_cast_derived () const
EIGEN_DEVICE_FUNC const Derived & const_derived () const
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
EIGEN_DEVICE_FUNC Index size () const
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
Protected Member Functions
template<typename OtherDerived >
Derived & assign (const OtherDerived &other)
template<typename OtherDerived >
void assignGeneric (const OtherDerived &other)
Static Protected Member Functions
static StorageIndex convert_index (const Index idx)
Protected Attributes
bool m_isRValue
Private Member Functions
template<typename Dest >
void evalTo (Dest &) const
Friends
std::ostream & operator<< (std::ostream &s, const SparseMatrixBase &m)
template<typename OtherDerived >
const Product< OtherDerived, Derived > operator* (const DiagonalBase< OtherDerived > &lhs, const SparseMatrixBase &rhs)
template<typename OtherDerived >
const Product< OtherDerived, Derived > operator* (const MatrixBase< OtherDerived > &lhs, const SparseMatrixBase &rhs)
Detailed Description
template<typename Derived>
class Eigen::SparseMatrixBase< Derived >
Base class of any sparse matrices or sparse expressions.
Template Parameters
Derived is the derived type, e.g. a sparse matrix type, or an expression, etc.
This class can be extended with the help of the plugin mechanism described on the page TopicCustomizing_Plugins by defining the preprocessor symbol EIGEN_SPARSEMATRIXBASE_PLUGIN.
Member Typedef Documentation
template<typename Derived> typedef internal::conditional<NumTraits<Scalar>::IsComplex, CwiseUnaryOp<internal::scalar_conjugate_op<Scalar>, Eigen::Transpose<const Derived> >, Transpose<const Derived> >::type Eigen::SparseMatrixBase< Derived >::AdjointReturnType
template<typename Derived> typedef EigenBase<Derived> Eigen::SparseMatrixBase< Derived >::Base
template<typename Derived> typedef Block<Derived> Eigen::SparseMatrixBase< Derived >::BlockXpr
template<typename Derived> typedef internal::conditional<_HasDirectAccess, const Scalar&, Scalar>::type Eigen::SparseMatrixBase< Derived >::CoeffReturnType
template<typename Derived> typedef Block<Derived, internal::traits<Derived>::RowsAtCompileTime, Dynamic, !IsRowMajor> Eigen::SparseMatrixBase< Derived >::ColsBlockXpr
template<typename Derived> typedef Block<Derived, internal::traits<Derived>::RowsAtCompileTime, 1, !IsRowMajor> Eigen::SparseMatrixBase< Derived >::ColXpr
template<typename Derived> typedef internal::conditional<NumTraits<Scalar>::IsComplex, const CwiseUnaryOp<internal::scalar_conjugate_op<Scalar>, const Derived>, const Derived& >::type Eigen::SparseMatrixBase< Derived >::ConjugateReturnType
template<typename Derived> typedef CwiseNullaryOp<internal::scalar_constant_op<Scalar>,Matrix<Scalar,Dynamic,Dynamic> > Eigen::SparseMatrixBase< Derived >::ConstantReturnType
template<typename Derived> typedef const Block<const Derived> Eigen::SparseMatrixBase< Derived >::ConstBlockXpr
template<typename Derived> typedef const Block<const Derived, internal::traits<Derived>::RowsAtCompileTime, Dynamic, !IsRowMajor> Eigen::SparseMatrixBase< Derived >::ConstColsBlockXpr
template<typename Derived> typedef const Block<const Derived, internal::traits<Derived>::RowsAtCompileTime, 1, !IsRowMajor> Eigen::SparseMatrixBase< Derived >::ConstColXpr
template<typename Derived> typedef Block<const Derived,IsRowMajor?1:Dynamic,IsRowMajor?Dynamic:1,true> Eigen::SparseMatrixBase< Derived >::ConstInnerVectorReturnType
template<typename Derived> typedef Block<const Derived,Dynamic,Dynamic,true> Eigen::SparseMatrixBase< Derived >::ConstInnerVectorsReturnType
template<typename Derived> typedef const Block<const Derived, Dynamic, internal::traits<Derived>::ColsAtCompileTime, IsRowMajor> Eigen::SparseMatrixBase< Derived >::ConstRowsBlockXpr
template<typename Derived> typedef const Block<const Derived, 1, internal::traits<Derived>::ColsAtCompileTime, IsRowMajor> Eigen::SparseMatrixBase< Derived >::ConstRowXpr
template<typename Derived> typedef const VectorBlock<const Derived> Eigen::SparseMatrixBase< Derived >::ConstSegmentReturnType
template<typename Derived> typedef internal::add_const<Transpose<const Derived> >::type Eigen::SparseMatrixBase< Derived >::ConstTransposeReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_abs2_op<Scalar>, const Derived> Eigen::SparseMatrixBase< Derived >::CwiseAbs2ReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_abs_op<Scalar>, const Derived> Eigen::SparseMatrixBase< Derived >::CwiseAbsReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_inverse_op<Scalar>, const Derived> Eigen::SparseMatrixBase< Derived >::CwiseInverseReturnType
template<typename Derived> typedef CwiseBinaryOp<internal::scalar_cmp_op<Scalar,Scalar,internal::cmp_EQ>, const Derived, const ConstantReturnType> Eigen::SparseMatrixBase< Derived >::CwiseScalarEqualReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_sign_op<Scalar>, const Derived> Eigen::SparseMatrixBase< Derived >::CwiseSignReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_sqrt_op<Scalar>, const Derived> Eigen::SparseMatrixBase< Derived >::CwiseSqrtReturnType
template<typename Derived> typedef Matrix<Scalar,RowsAtCompileTime,ColsAtCompileTime> Eigen::SparseMatrixBase< Derived >::DenseMatrixType
type of the equivalent dense matrix
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_imag_op<Scalar>, const Derived> Eigen::SparseMatrixBase< Derived >::ImagReturnType
template<typename Derived> typedef Matrix<StorageIndex,Dynamic,1> Eigen::SparseMatrixBase< Derived >::IndexVector
template<typename Derived> typedef Block<Derived,IsRowMajor?1:Dynamic,IsRowMajor?Dynamic:1,true> Eigen::SparseMatrixBase< Derived >::InnerVectorReturnType
template<typename Derived> typedef Block<Derived,Dynamic,Dynamic,true> Eigen::SparseMatrixBase< Derived >::InnerVectorsReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_opposite_op<Scalar>, const Derived> Eigen::SparseMatrixBase< Derived >::NegativeReturnType
template<typename Derived> typedef CwiseUnaryView<internal::scalar_imag_ref_op<Scalar>, Derived> Eigen::SparseMatrixBase< Derived >::NonConstImagReturnType
template<typename Derived> typedef internal::conditional<NumTraits<Scalar>::IsComplex, CwiseUnaryView<internal::scalar_real_ref_op<Scalar>, Derived>, Derived& >::type Eigen::SparseMatrixBase< Derived >::NonConstRealReturnType
template<typename Derived> typedef internal::add_const_on_value_type_if_arithmetic< typename internal::packet_traits<Scalar>::type >::type Eigen::SparseMatrixBase< Derived >::PacketReturnType
template<typename Derived> typedef internal::packet_traits<Scalar>::type Eigen::SparseMatrixBase< Derived >::PacketScalar
template<typename Derived> typedef SparseMatrix<Scalar, Flags&RowMajorBit ? RowMajor : ColMajor, StorageIndex> Eigen::SparseMatrixBase< Derived >::PlainObject
template<typename Derived> typedef internal::conditional<NumTraits<Scalar>::IsComplex, const CwiseUnaryOp<internal::scalar_real_op<Scalar>, const Derived>, const Derived& >::type Eigen::SparseMatrixBase< Derived >::RealReturnType
template<typename Derived> typedef NumTraits<Scalar>::Real Eigen::SparseMatrixBase< Derived >::RealScalar
This is the "real scalar" type; if the Scalar type is already real numbers (e.g. int, float or double) then RealScalar is just the same as Scalar. If Scalar is std::complex<T> then RealScalar is T.
See also
class NumTraits
template<typename Derived> typedef Block<Derived, Dynamic, internal::traits<Derived>::ColsAtCompileTime, IsRowMajor> Eigen::SparseMatrixBase< Derived >::RowsBlockXpr
template<typename Derived> typedef Block<Derived, 1, internal::traits<Derived>::ColsAtCompileTime, IsRowMajor> Eigen::SparseMatrixBase< Derived >::RowXpr
template<typename Derived> typedef internal::traits<Derived>::Scalar Eigen::SparseMatrixBase< Derived >::Scalar
template<typename Derived> typedef Matrix<Scalar,Dynamic,1> Eigen::SparseMatrixBase< Derived >::ScalarVector
template<typename Derived> typedef VectorBlock<Derived> Eigen::SparseMatrixBase< Derived >::SegmentReturnType
template<typename Derived> typedef Matrix<Scalar,EIGEN_SIZE_MAX(RowsAtCompileTime,ColsAtCompileTime), EIGEN_SIZE_MAX(RowsAtCompileTime,ColsAtCompileTime)> Eigen::SparseMatrixBase< Derived >::SquareMatrixType
type of the equivalent square matrix
template<typename Derived> typedef SparseMatrixBase Eigen::SparseMatrixBase< Derived >::StorageBaseType
template<typename Derived> typedef internal::traits<Derived>::StorageIndex Eigen::SparseMatrixBase< Derived >::StorageIndex
The integer type used to store indices within a SparseMatrix. For a SparseMatrix<Scalar,Options,IndexType> it an alias of the third template parameter IndexType.
template<typename Derived> typedef internal::traits<Derived>::StorageKind Eigen::SparseMatrixBase< Derived >::StorageKind
template<typename Derived> typedef Transpose<Derived> Eigen::SparseMatrixBase< Derived >::TransposeReturnType
template<typename Derived> typedef Scalar Eigen::SparseMatrixBase< Derived >::value_type
The numeric type of the expression' coefficients, e.g. float, double, int or std::complex<float>, etc.
It is an alias for the Scalar type
Member Enumeration Documentation
template<typename Derived> anonymous enum
Enumerator
RowsAtCompileTime
The number of rows at compile-time. This is just a copy of the value provided by the Derived type. If a value is not known at compile-time, it is set to the Dynamic constant.
See also
MatrixBase::rows(), MatrixBase::cols(), ColsAtCompileTime, SizeAtCompileTime
ColsAtCompileTime
The number of columns at compile-time. This is just a copy of the value provided by the Derived type. If a value is not known at compile-time, it is set to the Dynamic constant.
See also
MatrixBase::rows(), MatrixBase::cols(), RowsAtCompileTime, SizeAtCompileTime
SizeAtCompileTime
This is equal to the number of coefficients, i.e. the number of rows times the number of columns, or to Dynamic if this is not known at compile-time.
See also
RowsAtCompileTime, ColsAtCompileTime
MaxRowsAtCompileTime
MaxColsAtCompileTime
MaxSizeAtCompileTime
IsVectorAtCompileTime
This is set to true if either the number of rows or the number of columns is known at compile-time to be equal to 1. Indeed, in that case, we are dealing with a column-vector (if there is only one column) or with a row-vector (if there is only one row).
Flags
This stores expression Flags flags which may or may not be inherited by new expressions constructed from this one. See the list of flags.
IsRowMajor
InnerSizeAtCompileTime
_HasDirectAccess
Constructor & Destructor Documentation
template<typename Derived> Eigen::SparseMatrixBase< Derived >::SparseMatrixBase () inline
Member Function Documentation
template<typename Derived> const AdjointReturnType Eigen::SparseMatrixBase< Derived >::adjoint () const inline
Referenced by Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::_solve_impl(), and Eigen::SparseSelfAdjointView< MatrixType, _Mode >::rankUpdate().
template<typename Derived> template<typename OtherDerived > Derived& Eigen::SparseMatrixBase< Derived >::assign (const OtherDerived & other) inline protected
template<typename Derived> template<typename OtherDerived > void Eigen::SparseMatrixBase< Derived >::assignGeneric (const OtherDerived & other) inline protected
template<typename Derived> template<typename CustomBinaryOp , typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp<CustomBinaryOp, const Derived, const OtherDerived> Eigen::SparseMatrixBase< Derived >::binaryExpr (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > & other, const CustomBinaryOp & func = CustomBinaryOp()) const inline
Returns
an expression of the difference of *this and other
Note
If you want to substract a given scalar from all coefficients, see Cwise::operator-().
See also
class CwiseBinaryOp, operator-=()
Returns
an expression of the sum of *this and other
Note
If you want to add a given scalar to all coefficients, see Cwise::operator+().
See also
class CwiseBinaryOp, operator+=()
Returns
an expression of a custom coefficient-wise operator func of *this and other
The template parameter CustomBinaryOp is the type of the functor of the custom operator (see class CwiseBinaryOp for an example)
Here is an example illustrating the use of custom functors:
Output:
See also
class CwiseBinaryOp, operator+(), operator-(), cwiseProduct()
template<typename Derived> template<typename NRowsType , typename NColsType > EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<internal::get_fixed_value<NRowsType>::value,internal::get_fixed_value<NColsType>::value>::Type Eigen::SparseMatrixBase< Derived >::block (Index startRow, Index startCol, NRowsType blockRows, NColsType blockCols) inline
Returns
an expression of a block in *this with either dynamic or fixed sizes.
Parameters
startRow the first row in the block
startCol the first column in the block
blockRows number of rows in the block, specified at either run-time or compile-time
blockCols number of columns in the block, specified at either run-time or compile-time
Template Parameters
NRowsType the type of the value handling the number of rows in the block, typically Index.
NColsType the type of the value handling the number of columns in the block, typically Index.
Example using runtime (aka dynamic) sizes:
Output:
{3.4}:
The number of rows blockRows and columns blockCols can also be specified at compile-time by passing Eigen::fix<N>, or Eigen::fix<N>(n) as arguments. In the later case, n plays the role of a runtime fallback value in case N equals Eigen::Dynamic. Here is an example with a fixed number of rows NRows and dynamic number of columns cols:
mat.block(i,j,fix<NRows>,cols)
This function thus fully covers the features offered by the following overloads block<NRows,NCols>(Index, Index), and block<NRows,NCols>(Index, Index, Index, Index) that are thus obsolete. Indeed, this generic version avoids redundancy, it preserves the argument order, and prevents the need to rely on the template keyword in templated code.
but with less redundancy and more consistency as it does not modify the argument order and seamlessly enable hybrid fixed/dynamic sizes.
Note
Even in the case that the returned expression has dynamic size, in the case when it is applied to a fixed-size matrix, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See also
class Block, fix, fix<N>(int)
template<typename Derived> template<typename NRowsType , typename NColsType > EIGEN_DEVICE_FUNC const ConstFixedBlockXpr<internal::get_fixed_value<NRowsType>::value,internal::get_fixed_value<NColsType>::value>::Type Eigen::SparseMatrixBase< Derived >::block (Index startRow, Index startCol, NRowsType blockRows, NColsType blockCols) const inline
This is the const version of block(Index,Index,NRowsType,NColsType)
template<typename Derived> template<int NRows, int NCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<NRows,NCols>::Type Eigen::SparseMatrixBase< Derived >::block (Index startRow, Index startCol) inline
Returns
a fixed-size expression of a block of *this.
The template parameters NRows and NCols are the number of rows and columns in the block.
Parameters
startRow the first row in the block
startCol the first column in the block
Example:
Output:
Note
The usage of of this overload is discouraged from Eigen 3.4, better used the generic block(Index,Index,NRowsType,NColsType), here is the one-to-one equivalence:
mat.template block<NRows,NCols>(i,j)  <-->  mat.block(i,j,fix<NRows>,fix<NCols>)
since block is a templated member, the keyword template has to be used if the matrix type is also a template parameter:
m.template block<3,3>(1,1);
See also
block(Index,Index,NRowsType,NColsType), class Block
template<typename Derived> template<int NRows, int NCols> EIGEN_DEVICE_FUNC const ConstFixedBlockXpr<NRows,NCols>::Type Eigen::SparseMatrixBase< Derived >::block (Index startRow, Index startCol) const inline
This is the const version of block<>(Index, Index). */.
template<typename Derived> template<int NRows, int NCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr<NRows,NCols>::Type Eigen::SparseMatrixBase< Derived >::block (Index startRow, Index startCol, Index blockRows, Index blockCols) inline
Returns
an expression of a block of *this.
Template Parameters
NRows number of rows in block as specified at compile-time
NCols number of columns in block as specified at compile-time
Parameters
startRow the first row in the block
startCol the first column in the block
blockRows number of rows in block as specified at run-time
blockCols number of columns in block as specified at run-time
This function is mainly useful for blocks where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, blockRows should equal NRows unless NRows is Dynamic, and the same for the number of columns.
Example:
Output:
Note
The usage of of this overload is discouraged from Eigen 3.4, better used the generic block(Index,Index,NRowsType,NColsType), here is the one-to-one complete equivalence:
mat.template block<NRows,NCols>(i,j,rows,cols)     <-->  mat.block(i,j,fix<NRows>(rows),fix<NCols>(cols))
If we known that, e.g., NRows==Dynamic and NCols!=Dynamic, then the equivalence becomes:
mat.template block<Dynamic,NCols>(i,j,rows,NCols)  <-->  mat.block(i,j,rows,fix<NCols>)
See also
block(Index,Index,NRowsType,NColsType), class Block
template<typename Derived> template<int NRows, int NCols> const ConstFixedBlockXpr<NRows,NCols>::Type Eigen::SparseMatrixBase< Derived >::block (Index startRow, Index startCol, Index blockRows, Index blockCols) const inline
This is the const version of block<>(Index, Index, Index, Index).
template<typename Derived > NumTraits< typename internal::traits< Derived >::Scalar >::Real Eigen::SparseMatrixBase< Derived >::blueNorm () const inline
References Eigen::internal::blueNorm_impl().
template<typename Derived> template<typename NRowsType , typename NColsType > EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<internal::get_fixed_value<NRowsType>::value,internal::get_fixed_value<NColsType>::value>::Type Eigen::SparseMatrixBase< Derived >::bottomLeftCorner (NRowsType cRows, NColsType cCols) inline
Returns
an expression of a bottom-left corner of *this with either dynamic or fixed sizes.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Template Parameters
NRowsType the type of the value handling the number of rows in the block, typically Index.
NColsType the type of the value handling the number of columns in the block, typically Index.
Example:
Output:
The number of rows blockRows and columns blockCols can also be specified at compile-time by passing Eigen::fix<N>, or Eigen::fix<N>(n) as arguments. See block() for the details.
See also
block(Index,Index,NRowsType,NColsType), class Block
template<typename Derived> template<typename NRowsType , typename NColsType > EIGEN_DEVICE_FUNC ConstFixedBlockXpr<internal::get_fixed_value<NRowsType>::value,internal::get_fixed_value<NColsType>::value>::Type Eigen::SparseMatrixBase< Derived >::bottomLeftCorner (NRowsType cRows, NColsType cCols) const inline
This is the const version of bottomLeftCorner(NRowsType, NColsType).
template<typename Derived> template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<CRows,CCols>::Type Eigen::SparseMatrixBase< Derived >::bottomLeftCorner () inline
Returns
an expression of a fixed-size bottom-left corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Output:
See also
block(Index,Index,NRowsType,NColsType), class Block
template<typename Derived> template<int CRows, int CCols> EIGEN_DEVICE_FUNC const ConstFixedBlockXpr<CRows,CCols>::Type Eigen::SparseMatrixBase< Derived >::bottomLeftCorner () const inline
This is the const version of bottomLeftCorner<int, int>().
template<typename Derived> template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr<CRows,CCols>::Type Eigen::SparseMatrixBase< Derived >::bottomLeftCorner (Index cRows, Index cCols) inline
Returns
an expression of a bottom-left corner of *this.
Template Parameters
CRows number of rows in corner as specified at compile-time
CCols number of columns in corner as specified at compile-time
Parameters
cRows number of rows in corner as specified at run-time
cCols number of columns in corner as specified at run-time
This function is mainly useful for corners where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, cRows should equal CRows unless CRows is Dynamic, and the same for the number of columns.
Example:
Output:
See also
class Block
template<typename Derived> template<int CRows, int CCols> const ConstFixedBlockXpr<CRows,CCols>::Type Eigen::SparseMatrixBase< Derived >::bottomLeftCorner (Index cRows, Index cCols) const inline
This is the const version of bottomLeftCorner<int, int>(Index, Index).
template<typename Derived> template<typename NRowsType , typename NColsType > EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<internal::get_fixed_value<NRowsType>::value,internal::get_fixed_value<NColsType>::value>::Type Eigen::SparseMatrixBase< Derived >::bottomRightCorner (NRowsType cRows, NColsType cCols) inline
Returns
an expression of a bottom-right corner of *this with either dynamic or fixed sizes.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Template Parameters
NRowsType the type of the value handling the number of rows in the block, typically Index.
NColsType the type of the value handling the number of columns in the block, typically Index.
Example:
Output:
The number of rows blockRows and columns blockCols can also be specified at compile-time by passing Eigen::fix<N>, or Eigen::fix<N>(n) as arguments. See block() for the details.
See also
block(Index,Index,NRowsType,NColsType), class Block
template<typename Derived> template<typename NRowsType , typename NColsType > EIGEN_DEVICE_FUNC const ConstFixedBlockXpr<internal::get_fixed_value<NRowsType>::value,internal::get_fixed_value<NColsType>::value>::Type Eigen::SparseMatrixBase< Derived >::bottomRightCorner (NRowsType cRows, NColsType cCols) const inline
This is the const version of bottomRightCorner(NRowsType, NColsType).
template<typename Derived> template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<CRows,CCols>::Type Eigen::SparseMatrixBase< Derived >::bottomRightCorner () inline
Returns
an expression of a fixed-size bottom-right corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Output:
See also
block(Index,Index,NRowsType,NColsType), class Block
template<typename Derived> template<int CRows, int CCols> EIGEN_DEVICE_FUNC const ConstFixedBlockXpr<CRows,CCols>::Type Eigen::SparseMatrixBase< Derived >::bottomRightCorner () const inline
This is the const version of bottomRightCorner<int, int>().
template<typename Derived> template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr<CRows,CCols>::Type Eigen::SparseMatrixBase< Derived >::bottomRightCorner (Index cRows, Index cCols) inline
Returns
an expression of a bottom-right corner of *this.
Template Parameters
CRows number of rows in corner as specified at compile-time
CCols number of columns in corner as specified at compile-time
Parameters
cRows number of rows in corner as specified at run-time
cCols number of columns in corner as specified at run-time
This function is mainly useful for corners where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, cRows should equal CRows unless CRows is Dynamic, and the same for the number of columns.
Example:
Output:
See also
class Block
template<typename Derived> template<int CRows, int CCols> const ConstFixedBlockXpr<CRows,CCols>::Type Eigen::SparseMatrixBase< Derived >::bottomRightCorner (Index cRows, Index cCols) const inline
This is the const version of bottomRightCorner<int, int>(Index, Index).
template<typename Derived> template<typename NRowsType > EIGEN_DEVICE_FUNC NRowsBlockXpr<internal::get_fixed_value<NRowsType>::value>::Type Eigen::SparseMatrixBase< Derived >::bottomRows (NRowsType n) inline
Returns
a block consisting of the bottom rows of *this.
Parameters
n the number of rows in the block
Template Parameters
NRowsType the type of the value handling the number of rows in the block, typically Index.
Example:
Output:
The number of rows n can also be specified at compile-time by passing Eigen::fix<N>, or Eigen::fix<N>(n) as arguments. See block() for the details.
See also
block(Index,Index,NRowsType,NColsType), class Block
template<typename Derived> template<typename NRowsType > EIGEN_DEVICE_FUNC const ConstNRowsBlockXpr<internal::get_fixed_value<NRowsType>::value>::Type Eigen::SparseMatrixBase< Derived >::bottomRows (NRowsType n) const inline
This is the const version of bottomRows(NRowsType).
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC NRowsBlockXpr<N>::Type Eigen::SparseMatrixBase< Derived >::bottomRows (Index n = N) inline
Returns
a block consisting of the bottom rows of *this.
Template Parameters
N the number of rows in the block as specified at compile-time
Parameters
n the number of rows in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
block(Index,Index,NRowsType,NColsType), class Block
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC ConstNRowsBlockXpr<N>::Type Eigen::SparseMatrixBase< Derived >::bottomRows (Index n = N) const inline
This is the const version of bottomRows<int>().
template<typename Derived> template<typename NewType > EIGEN_DEVICE_FUNC CastXpr<NewType>::Type Eigen::SparseMatrixBase< Derived >::cast () const inline
Returns
an expression of *this with the Scalar type casted to NewScalar.
The template parameter NewScalar is the type we are casting the scalars to.
See also
class CwiseUnaryOp
template<typename Derived> EIGEN_DEVICE_FUNC ColXpr Eigen::SparseMatrixBase< Derived >::col (Index i) inline
Returns
an expression of the i-th column of *this. Note that the numbering starts at 0.
Example:
Output:
See also
row(), class Block
Referenced by Eigen::SPQR< _MatrixType >::compute().
template<typename Derived> EIGEN_DEVICE_FUNC ConstColXpr Eigen::SparseMatrixBase< Derived >::col (Index i) const inline
This is the const version of col().
template<typename Derived> Index Eigen::SparseMatrixBase< Derived >::cols (void) const inline
Returns
the number of columns.
See also
rows()
Referenced by Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::innerSize(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::isVector(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::outerSize(), and Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::size().
template<typename Derived> EIGEN_DEVICE_FUNC ConjugateReturnType Eigen::SparseMatrixBase< Derived >::conjugate () const inline
Returns
an expression of the complex conjugate of *this.
See also
Math functions, MatrixBase::adjoint()
template<typename Derived> Derived& Eigen::SparseMatrixBase< Derived >::const_cast_derived () const inline
Referenced by Eigen::CholmodBase< _MatrixType, _UpLo, CholmodSimplicialLLT< _MatrixType, _UpLo > >::_solve_impl(), Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::operator=(), Eigen::Ref< SparseMatrix< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Ref(), and Eigen::Ref< SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Ref().
template<typename Derived> static StorageIndex Eigen::SparseMatrixBase< Derived >::convert_index (const Index idx) inline static protected
template<typename Derived> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseAbsReturnType Eigen::SparseMatrixBase< Derived >::cwiseAbs () const inline
Returns
an expression of the coefficient-wise absolute value of *this
Example:
Output:
See also
cwiseAbs2()
template<typename Derived> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseAbs2ReturnType Eigen::SparseMatrixBase< Derived >::cwiseAbs2 () const inline
Returns
an expression of the coefficient-wise squared absolute value of *this
Example:
Output:
See also
cwiseAbs()
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC const CwiseBinaryOp<std::equal_to<Scalar>, const Derived, const OtherDerived> Eigen::SparseMatrixBase< Derived >::cwiseEqual (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > & other) const inline
Returns
an expression of the coefficient-wise == operator of *this and other
Warning
this performs an exact comparison, which is generally a bad idea with floating-point types. In order to check for equality between two vectors or matrices with floating-point coefficients, it is generally a far better idea to use a fuzzy comparison as provided by isApprox() and isMuchSmallerThan().
Example:
Output:
See also
cwiseNotEqual(), isApprox(), isMuchSmallerThan()
template<typename Derived> EIGEN_DEVICE_FUNC const CwiseScalarEqualReturnType Eigen::SparseMatrixBase< Derived >::cwiseEqual (const Scalar & s) const inline
Returns
an expression of the coefficient-wise == operator of *this and a scalar s
Warning
this performs an exact comparison, which is generally a bad idea with floating-point types. In order to check for equality between two vectors or matrices with floating-point coefficients, it is generally a far better idea to use a fuzzy comparison as provided by isApprox() and isMuchSmallerThan().
See also
cwiseEqual(const MatrixBase<OtherDerived> &) const
template<typename Derived> EIGEN_DEVICE_FUNC const CwiseInverseReturnType Eigen::SparseMatrixBase< Derived >::cwiseInverse () const inline
Returns
an expression of the coefficient-wise inverse of *this.
Example:
Output:
See also
cwiseProduct()
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp<internal::scalar_max_op<Scalar,Scalar>, const Derived, const OtherDerived> Eigen::SparseMatrixBase< Derived >::cwiseMax (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > & other) const inline
Returns
an expression of the coefficient-wise max of *this and other
Example:
Output:
See also
class CwiseBinaryOp, min()
template<typename Derived> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp<internal::scalar_max_op<Scalar,Scalar>, const Derived, const ConstantReturnType> Eigen::SparseMatrixBase< Derived >::cwiseMax (const Scalar & other) const inline
Returns
an expression of the coefficient-wise max of *this and scalar other
See also
class CwiseBinaryOp, min()
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp<internal::scalar_min_op<Scalar,Scalar>, const Derived, const OtherDerived> Eigen::SparseMatrixBase< Derived >::cwiseMin (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > & other) const inline
Returns
an expression of the coefficient-wise min of *this and other
Example:
Output:
See also
class CwiseBinaryOp, max()
template<typename Derived> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp<internal::scalar_min_op<Scalar,Scalar>, const Derived, const ConstantReturnType> Eigen::SparseMatrixBase< Derived >::cwiseMin (const Scalar & other) const inline
Returns
an expression of the coefficient-wise min of *this and scalar other
See also
class CwiseBinaryOp, min()
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC const CwiseBinaryOp<std::not_equal_to<Scalar>, const Derived, const OtherDerived> Eigen::SparseMatrixBase< Derived >::cwiseNotEqual (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > & other) const inline
Returns
an expression of the coefficient-wise != operator of *this and other
Warning
this performs an exact comparison, which is generally a bad idea with floating-point types. In order to check for equality between two vectors or matrices with floating-point coefficients, it is generally a far better idea to use a fuzzy comparison as provided by isApprox() and isMuchSmallerThan().
Example:
Output:
See also
cwiseEqual(), isApprox(), isMuchSmallerThan()
template<typename Derived> template<typename OtherDerived > EIGEN_STRONG_INLINE const CwiseProductDenseReturnType<OtherDerived>::Type Eigen::SparseMatrixBase< Derived >::cwiseProduct (const MatrixBase< OtherDerived > & other) const
template<typename Derived> template<typename OtherDerived > EIGEN_STRONG_INLINE const SparseMatrixBase<Derived>::template CwiseProductDenseReturnType<OtherDerived>::Type Eigen::SparseMatrixBase< Derived >::cwiseProduct (const MatrixBase< OtherDerived > & other) const
References EIGEN_STRONG_INLINE.
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp<internal::scalar_quotient_op<Scalar>, const Derived, const OtherDerived> Eigen::SparseMatrixBase< Derived >::cwiseQuotient (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > & other) const inline
Returns
an expression of the coefficient-wise quotient of *this and other
Example:
Output:
See also
class CwiseBinaryOp, cwiseProduct(), cwiseInverse()
template<typename Derived> EIGEN_DEVICE_FUNC const CwiseSignReturnType Eigen::SparseMatrixBase< Derived >::cwiseSign () const inline
Returns
an expression of the coefficient-wise signum of *this.
Example:
Output:
template<typename Derived> EIGEN_DEVICE_FUNC const CwiseSqrtReturnType Eigen::SparseMatrixBase< Derived >::cwiseSqrt () const inline
Returns
an expression of the coefficient-wise square root of *this.
Example:
Output:
See also
cwisePow(), cwiseSquare()
template<typename Derived> const Derived& Eigen::SparseMatrixBase< Derived >::derived () const inline
Referenced by Eigen::SparseSolverBase< SimplicialLDLT< _MatrixType, _UpLo, _Ordering > >::_solve_impl(), Eigen::IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::_solve_impl(), Eigen::CholmodBase< _MatrixType, _UpLo, CholmodSimplicialLLT< _MatrixType, _UpLo > >::_solve_impl(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::cols(), Eigen::SparseMatrixBase< Derived >::dot(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::eval(), Eigen::SparseMatrixBase< Derived >::isApprox(), Eigen::SluMatrix::Map(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::markAsRValue(), Eigen::SparseSelfAdjointView< MatrixType, _Mode >::operator*(), Eigen::operator*(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::operator*(), Eigen::SparseMatrixBase< Derived >::operator*(), Eigen::operator+(), Eigen::SparseMatrixBase< Derived >::operator+=(), Eigen::operator-(), Eigen::SparseMatrixBase< Derived >::operator-=(), Eigen::internal::sparse_matrix_block_impl< const SparseMatrix< _Scalar, _Options, _StorageIndex >, BlockRows, BlockCols >::operator=(), Eigen::SparseMatrixBase< Derived >::operator=(), Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::Ref< const SparseMatrix< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Ref(), Eigen::Ref< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Ref(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::rows(), Eigen::internal::sparse_solve_triangular_sparse_selector< Lhs, Rhs, Mode, UpLo, ColMajor >::run(), Eigen::SparseSolverBase< SimplicialLDLT< _MatrixType, _UpLo, _Ordering > >::solve(), Eigen::SparseQR< _MatrixType, _OrderingType >::solve(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::SparseMatrix(), Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::SparseVector(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::toDense(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::transpose(), and Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::twistedBy().
template<typename Derived> Derived& Eigen::SparseMatrixBase< Derived >::derived () inline
template<typename Derived> template<typename OtherDerived > internal::traits<Derived>::Scalar Eigen::SparseMatrixBase< Derived >::dot (const MatrixBase< OtherDerived > & other) const
References eigen_assert, EIGEN_STATIC_ASSERT, EIGEN_STATIC_ASSERT_SAME_VECTOR_SIZE, EIGEN_STATIC_ASSERT_VECTOR_ONLY, i, and Eigen::internal::size().
template<typename Derived> template<typename OtherDerived > internal::traits<Derived>::Scalar Eigen::SparseMatrixBase< Derived >::dot (const SparseMatrixBase< OtherDerived > & other) const
References Eigen::SparseMatrixBase< Derived >::derived(), eigen_assert, EIGEN_STATIC_ASSERT, EIGEN_STATIC_ASSERT_SAME_VECTOR_SIZE, EIGEN_STATIC_ASSERT_VECTOR_ONLY, i, Eigen::SparseMatrixBase< Derived >::size(), and Eigen::internal::size().
template<typename Derived> template<typename OtherDerived > Scalar Eigen::SparseMatrixBase< Derived >::dot (const MatrixBase< OtherDerived > & other) const
template<typename Derived> template<typename OtherDerived > Scalar Eigen::SparseMatrixBase< Derived >::dot (const SparseMatrixBase< OtherDerived > & other) const
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Eigen::SparseMatrixBase< Derived >::EIGEN_CWISE_BINARY_RETURN_TYPE (Derived , OtherDerived , product) const inline
Returns
an expression of the Schur product (coefficient wise product) of *this and other
Example:
Output:
See also
class CwiseBinaryOp, cwiseAbs2
template<typename Derived> const internal::eval<Derived>::type Eigen::SparseMatrixBase< Derived >::eval () const inline
Returns
the matrix or vector obtained by evaluating this expression.
Notice that in the case of a plain matrix or vector (not an expression) this function just returns a const reference, in order to avoid a useless copy.
template<typename Derived> template<typename Dest > void Eigen::SparseMatrixBase< Derived >::evalTo (Dest &) const private
Referenced by Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::convert_index().
template<typename Derived> template<typename NType > EIGEN_DEVICE_FUNC FixedSegmentReturnType<internal::get_fixed_value<NType>::value>::Type Eigen::SparseMatrixBase< Derived >::head (NType n) inline
Returns
an expression of the first coefficients of *this with either dynamic or fixed sizes.
Parameters
n the number of coefficients in the segment
Template Parameters
NType the type of the value handling the number of coefficients in the segment, typically Index.
Example:
Output:
The number of coefficients n can also be specified at compile-time by passing Eigen::fix<N>, or Eigen::fix<N>(n) as arguments. See block() for the details.
Note
Even in the case that the returned expression has dynamic size, in the case when it is applied to a fixed-size vector, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See also
class Block, block(Index,Index)
template<typename Derived> template<typename NType > EIGEN_DEVICE_FUNC const ConstFixedSegmentReturnType<internal::get_fixed_value<NType>::value>::Type Eigen::SparseMatrixBase< Derived >::head (NType n) const inline
This is the const version of head(NType).
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC FixedSegmentReturnType<N>::Type Eigen::SparseMatrixBase< Derived >::head (Index n = N) inline
Returns
a fixed-size expression of the first coefficients of *this.
Template Parameters
N the number of coefficients in the segment as specified at compile-time
Parameters
n the number of coefficients in the segment as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
head(NType), class Block
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType<N>::Type Eigen::SparseMatrixBase< Derived >::head (Index n = N) const inline
This is the const version of head<int>().
template<typename Derived> EIGEN_DEVICE_FUNC const ImagReturnType Eigen::SparseMatrixBase< Derived >::imag () const inline
Returns
an read-only expression of the imaginary part of *this.
See also
real()
template<typename Derived> EIGEN_DEVICE_FUNC NonConstImagReturnType Eigen::SparseMatrixBase< Derived >::imag () inline
Returns
a non const expression of the imaginary part of *this.
See also
real()
template<typename Derived> Index Eigen::SparseMatrixBase< Derived >::innerSize () const inline
Returns
the size of the inner dimension according to the storage order, i.e., the number of rows for a columns major matrix, and the number of cols otherwise
template<typename Derived > SparseMatrixBase< Derived >::InnerVectorReturnType Eigen::SparseMatrixBase< Derived >::innerVector (Index outer)
Returns
the outer -th column (resp. row) of the matrix *this if *this is col-major (resp. row-major).
template<typename Derived > const SparseMatrixBase< Derived >::ConstInnerVectorReturnType Eigen::SparseMatrixBase< Derived >::innerVector (Index outer) const
Returns
the outer -th column (resp. row) of the matrix *this if *this is col-major (resp. row-major). Read-only.
template<typename Derived > SparseMatrixBase< Derived >::InnerVectorsReturnType Eigen::SparseMatrixBase< Derived >::innerVectors (Index outerStart, Index outerSize)
Returns
the outer -th column (resp. row) of the matrix *this if *this is col-major (resp. row-major).
template<typename Derived > const SparseMatrixBase< Derived >::ConstInnerVectorsReturnType Eigen::SparseMatrixBase< Derived >::innerVectors (Index outerStart, Index outerSize) const
Returns
the outer -th column (resp. row) of the matrix *this if *this is col-major (resp. row-major). Read-only.
template<typename Derived > template<typename OtherDerived > bool Eigen::SparseMatrixBase< Derived >::isApprox (const SparseMatrixBase< OtherDerived > & other, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
References Eigen::SparseMatrixBase< Derived >::derived(), and type.
Referenced by Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::toDense().
template<typename Derived> template<typename OtherDerived > bool Eigen::SparseMatrixBase< Derived >::isApprox (const MatrixBase< OtherDerived > & other, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const inline
template<typename Derived> bool Eigen::SparseMatrixBase< Derived >::isRValue () const inline
Referenced by Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::operator=(), and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::operator=().
template<typename Derived> bool Eigen::SparseMatrixBase< Derived >::isVector () const inline
Returns
true if either the number of rows or the number of columns is equal to 1. In other words, this function returns
rows()==1 || cols()==1
See also
rows(), cols(), IsVectorAtCompileTime.
template<typename Derived> template<typename NColsType > EIGEN_DEVICE_FUNC NColsBlockXpr<internal::get_fixed_value<NColsType>::value>::Type Eigen::SparseMatrixBase< Derived >::leftCols (NColsType n) inline
Returns
a block consisting of the left columns of *this.
Parameters
n the number of columns in the block
Template Parameters
NColsType the type of the value handling the number of columns in the block, typically Index.
Example:
Output:
The number of columns n can also be specified at compile-time by passing Eigen::fix<N>, or Eigen::fix<N>(n) as arguments. See block() for the details.
See also
block(Index,Index,NRowsType,NColsType), class Block
template<typename Derived> template<typename NColsType > EIGEN_DEVICE_FUNC const ConstNColsBlockXpr<internal::get_fixed_value<NColsType>::value>::Type Eigen::SparseMatrixBase< Derived >::leftCols (NColsType n) const inline
This is the const version of leftCols(NColsType).
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC NColsBlockXpr<N>::Type Eigen::SparseMatrixBase< Derived >::leftCols (Index n = N) inline
Returns
a block consisting of the left columns of *this.
Template Parameters
N the number of columns in the block as specified at compile-time
Parameters
n the number of columns in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
block(Index,Index,NRowsType,NColsType), class Block
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC ConstNColsBlockXpr<N>::Type Eigen::SparseMatrixBase< Derived >::leftCols (Index n = N) const inline
This is the const version of leftCols<int>().
template<typename Derived> Derived& Eigen::SparseMatrixBase< Derived >::markAsRValue () inline
Referenced by Eigen::internal::conservative_sparse_sparse_product_selector< Lhs, Rhs, ResultType, ColMajor, ColMajor, ColMajor >::run().
template<typename Derived> template<typename NColsType > EIGEN_DEVICE_FUNC NColsBlockXpr<internal::get_fixed_value<NColsType>::value>::Type Eigen::SparseMatrixBase< Derived >::middleCols (Index startCol, NColsType numCols) inline
Returns
a block consisting of a range of columns of *this.
Parameters
startCol the index of the first column in the block
numCols the number of columns in the block
Template Parameters
NColsType the type of the value handling the number of columns in the block, typically Index.
Example:
Output:
The number of columns n can also be specified at compile-time by passing Eigen::fix<N>, or Eigen::fix<N>(n) as arguments. See block() for the details.
See also
block(Index,Index,NRowsType,NColsType), class Block
template<typename Derived> template<typename NColsType > EIGEN_DEVICE_FUNC const ConstNColsBlockXpr<internal::get_fixed_value<NColsType>::value>::Type Eigen::SparseMatrixBase< Derived >::middleCols (Index startCol, NColsType numCols) const inline
This is the const version of middleCols(Index,NColsType).
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC NColsBlockXpr<N>::Type Eigen::SparseMatrixBase< Derived >::middleCols (Index startCol, Index n = N) inline
Returns
a block consisting of a range of columns of *this.
Template Parameters
N the number of columns in the block as specified at compile-time
Parameters
startCol the index of the first column in the block
n the number of columns in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
block(Index,Index,NRowsType,NColsType), class Block
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC ConstNColsBlockXpr<N>::Type Eigen::SparseMatrixBase< Derived >::middleCols (Index startCol, Index n = N) const inline
This is the const version of middleCols<int>().
template<typename Derived> template<typename NRowsType > EIGEN_DEVICE_FUNC NRowsBlockXpr<internal::get_fixed_value<NRowsType>::value>::Type Eigen::SparseMatrixBase< Derived >::middleRows (Index startRow, NRowsType n) inline
Returns
a block consisting of a range of rows of *this.
Parameters
startRow the index of the first row in the block
n the number of rows in the block
Template Parameters
NRowsType the type of the value handling the number of rows in the block, typically Index.
Example:
Output:
The number of rows n can also be specified at compile-time by passing Eigen::fix<N>, or Eigen::fix<N>(n) as arguments. See block() for the details.
See also
block(Index,Index,NRowsType,NColsType), class Block
template<typename Derived> template<typename NRowsType > EIGEN_DEVICE_FUNC const ConstNRowsBlockXpr<internal::get_fixed_value<NRowsType>::value>::Type Eigen::SparseMatrixBase< Derived >::middleRows (Index startRow, NRowsType n) const inline
This is the const version of middleRows(Index,NRowsType).
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC NRowsBlockXpr<N>::Type Eigen::SparseMatrixBase< Derived >::middleRows (Index startRow, Index n = N) inline
Returns
a block consisting of a range of rows of *this.
Template Parameters
N the number of rows in the block as specified at compile-time
Parameters
startRow the index of the first row in the block
n the number of rows in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
block(Index,Index,NRowsType,NColsType), class Block
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC ConstNRowsBlockXpr<N>::Type Eigen::SparseMatrixBase< Derived >::middleRows (Index startRow, Index n = N) const inline
This is the const version of middleRows<int>().
template<typename Derived > NumTraits< typename internal::traits< Derived >::Scalar >::Real Eigen::SparseMatrixBase< Derived >::norm () const inline
References sqrt().
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC const CwiseBinaryOp<internal::scalar_boolean_and_op, const Derived, const OtherDerived> Eigen::SparseMatrixBase< Derived >::operator&& (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > & other) const inline
Returns
an expression of the coefficient-wise boolean and operator of *this and other
Warning
this operator is for expression of bool only.
Example:
Output:
See also
operator||(), select()
template<typename Derived> template<typename OtherDerived > const Product<Derived,OtherDerived> Eigen::SparseMatrixBase< Derived >::operator* (const DiagonalBase< OtherDerived > & other) const inline
template<typename Derived > template<typename OtherDerived > const Product< Derived, OtherDerived, AliasFreeProduct > Eigen::SparseMatrixBase< Derived >::operator* (const SparseMatrixBase< OtherDerived > & other) const inline
Returns
an expression of the product of two sparse matrices. By default a conservative product preserving the symbolic non zeros is performed. The automatic pruning of the small values can be achieved by calling the pruned() function in which case a totally different product algorithm is employed:
C = (A*B).pruned();             // supress numerical zeros (exact)
C = (A*B).pruned(ref);
C = (A*B).pruned(ref,epsilon);
where ref is a meaningful non zero reference value.
References Eigen::SparseMatrixBase< Derived >::derived().
template<typename Derived> template<typename OtherDerived > const Product<Derived,OtherDerived> Eigen::SparseMatrixBase< Derived >::operator* (const MatrixBase< OtherDerived > & other) const inline
template<typename Derived > EIGEN_STRONG_INLINE Derived & Eigen::SparseMatrixBase< Derived >::operator*= (const Scalar & other)
References EIGEN_STRONG_INLINE, and i.
Referenced by Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::twistedBy().
template<typename Derived> template<typename OtherDerived > Derived& Eigen::SparseMatrixBase< Derived >::operator*= (const SparseMatrixBase< OtherDerived > & other)
template<typename Derived> template<typename OtherDerived > Derived& Eigen::SparseMatrixBase< Derived >::operator+= (const SparseMatrixBase< OtherDerived > & other)
Referenced by Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::topLeftCorner().
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator+= (const DiagonalBase< OtherDerived > & other)
References Eigen::internal::call_assignment_no_alias(), and Eigen::DiagonalBase< Derived >::derived().
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator+= (const EigenBase< OtherDerived > & other)
References Eigen::internal::call_assignment(), and Eigen::EigenBase< Derived >::derived().
template<typename Derived> template<typename OtherDerived > EIGEN_STRONG_INLINE Derived& Eigen::SparseMatrixBase< Derived >::operator+= (const SparseMatrixBase< OtherDerived > & other)
References Eigen::SparseMatrixBase< Derived >::derived().
template<typename Derived> EIGEN_DEVICE_FUNC const NegativeReturnType Eigen::SparseMatrixBase< Derived >::operator- () const inline
Returns
an expression of the opposite of *this
template<typename Derived> template<typename OtherDerived > Derived& Eigen::SparseMatrixBase< Derived >::operator-= (const SparseMatrixBase< OtherDerived > & other)
Referenced by Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::topLeftCorner().
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator-= (const DiagonalBase< OtherDerived > & other)
References Eigen::internal::call_assignment_no_alias(), Eigen::DiagonalBase< Derived >::derived(), and EIGEN_STRONG_INLINE.
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator-= (const EigenBase< OtherDerived > & other)
References Eigen::internal::call_assignment(), Eigen::EigenBase< Derived >::derived(), and EIGEN_STRONG_INLINE.
template<typename Derived> template<typename OtherDerived > EIGEN_STRONG_INLINE Derived& Eigen::SparseMatrixBase< Derived >::operator-= (const SparseMatrixBase< OtherDerived > & other)
References Eigen::SparseMatrixBase< Derived >::derived(), and EIGEN_STRONG_INLINE.
template<typename Derived > EIGEN_STRONG_INLINE Derived & Eigen::SparseMatrixBase< Derived >::operator/= (const Scalar & other)
References i.
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator= (const EigenBase< OtherDerived > & other)
References Eigen::internal::call_assignment_no_alias(), and Eigen::EigenBase< Derived >::derived().
Referenced by Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::SparseMatrixBase().
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator= (const ReturnByValue< OtherDerived > & other)
References Eigen::ReturnByValue< Derived >::evalTo().
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator= (const SparseMatrixBase< OtherDerived > & other) inline
References Eigen::SparseMatrixBase< Derived >::derived().
template<typename Derived> Derived & Eigen::SparseMatrixBase< Derived >::operator= (const Derived & other) inline
References Eigen::internal::call_assignment_no_alias().
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC const CwiseBinaryOp<internal::scalar_boolean_or_op, const Derived, const OtherDerived> Eigen::SparseMatrixBase< Derived >::operator|| (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > & other) const inline
Returns
an expression of the coefficient-wise boolean or operator of *this and other
Warning
this operator is for expression of bool only.
Example:
Output:
See also
operator&&(), select()
template<typename Derived> Index Eigen::SparseMatrixBase< Derived >::outerSize () const inline
Returns
the size of the storage major dimension, i.e., the number of columns for a columns major matrix, and the number of rows otherwise
template<typename Derived > const SparseView< Derived > Eigen::SparseMatrixBase< Derived >::pruned (const Scalar & reference = Scalar(0), const RealScalar & epsilon = NumTraits<Scalar>::dummy_precision()) const inline
Returns
an expression of *this with values smaller than reference * epsilon removed.
This method is typically used in conjunction with the product of two sparse matrices to automatically prune the smallest values as follows:
C = (A*B).pruned();             // suppress numerical zeros (exact)
C = (A*B).pruned(ref);
C = (A*B).pruned(ref,epsilon);
where ref is a meaningful non zero reference value.
template<typename Derived> EIGEN_DEVICE_FUNC RealReturnType Eigen::SparseMatrixBase< Derived >::real () const inline
Returns
a read-only expression of the real part of *this.
See also
imag()
template<typename Derived> EIGEN_DEVICE_FUNC NonConstRealReturnType Eigen::SparseMatrixBase< Derived >::real () inline
Returns
a non const expression of the real part of *this.
See also
imag()
template<typename Derived> template<typename NColsType > EIGEN_DEVICE_FUNC NColsBlockXpr<internal::get_fixed_value<NColsType>::value>::Type Eigen::SparseMatrixBase< Derived >::rightCols (NColsType n) inline
Returns
a block consisting of the right columns of *this.
Parameters
n the number of columns in the block
Template Parameters
NColsType the type of the value handling the number of columns in the block, typically Index.
Example:
Output:
The number of columns n can also be specified at compile-time by passing Eigen::fix<N>, or Eigen::fix<N>(n) as arguments. See block() for the details.
See also
block(Index,Index,NRowsType,NColsType), class Block
template<typename Derived> template<typename NColsType > EIGEN_DEVICE_FUNC const ConstNColsBlockXpr<internal::get_fixed_value<NColsType>::value>::Type Eigen::SparseMatrixBase< Derived >::rightCols (NColsType n) const inline
This is the const version of rightCols(NColsType).
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC NColsBlockXpr<N>::Type Eigen::SparseMatrixBase< Derived >::rightCols (Index n = N) inline
Returns
a block consisting of the right columns of *this.
Template Parameters
N the number of columns in the block as specified at compile-time
Parameters
n the number of columns in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
block(Index,Index,NRowsType,NColsType), class Block
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC ConstNColsBlockXpr<N>::Type Eigen::SparseMatrixBase< Derived >::rightCols (Index n = N) const inline
This is the const version of rightCols<int>().
template<typename Derived> EIGEN_DEVICE_FUNC RowXpr Eigen::SparseMatrixBase< Derived >::row (Index i) inline
Returns
an expression of the i-th row of *this. Note that the numbering starts at 0.
Example:
Output:
See also
col(), class Block
template<typename Derived> EIGEN_DEVICE_FUNC ConstRowXpr Eigen::SparseMatrixBase< Derived >::row (Index i) const inline
This is the const version of row(). */.
template<typename Derived> Index Eigen::SparseMatrixBase< Derived >::rows (void) const inline
Returns
the number of rows.
See also
cols()
Referenced by Eigen::CholmodBase< _MatrixType, _UpLo, CholmodSimplicialLLT< _MatrixType, _UpLo > >::_solve_impl(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::innerSize(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::isVector(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::outerSize(), Eigen::internal::sparse_solve_triangular_sparse_selector< Lhs, Rhs, Mode, UpLo, ColMajor >::run(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::size(), Eigen::SparseSolverBase< SimplicialLDLT< _MatrixType, _UpLo, _Ordering > >::solve(), and Eigen::SparseQR< _MatrixType, _OrderingType >::solve().
template<typename Derived> template<typename NType > EIGEN_DEVICE_FUNC FixedSegmentReturnType<internal::get_fixed_value<NType>::value>::Type Eigen::SparseMatrixBase< Derived >::segment (Index start, NType n) inline
Returns
an expression of a segment (i.e. a vector block) in *this with either dynamic or fixed sizes.
Parameters
start the first coefficient in the segment
n the number of coefficients in the segment
Template Parameters
NType the type of the value handling the number of coefficients in the segment, typically Index.
Example:
Output:
The number of coefficients n can also be specified at compile-time by passing Eigen::fix<N>, or Eigen::fix<N>(n) as arguments. See block() for the details.
Note
Even in the case that the returned expression has dynamic size, in the case when it is applied to a fixed-size vector, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See also
block(Index,Index,NRowsType,NColsType), fix<N>, fix<N>(int), class Block
template<typename Derived> template<typename NType > EIGEN_DEVICE_FUNC const ConstFixedSegmentReturnType<internal::get_fixed_value<NType>::value>::Type Eigen::SparseMatrixBase< Derived >::segment (Index start, NType n) const inline
This is the const version of segment(Index,NType).
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC FixedSegmentReturnType<N>::Type Eigen::SparseMatrixBase< Derived >::segment (Index start, Index n = N) inline
Returns
a fixed-size expression of a segment (i.e. a vector block) in *this
Template Parameters
N the number of coefficients in the segment as specified at compile-time
Parameters
start the index of the first element in the segment
n the number of coefficients in the segment as specified at compile-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
segment(Index,NType), class Block
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType<N>::Type Eigen::SparseMatrixBase< Derived >::segment (Index start, Index n = N) const inline
This is the const version of segment<int>(Index).
template<typename Derived> template<unsigned int UpLo> SparseMatrixBase<Derived>::template ConstSelfAdjointViewReturnType<UpLo>::Type Eigen::SparseMatrixBase< Derived >::selfadjointView () const
template<typename Derived> template<unsigned int UpLo> SparseMatrixBase<Derived>::template SelfAdjointViewReturnType<UpLo>::Type Eigen::SparseMatrixBase< Derived >::selfadjointView ()
template<typename Derived> template<unsigned int UpLo> ConstSelfAdjointViewReturnType<UpLo>::Type Eigen::SparseMatrixBase< Derived >::selfadjointView () const inline
template<typename Derived> template<unsigned int UpLo> SelfAdjointViewReturnType<UpLo>::Type Eigen::SparseMatrixBase< Derived >::selfadjointView () inline
template<typename Derived> Index Eigen::SparseMatrixBase< Derived >::size () const inline
Returns
the number of coefficients, which is rows()*cols().
See also
rows(), cols().
Referenced by Eigen::SparseMatrixBase< Derived >::dot(), and Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::operator=().
template<typename Derived > NumTraits< typename internal::traits< Derived >::Scalar >::Real Eigen::SparseMatrixBase< Derived >::squaredNorm () const inline
References real().
template<typename Derived > internal::traits< Derived >::Scalar Eigen::SparseMatrixBase< Derived >::sum () const
References eigen_assert.
template<typename Derived> template<typename NType > EIGEN_DEVICE_FUNC FixedSegmentReturnType<internal::get_fixed_value<NType>::value>::Type Eigen::SparseMatrixBase< Derived >::tail (NType n) inline
Returns
an expression of a last coefficients of *this with either dynamic or fixed sizes.
Parameters
n the number of coefficients in the segment
Template Parameters
NType the type of the value handling the number of coefficients in the segment, typically Index.
Example:
Output:
The number of coefficients n can also be specified at compile-time by passing Eigen::fix<N>, or Eigen::fix<N>(n) as arguments. See block() for the details.
Note
Even in the case that the returned expression has dynamic size, in the case when it is applied to a fixed-size vector, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See also
class Block, block(Index,Index)
template<typename Derived> template<typename NType > EIGEN_DEVICE_FUNC const ConstFixedSegmentReturnType<internal::get_fixed_value<NType>::value>::Type Eigen::SparseMatrixBase< Derived >::tail (NType n) const inline
This is the const version of tail(Index).
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC FixedSegmentReturnType<N>::Type Eigen::SparseMatrixBase< Derived >::tail (Index n = N) inline
Returns
a fixed-size expression of the last coefficients of *this.
Template Parameters
N the number of coefficients in the segment as specified at compile-time
Parameters
n the number of coefficients in the segment as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
tail(NType), class Block
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType<N>::Type Eigen::SparseMatrixBase< Derived >::tail (Index n = N) const inline
This is the const version of tail<int>.
template<typename Derived> DenseMatrixType Eigen::SparseMatrixBase< Derived >::toDense () const inline
Referenced by Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::isApprox().
template<typename Derived> template<typename NRowsType , typename NColsType > EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<internal::get_fixed_value<NRowsType>::value,internal::get_fixed_value<NColsType>::value>::Type Eigen::SparseMatrixBase< Derived >::topLeftCorner (NRowsType cRows, NColsType cCols) inline
Returns
an expression of a top-left corner of *this with either dynamic or fixed sizes.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Template Parameters
NRowsType the type of the value handling the number of rows in the block, typically Index.
NColsType the type of the value handling the number of columns in the block, typically Index.
Example:
Output:
The number of rows blockRows and columns blockCols can also be specified at compile-time by passing Eigen::fix<N>, or Eigen::fix<N>(n) as arguments. See block() for the details.
See also
block(Index,Index,NRowsType,NColsType), class Block
template<typename Derived> template<typename NRowsType , typename NColsType > EIGEN_DEVICE_FUNC const ConstFixedBlockXpr<internal::get_fixed_value<NRowsType>::value,internal::get_fixed_value<NColsType>::value>::Type Eigen::SparseMatrixBase< Derived >::topLeftCorner (NRowsType cRows, NColsType cCols) const inline
This is the const version of topLeftCorner(Index, Index).
template<typename Derived> template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<CRows,CCols>::Type Eigen::SparseMatrixBase< Derived >::topLeftCorner () inline
Returns
an expression of a fixed-size top-left corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Output:
See also
block(Index,Index,NRowsType,NColsType), class Block
template<typename Derived> template<int CRows, int CCols> EIGEN_DEVICE_FUNC const ConstFixedBlockXpr<CRows,CCols>::Type Eigen::SparseMatrixBase< Derived >::topLeftCorner () const inline
This is the const version of topLeftCorner<int, int>().
template<typename Derived> template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr<CRows,CCols>::Type Eigen::SparseMatrixBase< Derived >::topLeftCorner (Index cRows, Index cCols) inline
Returns
an expression of a top-left corner of *this.
Template Parameters
CRows number of rows in corner as specified at compile-time
CCols number of columns in corner as specified at compile-time
Parameters
cRows number of rows in corner as specified at run-time
cCols number of columns in corner as specified at run-time
This function is mainly useful for corners where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, cRows should equal CRows unless CRows is Dynamic, and the same for the number of columns.
Example:
Output:
See also
class Block
template<typename Derived> template<int CRows, int CCols> const ConstFixedBlockXpr<CRows,CCols>::Type Eigen::SparseMatrixBase< Derived >::topLeftCorner (Index cRows, Index cCols) const inline
This is the const version of topLeftCorner<int, int>(Index, Index).
template<typename Derived> template<typename NRowsType , typename NColsType > EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<internal::get_fixed_value<NRowsType>::value,internal::get_fixed_value<NColsType>::value>::Type Eigen::SparseMatrixBase< Derived >::topRightCorner (NRowsType cRows, NColsType cCols) inline
Returns
a expression of a top-right corner of *this with either dynamic or fixed sizes.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Template Parameters
NRowsType the type of the value handling the number of rows in the block, typically Index.
NColsType the type of the value handling the number of columns in the block, typically Index.
Example with dynamic sizes:
Output:
The number of rows blockRows and columns blockCols can also be specified at compile-time by passing Eigen::fix<N>, or Eigen::fix<N>(n) as arguments. See block() for the details.
See also
block(Index,Index,NRowsType,NColsType), class Block
template<typename Derived> template<typename NRowsType , typename NColsType > EIGEN_DEVICE_FUNC const ConstFixedBlockXpr<internal::get_fixed_value<NRowsType>::value,internal::get_fixed_value<NColsType>::value>::Type Eigen::SparseMatrixBase< Derived >::topRightCorner (NRowsType cRows, NColsType cCols) const inline
This is the const version of topRightCorner(NRowsType, NColsType).
template<typename Derived> template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<CRows,CCols>::Type Eigen::SparseMatrixBase< Derived >::topRightCorner () inline
Returns
an expression of a fixed-size top-right corner of *this.
Template Parameters
CRows the number of rows in the corner
CCols the number of columns in the corner
Example:
Output:
See also
class Block, block<int,int>(Index,Index)
template<typename Derived> template<int CRows, int CCols> EIGEN_DEVICE_FUNC const ConstFixedBlockXpr<CRows,CCols>::Type Eigen::SparseMatrixBase< Derived >::topRightCorner () const inline
This is the const version of topRightCorner<int, int>().
template<typename Derived> template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr<CRows,CCols>::Type Eigen::SparseMatrixBase< Derived >::topRightCorner (Index cRows, Index cCols) inline
Returns
an expression of a top-right corner of *this.
Template Parameters
CRows number of rows in corner as specified at compile-time
CCols number of columns in corner as specified at compile-time
Parameters
cRows number of rows in corner as specified at run-time
cCols number of columns in corner as specified at run-time
This function is mainly useful for corners where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, cRows should equal CRows unless CRows is Dynamic, and the same for the number of columns.
Example:
Output:
See also
class Block
template<typename Derived> template<int CRows, int CCols> const ConstFixedBlockXpr<CRows,CCols>::Type Eigen::SparseMatrixBase< Derived >::topRightCorner (Index cRows, Index cCols) const inline
This is the const version of topRightCorner<int, int>(Index, Index).
template<typename Derived> template<typename NRowsType > EIGEN_DEVICE_FUNC NRowsBlockXpr<internal::get_fixed_value<NRowsType>::value>::Type Eigen::SparseMatrixBase< Derived >::topRows (NRowsType n) inline
Returns
a block consisting of the top rows of *this.
Parameters
n the number of rows in the block
Template Parameters
NRowsType the type of the value handling the number of rows in the block, typically Index.
Example:
Output:
The number of rows n can also be specified at compile-time by passing Eigen::fix<N>, or Eigen::fix<N>(n) as arguments. See block() for the details.
See also
block(Index,Index,NRowsType,NColsType), class Block
template<typename Derived> template<typename NRowsType > EIGEN_DEVICE_FUNC const ConstNRowsBlockXpr<internal::get_fixed_value<NRowsType>::value>::Type Eigen::SparseMatrixBase< Derived >::topRows (NRowsType n) const inline
This is the const version of topRows(NRowsType).
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC NRowsBlockXpr<N>::Type Eigen::SparseMatrixBase< Derived >::topRows (Index n = N) inline
Returns
a block consisting of the top rows of *this.
Template Parameters
N the number of rows in the block as specified at compile-time
Parameters
n the number of rows in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
block(Index,Index,NRowsType,NColsType), class Block
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC ConstNRowsBlockXpr<N>::Type Eigen::SparseMatrixBase< Derived >::topRows (Index n = N) const inline
This is the const version of topRows<int>().
template<typename Derived> TransposeReturnType Eigen::SparseMatrixBase< Derived >::transpose () inline
Referenced by Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::adjoint(), Eigen::IncompleteLUT< _Scalar, _StorageIndex >::analyzePattern(), and Eigen::PastixLU< _MatrixType, IsStrSym >::grabMatrix().
template<typename Derived> const ConstTransposeReturnType Eigen::SparseMatrixBase< Derived >::transpose () const inline
template<typename Derived > template<int Mode> const TriangularView< const Derived, Mode > Eigen::SparseMatrixBase< Derived >::triangularView () const inline
Referenced by Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::twistedBy().
template<typename Derived> SparseSymmetricPermutationProduct<Derived,Upper|Lower> Eigen::SparseMatrixBase< Derived >::twistedBy (const PermutationMatrix< Dynamic, Dynamic, StorageIndex > & perm) const inline
Returns
an expression of P H P^-1 where H is the matrix represented by *this
Referenced by Eigen::SimplicialCholeskyBase< SimplicialLDLT< _MatrixType, _UpLo, _Ordering > >::factorize(), Eigen::IncompleteLUT< _Scalar, _StorageIndex >::factorize(), and Eigen::SimplicialCholeskyBase< Derived >::ordering().
template<typename Derived> template<typename CustomUnaryOp > EIGEN_DEVICE_FUNC const CwiseUnaryOp<CustomUnaryOp, const Derived> Eigen::SparseMatrixBase< Derived >::unaryExpr (const CustomUnaryOp & func = CustomUnaryOp()) const inline
Apply a unary operator coefficient-wise.
Parameters
[in] func Functor implementing the unary operator
Template Parameters
CustomUnaryOp Type of func
Returns
An expression of a custom coefficient-wise unary operator func of *this
The function ptr_fun() from the C++ standard library can be used to make functors out of normal functions.
Example:
Output:
Genuine functors allow for more possibilities, for instance it may contain a state.
Example:
Output:
See also
unaryViewExpr, binaryExpr, class CwiseUnaryOp
template<typename Derived> template<typename CustomViewOp > EIGEN_DEVICE_FUNC const CwiseUnaryView<CustomViewOp, const Derived> Eigen::SparseMatrixBase< Derived >::unaryViewExpr (const CustomViewOp & func = CustomViewOp()) const inline
Returns
an expression of a custom coefficient-wise unary operator func of *this
The template parameter CustomUnaryOp is the type of the functor of the custom unary operator.
Example:
Output:
See also
unaryExpr, binaryExpr class CwiseUnaryOp
Friends And Related Function Documentation
template<typename Derived> template<typename OtherDerived > const Product<OtherDerived,Derived> operator* (const DiagonalBase< OtherDerived > & lhs, const SparseMatrixBase< Derived > & rhs) friend
template<typename Derived> template<typename OtherDerived > const Product<OtherDerived,Derived> operator* (const MatrixBase< OtherDerived > & lhs, const SparseMatrixBase< Derived > & rhs) friend
template<typename Derived> std::ostream& operator<< (std::ostream & s, const SparseMatrixBase< Derived > & m) friend
Member Data Documentation
template<typename Derived> bool Eigen::SparseMatrixBase< Derived >::m_isRValue protected
Referenced by Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::isRValue(), and Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::markAsRValue().
The documentation for this class was generated from the following files:
ForwardDeclarations.h
SparseMatrixBase.h
SparseAssign.h
SparseBlock.h
SparseCwiseBinaryOp.h
SparseCwiseUnaryOp.h
SparseDot.h
SparseFuzzy.h
SparseProduct.h
SparseRedux.h
SparseSelfAdjointView.h
SparseTriangularView.h
SparseView.h