SmartMouse_2018: Eigen::internal::FixedInt< N > Class Template Reference
Eigen::internal::FixedInt< N > Class Template Reference
#include <IntegralConstant.h>
Public Member Functions
operator int () const
FixedInt ()
FixedInt (VariableAndFixedInt< N > other)
FixedInt<-N > operator- () const
template<int M>
FixedInt< N+M > operator+ (FixedInt< M >) const
template<int M>
FixedInt< N-M > operator- (FixedInt< M >) const
template<int M>
FixedInt< N *M > operator* (FixedInt< M >) const
template<int M>
FixedInt< N/M > operator/ (FixedInt< M >) const
template<int M>
FixedInt< N%M > operator% (FixedInt< M >) const
template<int M>
FixedInt< N|M > operator| (FixedInt< M >) const
template<int M>
FixedInt< N &M > operator& (FixedInt< M >) const
FixedInt (FixedInt< N >(*)())
Static Public Attributes
static const int value = N
Constructor & Destructor Documentation
template<int N> Eigen::internal::FixedInt< N >::FixedInt () inline
Referenced by Eigen::internal::FixedInt< N >::FixedInt().
template<int N> Eigen::internal::FixedInt< N >::FixedInt (VariableAndFixedInt< N > other) inline
References eigen_internal_assert, EIGEN_ONLY_USED_FOR_DEBUG, and N.
template<int N> Eigen::internal::FixedInt< N >::FixedInt (FixedInt< N > *)() inline
References Eigen::internal::FixedInt< N >::FixedInt().
Member Function Documentation
template<int N> Eigen::internal::FixedInt< N >::operator int () const inline
References Eigen::internal::FixedInt< N >::value.
template<int N> template<int M> FixedInt<N%M> Eigen::internal::FixedInt< N >::operator% (FixedInt< M >) const inline
template<int N> template<int M> FixedInt<N&M> Eigen::internal::FixedInt< N >::operator& (FixedInt< M >) const inline
References operator()().
template<int N> template<int M> FixedInt<N*M> Eigen::internal::FixedInt< N >::operator* (FixedInt< M >) const inline
template<int N> template<int M> FixedInt<N+M> Eigen::internal::FixedInt< N >::operator+ (FixedInt< M >) const inline
template<int N> FixedInt<-N> Eigen::internal::FixedInt< N >::operator- () const inline
References N.
template<int N> template<int M> FixedInt<N-M> Eigen::internal::FixedInt< N >::operator- (FixedInt< M >) const inline
References N.
template<int N> template<int M> FixedInt<N/M> Eigen::internal::FixedInt< N >::operator/ (FixedInt< M >) const inline
References N.
template<int N> template<int M> FixedInt<N|M> Eigen::internal::FixedInt< N >::operator| (FixedInt< M >) const inline
Member Data Documentation
template<int N> const int Eigen::internal::FixedInt< N >::value = N static
Referenced by Eigen::internal::FixedInt< N >::operator int().
The documentation for this class was generated from the following file:
IntegralConstant.h