SmartMouse_2018: Server Class Reference
Server Class Reference
#include <Server.h>
Public Member Functions
Server ()
void Connect ()
void Start ()
void RunLoop ()
bool Run ()
void Step ()
void Join ()
bool IsConnected ()
unsigned int getNsOfSimPerStep () const
Public Attributes
std::thread * thread_
Private Member Functions
void OnServerControl (const smartmouse::msgs::ServerControl &msg)
void OnPhysics (const smartmouse::msgs::PhysicsConfig &msg)
void OnMaze (const smartmouse::msgs::Maze &msg)
void OnRobotCommand (const smartmouse::msgs::RobotCommand &msg)
void OnRobotDescription (const smartmouse::msgs::RobotDescription &msg)
void UpdateRobotState (double dt)
void ResetRobot (double reset_col, double reset_row, double reset_yaw)
void ResetTime ()
void PublishInternalState ()
void PublishWorldStats (double rtf)
void ComputeMaxSensorRange ()
const double ComputeSensorRange (const smartmouse::msgs::SensorDescription sensor)
double ComputeSensorDistToWall (smartmouse::msgs::SensorDescription sensor)
Private Attributes
ignition::transport::Node * node_ptr_
ignition::transport::Node::Publisher world_stats_pub_
ignition::transport::Node::Publisher sim_state_pub_
Time sim_time_
unsigned long steps_ = 0UL
std::mutex physics_mutex_
bool pause_ = true
bool static_
bool quit_ = false
bool connected_ = false
unsigned int ns_of_sim_per_step_ = 1000000u
unsigned long pause_at_steps_ = 0ul
double real_time_factor_ = 1.0
smartmouse::msgs::maze_walls_t maze_walls_
smartmouse::msgs::RobotCommand cmd_
smartmouse::msgs::RobotDescription mouse_
smartmouse::msgs::RobotSimState robot_state_
bool mouse_set_
unsigned int max_cells_to_check_
Constructor & Destructor Documentation
Server::Server ()
References ResetRobot().
Member Function Documentation
void Server::ComputeMaxSensorRange () private
References ComputeSensorRange(), max_cells_to_check_, mouse_, and smartmouse::maze::toCellUnits().
Referenced by OnRobotDescription().
double Server::ComputeSensorDistToWall (smartmouse::msgs::SensorDescription sensor) private
References smartmouse::kc::ANALOG_MAX_DIST_CU, smartmouse::kc::ANALOG_MIN_DIST_CU, RayTracing::distance_to_wall(), max_cells_to_check_, maze_walls_, range, robot_state_, smartmouse::maze::SIZE, smartmouse::maze::toCellUnits(), and smartmouse::maze::toMeters().
Referenced by UpdateRobotState().
const double Server::ComputeSensorRange (const smartmouse::msgs::SensorDescription sensor) private
References smartmouse::kc::ANALOG_MAX_DIST_M.
Referenced by ComputeMaxSensorRange().
void Server::Connect ()
References connected_, TopicNames::kMaze, TopicNames::kPhysics, TopicNames::kRobotCommand, TopicNames::kRobotDescription, TopicNames::kRobotSimState, TopicNames::kServerControl, TopicNames::kWorldStatistics, node_ptr_, OnMaze(), OnPhysics(), OnRobotCommand(), OnRobotDescription(), OnServerControl(), sim_state_pub_, and world_stats_pub_.
Referenced by RunLoop(), and TEST().
unsigned int Server::getNsOfSimPerStep () const
References ns_of_sim_per_step_.
bool Server::IsConnected ()
References connected_.
void Server::Join ()
References thread_.
Referenced by main().
void Server::OnMaze (const smartmouse::msgs::Maze & msg) private
References smartmouse::msgs::Convert(), maze_walls_, and physics_mutex_.
Referenced by Connect().
void Server::OnPhysics (const smartmouse::msgs::PhysicsConfig & msg) private
References e, ns_of_sim_per_step_, physics_mutex_, and real_time_factor_.
Referenced by Connect().
void Server::OnRobotCommand (const smartmouse::msgs::RobotCommand & msg) private
References cmd_, and physics_mutex_.
Referenced by Connect().
void Server::OnRobotDescription (const smartmouse::msgs::RobotDescription & msg) private
References ComputeMaxSensorRange(), mouse_, mouse_set_, and physics_mutex_.
Referenced by Connect().
void Server::OnServerControl (const smartmouse::msgs::ServerControl & msg) private
References pause_, pause_at_steps_, physics_mutex_, quit_, ResetRobot(), ResetTime(), static_, and steps_.
Referenced by Connect().
void Server::PublishInternalState () private
References robot_state_, and sim_state_pub_.
Referenced by ResetRobot(), ResetTime(), and Run().
void Server::PublishWorldStats (double rtf) private
References sim_time_, steps_, Time::toIgnMsg(), and world_stats_pub_.
Referenced by ResetTime(), and Run().
void Server::ResetRobot (double reset_col, double reset_row, double reset_yaw) private
References cmd_, PublishInternalState(), and robot_state_.
Referenced by OnServerControl(), and Server().
void Server::ResetTime () private
References pause_at_steps_, PublishInternalState(), PublishWorldStats(), sim_time_, steps_, and Time::Zero.
Referenced by OnServerControl().
bool Server::Run ()
References Time::Double(), e, Time::GetWallTime(), Time::MSleep(), ns_of_sim_per_step_, pause_, pause_at_steps_, physics_mutex_, PublishInternalState(), PublishWorldStats(), quit_, real_time_factor_, Time::Sleep(), Step(), and steps_.
Referenced by RunLoop().
void Server::RunLoop ()
References Connect(), done, and Run().
Referenced by Start().
void Server::Start ()
References RunLoop(), and thread_.
Referenced by main(), and TEST().
void Server::Step ()
References mouse_set_, ns_of_sim_per_step_, sim_time_, steps_, and UpdateRobotState().
Referenced by Run().
void Server::UpdateRobotState (double dt) private
References cmd_, GlobalPose::col, ComputeSensorDistToWall(), KinematicController::forwardKinematics(), mouse_, smartmouse::kc::radToMeters(), robot_state_, GlobalPose::row, sim_time_, static_, smartmouse::maze::toCellUnits(), Time::toIgnMsg(), smartmouse::math::wrapAngleRadInPlace(), GlobalPose::yaw, and smartmouse::math::yaw_diff().
Referenced by Step().
Member Data Documentation
smartmouse::msgs::RobotCommand Server::cmd_ private
Referenced by OnRobotCommand(), ResetRobot(), and UpdateRobotState().
bool Server::connected_ = false private
Referenced by Connect(), and IsConnected().
unsigned int Server::max_cells_to_check_ private
Referenced by ComputeMaxSensorRange(), and ComputeSensorDistToWall().
smartmouse::msgs::maze_walls_t Server::maze_walls_ private
Referenced by ComputeSensorDistToWall(), and OnMaze().
smartmouse::msgs::RobotDescription Server::mouse_ private
Referenced by ComputeMaxSensorRange(), OnRobotDescription(), and UpdateRobotState().
bool Server::mouse_set_ private
Referenced by OnRobotDescription(), and Step().
ignition::transport::Node* Server::node_ptr_ private
Referenced by Connect().
unsigned int Server::ns_of_sim_per_step_ = 1000000u private
Referenced by getNsOfSimPerStep(), OnPhysics(), Run(), and Step().
bool Server::pause_ = true private
Referenced by OnServerControl(), and Run().
unsigned long Server::pause_at_steps_ = 0ul private
Referenced by OnServerControl(), ResetTime(), and Run().
std::mutex Server::physics_mutex_ private
Referenced by OnMaze(), OnPhysics(), OnRobotCommand(), OnRobotDescription(), OnServerControl(), and Run().
bool Server::quit_ = false private
Referenced by OnServerControl(), and Run().
double Server::real_time_factor_ = 1.0 private
Referenced by OnPhysics(), and Run().
smartmouse::msgs::RobotSimState Server::robot_state_ private
Referenced by ComputeSensorDistToWall(), PublishInternalState(), ResetRobot(), and UpdateRobotState().
ignition::transport::Node::Publisher Server::sim_state_pub_ private
Referenced by Connect(), and PublishInternalState().
Time Server::sim_time_ private
Referenced by PublishWorldStats(), ResetTime(), Step(), and UpdateRobotState().
bool Server::static_ private
Referenced by OnServerControl(), and UpdateRobotState().
unsigned long Server::steps_ = 0UL private
Referenced by OnServerControl(), PublishWorldStats(), ResetTime(), Run(), and Step().
std::thread* Server::thread_
Referenced by Join(), and Start().
ignition::transport::Node::Publisher Server::world_stats_pub_ private
Referenced by Connect(), and PublishWorldStats().
The documentation for this class was generated from the following files:
Server.h
Server.cpp