SmartMouse_2018: LEDBlink Class Reference
LEDBlink Class Reference
#include <LEDBlink.h>
Public Member Functions
LEDBlink (const uint8_t led_pin, unsigned long blink_time)
void initialize ()
run once in the first iteration of the command's life. this will be overrided by individual commands
void execute ()
stuff to do over and over each iteration. this will be overrided by individual commands
bool isFinished ()
checked every iteration to see if we're done here. this will be overrided by individual commands
void end ()
called once at the end, once isFinished() returned true. this will be overrided by individual commands.
Public Member Functions inherited from Command
Command ()
Command (const char *name)
virtual ~Command ()
void setTimeout (unsigned long timeout)
unsigned long getTime ()
bool isTimedOut ()
virtual void _initialize ()
virtual void _execute ()
virtual void _end ()
bool cycle ()
actually does the excuting.
bool isRunning ()
check if the command is running.
bool operator!= (const Command &other)
comparator overload for !=. used when checking if command is in list
Private Attributes
const uint8_t led_pin
bool off
unsigned long blink_time
Additional Inherited Members
Static Public Member Functions inherited from Command
static void setTimerImplementation (TimerInterface *timer)
static TimerInterface * getTimerImplementation ()
Public Attributes inherited from Command
bool inParallel
used by command group to organize commands
const char * name
for convenient printing
bool initialized
bool running
unsigned long timeout
unsigned long startTime
Static Public Attributes inherited from Command
static TimerInterface * timer
Constructor & Destructor Documentation
LEDBlink::LEDBlink (const uint8_t led_pin, unsigned long blink_time)
Member Function Documentation
void LEDBlink::end () virtual
called once at the end, once isFinished() returned true. this will be overrided by individual commands.
Reimplemented from Command.
void LEDBlink::execute () virtual
stuff to do over and over each iteration. this will be overrided by individual commands
Reimplemented from Command.
References blink_time, Command::getTime(), led_pin, and off.
void LEDBlink::initialize () virtual
run once in the first iteration of the command's life. this will be overrided by individual commands
Reimplemented from Command.
References blink_time, led_pin, and Command::setTimeout().
bool LEDBlink::isFinished () virtual
checked every iteration to see if we're done here. this will be overrided by individual commands
Returns
is the function finished
Implements Command.
References Command::isTimedOut().
Member Data Documentation
unsigned long LEDBlink::blink_time private
Referenced by execute(), and initialize().
const uint8_t LEDBlink::led_pin private
Referenced by execute(), and initialize().
bool LEDBlink::off private
Referenced by execute().
The documentation for this class was generated from the following files:
LEDBlink.h
LEDBlink.cpp