SmartMouse_2018: Eigen::internal::UpperBidiagonalization< _MatrixType > Class Template Reference
Eigen::internal::UpperBidiagonalization< _MatrixType > Class Template Reference
#include <UpperBidiagonalization.h>
Public Types
enum { RowsAtCompileTime = MatrixType::RowsAtCompileTime, ColsAtCompileTime = MatrixType::ColsAtCompileTime, ColsAtCompileTimeMinusOne = internal::decrement_size<ColsAtCompileTime>::ret }
typedef _MatrixType MatrixType
typedef MatrixType::Scalar Scalar
typedef MatrixType::RealScalar RealScalar
typedef Eigen::Index Index
typedef Matrix< Scalar, 1, ColsAtCompileTime > RowVectorType
typedef Matrix< Scalar, RowsAtCompileTime, 1 > ColVectorType
typedef BandMatrix< RealScalar, ColsAtCompileTime, ColsAtCompileTime, 1, 0, RowMajor > BidiagonalType
typedef Matrix< Scalar, ColsAtCompileTime, 1 > DiagVectorType
typedef Matrix< Scalar, ColsAtCompileTimeMinusOne, 1 > SuperDiagVectorType
typedef HouseholderSequence< const MatrixType, const typename internal::remove_all< typename Diagonal< const MatrixType, 0 >::ConjugateReturnType >::type > HouseholderUSequenceType
typedef HouseholderSequence< const typename internal::remove_all< typename MatrixType::ConjugateReturnType >::type, Diagonal< const MatrixType, 1 >, OnTheRight > HouseholderVSequenceType
Public Member Functions
UpperBidiagonalization ()
Default Constructor.
UpperBidiagonalization (const MatrixType &matrix)
UpperBidiagonalization & compute (const MatrixType &matrix)
UpperBidiagonalization & computeUnblocked (const MatrixType &matrix)
const MatrixType & householder () const
const BidiagonalType & bidiagonal () const
const HouseholderUSequenceType householderU () const
const HouseholderVSequenceType householderV ()
Protected Attributes
MatrixType m_householder
BidiagonalType m_bidiagonal
bool m_isInitialized
Member Typedef Documentation
template<typename _MatrixType> typedef BandMatrix<RealScalar, ColsAtCompileTime, ColsAtCompileTime, 1, 0, RowMajor> Eigen::internal::UpperBidiagonalization< _MatrixType >::BidiagonalType
template<typename _MatrixType> typedef Matrix<Scalar, RowsAtCompileTime, 1> Eigen::internal::UpperBidiagonalization< _MatrixType >::ColVectorType
template<typename _MatrixType> typedef Matrix<Scalar, ColsAtCompileTime, 1> Eigen::internal::UpperBidiagonalization< _MatrixType >::DiagVectorType
template<typename _MatrixType> typedef HouseholderSequence< const MatrixType, const typename internal::remove_all<typename Diagonal<const MatrixType,0>::ConjugateReturnType>::type > Eigen::internal::UpperBidiagonalization< _MatrixType >::HouseholderUSequenceType
template<typename _MatrixType> typedef HouseholderSequence< const typename internal::remove_all<typename MatrixType::ConjugateReturnType>::type, Diagonal<const MatrixType,1>, OnTheRight > Eigen::internal::UpperBidiagonalization< _MatrixType >::HouseholderVSequenceType
template<typename _MatrixType> typedef Eigen::Index Eigen::internal::UpperBidiagonalization< _MatrixType >::Index
Deprecated:
since Eigen 3.3
template<typename _MatrixType> typedef _MatrixType Eigen::internal::UpperBidiagonalization< _MatrixType >::MatrixType
template<typename _MatrixType> typedef MatrixType::RealScalar Eigen::internal::UpperBidiagonalization< _MatrixType >::RealScalar
template<typename _MatrixType> typedef Matrix<Scalar, 1, ColsAtCompileTime> Eigen::internal::UpperBidiagonalization< _MatrixType >::RowVectorType
template<typename _MatrixType> typedef MatrixType::Scalar Eigen::internal::UpperBidiagonalization< _MatrixType >::Scalar
template<typename _MatrixType> typedef Matrix<Scalar, ColsAtCompileTimeMinusOne, 1> Eigen::internal::UpperBidiagonalization< _MatrixType >::SuperDiagVectorType
Member Enumeration Documentation
template<typename _MatrixType> anonymous enum
Enumerator
RowsAtCompileTime
ColsAtCompileTime
ColsAtCompileTimeMinusOne
Constructor & Destructor Documentation
template<typename _MatrixType> Eigen::internal::UpperBidiagonalization< _MatrixType >::UpperBidiagonalization () inline
Default Constructor.
The default constructor is useful in cases in which the user intends to perform decompositions via Bidiagonalization::compute(const MatrixType&).
template<typename _MatrixType> Eigen::internal::UpperBidiagonalization< _MatrixType >::UpperBidiagonalization (const MatrixType & matrix) inline explicit
References Eigen::internal::UpperBidiagonalization< _MatrixType >::compute(), and Eigen::internal::UpperBidiagonalization< _MatrixType >::computeUnblocked().
Member Function Documentation
template<typename _MatrixType> const BidiagonalType& Eigen::internal::UpperBidiagonalization< _MatrixType >::bidiagonal () const inline
References Eigen::internal::UpperBidiagonalization< _MatrixType >::m_bidiagonal.
Referenced by Eigen::BDCSVD< _MatrixType >::compute().
template<typename _MatrixType > UpperBidiagonalization< _MatrixType > & Eigen::internal::UpperBidiagonalization< _MatrixType >::compute (const MatrixType & matrix)
References eigen_assert, EIGEN_ONLY_USED_FOR_DEBUG, Eigen::internal::UpperBidiagonalization< _MatrixType >::m_bidiagonal, Eigen::internal::UpperBidiagonalization< _MatrixType >::m_householder, Eigen::internal::UpperBidiagonalization< _MatrixType >::m_isInitialized, and Eigen::internal::upperbidiagonalization_inplace_blocked().
Referenced by Eigen::internal::UpperBidiagonalization< _MatrixType >::UpperBidiagonalization().
template<typename _MatrixType > UpperBidiagonalization< _MatrixType > & Eigen::internal::UpperBidiagonalization< _MatrixType >::computeUnblocked (const MatrixType & matrix)
References Eigen::PlainObjectBase< Derived >::data(), eigen_assert, EIGEN_ONLY_USED_FOR_DEBUG, Eigen::internal::UpperBidiagonalization< _MatrixType >::m_bidiagonal, Eigen::internal::UpperBidiagonalization< _MatrixType >::m_householder, Eigen::internal::UpperBidiagonalization< _MatrixType >::m_isInitialized, and Eigen::internal::upperbidiagonalization_inplace_unblocked().
Referenced by Eigen::internal::UpperBidiagonalization< _MatrixType >::UpperBidiagonalization().
template<typename _MatrixType> const MatrixType& Eigen::internal::UpperBidiagonalization< _MatrixType >::householder () const inline
References Eigen::internal::UpperBidiagonalization< _MatrixType >::m_householder.
template<typename _MatrixType> const HouseholderUSequenceType Eigen::internal::UpperBidiagonalization< _MatrixType >::householderU () const inline
References eigen_assert, Eigen::internal::UpperBidiagonalization< _MatrixType >::m_householder, and Eigen::internal::UpperBidiagonalization< _MatrixType >::m_isInitialized.
Referenced by Eigen::BDCSVD< _MatrixType >::compute().
template<typename _MatrixType> const HouseholderVSequenceType Eigen::internal::UpperBidiagonalization< _MatrixType >::householderV () inline
References eigen_assert, Eigen::internal::UpperBidiagonalization< _MatrixType >::m_householder, and Eigen::internal::UpperBidiagonalization< _MatrixType >::m_isInitialized.
Referenced by Eigen::BDCSVD< _MatrixType >::compute().
Member Data Documentation
template<typename _MatrixType> BidiagonalType Eigen::internal::UpperBidiagonalization< _MatrixType >::m_bidiagonal protected
Referenced by Eigen::internal::UpperBidiagonalization< _MatrixType >::bidiagonal(), Eigen::internal::UpperBidiagonalization< _MatrixType >::compute(), and Eigen::internal::UpperBidiagonalization< _MatrixType >::computeUnblocked().
template<typename _MatrixType> MatrixType Eigen::internal::UpperBidiagonalization< _MatrixType >::m_householder protected
Referenced by Eigen::internal::UpperBidiagonalization< _MatrixType >::compute(), Eigen::internal::UpperBidiagonalization< _MatrixType >::computeUnblocked(), Eigen::internal::UpperBidiagonalization< _MatrixType >::householder(), Eigen::internal::UpperBidiagonalization< _MatrixType >::householderU(), and Eigen::internal::UpperBidiagonalization< _MatrixType >::householderV().
template<typename _MatrixType> bool Eigen::internal::UpperBidiagonalization< _MatrixType >::m_isInitialized protected
Referenced by Eigen::internal::UpperBidiagonalization< _MatrixType >::compute(), Eigen::internal::UpperBidiagonalization< _MatrixType >::computeUnblocked(), Eigen::internal::UpperBidiagonalization< _MatrixType >::householderU(), and Eigen::internal::UpperBidiagonalization< _MatrixType >::householderV().
The documentation for this class was generated from the following file:
UpperBidiagonalization.h