SmartMouse_2018: Eigen::TriangularBase< Derived > Class Template Reference
Eigen::TriangularBase< Derived > Class Template Reference
Base class for triangular part in a matrix.
#include <TriangularMatrix.h>
Public Types
enum {
Mode = internal::traits<Derived>::Mode, RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime, ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime, MaxRowsAtCompileTime = internal::traits<Derived>::MaxRowsAtCompileTime,
MaxColsAtCompileTime = internal::traits<Derived>::MaxColsAtCompileTime, SizeAtCompileTime, MaxSizeAtCompileTime
}
typedef internal::traits< Derived >::Scalar Scalar
typedef internal::traits< Derived >::StorageKind StorageKind
typedef internal::traits< Derived >::StorageIndex StorageIndex
typedef internal::traits< Derived >::FullMatrixType DenseMatrixType
typedef DenseMatrixType DenseType
typedef Derived const & Nested
Public Types inherited from Eigen::EigenBase< Derived >
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< Derived >::StorageKind StorageKind
Public Member Functions
EIGEN_DEVICE_FUNC TriangularBase ()
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
EIGEN_DEVICE_FUNC Index outerStride () const
EIGEN_DEVICE_FUNC Index innerStride () const
void resize (Index rows, Index cols)
EIGEN_DEVICE_FUNC Scalar coeff (Index row, Index col) const
EIGEN_DEVICE_FUNC Scalar & coeffRef (Index row, Index col)
template<typename Other >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void copyCoeff (Index row, Index col, Other &other)
EIGEN_DEVICE_FUNC Scalar operator() (Index row, Index col) const
EIGEN_DEVICE_FUNC Scalar & operator() (Index row, Index col)
EIGEN_DEVICE_FUNC const Derived & derived () const
EIGEN_DEVICE_FUNC Derived & derived ()
template<typename DenseDerived >
EIGEN_DEVICE_FUNC void evalTo (MatrixBase< DenseDerived > &other) const
template<typename DenseDerived >
EIGEN_DEVICE_FUNC void evalToLazy (MatrixBase< DenseDerived > &other) const
EIGEN_DEVICE_FUNC DenseMatrixType toDenseMatrix () const
Public Member Functions inherited from Eigen::EigenBase< Derived >
EIGEN_DEVICE_FUNC Derived & derived ()
EIGEN_DEVICE_FUNC const Derived & derived () const
EIGEN_DEVICE_FUNC Derived & const_cast_derived () const
EIGEN_DEVICE_FUNC const Derived & const_derived () const
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
EIGEN_DEVICE_FUNC Index size () const
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
Protected Member Functions
void check_coordinates (Index row, Index col) const
void check_coordinates_internal (Index, Index) const
Detailed Description
template<typename Derived>
class Eigen::TriangularBase< Derived >
Base class for triangular part in a matrix.
Member Typedef Documentation
template<typename Derived> typedef internal::traits<Derived>::FullMatrixType Eigen::TriangularBase< Derived >::DenseMatrixType
template<typename Derived> typedef DenseMatrixType Eigen::TriangularBase< Derived >::DenseType
template<typename Derived> typedef Derived const& Eigen::TriangularBase< Derived >::Nested
template<typename Derived> typedef internal::traits<Derived>::Scalar Eigen::TriangularBase< Derived >::Scalar
template<typename Derived> typedef internal::traits<Derived>::StorageIndex Eigen::TriangularBase< Derived >::StorageIndex
template<typename Derived> typedef internal::traits<Derived>::StorageKind Eigen::TriangularBase< Derived >::StorageKind
Member Enumeration Documentation
template<typename Derived> anonymous enum
Enumerator
Mode
RowsAtCompileTime
ColsAtCompileTime
MaxRowsAtCompileTime
MaxColsAtCompileTime
SizeAtCompileTime
This is equal to the number of coefficients, i.e. the number of rows times the number of columns, or to Dynamic if this is not known at compile-time.
See also
RowsAtCompileTime, ColsAtCompileTime
MaxSizeAtCompileTime
Constructor & Destructor Documentation
template<typename Derived> EIGEN_DEVICE_FUNC Eigen::TriangularBase< Derived >::TriangularBase () inline
Member Function Documentation
template<typename Derived> void Eigen::TriangularBase< Derived >::check_coordinates (Index row, Index col) const inline protected
template<typename Derived> void Eigen::TriangularBase< Derived >::check_coordinates_internal (Index , Index) const inline protected
template<typename Derived> EIGEN_DEVICE_FUNC Scalar Eigen::TriangularBase< Derived >::coeff (Index row, Index col) const inline
template<typename Derived> EIGEN_DEVICE_FUNC Scalar& Eigen::TriangularBase< Derived >::coeffRef (Index row, Index col) inline
template<typename Derived> EIGEN_DEVICE_FUNC Index Eigen::TriangularBase< Derived >::cols (void) const inline
template<typename Derived> template<typename Other > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::TriangularBase< Derived >::copyCoeff (Index row, Index col, Other & other) inline
See also
MatrixBase::copyCoeff(row,col)
template<typename Derived> EIGEN_DEVICE_FUNC const Derived& Eigen::TriangularBase< Derived >::derived () const inline
Referenced by Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::_solve_impl().
template<typename Derived> EIGEN_DEVICE_FUNC Derived& Eigen::TriangularBase< Derived >::derived () inline
template<typename Derived > template<typename DenseDerived > EIGEN_DEVICE_FUNC void Eigen::TriangularBase< Derived >::evalTo (MatrixBase< DenseDerived > & other) const
Assigns a triangular or selfadjoint matrix to a dense matrix. If the matrix is triangular, the opposite part is set to zero.
template<typename Derived > template<typename DenseDerived > EIGEN_DEVICE_FUNC void Eigen::TriangularBase< Derived >::evalToLazy (MatrixBase< DenseDerived > & other) const
Assigns a triangular or selfadjoint matrix to a dense matrix. If the matrix is triangular, the opposite part is set to zero.
References Eigen::internal::call_triangular_assignment_loop(), Eigen::DenseBase< Derived >::resize(), and Eigen::SelfAdjoint.
template<typename Derived> EIGEN_DEVICE_FUNC Index Eigen::TriangularBase< Derived >::innerStride () const inline
template<typename Derived> EIGEN_DEVICE_FUNC Scalar Eigen::TriangularBase< Derived >::operator() (Index row, Index col) const inline
template<typename Derived> EIGEN_DEVICE_FUNC Scalar& Eigen::TriangularBase< Derived >::operator() (Index row, Index col) inline
template<typename Derived> EIGEN_DEVICE_FUNC Index Eigen::TriangularBase< Derived >::outerStride () const inline
template<typename Derived> void Eigen::TriangularBase< Derived >::resize (Index rows, Index cols) inline
template<typename Derived> EIGEN_DEVICE_FUNC Index Eigen::TriangularBase< Derived >::rows (void) const inline
template<typename Derived> EIGEN_DEVICE_FUNC DenseMatrixType Eigen::TriangularBase< Derived >::toDenseMatrix () const inline
The documentation for this class was generated from the following file:
TriangularMatrix.h