SmartMouse_2018: Eigen::NestByValue< ExpressionType > Class Template Reference
Eigen::NestByValue< ExpressionType > Class Template Reference
Expression which must be nested by value.
#include <NestByValue.h>
Public Types
typedef internal::dense_xpr_base< NestByValue >::type Base
Public Member Functions
EIGEN_DEVICE_FUNC NestByValue (const ExpressionType &matrix)
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
EIGEN_DEVICE_FUNC Index outerStride () const
EIGEN_DEVICE_FUNC Index innerStride () const
EIGEN_DEVICE_FUNC const CoeffReturnType coeff (Index row, Index col) const
EIGEN_DEVICE_FUNC Scalar & coeffRef (Index row, Index col)
EIGEN_DEVICE_FUNC const CoeffReturnType coeff (Index index) const
EIGEN_DEVICE_FUNC Scalar & coeffRef (Index index)
template<int LoadMode>
EIGEN_DEVICE_FUNC const PacketScalar packet (Index row, Index col) const
template<int LoadMode>
EIGEN_DEVICE_FUNC void writePacket (Index row, Index col, const PacketScalar &x)
template<int LoadMode>
EIGEN_DEVICE_FUNC const PacketScalar packet (Index index) const
template<int LoadMode>
EIGEN_DEVICE_FUNC void writePacket (Index index, const PacketScalar &x)
EIGEN_DEVICE_FUNC operator const ExpressionType & () const
Protected Attributes
const ExpressionType m_expression
Detailed Description
template<typename ExpressionType>
class Eigen::NestByValue< ExpressionType >
Expression which must be nested by value.
Template Parameters
ExpressionType the type of the object of which we are requiring nesting-by-value
This class is the return type of MatrixBase::nestByValue() and most of the time this is the only way it is used.
See also
MatrixBase::nestByValue()
Member Typedef Documentation
template<typename ExpressionType > typedef internal::dense_xpr_base<NestByValue>::type Eigen::NestByValue< ExpressionType >::Base
Constructor & Destructor Documentation
template<typename ExpressionType > EIGEN_DEVICE_FUNC Eigen::NestByValue< ExpressionType >::NestByValue (const ExpressionType & matrix) inline explicit
Member Function Documentation
template<typename ExpressionType > EIGEN_DEVICE_FUNC const CoeffReturnType Eigen::NestByValue< ExpressionType >::coeff (Index row, Index col) const inline
template<typename ExpressionType > EIGEN_DEVICE_FUNC const CoeffReturnType Eigen::NestByValue< ExpressionType >::coeff (Index index) const inline
template<typename ExpressionType > EIGEN_DEVICE_FUNC Scalar& Eigen::NestByValue< ExpressionType >::coeffRef (Index row, Index col) inline
template<typename ExpressionType > EIGEN_DEVICE_FUNC Scalar& Eigen::NestByValue< ExpressionType >::coeffRef (Index index) inline
template<typename ExpressionType > EIGEN_DEVICE_FUNC Index Eigen::NestByValue< ExpressionType >::cols (void) const inline
template<typename ExpressionType > EIGEN_DEVICE_FUNC Index Eigen::NestByValue< ExpressionType >::innerStride () const inline
template<typename ExpressionType > EIGEN_DEVICE_FUNC Eigen::NestByValue< ExpressionType >::operator const ExpressionType & () const inline
template<typename ExpressionType > EIGEN_DEVICE_FUNC Index Eigen::NestByValue< ExpressionType >::outerStride () const inline
template<typename ExpressionType > template<int LoadMode> EIGEN_DEVICE_FUNC const PacketScalar Eigen::NestByValue< ExpressionType >::packet (Index row, Index col) const inline
References col(), and row().
template<typename ExpressionType > template<int LoadMode> EIGEN_DEVICE_FUNC const PacketScalar Eigen::NestByValue< ExpressionType >::packet (Index index) const inline
template<typename ExpressionType > EIGEN_DEVICE_FUNC Index Eigen::NestByValue< ExpressionType >::rows (void) const inline
template<typename ExpressionType > template<int LoadMode> EIGEN_DEVICE_FUNC void Eigen::NestByValue< ExpressionType >::writePacket (Index row, Index col, const PacketScalar & x) inline
References col(), and row().
template<typename ExpressionType > template<int LoadMode> EIGEN_DEVICE_FUNC void Eigen::NestByValue< ExpressionType >::writePacket (Index index, const PacketScalar & x) inline
Member Data Documentation
template<typename ExpressionType > const ExpressionType Eigen::NestByValue< ExpressionType >::m_expression protected
The documentation for this class was generated from the following file:
NestByValue.h