SmartMouse_2018: Eigen::DenseStorage< T, Dynamic, Dynamic, _Cols, _Options > Class Template Reference
Eigen::DenseStorage< T, Dynamic, Dynamic, _Cols, _Options > Class Template Reference
#include <DenseStorage.h>
Public Member Functions
EIGEN_DEVICE_FUNC DenseStorage ()
DenseStorage (internal::constructor_without_unaligned_array_assert)
EIGEN_DEVICE_FUNC DenseStorage (Index size, Index rows, Index cols)
EIGEN_DEVICE_FUNC DenseStorage (const DenseStorage &other)
EIGEN_DEVICE_FUNC DenseStorage & operator= (const DenseStorage &other)
EIGEN_DEVICE_FUNC ~DenseStorage ()
EIGEN_DEVICE_FUNC void swap (DenseStorage &other)
EIGEN_DEVICE_FUNC Index rows (void) const
void conservativeResize (Index size, Index rows, Index)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void resize (Index size, Index rows, Index)
EIGEN_DEVICE_FUNC const T * data () const
EIGEN_DEVICE_FUNC T * data ()
Static Public Member Functions
static EIGEN_DEVICE_FUNC Index cols (void)
Private Attributes
T * m_data
Index m_rows
Constructor & Destructor Documentation
template<typename T , int _Cols, int _Options> EIGEN_DEVICE_FUNC Eigen::DenseStorage< T, Dynamic, Dynamic, _Cols, _Options >::DenseStorage () inline
template<typename T , int _Cols, int _Options> Eigen::DenseStorage< T, Dynamic, Dynamic, _Cols, _Options >::DenseStorage (internal::constructor_without_unaligned_array_assert) inline explicit
template<typename T , int _Cols, int _Options> EIGEN_DEVICE_FUNC Eigen::DenseStorage< T, Dynamic, Dynamic, _Cols, _Options >::DenseStorage (Index size, Index rows, Index cols) inline
References eigen_internal_assert, EIGEN_INTERNAL_DENSE_STORAGE_CTOR_PLUGIN, and EIGEN_UNUSED_VARIABLE.
template<typename T , int _Cols, int _Options> EIGEN_DEVICE_FUNC Eigen::DenseStorage< T, Dynamic, Dynamic, _Cols, _Options >::DenseStorage (const DenseStorage< T, Dynamic, Dynamic, _Cols, _Options > & other) inline
References EIGEN_INTERNAL_DENSE_STORAGE_CTOR_PLUGIN, Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::m_data, Eigen::internal::size(), and Eigen::internal::smart_copy().
template<typename T , int _Cols, int _Options> EIGEN_DEVICE_FUNC Eigen::DenseStorage< T, Dynamic, Dynamic, _Cols, _Options >::~DenseStorage () inline
Member Function Documentation
template<typename T , int _Cols, int _Options> static EIGEN_DEVICE_FUNC Index Eigen::DenseStorage< T, Dynamic, Dynamic, _Cols, _Options >::cols (void) inline static
template<typename T , int _Cols, int _Options> void Eigen::DenseStorage< T, Dynamic, Dynamic, _Cols, _Options >::conservativeResize (Index size, Index rows, Index) inline
References Eigen::internal::size().
template<typename T , int _Cols, int _Options> EIGEN_DEVICE_FUNC const T* Eigen::DenseStorage< T, Dynamic, Dynamic, _Cols, _Options >::data () const inline
template<typename T , int _Cols, int _Options> EIGEN_DEVICE_FUNC T* Eigen::DenseStorage< T, Dynamic, Dynamic, _Cols, _Options >::data () inline
template<typename T , int _Cols, int _Options> EIGEN_DEVICE_FUNC DenseStorage& Eigen::DenseStorage< T, Dynamic, Dynamic, _Cols, _Options >::operator= (const DenseStorage< T, Dynamic, Dynamic, _Cols, _Options > & other) inline
References EIGEN_NOEXCEPT, Eigen::internal::swap(), and std::swap().
template<typename T , int _Cols, int _Options> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::DenseStorage< T, Dynamic, Dynamic, _Cols, _Options >::resize (Index size, Index rows, Index) inline
References EIGEN_INTERNAL_DENSE_STORAGE_CTOR_PLUGIN, and Eigen::internal::size().
template<typename T , int _Cols, int _Options> EIGEN_DEVICE_FUNC Index Eigen::DenseStorage< T, Dynamic, Dynamic, _Cols, _Options >::rows (void) const inline
template<typename T , int _Cols, int _Options> EIGEN_DEVICE_FUNC void Eigen::DenseStorage< T, Dynamic, Dynamic, _Cols, _Options >::swap (DenseStorage< T, Dynamic, Dynamic, _Cols, _Options > & other) inline
References Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::m_data, and std::swap().
Member Data Documentation
template<typename T , int _Cols, int _Options> T* Eigen::DenseStorage< T, Dynamic, Dynamic, _Cols, _Options >::m_data private
template<typename T , int _Cols, int _Options> Index Eigen::DenseStorage< T, Dynamic, Dynamic, _Cols, _Options >::m_rows private
The documentation for this class was generated from the following file:
DenseStorage.h