SmartMouse_2018: Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized > Class Template Reference
Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized > Class Template Reference
#include <Swap.h>
Public Types
typedef Base::Scalar Scalar
typedef Base::DstXprType DstXprType
typedef swap_assign_op< Scalar > Functor
Public Types inherited from Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar >, BuiltIn >
typedef DstEvaluatorTypeT DstEvaluatorType
typedef SrcEvaluatorTypeT SrcEvaluatorType
typedef DstEvaluatorType::Scalar Scalar
typedef copy_using_evaluator_traits< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar > > AssignmentTraits
typedef AssignmentTraits::PacketType PacketType
Public Member Functions
EIGEN_DEVICE_FUNC generic_dense_assignment_kernel (DstEvaluatorTypeT &dst, const SrcEvaluatorTypeT &src, const Functor &func, DstXprType &dstExpr)
template<int StoreMode, int LoadMode, typename PacketType >
void assignPacket (Index row, Index col)
template<int StoreMode, int LoadMode, typename PacketType >
void assignPacket (Index index)
template<int StoreMode, int LoadMode, typename PacketType >
void assignPacketByOuterInner (Index outer, Index inner)
Public Member Functions inherited from Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar >, BuiltIn >
EIGEN_DEVICE_FUNC generic_dense_assignment_kernel (DstEvaluatorType &dst, const SrcEvaluatorType &src, const swap_assign_op< DstEvaluatorTypeT::Scalar > &func, DstXprType &dstExpr)
EIGEN_DEVICE_FUNC Index size () const
EIGEN_DEVICE_FUNC Index innerSize () const
EIGEN_DEVICE_FUNC Index outerSize () const
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
EIGEN_DEVICE_FUNC Index outerStride () const
EIGEN_DEVICE_FUNC DstEvaluatorType & dstEvaluator ()
EIGEN_DEVICE_FUNC const SrcEvaluatorType & srcEvaluator () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void assignCoeff (Index row, Index col)
Assign src(row,col) to dst(row,col) through the assignment functor.
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void assignCoeff (Index index)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void assignCoeffByOuterInner (Index outer, Index inner)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void assignPacket (Index row, Index col)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void assignPacket (Index index)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void assignPacketByOuterInner (Index outer, Index inner)
EIGEN_DEVICE_FUNC const Scalar * dstDataPtr () const
Protected Types
typedef generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, BuiltIn > Base
Protected Types inherited from Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar >, BuiltIn >
typedef DstEvaluatorTypeT::XprType DstXprType
typedef SrcEvaluatorTypeT::XprType SrcXprType
Additional Inherited Members
Static Public Member Functions inherited from Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar >, BuiltIn >
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index rowIndexByOuterInner (Index outer, Index inner)
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index colIndexByOuterInner (Index outer, Index inner)
Protected Attributes inherited from Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar >, BuiltIn >
DstEvaluatorType & m_dst
const SrcEvaluatorType & m_src
const swap_assign_op< DstEvaluatorTypeT::Scalar > & m_functor
DstXprType & m_dstExpr
Member Typedef Documentation
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT > typedef generic_dense_assignment_kernel<DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op<typename DstEvaluatorTypeT::Scalar>, BuiltIn> Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized >::Base protected
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT > typedef Base::DstXprType Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized >::DstXprType
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT > typedef swap_assign_op<Scalar> Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized >::Functor
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT > typedef Base::Scalar Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized >::Scalar
Constructor & Destructor Documentation
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT > EIGEN_DEVICE_FUNC Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized >::generic_dense_assignment_kernel (DstEvaluatorTypeT & dst, const SrcEvaluatorTypeT & src, const Functor & func, DstXprType & dstExpr) inline
Member Function Documentation
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT > template<int StoreMode, int LoadMode, typename PacketType > void Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized >::assignPacket (Index row, Index col) inline
References col(), Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::m_dst, Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::m_src, and row().
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT > template<int StoreMode, int LoadMode, typename PacketType > void Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized >::assignPacket (Index index) inline
References Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::m_dst, and Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::m_src.
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT > template<int StoreMode, int LoadMode, typename PacketType > void Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized >::assignPacketByOuterInner (Index outer, Index inner) inline
References col(), and row().
The documentation for this class was generated from the following file:
Swap.h