SmartMouse_2018: Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex > Class Template Reference
Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex > Class Template Reference
A versatible sparse matrix representation.
#include <SparseMatrix.h>
Classes
struct default_prunning_func
class SingletonVector
Public Types
enum { Options = _Options }
typedef MappedSparseMatrix< Scalar, Flags > Map
typedef Diagonal< SparseMatrix > DiagonalReturnType
typedef Diagonal< const SparseMatrix > ConstDiagonalReturnType
typedef Base::InnerIterator InnerIterator
typedef Base::ReverseInnerIterator ReverseInnerIterator
typedef internal::CompressedStorage< Scalar, StorageIndex > Storage
typedef Base::IndexVector IndexVector
typedef Base::ScalarVector ScalarVector
Public Types inherited from Eigen::SparseCompressedBase< SparseMatrix< _Scalar, _Options, _StorageIndex > >
typedef SparseMatrixBase< SparseMatrix< _Scalar, _Options, _StorageIndex > > Base
Public Types inherited from Eigen::SparseMatrixBase< SparseMatrix< _Scalar, _Options, _StorageIndex > >
enum
typedef internal::traits< SparseMatrix< _Scalar, _Options, _StorageIndex > >::Scalar Scalar
typedef Scalar value_type
typedef internal::packet_traits< Scalar >::type PacketScalar
typedef internal::traits< SparseMatrix< _Scalar, _Options, _StorageIndex > >::StorageKind StorageKind
typedef internal::traits< SparseMatrix< _Scalar, _Options, _StorageIndex > >::StorageIndex StorageIndex
typedef internal::add_const_on_value_type_if_arithmetic< typename internal::packet_traits< Scalar >::type >::type PacketReturnType
typedef SparseMatrixBase StorageBaseType
typedef Matrix< StorageIndex, Dynamic, 1 > IndexVector
typedef Matrix< Scalar, Dynamic, 1 > ScalarVector
typedef internal::conditional< NumTraits< Scalar >::IsComplex, CwiseUnaryOp< internal::scalar_conjugate_op< Scalar >, Eigen::Transpose< const SparseMatrix< _Scalar, _Options, _StorageIndex > > >, Transpose< const SparseMatrix< _Scalar, _Options, _StorageIndex > > >::type AdjointReturnType
typedef Transpose< SparseMatrix< _Scalar, _Options, _StorageIndex > > TransposeReturnType
typedef internal::add_const< Transpose< const SparseMatrix< _Scalar, _Options, _StorageIndex > > >::type ConstTransposeReturnType
typedef SparseMatrix< Scalar, Flags &RowMajorBit?RowMajor:ColMajor, StorageIndex > PlainObject
typedef NumTraits< Scalar >::Real RealScalar
typedef internal::conditional< _HasDirectAccess, const Scalar &, Scalar >::type CoeffReturnType
typedef CwiseNullaryOp< internal::scalar_constant_op< Scalar >, Matrix< Scalar, Dynamic, Dynamic > > ConstantReturnType
typedef Matrix< Scalar, RowsAtCompileTime, ColsAtCompileTime > DenseMatrixType
typedef Matrix< Scalar, EIGEN_SIZE_MAX(RowsAtCompileTime, ColsAtCompileTime), EIGEN_SIZE_MAX(RowsAtCompileTime, ColsAtCompileTime)> SquareMatrixType
typedef EigenBase< SparseMatrix< _Scalar, _Options, _StorageIndex > > Base
typedef internal::conditional< NumTraits< Scalar >::IsComplex, const CwiseUnaryOp< internal::scalar_conjugate_op< Scalar >, const SparseMatrix< _Scalar, _Options, _StorageIndex > >, const SparseMatrix< _Scalar, _Options, _StorageIndex > & >::type ConjugateReturnType
typedef internal::conditional< NumTraits< Scalar >::IsComplex, const CwiseUnaryOp< internal::scalar_real_op< Scalar >, const SparseMatrix< _Scalar, _Options, _StorageIndex > >, const SparseMatrix< _Scalar, _Options, _StorageIndex > & >::type RealReturnType
typedef internal::conditional< NumTraits< Scalar >::IsComplex, CwiseUnaryView< internal::scalar_real_ref_op< Scalar >, SparseMatrix< _Scalar, _Options, _StorageIndex > >, SparseMatrix< _Scalar, _Options, _StorageIndex > & >::type NonConstRealReturnType
typedef CwiseUnaryOp< internal::scalar_imag_op< Scalar >, const SparseMatrix< _Scalar, _Options, _StorageIndex > > ImagReturnType
typedef CwiseUnaryView< internal::scalar_imag_ref_op< Scalar >, SparseMatrix< _Scalar, _Options, _StorageIndex > > NonConstImagReturnType
typedef CwiseUnaryOp< internal::scalar_opposite_op< Scalar >, const SparseMatrix< _Scalar, _Options, _StorageIndex > > NegativeReturnType
typedef CwiseUnaryOp< internal::scalar_abs_op< Scalar >, const SparseMatrix< _Scalar, _Options, _StorageIndex > > CwiseAbsReturnType
typedef CwiseUnaryOp< internal::scalar_abs2_op< Scalar >, const SparseMatrix< _Scalar, _Options, _StorageIndex > > CwiseAbs2ReturnType
typedef CwiseUnaryOp< internal::scalar_sqrt_op< Scalar >, const SparseMatrix< _Scalar, _Options, _StorageIndex > > CwiseSqrtReturnType
typedef CwiseUnaryOp< internal::scalar_sign_op< Scalar >, const SparseMatrix< _Scalar, _Options, _StorageIndex > > CwiseSignReturnType
typedef CwiseUnaryOp< internal::scalar_inverse_op< Scalar >, const SparseMatrix< _Scalar, _Options, _StorageIndex > > CwiseInverseReturnType
typedef CwiseBinaryOp< internal::scalar_cmp_op< Scalar, Scalar, internal::cmp_EQ >, const SparseMatrix< _Scalar, _Options, _StorageIndex >, const ConstantReturnType > CwiseScalarEqualReturnType
typedef Block< SparseMatrix< _Scalar, _Options, _StorageIndex >, internal::traits< SparseMatrix< _Scalar, _Options, _StorageIndex > >::RowsAtCompileTime, 1,!IsRowMajor > ColXpr
typedef const Block< const SparseMatrix< _Scalar, _Options, _StorageIndex >, internal::traits< SparseMatrix< _Scalar, _Options, _StorageIndex > >::RowsAtCompileTime, 1,!IsRowMajor > ConstColXpr
typedef Block< SparseMatrix< _Scalar, _Options, _StorageIndex >, 1, internal::traits< SparseMatrix< _Scalar, _Options, _StorageIndex > >::ColsAtCompileTime, IsRowMajor > RowXpr
typedef const Block< const SparseMatrix< _Scalar, _Options, _StorageIndex >, 1, internal::traits< SparseMatrix< _Scalar, _Options, _StorageIndex > >::ColsAtCompileTime, IsRowMajor > ConstRowXpr
typedef Block< SparseMatrix< _Scalar, _Options, _StorageIndex >, internal::traits< SparseMatrix< _Scalar, _Options, _StorageIndex > >::RowsAtCompileTime, Dynamic,!IsRowMajor > ColsBlockXpr
typedef const Block< const SparseMatrix< _Scalar, _Options, _StorageIndex >, internal::traits< SparseMatrix< _Scalar, _Options, _StorageIndex > >::RowsAtCompileTime, Dynamic,!IsRowMajor > ConstColsBlockXpr
typedef Block< SparseMatrix< _Scalar, _Options, _StorageIndex >, Dynamic, internal::traits< SparseMatrix< _Scalar, _Options, _StorageIndex > >::ColsAtCompileTime, IsRowMajor > RowsBlockXpr
typedef const Block< const SparseMatrix< _Scalar, _Options, _StorageIndex >, Dynamic, internal::traits< SparseMatrix< _Scalar, _Options, _StorageIndex > >::ColsAtCompileTime, IsRowMajor > ConstRowsBlockXpr
typedef Block< SparseMatrix< _Scalar, _Options, _StorageIndex > > BlockXpr
typedef const Block< const SparseMatrix< _Scalar, _Options, _StorageIndex > > ConstBlockXpr
typedef VectorBlock< SparseMatrix< _Scalar, _Options, _StorageIndex > > SegmentReturnType
typedef const VectorBlock< const SparseMatrix< _Scalar, _Options, _StorageIndex > > ConstSegmentReturnType
typedef Block< SparseMatrix< _Scalar, _Options, _StorageIndex >, IsRowMajor?1:Dynamic, IsRowMajor?Dynamic:1, true > InnerVectorReturnType
typedef Block< const SparseMatrix< _Scalar, _Options, _StorageIndex >, IsRowMajor?1:Dynamic, IsRowMajor?Dynamic:1, true > ConstInnerVectorReturnType
typedef Block< SparseMatrix< _Scalar, _Options, _StorageIndex >, Dynamic, Dynamic, true > InnerVectorsReturnType
typedef Block< const SparseMatrix< _Scalar, _Options, _StorageIndex >, Dynamic, Dynamic, true > ConstInnerVectorsReturnType
Public Types inherited from Eigen::EigenBase< SparseMatrix< _Scalar, _Options, _StorageIndex > >
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< SparseMatrix< _Scalar, _Options, _StorageIndex > >::StorageKind StorageKind
Public Member Functions
Index rows () const
Index cols () const
Index innerSize () const
Index outerSize () const
const Scalar * valuePtr () const
Scalar * valuePtr ()
const StorageIndex * innerIndexPtr () const
StorageIndex * innerIndexPtr ()
const StorageIndex * outerIndexPtr () const
StorageIndex * outerIndexPtr ()
const StorageIndex * innerNonZeroPtr () const
StorageIndex * innerNonZeroPtr ()
Storage & data ()
const Storage & data () const
Scalar coeff (Index row, Index col) const
Scalar & coeffRef (Index row, Index col)
Scalar & insert (Index row, Index col)
void setZero ()
void reserve (Index reserveSize)
template<class SizesType >
void reserve (const SizesType &reserveSizes, const typename SizesType::value_type &enableif=typename SizesType::value_type())
Scalar & insertBack (Index row, Index col)
Scalar & insertBackByOuterInner (Index outer, Index inner)
Scalar & insertBackByOuterInnerUnordered (Index outer, Index inner)
void startVec (Index outer)
void finalize ()
template<typename InputIterators >
void setFromTriplets (const InputIterators &begin, const InputIterators &end)
template<typename InputIterators , typename DupFunctor >
void setFromTriplets (const InputIterators &begin, const InputIterators &end, DupFunctor dup_func)
void sumupDuplicates ()
template<typename DupFunctor >
void collapseDuplicates (DupFunctor dup_func=DupFunctor())
Scalar & insertByOuterInner (Index j, Index i)
void makeCompressed ()
void uncompress ()
void prune (const Scalar &reference, const RealScalar &epsilon=NumTraits< RealScalar >::dummy_precision())
template<typename KeepFunc >
void prune (const KeepFunc &keep=KeepFunc())
void conservativeResize (Index rows, Index cols)
void resize (Index rows, Index cols)
void resizeNonZeros (Index size)
const ConstDiagonalReturnType diagonal () const
DiagonalReturnType diagonal ()
SparseMatrix ()
SparseMatrix (Index rows, Index cols)
template<typename OtherDerived >
SparseMatrix (const SparseMatrixBase< OtherDerived > &other)
template<typename OtherDerived , unsigned int UpLo>
SparseMatrix (const SparseSelfAdjointView< OtherDerived, UpLo > &other)
SparseMatrix (const SparseMatrix &other)
template<typename OtherDerived >
SparseMatrix (const ReturnByValue< OtherDerived > &other)
Copy constructor with in-place evaluation.
template<typename OtherDerived >
SparseMatrix (const DiagonalBase< OtherDerived > &other)
Copy constructor with in-place evaluation.
void swap (SparseMatrix &other)
void setIdentity ()
SparseMatrix & operator= (const SparseMatrix &other)
template<typename OtherDerived >
SparseMatrix & operator= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DONT_INLINE SparseMatrix & operator= (const SparseMatrixBase< OtherDerived > &other)
~SparseMatrix ()
Scalar sum () const
EIGEN_STRONG_INLINE Scalar & insertBackUncompressed (Index row, Index col)
template<typename OtherDerived >
EIGEN_DONT_INLINE SparseMatrix< Scalar, _Options, _StorageIndex > & operator= (const SparseMatrixBase< OtherDerived > &other)
Public Member Functions inherited from Eigen::SparseCompressedBase< SparseMatrix< _Scalar, _Options, _StorageIndex > >
Index nonZeros () const
const Scalar * valuePtr () const
Scalar * valuePtr ()
const StorageIndex * innerIndexPtr () const
StorageIndex * innerIndexPtr ()
const StorageIndex * outerIndexPtr () const
StorageIndex * outerIndexPtr ()
const StorageIndex * innerNonZeroPtr () const
StorageIndex * innerNonZeroPtr ()
bool isCompressed () const
const Map< const Array< Scalar, Dynamic, 1 > > coeffs () const
Map< Array< Scalar, Dynamic, 1 > > coeffs ()
Public Member Functions inherited from Eigen::SparseMatrixBase< SparseMatrix< _Scalar, _Options, _StorageIndex > >
SparseMatrix< _Scalar, _Options, _StorageIndex > & operator= (const EigenBase< OtherDerived > &other)
SparseMatrix< _Scalar, _Options, _StorageIndex > & operator= (const ReturnByValue< OtherDerived > &other)
SparseMatrix< _Scalar, _Options, _StorageIndex > & operator= (const SparseMatrixBase< OtherDerived > &other)
SparseMatrix< _Scalar, _Options, _StorageIndex > & operator= (const SparseMatrix< _Scalar, _Options, _StorageIndex > &other)
const SparseMatrix< _Scalar, _Options, _StorageIndex > & derived () const
SparseMatrix< _Scalar, _Options, _StorageIndex > & derived ()
SparseMatrix< _Scalar, _Options, _StorageIndex > & const_cast_derived () const
EIGEN_DEVICE_FUNC const NegativeReturnType operator- () const
EIGEN_DEVICE_FUNC CastXpr< NewType >::Type cast () const
EIGEN_DEVICE_FUNC ConjugateReturnType conjugate () const
EIGEN_DEVICE_FUNC RealReturnType real () const
EIGEN_DEVICE_FUNC NonConstRealReturnType real ()
EIGEN_DEVICE_FUNC const ImagReturnType imag () const
EIGEN_DEVICE_FUNC NonConstImagReturnType imag ()
EIGEN_DEVICE_FUNC const CwiseUnaryOp< CustomUnaryOp, const SparseMatrix< _Scalar, _Options, _StorageIndex > > unaryExpr (const CustomUnaryOp &func=CustomUnaryOp()) const
Apply a unary operator coefficient-wise.
EIGEN_DEVICE_FUNC const CwiseUnaryView< CustomViewOp, const SparseMatrix< _Scalar, _Options, _StorageIndex > > unaryViewExpr (const CustomViewOp &func=CustomViewOp()) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp< CustomBinaryOp, const SparseMatrix< _Scalar, _Options, _StorageIndex >, const OtherDerived > binaryExpr (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other, const CustomBinaryOp &func=CustomBinaryOp()) const
EIGEN_DEVICE_FUNC const CwiseBinaryOp< internal::scalar_boolean_and_op, const SparseMatrix< _Scalar, _Options, _StorageIndex >, const OtherDerived > operator&& (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
EIGEN_DEVICE_FUNC const CwiseBinaryOp< internal::scalar_boolean_or_op, const SparseMatrix< _Scalar, _Options, _StorageIndex >, const OtherDerived > operator|| (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseAbsReturnType cwiseAbs () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseAbs2ReturnType cwiseAbs2 () const
EIGEN_DEVICE_FUNC const CwiseSqrtReturnType cwiseSqrt () const
EIGEN_DEVICE_FUNC const CwiseSignReturnType cwiseSign () const
EIGEN_DEVICE_FUNC const CwiseInverseReturnType cwiseInverse () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const EIGEN_CWISE_BINARY_RETURN_TYPE (SparseMatrix< _Scalar, _Options, _StorageIndex >, OtherDerived, product) cwiseProduct(const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
EIGEN_DEVICE_FUNC const CwiseBinaryOp< std::equal_to< Scalar >, const SparseMatrix< _Scalar, _Options, _StorageIndex >, const OtherDerived > cwiseEqual (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
EIGEN_DEVICE_FUNC const CwiseScalarEqualReturnType cwiseEqual (const Scalar &s) const
EIGEN_DEVICE_FUNC const CwiseBinaryOp< std::not_equal_to< Scalar >, const SparseMatrix< _Scalar, _Options, _StorageIndex >, const OtherDerived > cwiseNotEqual (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp< internal::scalar_min_op< Scalar, Scalar >, const SparseMatrix< _Scalar, _Options, _StorageIndex >, const OtherDerived > cwiseMin (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp< internal::scalar_min_op< Scalar, Scalar >, const SparseMatrix< _Scalar, _Options, _StorageIndex >, const ConstantReturnType > cwiseMin (const Scalar &other) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp< internal::scalar_max_op< Scalar, Scalar >, const SparseMatrix< _Scalar, _Options, _StorageIndex >, const OtherDerived > cwiseMax (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp< internal::scalar_max_op< Scalar, Scalar >, const SparseMatrix< _Scalar, _Options, _StorageIndex >, const ConstantReturnType > cwiseMax (const Scalar &other) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp< internal::scalar_quotient_op< Scalar >, const SparseMatrix< _Scalar, _Options, _StorageIndex >, const OtherDerived > cwiseQuotient (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type block (Index startRow, Index startCol, NRowsType blockRows, NColsType blockCols)
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type block (Index startRow, Index startCol, NRowsType blockRows, NColsType blockCols) const
This is the const version of block(Index,Index,NRowsType,NColsType)
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol)
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol) const
This is the const version of block<>(Index, Index). */.
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol, Index blockRows, Index blockCols)
const ConstFixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol, Index blockRows, Index blockCols) const
This is the const version of block<>(Index, Index, Index, Index).
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type topRightCorner (NRowsType cRows, NColsType cCols)
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type topRightCorner (NRowsType cRows, NColsType cCols) const
This is the const version of topRightCorner(NRowsType, NColsType).
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type topRightCorner ()
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type topRightCorner () const
This is the const version of topRightCorner<int, int>().
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type topRightCorner (Index cRows, Index cCols)
const ConstFixedBlockXpr< CRows, CCols >::Type topRightCorner (Index cRows, Index cCols) const
This is the const version of topRightCorner<int, int>(Index, Index).
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type topLeftCorner (NRowsType cRows, NColsType cCols)
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type topLeftCorner (NRowsType cRows, NColsType cCols) const
This is the const version of topLeftCorner(Index, Index).
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type topLeftCorner ()
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type topLeftCorner () const
This is the const version of topLeftCorner<int, int>().
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type topLeftCorner (Index cRows, Index cCols)
const ConstFixedBlockXpr< CRows, CCols >::Type topLeftCorner (Index cRows, Index cCols) const
This is the const version of topLeftCorner<int, int>(Index, Index).
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type bottomRightCorner (NRowsType cRows, NColsType cCols)
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type bottomRightCorner (NRowsType cRows, NColsType cCols) const
This is the const version of bottomRightCorner(NRowsType, NColsType).
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type bottomRightCorner ()
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type bottomRightCorner () const
This is the const version of bottomRightCorner<int, int>().
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type bottomRightCorner (Index cRows, Index cCols)
const ConstFixedBlockXpr< CRows, CCols >::Type bottomRightCorner (Index cRows, Index cCols) const
This is the const version of bottomRightCorner<int, int>(Index, Index).
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type bottomLeftCorner (NRowsType cRows, NColsType cCols)
EIGEN_DEVICE_FUNC ConstFixedBlockXpr< internal::get_fixed_value< NRowsType >::value, internal::get_fixed_value< NColsType >::value >::Type bottomLeftCorner (NRowsType cRows, NColsType cCols) const
This is the const version of bottomLeftCorner(NRowsType, NColsType).
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type bottomLeftCorner ()
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type bottomLeftCorner () const
This is the const version of bottomLeftCorner<int, int>().
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type bottomLeftCorner (Index cRows, Index cCols)
const ConstFixedBlockXpr< CRows, CCols >::Type bottomLeftCorner (Index cRows, Index cCols) const
This is the const version of bottomLeftCorner<int, int>(Index, Index).
EIGEN_DEVICE_FUNC NRowsBlockXpr< internal::get_fixed_value< NRowsType >::value >::Type topRows (NRowsType n)
EIGEN_DEVICE_FUNC const ConstNRowsBlockXpr< internal::get_fixed_value< NRowsType >::value >::Type topRows (NRowsType n) const
This is the const version of topRows(NRowsType).
EIGEN_DEVICE_FUNC NRowsBlockXpr< N >::Type topRows (Index n=N)
EIGEN_DEVICE_FUNC ConstNRowsBlockXpr< N >::Type topRows (Index n=N) const
This is the const version of topRows<int>().
EIGEN_DEVICE_FUNC NRowsBlockXpr< internal::get_fixed_value< NRowsType >::value >::Type bottomRows (NRowsType n)
EIGEN_DEVICE_FUNC const ConstNRowsBlockXpr< internal::get_fixed_value< NRowsType >::value >::Type bottomRows (NRowsType n) const
This is the const version of bottomRows(NRowsType).
EIGEN_DEVICE_FUNC NRowsBlockXpr< N >::Type bottomRows (Index n=N)
EIGEN_DEVICE_FUNC ConstNRowsBlockXpr< N >::Type bottomRows (Index n=N) const
This is the const version of bottomRows<int>().
EIGEN_DEVICE_FUNC NRowsBlockXpr< internal::get_fixed_value< NRowsType >::value >::Type middleRows (Index startRow, NRowsType n)
EIGEN_DEVICE_FUNC const ConstNRowsBlockXpr< internal::get_fixed_value< NRowsType >::value >::Type middleRows (Index startRow, NRowsType n) const
This is the const version of middleRows(Index,NRowsType).
EIGEN_DEVICE_FUNC NRowsBlockXpr< N >::Type middleRows (Index startRow, Index n=N)
EIGEN_DEVICE_FUNC ConstNRowsBlockXpr< N >::Type middleRows (Index startRow, Index n=N) const
This is the const version of middleRows<int>().
EIGEN_DEVICE_FUNC NColsBlockXpr< internal::get_fixed_value< NColsType >::value >::Type leftCols (NColsType n)
EIGEN_DEVICE_FUNC const ConstNColsBlockXpr< internal::get_fixed_value< NColsType >::value >::Type leftCols (NColsType n) const
This is the const version of leftCols(NColsType).
EIGEN_DEVICE_FUNC NColsBlockXpr< N >::Type leftCols (Index n=N)
EIGEN_DEVICE_FUNC ConstNColsBlockXpr< N >::Type leftCols (Index n=N) const
This is the const version of leftCols<int>().
EIGEN_DEVICE_FUNC NColsBlockXpr< internal::get_fixed_value< NColsType >::value >::Type rightCols (NColsType n)
EIGEN_DEVICE_FUNC const ConstNColsBlockXpr< internal::get_fixed_value< NColsType >::value >::Type rightCols (NColsType n) const
This is the const version of rightCols(NColsType).
EIGEN_DEVICE_FUNC NColsBlockXpr< N >::Type rightCols (Index n=N)
EIGEN_DEVICE_FUNC ConstNColsBlockXpr< N >::Type rightCols (Index n=N) const
This is the const version of rightCols<int>().
EIGEN_DEVICE_FUNC NColsBlockXpr< internal::get_fixed_value< NColsType >::value >::Type middleCols (Index startCol, NColsType numCols)
EIGEN_DEVICE_FUNC const ConstNColsBlockXpr< internal::get_fixed_value< NColsType >::value >::Type middleCols (Index startCol, NColsType numCols) const
This is the const version of middleCols(Index,NColsType).
EIGEN_DEVICE_FUNC NColsBlockXpr< N >::Type middleCols (Index startCol, Index n=N)
EIGEN_DEVICE_FUNC ConstNColsBlockXpr< N >::Type middleCols (Index startCol, Index n=N) const
This is the const version of middleCols<int>().
EIGEN_DEVICE_FUNC ColXpr col (Index i)
EIGEN_DEVICE_FUNC ConstColXpr col (Index i) const
This is the const version of col().
EIGEN_DEVICE_FUNC RowXpr row (Index i)
EIGEN_DEVICE_FUNC ConstRowXpr row (Index i) const
This is the const version of row(). */.
EIGEN_DEVICE_FUNC FixedSegmentReturnType< internal::get_fixed_value< NType >::value >::Type segment (Index start, NType n)
EIGEN_DEVICE_FUNC const ConstFixedSegmentReturnType< internal::get_fixed_value< NType >::value >::Type segment (Index start, NType n) const
This is the const version of segment(Index,NType).
EIGEN_DEVICE_FUNC FixedSegmentReturnType< N >::Type segment (Index start, Index n=N)
EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType< N >::Type segment (Index start, Index n=N) const
This is the const version of segment<int>(Index).
EIGEN_DEVICE_FUNC FixedSegmentReturnType< internal::get_fixed_value< NType >::value >::Type head (NType n)
EIGEN_DEVICE_FUNC const ConstFixedSegmentReturnType< internal::get_fixed_value< NType >::value >::Type head (NType n) const
This is the const version of head(NType).
EIGEN_DEVICE_FUNC FixedSegmentReturnType< N >::Type head (Index n=N)
EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType< N >::Type head (Index n=N) const
This is the const version of head<int>().
EIGEN_DEVICE_FUNC FixedSegmentReturnType< internal::get_fixed_value< NType >::value >::Type tail (NType n)
EIGEN_DEVICE_FUNC const ConstFixedSegmentReturnType< internal::get_fixed_value< NType >::value >::Type tail (NType n) const
This is the const version of tail(Index).
EIGEN_DEVICE_FUNC FixedSegmentReturnType< N >::Type tail (Index n=N)
EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType< N >::Type tail (Index n=N) const
This is the const version of tail<int>.
Index rows () const
Index cols () const
Index size () const
bool isVector () const
Index outerSize () const
Index innerSize () const
bool isRValue () const
SparseMatrix< _Scalar, _Options, _StorageIndex > & markAsRValue ()
SparseMatrixBase ()
SparseMatrix< _Scalar, _Options, _StorageIndex > & operator+= (const SparseMatrixBase< OtherDerived > &other)
SparseMatrix< _Scalar, _Options, _StorageIndex > & operator+= (const DiagonalBase< OtherDerived > &other)
SparseMatrix< _Scalar, _Options, _StorageIndex > & operator+= (const EigenBase< OtherDerived > &other)
SparseMatrix< _Scalar, _Options, _StorageIndex > & operator-= (const SparseMatrixBase< OtherDerived > &other)
SparseMatrix< _Scalar, _Options, _StorageIndex > & operator-= (const DiagonalBase< OtherDerived > &other)
SparseMatrix< _Scalar, _Options, _StorageIndex > & operator-= (const EigenBase< OtherDerived > &other)
SparseMatrix< _Scalar, _Options, _StorageIndex > & operator*= (const Scalar &other)
SparseMatrix< _Scalar, _Options, _StorageIndex > & operator*= (const SparseMatrixBase< OtherDerived > &other)
SparseMatrix< _Scalar, _Options, _StorageIndex > & operator/= (const Scalar &other)
EIGEN_STRONG_INLINE const CwiseProductDenseReturnType< OtherDerived >::Type cwiseProduct (const MatrixBase< OtherDerived > &other) const
const Product< SparseMatrix< _Scalar, _Options, _StorageIndex >, OtherDerived > operator* (const DiagonalBase< OtherDerived > &other) const
const Product< SparseMatrix< _Scalar, _Options, _StorageIndex >, OtherDerived, AliasFreeProduct > operator* (const SparseMatrixBase< OtherDerived > &other) const
const Product< SparseMatrix< _Scalar, _Options, _StorageIndex >, OtherDerived > operator* (const MatrixBase< OtherDerived > &other) const
SparseSymmetricPermutationProduct< SparseMatrix< _Scalar, _Options, _StorageIndex >, Upper|Lower > twistedBy (const PermutationMatrix< Dynamic, Dynamic, StorageIndex > &perm) const
const TriangularView< const SparseMatrix< _Scalar, _Options, _StorageIndex >, Mode > triangularView () const
ConstSelfAdjointViewReturnType< UpLo >::Type selfadjointView () const
SelfAdjointViewReturnType< UpLo >::Type selfadjointView ()
Scalar dot (const MatrixBase< OtherDerived > &other) const
Scalar dot (const SparseMatrixBase< OtherDerived > &other) const
RealScalar squaredNorm () const
RealScalar norm () const
RealScalar blueNorm () const
TransposeReturnType transpose ()
const ConstTransposeReturnType transpose () const
const AdjointReturnType adjoint () const
InnerVectorReturnType innerVector (Index outer)
const ConstInnerVectorReturnType innerVector (Index outer) const
InnerVectorsReturnType innerVectors (Index outerStart, Index outerSize)
const ConstInnerVectorsReturnType innerVectors (Index outerStart, Index outerSize) const
DenseMatrixType toDense () const
bool isApprox (const SparseMatrixBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool isApprox (const MatrixBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
const internal::eval< SparseMatrix< _Scalar, _Options, _StorageIndex > >::type eval () const
Scalar sum () const
const SparseView< SparseMatrix< _Scalar, _Options, _StorageIndex > > pruned (const Scalar &reference=Scalar(0), const RealScalar &epsilon=NumTraits< Scalar >::dummy_precision()) const
Public Member Functions inherited from Eigen::EigenBase< SparseMatrix< _Scalar, _Options, _StorageIndex > >
EIGEN_DEVICE_FUNC SparseMatrix< _Scalar, _Options, _StorageIndex > & derived ()
EIGEN_DEVICE_FUNC const SparseMatrix< _Scalar, _Options, _StorageIndex > & derived () const
EIGEN_DEVICE_FUNC SparseMatrix< _Scalar, _Options, _StorageIndex > & const_cast_derived () const
EIGEN_DEVICE_FUNC const SparseMatrix< _Scalar, _Options, _StorageIndex > & const_derived () const
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
EIGEN_DEVICE_FUNC Index size () const
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
Protected Types
typedef SparseMatrix< Scalar,(Flags &~RowMajorBit)|(IsRowMajor?RowMajorBit:0)> TransposedSparseMatrix
Protected Types inherited from Eigen::SparseCompressedBase< SparseMatrix< _Scalar, _Options, _StorageIndex > >
typedef Base::IndexVector IndexVector
Protected Member Functions
template<class SizesType >
void reserveInnerVectors (const SizesType &reserveSizes)
template<typename Other >
void initAssignment (const Other &other)
EIGEN_DONT_INLINE Scalar & insertCompressed (Index row, Index col)
EIGEN_DONT_INLINE Scalar & insertUncompressed (Index row, Index col)
Protected Member Functions inherited from Eigen::SparseCompressedBase< SparseMatrix< _Scalar, _Options, _StorageIndex > >
Eigen::Map< IndexVector > innerNonZeros ()
const Eigen::Map< const IndexVector > innerNonZeros () const
SparseCompressedBase ()
Protected Member Functions inherited from Eigen::SparseMatrixBase< SparseMatrix< _Scalar, _Options, _StorageIndex > >
SparseMatrix< _Scalar, _Options, _StorageIndex > & assign (const OtherDerived &other)
void assignGeneric (const OtherDerived &other)
Protected Attributes
Index m_outerSize
Index m_innerSize
StorageIndex * m_outerIndex
StorageIndex * m_innerNonZeros
Storage m_data
Protected Attributes inherited from Eigen::SparseMatrixBase< SparseMatrix< _Scalar, _Options, _StorageIndex > >
bool m_isRValue
Private Types
typedef SparseCompressedBase< SparseMatrix > Base
Static Private Member Functions
static void check_template_parameters ()
Friends
class SparseVector< _Scalar, 0, _StorageIndex >
std::ostream & operator<< (std::ostream &s, const SparseMatrix &m)
Additional Inherited Members
Static Protected Member Functions inherited from Eigen::SparseMatrixBase< SparseMatrix< _Scalar, _Options, _StorageIndex > >
static StorageIndex convert_index (const Index idx)
Detailed Description
template<typename _Scalar, int _Options, typename _StorageIndex>
class Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >
A versatible sparse matrix representation.
This class implements a more versatile variants of the common compressed row/column storage format. Each colmun's (resp. row) non zeros are stored as a pair of value with associated row (resp. colmiun) index. All the non zeros are stored in a single large buffer. Unlike the compressed format, there might be extra space inbetween the nonzeros of two successive colmuns (resp. rows) such that insertion of new non-zero can be done with limited memory reallocation and copies.
A call to the function makeCompressed() turns the matrix into the standard compressed format compatible with many library.
More details on this storage sceheme are given in the manual pages.
Template Parameters
_Scalar the scalar type, i.e. the type of the coefficients
_Options Union of bit flags controlling the storage scheme. Currently the only possibility is ColMajor or RowMajor. The default is 0 which means column-major.
_StorageIndex the type of the indices. It has to be a signed type (e.g., short, int, std::ptrdiff_t). Default is int.
Warning
In Eigen 3.2, the undocumented type SparseMatrix::Index was improperly defined as the storage index type (e.g., int), whereas it is now (starting from Eigen 3.3) deprecated and always defined as Eigen::Index. Codes making use of SparseMatrix::Index, might thus likely have to be changed to use SparseMatrix::StorageIndex instead.
This class can be extended with the help of the plugin mechanism described on the page TopicCustomizing_Plugins by defining the preprocessor symbol EIGEN_SPARSEMATRIX_PLUGIN.
Member Typedef Documentation
template<typename _Scalar, int _Options, typename _StorageIndex> typedef SparseCompressedBase<SparseMatrix> Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::Base private
template<typename _Scalar, int _Options, typename _StorageIndex> typedef Diagonal<const SparseMatrix> Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::ConstDiagonalReturnType
template<typename _Scalar, int _Options, typename _StorageIndex> typedef Diagonal<SparseMatrix> Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::DiagonalReturnType
template<typename _Scalar, int _Options, typename _StorageIndex> typedef Base::IndexVector Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::IndexVector
template<typename _Scalar, int _Options, typename _StorageIndex> typedef Base::InnerIterator Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::InnerIterator
template<typename _Scalar, int _Options, typename _StorageIndex> typedef MappedSparseMatrix<Scalar,Flags> Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::Map
template<typename _Scalar, int _Options, typename _StorageIndex> typedef Base::ReverseInnerIterator Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::ReverseInnerIterator
template<typename _Scalar, int _Options, typename _StorageIndex> typedef Base::ScalarVector Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::ScalarVector
template<typename _Scalar, int _Options, typename _StorageIndex> typedef internal::CompressedStorage<Scalar,StorageIndex> Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::Storage
template<typename _Scalar, int _Options, typename _StorageIndex> typedef SparseMatrix<Scalar,(Flags&~RowMajorBit)|(IsRowMajor?RowMajorBit:0)> Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::TransposedSparseMatrix protected
Member Enumeration Documentation
template<typename _Scalar, int _Options, typename _StorageIndex> anonymous enum
Enumerator
Options
Constructor & Destructor Documentation
template<typename _Scalar, int _Options, typename _StorageIndex> Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::SparseMatrix () inline
Default constructor yielding an empty 0 x 0 matrix
template<typename _Scalar, int _Options, typename _StorageIndex> Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::SparseMatrix (Index rows, Index cols) inline
Constructs a rows x cols empty matrix
template<typename _Scalar, int _Options, typename _StorageIndex> template<typename OtherDerived > Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::SparseMatrix (const SparseMatrixBase< OtherDerived > & other) inline
Constructs a sparse matrix from the sparse expression other
template<typename _Scalar, int _Options, typename _StorageIndex> template<typename OtherDerived , unsigned int UpLo> Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::SparseMatrix (const SparseSelfAdjointView< OtherDerived, UpLo > & other) inline
Constructs a sparse matrix from the sparse selfadjoint view other
template<typename _Scalar, int _Options, typename _StorageIndex> Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::SparseMatrix (const SparseMatrix< _Scalar, _Options, _StorageIndex > & other) inline
Copy constructor (it performs a deep copy)
template<typename _Scalar, int _Options, typename _StorageIndex> template<typename OtherDerived > Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::SparseMatrix (const ReturnByValue< OtherDerived > & other) inline
Copy constructor with in-place evaluation.
template<typename _Scalar, int _Options, typename _StorageIndex> template<typename OtherDerived > Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::SparseMatrix (const DiagonalBase< OtherDerived > & other) inline explicit
Copy constructor with in-place evaluation.
template<typename _Scalar, int _Options, typename _StorageIndex> Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::~SparseMatrix () inline
Destructor
Member Function Documentation
template<typename _Scalar, int _Options, typename _StorageIndex> static void Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::check_template_parameters () inline static private
template<typename _Scalar, int _Options, typename _StorageIndex> Scalar Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::coeff (Index row, Index col) const inline
Returns
the value of the matrix at position i, j This function returns Scalar(0) if the element is an explicit zero
template<typename _Scalar, int _Options, typename _StorageIndex> Scalar& Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::coeffRef (Index row, Index col) inline
Returns
a non-const reference to the value of the matrix at position i, j
If the element does not exist then it is inserted via the insert(Index,Index) function which itself turns the matrix into a non compressed form if that was not the case.
This is a O(log(nnz_j)) operation (binary search) plus the cost of insert(Index,Index) function if the element does not already exist.
template<typename Scalar , int _Options, typename _StorageIndex > template<typename DupFunctor > void Eigen::SparseMatrix< Scalar, _Options, _StorageIndex >::collapseDuplicates (DupFunctor dup_func = DupFunctor())
References eigen_assert, i, Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::index(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::resize(), and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::value().
template<typename _Scalar, int _Options, typename _StorageIndex> Index Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::cols (void) const inline
Returns
the number of columns of the matrix
Referenced by Eigen::SparseLU< _MatrixType, _OrderingType >::analyzePattern(), Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::cols(), Eigen::SparseLU< _MatrixType, _OrderingType >::cols(), Eigen::SPQR< _MatrixType >::compute(), Eigen::PastixBase< Derived >::compute(), Eigen::SparseLU< _MatrixType, _OrderingType >::factorize(), Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::factorize(), Eigen::SimplicialCholeskyBase< Derived >::factorize_preordered(), Eigen::internal::minimum_degree_ordering(), and Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, Diagonal2Sparse >::run().
template<typename _Scalar, int _Options, typename _StorageIndex> void Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::conservativeResize (Index rows, Index cols) inline
Resizes the matrix to a rows x cols matrix leaving old values untouched.
If the sizes of the matrix are decreased, then the matrix is turned to uncompressed-mode and the storage of the out of bounds coefficients is kept and reserved. Call makeCompressed() to pack the entries and squeeze extra memory.
See also
reserve(), setZero(), makeCompressed()
template<typename _Scalar, int _Options, typename _StorageIndex> Storage& Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::data () inline
template<typename _Scalar, int _Options, typename _StorageIndex> const Storage& Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::data () const inline
template<typename _Scalar, int _Options, typename _StorageIndex> const ConstDiagonalReturnType Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::diagonal () const inline
Returns
a const expression of the diagonal coefficients.
template<typename _Scalar, int _Options, typename _StorageIndex> DiagonalReturnType Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::diagonal () inline
Returns
a read-write expression of the diagonal coefficients.
Warning
If the diagonal entries are written, then all diagonal entries must already exist, otherwise an assertion will be raised.
template<typename _Scalar, int _Options, typename _StorageIndex> void Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::finalize () inline
template<typename _Scalar, int _Options, typename _StorageIndex> template<typename Other > void Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::initAssignment (const Other & other) inline protected
template<typename _Scalar, int _Options, typename _StorageIndex> const StorageIndex* Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::innerIndexPtr () const inline
Returns
a const pointer to the array of inner indices. This function is aimed at interoperability with other libraries.
See also
valuePtr(), outerIndexPtr()
Referenced by Eigen::PastixBase< Derived >::analyzePattern(), Eigen::UmfPackLU< _MatrixType >::extractData(), Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::factorize(), Eigen::PastixBase< Derived >::factorize(), Eigen::internal::minimum_degree_ordering(), and Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, Diagonal2Sparse >::run().
template<typename _Scalar, int _Options, typename _StorageIndex> StorageIndex* Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::innerIndexPtr () inline
Returns
a non-const pointer to the array of inner indices. This function is aimed at interoperability with other libraries.
See also
valuePtr(), outerIndexPtr()
template<typename _Scalar, int _Options, typename _StorageIndex> const StorageIndex* Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::innerNonZeroPtr () const inline
Returns
a const pointer to the array of the number of non zeros of the inner vectors. This function is aimed at interoperability with other libraries.
Warning
it returns the null pointer 0 in compressed mode
Referenced by Eigen::SparseLU< _MatrixType, _OrderingType >::analyzePattern(), and Eigen::SparseLU< _MatrixType, _OrderingType >::factorize().
template<typename _Scalar, int _Options, typename _StorageIndex> StorageIndex* Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::innerNonZeroPtr () inline
Returns
a non-const pointer to the array of the number of non zeros of the inner vectors. This function is aimed at interoperability with other libraries.
Warning
it returns the null pointer 0 in compressed mode
template<typename _Scalar, int _Options, typename _StorageIndex> Index Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::innerSize () const inline
Returns
the number of rows (resp. columns) of the matrix if the storage order column major (resp. row major)
template<typename _Scalar , int _Options, typename _StorageIndex > SparseMatrix< _Scalar, _Options, _StorageIndex >::Scalar & Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insert (Index row, Index col)
Returns
a reference to a novel non zero coefficient with coordinates row x col. The non zero coefficient must not already exist.
If the matrix *this is in compressed mode, then *this is turned into uncompressed mode while reserving room for 2 x this->innerSize() non zeros if reserve(Index) has not been called earlier. In this case, the insertion procedure is optimized for a sequential insertion mode where elements are assumed to be inserted by increasing outer-indices.
If that's not the case, then it is strongly recommended to either use a triplet-list to assemble the matrix, or to first call reserve(const SizesType &) to reserve the appropriate number of non-zero elements per inner vector.
Assuming memory has been appropriately reserved, this function performs a sorted insertion in O(1) if the elements of each inner vector are inserted in increasing inner index order, and in O(nnz_j) for a random insertion.
References Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::allocatedSize(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::append(), col(), Eigen::internal::convert_index(), eigen_assert, eigen_internal_assert, Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::index(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::reserve(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::resize(), row(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::size(), Eigen::internal::throw_std_bad_alloc(), and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::value().
template<typename _Scalar, int _Options, typename _StorageIndex> Scalar& Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertBack (Index row, Index col) inline
template<typename _Scalar, int _Options, typename _StorageIndex> Scalar& Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertBackByOuterInner (Index outer, Index inner) inline
template<typename _Scalar, int _Options, typename _StorageIndex> Scalar& Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertBackByOuterInnerUnordered (Index outer, Index inner) inline
template<typename _Scalar, int _Options, typename _StorageIndex> EIGEN_STRONG_INLINE Scalar& Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertBackUncompressed (Index row, Index col) inline
template<typename _Scalar, int _Options, typename _StorageIndex> Scalar& Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertByOuterInner (Index j, Index i) inline
template<typename _Scalar , int _Options, typename _StorageIndex > EIGEN_DONT_INLINE SparseMatrix< _Scalar, _Options, _StorageIndex >::Scalar & Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertCompressed (Index row, Index col) protected
References Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::allocatedSize(), col(), Eigen::internal::convert_index(), eigen_assert, Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::index(), Eigen::half_impl::max(), Eigen::half_impl::min(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::reserve(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::resize(), row(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::size(), and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::value().
template<typename _Scalar , int _Options, typename _StorageIndex > EIGEN_DONT_INLINE SparseMatrix< _Scalar, _Options, _StorageIndex >::Scalar & Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertUncompressed (Index row, Index col) protected
References col(), Eigen::internal::convert_index(), eigen_assert, Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::index(), and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::value().
template<typename _Scalar, int _Options, typename _StorageIndex> void Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::makeCompressed () inline
Turns the matrix into the compressed format.
Referenced by Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, Diagonal2Sparse >::run().
template<typename _Scalar, int _Options, typename _StorageIndex> SparseMatrix& Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::operator= (const SparseMatrix< _Scalar, _Options, _StorageIndex > & other) inline
template<typename _Scalar, int _Options, typename _StorageIndex> template<typename OtherDerived > SparseMatrix& Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::operator= (const EigenBase< OtherDerived > & other) inline
template<typename _Scalar, int _Options, typename _StorageIndex> template<typename OtherDerived > EIGEN_DONT_INLINE SparseMatrix& Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::operator= (const SparseMatrixBase< OtherDerived > & other)
template<typename _Scalar, int _Options, typename _StorageIndex> template<typename OtherDerived > EIGEN_DONT_INLINE SparseMatrix<Scalar,_Options,_StorageIndex>& Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::operator= (const SparseMatrixBase< OtherDerived > & other)
References Eigen::SparseMatrixBase< Derived >::cols(), Eigen::SparseMatrixBase< Derived >::derived(), EIGEN_STATIC_ASSERT, Eigen::SparseMatrixBase< Derived >::isRValue(), it, Eigen::RowMajorBit, Eigen::SparseMatrixBase< Derived >::rows(), Eigen::internal::swap(), and type.
template<typename _Scalar, int _Options, typename _StorageIndex> const StorageIndex* Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::outerIndexPtr () const inline
Returns
a const pointer to the array of the starting positions of the inner vectors. This function is aimed at interoperability with other libraries.
See also
valuePtr(), innerIndexPtr()
Referenced by Eigen::SparseLU< _MatrixType, _OrderingType >::analyzePattern(), Eigen::PastixBase< Derived >::analyzePattern(), Eigen::UmfPackLU< _MatrixType >::extractData(), Eigen::SparseLU< _MatrixType, _OrderingType >::factorize(), Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::factorize(), Eigen::PastixBase< Derived >::factorize(), Eigen::internal::minimum_degree_ordering(), and Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, Diagonal2Sparse >::run().
template<typename _Scalar, int _Options, typename _StorageIndex> StorageIndex* Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::outerIndexPtr () inline
Returns
a non-const pointer to the array of the starting positions of the inner vectors. This function is aimed at interoperability with other libraries.
See also
valuePtr(), innerIndexPtr()
template<typename _Scalar, int _Options, typename _StorageIndex> Index Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::outerSize () const inline
Returns
the number of columns (resp. rows) of the matrix if the storage order column major (resp. row major)
Referenced by Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::swap().
template<typename _Scalar, int _Options, typename _StorageIndex> void Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::prune (const Scalar & reference, const RealScalar & epsilon = NumTraits<RealScalar>::dummy_precision()) inline
Suppresses all nonzeros which are much smaller than reference under the tolerence epsilon
template<typename _Scalar, int _Options, typename _StorageIndex> template<typename KeepFunc > void Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::prune (const KeepFunc & keep = KeepFunc()) inline
Turns the matrix into compressed format, and suppresses all nonzeros which do not satisfy the predicate keep. The functor type KeepFunc must implement the following function:
bool operator() (const Index& row, const Index& col, const Scalar& value) const;
See also
prune(Scalar,RealScalar)
template<typename _Scalar, int _Options, typename _StorageIndex> void Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::reserve (Index reserveSize) inline
Preallocates reserveSize non zeros.
Precondition: the matrix must be in compressed mode.
template<typename _Scalar, int _Options, typename _StorageIndex> template<class SizesType > void Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::reserve (const SizesType & reserveSizes, const typename SizesType::value_type & enableif = typename SizesType::value_type()) inline
template<typename _Scalar, int _Options, typename _StorageIndex> template<class SizesType > void Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::reserveInnerVectors (const SizesType & reserveSizes) inline protected
template<typename _Scalar, int _Options, typename _StorageIndex> void Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::resize (Index rows, Index cols) inline
Resizes the matrix to a rows x cols matrix and initializes it to zero.
This function does not free the currently allocated memory. To release as much as memory as possible, call
mat.data().squeeze();
after resizing it.
See also
reserve(), setZero()
Referenced by Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::analyzePattern(), Eigen::UmfPackLU< _MatrixType >::extractData(), Eigen::PastixLLT< _MatrixType, _UpLo >::grabMatrix(), Eigen::PastixLDLT< _MatrixType, _UpLo >::grabMatrix(), Eigen::SimplicialCholeskyBase< Derived >::ordering(), and Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, Diagonal2Sparse >::run().
template<typename _Scalar, int _Options, typename _StorageIndex> void Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::resizeNonZeros (Index size) inline
Referenced by Eigen::UmfPackLU< _MatrixType >::extractData(), Eigen::internal::minimum_degree_ordering(), and Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, Diagonal2Sparse >::run().
template<typename _Scalar, int _Options, typename _StorageIndex> Index Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::rows (void) const inline
Returns
the number of rows of the matrix
Referenced by Eigen::PastixBase< Derived >::analyzePattern(), Eigen::SimplicialCholeskyBase< Derived >::analyzePattern_preordered(), Eigen::SPQR< _MatrixType >::compute(), Eigen::PastixBase< Derived >::compute(), Eigen::SparseLU< _MatrixType, _OrderingType >::factorize(), Eigen::PastixBase< Derived >::factorize(), Eigen::SimplicialCholeskyBase< Derived >::factorize_preordered(), Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::rows(), Eigen::SparseLU< _MatrixType, _OrderingType >::rows(), and Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, Diagonal2Sparse >::run().
template<typename Scalar , int _Options, typename _StorageIndex > template<typename InputIterators > void Eigen::SparseMatrix< Scalar, _Options, _StorageIndex >::setFromTriplets (const InputIterators & begin, const InputIterators & end)
Fill the matrix *this with the list of triplets defined by the iterator range begin - end.
A triplet is a tuple (i,j,value) defining a non-zero element. The input list of triplets does not have to be sorted, and can contains duplicated elements. In any case, the result is a sorted and compressed sparse matrix where the duplicates have been summed up. This is a O(n) operation, with n the number of triplet elements. The initial contents of *this is destroyed. The matrix *this must be properly resized beforehand using the SparseMatrix(Index,Index) constructor, or the resize(Index,Index) method. The sizes are not extracted from the triplet list.
The InputIterators value_type must provide the following interface:
Scalar value() const; // the value
Scalar row() const;   // the row index i
Scalar col() const;   // the column index j
See for instance the Eigen::Triplet template class.
Here is a typical usage example:
typedef Triplet<double> T;
std::vector<T> tripletList;
triplets.reserve(estimation_of_entries);
for(...)
{
  // ...
  tripletList.push_back(T(i,j,v_ij));
}
SparseMatrixType m(rows,cols);
m.setFromTriplets(tripletList.begin(), tripletList.end());
// m is ready to go!
Warning
The list of triplets is read multiple times (at least twice). Therefore, it is not recommended to define an abstract iterator over a complex data-structure that would be expensive to evaluate. The triplets should rather be explicitely stored into a std::vector for instance.
References Eigen::placeholders::end().
template<typename Scalar , int _Options, typename _StorageIndex > template<typename InputIterators , typename DupFunctor > void Eigen::SparseMatrix< Scalar, _Options, _StorageIndex >::setFromTriplets (const InputIterators & begin, const InputIterators & end, DupFunctor dup_func)
The same as setFromTriplets but when duplicates are met the functor dup_func is applied:
value = dup_func(OldValue, NewValue)
Here is a C++11 example keeping the latest entry only:
mat.setFromTriplets(triplets.begin(), triplets.end(), [] (const Scalar&,const Scalar &b) { return b; });
References Eigen::placeholders::end().
template<typename _Scalar, int _Options, typename _StorageIndex> void Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::setIdentity () inline
Sets *this to the identity matrix. This function also turns the matrix into compressed mode, and drop any reserved memory.
template<typename _Scalar, int _Options, typename _StorageIndex> void Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::setZero () inline
Removes all non zeros but keep allocated memory
This function does not free the currently allocated memory. To release as much as memory as possible, call
mat.data().squeeze();
after resizing it.
See also
resize(Index,Index), data()
Referenced by Eigen::internal::set_from_triplets().
template<typename _Scalar, int _Options, typename _StorageIndex> void Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::startVec (Index outer) inline
template<typename _Scalar , int _Options, typename _Index > internal::traits< SparseMatrix< _Scalar, _Options, _Index > >::Scalar Eigen::SparseMatrix< _Scalar, _Options, _Index >::sum () const
Overloaded for performance
References eigen_assert, and Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::Map().
template<typename _Scalar, int _Options, typename _StorageIndex> void Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::sumupDuplicates () inline
template<typename _Scalar, int _Options, typename _StorageIndex> void Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::swap (SparseMatrix< _Scalar, _Options, _StorageIndex > & other) inline
Swaps the content of two sparse matrices of the same type. This is a fast operation that simply swaps the underlying pointers and parameters.
template<typename _Scalar, int _Options, typename _StorageIndex> void Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::uncompress () inline
Turns the matrix into the uncompressed mode
Referenced by Eigen::SparseLU< _MatrixType, _OrderingType >::analyzePattern(), and Eigen::SparseLU< _MatrixType, _OrderingType >::factorize().
template<typename _Scalar, int _Options, typename _StorageIndex> const Scalar* Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::valuePtr () const inline
Returns
a const pointer to the array of values. This function is aimed at interoperability with other libraries.
See also
innerIndexPtr(), outerIndexPtr()
Referenced by Eigen::PastixBase< Derived >::analyzePattern(), Eigen::UmfPackLU< _MatrixType >::extractData(), Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::factorize(), Eigen::PastixBase< Derived >::factorize(), and Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, Diagonal2Sparse >::run().
template<typename _Scalar, int _Options, typename _StorageIndex> Scalar* Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::valuePtr () inline
Returns
a non-const pointer to the array of values. This function is aimed at interoperability with other libraries.
See also
innerIndexPtr(), outerIndexPtr()
Friends And Related Function Documentation
template<typename _Scalar, int _Options, typename _StorageIndex> std::ostream& operator<< (std::ostream & s, const SparseMatrix< _Scalar, _Options, _StorageIndex > & m) friend
template<typename _Scalar, int _Options, typename _StorageIndex> friend class SparseVector< _Scalar, 0, _StorageIndex > friend
Member Data Documentation
template<typename _Scalar, int _Options, typename _StorageIndex> Storage Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_data protected
Referenced by Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::operator=(), Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::swap(), and Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::swap().
template<typename _Scalar, int _Options, typename _StorageIndex> StorageIndex* Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_innerNonZeros protected
Referenced by Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::swap().
template<typename _Scalar, int _Options, typename _StorageIndex> Index Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_innerSize protected
Referenced by Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::swap(), and Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::swap().
template<typename _Scalar, int _Options, typename _StorageIndex> StorageIndex* Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_outerIndex protected
Referenced by Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::operator=(), and Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::swap().
template<typename _Scalar, int _Options, typename _StorageIndex> Index Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_outerSize protected
Referenced by Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::swap().
The documentation for this class was generated from the following files:
SparseMatrix.h
SparseRedux.h