SmartMouse_2018: smartmouse::kc::DriveStraightState Class Reference
smartmouse::kc::DriveStraightState Class Reference
#include <DriveStraightState.h>
Public Member Functions
DriveStraightState (GlobalPose start_pose, double goalDisp, double v_initial, double v_final)
std::pair< double, double > compute_wheel_velocities (Mouse &mouse, double t_s)
double dispError ()
double compute_forward_velocity (double t_s)
Static Public Attributes
static constexpr double kPWall = 0.8
static constexpr double kPYaw = -1.2
Private Attributes
double goal_disp = 0
const double v_0 = 0
double v_f = 0
const double t_1 = 0
const double v_1 = 0
const double v_2 = 0
double t_2 = 0
double t_f = 0
double disp = 0
GlobalPose start_pose
Static Private Attributes
static constexpr double a_m = 2
static constexpr double j_m = 10
Constructor & Destructor Documentation
smartmouse::kc::DriveStraightState::DriveStraightState (GlobalPose start_pose, double goalDisp, double v_initial, double v_final)
Member Function Documentation
double smartmouse::kc::DriveStraightState::compute_forward_velocity (double t_s)
References a_m, j_m, t_1, t_2, t_f, v_0, v_1, v_2, and v_f.
Referenced by compute_wheel_velocities().
std::pair< double, double > smartmouse::kc::DriveStraightState::compute_wheel_velocities (Mouse & mouse, double t_s)
References compute_forward_velocity(), dir_to_yaw(), disp, KinematicController::fwdDisp(), Mouse::getDir(), Mouse::getGlobalPose(), kPWall, kPYaw, KinematicController::sidewaysDispToCenter(), start_pose, GlobalPose::yaw, and smartmouse::math::yaw_diff().
double smartmouse::kc::DriveStraightState::dispError ()
References disp, and goal_disp.
Member Data Documentation
constexpr double smartmouse::kc::DriveStraightState::a_m = 2 static private
Referenced by compute_forward_velocity().
double smartmouse::kc::DriveStraightState::disp = 0 private
Referenced by compute_wheel_velocities(), and dispError().
double smartmouse::kc::DriveStraightState::goal_disp = 0 private
Referenced by dispError().
constexpr double smartmouse::kc::DriveStraightState::j_m = 10 static private
Referenced by compute_forward_velocity().
constexpr double smartmouse::kc::DriveStraightState::kPWall = 0.8 static
Referenced by compute_wheel_velocities().
constexpr double smartmouse::kc::DriveStraightState::kPYaw = -1.2 static
Referenced by compute_wheel_velocities().
GlobalPose smartmouse::kc::DriveStraightState::start_pose private
Referenced by compute_wheel_velocities().
const double smartmouse::kc::DriveStraightState::t_1 = 0 private
Referenced by compute_forward_velocity().
double smartmouse::kc::DriveStraightState::t_2 = 0 private
Referenced by compute_forward_velocity().
double smartmouse::kc::DriveStraightState::t_f = 0 private
Referenced by compute_forward_velocity().
const double smartmouse::kc::DriveStraightState::v_0 = 0 private
Referenced by compute_forward_velocity().
const double smartmouse::kc::DriveStraightState::v_1 = 0 private
Referenced by compute_forward_velocity().
const double smartmouse::kc::DriveStraightState::v_2 = 0 private
Referenced by compute_forward_velocity().
double smartmouse::kc::DriveStraightState::v_f = 0 private
Referenced by compute_forward_velocity().
The documentation for this class was generated from the following files:
DriveStraightState.h
DriveStraightState.cpp