SmartMouse_2018: Finish Class Reference
Finish Class Reference
#include <Finish.h>
Public Member Functions
Finish (AbstractMaze *maze)
void initialize ()
run once in the first iteration of the command's life. this will be overrided by individual commands
void execute ()
stuff to do over and over each iteration. this will be overrided by individual commands
bool isFinished ()
checked every iteration to see if we're done here. this will be overrided by individual commands
Finish (AbstractMaze *maze)
void initialize ()
run once in the first iteration of the command's life. this will be overrided by individual commands
bool isFinished ()
checked every iteration to see if we're done here. this will be overrided by individual commands
Finish (AbstractMaze *maze)
void initialize ()
run once in the first iteration of the command's life. this will be overrided by individual commands
bool isFinished ()
checked every iteration to see if we're done here. this will be overrided by individual commands
Public Member Functions inherited from Command
Command ()
Command (const char *name)
virtual ~Command ()
void setTimeout (unsigned long timeout)
unsigned long getTime ()
bool isTimedOut ()
virtual void _initialize ()
virtual void _execute ()
virtual void end ()
called once at the end, once isFinished() returned true. this will be overrided by individual commands.
virtual void _end ()
bool cycle ()
actually does the excuting.
bool isRunning ()
check if the command is running.
bool operator!= (const Command &other)
comparator overload for !=. used when checking if command is in list
Private Attributes
const unsigned int BLINK_TIME = 50
AbstractMaze * maze
RealMouse * mouse
unsigned long t
uint8_t pin_id
bool on
Additional Inherited Members
Static Public Member Functions inherited from Command
static void setTimerImplementation (TimerInterface *timer)
static TimerInterface * getTimerImplementation ()
Public Attributes inherited from Command
bool inParallel
used by command group to organize commands
const char * name
for convenient printing
bool initialized
bool running
unsigned long timeout
unsigned long startTime
Static Public Attributes inherited from Command
static TimerInterface * timer
Constructor & Destructor Documentation
Finish::Finish (AbstractMaze * maze)
Finish::Finish (AbstractMaze * maze)
Finish::Finish (AbstractMaze * maze)
Member Function Documentation
void Finish::execute () virtual
stuff to do over and over each iteration. this will be overrided by individual commands
Reimplemented from Command.
References BLINK_TIME, Command::getTime(), RealMouse::LED_1, RealMouse::LED_8, on, pin_id, and t.
void Finish::initialize () virtual
run once in the first iteration of the command's life. this will be overrided by individual commands
Reimplemented from Command.
void Finish::initialize () virtual
run once in the first iteration of the command's life. this will be overrided by individual commands
Reimplemented from Command.
void Finish::initialize () virtual
run once in the first iteration of the command's life. this will be overrided by individual commands
Reimplemented from Command.
References Command::getTime(), RealMouse::LED_1, mouse, on, pin_id, RealMouse::setSpeedCps(), Command::setTimeout(), and t.
bool Finish::isFinished () virtual
checked every iteration to see if we're done here. this will be overrided by individual commands
Returns
is the function finished
Implements Command.
bool Finish::isFinished () virtual
checked every iteration to see if we're done here. this will be overrided by individual commands
Returns
is the function finished
Implements Command.
bool Finish::isFinished () virtual
checked every iteration to see if we're done here. this will be overrided by individual commands
Returns
is the function finished
Implements Command.
References Command::isTimedOut().
Member Data Documentation
const unsigned int Finish::BLINK_TIME = 50 private
Referenced by execute().
AbstractMaze * Finish::maze private
RealMouse* Finish::mouse private
Referenced by initialize().
bool Finish::on private
Referenced by execute(), and initialize().
uint8_t Finish::pin_id private
Referenced by execute(), and initialize().
unsigned long Finish::t private
Referenced by execute(), and initialize().
The documentation for this class was generated from the following files:
real/commands/Finish.h
real/commands/Finish.cpp