SmartMouse_2018: Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false > Class Template Reference
Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false > Class Template Reference
#include <GeneralBlockPanelKernel.h>
Public Types
enum {
ConjLhs = _ConjLhs, ConjRhs = false, Vectorizable = packet_traits<LhsScalar>::Vectorizable && packet_traits<RhsScalar>::Vectorizable, LhsPacketSize = Vectorizable ? packet_traits<LhsScalar>::size : 1,
RhsPacketSize = Vectorizable ? packet_traits<RhsScalar>::size : 1, ResPacketSize = Vectorizable ? packet_traits<ResScalar>::size : 1, NumberOfRegisters = EIGEN_ARCH_DEFAULT_NUMBER_OF_REGISTERS, nr = 4,
mr = (EIGEN_PLAIN_ENUM_MIN(16,NumberOfRegisters)/2/nr)*LhsPacketSize, LhsProgress = LhsPacketSize, RhsProgress = 1
}
typedef std::complex< RealScalar > LhsScalar
typedef RealScalar RhsScalar
typedef ScalarBinaryOpTraits< LhsScalar, RhsScalar >::ReturnType ResScalar
typedef packet_traits< LhsScalar >::type _LhsPacket
typedef packet_traits< RhsScalar >::type _RhsPacket
typedef packet_traits< ResScalar >::type _ResPacket
typedef conditional< Vectorizable, _LhsPacket, LhsScalar >::type LhsPacket
typedef conditional< Vectorizable, _RhsPacket, RhsScalar >::type RhsPacket
typedef conditional< Vectorizable, _ResPacket, ResScalar >::type ResPacket
typedef ResPacket AccPacket
Public Member Functions
EIGEN_STRONG_INLINE void initAcc (AccPacket &p)
EIGEN_STRONG_INLINE void loadRhs (const RhsScalar *b, RhsPacket &dest) const
EIGEN_STRONG_INLINE void loadRhsQuad (const RhsScalar *b, RhsPacket &dest) const
EIGEN_STRONG_INLINE void loadLhs (const LhsScalar *a, LhsPacket &dest) const
EIGEN_STRONG_INLINE void loadLhsUnaligned (const LhsScalar *a, LhsPacket &dest) const
EIGEN_STRONG_INLINE void broadcastRhs (const RhsScalar *b, RhsPacket &b0, RhsPacket &b1, RhsPacket &b2, RhsPacket &b3)
EIGEN_STRONG_INLINE void madd (const LhsPacket &a, const RhsPacket &b, AccPacket &c, RhsPacket &tmp) const
EIGEN_STRONG_INLINE void madd_impl (const LhsPacket &a, const RhsPacket &b, AccPacket &c, RhsPacket &tmp, const true_type &) const
EIGEN_STRONG_INLINE void madd_impl (const LhsScalar &a, const RhsScalar &b, ResScalar &c, RhsScalar &, const false_type &) const
EIGEN_STRONG_INLINE void acc (const AccPacket &c, const ResPacket &alpha, ResPacket &r) const
Protected Attributes
conj_helper< ResPacket, ResPacket, ConjLhs, false > cj
Member Typedef Documentation
template<typename RealScalar , bool _ConjLhs> typedef packet_traits<LhsScalar>::type Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::_LhsPacket
template<typename RealScalar , bool _ConjLhs> typedef packet_traits<ResScalar>::type Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::_ResPacket
template<typename RealScalar , bool _ConjLhs> typedef packet_traits<RhsScalar>::type Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::_RhsPacket
template<typename RealScalar , bool _ConjLhs> typedef ResPacket Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::AccPacket
template<typename RealScalar , bool _ConjLhs> typedef conditional<Vectorizable,_LhsPacket,LhsScalar>::type Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::LhsPacket
template<typename RealScalar , bool _ConjLhs> typedef std::complex<RealScalar> Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::LhsScalar
template<typename RealScalar , bool _ConjLhs> typedef conditional<Vectorizable,_ResPacket,ResScalar>::type Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::ResPacket
template<typename RealScalar , bool _ConjLhs> typedef ScalarBinaryOpTraits<LhsScalar, RhsScalar>::ReturnType Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::ResScalar
template<typename RealScalar , bool _ConjLhs> typedef conditional<Vectorizable,_RhsPacket,RhsScalar>::type Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::RhsPacket
template<typename RealScalar , bool _ConjLhs> typedef RealScalar Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::RhsScalar
Member Enumeration Documentation
template<typename RealScalar , bool _ConjLhs> anonymous enum
Enumerator
ConjLhs
ConjRhs
Vectorizable
LhsPacketSize
RhsPacketSize
ResPacketSize
NumberOfRegisters
nr
mr
LhsProgress
RhsProgress
Member Function Documentation
template<typename RealScalar , bool _ConjLhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::acc (const AccPacket & c, const ResPacket & alpha, ResPacket & r) const inline
template<typename RealScalar , bool _ConjLhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::broadcastRhs (const RhsScalar * b, RhsPacket & b0, RhsPacket & b1, RhsPacket & b2, RhsPacket & b3) inline
References Eigen::internal::pbroadcast4().
template<typename RealScalar , bool _ConjLhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::initAcc (AccPacket & p) inline
template<typename RealScalar , bool _ConjLhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::loadLhs (const LhsScalar * a, LhsPacket & dest) const inline
template<typename RealScalar , bool _ConjLhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::loadLhsUnaligned (const LhsScalar * a, LhsPacket & dest) const inline
template<typename RealScalar , bool _ConjLhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::loadRhs (const RhsScalar * b, RhsPacket & dest) const inline
template<typename RealScalar , bool _ConjLhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::loadRhsQuad (const RhsScalar * b, RhsPacket & dest) const inline
template<typename RealScalar , bool _ConjLhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::madd (const LhsPacket & a, const RhsPacket & b, AccPacket & c, RhsPacket & tmp) const inline
template<typename RealScalar , bool _ConjLhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::madd_impl (const LhsPacket & a, const RhsPacket & b, AccPacket & c, RhsPacket & tmp, const true_type &) const inline
References EIGEN_UNUSED_VARIABLE, Eigen::internal::padd(), Eigen::internal::pmadd(), and Eigen::internal::pmul().
template<typename RealScalar , bool _ConjLhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::madd_impl (const LhsScalar & a, const RhsScalar & b, ResScalar & c, RhsScalar & , const false_type &) const inline
Member Data Documentation
template<typename RealScalar , bool _ConjLhs> conj_helper<ResPacket,ResPacket,ConjLhs,false> Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::cj protected
The documentation for this class was generated from the following file:
GeneralBlockPanelKernel.h