SmartMouse_2018: Eigen::Tridiagonalization< _MatrixType > Class Template Reference
Eigen::Tridiagonalization< _MatrixType > Class Template Reference
Tridiagonal decomposition of a selfadjoint matrix.
#include <Tridiagonalization.h>
Public Types
enum {
Size = MatrixType::RowsAtCompileTime, SizeMinusOne = Size == Dynamic ? Dynamic : (Size > 1 ? Size - 1 : 1), Options = MatrixType::Options, MaxSize = MatrixType::MaxRowsAtCompileTime,
MaxSizeMinusOne = MaxSize == Dynamic ? Dynamic : (MaxSize > 1 ? MaxSize - 1 : 1)
}
typedef _MatrixType MatrixType
Synonym for the template parameter _MatrixType.
typedef MatrixType::Scalar Scalar
typedef NumTraits< Scalar >::Real RealScalar
typedef Eigen::Index Index
typedef Matrix< Scalar, SizeMinusOne, 1, Options &~RowMajor, MaxSizeMinusOne, 1 > CoeffVectorType
typedef internal::plain_col_type< MatrixType, RealScalar >::type DiagonalType
typedef Matrix< RealScalar, SizeMinusOne, 1, Options &~RowMajor, MaxSizeMinusOne, 1 > SubDiagonalType
typedef internal::remove_all< typename MatrixType::RealReturnType >::type MatrixTypeRealView
typedef internal::TridiagonalizationMatrixTReturnType< MatrixTypeRealView > MatrixTReturnType
typedef internal::conditional< NumTraits< Scalar >::IsComplex, typename internal::add_const_on_value_type< typename Diagonal< const MatrixType >::RealReturnType >::type, const Diagonal< const MatrixType > >::type DiagonalReturnType
typedef internal::conditional< NumTraits< Scalar >::IsComplex, typename internal::add_const_on_value_type< typename Diagonal< const MatrixType,-1 >::RealReturnType >::type, const Diagonal< const MatrixType,-1 > >::type SubDiagonalReturnType
typedef HouseholderSequence< MatrixType, typename internal::remove_all< typename CoeffVectorType::ConjugateReturnType >::type > HouseholderSequenceType
Return type of matrixQ()
Public Member Functions
Tridiagonalization (Index size=Size==Dynamic?2:Size)
Default constructor.
template<typename InputType >
Tridiagonalization (const EigenBase< InputType > &matrix)
Constructor; computes tridiagonal decomposition of given matrix.
template<typename InputType >
Tridiagonalization & compute (const EigenBase< InputType > &matrix)
Computes tridiagonal decomposition of given matrix.
CoeffVectorType householderCoefficients () const
Returns the Householder coefficients.
const MatrixType & packedMatrix () const
Returns the internal representation of the decomposition.
HouseholderSequenceType matrixQ () const
Returns the unitary matrix Q in the decomposition.
MatrixTReturnType matrixT () const
Returns an expression of the tridiagonal matrix T in the decomposition.
DiagonalReturnType diagonal () const
Returns the diagonal of the tridiagonal matrix T in the decomposition.
SubDiagonalReturnType subDiagonal () const
Returns the subdiagonal of the tridiagonal matrix T in the decomposition.
Protected Attributes
MatrixType m_matrix
CoeffVectorType m_hCoeffs
bool m_isInitialized
Detailed Description
template<typename _MatrixType>
class Eigen::Tridiagonalization< _MatrixType >
Tridiagonal decomposition of a selfadjoint matrix.
Template Parameters
_MatrixType the type of the matrix of which we are computing the tridiagonal decomposition; this is expected to be an instantiation of the Matrix class template.
This class performs a tridiagonal decomposition of a selfadjoint matrix such that: where is unitary and a real symmetric tridiagonal matrix.
A tridiagonal matrix is a matrix which has nonzero elements only on the main diagonal and the first diagonal below and above it. The Hessenberg decomposition of a selfadjoint matrix is in fact a tridiagonal decomposition. This class is used in SelfAdjointEigenSolver to compute the eigenvalues and eigenvectors of a selfadjoint matrix.
Call the function compute() to compute the tridiagonal decomposition of a given matrix. Alternatively, you can use the Tridiagonalization(const MatrixType&) constructor which computes the tridiagonal Schur decomposition at construction time. Once the decomposition is computed, you can use the matrixQ() and matrixT() functions to retrieve the matrices Q and T in the decomposition.
The documentation of Tridiagonalization(const MatrixType&) contains an example of the typical use of this class.
See also
class HessenbergDecomposition, class SelfAdjointEigenSolver
Member Typedef Documentation
template<typename _MatrixType> typedef Matrix<Scalar, SizeMinusOne, 1, Options & ~RowMajor, MaxSizeMinusOne, 1> Eigen::Tridiagonalization< _MatrixType >::CoeffVectorType
template<typename _MatrixType> typedef internal::conditional<NumTraits<Scalar>::IsComplex, typename internal::add_const_on_value_type<typename Diagonal<const MatrixType>::RealReturnType>::type, const Diagonal<const MatrixType> >::type Eigen::Tridiagonalization< _MatrixType >::DiagonalReturnType
template<typename _MatrixType> typedef internal::plain_col_type<MatrixType, RealScalar>::type Eigen::Tridiagonalization< _MatrixType >::DiagonalType
template<typename _MatrixType> typedef HouseholderSequence<MatrixType,typename internal::remove_all<typename CoeffVectorType::ConjugateReturnType>::type> Eigen::Tridiagonalization< _MatrixType >::HouseholderSequenceType
Return type of matrixQ()
template<typename _MatrixType> typedef Eigen::Index Eigen::Tridiagonalization< _MatrixType >::Index
Deprecated:
since Eigen 3.3
template<typename _MatrixType> typedef internal::TridiagonalizationMatrixTReturnType<MatrixTypeRealView> Eigen::Tridiagonalization< _MatrixType >::MatrixTReturnType
template<typename _MatrixType> typedef _MatrixType Eigen::Tridiagonalization< _MatrixType >::MatrixType
Synonym for the template parameter _MatrixType.
template<typename _MatrixType> typedef internal::remove_all<typename MatrixType::RealReturnType>::type Eigen::Tridiagonalization< _MatrixType >::MatrixTypeRealView
template<typename _MatrixType> typedef NumTraits<Scalar>::Real Eigen::Tridiagonalization< _MatrixType >::RealScalar
template<typename _MatrixType> typedef MatrixType::Scalar Eigen::Tridiagonalization< _MatrixType >::Scalar
template<typename _MatrixType> typedef internal::conditional<NumTraits<Scalar>::IsComplex, typename internal::add_const_on_value_type<typename Diagonal<const MatrixType, -1>::RealReturnType>::type, const Diagonal<const MatrixType, -1> >::type Eigen::Tridiagonalization< _MatrixType >::SubDiagonalReturnType
template<typename _MatrixType> typedef Matrix<RealScalar, SizeMinusOne, 1, Options & ~RowMajor, MaxSizeMinusOne, 1> Eigen::Tridiagonalization< _MatrixType >::SubDiagonalType
Member Enumeration Documentation
template<typename _MatrixType> anonymous enum
Enumerator
Size
SizeMinusOne
Options
MaxSize
MaxSizeMinusOne
Constructor & Destructor Documentation
template<typename _MatrixType> Eigen::Tridiagonalization< _MatrixType >::Tridiagonalization (Index size = Size==Dynamic ? 2 : Size) inline explicit
Default constructor.
Parameters
[in] size Positive integer, size of the matrix whose tridiagonal decomposition will be computed.
The default constructor is useful in cases in which the user intends to perform decompositions via compute(). The size parameter is only used as a hint. It is not an error to give a wrong size, but it may impair performance.
See also
compute() for an example.
template<typename _MatrixType> template<typename InputType > Eigen::Tridiagonalization< _MatrixType >::Tridiagonalization (const EigenBase< InputType > & matrix) inline explicit
Constructor; computes tridiagonal decomposition of given matrix.
Parameters
[in] matrix Selfadjoint matrix whose tridiagonal decomposition is to be computed.
This constructor calls compute() to compute the tridiagonal decomposition.
Example:
Output:
References Eigen::internal::tridiagonalization_inplace().
Member Function Documentation
template<typename _MatrixType> template<typename InputType > Tridiagonalization& Eigen::Tridiagonalization< _MatrixType >::compute (const EigenBase< InputType > & matrix) inline
Computes tridiagonal decomposition of given matrix.
Parameters
[in] matrix Selfadjoint matrix whose tridiagonal decomposition is to be computed.
Returns
Reference to *this
The tridiagonal decomposition is computed by bringing the columns of the matrix successively in the required form using Householder reflections. The cost is flops, where denotes the size of the given matrix.
This method reuses of the allocated data in the Tridiagonalization object, if the size of the matrix does not change.
Example:
Output:
References Eigen::EigenBase< Derived >::derived(), Eigen::EigenBase< Derived >::rows(), and Eigen::internal::tridiagonalization_inplace().
template<typename MatrixType > Tridiagonalization< MatrixType >::DiagonalReturnType Eigen::Tridiagonalization< MatrixType >::diagonal () const
Returns the diagonal of the tridiagonal matrix T in the decomposition.
Returns
expression representing the diagonal of T
Precondition
Either the constructor Tridiagonalization(const MatrixType&) or the member function compute(const MatrixType&) has been called before to compute the tridiagonal decomposition of a matrix.
Example:
Output:
See also
matrixT(), subDiagonal()
References eigen_assert.
template<typename _MatrixType> CoeffVectorType Eigen::Tridiagonalization< _MatrixType >::householderCoefficients () const inline
Returns the Householder coefficients.
Returns
a const reference to the vector of Householder coefficients
Precondition
Either the constructor Tridiagonalization(const MatrixType&) or the member function compute(const MatrixType&) has been called before to compute the tridiagonal decomposition of a matrix.
The Householder coefficients allow the reconstruction of the matrix in the tridiagonal decomposition from the packed data.
Example:
Output:
See also
packedMatrix(), Householder module
References eigen_assert.
template<typename _MatrixType> HouseholderSequenceType Eigen::Tridiagonalization< _MatrixType >::matrixQ () const inline
Returns the unitary matrix Q in the decomposition.
Returns
object representing the matrix Q
Precondition
Either the constructor Tridiagonalization(const MatrixType&) or the member function compute(const MatrixType&) has been called before to compute the tridiagonal decomposition of a matrix.
This function returns a light-weight object of template class HouseholderSequence. You can either apply it directly to a matrix or you can convert it to a matrix of type MatrixType.
See also
Tridiagonalization(const MatrixType&) for an example, matrixT(), class HouseholderSequence
References eigen_assert.
template<typename _MatrixType> MatrixTReturnType Eigen::Tridiagonalization< _MatrixType >::matrixT () const inline
Returns an expression of the tridiagonal matrix T in the decomposition.
Returns
expression object representing the matrix T
Precondition
Either the constructor Tridiagonalization(const MatrixType&) or the member function compute(const MatrixType&) has been called before to compute the tridiagonal decomposition of a matrix.
Currently, this function can be used to extract the matrix T from internal data and copy it to a dense matrix object. In most cases, it may be sufficient to directly use the packed matrix or the vector expressions returned by diagonal() and subDiagonal() instead of creating a new dense copy matrix with this function.
See also
Tridiagonalization(const MatrixType&) for an example, matrixQ(), packedMatrix(), diagonal(), subDiagonal()
References eigen_assert.
template<typename _MatrixType> const MatrixType& Eigen::Tridiagonalization< _MatrixType >::packedMatrix () const inline
Returns the internal representation of the decomposition.
Returns
a const reference to a matrix with the internal representation of the decomposition.
Precondition
Either the constructor Tridiagonalization(const MatrixType&) or the member function compute(const MatrixType&) has been called before to compute the tridiagonal decomposition of a matrix.
The returned matrix contains the following information:
the strict upper triangular part is equal to the input matrix A.
the diagonal and lower sub-diagonal represent the real tridiagonal symmetric matrix T.
the rest of the lower part contains the Householder vectors that, combined with Householder coefficients returned by householderCoefficients(), allows to reconstruct the matrix Q as . Here, the matrices are the Householder transformations where is the th Householder coefficient and is the Householder vector defined by with M the matrix returned by this function.
See LAPACK for further details on this packed storage.
Example:
Output:
See also
householderCoefficients()
References eigen_assert.
template<typename MatrixType > Tridiagonalization< MatrixType >::SubDiagonalReturnType Eigen::Tridiagonalization< MatrixType >::subDiagonal () const
Returns the subdiagonal of the tridiagonal matrix T in the decomposition.
Returns
expression representing the subdiagonal of T
Precondition
Either the constructor Tridiagonalization(const MatrixType&) or the member function compute(const MatrixType&) has been called before to compute the tridiagonal decomposition of a matrix.
See also
diagonal() for an example, matrixT()
References eigen_assert, and real().
Member Data Documentation
template<typename _MatrixType> CoeffVectorType Eigen::Tridiagonalization< _MatrixType >::m_hCoeffs protected
template<typename _MatrixType> bool Eigen::Tridiagonalization< _MatrixType >::m_isInitialized protected
template<typename _MatrixType> MatrixType Eigen::Tridiagonalization< _MatrixType >::m_matrix protected
The documentation for this class was generated from the following file:
Tridiagonalization.h