SmartMouse_2018: Mouse Class Reference
Mouse Class Reference abstract
depresents a mouse don't ever change the row/col of a mouse directly. This prevents it from working on the real robot use forward and turnToFace to move the mouse around. Once those functions work on the real robot it will port over fluidly
#include <Mouse.h>
Public Member Functions
Mouse ()
Mouse (AbstractMaze *maze)
Mouse (unsigned int starting_row, unsigned int starting_col)
Mouse (AbstractMaze *maze, unsigned int starting_row, unsigned int starting_col)
void reset ()
unsigned int getCol ()
return the current column. Guaranteed to be between 0 and MAZE_SIZE
unsigned int getRow ()
return the current row. Guaranteed to be between 0 and MAZE_SIZE
Direction getDir ()
return the current direction.
bool inBounds ()
bool atCenter ()
is the mouse at the center of the maze?
void mark_mouse_position_visited ()
void internalTurnToFace (Direction dir)
void internalForward ()
void print_maze_mouse ()
void maze_mouse_string (char *)
virtual SensorReading checkWalls ()=0
bool isWallInDirection (Direction d)
virtual GlobalPose getGlobalPose ()=0
virtual LocalPose getLocalPose ()=0
Public Attributes
AbstractMaze * maze
Protected Attributes
unsigned int row
unsigned int col
Direction dir
Detailed Description
depresents a mouse don't ever change the row/col of a mouse directly. This prevents it from working on the real robot use forward and turnToFace to move the mouse around. Once those functions work on the real robot it will port over fluidly
Constructor & Destructor Documentation
Mouse::Mouse ()
References E.
Mouse::Mouse (AbstractMaze * maze)
Mouse::Mouse (unsigned int starting_row, unsigned int starting_col)
Mouse::Mouse (AbstractMaze * maze, unsigned int starting_row, unsigned int starting_col)
Member Function Documentation
bool Mouse::atCenter ()
is the mouse at the center of the maze?
References smartmouse::maze::CENTER, col, and row.
virtual SensorReading Mouse::checkWalls () pure virtual
Implemented in RealMouse, SimMouse, and ConsoleMouse.
Referenced by WallFollow::planNextStep(), and Flood::planNextStep().
unsigned int Mouse::getCol ()
return the current column. Guaranteed to be between 0 and MAZE_SIZE
Returns
current column
References col.
Referenced by KinematicController::dispToNextEdge(), ArcTurn::initialize(), SpeedRun::isFinished(), ReturnToStart::isFinished(), ArcTurn::isFinished(), WallFollow::isFinished(), Flood::isFinished(), and Flood::planNextStep().
Direction Mouse::getDir ()
return the current direction.
Returns
current direction
References dir.
Referenced by smartmouse::kc::DriveStraightState::compute_wheel_velocities(), KinematicController::dispToNextEdge(), KinematicController::estimate_pose(), KinematicController::getLocalPose(), Turn::initialize(), ArcTurn::initialize(), SolveMaze::isFinished(), ArcTurn::isFinished(), WallFollow::planNextStep(), Flood::planNextStep(), and KinematicController::run().
virtual GlobalPose Mouse::getGlobalPose () pure virtual
Implemented in RealMouse, SimMouse, and ConsoleMouse.
Referenced by smartmouse::kc::DriveStraightState::compute_wheel_velocities(), KinematicController::dispToNextEdge(), and KinematicController::poseOfToNthEdge().
virtual LocalPose Mouse::getLocalPose () pure virtual
Implemented in RealMouse, SimMouse, and ConsoleMouse.
Referenced by KinematicController::fwdDispToCenter(), and KinematicController::sidewaysDispToCenter().
unsigned int Mouse::getRow ()
return the current row. Guaranteed to be between 0 and MAZE_SIZE
Returns
current row
References row.
Referenced by KinematicController::dispToNextEdge(), ArcTurn::initialize(), SpeedRun::isFinished(), ReturnToStart::isFinished(), ArcTurn::isFinished(), WallFollow::isFinished(), Flood::isFinished(), and Flood::planNextStep().
bool Mouse::inBounds ()
check if we're in bounds
References col, row, and smartmouse::maze::SIZE.
void Mouse::internalForward ()
References col, dir, E, N, row, S, and W.
Referenced by main(), WallFollow::solve(), and Flood::solve().
void Mouse::internalTurnToFace (Direction dir)
References dir.
Referenced by TurnInPlace::end(), ArcTurn::end(), main(), WallFollow::solve(), and Flood::solve().
bool Mouse::isWallInDirection (Direction d)
doesn't simply read sensors. Check the internal maze structure
References col, AbstractMaze::get_node(), maze, Node::neighbor(), and row.
Referenced by KinematicController::estimate_pose().
void Mouse::mark_mouse_position_visited ()
References col, maze, AbstractMaze::nodes, row, and Node::visited.
Referenced by WallFollow::planNextStep().
void Mouse::maze_mouse_string (char * buff)
creates one long string of the mouse in the maze in ascii
References col, dir, E, i, maze, N, Node::neighbor(), AbstractMaze::nodes, NULL, row, S, smartmouse::maze::SIZE, and W.
Referenced by print_maze_mouse().
void Mouse::print_maze_mouse ()
prints a maze with a mouse in it
References smartmouse::maze::BUFF_SIZE, maze_mouse_string(), and print().
Referenced by ReturnToStart::isFinished(), SpeedRun::isFinished(), and main().
void Mouse::reset ()
References col, dir, E, and row.
Referenced by SimMouse::resetToStartPose(), RealMouse::resetToStartPose(), WallFollow::setup(), and Flood::setup().
Member Data Documentation
unsigned int Mouse::col protected
Referenced by atCenter(), ConsoleMouse::checkWalls(), SimMouse::checkWalls(), RealMouse::checkWalls(), getCol(), ConsoleMouse::getGlobalPose(), inBounds(), internalForward(), isWallInDirection(), mark_mouse_position_visited(), maze_mouse_string(), reset(), SimMouse::run(), and RealMouse::run().
Direction Mouse::dir protected
Referenced by SimMouse::checkWalls(), RealMouse::checkWalls(), getDir(), ConsoleMouse::getGlobalPose(), ConsoleMouse::getLocalPose(), internalForward(), internalTurnToFace(), maze_mouse_string(), reset(), and SimMouse::SimMouse().
AbstractMaze* Mouse::maze
Referenced by SolveCommand::initialize(), ReturnToStart::initialize(), SpeedRun::initialize(), SolveCommand::isFinished(), isWallInDirection(), mark_mouse_position_visited(), maze_mouse_string(), Flood::planNextStep(), ConsoleMouse::seedMaze(), WallFollow::setup(), Flood::setup(), WallFollow::solve(), and Flood::teardown().
unsigned int Mouse::row protected
Referenced by atCenter(), ConsoleMouse::checkWalls(), SimMouse::checkWalls(), RealMouse::checkWalls(), ConsoleMouse::getGlobalPose(), getRow(), inBounds(), internalForward(), isWallInDirection(), mark_mouse_position_visited(), maze_mouse_string(), reset(), SimMouse::run(), and RealMouse::run().
The documentation for this class was generated from the following files:
Mouse.h
Mouse.cpp