SmartMouse_2018: Eigen::LeastSquareDiagonalPreconditioner< _Scalar > Class Template Reference
Eigen::LeastSquareDiagonalPreconditioner< _Scalar > Class Template Reference
Jacobi preconditioner for LeastSquaresConjugateGradient.
#include <BasicPreconditioners.h>
Public Member Functions
LeastSquareDiagonalPreconditioner ()
template<typename MatType >
LeastSquareDiagonalPreconditioner (const MatType &mat)
template<typename MatType >
LeastSquareDiagonalPreconditioner & analyzePattern (const MatType &)
template<typename MatType >
LeastSquareDiagonalPreconditioner & factorize (const MatType &mat)
template<typename MatType >
LeastSquareDiagonalPreconditioner & compute (const MatType &mat)
ComputationInfo info ()
Public Member Functions inherited from Eigen::DiagonalPreconditioner< _Scalar >
DiagonalPreconditioner ()
template<typename MatType >
DiagonalPreconditioner (const MatType &mat)
Index rows () const
Index cols () const
template<typename MatType >
DiagonalPreconditioner & analyzePattern (const MatType &)
template<typename MatType >
DiagonalPreconditioner & factorize (const MatType &mat)
template<typename MatType >
DiagonalPreconditioner & compute (const MatType &mat)
template<typename Rhs , typename Dest >
void _solve_impl (const Rhs &b, Dest &x) const
template<typename Rhs >
const Solve< DiagonalPreconditioner, Rhs > solve (const MatrixBase< Rhs > &b) const
ComputationInfo info ()
Private Types
typedef _Scalar Scalar
typedef NumTraits< Scalar >::Real RealScalar
typedef DiagonalPreconditioner< _Scalar > Base
Additional Inherited Members
Public Types inherited from Eigen::DiagonalPreconditioner< _Scalar >
enum { ColsAtCompileTime = Dynamic, MaxColsAtCompileTime = Dynamic }
typedef Vector::StorageIndex StorageIndex
Protected Attributes inherited from Eigen::DiagonalPreconditioner< _Scalar >
Vector m_invdiag
bool m_isInitialized
Detailed Description
template<typename _Scalar>
class Eigen::LeastSquareDiagonalPreconditioner< _Scalar >
Jacobi preconditioner for LeastSquaresConjugateGradient.
This class allows to approximately solve for A' A x = A' b problems assuming A' A is a diagonal matrix. In other words, this preconditioner neglects all off diagonal entries and, in Eigen's language, solves for:
(A.adjoint() * A).diagonal().asDiagonal() * x = b
Template Parameters
_Scalar the type of the scalar.
The diagonal entries are pre-inverted and stored into a dense vector.
See also
class LeastSquaresConjugateGradient, class DiagonalPreconditioner
Member Typedef Documentation
template<typename _Scalar > typedef DiagonalPreconditioner<_Scalar> Eigen::LeastSquareDiagonalPreconditioner< _Scalar >::Base private
template<typename _Scalar > typedef NumTraits<Scalar>::Real Eigen::LeastSquareDiagonalPreconditioner< _Scalar >::RealScalar private
template<typename _Scalar > typedef _Scalar Eigen::LeastSquareDiagonalPreconditioner< _Scalar >::Scalar private
Constructor & Destructor Documentation
template<typename _Scalar > Eigen::LeastSquareDiagonalPreconditioner< _Scalar >::LeastSquareDiagonalPreconditioner () inline
template<typename _Scalar > template<typename MatType > Eigen::LeastSquareDiagonalPreconditioner< _Scalar >::LeastSquareDiagonalPreconditioner (const MatType & mat) inline explicit
References Eigen::DiagonalPreconditioner< _Scalar >::compute().
Member Function Documentation
template<typename _Scalar > template<typename MatType > LeastSquareDiagonalPreconditioner& Eigen::LeastSquareDiagonalPreconditioner< _Scalar >::analyzePattern (const MatType &) inline
template<typename _Scalar > template<typename MatType > LeastSquareDiagonalPreconditioner& Eigen::LeastSquareDiagonalPreconditioner< _Scalar >::compute (const MatType & mat) inline
References Eigen::DiagonalPreconditioner< _Scalar >::factorize().
template<typename _Scalar > template<typename MatType > LeastSquareDiagonalPreconditioner& Eigen::LeastSquareDiagonalPreconditioner< _Scalar >::factorize (const MatType & mat) inline
References abs2(), it, Eigen::DiagonalPreconditioner< _Scalar >::m_invdiag, real(), Eigen::PlainObjectBase< Derived >::resize(), and Eigen::PlainObjectBase< Derived >::setZero().
template<typename _Scalar > ComputationInfo Eigen::LeastSquareDiagonalPreconditioner< _Scalar >::info () inline
References Eigen::Success.
The documentation for this class was generated from the following file:
BasicPreconditioners.h