SmartMouse_2018: Encoder Class Reference
Encoder Class Reference
#include <Encoder.h>
Public Member Functions
void init (uint8_t pin1, uint8_t pin2)
int32_t read ()
void write (int32_t p)
Static Public Member Functions
static void update (Encoder_internal_state_t *arg)
Static Public Attributes
static Encoder_internal_state_t * interruptArgs [ENCODER_ARGLIST_SIZE]
Static Private Member Functions
static uint8_t attach_interrupt (uint8_t pin, Encoder_internal_state_t *state)
Private Attributes
Encoder_internal_state_t encoder
uint8_t interrupts_in_use
Member Function Documentation
static uint8_t Encoder::attach_interrupt (uint8_t pin, Encoder_internal_state_t * state) inline static private
References interruptArgs, and update().
Referenced by init().
void Encoder::init (uint8_t pin1, uint8_t pin2) inline
References attach_interrupt(), encoder, interrupts_in_use, Encoder_internal_state_t::pin1_bitmask, Encoder_internal_state_t::pin1_register, Encoder_internal_state_t::pin2_bitmask, Encoder_internal_state_t::pin2_register, Encoder_internal_state_t::position, and Encoder_internal_state_t::state.
Referenced by RealMouse::setup().
int32_t Encoder::read () inline
References encoder, interrupts_in_use, Encoder_internal_state_t::position, and update().
Referenced by WaitForStart::execute(), WaitForStart::initialize(), loop(), RealMouse::resetToStartPose(), RealMouse::run(), and write().
static void Encoder::update (Encoder_internal_state_t * arg) inline static
References arg(), Encoder_internal_state_t::pin1_bitmask, Encoder_internal_state_t::pin1_register, Encoder_internal_state_t::pin2_bitmask, Encoder_internal_state_t::pin2_register, Encoder_internal_state_t::position, and Encoder_internal_state_t::state.
Referenced by attach_interrupt(), read(), and write().
void Encoder::write (int32_t p) inline
References encoder, Encoder_internal_state_t::position, read(), and update().
Member Data Documentation
Encoder_internal_state_t Encoder::encoder private
Referenced by init(), read(), and write().
Encoder_internal_state_t * Encoder::interruptArgs static
Referenced by attach_interrupt().
uint8_t Encoder::interrupts_in_use private
Referenced by init(), and read().
The documentation for this class was generated from the following files:
Encoder.h
Encoder.cpp