SmartMouse_2018: ControlPlotWidget Class Reference
ControlPlotWidget Class Reference
#include <ControlPlotWidget.h>
Signals
void Replot ()
Public Member Functions
ControlPlotWidget ()
void Clear ()
const QString GetTabName () override
void ControlCallback (const smartmouse::msgs::RobotCommand &msg)
Private Slots
void LeftChecked ()
void RightChecked ()
Private Attributes
Ui::ControlPlotWidget * ui_
ignition::transport::Node node_
QwtPlot * plot_
PlotSeriesData * left_actual_
PlotSeriesData * right_actual_
const unsigned int capacity_
Constructor & Destructor Documentation
ControlPlotWidget::ControlPlotWidget ()
References PlotSeriesData::Attach(), capacity_, Clear(), ControlCallback(), TopicNames::kRobotCommand, left_actual_, LeftChecked(), node_, plot_, Replot(), right_actual_, RightChecked(), and ui_.
Member Function Documentation
void ControlPlotWidget::Clear ()
References PlotSeriesData::Clear(), left_actual_, and right_actual_.
Referenced by ControlPlotWidget().
void ControlPlotWidget::ControlCallback (const smartmouse::msgs::RobotCommand & msg)
References PlotSeriesData::Append(), smartmouse::msgs::ConvertSec(), left_actual_, Replot(), and right_actual_.
Referenced by ControlPlotWidget().
const QString ControlPlotWidget::GetTabName () override virtual
Implements AbstractTab.
Referenced by StateWidget::StateWidget().
void ControlPlotWidget::LeftChecked () private slot
References PlotSeriesData::Attach(), PlotSeriesData::Hide(), left_actual_, plot_, and ui_.
Referenced by ControlPlotWidget().
void ControlPlotWidget::Replot () signal
Referenced by ControlCallback(), and ControlPlotWidget().
void ControlPlotWidget::RightChecked () private slot
References PlotSeriesData::Attach(), PlotSeriesData::Hide(), plot_, right_actual_, and ui_.
Referenced by ControlPlotWidget().
Member Data Documentation
const unsigned int ControlPlotWidget::capacity_ private
Referenced by ControlPlotWidget().
PlotSeriesData* ControlPlotWidget::left_actual_ private
Referenced by Clear(), ControlCallback(), ControlPlotWidget(), and LeftChecked().
ignition::transport::Node ControlPlotWidget::node_ private
Referenced by ControlPlotWidget().
QwtPlot* ControlPlotWidget::plot_ private
Referenced by ControlPlotWidget(), LeftChecked(), and RightChecked().
PlotSeriesData* ControlPlotWidget::right_actual_ private
Referenced by Clear(), ControlCallback(), ControlPlotWidget(), and RightChecked().
Ui::ControlPlotWidget* ControlPlotWidget::ui_ private
Referenced by ControlPlotWidget(), LeftChecked(), and RightChecked().
The documentation for this class was generated from the following files:
ControlPlotWidget.h
ControlPlotWidget.cpp