SmartMouse_2018: CommonCwiseUnaryOps.h File Reference
CommonCwiseUnaryOps.h File Reference
Classes
struct CastXpr< NewType >
Typedefs
typedef internal::conditional< NumTraits< Scalar >::IsComplex, const CwiseUnaryOp< internal::scalar_conjugate_op< Scalar >, const Derived >, const Derived & >::type ConjugateReturnType
typedef internal::conditional< NumTraits< Scalar >::IsComplex, const CwiseUnaryOp< internal::scalar_real_op< Scalar >, const Derived >, const Derived & >::type RealReturnType
typedef internal::conditional< NumTraits< Scalar >::IsComplex, CwiseUnaryView< internal::scalar_real_ref_op< Scalar >, Derived >, Derived & >::type NonConstRealReturnType
typedef CwiseUnaryOp< internal::scalar_imag_op< Scalar >, const Derived > ImagReturnType
typedef CwiseUnaryView< internal::scalar_imag_ref_op< Scalar >, Derived > NonConstImagReturnType
typedef CwiseUnaryOp< internal::scalar_opposite_op< Scalar >, const Derived > NegativeReturnType
Functions
EIGEN_DEVICE_FUNC const NegativeReturnType operator- () const
template<typename NewType >
EIGEN_DEVICE_FUNC CastXpr< NewType >::Type cast () const
EIGEN_DEVICE_FUNC ConjugateReturnType conjugate () const
EIGEN_DEVICE_FUNC RealReturnType real ()
EIGEN_DEVICE_FUNC const ImagReturnType imag ()
template<typename CustomUnaryOp >
EIGEN_DEVICE_FUNC const CwiseUnaryOp< CustomUnaryOp, const Derived > unaryExpr (const CustomUnaryOp &func=CustomUnaryOp()) const
Apply a unary operator coefficient-wise.
template<typename CustomViewOp >
EIGEN_DEVICE_FUNC const CwiseUnaryView< CustomViewOp, const Derived > unaryViewExpr (const CustomViewOp &func=CustomViewOp()) const
Typedef Documentation
typedef internal::conditional<NumTraits<Scalar>::IsComplex, const CwiseUnaryOp<internal::scalar_conjugate_op<Scalar>, const Derived>, const Derived& >::type ConjugateReturnType
typedef CwiseUnaryOp<internal::scalar_imag_op<Scalar>, const Derived> ImagReturnType
typedef CwiseUnaryOp<internal::scalar_opposite_op<Scalar>, const Derived> NegativeReturnType
typedef CwiseUnaryView<internal::scalar_imag_ref_op<Scalar>, Derived> NonConstImagReturnType
typedef internal::conditional<NumTraits<Scalar>::IsComplex, CwiseUnaryView<internal::scalar_real_ref_op<Scalar>, Derived>, Derived& >::type NonConstRealReturnType
typedef internal::conditional<NumTraits<Scalar>::IsComplex, const CwiseUnaryOp<internal::scalar_real_op<Scalar>, const Derived>, const Derived& >::type RealReturnType
Function Documentation
template<typename NewType > EIGEN_DEVICE_FUNC CastXpr<NewType>::Type cast () const
Returns
an expression of *this with the Scalar type casted to NewScalar.
The template parameter NewScalar is the type we are casting the scalars to.
See also
class CwiseUnaryOp
References conjugate(), and EIGEN_DOC_UNARY_ADDONS.
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::operator*(), and Eigen::operator*().
EIGEN_DEVICE_FUNC ConjugateReturnType conjugate () const inline
Returns
an expression of the complex conjugate of *this.
See also
Math functions, MatrixBase::adjoint()
References EIGEN_DOC_UNARY_ADDONS, and real().
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::adjoint(), cast(), Eigen::VectorwiseOp< ExpressionType, Direction >::cross(), Eigen::QuaternionBase< Quaternion< _Scalar, _Options > >::dot(), and Eigen::QuaternionBase< Derived >::inverse().
EIGEN_DEVICE_FUNC NonConstImagReturnType imag () const inline
Returns
an read-only expression of the imaginary part of *this.
See also
real()
Returns
a non const expression of the imaginary part of *this.
See also
real()
References EIGEN_DOC_UNARY_ADDONS, and unaryExpr().
Referenced by Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::compute(), Eigen::EigenSolver< _MatrixType >::doComputeEigenvectors(), Eigen::EigenSolver< _MatrixType >::eigenvectors(), Eigen::SparseQR< _MatrixType, _OrderingType >::factorize(), Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::loadRhs(), Eigen::MatrixBase< Derived >::makeHouseholder(), Eigen::internal::scalar_imag_op< Scalar >::operator()(), Eigen::internal::scalar_sign_op< Scalar, true >::operator()(), Eigen::internal::pcplxflip(), Eigen::internal::pgather< std::complex< double >, Packet2cd >(), Eigen::internal::pgather< std::complex< float >, Packet4cf >(), Eigen::internal::conj_helper< std::complex< RealScalar >, std::complex< RealScalar >, false, true >::pmul(), Eigen::internal::conj_helper< std::complex< RealScalar >, std::complex< RealScalar >, true, false >::pmul(), Eigen::internal::conj_helper< std::complex< RealScalar >, std::complex< RealScalar >, true, true >::pmul(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), Eigen::internal::pmul(), Eigen::EigenSolver< _MatrixType >::pseudoEigenvalueMatrix(), real(), Eigen::internal::trmv_selector< Mode, ColMajor >::run(), Eigen::internal::gemv_dense_selector< OnTheRight, ColMajor, true >::run(), Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::run(), and unaryViewExpr().
EIGEN_DEVICE_FUNC const NegativeReturnType operator- () const inline
Returns
an expression of the opposite of *this
EIGEN_DEVICE_FUNC NonConstRealReturnType real () const inline
Returns
a read-only expression of the real part of *this.
See also
imag()
Returns
a non const expression of the real part of *this.
See also
imag()
References EIGEN_DOC_UNARY_ADDONS, and imag().
Referenced by Eigen::GeneralizedEigenSolver< _MatrixType >::compute(), Eigen::SelfAdjointEigenSolver< _MatrixType >::compute(), Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::compute(), Eigen::ComplexSchur< _MatrixType >::computeShift(), conjugate(), Eigen::internal::conjugate_gradient(), Eigen::EigenSolver< _MatrixType >::doComputeEigenvectors(), Eigen::EigenSolver< _MatrixType >::eigenvectors(), Eigen::SparseQR< _MatrixType, _OrderingType >::factorize(), Eigen::LeastSquareDiagonalPreconditioner< _Scalar >::factorize(), Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::factorize(), Eigen::SimplicialCholeskyBase< Derived >::factorize_preordered(), Eigen::internal::least_square_conjugate_gradient(), Eigen::internal::llt_rank_update_lower(), Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::loadRhs(), Eigen::CholmodBase< _MatrixType, _UpLo, CholmodSimplicialLLT< _MatrixType, _UpLo > >::logDeterminant(), Eigen::JacobiRotation< Scalar >::makeGivens(), Eigen::MatrixBase< Derived >::makeHouseholder(), Eigen::JacobiRotation< Scalar >::makeJacobi(), Eigen::internal::symm_pack_lhs< Scalar, Index, Pack1, Pack2_dummy, StorageOrder >::operator()(), Eigen::internal::symm_pack_rhs< Scalar, Index, nr, StorageOrder >::operator()(), Eigen::internal::scalar_real_op< Scalar >::operator()(), Eigen::internal::scalar_sign_op< Scalar, true >::operator()(), Eigen::internal::symm_pack_lhs< Scalar, Index, Pack1, Pack2_dummy, StorageOrder >::pack(), Eigen::internal::pcplxflip(), Eigen::internal::pgather< std::complex< double >, Packet2cd >(), Eigen::internal::pgather< std::complex< float >, Packet4cf >(), Eigen::internal::conj_helper< std::complex< RealScalar >, std::complex< RealScalar >, false, true >::pmul(), Eigen::internal::conj_helper< std::complex< RealScalar >, std::complex< RealScalar >, true, false >::pmul(), Eigen::internal::conj_helper< std::complex< RealScalar >, std::complex< RealScalar >, true, true >::pmul(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), Eigen::internal::pmul(), Eigen::EigenSolver< _MatrixType >::pseudoEigenvalueMatrix(), Eigen::internal::real_2x2_jacobi_svd(), Eigen::internal::selfadjoint_matrix_vector_product< Scalar, Index, StorageOrder, UpLo, ConjugateLhs, ConjugateRhs, Version >::run(), Eigen::internal::get_factor< Scalar, typename NumTraits< Scalar >::Real >::run(), Eigen::internal::tridiagonalization_inplace_selector< MatrixType, Size, IsComplex >::run(), Eigen::internal::tridiagonalization_inplace_selector< MatrixType, 1, IsComplex >::run(), Eigen::MatrixBase< Derived >::squaredNorm(), Eigen::SparseMatrixBase< Derived >::squaredNorm(), Eigen::Tridiagonalization< _MatrixType >::subDiagonal(), unaryViewExpr(), Eigen::internal::ldlt_inplace< Lower >::unblocked(), Eigen::internal::llt_inplace< Scalar, Lower >::unblocked(), and Eigen::internal::ldlt_inplace< Lower >::updateInPlace().
template<typename CustomUnaryOp > EIGEN_DEVICE_FUNC const CwiseUnaryOp<CustomUnaryOp, const Derived> unaryExpr (const CustomUnaryOp & func = CustomUnaryOp()) const inline
Apply a unary operator coefficient-wise.
Parameters
[in] func Functor implementing the unary operator
Template Parameters
CustomUnaryOp Type of func
Returns
An expression of a custom coefficient-wise unary operator func of *this
The function ptr_fun() from the C++ standard library can be used to make functors out of normal functions.
Example:
Output:
Genuine functors allow for more possibilities, for instance it may contain a state.
Example:
Output:
See also
unaryViewExpr, binaryExpr, class CwiseUnaryOp
References EIGEN_DOC_UNARY_ADDONS, and unaryViewExpr().
Referenced by imag().
template<typename CustomViewOp > EIGEN_DEVICE_FUNC const CwiseUnaryView<CustomViewOp, const Derived> unaryViewExpr (const CustomViewOp & func = CustomViewOp()) const inline
Returns
an expression of a custom coefficient-wise unary operator func of *this
The template parameter CustomUnaryOp is the type of the functor of the custom unary operator.
Example:
Output:
See also
unaryExpr, binaryExpr class CwiseUnaryOp
References EIGEN_DOC_UNARY_ADDONS, imag(), and real().
Referenced by unaryExpr().