SmartMouse_2018: CommonTest.cpp File Reference
CommonTest.cpp File Reference
#include "gtest/gtest.h"
#include <common/KinematicController/KinematicController.h>
Functions
TEST (ForwardKinematicsTest, Forward_one_second)
TEST (ForwardKinematicsTest, Forward_tenth_second)
TEST (ForwardKinematicsTest, half_cw_turn_one_second)
TEST (ForwardKinematicsTest, half_ccw_turn_one_second)
TEST (ForwardKinematicsTest, cw_turn_one_second)
TEST (ForwardKinematicsTest, ccw_turn_one_second)
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
TEST (ForwardKinematicsTest , Forward_one_second)
References GlobalPose::col, KinematicController::forwardKinematics(), GlobalPose::row, and GlobalPose::yaw.
TEST (ForwardKinematicsTest , Forward_tenth_second)
References GlobalPose::col, KinematicController::forwardKinematics(), GlobalPose::row, and GlobalPose::yaw.
TEST (ForwardKinematicsTest , half_cw_turn_one_second)
References GlobalPose::col, e, KinematicController::forwardKinematics(), M_PI, GlobalPose::row, smartmouse::kc::TRACK_WIDTH_CU, and GlobalPose::yaw.
TEST (ForwardKinematicsTest , half_ccw_turn_one_second)
References GlobalPose::col, e, KinematicController::forwardKinematics(), M_PI, GlobalPose::row, smartmouse::kc::TRACK_WIDTH_CU, and GlobalPose::yaw.
TEST (ForwardKinematicsTest , cw_turn_one_second)
References GlobalPose::col, e, KinematicController::forwardKinematics(), M_PI, GlobalPose::row, smartmouse::kc::TRACK_WIDTH_CU, and GlobalPose::yaw.
TEST (ForwardKinematicsTest , ccw_turn_one_second)
References GlobalPose::col, e, KinematicController::forwardKinematics(), M_PI, GlobalPose::row, smartmouse::kc::TRACK_WIDTH_CU, and GlobalPose::yaw.