SmartMouse_2018: ConsoleSolve.cpp File Reference
ConsoleSolve.cpp File Reference
#include <fstream>
#include <iostream>
#include <common/commanduino/CommanDuino.h>
#include <common/commands/SolveCommand.h>
#include <console/ConsoleMouse.h>
#include <console/ConsoleTimer.h>
#include <common/core/Flood.h>
#include <cstring>
#include <common/core/util.h>
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
References AbstractMaze::gen_random_legal_maze(), GlobalProgramSettings, in, ConsoleMouse::inst(), Solver::isSolvable(), m, maze, global_program_settings_t::quiet, Scheduler::run(), scheduler, ConsoleMouse::seedMaze(), Command::setTimerImplementation(), and timer.