SmartMouse_2018: Direction.h File Reference
Direction.h File Reference
Enumerations
enum Direction {
Direction::N, Direction::E, Direction::S, Direction::W,
Direction::Last, Direction::First = N, Direction::INVALID = -1
}
Functions
Direction left_of_dir (Direction d)
returns the left of the given direction
Direction right_of_dir (Direction d)
char yaw_to_char (double yaw)
Direction yaw_to_dir (double yaw)
double dir_to_yaw (Direction d)
char opposite_direction (char c)
Direction int_to_dir (int i)
Direction operator++ (Direction &dir, int)
increments the direction in the order N, E, S, W, N, ...
Direction operator-- (Direction &dir, int)
Direction opposite_direction (Direction d)
returns the opposite direction of the input direction
char dir_to_char (Direction dir)
Direction char_to_dir (char c)
Enumeration Type Documentation
enum Direction strong
Enumerator
N
E
S
W
Last
First
INVALID
Function Documentation
Direction char_to_dir (char c)
translate a char into the direction representation
References E, INVALID, N, S, and W.
Referenced by main().
char dir_to_char (Direction dir)
translate a Dir (integer 0=N 1=E 2=S 3=W) into the character representation
References E, N, S, and W.
Referenced by route_to_string().
double dir_to_yaw (Direction d)
References E, M_PI, N, S, and W.
Referenced by smartmouse::kc::DriveStraightState::compute_wheel_velocities(), KinematicController::estimate_pose(), ArcTurn::execute(), ConsoleMouse::getGlobalPose(), ConsoleMouse::getLocalPose(), KinematicController::getLocalPose(), TurnInPlace::initialize(), ArcTurn::initialize(), and KinematicController::run().
Direction int_to_dir (int i)
References E, INVALID, N, S, and W.
Referenced by AbstractMaze::gen_random_legal_maze().
Direction left_of_dir (Direction d)
returns the left of the given direction
References E, INVALID, N, S, and W.
Referenced by SimMouse::checkWalls(), RealMouse::checkWalls(), KinematicController::estimate_pose(), and WallFollow::planNextStep().
Direction operator++ (Direction & dir, int)
increments the direction in the order N, E, S, W, N, ...
References E, INVALID, Last, N, S, and W.
Direction operator-- (Direction & dir, int)
References E, INVALID, Last, N, S, and W.
char opposite_direction (char c)
Referenced by SimMouse::checkWalls(), RealMouse::checkWalls(), AbstractMaze::connect_neighbor(), AbstractMaze::disconnect_neighbor(), AbstractMaze::flood_fill(), Turn::initialize(), and WallFollow::planNextStep().
Direction opposite_direction (Direction d)
returns the opposite direction of the input direction
Parameters
d direction you want the opposite of
Returns
the opposite direction of d
References E, INVALID, N, S, and W.
Direction right_of_dir (Direction d)
References E, INVALID, N, S, and W.
Referenced by SimMouse::checkWalls(), RealMouse::checkWalls(), KinematicController::estimate_pose(), and ArcTurn::execute().
char yaw_to_char (double yaw)
Referenced by StateWidget::StateCallback().
Direction yaw_to_dir (double yaw)
References E, N, S, and W.