SmartMouse_2018: GenerateMaze.cpp File Reference
GenerateMaze.cpp File Reference
#include <console/ConsoleMouse.h>
#include <iostream>
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
References smartmouse::maze::BUFF_SIZE, AbstractMaze::gen_random_legal_maze(), maze, AbstractMaze::print_maze(), AbstractMaze::print_maze_str(), and time.