SmartMouse_2018: Gazebo_common
Gazebo_common
Classes
class Time
A Time class, can be used to hold wall- or sim-time. stored as sec and nano-sec.
Enumerations
enum Time::FormatOption {
Time::DAYS = 0, Time::HOURS = 1, Time::MINUTES = 2, Time::SECONDS = 3,
Time::MILLISECONDS = 4
}
Functions
Time::Time ()
Constructors.
Time::Time (const Time &_time)
Copy constructor.
Time::Time (const struct timeval &_tv)
Constructor.
Time::Time (const struct timespec &_tv)
Constructor.
Time::Time (int32_t _sec, int32_t _nsec)
Constructor.
Time::Time (double _time)
Constuctor.
Time::Time (ignition::msgs::Time _time)
Constuctor.
virtual Time::~Time ()
Destructor.
static const Time & Time::GetWallTime ()
Get the wall time.
void Time::SetToWallTime ()
Set the time to the wall time.
void Time::Set (int32_t _sec, int32_t _nsec)
Set to sec and nsec.
void Time::Set (double _seconds)
Set to seconds.
double Time::Double () const
Get the time as a double.
float Time::Float () const
Get the time as a float.
std::string Time::FormattedString (FormatOption _start=DAYS, FormatOption _end=MILLISECONDS) const
Get the time as a string formatted as "DD hh:mm:ss.mmm", with the option to choose the start/end.
ignition::msgs::Time Time::toIgnMsg () const
static Time Time::Sleep (const Time &_time)
Sleep for the specified time.
static Time Time::MSleep (unsigned int _ms)
Millisecond sleep.
static Time Time::NSleep (unsigned int _ns)
Nano sleep.
Time & Time::operator= (const struct timeval &_tv)
Assignment operator.
Time & Time::operator= (const struct timespec &_tv)
Assignment operator.
Time & Time::operator= (const Time &_time)
Assignment operator.
Time Time::operator+ (const struct timeval &_tv) const
Addition operators.
Time Time::operator+ (const struct timespec &_tv) const
Addition operators.
const Time & Time::operator+= (const struct timeval &_tv)
Addition assignment operator.
const Time & Time::operator+= (const struct timespec &_tv)
Addition assignment operator.
Time Time::operator+ (const Time &_time) const
Addition operators.
const Time & Time::operator+= (const Time &_time)
Addition assignemtn operator.
Time Time::operator- (const struct timeval &_tv) const
Subtraction operator.
const Time & Time::operator-= (const struct timeval &_tv)
Subtraction assignment operator.
Time Time::operator- (const struct timespec &_tv) const
Subtraction operator.
const Time & Time::operator-= (const struct timespec &_tv)
Subtraction assignment operator.
Time Time::operator- (const Time &_time) const
Subtraction operator.
const Time & Time::operator-= (const Time &_time)
Subtraction assignment operator.
Time Time::operator* (const struct timeval &_tv) const
Multiplication operator.
const Time & Time::operator*= (const struct timeval &_tv)
Multiplication assignment operator.
Time Time::operator* (const struct timespec &_tv) const
Multiplication operator.
const Time & Time::operator*= (const struct timespec &_tv)
Multiplication assignment operator.
Time Time::operator* (const Time &_time) const
Multiplication operators.
const Time & Time::operator*= (const Time &_time)
Multiplication operators.
Time Time::operator/ (const struct timeval &_tv) const
Division operator.
const Time & Time::operator/= (const struct timeval &_tv)
Division assignment operator.
Time Time::operator/ (const struct timespec &_tv) const
Division operator.
const Time & Time::operator/= (const struct timespec &_tv)
Division assignment operator.
Time Time::operator/ (const Time &_time) const
Division operator.
const Time & Time::operator/= (const Time &time)
Division assignment operator.
bool Time::operator== (const struct timeval &_tv) const
Equal to operator.
bool Time::operator== (const struct timespec &_tv) const
Equal to operator.
bool Time::operator== (const Time &_time) const
Equal to operator.
bool Time::operator== (double _time) const
Equal to operator.
bool Time::operator!= (const struct timeval &_tv) const
Equal to operator.
bool Time::operator!= (const struct timespec &_tv) const
Equal to operator.
bool Time::operator!= (const Time &_time) const
Equal to operator.
bool Time::operator!= (double _time) const
Equal to operator.
bool Time::operator< (const struct timeval &_tv) const
Less than operator.
bool Time::operator< (const struct timespec &_tv) const
Less than operator.
bool Time::operator< (const Time &_time) const
Less than operator.
bool Time::operator< (double _time) const
Less than operator.
bool Time::operator<= (const struct timeval &_tv) const
Less than or equal to operator.
bool Time::operator<= (const struct timespec &_tv) const
Less than or equal to operator.
bool Time::operator<= (const Time &_time) const
Less than or equal to operator.
bool Time::operator<= (double _time) const
Less than or equal to operator.
bool Time::operator> (const struct timeval &_tv) const
Greater than operator.
bool Time::operator> (const struct timespec &_tv) const
Greater than operator.
bool Time::operator> (const Time &_time) const
Greater than operator.
bool Time::operator> (double _time) const
Greater than operator.
bool Time::operator>= (const struct timeval &_tv) const
Greater than or equal operator.
bool Time::operator>= (const struct timespec &_tv) const
Greater than or equal operator.
bool Time::operator>= (const Time &_time) const
Greater than or equal operator.
bool Time::operator>= (double _time) const
Greater than or equal operator.
static double Time::SecToNano (double _sec)
Convert seconds to nanoseconds.
static double Time::MilToNano (double _ms)
Convert milliseconds to nanoseconds.
static double Time::MicToNano (double _ms)
Convert microseconds to nanoseconds.
void Time::Correct ()
Correct the time so that small additions/substractions preserve the internal seconds and nanoseconds separation.
Variables
static const Time Time::Zero = Time(0, 0)
A static zero time variable set to Time(0, 0).
static const Time Time::Second = Time(1, 0)
A static time variable set to a second: Time(1, 0).
static const Time Time::Hour = Time(3600, 0)
A static time variable set to an hour: Time(3600, 0).
int32_t Time::sec
Seconds.
int32_t Time::nsec
Nanoseconds.
static const int32_t Time::nsInSec = 1000000000L
Constant multiplier to convert from nanoseconds to seconds.
static const int32_t Time::nsInMs = 1000000
Constant multiplier to convert from nanoseconds to milliseconds.
static Time Time::wallTime
a singleton value of the last GetWallTime() value
static std::string Time::wallTimeISO
Wall time as an ISO string.
static struct timespec Time::clockResolution
Friends
std::ostream & Time::operator<< (std::ostream &_out, const Time &_time)
Stream insertion operator.
std::istream & Time::operator>> (std::istream &_in, Time &_time)
Stream extraction operator.
Detailed Description
Enumeration Type Documentation
enum Time::FormatOption
Enumerator
DAYS
Days.
HOURS
Hours.
MINUTES
Minutes.
SECONDS
Seconds.
MILLISECONDS
Milliseconds.
Function Documentation
void Time::Correct () inline private
Correct the time so that small additions/substractions preserve the internal seconds and nanoseconds separation.
References Time::nsInSec.
Referenced by Time::operator*(), Time::operator*=(), Time::operator+(), Time::operator+=(), Time::operator-(), Time::operator-=(), Time::Set(), and Time::Time().
double Time::Double () const
Get the time as a double.
Returns
Time as a double in seconds
References e, Time::nsec, and Time::sec.
Referenced by Time::operator*(), Time::operator*=(), Time::operator/(), and Server::Run().
float Time::Float () const
Get the time as a float.
Returns
Time as a float in seconds
References e, Time::nsec, and Time::sec.
std::string Time::FormattedString (FormatOption _start = DAYS, FormatOption _end = MILLISECONDS) const
Get the time as a string formatted as "DD hh:mm:ss.mmm", with the option to choose the start/end.
Parameters
[in] _start Start point.
[in] _end End point.
Returns
String representing time.
References Time::MILLISECONDS, Time::nsec, Time::nsInMs, and Time::sec.
const Time & Time::GetWallTime () static
Get the wall time.
Returns
the current time
References Time::nsInSec, and Time::wallTime.
Referenced by Server::Run(), Time::SetToWallTime(), and TEST().
static double Time::MicToNano (double _ms) inline static
Convert microseconds to nanoseconds.
Parameters
_ms microseconds
Returns
nanoseconds
static double Time::MilToNano (double _ms) inline static
Convert milliseconds to nanoseconds.
Parameters
[in] _ms milliseconds
Returns
nanoseconds
Time Time::MSleep (unsigned int _ms) static
Millisecond sleep.
Parameters
[in] _ms milliseconds
Returns
Time actually slept
References Time::Sleep(), and Time::Time().
Referenced by Server::Run().
Time Time::NSleep (unsigned int _ns) static
Nano sleep.
Parameters
[in] _ns nanoseconds
Returns
Time actually slept
References Time::Sleep(), and Time::Time().
bool Time::operator!= (const struct timeval & _tv) const
Equal to operator.
Parameters
[in] _tv the time to compare to
Returns
true if values are the same, false otherwise
bool Time::operator!= (const struct timespec & _tv) const
Equal to operator.
Parameters
[in] _tv the time to compare to
Returns
true if values are the same, false otherwise
bool Time::operator!= (const Time & _time) const
Equal to operator.
Parameters
[in] _time the time to compare to
Returns
true if values are the same, false otherwise
bool Time::operator!= (double _time) const
Equal to operator.
Parameters
[in] _time the time to compare to
Returns
true if values are the same, false otherwise
Time Time::operator* (const struct timeval & _tv) const
Multiplication operator.
Parameters
[in] _tv The scaling duration
Returns
Time instance
References Time::Correct(), and Time::Double().
Time Time::operator* (const struct timespec & _tv) const
Multiplication operator.
Parameters
[in] _tv the scaling duration
Returns
Time instance
References Time::Correct(), and Time::Double().
Time Time::operator* (const Time & _time) const
Multiplication operators.
Parameters
[in] _time the scaling factor
Returns
a scaled Time instance
References Time::Correct(), and Time::Double().
const Time & Time::operator*= (const struct timeval & _tv)
Multiplication assignment operator.
Parameters
[in] _tv the scaling duration
Returns
a reference to this instance
References Time::Correct(), Time::Double(), and Time::Set().
const Time & Time::operator*= (const struct timespec & _tv)
Multiplication assignment operator.
Parameters
[in] _tv the scaling duration
Returns
a reference to this instance
References Time::Correct(), Time::Double(), and Time::Set().
const Time & Time::operator*= (const Time & _time)
Multiplication operators.
Parameters
[in] _time scale factor
Returns
a scaled Time instance
References Time::Correct(), Time::Double(), and Time::Set().
Time Time::operator+ (const struct timeval & _tv) const
Addition operators.
Parameters
[in] _tv the time to add
Returns
a Time instance
References Time::Correct(), and Time::sec.
Time Time::operator+ (const struct timespec & _tv) const
Addition operators.
Parameters
[in] _tv the time to add
Returns
a Time instance
References Time::Correct(), and Time::sec.
Time Time::operator+ (const Time & _time) const
Addition operators.
Parameters
[in] _time The time to add
Returns
a Time instance
References Time::Correct(), Time::nsec, and Time::sec.
const Time & Time::operator+= (const struct timeval & _tv)
Addition assignment operator.
Parameters
[in] _tv the time to add
Returns
a reference to this instance
References Time::Correct(), Time::nsec, and Time::sec.
const Time & Time::operator+= (const struct timespec & _tv)
Addition assignment operator.
Parameters
[in] _tv the time to add
Returns
a reference to this instance
References Time::Correct(), Time::nsec, and Time::sec.
const Time & Time::operator+= (const Time & _time)
Addition assignemtn operator.
Parameters
[in] _time The time to add
Returns
a Time instance
References Time::Correct(), Time::nsec, and Time::sec.
Time Time::operator- (const struct timeval & _tv) const
Subtraction operator.
Parameters
[in] _tv The time to subtract
Returns
a Time instance
References Time::Correct(), and Time::sec.
Time Time::operator- (const struct timespec & _tv) const
Subtraction operator.
Parameters
[in] _tv The time to subtract
Returns
a Time instance
References Time::Correct(), and Time::sec.
Time Time::operator- (const Time & _time) const
Subtraction operator.
Parameters
[in] _time The time to subtract
Returns
a Time instance
References Time::Correct(), Time::nsec, and Time::sec.
const Time & Time::operator-= (const struct timeval & _tv)
Subtraction assignment operator.
Parameters
[in] _tv The time to subtract
Returns
a Time instance
References Time::Correct(), Time::nsec, and Time::sec.
const Time & Time::operator-= (const struct timespec & _tv)
Subtraction assignment operator.
Parameters
[in] _tv The time to subtract
Returns
a Time instance
References Time::Correct(), Time::nsec, and Time::sec.
const Time & Time::operator-= (const Time & _time)
Subtraction assignment operator.
Parameters
[in] _time The time to subtract
Returns
a reference to this instance
References Time::Correct(), Time::nsec, and Time::sec.
Time Time::operator/ (const struct timeval & _tv) const
Division operator.
Parameters
[in] _tv a timeval divisor
Returns
a Time instance
References Time::Time().
Time Time::operator/ (const struct timespec & _tv) const
Division operator.
Parameters
[in] _tv a timespec divisor
Returns
a Time instance
References Time::Time().
Time Time::operator/ (const Time & _time) const
Division operator.
Parameters
[in] _time the divisor
Returns
a Time instance
References Time::Double(), Time::nsec, Time::sec, and Time::Set().
const Time & Time::operator/= (const struct timeval & _tv)
Division assignment operator.
Parameters
[in] _tv a divisor
Returns
a Time instance
References Time::Time().
const Time & Time::operator/= (const struct timespec & _tv)
Division assignment operator.
Parameters
[in] _tv a divisor
Returns
a Time instance
References Time::Time().
const Time & Time::operator/= (const Time & time)
Division assignment operator.
Parameters
[in] time the divisor
Returns
a Time instance
bool Time::operator< (const struct timeval & _tv) const
Less than operator.
Parameters
[in] _tv the time to compare with
Returns
true if tv is shorter than this, false otherwise
References Time::Time().
bool Time::operator< (const struct timespec & _tv) const
Less than operator.
Parameters
[in] _tv the time to compare with
Returns
true if tv is shorter than this, false otherwise
References Time::Time().
bool Time::operator< (const Time & _time) const
Less than operator.
Parameters
[in] _time the time to compare with
Returns
true if time is shorter than this, false otherwise
References Time::nsec, and Time::sec.
bool Time::operator< (double _time) const
Less than operator.
Parameters
[in] _time the time to compare with
Returns
true if time is shorter than this, false otherwise
References Time::Time().
bool Time::operator<= (const struct timeval & _tv) const
Less than or equal to operator.
Parameters
[in] _tv the time to compare with
Returns
true if tv is shorter than or equal to this, false otherwise
References Time::Time().
bool Time::operator<= (const struct timespec & _tv) const
Less than or equal to operator.
Parameters
[in] _tv the time to compare with
Returns
true if tv is shorter than or equal to this, false otherwise
References Time::Time().
bool Time::operator<= (const Time & _time) const
Less than or equal to operator.
Parameters
[in] _time the time to compare with
Returns
true if time is shorter than or equal to this, false otherwise
bool Time::operator<= (double _time) const
Less than or equal to operator.
Parameters
[in] _time the time to compare with
Returns
true if time is shorter than or equal to this, false otherwise
References Time::Time().
Time & Time::operator= (const struct timeval & _tv)
Assignment operator.
Parameters
[in] _tv the new time
Returns
a reference to this instance
References Time::nsec, and Time::sec.
Time & Time::operator= (const struct timespec & _tv)
Assignment operator.
Parameters
[in] _tv the new time
Returns
a reference to this instance
References Time::nsec, and Time::sec.
Time & Time::operator= (const Time & _time)
Assignment operator.
Parameters
[in] _time the new time
Returns
a reference to this instance
References Time::nsec, and Time::sec.
bool Time::operator== (const struct timeval & _tv) const
Equal to operator.
Parameters
[in] _tv the time to compare to
Returns
true if values are the same, false otherwise
References Time::Time().
bool Time::operator== (const struct timespec & _tv) const
Equal to operator.
Parameters
[in] _tv the time to compare to
Returns
true if values are the same, false otherwise
References Time::Time().
bool Time::operator== (const Time & _time) const
Equal to operator.
Parameters
[in] _time the time to compare to
Returns
true if values are the same, false otherwise
References Time::nsec, and Time::sec.
bool Time::operator== (double _time) const
Equal to operator.
Parameters
[in] _time the time to compare to
Returns
true if values are the same, false otherwise
References Time::Time().
bool Time::operator> (const struct timeval & _tv) const
Greater than operator.
Parameters
[in] _tv the time to compare with
Returns
true if time is greater than this, false otherwise
References Time::Time().
bool Time::operator> (const struct timespec & _tv) const
Greater than operator.
Parameters
[in] _tv the time to compare with
Returns
true if time is greater than this, false otherwise
References Time::Time().
bool Time::operator> (const Time & _time) const
Greater than operator.
Parameters
[in] _time the time to compare with
Returns
true if time is greater than this, false otherwise
bool Time::operator> (double _time) const
Greater than operator.
Parameters
[in] _time the time to compare with
Returns
true if time is greater than this, false otherwise
References Time::Time().
bool Time::operator>= (const struct timeval & _tv) const
Greater than or equal operator.
Parameters
[in] _tv the time to compare with
Returns
true if tv is greater than or equal to this, false otherwise
References Time::Time().
bool Time::operator>= (const struct timespec & _tv) const
Greater than or equal operator.
Parameters
[in] _tv the time to compare with
Returns
true if tv is greater than or equal to this, false otherwise
References Time::Time().
bool Time::operator>= (const Time & _time) const
Greater than or equal operator.
Parameters
[in] _time the time to compare with
Returns
true if time is greater than or equal to this, false otherwise
bool Time::operator>= (double _time) const
Greater than or equal operator.
Parameters
[in] _time the time to compare with
Returns
true if time is greater than or equal to this, false otherwise
References Time::Time().
static double Time::SecToNano (double _sec) inline static
Convert seconds to nanoseconds.
Parameters
[in] _sec duration in seconds
Returns
nanoseconds
void Time::Set (int32_t _sec, int32_t _nsec)
Set to sec and nsec.
Parameters
[in] _sec Seconds
[in] _nsec Nanoseconds
References Time::Correct(), Time::nsec, and Time::sec.
Referenced by Time::operator*=(), Time::operator/(), and Time::Time().
void Time::Set (double _seconds)
Set to seconds.
Parameters
[in] _seconds Number of seconds
References Time::Correct(), Time::nsec, Time::nsInSec, and Time::sec.
void Time::SetToWallTime ()
Set the time to the wall time.
References Time::GetWallTime().
Time Time::Sleep (const Time & _time) static
Sleep for the specified time.
Parameters
[in] _time Sleep time
Returns
Time actually slept
References Time::clockResolution, Time::nsec, Time::sec, and timer.
Referenced by Time::MSleep(), Time::NSleep(), and Server::Run().
Time::Time ()
Constructors.
Referenced by Time::MSleep(), Time::NSleep(), Time::operator/(), Time::operator/=(), Time::operator<(), Time::operator<=(), Time::operator==(), Time::operator>(), and Time::operator>=().
Time::Time (const Time & _time)
Copy constructor.
Parameters
[in] time Time to copy
Time::Time (const struct timeval & _tv)
Constructor.
Parameters
[in] _tv Time to initialize to
References Time::nsec, and Time::sec.
Time::Time (const struct timespec & _tv)
Constructor.
Parameters
[in] _tv Time to initialize to
References Time::nsec, and Time::sec.
Time::Time (int32_t _sec, int32_t _nsec)
Constructor.
Parameters
[in] _sec Seconds
[in] _nsec Nanoseconds
References Time::Correct().
Time::Time (double _time)
Constuctor.
Parameters
[in] _time Time in double format sec.nsec
References Time::Set().
Time::Time (ignition::msgs::Time _time)
Constuctor.
Parameters
[in] _time Time form ignition msg
References Time::Set().
ignition::msgs::Time Time::toIgnMsg () const
References Time::nsec, Time::sec, and time.
Referenced by Server::PublishWorldStats(), and Server::UpdateRobotState().
Time::~Time () virtual
Destructor.
Variable Documentation
struct timespec Time::clockResolution static private
Referenced by Time::Sleep().
const Time Time::Hour = Time(3600, 0) static
A static time variable set to an hour: Time(3600, 0).
int32_t Time::nsec
Nanoseconds.
Referenced by Time::Double(), Time::Float(), Time::FormattedString(), Time::operator+(), Time::operator+=(), Time::operator-(), Time::operator-=(), Time::operator/(), Time::operator<(), Time::operator=(), Time::operator==(), Time::Set(), Time::Sleep(), Time::Time(), and Time::toIgnMsg().
const int32_t Time::nsInMs = 1000000 static
Constant multiplier to convert from nanoseconds to milliseconds.
Referenced by Time::FormattedString().
const int32_t Time::nsInSec = 1000000000L static
Constant multiplier to convert from nanoseconds to seconds.
Referenced by Time::Correct(), Time::GetWallTime(), and Time::Set().
int32_t Time::sec
Seconds.
Referenced by Time::Double(), Time::Float(), Time::FormattedString(), Time::operator+(), Time::operator+=(), Time::operator-(), Time::operator-=(), Time::operator/(), Time::operator<(), Time::operator=(), Time::operator==(), Time::Set(), Time::Sleep(), Time::Time(), and Time::toIgnMsg().
const Time Time::Second = Time(1, 0) static
A static time variable set to a second: Time(1, 0).
Time Time::wallTime static private
a singleton value of the last GetWallTime() value
Referenced by Time::GetWallTime().
std::string Time::wallTimeISO static private
Wall time as an ISO string.
const Time Time::Zero = Time(0, 0) static
A static zero time variable set to Time(0, 0).
Referenced by Server::ResetTime().
Friends
std::ostream& operator<< (std::ostream & _out, const Time & _time) friend
Stream insertion operator.
Parameters
[in] _out the output stream
[in] _time time to write to the stream
Returns
the output stream
std::istream& operator>> (std::istream & _in, Time & _time) friend
Stream extraction operator.
Parameters
[in] _in the input stream
[in] _time time to read from to the stream
Returns
the input stream