SmartMouse_2018: Half.h File Reference
Half.h File Reference
Classes
struct Eigen::half_impl::__half_raw
struct Eigen::half_impl::half_base
struct Eigen::half
union Eigen::half_impl::FP32
struct Eigen::internal::random_default_impl< half, false, false >
struct Eigen::internal::is_arithmetic< half >
struct std::numeric_limits< Eigen::half >
struct Eigen::NumTraits< Eigen::half >
Namespaces
Eigen
Eigen::half_impl
Eigen::internal
std
Macros
#define EIGEN_EXPLICIT_CAST(tgt_type) operator tgt_type()
Functions
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC __half_raw Eigen::half_impl::raw_uint16_to_half (unsigned short x)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC __half_raw Eigen::half_impl::float_to_half_rtne (float ff)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC float Eigen::half_impl::half_to_float (__half_raw h)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC half Eigen::half_impl::operator+ (const half &a, const half &b)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC half Eigen::half_impl::operator* (const half &a, const half &b)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC half Eigen::half_impl::operator- (const half &a, const half &b)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC half Eigen::half_impl::operator/ (const half &a, const half &b)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC half Eigen::half_impl::operator- (const half &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC half & Eigen::half_impl::operator+= (half &a, const half &b)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC half & Eigen::half_impl::operator*= (half &a, const half &b)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC half & Eigen::half_impl::operator-= (half &a, const half &b)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC half & Eigen::half_impl::operator/= (half &a, const half &b)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bool Eigen::half_impl::operator== (const half &a, const half &b)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bool Eigen::half_impl::operator!= (const half &a, const half &b)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bool Eigen::half_impl::operator< (const half &a, const half &b)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bool Eigen::half_impl::operator<= (const half &a, const half &b)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bool Eigen::half_impl::operator> (const half &a, const half &b)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bool Eigen::half_impl::operator>= (const half &a, const half &b)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC half Eigen::half_impl::operator/ (const half &a, Index b)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bool() Eigen::half_impl::isinf (const half &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bool() Eigen::half_impl::isnan (const half &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bool() Eigen::half_impl::isfinite (const half &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC half Eigen::half_impl::abs (const half &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC half Eigen::half_impl::exp (const half &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC half Eigen::half_impl::expm1 (const half &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC half Eigen::half_impl::log (const half &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC half Eigen::half_impl::log1p (const half &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC half Eigen::half_impl::log10 (const half &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC half Eigen::half_impl::sqrt (const half &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC half Eigen::half_impl::pow (const half &a, const half &b)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC half Eigen::half_impl::sin (const half &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC half Eigen::half_impl::cos (const half &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC half Eigen::half_impl::tan (const half &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC half Eigen::half_impl::tanh (const half &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC half Eigen::half_impl::floor (const half &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC half Eigen::half_impl::ceil (const half &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC half() Eigen::half_impl::min (const half &a, const half &b)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC half() Eigen::half_impl::max (const half &a, const half &b)
EIGEN_ALWAYS_INLINE std::ostream & Eigen::half_impl::operator<< (std::ostream &os, const half &v)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC Eigen::half fabsh (const Eigen::half &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC Eigen::half exph (const Eigen::half &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC Eigen::half logh (const Eigen::half &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC Eigen::half sqrth (const Eigen::half &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC Eigen::half powh (const Eigen::half &a, const Eigen::half &b)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC Eigen::half floorh (const Eigen::half &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC Eigen::half ceilh (const Eigen::half &a)
Macro Definition Documentation
#define EIGEN_EXPLICIT_CAST (tgt_type) operator tgt_type()
Function Documentation
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC Eigen::half ceilh (const Eigen::half & a)
References EIGEN_ALWAYS_INLINE, EIGEN_STRONG_INLINE, Eigen::half_impl::isfinite(), Eigen::half_impl::isinf(), Eigen::half_impl::isnan(), operator()(), Eigen::half_impl::raw_uint16_to_half(), and Eigen::half_impl::__half_raw::x.
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC Eigen::half exph (const Eigen::half & a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC Eigen::half fabsh (const Eigen::half & a)
References Eigen::half_impl::__half_raw::x.
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC Eigen::half floorh (const Eigen::half & a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC Eigen::half logh (const Eigen::half & a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC Eigen::half powh (const Eigen::half & a, const Eigen::half & b)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC Eigen::half sqrth (const Eigen::half & a)