SmartMouse_2018: IndexedViewMethods.h File Reference
IndexedViewMethods.h File Reference
#include "IndexedViewMethods.h"
Classes
struct IvcRowType< Indices >
struct IvcColType< Indices >
struct IvcType< Indices >
struct valid_indexed_view_overload< RowIndices, ColIndices >
struct EIGEN_INDEXED_VIEW_METHOD_TYPE< RowIndices, ColIndices >
Macros
#define EIGEN_INDEXED_VIEW_METHOD_CONST const
#define EIGEN_INDEXED_VIEW_METHOD_TYPE ConstIndexedViewType
#define EIGEN_INDEXED_VIEW_METHOD_2ND_PASS
#define EIGEN_INDEXED_VIEW_METHOD_CONST
#define EIGEN_INDEXED_VIEW_METHOD_TYPE IndexedViewType
#define EIGEN_INDEXED_VIEW_METHOD_CONST const
#define EIGEN_INDEXED_VIEW_METHOD_TYPE ConstIndexedViewType
#define EIGEN_INDEXED_VIEW_METHOD_2ND_PASS
Typedefs
typedef internal::IndexedViewCompatibleType< Index, 1 >::type IvcIndex
Functions
template<typename Indices >
IvcRowType< Indices >::type ivcRow (const Indices &indices) const
template<typename Indices >
IvcColType< Indices >::type ivcCol (const Indices &indices) const
template<typename Indices >
IvcColType< Indices >::type ivcSize (const Indices &indices) const
template<typename RowIndices , typename ColIndices >
internal::enable_if< valid_indexed_view_overload< RowIndices, ColIndices >::value &&internal::traits< typename EIGEN_INDEXED_VIEW_METHOD_TYPE< RowIndices, ColIndices >::type >::ReturnAsIndexedView, typename EIGEN_INDEXED_VIEW_METHOD_TYPE< RowIndices, ColIndices >::type >::type operator() (const RowIndices &rowIndices, const ColIndices &colIndices) EIGEN_INDEXED_VIEW_METHOD_CONST
template<typename RowIndices , typename ColIndices >
internal::enable_if< valid_indexed_view_overload< RowIndices, ColIndices >::value &&internal::traits< typename EIGEN_INDEXED_VIEW_METHOD_TYPE< RowIndices, ColIndices >::type >::ReturnAsBlock, typename internal::traits< typename EIGEN_INDEXED_VIEW_METHOD_TYPE< RowIndices, ColIndices >::type >::BlockType >::type operator() (const RowIndices &rowIndices, const ColIndices &colIndices) EIGEN_INDEXED_VIEW_METHOD_CONST
template<typename RowIndices , typename ColIndices >
internal::enable_if< valid_indexed_view_overload< RowIndices, ColIndices >::value &&internal::traits< typename EIGEN_INDEXED_VIEW_METHOD_TYPE< RowIndices, ColIndices >::type >::ReturnAsScalar, CoeffReturnType >::type operator() (const RowIndices &rowIndices, const ColIndices &colIndices) EIGEN_INDEXED_VIEW_METHOD_CONST
template<typename Indices >
internal::enable_if< IsRowMajor &&(!(internal::get_compile_time_incr< typename IvcType< Indices >::type >::value==1||internal::is_valid_index_type< Indices >::value)), IndexedView< EIGEN_INDEXED_VIEW_METHOD_CONST Derived, IvcIndex, typename IvcType< Indices >::type > >::type operator() (const Indices &indices) EIGEN_INDEXED_VIEW_METHOD_CONST
template<typename Indices >
internal::enable_if< (!IsRowMajor)&&(!(internal::get_compile_time_incr< typename IvcType< Indices >::type >::value==1||internal::is_valid_index_type< Indices >::value)), IndexedView< EIGEN_INDEXED_VIEW_METHOD_CONST Derived, typename IvcType< Indices >::type, IvcIndex > >::type operator() (const Indices &indices) EIGEN_INDEXED_VIEW_METHOD_CONST
template<typename Indices >
internal::enable_if< (internal::get_compile_time_incr< typename IvcType< Indices >::type >::value==1)&&(!internal::is_valid_index_type< Indices >::value)&&(!Symbolic::is_symbolic< Indices >::value), VectorBlock< EIGEN_INDEXED_VIEW_METHOD_CONST Derived, internal::array_size< Indices >::value > >::type operator() (const Indices &indices) EIGEN_INDEXED_VIEW_METHOD_CONST
template<typename IndexType >
internal::enable_if< Symbolic::is_symbolic< IndexType >::value, CoeffReturnType >::type operator() (const IndexType &id) EIGEN_INDEXED_VIEW_METHOD_CONST
Macro Definition Documentation
#define EIGEN_INDEXED_VIEW_METHOD_2ND_PASS
#define EIGEN_INDEXED_VIEW_METHOD_2ND_PASS
#define EIGEN_INDEXED_VIEW_METHOD_CONST const
#define EIGEN_INDEXED_VIEW_METHOD_CONST const
Referenced by operator()().
#define EIGEN_INDEXED_VIEW_METHOD_CONST
#define EIGEN_INDEXED_VIEW_METHOD_TYPE ConstIndexedViewType
#define EIGEN_INDEXED_VIEW_METHOD_TYPE ConstIndexedViewType
#define EIGEN_INDEXED_VIEW_METHOD_TYPE IndexedViewType
Typedef Documentation
typedef internal::IndexedViewCompatibleType<Index,1>::type IvcIndex protected
Function Documentation
template<typename Indices > IvcColType<Indices>::type ivcCol (const Indices & indices) const protected
References Eigen::internal::makeIndexedViewCompatible(), and Eigen::Specialized.
Referenced by operator()().
template<typename Indices > IvcRowType<Indices>::type ivcRow (const Indices & indices) const protected
References Eigen::internal::makeIndexedViewCompatible(), and Eigen::Specialized.
Referenced by operator()().
template<typename Indices > IvcColType<Indices>::type ivcSize (const Indices & indices) const protected
References Eigen::internal::makeIndexedViewCompatible(), Eigen::internal::size(), and Eigen::Specialized.
Referenced by operator()().
template<typename RowIndices , typename ColIndices > internal::enable_if<valid_indexed_view_overload<RowIndices,ColIndices>::value && internal::traits<typename EIGEN_INDEXED_VIEW_METHOD_TYPE<RowIndices,ColIndices>::type>::ReturnAsIndexedView, typename EIGEN_INDEXED_VIEW_METHOD_TYPE<RowIndices,ColIndices>::type >::type operator() (const RowIndices & rowIndices, const ColIndices & colIndices)
References ivcCol(), ivcRow(), and type.
Referenced by ceilh(), Eigen::internal::blas_data_mapper< const Scalar, Index, StorageOrder >::gatherPacket(), Eigen::internal::blas_data_mapper< const Scalar, Index, StorageOrder >::getSubMapper(), Eigen::internal::const_blas_data_mapper< Scalar, Index, StorageOrder >::getSubMapper(), Eigen::internal::blas_data_mapper< const Scalar, Index, StorageOrder >::load(), Eigen::internal::blas_data_mapper< const Scalar, Index, StorageOrder >::loadHalfPacket(), Eigen::internal::blas_data_mapper< const Scalar, Index, StorageOrder >::loadPacket(), Eigen::internal::FixedInt< N >::operator&(), operator()(), Eigen::internal::bind1st_op< BinaryOp >::operator()(), Eigen::internal::bind2nd_op< BinaryOp >::operator()(), and Eigen::internal::blas_data_mapper< const Scalar, Index, StorageOrder >::scatterPacket().
template<typename RowIndices , typename ColIndices > internal::enable_if<valid_indexed_view_overload<RowIndices,ColIndices>::value && internal::traits<typename EIGEN_INDEXED_VIEW_METHOD_TYPE<RowIndices,ColIndices>::type>::ReturnAsBlock, typename internal::traits<typename EIGEN_INDEXED_VIEW_METHOD_TYPE<RowIndices,ColIndices>::type>::BlockType>::type operator() (const RowIndices & rowIndices, const ColIndices & colIndices)
References Eigen::internal::first(), ivcCol(), ivcRow(), Eigen::internal::size(), and type.
template<typename RowIndices , typename ColIndices > internal::enable_if<valid_indexed_view_overload<RowIndices,ColIndices>::value && internal::traits<typename EIGEN_INDEXED_VIEW_METHOD_TYPE<RowIndices,ColIndices>::type>::ReturnAsScalar, CoeffReturnType >::type operator() (const RowIndices & rowIndices, const ColIndices & colIndices)
References EIGEN_INDEXED_VIEW_METHOD_CONST, Eigen::internal::eval_expr_given_size(), ivcCol(), ivcRow(), operator()(), and type.
template<typename Indices > internal::enable_if< IsRowMajor && (!(internal::get_compile_time_incr<typename IvcType<Indices>::type>::value==1 || internal::is_valid_index_type<Indices>::value)), IndexedView<EIGEN_INDEXED_VIEW_METHOD_CONST Derived,IvcIndex,typename IvcType<Indices>::type> >::type operator() (const Indices & indices)
References EIGEN_INDEXED_VIEW_METHOD_CONST, EIGEN_STATIC_ASSERT_VECTOR_ONLY, ivcCol(), and type.
template<typename Indices > internal::enable_if< (!IsRowMajor) && (!(internal::get_compile_time_incr<typename IvcType<Indices>::type>::value==1 || internal::is_valid_index_type<Indices>::value)), IndexedView<EIGEN_INDEXED_VIEW_METHOD_CONST Derived,typename IvcType<Indices>::type,IvcIndex> >::type operator() (const Indices & indices)
References EIGEN_INDEXED_VIEW_METHOD_CONST, EIGEN_STATIC_ASSERT_VECTOR_ONLY, ivcRow(), and type.
template<typename Indices > internal::enable_if< (internal::get_compile_time_incr<typename IvcType<Indices>::type>::value==1) && (!internal::is_valid_index_type<Indices>::value) && (!Symbolic::is_symbolic<Indices>::value), VectorBlock<EIGEN_INDEXED_VIEW_METHOD_CONST Derived,internal::array_size<Indices>::value> >::type operator() (const Indices & indices)
References EIGEN_STATIC_ASSERT_VECTOR_ONLY, Eigen::internal::first(), ivcSize(), Eigen::internal::size(), and type.
template<typename IndexType > internal::enable_if<Symbolic::is_symbolic<IndexType>::value, CoeffReturnType >::type operator() (const IndexType & id)
References EIGEN_INDEXED_VIEW_METHOD_CONST, EIGEN_STATIC_ASSERT_VECTOR_ONLY, Eigen::internal::eval_expr_given_size(), operator()(), Eigen::internal::size(), and type.