SmartMouse_2018: MatrixCwiseUnaryOps.h File Reference
MatrixCwiseUnaryOps.h File Reference
Typedefs
typedef CwiseUnaryOp< internal::scalar_abs_op< Scalar >, const Derived > CwiseAbsReturnType
typedef CwiseUnaryOp< internal::scalar_abs2_op< Scalar >, const Derived > CwiseAbs2ReturnType
typedef CwiseUnaryOp< internal::scalar_sqrt_op< Scalar >, const Derived > CwiseSqrtReturnType
typedef CwiseUnaryOp< internal::scalar_sign_op< Scalar >, const Derived > CwiseSignReturnType
typedef CwiseUnaryOp< internal::scalar_inverse_op< Scalar >, const Derived > CwiseInverseReturnType
Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseAbsReturnType cwiseAbs () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseAbs2ReturnType cwiseAbs2 () const
EIGEN_DEVICE_FUNC const CwiseSqrtReturnType cwiseSqrt () const
EIGEN_DEVICE_FUNC const CwiseSignReturnType cwiseSign () const
EIGEN_DEVICE_FUNC const CwiseInverseReturnType cwiseInverse () const
Typedef Documentation
typedef CwiseUnaryOp<internal::scalar_abs2_op<Scalar>, const Derived> CwiseAbs2ReturnType
typedef CwiseUnaryOp<internal::scalar_abs_op<Scalar>, const Derived> CwiseAbsReturnType
typedef CwiseUnaryOp<internal::scalar_inverse_op<Scalar>, const Derived> CwiseInverseReturnType
typedef CwiseUnaryOp<internal::scalar_sign_op<Scalar>, const Derived> CwiseSignReturnType
typedef CwiseUnaryOp<internal::scalar_sqrt_op<Scalar>, const Derived> CwiseSqrtReturnType
Function Documentation
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseAbsReturnType cwiseAbs () const
Returns
an expression of the coefficient-wise absolute value of *this
Example:
Output:
See also
cwiseAbs2()
References cwiseAbs2(), EIGEN_DOC_UNARY_ADDONS, and EIGEN_STRONG_INLINE.
Referenced by Eigen::MatrixBase< Derived >::hypotNorm(), and Eigen::MatrixBase< Derived >::stableNormalize().
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseAbs2ReturnType cwiseAbs2 () const
Returns
an expression of the coefficient-wise squared absolute value of *this
Example:
Output:
See also
cwiseAbs()
References cwiseSqrt(), EIGEN_DOC_UNARY_ADDONS, and square().
Referenced by cwiseAbs().
EIGEN_DEVICE_FUNC const CwiseInverseReturnType cwiseInverse () const inline
Returns
an expression of the coefficient-wise inverse of *this.
Example:
Output:
See also
cwiseProduct()
Referenced by cwiseSign(), and Eigen::DiagonalBase< DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > >::inverse().
EIGEN_DEVICE_FUNC const CwiseSignReturnType cwiseSign () const inline
Returns
an expression of the coefficient-wise signum of *this.
Example:
Output:
References cwiseInverse(), EIGEN_DOC_UNARY_ADDONS, and inverse().
Referenced by cwiseSqrt().
EIGEN_DEVICE_FUNC const CwiseSqrtReturnType cwiseSqrt () const inline
Returns
an expression of the coefficient-wise square root of *this.
Example:
Output:
See also
cwisePow(), cwiseSquare()
References cwiseSign(), EIGEN_DOC_UNARY_ADDONS, and sign().
Referenced by cwiseAbs2().