SmartMouse_2018: Eigen::placeholders Namespace Reference
Eigen::placeholders Namespace Reference
Namespaces
internal
Functions
static const Symbolic::AddExpr< Symbolic::SymbolExpr< internal::symbolic_last_tag >, Symbolic::ValueExpr< Eigen::internal::FixedInt< 1 > > > end (last+fix< 1 >())
Variables
static const Symbolic::SymbolExpr< internal::symbolic_last_tag > last
static const Eigen::internal::all_t all
Detailed Description
Namespace containing symbolic placeholder and identifiers
Function Documentation
static const Symbolic::AddExpr<Symbolic::SymbolExpr<internal::symbolic_last_tag>,Symbolic::ValueExpr<Eigen::internal::FixedInt<1> > > Eigen::placeholders::end (last+fix< 1 > ()) static
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheLeft(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::back(), Eigen::SparseMapBase< Derived, ReadOnlyAccessors >::coeff(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::coeff(), Eigen::SparseMapBase< Derived, WriteAccessors >::coeffRef(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::coeffRef(), Eigen::internal::computeFromTridiagonal_impl(), nlohmann::detail::external_constructor< value_t::array >::construct(), nlohmann::detail::external_constructor< value_t::object >::construct(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::erase(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::finalize(), Eigen::internal::evaluator< SparseCompressedBase< Derived > >::find(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::find(), nlohmann::detail::from_json(), nlohmann::detail::from_json_array_impl(), Eigen::BlockImpl< XprType, BlockRows, BlockCols, true, Sparse >::nonZeros(), Eigen::internal::sparse_matrix_block_impl< const SparseMatrix< _Scalar, _Options, _StorageIndex >, BlockRows, BlockCols >::operator=(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::parse(), Eigen::PermutationMatrix< RowsAtCompileTime, MaxRowsAtCompileTime >::PermutationMatrix(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::prune(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::rbegin(), std::vector< T, EIGEN_ALIGNED_ALLOCATOR< T > >::resize(), std::deque< T, EIGEN_ALIGNED_ALLOCATOR< T > >::resize(), std::list< T, EIGEN_ALIGNED_ALLOCATOR< T > >::resize(), Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheLeft, Mode, Conjugate, TriStorageOrder, ColMajor >::run(), Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, true, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >::run(), Eigen::internal::unaligned_dense_assignment_loop< false >::run(), Eigen::internal::set_from_triplets(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::setFromTriplets(), TEST(), Eigen::internal::tridiagonal_qr_step(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::value(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::numtostr::x_write().
Variable Documentation
Eigen::placeholders::all static
Can be used as a parameter to DenseBase::operator()(const RowIndices&, const ColIndices&) to index all rows or columns
Referenced by Eigen::AlignedBox< _Scalar, _AmbientDim >::contains(), Eigen::BDCSVD< _MatrixType >::deflation(), Eigen::DenseBase< Derived >::hasNaN(), Eigen::AlignedBox< _Scalar, _AmbientDim >::intersects(), and Eigen::internal::ldlt_inplace< Lower >::unblocked().
Eigen::placeholders::last static
Can be used as a parameter to Eigen::seq and Eigen::seqN functions to symbolically reference the last element/row/columns of the underlying vector or matrix once passed to DenseBase::operator()(const RowIndices&, const ColIndices&).
This symbolic placeholder support standard arithmetic operation.
A typical usage example would be:
using namespace Eigen;
using Eigen::placeholders::last;
VectorXd v(n);
v(seq(2,last-2)).setOnes();
See also
end
Referenced by LinkedList< T >::add(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::conservativeResize(), Eigen::internal::eval_expr_given_size(), LinkedList< T >::LinkedList(), Eigen::internal::minimum_degree_ordering(), Eigen::BDCSVD< _MatrixType >::perturbCol0(), LinkedList< T >::pop(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_pointer::pop_back(), Eigen::internal::QuickSplit(), and LinkedList< T >::~LinkedList().