SmartMouse_2018: smartmouse::kc Namespace Reference
smartmouse::kc Namespace Reference
Classes
class DriveStraightState
Functions
constexpr double cellsToRad (double x)
constexpr double meterToRad (double x)
constexpr double radToMeters (double x)
constexpr double radToCU (double x)
Variables
const double kVf = 1.0
double MAX_SPEED_MPS = 0.90
double MAX_SPEED_CUPS = smartmouse::maze::toCellUnits(MAX_SPEED_MPS)
bool ARC_TURN = false
constexpr double FRONT_ANALOG_ANGLE = 1.35255
constexpr double BACK_ANALOG_ANGLE = 1.35255
constexpr double FRONT_SIDE_ANALOG_X = 0.042
constexpr double FRONT_SIDE_ANALOG_Y = 0.0350
constexpr double BACK_SIDE_ANALOG_X = -0.0206
constexpr double BACK_SIDE_ANALOG_Y = 0.0335
constexpr double FRONT_ANALOG_X = 0.056
constexpr double GERALD_X = 0.054
constexpr double GERALD_Y = 0.018
constexpr double GERALD_ANGLE = 0.6544985
constexpr double MAX_HARDWARE_SPEED_MPS = 0.60
constexpr double MIN_SPEED_MPS = 0.014
constexpr double FRONT_WALL_THRESHOLD = 0.15
constexpr double SIDE_WALL_THRESHOLD = 0.08
constexpr double GERALD_WALL_THRESHOLD = 0.17
constexpr double WALL_CHANGED_THRESHOLD = 0.02
constexpr double ROT_TOLERANCE = 0.05
constexpr double TRACK_WIDTH_M = 0.0633
constexpr double ANALOG_MAX_DIST_M = 0.18
constexpr double ANALOG_MIN_DIST_M = 0.01
constexpr double WHEEL_RAD = 0.0145
constexpr double MIN_ABSTRACT_FORCE = 3.5
constexpr double TRACK_WIDTH_CU = smartmouse::maze::toCellUnits(TRACK_WIDTH_M)
constexpr double MAX_HARDWARE_SPEED_CUPS = smartmouse::maze::toCellUnits(MAX_HARDWARE_SPEED_MPS)
constexpr double MIN_SPEED_CUPS = smartmouse::maze::toCellUnits(MIN_SPEED_MPS)
constexpr double ANALOG_MAX_DIST_CU = smartmouse::maze::toCellUnits(ANALOG_MAX_DIST_M)
constexpr double ANALOG_MIN_DIST_CU = smartmouse::maze::toCellUnits(ANALOG_MIN_DIST_M)
Function Documentation
constexpr double smartmouse::kc::cellsToRad (double x)
References smartmouse::maze::UNIT_DIST_M, and WHEEL_RAD.
Referenced by RegulatedMotor::setAccelerationCpss(), and RegulatedMotor::setSetpointCps().
constexpr double smartmouse::kc::meterToRad (double x)
References WHEEL_RAD.
constexpr double smartmouse::kc::radToCU (double x)
References smartmouse::maze::UNIT_DIST_M.
Referenced by KinematicController::getCurrentForwardSpeedCUPS(), SimMouse::run(), KinematicController::run(), and StateWidget::StateCallback().
constexpr double smartmouse::kc::radToMeters (double x)
References WHEEL_RAD.
Referenced by RegulatedMotor::isStopped(), and Server::UpdateRobotState().
Variable Documentation
constexpr double smartmouse::kc::ANALOG_MAX_DIST_CU = smartmouse::maze::toCellUnits(ANALOG_MAX_DIST_M)
Referenced by Server::ComputeSensorDistToWall().
constexpr double smartmouse::kc::ANALOG_MAX_DIST_M = 0.18
Referenced by Server::ComputeSensorRange().
constexpr double smartmouse::kc::ANALOG_MIN_DIST_CU = smartmouse::maze::toCellUnits(ANALOG_MIN_DIST_M)
Referenced by Server::ComputeSensorDistToWall().
constexpr double smartmouse::kc::ANALOG_MIN_DIST_M = 0.01
bool smartmouse::kc::ARC_TURN = false
Referenced by WaitForStart::execute(), and Turn::initialize().
constexpr double smartmouse::kc::BACK_ANALOG_ANGLE = 1.35255
Referenced by KinematicController::estimate_pose().
constexpr double smartmouse::kc::BACK_SIDE_ANALOG_X = -0.0206
Referenced by KinematicController::estimate_pose().
constexpr double smartmouse::kc::BACK_SIDE_ANALOG_Y = 0.0335
Referenced by KinematicController::estimate_pose().
constexpr double smartmouse::kc::FRONT_ANALOG_ANGLE = 1.35255
Referenced by IRConverter::calibrate(), and KinematicController::estimate_pose().
constexpr double smartmouse::kc::FRONT_ANALOG_X = 0.056
Referenced by KinematicController::run().
constexpr double smartmouse::kc::FRONT_SIDE_ANALOG_X = 0.042
Referenced by KinematicController::estimate_pose().
constexpr double smartmouse::kc::FRONT_SIDE_ANALOG_Y = 0.0350
Referenced by IRConverter::calibrate(), and KinematicController::estimate_pose().
constexpr double smartmouse::kc::FRONT_WALL_THRESHOLD = 0.15
Referenced by SimMouse::checkWalls().
constexpr double smartmouse::kc::GERALD_ANGLE = 0.6544985
Referenced by KinematicController::estimate_pose().
constexpr double smartmouse::kc::GERALD_WALL_THRESHOLD = 0.17
Referenced by KinematicController::estimate_pose().
constexpr double smartmouse::kc::GERALD_X = 0.054
constexpr double smartmouse::kc::GERALD_Y = 0.018
const double smartmouse::kc::kVf = 1.0
constexpr double smartmouse::kc::MAX_HARDWARE_SPEED_CUPS = smartmouse::maze::toCellUnits(MAX_HARDWARE_SPEED_MPS)
constexpr double smartmouse::kc::MAX_HARDWARE_SPEED_MPS = 0.60
Referenced by WaitForStart::execute().
double smartmouse::kc::MAX_SPEED_CUPS = smartmouse::maze::toCellUnits(MAX_SPEED_MPS)
Referenced by WaitForStart::end(), and RegulatedMotor::setSetpointCps().
double smartmouse::kc::MAX_SPEED_MPS = 0.90
Referenced by WaitForStart::end().
constexpr double smartmouse::kc::MIN_ABSTRACT_FORCE = 3.5
Referenced by RegulatedMotor::isStopped(), and SimMouse::isStopped().
constexpr double smartmouse::kc::MIN_SPEED_CUPS = smartmouse::maze::toCellUnits(MIN_SPEED_MPS)
Referenced by RegulatedMotor::setSetpointCps().
constexpr double smartmouse::kc::MIN_SPEED_MPS = 0.014
constexpr double smartmouse::kc::ROT_TOLERANCE = 0.05
Referenced by TurnInPlace::isFinished().
constexpr double smartmouse::kc::SIDE_WALL_THRESHOLD = 0.08
Referenced by SimMouse::checkWalls(), and KinematicController::estimate_pose().
constexpr double smartmouse::kc::TRACK_WIDTH_CU = smartmouse::maze::toCellUnits(TRACK_WIDTH_M)
Referenced by KinematicController::forwardKinematics(), and TEST().
constexpr double smartmouse::kc::TRACK_WIDTH_M = 0.0633
constexpr double smartmouse::kc::WALL_CHANGED_THRESHOLD = 0.02
Referenced by KinematicController::estimate_pose().
constexpr double smartmouse::kc::WHEEL_RAD = 0.0145
Referenced by cellsToRad(), meterToRad(), and radToMeters().