SmartMouse_2018: Eigen::internal Namespace Reference
Eigen::internal Namespace Reference
Classes
struct abs_knowing_score
struct abs_knowing_score< Scalar, typename scalar_score_coeff_op< Scalar >::Score_is_abs >
struct accessors_level
struct add_assign_op
struct add_const
struct add_const< T & >
struct add_const_on_value_type
struct add_const_on_value_type< T & >
struct add_const_on_value_type< T * >
struct add_const_on_value_type< T *const >
struct add_const_on_value_type< T const *const >
struct add_const_on_value_type_if_arithmetic
class aligned_stack_memory_handler
struct all_t
struct all_unroller
struct all_unroller< Derived, 0, Rows >
struct all_unroller< Derived, Dynamic, Rows >
struct AllRange
class AmbiVector
struct any_unroller
struct any_unroller< Derived, 0, Rows >
struct any_unroller< Derived, Dynamic, Rows >
struct apply_rotation_in_the_plane_selector
struct apply_rotation_in_the_plane_selector< Scalar, OtherScalar, SizeAtCompileTime, MinAlignment, true >
struct array_size
struct array_size< const T(&)[N]>
struct array_size< T(&)[N]>
struct array_size< T, typename internal::enable_if<((T::SizeAtCompileTime &0)==0)>::type >
struct aseq_negate
struct aseq_negate< FixedInt< DynamicIndex > >
struct aseq_negate< FixedInt< N > >
struct aseq_negate< Index >
struct aseq_reverse_first_type
struct aseq_reverse_first_type< FirstType, SizeType, IncrType, false, true >
struct aseq_reverse_first_type< FirstType, SizeType, IncrType, true, false >
struct aseq_reverse_first_type< FirstType, SizeType, IncrType, true, true >
struct aseq_reverse_first_type_aux
struct aseq_reverse_first_type_aux< SizeType, IncrType, typename internal::enable_if< bool((SizeType::value+IncrType::value)|0x1)>::type >
struct assign_op
struct assign_op< DstScalar, void >
struct Assignment
struct Assignment< DstXprType, CwiseBinaryOp< internal::scalar_product_op< ScalarBis, Scalar >, const CwiseNullaryOp< internal::scalar_constant_op< ScalarBis >, Plain >, const Product< Lhs, Rhs, DefaultProduct > >, AssignFunc, Dense2Dense >
struct Assignment< DstXprType, Homogeneous< ArgType, Horizontal >, internal::assign_op< Scalar, typename ArgType::Scalar >, Dense2Dense >
struct Assignment< DstXprType, Homogeneous< ArgType, Vertical >, internal::assign_op< Scalar, typename ArgType::Scalar >, Dense2Dense >
struct Assignment< DstXprType, Inverse< ColPivHouseholderQR< MatrixType > >, internal::assign_op< typename DstXprType::Scalar, typename ColPivHouseholderQR< MatrixType >::Scalar >, Dense2Dense >
struct Assignment< DstXprType, Inverse< CompleteOrthogonalDecomposition< MatrixType > >, internal::assign_op< typename DstXprType::Scalar, typename CompleteOrthogonalDecomposition< MatrixType >::Scalar >, Dense2Dense >
struct Assignment< DstXprType, Inverse< FullPivHouseholderQR< MatrixType > >, internal::assign_op< typename DstXprType::Scalar, typename FullPivHouseholderQR< MatrixType >::Scalar >, Dense2Dense >
struct Assignment< DstXprType, Inverse< FullPivLU< MatrixType > >, internal::assign_op< typename DstXprType::Scalar, typename FullPivLU< MatrixType >::Scalar >, Dense2Dense >
struct Assignment< DstXprType, Inverse< PartialPivLU< MatrixType > >, internal::assign_op< typename DstXprType::Scalar, typename PartialPivLU< MatrixType >::Scalar >, Dense2Dense >
struct Assignment< DstXprType, Inverse< XprType >, internal::assign_op< typename DstXprType::Scalar, typename XprType::Scalar >, Dense2Dense >
struct Assignment< DstXprType, Product< Lhs, Rhs, AliasFreeProduct >, internal::add_assign_op< typename DstXprType::Scalar, typename Product< Lhs, Rhs, AliasFreeProduct >::Scalar >, Sparse2Dense >
struct Assignment< DstXprType, Product< Lhs, Rhs, AliasFreeProduct >, internal::assign_op< typename DstXprType::Scalar, typename Product< Lhs, Rhs, AliasFreeProduct >::Scalar >, Sparse2Dense >
struct Assignment< DstXprType, Product< Lhs, Rhs, AliasFreeProduct >, internal::sub_assign_op< typename DstXprType::Scalar, typename Product< Lhs, Rhs, AliasFreeProduct >::Scalar >, Sparse2Dense >
struct Assignment< DstXprType, Product< Lhs, Rhs, DefaultProduct >, internal::add_assign_op< Scalar, typename Product< Lhs, Rhs, DefaultProduct >::Scalar >, Dense2Triangular >
struct Assignment< DstXprType, Product< Lhs, Rhs, DefaultProduct >, internal::assign_op< Scalar, typename Product< Lhs, Rhs, DefaultProduct >::Scalar >, Dense2Triangular >
struct Assignment< DstXprType, Product< Lhs, Rhs, DefaultProduct >, internal::sub_assign_op< Scalar, typename Product< Lhs, Rhs, DefaultProduct >::Scalar >, Dense2Triangular >
struct Assignment< DstXprType, Product< Lhs, Rhs, Options >, internal::add_assign_op< Scalar, Scalar >, Dense2Dense, typename enable_if<(Options==DefaultProduct||Options==AliasFreeProduct)>::type >
struct Assignment< DstXprType, Product< Lhs, Rhs, Options >, internal::assign_op< Scalar, Scalar >, Dense2Dense, typename enable_if<(Options==DefaultProduct||Options==AliasFreeProduct)>::type >
struct Assignment< DstXprType, Product< Lhs, Rhs, Options >, internal::sub_assign_op< Scalar, Scalar >, Dense2Dense, typename enable_if<(Options==DefaultProduct||Options==AliasFreeProduct)>::type >
struct Assignment< DstXprType, Solve< CwiseUnaryOp< internal::scalar_conjugate_op< typename DecType::Scalar >, const Transpose< const DecType > >, RhsType >, internal::assign_op< Scalar, Scalar >, Dense2Dense >
struct Assignment< DstXprType, Solve< DecType, RhsType >, internal::assign_op< Scalar, Scalar >, Dense2Dense >
struct Assignment< DstXprType, Solve< DecType, RhsType >, internal::assign_op< Scalar, Scalar >, Sparse2Sparse >
struct Assignment< DstXprType, Solve< Transpose< const DecType >, RhsType >, internal::assign_op< Scalar, Scalar >, Dense2Dense >
struct Assignment< DstXprType, SolveWithGuess< DecType, RhsType, GuessType >, internal::assign_op< Scalar, Scalar >, Dense2Dense >
struct Assignment< DstXprType, SparseQRMatrixQReturnType< SparseQRType >, internal::assign_op< typename DstXprType::Scalar, typename DstXprType::Scalar >, Sparse2Dense >
struct Assignment< DstXprType, SparseQRMatrixQReturnType< SparseQRType >, internal::assign_op< typename DstXprType::Scalar, typename DstXprType::Scalar >, Sparse2Sparse >
struct Assignment< DstXprType, SparseSymmetricPermutationProduct< MatrixType, Mode >, internal::assign_op< Scalar, typename MatrixType::Scalar >, Sparse2Sparse >
struct Assignment< DstXprType, SrcXprType, Functor, Dense2Dense, Weak >
struct Assignment< DstXprType, SrcXprType, Functor, Dense2Triangular >
struct Assignment< DstXprType, SrcXprType, Functor, Diagonal2Dense >
struct Assignment< DstXprType, SrcXprType, Functor, Diagonal2Sparse >
struct Assignment< DstXprType, SrcXprType, Functor, EigenBase2EigenBase, Weak >
struct Assignment< DstXprType, SrcXprType, Functor, Sparse2Dense >
struct Assignment< DstXprType, SrcXprType, Functor, Sparse2Sparse >
struct Assignment< DstXprType, SrcXprType, Functor, SparseSelfAdjoint2Sparse >
struct Assignment< DstXprType, SrcXprType, Functor, Triangular2Dense >
struct Assignment< DstXprType, SrcXprType, Functor, Triangular2Triangular >
struct assignment_from_xpr_op_product
struct AssignmentKind
struct AssignmentKind< DenseShape, BandShape >
struct AssignmentKind< DenseShape, DenseShape >
struct AssignmentKind< DenseShape, DiagonalShape >
struct AssignmentKind< DenseShape, HomogeneousShape >
struct AssignmentKind< DenseShape, PermutationShape >
struct AssignmentKind< DenseShape, SparseShape >
struct AssignmentKind< DenseShape, SparseTriangularShape >
struct AssignmentKind< DenseShape, TriangularShape >
struct AssignmentKind< SparseSelfAdjointShape, SparseShape >
struct AssignmentKind< SparseShape, DiagonalShape >
struct AssignmentKind< SparseShape, SparseSelfAdjointShape >
struct AssignmentKind< SparseShape, SparseShape >
struct AssignmentKind< SparseShape, SparseTriangularShape >
struct AssignmentKind< TriangularShape, DenseShape >
struct AssignmentKind< TriangularShape, TriangularShape >
class BandMatrix
Represents a rectangular matrix with a banded storage.
class BandMatrixBase
class BandMatrixWrapper
struct BandShape
struct binary_evaluator
struct binary_evaluator< CwiseBinaryOp< BinaryOp, Lhs, Rhs >, IndexBased, IndexBased >
struct binary_evaluator< CwiseBinaryOp< BinaryOp, Lhs, Rhs >, IndexBased, IteratorBased >
struct binary_evaluator< CwiseBinaryOp< BinaryOp, Lhs, Rhs >, IteratorBased, IndexBased >
struct binary_evaluator< CwiseBinaryOp< BinaryOp, Lhs, Rhs >, IteratorBased, IteratorBased >
struct binary_evaluator< CwiseBinaryOp< scalar_boolean_and_op, Lhs, Rhs >, IndexBased, IteratorBased >
struct binary_evaluator< CwiseBinaryOp< scalar_boolean_and_op, Lhs, Rhs >, IteratorBased, IndexBased >
struct binary_evaluator< CwiseBinaryOp< scalar_boolean_and_op, Lhs, Rhs >, IteratorBased, IteratorBased >
struct binary_evaluator< CwiseBinaryOp< scalar_product_op< T1, T2 >, Lhs, Rhs >, IndexBased, IteratorBased >
struct binary_evaluator< CwiseBinaryOp< scalar_product_op< T1, T2 >, Lhs, Rhs >, IteratorBased, IndexBased >
struct binary_evaluator< CwiseBinaryOp< scalar_product_op< T1, T2 >, Lhs, Rhs >, IteratorBased, IteratorBased >
struct binary_evaluator< CwiseBinaryOp< scalar_quotient_op< T1, T2 >, Lhs, Rhs >, IteratorBased, IndexBased >
struct binary_op_base
struct binary_result_of_select
struct binary_result_of_select< Func, ArgType0, ArgType1, sizeof(has_std_result_type)>
struct binary_result_of_select< Func, ArgType0, ArgType1, sizeof(has_tr1_result)>
struct binary_sparse_evaluator
struct bind1st_op
struct bind2nd_op
class blas_data_mapper
struct blas_traits
struct blas_traits< const T >
struct blas_traits< CwiseBinaryOp< scalar_product_op< Scalar >, const CwiseNullaryOp< scalar_constant_op< Scalar >, Plain >, NestedXpr > >
struct blas_traits< CwiseBinaryOp< scalar_product_op< Scalar >, const CwiseNullaryOp< scalar_constant_op< Scalar >, Plain1 >, const CwiseNullaryOp< scalar_constant_op< Scalar >, Plain2 > > >
struct blas_traits< CwiseBinaryOp< scalar_product_op< Scalar >, NestedXpr, const CwiseNullaryOp< scalar_constant_op< Scalar >, Plain > > >
struct blas_traits< CwiseUnaryOp< scalar_conjugate_op< Scalar >, NestedXpr > >
struct blas_traits< CwiseUnaryOp< scalar_opposite_op< Scalar >, NestedXpr > >
struct blas_traits< Transpose< NestedXpr > >
class BlasLinearMapper
class BlasVectorMapper
struct block_evaluator
struct block_evaluator< ArgType, BlockRows, BlockCols, InnerPanel, false >
struct block_evaluator< ArgType, BlockRows, BlockCols, InnerPanel, true >
class BlockImpl_dense
class BlockImpl_dense< XprType, BlockRows, BlockCols, InnerPanel, true >
struct CacheSizes
struct cast_return_type
struct check_rows_cols_for_overflow
struct check_rows_cols_for_overflow< Dynamic >
struct check_transpose_aliasing_compile_time_selector
struct check_transpose_aliasing_compile_time_selector< DestIsTransposed, CwiseBinaryOp< BinOp, DerivedA, DerivedB > >
struct check_transpose_aliasing_run_time_selector
struct check_transpose_aliasing_run_time_selector< Scalar, DestIsTransposed, CwiseBinaryOp< BinOp, DerivedA, DerivedB > >
struct checkTransposeAliasing_impl
struct checkTransposeAliasing_impl< Derived, OtherDerived, false >
struct cholmod_configure_matrix
struct cholmod_configure_matrix< double >
struct cholmod_configure_matrix< std::complex< double > >
struct cleanup_index_type
struct cleanup_index_type< FixedInt< N >(*)(), DynamicKey >
struct cleanup_index_type< T, DynamicKey, typename internal::enable_if< internal::is_integral< T >::value >::type >
struct cleanup_index_type< VariableAndFixedInt< DynamicKey >, DynamicKey >
struct cleanup_index_type< VariableAndFixedInt< N >, DynamicKey >
struct cleanup_seq_incr
struct coeff_visitor
struct colamd_col
struct Colamd_Row
struct column_dfs_traits
struct complex_schur_reduce_to_hessenberg
struct complex_schur_reduce_to_hessenberg< MatrixType, false >
class CompressedStorage
struct compute_default_alignment
struct compute_default_alignment< T, Dynamic >
struct compute_default_alignment_helper
struct compute_inverse
struct compute_inverse< MatrixType, ResultType, 1 >
struct compute_inverse< MatrixType, ResultType, 2 >
struct compute_inverse< MatrixType, ResultType, 3 >
struct compute_inverse< MatrixType, ResultType, 4 >
struct compute_inverse_and_det_with_check
struct compute_inverse_and_det_with_check< MatrixType, ResultType, 1 >
struct compute_inverse_and_det_with_check< MatrixType, ResultType, 2 >
struct compute_inverse_and_det_with_check< MatrixType, ResultType, 3 >
struct compute_inverse_and_det_with_check< MatrixType, ResultType, 4 >
struct compute_inverse_size4
struct compute_inverse_size4< Architecture::SSE, double, MatrixType, ResultType >
struct compute_inverse_size4< Architecture::SSE, float, MatrixType, ResultType >
class compute_matrix_flags
struct conditional
struct conditional< false, Then, Else >
struct conj_expr_if
struct conj_helper
struct conj_helper< Packet1cd, Packet1cd, false, true >
struct conj_helper< Packet1cd, Packet1cd, true, false >
struct conj_helper< Packet1cd, Packet1cd, true, true >
struct conj_helper< Packet2cd, Packet2cd, false, true >
struct conj_helper< Packet2cd, Packet2cd, true, false >
struct conj_helper< Packet2cd, Packet2cd, true, true >
struct conj_helper< Packet2cf, Packet2cf, false, true >
struct conj_helper< Packet2cf, Packet2cf, true, false >
struct conj_helper< Packet2cf, Packet2cf, true, true >
struct conj_helper< Packet4cf, Packet4cf, false, true >
struct conj_helper< Packet4cf, Packet4cf, true, false >
struct conj_helper< Packet4cf, Packet4cf, true, true >
struct conj_helper< RealScalar, std::complex< RealScalar >, false, Conj >
struct conj_helper< Scalar, Scalar, false, false >
struct conj_helper< std::complex< RealScalar >, RealScalar, Conj, false >
struct conj_helper< std::complex< RealScalar >, std::complex< RealScalar >, false, true >
struct conj_helper< std::complex< RealScalar >, std::complex< RealScalar >, true, false >
struct conj_helper< std::complex< RealScalar >, std::complex< RealScalar >, true, true >
struct conj_if
struct conj_if< false >
struct conj_if< true >
struct conservative_resize_like_impl
struct conservative_resize_like_impl< Derived, OtherDerived, true >
struct conservative_sparse_sparse_product_selector
struct conservative_sparse_sparse_product_selector< Lhs, Rhs, ResultType, ColMajor, ColMajor, ColMajor >
struct conservative_sparse_sparse_product_selector< Lhs, Rhs, ResultType, ColMajor, ColMajor, RowMajor >
struct conservative_sparse_sparse_product_selector< Lhs, Rhs, ResultType, ColMajor, RowMajor, ColMajor >
struct conservative_sparse_sparse_product_selector< Lhs, Rhs, ResultType, ColMajor, RowMajor, RowMajor >
struct conservative_sparse_sparse_product_selector< Lhs, Rhs, ResultType, RowMajor, ColMajor, ColMajor >
struct conservative_sparse_sparse_product_selector< Lhs, Rhs, ResultType, RowMajor, ColMajor, RowMajor >
struct conservative_sparse_sparse_product_selector< Lhs, Rhs, ResultType, RowMajor, RowMajor, ColMajor >
struct conservative_sparse_sparse_product_selector< Lhs, Rhs, ResultType, RowMajor, RowMajor, RowMajor >
class const_blas_data_mapper
struct constructor_without_unaligned_array_assert
struct copy_using_evaluator_DefaultTraversal_CompleteUnrolling
struct copy_using_evaluator_DefaultTraversal_CompleteUnrolling< Kernel, Stop, Stop >
struct copy_using_evaluator_DefaultTraversal_InnerUnrolling
struct copy_using_evaluator_DefaultTraversal_InnerUnrolling< Kernel, Stop, Stop >
struct copy_using_evaluator_innervec_CompleteUnrolling
struct copy_using_evaluator_innervec_CompleteUnrolling< Kernel, Stop, Stop >
struct copy_using_evaluator_innervec_InnerUnrolling
struct copy_using_evaluator_innervec_InnerUnrolling< Kernel, Stop, Stop, SrcAlignment, DstAlignment >
struct copy_using_evaluator_LinearTraversal_CompleteUnrolling
struct copy_using_evaluator_LinearTraversal_CompleteUnrolling< Kernel, Stop, Stop >
struct copy_using_evaluator_traits
struct cross3_impl
struct cross3_impl< Architecture::SSE, VectorLhs, VectorRhs, float, true >
struct cwise_promote_storage_order
struct cwise_promote_storage_order< LhsKind, Sparse, LhsOrder, RhsOrder >
struct cwise_promote_storage_order< Sparse, RhsKind, LhsOrder, RhsOrder >
struct cwise_promote_storage_order< Sparse, Sparse, Order, Order >
struct cwise_promote_storage_type
struct cwise_promote_storage_type< A, A, Functor >
struct cwise_promote_storage_type< A, Dense, Functor >
struct cwise_promote_storage_type< Dense, B, Functor >
struct cwise_promote_storage_type< Dense, Dense, Functor >
struct cwise_promote_storage_type< Dense, Sparse, Functor >
struct cwise_promote_storage_type< Sparse, Dense, Functor >
struct decrement_size
struct default_digits10_impl
struct default_digits10_impl< T, false, false >
struct default_digits10_impl< T, false, true >
struct default_packet_traits
struct Dense2Dense
struct Dense2Triangular
struct dense_assignment_loop
struct dense_assignment_loop< Kernel, DefaultTraversal, CompleteUnrolling >
struct dense_assignment_loop< Kernel, DefaultTraversal, InnerUnrolling >
struct dense_assignment_loop< Kernel, DefaultTraversal, NoUnrolling >
struct dense_assignment_loop< Kernel, InnerVectorizedTraversal, CompleteUnrolling >
struct dense_assignment_loop< Kernel, InnerVectorizedTraversal, InnerUnrolling >
struct dense_assignment_loop< Kernel, InnerVectorizedTraversal, NoUnrolling >
struct dense_assignment_loop< Kernel, LinearTraversal, CompleteUnrolling >
struct dense_assignment_loop< Kernel, LinearTraversal, NoUnrolling >
struct dense_assignment_loop< Kernel, LinearVectorizedTraversal, CompleteUnrolling >
struct dense_assignment_loop< Kernel, LinearVectorizedTraversal, NoUnrolling >
struct dense_assignment_loop< Kernel, SliceVectorizedTraversal, NoUnrolling >
class dense_product_base
class dense_product_base< Lhs, Rhs, Option, InnerProduct >
struct dense_xpr_base
struct dense_xpr_base< Derived, ArrayXpr >
struct dense_xpr_base< Derived, MatrixXpr >
struct determinant_impl
struct determinant_impl< Derived, 1 >
struct determinant_impl< Derived, 2 >
struct determinant_impl< Derived, 3 >
struct determinant_impl< Derived, 4 >
struct Diagonal2Dense
struct Diagonal2Sparse
struct diagonal_product_evaluator_base
struct direct_selfadjoint_eigenvalues
struct direct_selfadjoint_eigenvalues< SolverType, 2, false >
struct direct_selfadjoint_eigenvalues< SolverType, 3, false >
struct div_assign_op
struct dot_nocheck
struct dot_nocheck< T, U, true >
struct DoublePacket
struct EigenBase2EigenBase
struct eigenvalues_selector
struct eigenvalues_selector< Derived, false >
struct enable_if
struct enable_if< true, T >
struct enable_if_ref
struct enable_if_ref< Ref< T >, Derived >
struct EnableIf
struct etor_product_coeff_impl
struct etor_product_packet_impl
struct etor_product_packet_impl< ColMajor, 0, Lhs, Rhs, Packet, LoadMode >
struct etor_product_packet_impl< ColMajor, 1, Lhs, Rhs, Packet, LoadMode >
struct etor_product_packet_impl< ColMajor, Dynamic, Lhs, Rhs, Packet, LoadMode >
struct etor_product_packet_impl< ColMajor, UnrollingIndex, Lhs, Rhs, Packet, LoadMode >
struct etor_product_packet_impl< RowMajor, 0, Lhs, Rhs, Packet, LoadMode >
struct etor_product_packet_impl< RowMajor, 1, Lhs, Rhs, Packet, LoadMode >
struct etor_product_packet_impl< RowMajor, Dynamic, Lhs, Rhs, Packet, LoadMode >
struct etor_product_packet_impl< RowMajor, UnrollingIndex, Lhs, Rhs, Packet, LoadMode >
struct eval
struct eval< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >, Dense >
struct eval< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >, Dense >
struct eval< T, Dense >
struct eval< T, DiagonalShape >
struct eval< T, Sparse >
class EvalToTemp
struct evaluator
struct evaluator< Array< Scalar, Rows, Cols, Options, MaxRows, MaxCols > >
struct evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel > >
struct evaluator< const T >
struct evaluator< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >
struct evaluator< CwiseBinaryOp< internal::scalar_product_op< Scalar1, Scalar2 >, const CwiseNullaryOp< internal::scalar_constant_op< Scalar1 >, Plain1 >, const Product< Lhs, Rhs, DefaultProduct > > >
struct evaluator< CwiseNullaryOp< NullaryOp, PlainObjectType > >
struct evaluator< CwiseTernaryOp< TernaryOp, Arg1, Arg2, Arg3 > >
struct evaluator< Diagonal< ArgType, DiagIndex > >
struct evaluator< Diagonal< const Product< Lhs, Rhs, DefaultProduct >, DiagIndex > >
struct evaluator< EvalToTemp< ArgType > >
struct evaluator< Map< const SparseMatrix< MatScalar, MatOptions, MatIndex >, Options, StrideType > >
struct evaluator< Map< PlainObjectType, MapOptions, StrideType > >
struct evaluator< Map< SparseMatrix< MatScalar, MatOptions, MatIndex >, Options, StrideType > >
struct evaluator< MappedSparseMatrix< _Scalar, _Options, _StorageIndex > >
struct evaluator< Matrix< Scalar, Rows, Cols, Options, MaxRows, MaxCols > >
struct evaluator< PartialReduxExpr< ArgType, MemberOp, Direction > >
struct evaluator< PlainObjectBase< Derived > >
struct evaluator< Product< Lhs, Rhs, Options > >
struct evaluator< Ref< const SparseMatrix< MatScalar, MatOptions, MatIndex >, Options, StrideType > >
struct evaluator< Ref< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType > >
struct evaluator< Ref< PlainObjectType, RefOptions, StrideType > >
struct evaluator< Ref< SparseMatrix< MatScalar, MatOptions, MatIndex >, Options, StrideType > >
struct evaluator< Ref< SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType > >
struct evaluator< ReturnByValue< Derived > >
struct evaluator< Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType > >
struct evaluator< Solve< Decomposition, RhsType > >
struct evaluator< SolveWithGuess< Decomposition, RhsType, GuessType > >
struct evaluator< SparseCompressedBase< Derived > >
struct evaluator< SparseMatrix< _Scalar, _Options, _StorageIndex > >
struct evaluator< SparseVector< _Scalar, _Options, _Index > >
struct evaluator_assume_aliasing
struct evaluator_assume_aliasing< CwiseBinaryOp< internal::scalar_difference_op< typename OtherXpr::Scalar, typename Product< Lhs, Rhs, DefaultProduct >::Scalar >, const OtherXpr, const Product< Lhs, Rhs, DefaultProduct > >, DenseShape >
struct evaluator_assume_aliasing< CwiseBinaryOp< internal::scalar_product_op< Scalar1, Scalar2 >, const CwiseNullaryOp< internal::scalar_constant_op< Scalar1 >, Plain1 >, const Product< Lhs, Rhs, DefaultProduct > > >
struct evaluator_assume_aliasing< CwiseBinaryOp< internal::scalar_sum_op< typename OtherXpr::Scalar, typename Product< Lhs, Rhs, DefaultProduct >::Scalar >, const OtherXpr, const Product< Lhs, Rhs, DefaultProduct > >, DenseShape >
struct evaluator_assume_aliasing< Product< Lhs, Rhs, DefaultProduct > >
struct evaluator_base
struct evaluator_traits
struct evaluator_traits< BandMatrix< _Scalar, _Rows, _Cols, _Supers, _Subs, _Options > >
struct evaluator_traits< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >
struct evaluator_traits< Homogeneous< ArgType, Direction > >
struct evaluator_traits< HouseholderSequence< VectorsType, CoeffsType, Side > >
struct evaluator_traits< SelfAdjointView< MatrixType, Mode > >
struct evaluator_traits< SparseQRMatrixQReturnType< SparseQRType > >
struct evaluator_traits< SparseSelfAdjointView< MatrixType, Mode > >
struct evaluator_traits< TriangularView< MatrixType, Mode > >
struct evaluator_traits_base
struct evaluator_wrapper_base
struct extract_data_selector
struct extract_data_selector< T, false >
struct false_type
struct find_best_packet
struct find_best_packet_helper
struct find_best_packet_helper< Size, PacketType, false >
struct find_best_packet_helper< Size, PacketType, true >
struct first_aligned_impl
struct first_aligned_impl< Alignment, Derived, false >
class FixedInt
struct FullPivHouseholderQRMatrixQReturnType
Expression type for return value of FullPivHouseholderQR::matrixQ()
struct functor_has_linear_access
struct functor_traits
struct functor_traits< add_assign_op< DstScalar, SrcScalar > >
struct functor_traits< assign_op< DstScalar, SrcScalar > >
struct functor_traits< bind1st_op< BinaryOp > >
struct functor_traits< bind2nd_op< BinaryOp > >
struct functor_traits< div_assign_op< DstScalar, SrcScalar > >
struct functor_traits< linspaced_op< Scalar, PacketType > >
struct functor_traits< max_coeff_visitor< Scalar > >
struct functor_traits< min_coeff_visitor< Scalar > >
struct functor_traits< mul_assign_op< DstScalar, SrcScalar > >
struct functor_traits< scalar_abs2_op< Scalar > >
struct functor_traits< scalar_abs_op< Scalar > >
struct functor_traits< scalar_acos_op< Scalar > >
struct functor_traits< scalar_arg_op< Scalar > >
struct functor_traits< scalar_asin_op< Scalar > >
struct functor_traits< scalar_atan_op< Scalar > >
struct functor_traits< scalar_boolean_and_op >
struct functor_traits< scalar_boolean_not_op< Scalar > >
struct functor_traits< scalar_boolean_or_op >
struct functor_traits< scalar_boolean_xor_op >
struct functor_traits< scalar_cast_op< Eigen::half, float > >
struct functor_traits< scalar_cast_op< float, Eigen::half > >
struct functor_traits< scalar_cast_op< int, Eigen::half > >
struct functor_traits< scalar_cast_op< Scalar, NewType > >
struct functor_traits< scalar_ceil_op< Scalar > >
struct functor_traits< scalar_cmp_op< LhsScalar, RhsScalar, cmp > >
struct functor_traits< scalar_conj_product_op< LhsScalar, RhsScalar > >
struct functor_traits< scalar_conjugate_op< Scalar > >
struct functor_traits< scalar_constant_op< Scalar > >
struct functor_traits< scalar_cos_op< Scalar > >
struct functor_traits< scalar_cosh_op< Scalar > >
struct functor_traits< scalar_cube_op< Scalar > >
struct functor_traits< scalar_difference_op< LhsScalar, RhsScalar > >
struct functor_traits< scalar_exp_op< Scalar > >
struct functor_traits< scalar_expm1_op< Scalar > >
struct functor_traits< scalar_floor_op< Scalar > >
struct functor_traits< scalar_hypot_op< Scalar, Scalar > >
struct functor_traits< scalar_identity_op< Scalar > >
struct functor_traits< scalar_imag_op< Scalar > >
struct functor_traits< scalar_imag_ref_op< Scalar > >
struct functor_traits< scalar_inverse_op< Scalar > >
struct functor_traits< scalar_isfinite_op< Scalar > >
struct functor_traits< scalar_isinf_op< Scalar > >
struct functor_traits< scalar_isnan_op< Scalar > >
struct functor_traits< scalar_log10_op< Scalar > >
struct functor_traits< scalar_log1p_op< Scalar > >
struct functor_traits< scalar_log_op< Scalar > >
struct functor_traits< scalar_max_op< LhsScalar, RhsScalar > >
struct functor_traits< scalar_min_op< LhsScalar, RhsScalar > >
struct functor_traits< scalar_opposite_op< Scalar > >
struct functor_traits< scalar_pow_op< Scalar, Exponent > >
struct functor_traits< scalar_product_op< LhsScalar, RhsScalar > >
struct functor_traits< scalar_quotient_op< LhsScalar, RhsScalar > >
struct functor_traits< scalar_random_op< Scalar > >
struct functor_traits< scalar_real_op< Scalar > >
struct functor_traits< scalar_real_ref_op< Scalar > >
struct functor_traits< scalar_round_op< Scalar > >
struct functor_traits< scalar_rsqrt_op< Scalar > >
struct functor_traits< scalar_score_coeff_op< Scalar > >
struct functor_traits< scalar_sign_op< Scalar > >
struct functor_traits< scalar_sin_op< Scalar > >
struct functor_traits< scalar_sinh_op< Scalar > >
struct functor_traits< scalar_sqrt_op< Scalar > >
struct functor_traits< scalar_square_op< Scalar > >
struct functor_traits< scalar_sum_op< LhsScalar, RhsScalar > >
struct functor_traits< scalar_tan_op< Scalar > >
struct functor_traits< scalar_tanh_op< Scalar > >
struct functor_traits< std::binary_negate< T > >
struct functor_traits< std::binder1st< T > >
struct functor_traits< std::binder2nd< T > >
struct functor_traits< std::divides< T > >
struct functor_traits< std::equal_to< T > >
struct functor_traits< std::greater< T > >
struct functor_traits< std::greater_equal< T > >
struct functor_traits< std::less< T > >
struct functor_traits< std::less_equal< T > >
struct functor_traits< std::logical_and< T > >
struct functor_traits< std::logical_not< T > >
struct functor_traits< std::logical_or< T > >
struct functor_traits< std::minus< T > >
struct functor_traits< std::multiplies< T > >
struct functor_traits< std::negate< T > >
struct functor_traits< std::not_equal_to< T > >
struct functor_traits< std::plus< T > >
struct functor_traits< std::unary_negate< T > >
struct functor_traits< sub_assign_op< DstScalar, SrcScalar > >
struct functor_traits< swap_assign_op< Scalar > >
struct gebp_kernel
struct gebp_madd_selector
struct gebp_madd_selector< CJ, T, T, T, T >
class gebp_traits
class gebp_traits< RealScalar, std::complex< RealScalar >, false, _ConjRhs >
class gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >
class gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >
class gemm_blocking_space
class gemm_blocking_space< StorageOrder, _LhsScalar, _RhsScalar, MaxRows, MaxCols, MaxDepth, KcFactor, false >
class gemm_blocking_space< StorageOrder, _LhsScalar, _RhsScalar, MaxRows, MaxCols, MaxDepth, KcFactor, true >
struct gemm_functor
struct gemm_pack_lhs
struct gemm_pack_lhs< Scalar, Index, DataMapper, Pack1, Pack2, ColMajor, Conjugate, PanelMode >
struct gemm_pack_lhs< Scalar, Index, DataMapper, Pack1, Pack2, RowMajor, Conjugate, PanelMode >
struct gemm_pack_rhs
struct gemm_pack_rhs< Scalar, Index, DataMapper, nr, ColMajor, Conjugate, PanelMode >
struct gemm_pack_rhs< Scalar, Index, DataMapper, nr, RowMajor, Conjugate, PanelMode >
struct GemmParallelInfo
struct gemv_dense_selector
struct gemv_dense_selector< OnTheLeft, StorageOrder, BlasCompatible >
struct gemv_dense_selector< OnTheRight, ColMajor, false >
struct gemv_dense_selector< OnTheRight, ColMajor, true >
struct gemv_dense_selector< OnTheRight, RowMajor, false >
struct gemv_dense_selector< OnTheRight, RowMajor, true >
struct gemv_static_vector_if
struct gemv_static_vector_if< Scalar, Size, Dynamic, true >
struct gemv_static_vector_if< Scalar, Size, MaxSize, false >
struct gemv_static_vector_if< Scalar, Size, MaxSize, true >
struct general_matrix_matrix_product
struct general_matrix_matrix_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor >
struct general_matrix_matrix_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, RowMajor >
struct general_matrix_matrix_rankupdate
struct general_matrix_matrix_triangular_product
struct general_matrix_matrix_triangular_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor, UpLo, Version >
struct general_matrix_matrix_triangular_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, RowMajor, UpLo, Version >
struct general_matrix_vector_product
struct general_matrix_vector_product< Index, LhsScalar, LhsMapper, ColMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >
struct general_matrix_vector_product< Index, LhsScalar, LhsMapper, RowMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >
struct general_matrix_vector_product_gemv
class generic_dense_assignment_kernel
class generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized >
class generic_matrix_wrapper
class generic_matrix_wrapper< MatrixType, false >
class generic_matrix_wrapper< MatrixType, true >
struct generic_product_impl
struct generic_product_impl< Homogeneous< LhsArg, Horizontal >, Rhs, HomogeneousShape, DenseShape, ProductTag >
struct generic_product_impl< Inverse< Lhs >, Rhs, PermutationShape, MatrixShape, ProductTag >
struct generic_product_impl< Lhs, Homogeneous< RhsArg, Vertical >, DenseShape, HomogeneousShape, ProductTag >
struct generic_product_impl< Lhs, Homogeneous< RhsArg, Vertical >, TriangularShape, HomogeneousShape, ProductTag >
struct generic_product_impl< Lhs, Inverse< Rhs >, MatrixShape, PermutationShape, ProductTag >
struct generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, CoeffBasedProductMode >
struct generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, GemmProduct >
struct generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, GemvProduct >
struct generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, InnerProduct >
struct generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, LazyCoeffBasedProductMode >
struct generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, OuterProduct >
struct generic_product_impl< Lhs, Rhs, DenseShape, SelfAdjointShape, ProductTag >
struct generic_product_impl< Lhs, Rhs, DenseShape, SparseShape, ProductType >
struct generic_product_impl< Lhs, Rhs, DenseShape, SparseTriangularShape, ProductType >
struct generic_product_impl< Lhs, Rhs, DenseShape, TriangularShape, ProductTag >
struct generic_product_impl< Lhs, Rhs, MatrixShape, PermutationShape, ProductTag >
struct generic_product_impl< Lhs, Rhs, MatrixShape, TranspositionsShape, ProductTag >
struct generic_product_impl< Lhs, Rhs, PermutationShape, MatrixShape, ProductTag >
struct generic_product_impl< Lhs, Rhs, SelfAdjointShape, DenseShape, ProductTag >
struct generic_product_impl< Lhs, Rhs, SparseShape, DenseShape, ProductType >
struct generic_product_impl< Lhs, Rhs, SparseShape, SparseShape, ProductType >
struct generic_product_impl< Lhs, Rhs, SparseShape, SparseTriangularShape, ProductType >
struct generic_product_impl< Lhs, Rhs, SparseTriangularShape, DenseShape, ProductType >
struct generic_product_impl< Lhs, Rhs, SparseTriangularShape, SparseShape, ProductType >
struct generic_product_impl< Lhs, Rhs, TranspositionsShape, MatrixShape, ProductTag >
struct generic_product_impl< Lhs, Rhs, TriangularShape, DenseShape, ProductTag >
struct generic_product_impl< Lhs, RhsView, DenseShape, SparseSelfAdjointShape, ProductType >
struct generic_product_impl< Lhs, Transpose< Rhs >, MatrixShape, TranspositionsShape, ProductTag >
struct generic_product_impl< LhsView, Rhs, SparseSelfAdjointShape, DenseShape, ProductType >
struct generic_product_impl< Transform< Scalar, Dim, Mode, Options >, Homogeneous< RhsArg, Vertical >, DenseShape, HomogeneousShape, ProductTag >
struct generic_product_impl< Transpose< Lhs >, Rhs, TranspositionsShape, MatrixShape, ProductTag >
struct generic_product_impl_base
struct generic_xpr_base
struct generic_xpr_base< Derived, MatrixXpr, SolverStorage >
struct generic_xpr_base< Derived, MatrixXpr, Sparse >
struct generic_xpr_base< Derived, XprKind, Dense >
struct get_compile_time_incr
struct get_compile_time_incr< AllRange< Size > >
struct get_compile_time_incr< ArithmeticSequence< FirstType, SizeType, IncrType > >
struct get_compile_time_incr< SingleRange >
struct get_factor
struct get_factor< Scalar, typename NumTraits< Scalar >::Real >
struct get_fixed_value
struct get_fixed_value< FixedInt< N >(*)(), Default >
struct get_fixed_value< FixedInt< N >, Default >
struct get_fixed_value< variable_if_dynamic< T, N >, Default >
struct get_fixed_value< VariableAndFixedInt< N >, Default >
struct glue_shapes
struct glue_shapes< DenseShape, TriangularShape >
struct glue_shapes< SparseShape, SelfAdjointShape >
struct glue_shapes< SparseShape, TriangularShape >
struct has_binary_operator
struct has_binary_operator<linspaced_op< Scalar, PacketType >, IndexType >
struct has_binary_operator<scalar_constant_op< Scalar >, IndexType >
struct has_binary_operator<scalar_identity_op< Scalar >, IndexType >
struct has_binary_operator<scalar_random_op< Scalar >, IndexType >
struct has_direct_access
struct has_none
struct has_nullary_operator
struct has_nullary_operator<linspaced_op< Scalar, PacketType >, IndexType >
struct has_nullary_operator<scalar_constant_op< Scalar >, IndexType >
struct has_nullary_operator<scalar_identity_op< Scalar >, IndexType >
struct has_nullary_operator<scalar_random_op< Scalar >, IndexType >
struct has_ReturnType
struct has_std_result_type
struct has_tr1_result
struct has_unary_operator
struct has_unary_operator<linspaced_op< Scalar, PacketType >, IndexType >
struct has_unary_operator<scalar_constant_op< Scalar >, IndexType >
struct has_unary_operator<scalar_identity_op< Scalar >, IndexType >
struct has_unary_operator<scalar_random_op< Scalar >, IndexType >
struct HessenbergDecompositionMatrixHReturnType
Expression type for return value of HessenbergDecomposition::matrixH()
struct homogeneous_left_product_impl
struct homogeneous_left_product_impl< Homogeneous< MatrixType, Vertical >, Lhs >
struct homogeneous_left_product_refactoring_helper
struct homogeneous_right_product_impl
struct homogeneous_right_product_impl< Homogeneous< MatrixType, Horizontal >, Rhs >
struct homogeneous_right_product_refactoring_helper
struct householder_qr_inplace_blocked
struct HouseholderSequenceShape
struct hseq_side_dependent_impl
struct hseq_side_dependent_impl< VectorsType, CoeffsType, OnTheRight >
struct image_retval
struct image_retval< FullPivLU< _MatrixType > >
class image_retval_base
struct IndexBased
struct IndexedViewCompatibleType
struct IndexedViewCompatibleType< all_t, XprSize >
struct IndexedViewCompatibleType< ArithmeticSequence< FirstType, SizeType, IncrType >, XprSize >
struct IndexedViewCompatibleType< T, XprSize, typename enable_if< Symbolic::is_symbolic< T >::value >::type >
struct IndexedViewCompatibleType< T, XprSize, typename internal::enable_if< internal::is_integral< T >::value >::type >
class inner_iterator_selector
class inner_iterator_selector< XprType, IndexBased >
class inner_iterator_selector< XprType, IteratorBased >
struct inner_stride_at_compile_time
struct inner_stride_at_compile_time< Derived, false >
struct inplace_transpose_selector
struct inplace_transpose_selector< MatrixType, false, MatchPacketSize >
struct inplace_transpose_selector< MatrixType, true, false >
struct inplace_transpose_selector< MatrixType, true, true >
struct inverse_impl
struct is_arithmetic
struct is_arithmetic< __m128 >
struct is_arithmetic< __m128d >
struct is_arithmetic< __m128i >
struct is_arithmetic< __m256 >
struct is_arithmetic< __m256d >
struct is_arithmetic< __m256i >
struct is_arithmetic< __m512 >
struct is_arithmetic< __m512d >
struct is_arithmetic< __m512i >
struct is_arithmetic< bool >
struct is_arithmetic< char >
struct is_arithmetic< double >
struct is_arithmetic< float >
struct is_arithmetic< half >
struct is_arithmetic< long double >
struct is_arithmetic< signed char >
struct is_arithmetic< signed int >
struct is_arithmetic< signed long >
struct is_arithmetic< signed short >
struct is_arithmetic< unsigned char >
struct is_arithmetic< unsigned int >
struct is_arithmetic< unsigned long >
struct is_arithmetic< unsigned short >
struct is_const
struct is_const< T const >
struct is_convertible
struct is_convertible_impl
struct is_diagonal
struct is_diagonal< DiagonalBase< T > >
struct is_diagonal< DiagonalMatrix< T, S > >
struct is_diagonal< DiagonalWrapper< T > >
struct is_integral
struct is_integral< bool >
struct is_integral< char >
struct is_integral< signed char >
struct is_integral< signed int >
struct is_integral< signed long >
struct is_integral< signed short >
struct is_integral< unsigned char >
struct is_integral< unsigned int >
struct is_integral< unsigned long >
struct is_integral< unsigned short >
struct is_lvalue
struct is_ref_compatible
struct is_ref_compatible_impl
struct is_same
struct is_same< T, T >
struct is_valid_index_type
struct isApprox_selector
struct isApprox_selector< Derived, OtherDerived, true >
struct isMuchSmallerThan_object_selector
struct isMuchSmallerThan_object_selector< Derived, OtherDerived, true >
struct isMuchSmallerThan_scalar_selector
struct isMuchSmallerThan_scalar_selector< Derived, true >
struct IteratorBased
struct kernel_retval
struct kernel_retval< FullPivLU< _MatrixType > >
class kernel_retval_base
struct lapacke_llt
struct ldlt_inplace
struct ldlt_inplace< Lower >
struct ldlt_inplace< Upper >
struct LDLT_Traits
struct LDLT_Traits< MatrixType, Lower >
struct LDLT_Traits< MatrixType, Upper >
class level3_blocking
struct linspaced_op
struct linspaced_op_impl
struct linspaced_op_impl< Scalar, Packet, false >
struct linspaced_op_impl< Scalar, Packet, true >
struct llt_inplace
struct llt_inplace< Scalar, Lower >
struct llt_inplace< Scalar, Upper >
struct LLT_Traits
struct LLT_Traits< MatrixType, Lower >
struct LLT_Traits< MatrixType, Upper >
struct lpNorm_selector
struct lpNorm_selector< Derived, 1 >
struct lpNorm_selector< Derived, 2 >
struct lpNorm_selector< Derived, Infinity >
struct LU_GlobalLU_t
struct LU_kernel_bmod
struct LU_kernel_bmod< 1 >
class make_proper_matrix_type
struct make_size_type
struct mapbase_evaluator
class MappedSuperNodalMatrix
a class to manipulate the L supernodal factor from the SparseLU factorization
struct matrix_swap_impl
struct matrix_swap_impl< MatrixTypeA, MatrixTypeB, true >
struct matrix_type_times_scalar_type
struct max_coeff_visitor
struct member_lpnorm
struct member_redux
struct meta_least_common_multiple
struct meta_least_common_multiple< A, B, K, true >
struct meta_no
class meta_sqrt
class meta_sqrt< Y, InfX, SupX, true >
struct meta_yes
struct min_coeff_visitor
struct mul_assign_op
struct nested_eval
struct nested_eval< ReturnByValue< Derived >, n, PlainObject >
class no_assignment_operator
class noncopyable
struct nullary_wrapper
struct nullary_wrapper< Scalar, NullaryOp, false, false, false >
struct nullary_wrapper< Scalar, NullaryOp, false, false, true >
struct nullary_wrapper< Scalar, NullaryOp, false, true, false >
struct nullary_wrapper< Scalar, NullaryOp, true, false, false >
struct outer_stride_at_compile_time
struct outer_stride_at_compile_time< Derived, false >
union Packet
struct Packet1cd
struct Packet2cd
struct Packet2cf
struct Packet4cf
struct Packet4f
struct packet_traits
struct packet_traits< const T >
struct packet_traits< double >
struct packet_traits< float >
struct packet_traits< int >
struct packet_traits< int32_t >
struct packet_traits< std::complex< double > >
struct packet_traits< std::complex< float > >
struct PacketBlock
struct palign_impl
struct palign_impl< Offset, Packet16f >
struct palign_impl< Offset, Packet1cd >
struct palign_impl< Offset, Packet2cd >
struct palign_impl< Offset, Packet2cf >
struct palign_impl< Offset, Packet2d >
struct palign_impl< Offset, Packet4cf >
struct palign_impl< Offset, Packet4d >
struct palign_impl< Offset, Packet4f >
struct palign_impl< Offset, Packet4i >
struct palign_impl< Offset, Packet8d >
struct palign_impl< Offset, Packet8f >
struct panel_dfs_traits
struct pardiso_run_selector
struct pardiso_run_selector< long long int >
struct pardiso_traits
struct pardiso_traits< PardisoLDLT< _MatrixType, Options > >
struct pardiso_traits< PardisoLLT< _MatrixType, Options > >
struct pardiso_traits< PardisoLU< _MatrixType > >
struct partial_lu_impl
struct pastix_traits
struct pastix_traits< PastixLDLT< _MatrixType, Options > >
struct pastix_traits< PastixLLT< _MatrixType, Options > >
struct pastix_traits< PastixLU< _MatrixType > >
struct perfvalues
struct permutation_matrix_product
struct permutation_matrix_product< ExpressionType, Side, Transposed, DenseShape >
struct permutation_matrix_product< ExpressionType, Side, Transposed, HomogeneousShape >
struct permutation_matrix_product< ExpressionType, Side, Transposed, SparseShape >
struct plain_array
struct plain_array< T, 0, MatrixOrArrayOptions, Alignment >
struct plain_array< T, Size, MatrixOrArrayOptions, 16 >
struct plain_array< T, Size, MatrixOrArrayOptions, 32 >
struct plain_array< T, Size, MatrixOrArrayOptions, 64 >
struct plain_array< T, Size, MatrixOrArrayOptions, 8 >
struct plain_col_type
struct plain_constant_type
struct plain_diag_type
struct plain_matrix_type
struct plain_matrix_type< T, Dense >
struct plain_matrix_type< T, DiagonalShape >
struct plain_matrix_type< T, Sparse >
struct plain_matrix_type_column_major
struct plain_matrix_type_dense
struct plain_matrix_type_dense< T, ArrayXpr, Flags >
struct plain_matrix_type_dense< T, MatrixXpr, Flags >
struct plain_matrix_type_row_major
struct plain_object_eval
struct plain_object_eval< T, Dense >
struct plain_object_eval< T, Sparse >
struct plain_row_type
class plainobjectbase_evaluator_data
class plainobjectbase_evaluator_data< Scalar, Dynamic >
struct product_evaluator
struct product_evaluator< Product< Lhs, Rhs, AliasFreeProduct >, ProductTag, PermutationShape, SparseShape >
struct product_evaluator< Product< Lhs, Rhs, AliasFreeProduct >, ProductTag, SparseShape, PermutationShape >
struct product_evaluator< Product< Lhs, Rhs, DefaultProduct >, LazyCoeffBasedProductMode, DenseShape, DenseShape >
struct product_evaluator< Product< Lhs, Rhs, DefaultProduct >, OuterProduct, DenseShape, SparseShape >
struct product_evaluator< Product< Lhs, Rhs, DefaultProduct >, OuterProduct, SparseShape, DenseShape >
struct product_evaluator< Product< Lhs, Rhs, DefaultProduct >, ProductTag, DiagonalShape, SparseShape >
struct product_evaluator< Product< Lhs, Rhs, DefaultProduct >, ProductTag, SparseShape, DiagonalShape >
struct product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >
struct product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, HomogeneousShape >
struct product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, HomogeneousShape, DenseShape >
struct product_evaluator< Product< Lhs, Rhs, Options >, ProductTag, LhsShape, RhsShape >
struct product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DenseShape, DiagonalShape >
struct product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DiagonalShape, DenseShape >
struct product_evaluator< Product< Lhs, RhsView, DefaultProduct >, ProductTag, SparseShape, SparseSelfAdjointShape >
struct product_evaluator< Product< LhsView, Rhs, DefaultProduct >, ProductTag, SparseSelfAdjointShape, SparseShape >
struct product_promote_storage_type
struct product_promote_storage_type< A, A, ProductTag >
struct product_promote_storage_type< A, Dense, ProductTag >
struct product_promote_storage_type< A, DiagonalShape, ProductTag >
struct product_promote_storage_type< A, PermutationStorage, ProductTag >
struct product_promote_storage_type< Dense, B, ProductTag >
struct product_promote_storage_type< Dense, Dense, ProductTag >
struct product_promote_storage_type< Dense, DiagonalShape, ProductTag >
struct product_promote_storage_type< Dense, PermutationStorage, ProductTag >
struct product_promote_storage_type< Dense, Sparse, OuterProduct >
struct product_promote_storage_type< DiagonalShape, B, ProductTag >
struct product_promote_storage_type< DiagonalShape, Dense, ProductTag >
struct product_promote_storage_type< PermutationStorage, B, ProductTag >
struct product_promote_storage_type< PermutationStorage, Dense, ProductTag >
struct product_promote_storage_type< PermutationStorage, Sparse, ProductTag >
struct product_promote_storage_type< Sparse, Dense, OuterProduct >
struct product_promote_storage_type< Sparse, PermutationStorage, ProductTag >
struct product_selfadjoint_matrix
struct product_selfadjoint_matrix< Scalar, Index, LhsStorageOrder, false, ConjugateLhs, RhsStorageOrder, true, ConjugateRhs, ColMajor >
struct product_selfadjoint_matrix< Scalar, Index, LhsStorageOrder, LhsSelfAdjoint, ConjugateLhs, RhsStorageOrder, RhsSelfAdjoint, ConjugateRhs, RowMajor >
struct product_selfadjoint_matrix< Scalar, Index, LhsStorageOrder, true, ConjugateLhs, RhsStorageOrder, false, ConjugateRhs, ColMajor >
struct product_size_category
struct product_triangular_matrix_matrix
struct product_triangular_matrix_matrix< Scalar, Index, Mode, false, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >
struct product_triangular_matrix_matrix< Scalar, Index, Mode, LhsIsTriangular, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, RowMajor, Version >
struct product_triangular_matrix_matrix< Scalar, Index, Mode, true, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >
struct product_triangular_matrix_matrix_trmm
struct product_type
struct product_type_selector
struct product_type_selector< 1, 1, 1 >
struct product_type_selector< 1, 1, Depth >
struct product_type_selector< 1, Large, Large >
struct product_type_selector< 1, Large, Small >
struct product_type_selector< 1, N, 1 >
struct product_type_selector< 1, Small, Large >
struct product_type_selector< 1, Small, Small >
struct product_type_selector< Large, 1, Large >
struct product_type_selector< Large, 1, Small >
struct product_type_selector< Large, Large, Large >
struct product_type_selector< Large, Large, Small >
struct product_type_selector< Large, Small, 1 >
struct product_type_selector< Large, Small, Large >
struct product_type_selector< Large, Small, Small >
struct product_type_selector< M, 1, 1 >
struct product_type_selector< M, N, 1 >
struct product_type_selector< Small, 1, Large >
struct product_type_selector< Small, 1, Small >
struct product_type_selector< Small, Large, 1 >
struct product_type_selector< Small, Large, Large >
struct product_type_selector< Small, Large, Small >
struct product_type_selector< Small, Small, 1 >
struct product_type_selector< Small, Small, Large >
struct product_type_selector< Small, Small, Small >
struct projective_transform_inverse
struct projective_transform_inverse< TransformType, Projective >
struct promote_index_type
struct promote_scalar_arg
struct promote_scalar_arg< S, T, false >
struct promote_scalar_arg< S, T, true >
struct promote_scalar_arg_unsupported
struct promote_scalar_arg_unsupported< ExprScalar, T, PromotedType, false, true >
struct promote_scalar_arg_unsupported< S, T, PromotedType, ConvertibleToLiteral, false >
struct promote_scalar_arg_unsupported< S, T, PromotedType, true, true >
struct promote_scalar_arg_unsupported< S, T, S, false, true >
struct promote_storage_type
struct promote_storage_type< A, A >
struct promote_storage_type< A, const A >
struct promote_storage_type< const A, A >
struct qr_preconditioner_impl
class qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >
class qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >
class qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >
class qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >
class qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >
class qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >
class qr_preconditioner_impl< MatrixType, QRPreconditioner, Case, false >
struct qr_preconditioner_should_do_anything
struct quat_conj
struct quat_conj< Architecture::SSE, Derived, double >
struct quat_conj< Architecture::SSE, Derived, float >
struct quat_product
struct quat_product< Architecture::SSE, Derived, OtherDerived, double >
struct quat_product< Architecture::SSE, Derived, OtherDerived, float >
struct quaternionbase_assign_impl
struct quaternionbase_assign_impl< Other, 3, 3 >
struct quaternionbase_assign_impl< Other, 4, 1 >
struct random_default_impl< half, false, false >
struct rcond_compute_sign
struct rcond_compute_sign< Vector, Vector, false >
class redux_evaluator
struct redux_impl
struct redux_impl< Func, Derived, DefaultTraversal, CompleteUnrolling >
struct redux_impl< Func, Derived, DefaultTraversal, NoUnrolling >
struct redux_impl< Func, Derived, LinearVectorizedTraversal, CompleteUnrolling >
struct redux_impl< Func, Derived, LinearVectorizedTraversal, NoUnrolling >
struct redux_impl< Func, Derived, SliceVectorizedTraversal, Unrolling >
struct redux_novec_unroller
struct redux_novec_unroller< Func, Derived, Start, 0 >
struct redux_novec_unroller< Func, Derived, Start, 1 >
struct redux_traits
struct redux_vec_unroller
struct redux_vec_unroller< Func, Derived, Start, 1 >
struct ref_selector
struct remove_all
struct remove_all< const T >
struct remove_all< T & >
struct remove_all< T * >
struct remove_all< T const & >
struct remove_all< T const * >
struct remove_const
struct remove_const< const T >
struct remove_const< const T[]>
struct remove_const< const T[Size]>
struct remove_pointer
struct remove_pointer< T * >
struct remove_pointer< T *const >
struct remove_reference
struct remove_reference< T & >
struct result_of
struct result_of< Func(ArgType)>
struct result_of< Func(ArgType0, ArgType1)>
struct result_of< Func(ArgType0, ArgType1, ArgType2)>
struct result_of< scalar_cmp_op< LhsScalar, RhsScalar, Cmp >(LhsScalar, RhsScalar)>
struct reverse_packet_cond
struct reverse_packet_cond< PacketType, false >
struct rotation_base_generic_product_selector
struct rotation_base_generic_product_selector< RotationDerived, DiagonalMatrix< Scalar, Dim, MaxDim >, false >
struct rotation_base_generic_product_selector< RotationDerived, MatrixType, false >
struct rotation_base_generic_product_selector< RotationDerived, OtherVectorType, true >
struct scalar_abs2_op
struct scalar_abs_op
struct scalar_acos_op
struct scalar_arg_op
struct scalar_asin_op
struct scalar_atan_op
struct scalar_betainc_op
struct scalar_boolean_and_op
struct scalar_boolean_not_op
struct scalar_boolean_or_op
struct scalar_boolean_xor_op
struct scalar_cast_op
struct scalar_cast_op< Eigen::half, float >
struct scalar_cast_op< float, Eigen::half >
struct scalar_cast_op< int, Eigen::half >
struct scalar_ceil_op
struct scalar_cmp_op
struct scalar_cmp_op< LhsScalar, RhsScalar, cmp_EQ >
struct scalar_cmp_op< LhsScalar, RhsScalar, cmp_GE >
struct scalar_cmp_op< LhsScalar, RhsScalar, cmp_GT >
struct scalar_cmp_op< LhsScalar, RhsScalar, cmp_LE >
struct scalar_cmp_op< LhsScalar, RhsScalar, cmp_LT >
struct scalar_cmp_op< LhsScalar, RhsScalar, cmp_NEQ >
struct scalar_cmp_op< LhsScalar, RhsScalar, cmp_UNORD >
struct scalar_conj_product_op
struct scalar_conjugate_op
struct scalar_constant_op
struct scalar_cos_op
struct scalar_cosh_op
struct scalar_cube_op
struct scalar_difference_op
struct scalar_digamma_op
struct scalar_div_cost
struct scalar_div_cost< double, true >
struct scalar_div_cost< float, true >
struct scalar_div_cost< signed long, Vectorized, typename conditional< sizeof(long)==8, void, false_type >::type >
struct scalar_div_cost< std::complex< T >, Vectorized >
struct scalar_div_cost< unsigned long, Vectorized, typename conditional< sizeof(long)==8, void, false_type >::type >
struct scalar_erf_op
struct scalar_erfc_op
struct scalar_exp_op
struct scalar_expm1_op
struct scalar_floor_op
struct scalar_hypot_op
struct scalar_hypot_op< Scalar, Scalar >
struct scalar_identity_op
struct scalar_igamma_op
struct scalar_igammac_op
struct scalar_imag_op
struct scalar_imag_ref_op
struct scalar_inverse_op
struct scalar_isfinite_op
struct scalar_isinf_op
struct scalar_isnan_op
struct scalar_lgamma_op
struct scalar_log10_op
struct scalar_log1p_op
struct scalar_log_op
struct scalar_max_op
struct scalar_min_op
struct scalar_opposite_op
struct scalar_pow_op
struct scalar_product_op
struct scalar_product_traits
struct scalar_quotient_op
struct scalar_random_op
struct scalar_real_op
struct scalar_real_ref_op
struct scalar_round_op
struct scalar_rsqrt_op
struct scalar_score_coeff_op
struct scalar_sign_op
struct scalar_sign_op< Scalar, false >
struct scalar_sign_op< Scalar, true >
struct scalar_sin_op
struct scalar_sinh_op
struct scalar_sqrt_op
struct scalar_square_op
struct scalar_sum_op
struct scalar_sum_op< bool, bool >
struct scalar_tan_op
struct scalar_tanh_op
struct scalar_zeta_op
class scoped_array
struct Selector
struct selfadjoint_matrix_vector_product
struct selfadjoint_matrix_vector_product_symv
struct selfadjoint_product_impl
struct selfadjoint_product_impl< Lhs, 0, true, Rhs, RhsMode, false >
struct selfadjoint_product_impl< Lhs, LhsMode, false, Rhs, 0, true >
struct selfadjoint_product_impl< Lhs, LhsMode, false, Rhs, RhsMode, false >
struct selfadjoint_rank2_update_selector
struct selfadjoint_rank2_update_selector< Scalar, Index, UType, VType, Lower >
struct selfadjoint_rank2_update_selector< Scalar, Index, UType, VType, Upper >
struct setIdentity_impl
struct setIdentity_impl< Derived, true >
struct significant_decimals_impl
struct simplicial_cholesky_grab_input
struct simplicial_cholesky_grab_input< MatrixType, MatrixType >
struct SingleRange
struct size_at_compile_time
struct size_of_xpr_at_compile_time
struct smart_copy_helper
struct smart_copy_helper< T, false >
struct smart_copy_helper< T, true >
struct smart_memmove_helper
struct smart_memmove_helper< T, false >
struct smart_memmove_helper< T, true >
struct solve_traits
struct solve_traits< Decomposition, RhsType, Dense >
struct solve_traits< Decomposition, RhsType, Sparse >
struct Sparse2Dense
struct Sparse2Sparse
struct sparse_conjunction_evaluator
struct sparse_conjunction_evaluator< XprType, IndexBased, IteratorBased >
struct sparse_conjunction_evaluator< XprType, IteratorBased, IndexBased >
struct sparse_conjunction_evaluator< XprType, IteratorBased, IteratorBased >
struct sparse_dense_outer_product_evaluator
struct sparse_diagonal_product_evaluator
struct sparse_diagonal_product_evaluator< SparseXprType, DiagCoeffType, SDP_AsCwiseProduct >
struct sparse_diagonal_product_evaluator< SparseXprType, DiagonalCoeffType, SDP_AsScalarProduct >
struct sparse_eval
struct sparse_eval< T, 1, 1, Flags >
struct sparse_eval< T, 1, Cols, Flags >
struct sparse_eval< T, Rows, 1, Flags >
class sparse_matrix_block_impl
struct sparse_solve_triangular_selector
struct sparse_solve_triangular_selector< Lhs, Rhs, Mode, Lower, ColMajor >
struct sparse_solve_triangular_selector< Lhs, Rhs, Mode, Lower, RowMajor >
struct sparse_solve_triangular_selector< Lhs, Rhs, Mode, Upper, ColMajor >
struct sparse_solve_triangular_selector< Lhs, Rhs, Mode, Upper, RowMajor >
struct sparse_solve_triangular_sparse_selector
struct sparse_solve_triangular_sparse_selector< Lhs, Rhs, Mode, UpLo, ColMajor >
struct sparse_sparse_product_with_pruning_selector
struct sparse_sparse_product_with_pruning_selector< Lhs, Rhs, ResultType, ColMajor, ColMajor, ColMajor >
struct sparse_sparse_product_with_pruning_selector< Lhs, Rhs, ResultType, ColMajor, ColMajor, RowMajor >
struct sparse_sparse_product_with_pruning_selector< Lhs, Rhs, ResultType, ColMajor, RowMajor, ColMajor >
struct sparse_sparse_product_with_pruning_selector< Lhs, Rhs, ResultType, ColMajor, RowMajor, RowMajor >
struct sparse_sparse_product_with_pruning_selector< Lhs, Rhs, ResultType, RowMajor, ColMajor, ColMajor >
struct sparse_sparse_product_with_pruning_selector< Lhs, Rhs, ResultType, RowMajor, ColMajor, RowMajor >
struct sparse_sparse_product_with_pruning_selector< Lhs, Rhs, ResultType, RowMajor, RowMajor, ColMajor >
struct sparse_sparse_product_with_pruning_selector< Lhs, Rhs, ResultType, RowMajor, RowMajor, RowMajor >
struct sparse_sparse_to_dense_product_selector
struct sparse_sparse_to_dense_product_selector< Lhs, Rhs, ResultType, ColMajor, ColMajor >
struct sparse_sparse_to_dense_product_selector< Lhs, Rhs, ResultType, ColMajor, RowMajor >
struct sparse_sparse_to_dense_product_selector< Lhs, Rhs, ResultType, RowMajor, ColMajor >
struct sparse_sparse_to_dense_product_selector< Lhs, Rhs, ResultType, RowMajor, RowMajor >
struct sparse_time_dense_product_impl
struct sparse_time_dense_product_impl< SparseLhsType, DenseRhsType, DenseResType, AlphaType, ColMajor, true >
struct sparse_time_dense_product_impl< SparseLhsType, DenseRhsType, DenseResType, typename DenseResType::Scalar, ColMajor, false >
struct sparse_time_dense_product_impl< SparseLhsType, DenseRhsType, DenseResType, typename DenseResType::Scalar, RowMajor, false >
struct sparse_time_dense_product_impl< SparseLhsType, DenseRhsType, DenseResType, typename DenseResType::Scalar, RowMajor, true >
struct sparse_vector_assign_selector
struct sparse_vector_assign_selector< Dest, Src, SVA_Inner >
struct sparse_vector_assign_selector< Dest, Src, SVA_Outer >
struct sparse_vector_assign_selector< Dest, Src, SVA_RuntimeSwitch >
class SparseLUImpl
class SparseRefBase
struct SparseSelfAdjoint2Sparse
struct SparseSelfAdjointShape
class SparseTransposeImpl
class SparseTransposeImpl< MatrixType, CompressedAccessBit >
struct SparseTriangularShape
struct static_assertion
struct static_assertion< true >
struct stem_function
struct storage_kind_to_evaluator_kind
struct storage_kind_to_evaluator_kind< Sparse >
struct storage_kind_to_shape
struct storage_kind_to_shape< Dense >
struct storage_kind_to_shape< DiagonalShape >
struct storage_kind_to_shape< PermutationStorage >
struct storage_kind_to_shape< SolverStorage >
struct storage_kind_to_shape< Sparse >
struct storage_kind_to_shape< TranspositionsStorage >
struct sub_assign_op
struct svd_precondition_2x2_block_to_be_real
struct svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, false >
struct svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >
struct swap_assign_op
struct symm_pack_lhs
struct symm_pack_rhs
struct take_matrix_for_product
struct take_matrix_for_product< Transform< Scalar, Dim, Mode, Options > >
struct take_matrix_for_product< Transform< Scalar, Dim, Projective, Options > >
struct ternary_evaluator
struct ternary_evaluator< CwiseTernaryOp< TernaryOp, Arg1, Arg2, Arg3 >, IndexBased, IndexBased >
struct ternary_result_of_select
struct ternary_result_of_select< Func, ArgType0, ArgType1, ArgType2, sizeof(has_std_result_type)>
struct ternary_result_of_select< Func, ArgType0, ArgType1, ArgType2, sizeof(has_tr1_result)>
struct traits
struct traits< AngleAxis< _Scalar > >
struct traits< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >
struct traits< ArrayWrapper< ExpressionType > >
struct traits< BandMatrix< _Scalar, _Rows, _Cols, _Supers, _Subs, _Options > >
struct traits< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >
struct traits< BDCSVD< _MatrixType > >
struct traits< BiCGSTAB< _MatrixType, _Preconditioner > >
struct traits< Block< XprType, BlockRows, BlockCols, InnerPanel > >
struct traits< ColPivHouseholderQR< _MatrixType > >
struct traits< CompleteOrthogonalDecomposition< _MatrixType > >
struct traits< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >
struct traits< const T >
struct traits< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >
struct traits< CwiseNullaryOp< NullaryOp, PlainObjectType > >
struct traits< CwiseTernaryOp< TernaryOp, Arg1, Arg2, Arg3 > >
struct traits< CwiseUnaryOp< UnaryOp, XprType > >
struct traits< CwiseUnaryView< ViewOp, MatrixType > >
struct traits< Diagonal< const SparseMatrix< _Scalar, _Options, _StorageIndex >, DiagIndex > >
struct traits< Diagonal< MatrixType, DiagIndex > >
struct traits< Diagonal< SparseMatrix< _Scalar, _Options, _StorageIndex >, DiagIndex > >
struct traits< DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > >
struct traits< DiagonalWrapper< _DiagonalVectorType > >
struct traits< EvalToTemp< ArgType > >
struct traits< ForceAlignedAccess< ExpressionType > >
struct traits< FullPivHouseholderQR< _MatrixType > >
struct traits< FullPivHouseholderQRMatrixQReturnType< MatrixType > >
struct traits< FullPivLU< _MatrixType > >
struct traits< HessenbergDecompositionMatrixHReturnType< MatrixType > >
struct traits< Homogeneous< MatrixType, Direction > >
struct traits< homogeneous_left_product_impl< Homogeneous< MatrixType, Vertical >, Lhs > >
struct traits< homogeneous_right_product_impl< Homogeneous< MatrixType, Horizontal >, Rhs > >
struct traits< HouseholderSequence< VectorsType, CoeffsType, Side > >
struct traits< image_retval_base< DecompositionType > >
struct traits< IndexedView< XprType, RowIndices, ColIndices > >
struct traits< Inverse< XprType > >
struct traits< JacobiSVD< _MatrixType, QRPreconditioner > >
struct traits< kernel_retval_base< DecompositionType > >
struct traits< LeastSquaresConjugateGradient< _MatrixType, _Preconditioner > >
struct traits< Map< const Quaternion< _Scalar >, _Options > >
struct traits< Map< const SparseMatrix< MatScalar, MatOptions, MatIndex >, Options, StrideType > >
struct traits< Map< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex >, _PacketAccess > >
struct traits< Map< PlainObjectType, MapOptions, StrideType > >
struct traits< Map< Quaternion< _Scalar >, _Options > >
struct traits< Map< SparseMatrix< MatScalar, MatOptions, MatIndex >, Options, StrideType > >
struct traits< Map< Transpositions< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex >, _PacketAccess > >
struct traits< MappedSparseMatrix< _Scalar, _Flags, _StorageIndex > >
struct traits< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >
struct traits< MatrixWrapper< ExpressionType > >
struct traits< NestByValue< ExpressionType > >
struct traits< PartialPivLU< _MatrixType > >
struct traits< PartialReduxExpr< MatrixType, MemberOp, Direction > >
struct traits< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex > >
struct traits< PermutationWrapper< _IndicesType > >
struct traits< Product< Lhs, Rhs, Option > >
struct traits< Quaternion< _Scalar, _Options > >
struct traits< Ref< _PlainObjectType, _Options, _StrideType > >
struct traits< Ref< const SparseMatrix< MatScalar, MatOptions, MatIndex >, _Options, _StrideType > >
struct traits< Ref< const SparseVector< MatScalar, MatOptions, MatIndex >, _Options, _StrideType > >
struct traits< Ref< SparseMatrix< MatScalar, MatOptions, MatIndex >, _Options, _StrideType > >
struct traits< Ref< SparseVector< MatScalar, MatOptions, MatIndex >, _Options, _StrideType > >
struct traits< RefBase< Derived > >
struct traits< Replicate< MatrixType, RowFactor, ColFactor > >
struct traits< ReturnByValue< Derived > >
struct traits< Reverse< MatrixType, Direction > >
struct traits< Rotation2D< _Scalar > >
struct traits< Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType > >
struct traits< SelfAdjointView< MatrixType, UpLo > >
struct traits< SimplicialCholesky< _MatrixType, _UpLo, _Ordering > >
struct traits< SimplicialLDLT< _MatrixType, _UpLo, _Ordering > >
struct traits< SimplicialLLT< _MatrixType, _UpLo, _Ordering > >
struct traits< Solve< Decomposition, RhsType > >
struct traits< SolveWithGuess< Decomposition, RhsType, GuessType > >
struct traits< SparseCompressedBase< Derived > >
struct traits< SparseMatrix< _Scalar, _Options, _StorageIndex > >
struct traits< SparseQR_QProduct< SparseQRType, Derived > >
struct traits< SparseQRMatrixQReturnType< SparseQRType > >
struct traits< SparseQRMatrixQTransposeReturnType< SparseQRType > >
struct traits< SparseRefBase< Derived > >
struct traits< SparseSelfAdjointView< MatrixType, Mode > >
struct traits< SparseSymmetricPermutationProduct< MatrixType, Mode > >
struct traits< SparseVector< _Scalar, _Options, _StorageIndex > >
struct traits< SparseView< MatrixType > >
struct traits< SPQR_QProduct< SPQRType, Derived > >
struct traits< SPQRMatrixQReturnType< SPQRType > >
struct traits< SPQRMatrixQTransposeReturnType< SPQRType > >
struct traits< Transform< _Scalar, _Dim, _Mode, _Options > >
struct traits< Transpose< MatrixType > >
struct traits< Transpose< TranspositionsBase< Derived > > >
struct traits< Transpositions< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex > >
struct traits< TranspositionsWrapper< _IndicesType > >
struct traits< triangular_solve_retval< Side, TriangularType, Rhs > >
struct traits< TriangularView< MatrixType, _Mode > >
struct traits< TridiagonalizationMatrixTReturnType< MatrixType > >
struct traits< VectorBlock< VectorType, Size > >
struct transfer_constness
struct transform_construct_from_matrix
struct transform_construct_from_matrix< Other, AffineCompact, Options, Dim, HDim, HDim, HDim >
struct transform_construct_from_matrix< Other, Mode, Options, Dim, HDim, Dim, Dim >
struct transform_construct_from_matrix< Other, Mode, Options, Dim, HDim, Dim, HDim >
struct transform_construct_from_matrix< Other, Mode, Options, Dim, HDim, HDim, HDim >
struct transform_left_product_impl
struct transform_left_product_impl< Other, AffineCompact, Options, Dim, HDim, Dim, HDim >
struct transform_left_product_impl< Other, AffineCompact, Options, Dim, HDim, HDim, HDim >
struct transform_left_product_impl< Other, Mode, Options, Dim, HDim, Dim, Dim >
struct transform_left_product_impl< Other, Mode, Options, Dim, HDim, Dim, HDim >
struct transform_left_product_impl< Other, Mode, Options, Dim, HDim, HDim, HDim >
struct transform_make_affine
struct transform_make_affine< AffineCompact >
struct transform_product_result
struct transform_right_product_impl
struct transform_right_product_impl< TransformType, MatrixType, 0, RhsCols >
struct transform_right_product_impl< TransformType, MatrixType, 1, RhsCols >
struct transform_right_product_impl< TransformType, MatrixType, 2, 1 >
struct transform_right_product_impl< TransformType, MatrixType, 2, RhsCols >
struct transform_take_affine_part
struct transform_take_affine_part< Transform< Scalar, Dim, AffineCompact, Options > >
struct transform_traits
struct transform_transform_product_impl
struct transform_transform_product_impl< Transform< Scalar, Dim, AffineCompact, LhsOptions >, Transform< Scalar, Dim, Projective, RhsOptions >, true >
struct transform_transform_product_impl< Transform< Scalar, Dim, LhsMode, LhsOptions >, Transform< Scalar, Dim, RhsMode, RhsOptions >, false >
struct transform_transform_product_impl< Transform< Scalar, Dim, LhsMode, LhsOptions >, Transform< Scalar, Dim, RhsMode, RhsOptions >, true >
struct transform_transform_product_impl< Transform< Scalar, Dim, Projective, LhsOptions >, Transform< Scalar, Dim, AffineCompact, RhsOptions >, true >
struct TransposeImpl_base
struct TransposeImpl_base< MatrixType, false >
struct transposition_matrix_product
struct Triangular2Dense
struct Triangular2Triangular
struct triangular_assignment_loop
struct triangular_assignment_loop< Kernel, Mode, 0, SetOpposite >
struct triangular_assignment_loop< Kernel, Mode, Dynamic, SetOpposite >
class triangular_dense_assignment_kernel
class triangular_dense_assignment_kernel< UpLo, SelfAdjoint, SetOpposite, DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >
struct triangular_matrix_vector_product
struct triangular_matrix_vector_product< Index, Mode, LhsScalar, ConjLhs, RhsScalar, ConjRhs, ColMajor, Version >
struct triangular_matrix_vector_product< Index, Mode, LhsScalar, ConjLhs, RhsScalar, ConjRhs, RowMajor, Version >
struct triangular_matrix_vector_product_trmv
struct triangular_product_impl
struct triangular_product_impl< Mode, false, Lhs, true, Rhs, false >
struct triangular_product_impl< Mode, LhsIsTriangular, Lhs, false, Rhs, false >
struct triangular_product_impl< Mode, true, Lhs, false, Rhs, true >
struct triangular_solve_matrix
struct triangular_solve_matrix< Scalar, Index, OnTheLeft, Mode, Conjugate, TriStorageOrder, ColMajor >
struct triangular_solve_matrix< Scalar, Index, OnTheRight, Mode, Conjugate, TriStorageOrder, ColMajor >
struct triangular_solve_matrix< Scalar, Index, Side, Mode, Conjugate, TriStorageOrder, RowMajor >
struct triangular_solve_retval
struct triangular_solve_vector
struct triangular_solve_vector< LhsScalar, RhsScalar, Index, OnTheLeft, Mode, Conjugate, ColMajor >
struct triangular_solve_vector< LhsScalar, RhsScalar, Index, OnTheLeft, Mode, Conjugate, RowMajor >
struct triangular_solve_vector< LhsScalar, RhsScalar, Index, OnTheRight, Mode, Conjugate, StorageOrder >
struct triangular_solver_selector
struct triangular_solver_selector< Lhs, Rhs, OnTheLeft, Mode, CompleteUnrolling, 1 >
struct triangular_solver_selector< Lhs, Rhs, OnTheRight, Mode, CompleteUnrolling, 1 >
struct triangular_solver_selector< Lhs, Rhs, Side, Mode, NoUnrolling, 1 >
struct triangular_solver_selector< Lhs, Rhs, Side, Mode, NoUnrolling, Dynamic >
struct triangular_solver_unroller
struct triangular_solver_unroller< Lhs, Rhs, Mode, LoopIndex, Size, false >
struct triangular_solver_unroller< Lhs, Rhs, Mode, LoopIndex, Size, true >
struct tribb_kernel
struct tridiagonalization_inplace_selector
struct tridiagonalization_inplace_selector< MatrixType, 1, IsComplex >
struct tridiagonalization_inplace_selector< MatrixType, 3, false >
struct TridiagonalizationMatrixTReturnType
class TridiagonalMatrix
Represents a tridiagonal matrix with a compact banded storage.
struct trmv_selector
struct trmv_selector< Mode, ColMajor >
struct trmv_selector< Mode, RowMajor >
class trsolve_traits
struct true_type
struct type_casting_traits
struct type_casting_traits< double, float >
struct type_casting_traits< float, double >
struct type_casting_traits< float, int >
struct type_casting_traits< int, float >
struct umeyama_transform_matrix_type
struct unaligned_dense_assignment_loop
struct unaligned_dense_assignment_loop< false >
struct unary_evaluator
struct unary_evaluator< ArrayWrapper< TArgType > >
struct unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >
struct unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IteratorBased >
struct unary_evaluator< Block< const SparseMatrix< _Scalar, _Options, _StorageIndex >, BlockRows, BlockCols, true >, IteratorBased >
struct unary_evaluator< Block< SparseMatrix< _Scalar, _Options, _StorageIndex >, BlockRows, BlockCols, true >, IteratorBased >
struct unary_evaluator< CwiseUnaryOp< UnaryOp, ArgType >, IndexBased >
struct unary_evaluator< CwiseUnaryOp< UnaryOp, ArgType >, IteratorBased >
struct unary_evaluator< CwiseUnaryView< UnaryOp, ArgType >, IndexBased >
struct unary_evaluator< CwiseUnaryView< ViewOp, ArgType >, IteratorBased >
struct unary_evaluator< Homogeneous< ArgType, Direction >, IndexBased >
struct unary_evaluator< IndexedView< ArgType, RowIndices, ColIndices >, IndexBased >
struct unary_evaluator< Inverse< ArgType > >
struct unary_evaluator< MatrixWrapper< TArgType > >
struct unary_evaluator< Replicate< ArgType, RowFactor, ColFactor > >
struct unary_evaluator< Reverse< ArgType, Direction > >
struct unary_evaluator< SparseView< ArgType >, IndexBased >
struct unary_evaluator< SparseView< ArgType >, IteratorBased >
struct unary_evaluator< SparseView< Product< Lhs, Rhs, Options > >, IteratorBased >
struct unary_evaluator< Transpose< ArgType >, IndexBased >
struct unary_evaluator< Transpose< ArgType >, IteratorBased >
struct unary_evaluator< TriangularView< ArgType, Mode >, IteratorBased >
struct unary_evaluator< TriangularView< MatrixType, Mode >, IndexBased >
struct unary_result_of_select
struct unary_result_of_select< Func, ArgType, sizeof(has_std_result_type)>
struct unary_result_of_select< Func, ArgType, sizeof(has_tr1_result)>
struct unitOrthogonal_selector
struct unitOrthogonal_selector< Derived, 2 >
struct unitOrthogonal_selector< Derived, 3 >
struct unpacket_traits
struct unpacket_traits< DoublePacket< Packet > >
struct unpacket_traits< Packet16f >
struct unpacket_traits< Packet16i >
struct unpacket_traits< Packet1cd >
struct unpacket_traits< Packet2cd >
struct unpacket_traits< Packet2cf >
struct unpacket_traits< Packet2d >
struct unpacket_traits< Packet4cf >
struct unpacket_traits< Packet4d >
struct unpacket_traits< Packet4f >
struct unpacket_traits< Packet4i >
struct unpacket_traits< Packet8d >
struct unpacket_traits< Packet8f >
struct unpacket_traits< Packet8i >
class UpperBidiagonalization
class variable_if_dynamic
class variable_if_dynamic< T, Dynamic >
class variable_if_dynamicindex
class variable_if_dynamicindex< T, DynamicIndex >
class VariableAndFixedInt
struct vectorwise_reverse_inplace_impl
struct vectorwise_reverse_inplace_impl< Horizontal >
struct vectorwise_reverse_inplace_impl< Vertical >
class visitor_evaluator
struct visitor_impl
struct visitor_impl< Visitor, Derived, 1 >
struct visitor_impl< Visitor, Derived, Dynamic >
class vml_assign_traits
Typedefs
typedef __vector float Packet4f
typedef __vector int Packet4i
typedef __vector unsigned int Packet4ui
typedef __vector __bool int Packet4bi
typedef __vector short int Packet8i
typedef __vector unsigned char Packet16uc
typedef __m256 Packet8f
typedef __m256d Packet4d
typedef __m512 Packet16f
typedef __m512i Packet16i
typedef __m512d Packet8d
typedef float32x2_t Packet2f
typedef int32x2_t Packet2i
typedef __m128d Packet2d
typedef __vector unsigned long long Packet2ul
typedef __vector long long Packet2l
typedef std::ptrdiff_t IntPtr
typedef std::size_t UIntPtr
Enumerations
enum SignMatrix { PositiveSemiDef, NegativeSemiDef, ZeroSign, Indefinite }
enum PermPermProduct_t { PermPermProduct }
enum ComparisonName {
cmp_EQ = 0, cmp_LT = 1, cmp_LE = 2, cmp_UNORD = 3,
cmp_NEQ = 4, cmp_GT = 5, cmp_GE = 6
}
enum { SDP_AsScalarProduct, SDP_AsCwiseProduct }
enum { SVA_RuntimeSwitch, SVA_Inner, SVA_Outer }
enum { LUNoMarker = 3 }
enum { emptyIdxLU = -1 }
enum MemType {
LUSUP, UCOL, LSUB, USUB,
LLVL, ULVL
}
enum { PreconditionIfMoreColsThanRows, PreconditionIfMoreRowsThanCols }
Functions
template<typename MatrixType , typename VectorType >
static Index llt_rank_update_lower (MatrixType &mat, const VectorType &vec, const typename MatrixType::RealScalar &sigma)
template<typename _StorageIndex >
cholmod_dense * cm_solve (int sys, cholmod_factor &L, cholmod_dense &B, cholmod_common &Common)
template<>
cholmod_dense * cm_solve< long > (int sys, cholmod_factor &L, cholmod_dense &B, cholmod_common &Common)
template<typename _StorageIndex >
cholmod_sparse * cm_spsolve (int sys, cholmod_factor &L, cholmod_sparse &B, cholmod_common &Common)
template<>
cholmod_sparse * cm_spsolve< long > (int sys, cholmod_factor &L, cholmod_sparse &B, cholmod_common &Common)
template<typename _StorageIndex >
int cm_factorize_p (cholmod_sparse *A, double beta[2], _StorageIndex *fset, std::size_t fsize, cholmod_factor *L, cholmod_common &Common)
template<>
int cm_factorize_p< long > (cholmod_sparse *A, double beta[2], long *fset, std::size_t fsize, cholmod_factor *L, cholmod_common &Common)
template<>
EIGEN_STRONG_INLINE Packet2cf pset1< Packet2cf > (const std::complex< float > &from)
template<>
EIGEN_STRONG_INLINE Packet2cf pload< Packet2cf > (const std::complex< float > *from)
template<>
EIGEN_STRONG_INLINE Packet2cf ploadu< Packet2cf > (const std::complex< float > *from)
template<>
EIGEN_STRONG_INLINE Packet2cf ploaddup< Packet2cf > (const std::complex< float > *from)
template<>
EIGEN_STRONG_INLINE void pstore< std::complex< float > > (std::complex< float > *to, const Packet2cf &from)
template<>
EIGEN_STRONG_INLINE void pstoreu< std::complex< float > > (std::complex< float > *to, const Packet2cf &from)
template<>
EIGEN_DEVICE_FUNC Packet2cf pgather< std::complex< float >, Packet2cf > (const std::complex< float > *from, Index stride)
template<>
EIGEN_DEVICE_FUNC void pscatter< std::complex< float >, Packet2cf > (std::complex< float > *to, const Packet2cf &from, Index stride)
template<>
EIGEN_STRONG_INLINE Packet2cf padd< Packet2cf > (const Packet2cf &a, const Packet2cf &b)
template<>
EIGEN_STRONG_INLINE Packet2cf psub< Packet2cf > (const Packet2cf &a, const Packet2cf &b)
template<>
EIGEN_STRONG_INLINE Packet2cf pnegate (const Packet2cf &a)
template<>
EIGEN_STRONG_INLINE Packet2cf pconj (const Packet2cf &a)
template<>
EIGEN_STRONG_INLINE Packet2cf pmul< Packet2cf > (const Packet2cf &a, const Packet2cf &b)
template<>
EIGEN_STRONG_INLINE Packet2cf pand< Packet2cf > (const Packet2cf &a, const Packet2cf &b)
template<>
EIGEN_STRONG_INLINE Packet2cf por< Packet2cf > (const Packet2cf &a, const Packet2cf &b)
template<>
EIGEN_STRONG_INLINE Packet2cf pxor< Packet2cf > (const Packet2cf &a, const Packet2cf &b)
template<>
EIGEN_STRONG_INLINE Packet2cf pandnot< Packet2cf > (const Packet2cf &a, const Packet2cf &b)
template<>
EIGEN_STRONG_INLINE void prefetch< std::complex< float > > (const std::complex< float > *addr)
template<>
EIGEN_STRONG_INLINE std::complex< float > pfirst< Packet2cf > (const Packet2cf &a)
template<>
EIGEN_STRONG_INLINE Packet2cf preverse (const Packet2cf &a)
template<>
EIGEN_STRONG_INLINE std::complex< float > predux< Packet2cf > (const Packet2cf &a)
template<>
EIGEN_STRONG_INLINE Packet2cf preduxp< Packet2cf > (const Packet2cf *vecs)
template<>
EIGEN_STRONG_INLINE std::complex< float > predux_mul< Packet2cf > (const Packet2cf &a)
template<>
EIGEN_STRONG_INLINE Packet2cf pdiv< Packet2cf > (const Packet2cf &a, const Packet2cf &b)
template<>
EIGEN_STRONG_INLINE Packet2cf pcplxflip< Packet2cf > (const Packet2cf &x)
EIGEN_STRONG_INLINE void ptranspose (PacketBlock< Packet2cf, 2 > &kernel)
static _EIGEN_DECLARE_CONST_Packet4f (1, 1.0f)
static _EIGEN_DECLARE_CONST_Packet4f (half, 0.5f)
static _EIGEN_DECLARE_CONST_Packet4i (0x7f, 0x7f)
static _EIGEN_DECLARE_CONST_Packet4i (23, 23)
static _EIGEN_DECLARE_CONST_Packet4f_FROM_INT (inv_mant_mask,~0x7f800000)
static _EIGEN_DECLARE_CONST_Packet4f_FROM_INT (min_norm_pos, 0x00800000)
static _EIGEN_DECLARE_CONST_Packet4f_FROM_INT (minus_inf, 0xff800000)
static _EIGEN_DECLARE_CONST_Packet4f_FROM_INT (minus_nan, 0xffffffff)
static _EIGEN_DECLARE_CONST_Packet4f (cephes_SQRTHF, 0.707106781186547524f)
static _EIGEN_DECLARE_CONST_Packet4f (cephes_log_p0, 7.0376836292E-2f)
static _EIGEN_DECLARE_CONST_Packet4f (cephes_log_p1,-1.1514610310E-1f)
static _EIGEN_DECLARE_CONST_Packet4f (cephes_log_p2, 1.1676998740E-1f)
static _EIGEN_DECLARE_CONST_Packet4f (cephes_log_p3,-1.2420140846E-1f)
static _EIGEN_DECLARE_CONST_Packet4f (cephes_log_p4,+1.4249322787E-1f)
static _EIGEN_DECLARE_CONST_Packet4f (cephes_log_p5,-1.6668057665E-1f)
static _EIGEN_DECLARE_CONST_Packet4f (cephes_log_p6,+2.0000714765E-1f)
static _EIGEN_DECLARE_CONST_Packet4f (cephes_log_p7,-2.4999993993E-1f)
static _EIGEN_DECLARE_CONST_Packet4f (cephes_log_p8,+3.3333331174E-1f)
static _EIGEN_DECLARE_CONST_Packet4f (cephes_log_q1,-2.12194440e-4f)
static _EIGEN_DECLARE_CONST_Packet4f (cephes_log_q2, 0.693359375f)
static _EIGEN_DECLARE_CONST_Packet4f (exp_hi, 88.3762626647950f)
static _EIGEN_DECLARE_CONST_Packet4f (exp_lo,-88.3762626647949f)
static _EIGEN_DECLARE_CONST_Packet4f (cephes_LOG2EF, 1.44269504088896341f)
static _EIGEN_DECLARE_CONST_Packet4f (cephes_exp_C1, 0.693359375f)
static _EIGEN_DECLARE_CONST_Packet4f (cephes_exp_C2,-2.12194440e-4f)
static _EIGEN_DECLARE_CONST_Packet4f (cephes_exp_p0, 1.9875691500E-4f)
static _EIGEN_DECLARE_CONST_Packet4f (cephes_exp_p1, 1.3981999507E-3f)
static _EIGEN_DECLARE_CONST_Packet4f (cephes_exp_p2, 8.3334519073E-3f)
static _EIGEN_DECLARE_CONST_Packet4f (cephes_exp_p3, 4.1665795894E-2f)
static _EIGEN_DECLARE_CONST_Packet4f (cephes_exp_p4, 1.6666665459E-1f)
static _EIGEN_DECLARE_CONST_Packet4f (cephes_exp_p5, 5.0000001201E-1f)
template<>
EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet4f plog< Packet4f > (const Packet4f &_x)
template<>
EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet4f pexp< Packet4f > (const Packet4f &_x)
template<>
EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet4f prsqrt< Packet4f > (const Packet4f &x)
static _EIGEN_DECLARE_CONST_FAST_Packet4f (ZERO, 0)
static _EIGEN_DECLARE_CONST_FAST_Packet4i (ZERO, 0)
static _EIGEN_DECLARE_CONST_FAST_Packet4i (ONE, 1)
static _EIGEN_DECLARE_CONST_FAST_Packet4i (MINUS16,-16)
static _EIGEN_DECLARE_CONST_FAST_Packet4i (MINUS1,-1)
std::ostream & operator<< (std::ostream &s, const Packet16uc &v)
std::ostream & operator<< (std::ostream &s, const Packet4f &v)
std::ostream & operator<< (std::ostream &s, const Packet4i &v)
std::ostream & operator<< (std::ostream &s, const Packet4ui &v)
template<>
EIGEN_STRONG_INLINE Packet4f pload< Packet4f > (const float *from)
template<>
EIGEN_STRONG_INLINE Packet4i pload< Packet4i > (const int *from)
template<>
EIGEN_STRONG_INLINE void pstore< float > (float *to, const Packet4f &from)
template<>
EIGEN_STRONG_INLINE void pstore< int > (int *to, const Packet4i &from)
template<>
EIGEN_STRONG_INLINE Packet4f pset1< Packet4f > (const float &from)
template<>
EIGEN_STRONG_INLINE Packet4i pset1< Packet4i > (const int &from)
template<>
EIGEN_STRONG_INLINE void pbroadcast4< Packet4f > (const float *a, Packet4f &a0, Packet4f &a1, Packet4f &a2, Packet4f &a3)
template<>
EIGEN_STRONG_INLINE void pbroadcast4< Packet4i > (const int *a, Packet4i &a0, Packet4i &a1, Packet4i &a2, Packet4i &a3)
template<>
EIGEN_DEVICE_FUNC Packet4f pgather< float, Packet4f > (const float *from, Index stride)
template<>
EIGEN_DEVICE_FUNC Packet4i pgather< int, Packet4i > (const int *from, Index stride)
template<>
EIGEN_DEVICE_FUNC void pscatter< float, Packet4f > (float *to, const Packet4f &from, Index stride)
template<>
EIGEN_DEVICE_FUNC void pscatter< int, Packet4i > (int *to, const Packet4i &from, Index stride)
template<>
EIGEN_STRONG_INLINE Packet4f plset< Packet4f > (const float &a)
template<>
EIGEN_STRONG_INLINE Packet4i plset< Packet4i > (const int &a)
template<>
EIGEN_STRONG_INLINE Packet4f padd< Packet4f > (const Packet4f &a, const Packet4f &b)
template<>
EIGEN_STRONG_INLINE Packet4i padd< Packet4i > (const Packet4i &a, const Packet4i &b)
template<>
EIGEN_STRONG_INLINE Packet4f psub< Packet4f > (const Packet4f &a, const Packet4f &b)
template<>
EIGEN_STRONG_INLINE Packet4i psub< Packet4i > (const Packet4i &a, const Packet4i &b)
template<>
EIGEN_STRONG_INLINE Packet4f pnegate (const Packet4f &a)
template<>
EIGEN_STRONG_INLINE Packet4i pnegate (const Packet4i &a)
template<>
EIGEN_STRONG_INLINE Packet4f pconj (const Packet4f &a)
template<>
EIGEN_STRONG_INLINE Packet4i pconj (const Packet4i &a)
template<>
EIGEN_STRONG_INLINE Packet4f pmul< Packet4f > (const Packet4f &a, const Packet4f &b)
template<>
EIGEN_STRONG_INLINE Packet4i pmul< Packet4i > (const Packet4i &a, const Packet4i &b)
template<>
EIGEN_STRONG_INLINE Packet4f pdiv< Packet4f > (const Packet4f &a, const Packet4f &b)
template<>
EIGEN_STRONG_INLINE Packet4i pdiv< Packet4i > (const Packet4i &, const Packet4i &)
template<>
EIGEN_STRONG_INLINE Packet4f pmadd (const Packet4f &a, const Packet4f &b, const Packet4f &c)
template<>
EIGEN_STRONG_INLINE Packet4i pmadd (const Packet4i &a, const Packet4i &b, const Packet4i &c)
template<>
EIGEN_STRONG_INLINE Packet4f pmin< Packet4f > (const Packet4f &a, const Packet4f &b)
template<>
EIGEN_STRONG_INLINE Packet4i pmin< Packet4i > (const Packet4i &a, const Packet4i &b)
template<>
EIGEN_STRONG_INLINE Packet4f pmax< Packet4f > (const Packet4f &a, const Packet4f &b)
template<>
EIGEN_STRONG_INLINE Packet4i pmax< Packet4i > (const Packet4i &a, const Packet4i &b)
template<>
EIGEN_STRONG_INLINE Packet4f pand< Packet4f > (const Packet4f &a, const Packet4f &b)
template<>
EIGEN_STRONG_INLINE Packet4i pand< Packet4i > (const Packet4i &a, const Packet4i &b)
template<>
EIGEN_STRONG_INLINE Packet4f por< Packet4f > (const Packet4f &a, const Packet4f &b)
template<>
EIGEN_STRONG_INLINE Packet4i por< Packet4i > (const Packet4i &a, const Packet4i &b)
template<>
EIGEN_STRONG_INLINE Packet4f pxor< Packet4f > (const Packet4f &a, const Packet4f &b)
template<>
EIGEN_STRONG_INLINE Packet4i pxor< Packet4i > (const Packet4i &a, const Packet4i &b)
template<>
EIGEN_STRONG_INLINE Packet4f pandnot< Packet4f > (const Packet4f &a, const Packet4f &b)
template<>
EIGEN_STRONG_INLINE Packet4i pandnot< Packet4i > (const Packet4i &a, const Packet4i &b)
template<>
EIGEN_STRONG_INLINE Packet4f pround< Packet4f > (const Packet4f &a)
template<>
EIGEN_STRONG_INLINE Packet4f pceil< Packet4f > (const Packet4f &a)
template<>
EIGEN_STRONG_INLINE Packet4f pfloor< Packet4f > (const Packet4f &a)
template<>
EIGEN_STRONG_INLINE Packet4i ploadu< Packet4i > (const int *from)
template<>
EIGEN_STRONG_INLINE Packet4f ploadu< Packet4f > (const float *from)
template<>
EIGEN_STRONG_INLINE Packet4f ploaddup< Packet4f > (const float *from)
template<>
EIGEN_STRONG_INLINE Packet4i ploaddup< Packet4i > (const int *from)
template<>
EIGEN_STRONG_INLINE void pstoreu< int > (int *to, const Packet4i &from)
template<>
EIGEN_STRONG_INLINE void pstoreu< float > (float *to, const Packet4f &from)
template<>
EIGEN_STRONG_INLINE void prefetch< float > (const float *addr)
template<>
EIGEN_STRONG_INLINE void prefetch< int > (const int *addr)
template<>
EIGEN_STRONG_INLINE float pfirst< Packet4f > (const Packet4f &a)
template<>
EIGEN_STRONG_INLINE int pfirst< Packet4i > (const Packet4i &a)
template<>
EIGEN_STRONG_INLINE Packet4f preverse (const Packet4f &a)
template<>
EIGEN_STRONG_INLINE Packet4i preverse (const Packet4i &a)
template<>
EIGEN_STRONG_INLINE Packet4f pabs (const Packet4f &a)
template<>
EIGEN_STRONG_INLINE Packet4i pabs (const Packet4i &a)
template<>
EIGEN_STRONG_INLINE float predux< Packet4f > (const Packet4f &a)
template<>
EIGEN_STRONG_INLINE Packet4f preduxp< Packet4f > (const Packet4f *vecs)
template<>
EIGEN_STRONG_INLINE int predux< Packet4i > (const Packet4i &a)
template<>
EIGEN_STRONG_INLINE Packet4i preduxp< Packet4i > (const Packet4i *vecs)
template<>
EIGEN_STRONG_INLINE float predux_mul< Packet4f > (const Packet4f &a)
template<>
EIGEN_STRONG_INLINE int predux_mul< Packet4i > (const Packet4i &a)
template<>
EIGEN_STRONG_INLINE float predux_min< Packet4f > (const Packet4f &a)
template<>
EIGEN_STRONG_INLINE int predux_min< Packet4i > (const Packet4i &a)
template<>
EIGEN_STRONG_INLINE float predux_max< Packet4f > (const Packet4f &a)
template<>
EIGEN_STRONG_INLINE int predux_max< Packet4i > (const Packet4i &a)
EIGEN_DEVICE_FUNC void ptranspose (PacketBlock< Packet4f, 4 > &kernel)
EIGEN_DEVICE_FUNC void ptranspose (PacketBlock< Packet4i, 4 > &kernel)
template<>
EIGEN_STRONG_INLINE Packet4i pblend (const Selector< 4 > &ifPacket, const Packet4i &thenPacket, const Packet4i &elsePacket)
template<>
EIGEN_STRONG_INLINE Packet4f pblend (const Selector< 4 > &ifPacket, const Packet4f &thenPacket, const Packet4f &elsePacket)
template<>
EIGEN_STRONG_INLINE Packet4cf padd< Packet4cf > (const Packet4cf &a, const Packet4cf &b)
template<>
EIGEN_STRONG_INLINE Packet4cf psub< Packet4cf > (const Packet4cf &a, const Packet4cf &b)
template<>
EIGEN_STRONG_INLINE Packet4cf pnegate (const Packet4cf &a)
template<>
EIGEN_STRONG_INLINE Packet4cf pconj (const Packet4cf &a)
template<>
EIGEN_STRONG_INLINE Packet4cf pmul< Packet4cf > (const Packet4cf &a, const Packet4cf &b)
template<>
EIGEN_STRONG_INLINE Packet4cf pand< Packet4cf > (const Packet4cf &a, const Packet4cf &b)
template<>
EIGEN_STRONG_INLINE Packet4cf por< Packet4cf > (const Packet4cf &a, const Packet4cf &b)
template<>
EIGEN_STRONG_INLINE Packet4cf pxor< Packet4cf > (const Packet4cf &a, const Packet4cf &b)
template<>
EIGEN_STRONG_INLINE Packet4cf pandnot< Packet4cf > (const Packet4cf &a, const Packet4cf &b)
template<>
EIGEN_STRONG_INLINE Packet4cf pload< Packet4cf > (const std::complex< float > *from)
template<>
EIGEN_STRONG_INLINE Packet4cf ploadu< Packet4cf > (const std::complex< float > *from)
template<>
EIGEN_STRONG_INLINE Packet4cf pset1< Packet4cf > (const std::complex< float > &from)
template<>
EIGEN_STRONG_INLINE Packet4cf ploaddup< Packet4cf > (const std::complex< float > *from)
template<>
EIGEN_STRONG_INLINE void pstore< std::complex< float > > (std::complex< float > *to, const Packet4cf &from)
template<>
EIGEN_STRONG_INLINE void pstoreu< std::complex< float > > (std::complex< float > *to, const Packet4cf &from)
template<>
EIGEN_DEVICE_FUNC Packet4cf pgather< std::complex< float >, Packet4cf > (const std::complex< float > *from, Index stride)
template<>
EIGEN_DEVICE_FUNC void pscatter< std::complex< float >, Packet4cf > (std::complex< float > *to, const Packet4cf &from, Index stride)
template<>
EIGEN_STRONG_INLINE std::complex< float > pfirst< Packet4cf > (const Packet4cf &a)
template<>
EIGEN_STRONG_INLINE Packet4cf preverse (const Packet4cf &a)
template<>
EIGEN_STRONG_INLINE std::complex< float > predux< Packet4cf > (const Packet4cf &a)
template<>
EIGEN_STRONG_INLINE Packet4cf preduxp< Packet4cf > (const Packet4cf *vecs)
template<>
EIGEN_STRONG_INLINE std::complex< float > predux_mul< Packet4cf > (const Packet4cf &a)
template<>
EIGEN_STRONG_INLINE Packet4cf pdiv< Packet4cf > (const Packet4cf &a, const Packet4cf &b)
template<>
EIGEN_STRONG_INLINE Packet4cf pcplxflip< Packet4cf > (const Packet4cf &x)
template<>
EIGEN_STRONG_INLINE Packet2cd padd< Packet2cd > (const Packet2cd &a, const Packet2cd &b)
template<>
EIGEN_STRONG_INLINE Packet2cd psub< Packet2cd > (const Packet2cd &a, const Packet2cd &b)
template<>
EIGEN_STRONG_INLINE Packet2cd pnegate (const Packet2cd &a)
template<>
EIGEN_STRONG_INLINE Packet2cd pconj (const Packet2cd &a)
template<>
EIGEN_STRONG_INLINE Packet2cd pmul< Packet2cd > (const Packet2cd &a, const Packet2cd &b)
template<>
EIGEN_STRONG_INLINE Packet2cd pand< Packet2cd > (const Packet2cd &a, const Packet2cd &b)
template<>
EIGEN_STRONG_INLINE Packet2cd por< Packet2cd > (const Packet2cd &a, const Packet2cd &b)
template<>
EIGEN_STRONG_INLINE Packet2cd pxor< Packet2cd > (const Packet2cd &a, const Packet2cd &b)
template<>
EIGEN_STRONG_INLINE Packet2cd pandnot< Packet2cd > (const Packet2cd &a, const Packet2cd &b)
template<>
EIGEN_STRONG_INLINE Packet2cd pload< Packet2cd > (const std::complex< double > *from)
template<>
EIGEN_STRONG_INLINE Packet2cd ploadu< Packet2cd > (const std::complex< double > *from)
template<>
EIGEN_STRONG_INLINE Packet2cd pset1< Packet2cd > (const std::complex< double > &from)
template<>
EIGEN_STRONG_INLINE Packet2cd ploaddup< Packet2cd > (const std::complex< double > *from)
template<>
EIGEN_STRONG_INLINE void pstore< std::complex< double > > (std::complex< double > *to, const Packet2cd &from)
template<>
EIGEN_STRONG_INLINE void pstoreu< std::complex< double > > (std::complex< double > *to, const Packet2cd &from)
template<>
EIGEN_DEVICE_FUNC Packet2cd pgather< std::complex< double >, Packet2cd > (const std::complex< double > *from, Index stride)
template<>
EIGEN_DEVICE_FUNC void pscatter< std::complex< double >, Packet2cd > (std::complex< double > *to, const Packet2cd &from, Index stride)
template<>
EIGEN_STRONG_INLINE std::complex< double > pfirst< Packet2cd > (const Packet2cd &a)
template<>
EIGEN_STRONG_INLINE Packet2cd preverse (const Packet2cd &a)
template<>
EIGEN_STRONG_INLINE std::complex< double > predux< Packet2cd > (const Packet2cd &a)
template<>
EIGEN_STRONG_INLINE Packet2cd preduxp< Packet2cd > (const Packet2cd *vecs)
template<>
EIGEN_STRONG_INLINE std::complex< double > predux_mul< Packet2cd > (const Packet2cd &a)
template<>
EIGEN_STRONG_INLINE Packet2cd pdiv< Packet2cd > (const Packet2cd &a, const Packet2cd &b)
template<>
EIGEN_STRONG_INLINE Packet2cd pcplxflip< Packet2cd > (const Packet2cd &x)
EIGEN_DEVICE_FUNC void ptranspose (PacketBlock< Packet4cf, 4 > &kernel)
EIGEN_DEVICE_FUNC void ptranspose (PacketBlock< Packet2cd, 2 > &kernel)
template<>
EIGEN_STRONG_INLINE Packet4cf pinsertfirst (const Packet4cf &a, std::complex< float > b)
template<>
EIGEN_STRONG_INLINE Packet2cd pinsertfirst (const Packet2cd &a, std::complex< double > b)
template<>
EIGEN_STRONG_INLINE Packet4cf pinsertlast (const Packet4cf &a, std::complex< float > b)
template<>
EIGEN_STRONG_INLINE Packet2cd pinsertlast (const Packet2cd &a, std::complex< double > b)
Packet8i pshiftleft (Packet8i v, int n)
Packet8f pshiftright (Packet8f v, int n)
template<>
EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet8f psin< Packet8f > (const Packet8f &_x)
template<>
EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet8f plog< Packet8f > (const Packet8f &_x)
template<>
EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet8f pexp< Packet8f > (const Packet8f &_x)
template<>
EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet8f ptanh< Packet8f > (const Packet8f &x)
template<>
EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet4d pexp< Packet4d > (const Packet4d &_x)
template<>
EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet8f psqrt< Packet8f > (const Packet8f &x)
template<>
EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet4d psqrt< Packet4d > (const Packet4d &x)
template<>
EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet8f prsqrt< Packet8f > (const Packet8f &x)
template<>
EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet4d prsqrt< Packet4d > (const Packet4d &x)
template<>
EIGEN_STRONG_INLINE Packet8f pset1< Packet8f > (const float &from)
template<>
EIGEN_STRONG_INLINE Packet4d pset1< Packet4d > (const double &from)
template<>
EIGEN_STRONG_INLINE Packet8i pset1< Packet8i > (const int &from)
template<>
EIGEN_STRONG_INLINE Packet8f pload1< Packet8f > (const float *from)
template<>
EIGEN_STRONG_INLINE Packet4d pload1< Packet4d > (const double *from)
template<>
EIGEN_STRONG_INLINE Packet8f plset< Packet8f > (const float &a)
template<>
EIGEN_STRONG_INLINE Packet4d plset< Packet4d > (const double &a)
template<>
EIGEN_STRONG_INLINE Packet8f padd< Packet8f > (const Packet8f &a, const Packet8f &b)
template<>
EIGEN_STRONG_INLINE Packet4d padd< Packet4d > (const Packet4d &a, const Packet4d &b)
template<>
EIGEN_STRONG_INLINE Packet8f psub< Packet8f > (const Packet8f &a, const Packet8f &b)
template<>
EIGEN_STRONG_INLINE Packet4d psub< Packet4d > (const Packet4d &a, const Packet4d &b)
template<>
EIGEN_STRONG_INLINE Packet8f pnegate (const Packet8f &a)
template<>
EIGEN_STRONG_INLINE Packet4d pnegate (const Packet4d &a)
template<>
EIGEN_STRONG_INLINE Packet8f pconj (const Packet8f &a)
template<>
EIGEN_STRONG_INLINE Packet4d pconj (const Packet4d &a)
template<>
EIGEN_STRONG_INLINE Packet8i pconj (const Packet8i &a)
template<>
EIGEN_STRONG_INLINE Packet8f pmul< Packet8f > (const Packet8f &a, const Packet8f &b)
template<>
EIGEN_STRONG_INLINE Packet4d pmul< Packet4d > (const Packet4d &a, const Packet4d &b)
template<>
EIGEN_STRONG_INLINE Packet8f pdiv< Packet8f > (const Packet8f &a, const Packet8f &b)
template<>
EIGEN_STRONG_INLINE Packet4d pdiv< Packet4d > (const Packet4d &a, const Packet4d &b)
template<>
EIGEN_STRONG_INLINE Packet8i pdiv< Packet8i > (const Packet8i &, const Packet8i &)
template<>
EIGEN_STRONG_INLINE Packet8f pmin< Packet8f > (const Packet8f &a, const Packet8f &b)
template<>
EIGEN_STRONG_INLINE Packet4d pmin< Packet4d > (const Packet4d &a, const Packet4d &b)
template<>
EIGEN_STRONG_INLINE Packet8f pmax< Packet8f > (const Packet8f &a, const Packet8f &b)
template<>
EIGEN_STRONG_INLINE Packet4d pmax< Packet4d > (const Packet4d &a, const Packet4d &b)
template<>
EIGEN_STRONG_INLINE Packet8f pround< Packet8f > (const Packet8f &a)
template<>
EIGEN_STRONG_INLINE Packet4d pround< Packet4d > (const Packet4d &a)
template<>
EIGEN_STRONG_INLINE Packet8f pceil< Packet8f > (const Packet8f &a)
template<>
EIGEN_STRONG_INLINE Packet4d pceil< Packet4d > (const Packet4d &a)
template<>
EIGEN_STRONG_INLINE Packet8f pfloor< Packet8f > (const Packet8f &a)
template<>
EIGEN_STRONG_INLINE Packet4d pfloor< Packet4d > (const Packet4d &a)
template<>
EIGEN_STRONG_INLINE Packet8f pand< Packet8f > (const Packet8f &a, const Packet8f &b)
template<>
EIGEN_STRONG_INLINE Packet4d pand< Packet4d > (const Packet4d &a, const Packet4d &b)
template<>
EIGEN_STRONG_INLINE Packet8f por< Packet8f > (const Packet8f &a, const Packet8f &b)
template<>
EIGEN_STRONG_INLINE Packet4d por< Packet4d > (const Packet4d &a, const Packet4d &b)
template<>
EIGEN_STRONG_INLINE Packet8f pxor< Packet8f > (const Packet8f &a, const Packet8f &b)
template<>
EIGEN_STRONG_INLINE Packet4d pxor< Packet4d > (const Packet4d &a, const Packet4d &b)
template<>
EIGEN_STRONG_INLINE Packet8f pandnot< Packet8f > (const Packet8f &a, const Packet8f &b)
template<>
EIGEN_STRONG_INLINE Packet4d pandnot< Packet4d > (const Packet4d &a, const Packet4d &b)
template<>
EIGEN_STRONG_INLINE Packet8f pload< Packet8f > (const float *from)
template<>
EIGEN_STRONG_INLINE Packet4d pload< Packet4d > (const double *from)
template<>
EIGEN_STRONG_INLINE Packet8i pload< Packet8i > (const int *from)
template<>
EIGEN_STRONG_INLINE Packet8f ploadu< Packet8f > (const float *from)
template<>
EIGEN_STRONG_INLINE Packet4d ploadu< Packet4d > (const double *from)
template<>
EIGEN_STRONG_INLINE Packet8i ploadu< Packet8i > (const int *from)
template<>
EIGEN_STRONG_INLINE Packet8f ploaddup< Packet8f > (const float *from)
template<>
EIGEN_STRONG_INLINE Packet4d ploaddup< Packet4d > (const double *from)
template<>
EIGEN_STRONG_INLINE Packet8f ploadquad< Packet8f > (const float *from)
template<>
EIGEN_STRONG_INLINE void pstore< float > (float *to, const Packet8f &from)
template<>
EIGEN_STRONG_INLINE void pstore< double > (double *to, const Packet4d &from)
template<>
EIGEN_STRONG_INLINE void pstore< int > (int *to, const Packet8i &from)
template<>
EIGEN_STRONG_INLINE void pstoreu< float > (float *to, const Packet8f &from)
template<>
EIGEN_STRONG_INLINE void pstoreu< double > (double *to, const Packet4d &from)
template<>
EIGEN_STRONG_INLINE void pstoreu< int > (int *to, const Packet8i &from)
template<>
EIGEN_DEVICE_FUNC Packet8f pgather< float, Packet8f > (const float *from, Index stride)
template<>
EIGEN_DEVICE_FUNC Packet4d pgather< double, Packet4d > (const double *from, Index stride)
template<>
EIGEN_DEVICE_FUNC void pscatter< float, Packet8f > (float *to, const Packet8f &from, Index stride)
template<>
EIGEN_DEVICE_FUNC void pscatter< double, Packet4d > (double *to, const Packet4d &from, Index stride)
template<>
EIGEN_STRONG_INLINE void pstore1< Packet8f > (float *to, const float &a)
template<>
EIGEN_STRONG_INLINE void pstore1< Packet4d > (double *to, const double &a)
template<>
EIGEN_STRONG_INLINE void pstore1< Packet8i > (int *to, const int &a)
template<>
EIGEN_STRONG_INLINE void prefetch< double > (const double *addr)
template<>
EIGEN_STRONG_INLINE float pfirst< Packet8f > (const Packet8f &a)
template<>
EIGEN_STRONG_INLINE double pfirst< Packet4d > (const Packet4d &a)
template<>
EIGEN_STRONG_INLINE int pfirst< Packet8i > (const Packet8i &a)
template<>
EIGEN_STRONG_INLINE Packet8f preverse (const Packet8f &a)
template<>
EIGEN_STRONG_INLINE Packet4d preverse (const Packet4d &a)
template<>
EIGEN_STRONG_INLINE Packet8f pabs (const Packet8f &a)
template<>
EIGEN_STRONG_INLINE Packet4d pabs (const Packet4d &a)
template<>
EIGEN_STRONG_INLINE Packet8f preduxp< Packet8f > (const Packet8f *vecs)
template<>
EIGEN_STRONG_INLINE Packet4d preduxp< Packet4d > (const Packet4d *vecs)
template<>
EIGEN_STRONG_INLINE float predux< Packet8f > (const Packet8f &a)
template<>
EIGEN_STRONG_INLINE double predux< Packet4d > (const Packet4d &a)
template<>
EIGEN_STRONG_INLINE Packet4f predux_downto4< Packet8f > (const Packet8f &a)
template<>
EIGEN_STRONG_INLINE float predux_mul< Packet8f > (const Packet8f &a)
template<>
EIGEN_STRONG_INLINE double predux_mul< Packet4d > (const Packet4d &a)
template<>
EIGEN_STRONG_INLINE float predux_min< Packet8f > (const Packet8f &a)
template<>
EIGEN_STRONG_INLINE double predux_min< Packet4d > (const Packet4d &a)
template<>
EIGEN_STRONG_INLINE float predux_max< Packet8f > (const Packet8f &a)
template<>
EIGEN_STRONG_INLINE double predux_max< Packet4d > (const Packet4d &a)
EIGEN_DEVICE_FUNC void ptranspose (PacketBlock< Packet8f, 8 > &kernel)
EIGEN_DEVICE_FUNC void ptranspose (PacketBlock< Packet8f, 4 > &kernel)
EIGEN_DEVICE_FUNC void ptranspose (PacketBlock< Packet4d, 4 > &kernel)
template<>
EIGEN_STRONG_INLINE Packet8f pblend (const Selector< 8 > &ifPacket, const Packet8f &thenPacket, const Packet8f &elsePacket)
template<>
EIGEN_STRONG_INLINE Packet4d pblend (const Selector< 4 > &ifPacket, const Packet4d &thenPacket, const Packet4d &elsePacket)
template<>
EIGEN_STRONG_INLINE Packet8f pinsertfirst (const Packet8f &a, float b)
template<>
EIGEN_STRONG_INLINE Packet4d pinsertfirst (const Packet4d &a, double b)
template<>
EIGEN_STRONG_INLINE Packet8f pinsertlast (const Packet8f &a, float b)
template<>
EIGEN_STRONG_INLINE Packet4d pinsertlast (const Packet4d &a, double b)
template<>
EIGEN_STRONG_INLINE Packet8i pcast< Packet8f, Packet8i > (const Packet8f &a)
template<>
EIGEN_STRONG_INLINE Packet8f pcast< Packet8i, Packet8f > (const Packet8i &a)
template<>
EIGEN_STRONG_INLINE Packet16f pset1< Packet16f > (const float &from)
template<>
EIGEN_STRONG_INLINE Packet8d pset1< Packet8d > (const double &from)
template<>
EIGEN_STRONG_INLINE Packet16i pset1< Packet16i > (const int &from)
template<>
EIGEN_STRONG_INLINE Packet16f pload1< Packet16f > (const float *from)
template<>
EIGEN_STRONG_INLINE Packet8d pload1< Packet8d > (const double *from)
template<>
EIGEN_STRONG_INLINE Packet16f plset< Packet16f > (const float &a)
template<>
EIGEN_STRONG_INLINE Packet8d plset< Packet8d > (const double &a)
template<>
EIGEN_STRONG_INLINE Packet16f padd< Packet16f > (const Packet16f &a, const Packet16f &b)
template<>
EIGEN_STRONG_INLINE Packet8d padd< Packet8d > (const Packet8d &a, const Packet8d &b)
template<>
EIGEN_STRONG_INLINE Packet16f psub< Packet16f > (const Packet16f &a, const Packet16f &b)
template<>
EIGEN_STRONG_INLINE Packet8d psub< Packet8d > (const Packet8d &a, const Packet8d &b)
template<>
EIGEN_STRONG_INLINE Packet16f pnegate (const Packet16f &a)
template<>
EIGEN_STRONG_INLINE Packet8d pnegate (const Packet8d &a)
template<>
EIGEN_STRONG_INLINE Packet16f pconj (const Packet16f &a)
template<>
EIGEN_STRONG_INLINE Packet8d pconj (const Packet8d &a)
template<>
EIGEN_STRONG_INLINE Packet16i pconj (const Packet16i &a)
template<>
EIGEN_STRONG_INLINE Packet16f pmul< Packet16f > (const Packet16f &a, const Packet16f &b)
template<>
EIGEN_STRONG_INLINE Packet8d pmul< Packet8d > (const Packet8d &a, const Packet8d &b)
template<>
EIGEN_STRONG_INLINE Packet16f pdiv< Packet16f > (const Packet16f &a, const Packet16f &b)
template<>
EIGEN_STRONG_INLINE Packet8d pdiv< Packet8d > (const Packet8d &a, const Packet8d &b)
template<>
EIGEN_STRONG_INLINE Packet16f pmin< Packet16f > (const Packet16f &a, const Packet16f &b)
template<>
EIGEN_STRONG_INLINE Packet8d pmin< Packet8d > (const Packet8d &a, const Packet8d &b)
template<>
EIGEN_STRONG_INLINE Packet16f pmax< Packet16f > (const Packet16f &a, const Packet16f &b)
template<>
EIGEN_STRONG_INLINE Packet8d pmax< Packet8d > (const Packet8d &a, const Packet8d &b)
template<>
EIGEN_STRONG_INLINE Packet16f pand< Packet16f > (const Packet16f &a, const Packet16f &b)
template<>
EIGEN_STRONG_INLINE Packet8d pand< Packet8d > (const Packet8d &a, const Packet8d &b)
template<>
EIGEN_STRONG_INLINE Packet16f por< Packet16f > (const Packet16f &a, const Packet16f &b)
template<>
EIGEN_STRONG_INLINE Packet8d por< Packet8d > (const Packet8d &a, const Packet8d &b)
template<>
EIGEN_STRONG_INLINE Packet16f pxor< Packet16f > (const Packet16f &a, const Packet16f &b)
template<>
EIGEN_STRONG_INLINE Packet8d pxor< Packet8d > (const Packet8d &a, const Packet8d &b)
template<>
EIGEN_STRONG_INLINE Packet16f pandnot< Packet16f > (const Packet16f &a, const Packet16f &b)
template<>
EIGEN_STRONG_INLINE Packet8d pandnot< Packet8d > (const Packet8d &a, const Packet8d &b)
template<>
EIGEN_STRONG_INLINE Packet16f pload< Packet16f > (const float *from)
template<>
EIGEN_STRONG_INLINE Packet8d pload< Packet8d > (const double *from)
template<>
EIGEN_STRONG_INLINE Packet16i pload< Packet16i > (const int *from)
template<>
EIGEN_STRONG_INLINE Packet16f ploadu< Packet16f > (const float *from)
template<>
EIGEN_STRONG_INLINE Packet8d ploadu< Packet8d > (const double *from)
template<>
EIGEN_STRONG_INLINE Packet16i ploadu< Packet16i > (const int *from)
template<>
EIGEN_STRONG_INLINE Packet16f ploaddup< Packet16f > (const float *from)
template<>
EIGEN_STRONG_INLINE Packet8d ploaddup< Packet8d > (const double *from)
template<>
EIGEN_STRONG_INLINE Packet16f ploadquad< Packet16f > (const float *from)
template<>
EIGEN_STRONG_INLINE Packet8d ploadquad< Packet8d > (const double *from)
template<>
EIGEN_STRONG_INLINE void pstore< float > (float *to, const Packet16f &from)
template<>
EIGEN_STRONG_INLINE void pstore< double > (double *to, const Packet8d &from)
template<>
EIGEN_STRONG_INLINE void pstore< int > (int *to, const Packet16i &from)
template<>
EIGEN_STRONG_INLINE void pstoreu< float > (float *to, const Packet16f &from)
template<>
EIGEN_STRONG_INLINE void pstoreu< double > (double *to, const Packet8d &from)
template<>
EIGEN_STRONG_INLINE void pstoreu< int > (int *to, const Packet16i &from)
template<>
EIGEN_DEVICE_FUNC Packet16f pgather< float, Packet16f > (const float *from, Index stride)
template<>
EIGEN_DEVICE_FUNC Packet8d pgather< double, Packet8d > (const double *from, Index stride)
template<>
EIGEN_DEVICE_FUNC void pscatter< float, Packet16f > (float *to, const Packet16f &from, Index stride)
template<>
EIGEN_DEVICE_FUNC void pscatter< double, Packet8d > (double *to, const Packet8d &from, Index stride)
template<>
EIGEN_STRONG_INLINE void pstore1< Packet16f > (float *to, const float &a)
template<>
EIGEN_STRONG_INLINE void pstore1< Packet8d > (double *to, const double &a)
template<>
EIGEN_STRONG_INLINE void pstore1< Packet16i > (int *to, const int &a)
template<>
EIGEN_STRONG_INLINE float pfirst< Packet16f > (const Packet16f &a)
template<>
EIGEN_STRONG_INLINE double pfirst< Packet8d > (const Packet8d &a)
template<>
EIGEN_STRONG_INLINE int pfirst< Packet16i > (const Packet16i &a)
template<>
EIGEN_STRONG_INLINE Packet16f preverse (const Packet16f &a)
template<>
EIGEN_STRONG_INLINE Packet8d preverse (const Packet8d &a)
template<>
EIGEN_STRONG_INLINE Packet16f pabs (const Packet16f &a)
template<>
EIGEN_STRONG_INLINE Packet8d pabs (const Packet8d &a)
template<>
EIGEN_STRONG_INLINE Packet16f preduxp< Packet16f > (const Packet16f *vecs)
template<>
EIGEN_STRONG_INLINE Packet8d preduxp< Packet8d > (const Packet8d *vecs)
template<>
EIGEN_STRONG_INLINE float predux< Packet16f > (const Packet16f &a)
template<>
EIGEN_STRONG_INLINE double predux< Packet8d > (const Packet8d &a)
template<>
EIGEN_STRONG_INLINE Packet8f predux_downto4< Packet16f > (const Packet16f &a)
template<>
EIGEN_STRONG_INLINE Packet4d predux_downto4< Packet8d > (const Packet8d &a)
template<>
EIGEN_STRONG_INLINE float predux_mul< Packet16f > (const Packet16f &a)
template<>
EIGEN_STRONG_INLINE double predux_mul< Packet8d > (const Packet8d &a)
template<>
EIGEN_STRONG_INLINE float predux_min< Packet16f > (const Packet16f &a)
template<>
EIGEN_STRONG_INLINE double predux_min< Packet8d > (const Packet8d &a)
template<>
EIGEN_STRONG_INLINE float predux_max< Packet16f > (const Packet16f &a)
template<>
EIGEN_STRONG_INLINE double predux_max< Packet8d > (const Packet8d &a)
EIGEN_DEVICE_FUNC void ptranspose (PacketBlock< Packet16f, 16 > &kernel)
EIGEN_DEVICE_FUNC void ptranspose (PacketBlock< Packet16f, 4 > &kernel)
EIGEN_DEVICE_FUNC void ptranspose (PacketBlock< Packet8d, 4 > &kernel)
EIGEN_DEVICE_FUNC void ptranspose (PacketBlock< Packet8d, 8 > &kernel)
template<>
EIGEN_STRONG_INLINE Packet16f pblend (const Selector< 16 > &, const Packet16f &, const Packet16f &)
template<>
EIGEN_STRONG_INLINE Packet8d pblend (const Selector< 8 > &, const Packet8d &, const Packet8d &)
uint32x4_t p4ui_CONJ_XOR ()
uint32x2_t p2ui_CONJ_XOR ()
template<>
EIGEN_STRONG_INLINE Packet4i pset1< Packet4i > (const int32_t &from)
template<>
EIGEN_STRONG_INLINE Packet4i plset< Packet4i > (const int32_t &a)
template<>
EIGEN_STRONG_INLINE Packet4i pload< Packet4i > (const int32_t *from)
template<>
EIGEN_STRONG_INLINE Packet4i ploadu< Packet4i > (const int32_t *from)
template<>
EIGEN_STRONG_INLINE Packet4i ploaddup< Packet4i > (const int32_t *from)
template<>
EIGEN_STRONG_INLINE void pstore< int32_t > (int32_t *to, const Packet4i &from)
template<>
EIGEN_STRONG_INLINE void pstoreu< int32_t > (int32_t *to, const Packet4i &from)
template<>
EIGEN_DEVICE_FUNC Packet4i pgather< int32_t, Packet4i > (const int32_t *from, Index stride)
template<>
EIGEN_DEVICE_FUNC void pscatter< int32_t, Packet4i > (int32_t *to, const Packet4i &from, Index stride)
template<>
EIGEN_STRONG_INLINE void prefetch< int32_t > (const int32_t *addr)
template<>
EIGEN_STRONG_INLINE int32_t pfirst< Packet4i > (const Packet4i &a)
template<>
EIGEN_STRONG_INLINE int32_t predux< Packet4i > (const Packet4i &a)
template<>
EIGEN_STRONG_INLINE int32_t predux_mul< Packet4i > (const Packet4i &a)
template<>
EIGEN_STRONG_INLINE int32_t predux_min< Packet4i > (const Packet4i &a)
template<>
EIGEN_STRONG_INLINE int32_t predux_max< Packet4i > (const Packet4i &a)
EIGEN_STRONG_INLINE Packet2cf pcplxflip (const Packet2cf &x)
template<>
EIGEN_STRONG_INLINE Packet1cd padd< Packet1cd > (const Packet1cd &a, const Packet1cd &b)
template<>
EIGEN_STRONG_INLINE Packet1cd psub< Packet1cd > (const Packet1cd &a, const Packet1cd &b)
template<>
EIGEN_STRONG_INLINE Packet1cd pnegate (const Packet1cd &a)
template<>
EIGEN_STRONG_INLINE Packet1cd pconj (const Packet1cd &a)
template<>
EIGEN_STRONG_INLINE Packet1cd pmul< Packet1cd > (const Packet1cd &a, const Packet1cd &b)
template<>
EIGEN_STRONG_INLINE Packet1cd pand< Packet1cd > (const Packet1cd &a, const Packet1cd &b)
template<>
EIGEN_STRONG_INLINE Packet1cd por< Packet1cd > (const Packet1cd &a, const Packet1cd &b)
template<>
EIGEN_STRONG_INLINE Packet1cd pxor< Packet1cd > (const Packet1cd &a, const Packet1cd &b)
template<>
EIGEN_STRONG_INLINE Packet1cd pandnot< Packet1cd > (const Packet1cd &a, const Packet1cd &b)
template<>
EIGEN_STRONG_INLINE Packet1cd pload< Packet1cd > (const std::complex< double > *from)
template<>
EIGEN_STRONG_INLINE Packet1cd ploadu< Packet1cd > (const std::complex< double > *from)
template<>
EIGEN_STRONG_INLINE Packet1cd pset1< Packet1cd > (const std::complex< double > &from)
template<>
EIGEN_STRONG_INLINE Packet1cd ploaddup< Packet1cd > (const std::complex< double > *from)
template<>
EIGEN_STRONG_INLINE void pstore< std::complex< double > > (std::complex< double > *to, const Packet1cd &from)
template<>
EIGEN_STRONG_INLINE void pstoreu< std::complex< double > > (std::complex< double > *to, const Packet1cd &from)
template<>
EIGEN_STRONG_INLINE void prefetch< std::complex< double > > (const std::complex< double > *addr)
template<>
EIGEN_STRONG_INLINE std::complex< double > pfirst< Packet1cd > (const Packet1cd &a)
template<>
EIGEN_STRONG_INLINE Packet1cd preverse (const Packet1cd &a)
template<>
EIGEN_STRONG_INLINE std::complex< double > predux< Packet1cd > (const Packet1cd &a)
template<>
EIGEN_STRONG_INLINE Packet1cd preduxp< Packet1cd > (const Packet1cd *vecs)
template<>
EIGEN_STRONG_INLINE std::complex< double > predux_mul< Packet1cd > (const Packet1cd &a)
template<>
EIGEN_STRONG_INLINE Packet1cd pdiv< Packet1cd > (const Packet1cd &a, const Packet1cd &b)
EIGEN_STRONG_INLINE Packet1cd pcplxflip (const Packet1cd &x)
template<>
EIGEN_STRONG_INLINE Packet2cf pblend (const Selector< 2 > &ifPacket, const Packet2cf &thenPacket, const Packet2cf &elsePacket)
template<>
EIGEN_STRONG_INLINE Packet2cf pinsertfirst (const Packet2cf &a, std::complex< float > b)
template<>
EIGEN_STRONG_INLINE Packet1cd pinsertfirst (const Packet1cd &, std::complex< double > b)
template<>
EIGEN_STRONG_INLINE Packet2cf pinsertlast (const Packet2cf &a, std::complex< float > b)
template<>
EIGEN_STRONG_INLINE Packet1cd pinsertlast (const Packet1cd &, std::complex< double > b)
template<>
EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet2d pexp< Packet2d > (const Packet2d &_x)
template<>
EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet4f psin< Packet4f > (const Packet4f &_x)
template<>
EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet4f pcos< Packet4f > (const Packet4f &_x)
template<>
EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet4f psqrt< Packet4f > (const Packet4f &x)
template<>
EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet2d psqrt< Packet2d > (const Packet2d &x)
template<>
EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet2d prsqrt< Packet2d > (const Packet2d &x)
template<>
EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet4f ptanh< Packet4f > (const Packet4f &x)
template<>
EIGEN_STRONG_INLINE Packet2d pset1< Packet2d > (const double &from)
template<>
EIGEN_STRONG_INLINE Packet2d plset< Packet2d > (const double &a)
template<>
EIGEN_STRONG_INLINE Packet2d padd< Packet2d > (const Packet2d &a, const Packet2d &b)
template<>
EIGEN_STRONG_INLINE Packet2d psub< Packet2d > (const Packet2d &a, const Packet2d &b)
template<>
EIGEN_STRONG_INLINE Packet2d pnegate (const Packet2d &a)
template<>
EIGEN_STRONG_INLINE Packet2d pconj (const Packet2d &a)
template<>
EIGEN_STRONG_INLINE Packet2d pmul< Packet2d > (const Packet2d &a, const Packet2d &b)
template<>
EIGEN_STRONG_INLINE Packet2d pdiv< Packet2d > (const Packet2d &a, const Packet2d &b)
template<>
EIGEN_STRONG_INLINE Packet2d pmin< Packet2d > (const Packet2d &a, const Packet2d &b)
template<>
EIGEN_STRONG_INLINE Packet2d pmax< Packet2d > (const Packet2d &a, const Packet2d &b)
template<>
EIGEN_STRONG_INLINE Packet2d pand< Packet2d > (const Packet2d &a, const Packet2d &b)
template<>
EIGEN_STRONG_INLINE Packet2d por< Packet2d > (const Packet2d &a, const Packet2d &b)
template<>
EIGEN_STRONG_INLINE Packet2d pxor< Packet2d > (const Packet2d &a, const Packet2d &b)
template<>
EIGEN_STRONG_INLINE Packet2d pandnot< Packet2d > (const Packet2d &a, const Packet2d &b)
template<>
EIGEN_STRONG_INLINE Packet2d pload< Packet2d > (const double *from)
template<>
EIGEN_STRONG_INLINE Packet2d ploadu< Packet2d > (const double *from)
template<>
EIGEN_STRONG_INLINE Packet2d ploaddup< Packet2d > (const double *from)
template<>
EIGEN_STRONG_INLINE void pstore< double > (double *to, const Packet2d &from)
template<>
EIGEN_STRONG_INLINE void pstoreu< double > (double *to, const Packet2d &from)
template<>
EIGEN_DEVICE_FUNC Packet2d pgather< double, Packet2d > (const double *from, Index stride)
template<>
EIGEN_DEVICE_FUNC void pscatter< double, Packet2d > (double *to, const Packet2d &from, Index stride)
template<>
EIGEN_STRONG_INLINE void pstore1< Packet4f > (float *to, const float &a)
template<>
EIGEN_STRONG_INLINE void pstore1< Packet2d > (double *to, const double &a)
template<>
EIGEN_STRONG_INLINE double pfirst< Packet2d > (const Packet2d &a)
template<>
EIGEN_STRONG_INLINE Packet2d preverse (const Packet2d &a)
template<>
EIGEN_STRONG_INLINE Packet2d pabs (const Packet2d &a)
template<>
EIGEN_STRONG_INLINE void pbroadcast4< Packet2d > (const double *a, Packet2d &a0, Packet2d &a1, Packet2d &a2, Packet2d &a3)
EIGEN_STRONG_INLINE void punpackp (Packet4f *vecs)
template<>
EIGEN_STRONG_INLINE Packet2d preduxp< Packet2d > (const Packet2d *vecs)
template<>
EIGEN_STRONG_INLINE double predux< Packet2d > (const Packet2d &a)
template<>
EIGEN_STRONG_INLINE double predux_mul< Packet2d > (const Packet2d &a)
template<>
EIGEN_STRONG_INLINE double predux_min< Packet2d > (const Packet2d &a)
template<>
EIGEN_STRONG_INLINE double predux_max< Packet2d > (const Packet2d &a)
EIGEN_DEVICE_FUNC void ptranspose (PacketBlock< Packet2d, 2 > &kernel)
template<>
EIGEN_STRONG_INLINE Packet2d pblend (const Selector< 2 > &ifPacket, const Packet2d &thenPacket, const Packet2d &elsePacket)
template<>
EIGEN_STRONG_INLINE Packet4f pinsertfirst (const Packet4f &a, float b)
template<>
EIGEN_STRONG_INLINE Packet2d pinsertfirst (const Packet2d &a, double b)
template<>
EIGEN_STRONG_INLINE Packet4f pinsertlast (const Packet4f &a, float b)
template<>
EIGEN_STRONG_INLINE Packet2d pinsertlast (const Packet2d &a, double b)
template<>
EIGEN_STRONG_INLINE Packet4i pcast< Packet4f, Packet4i > (const Packet4f &a)
template<>
EIGEN_STRONG_INLINE Packet4f pcast< Packet4i, Packet4f > (const Packet4i &a)
template<>
EIGEN_STRONG_INLINE Packet4f pcast< Packet2d, Packet4f > (const Packet2d &a, const Packet2d &b)
template<>
EIGEN_STRONG_INLINE Packet2d pcast< Packet4f, Packet2d > (const Packet4f &a)
template<>
EIGEN_DEVICE_FUNC Packet1cd pgather< std::complex< double >, Packet1cd > (const std::complex< double > *from, Index stride EIGEN_UNUSED)
template<>
EIGEN_DEVICE_FUNC void pscatter< std::complex< double >, Packet1cd > (std::complex< double > *to, const Packet1cd &from, Index stride EIGEN_UNUSED)
EIGEN_STRONG_INLINE void ptranspose (PacketBlock< Packet1cd, 2 > &kernel)
static _EIGEN_DECLARE_CONST_Packet2d (1, 1.0)
static _EIGEN_DECLARE_CONST_Packet2d (2, 2.0)
static _EIGEN_DECLARE_CONST_Packet2d (half, 0.5)
static _EIGEN_DECLARE_CONST_Packet2d (exp_hi, 709.437)
static _EIGEN_DECLARE_CONST_Packet2d (exp_lo,-709.436139303)
static _EIGEN_DECLARE_CONST_Packet2d (cephes_LOG2EF, 1.4426950408889634073599)
static _EIGEN_DECLARE_CONST_Packet2d (cephes_exp_p0, 1.26177193074810590878e-4)
static _EIGEN_DECLARE_CONST_Packet2d (cephes_exp_p1, 3.02994407707441961300e-2)
static _EIGEN_DECLARE_CONST_Packet2d (cephes_exp_p2, 9.99999999999999999910e-1)
static _EIGEN_DECLARE_CONST_Packet2d (cephes_exp_q0, 3.00198505138664455042e-6)
static _EIGEN_DECLARE_CONST_Packet2d (cephes_exp_q1, 2.52448340349684104192e-3)
static _EIGEN_DECLARE_CONST_Packet2d (cephes_exp_q2, 2.27265548208155028766e-1)
static _EIGEN_DECLARE_CONST_Packet2d (cephes_exp_q3, 2.00000000000000000009e0)
static _EIGEN_DECLARE_CONST_Packet2d (cephes_exp_C1, 0.693145751953125)
static _EIGEN_DECLARE_CONST_Packet2d (cephes_exp_C2, 1.42860682030941723212e-6)
static _EIGEN_DECLARE_CONST_FAST_Packet4i (ONE, 1)
static _EIGEN_DECLARE_CONST_FAST_Packet2d (ZERO, 0)
static _EIGEN_DECLARE_CONST_FAST_Packet2l (ZERO, 0)
static _EIGEN_DECLARE_CONST_FAST_Packet2l (ONE, 1)
std::ostream & operator<< (std::ostream &s, const Packet2l &v)
std::ostream & operator<< (std::ostream &s, const Packet2ul &v)
std::ostream & operator<< (std::ostream &s, const Packet2d &v)
template<int element>
EIGEN_STRONG_INLINE Packet4f vec_splat_packet4f (const Packet4f &from)
template<>
EIGEN_STRONG_INLINE Packet2d pmadd (const Packet2d &a, const Packet2d &b, const Packet2d &c)
template<>
EIGEN_STRONG_INLINE Packet2d pround< Packet2d > (const Packet2d &a)
template<>
EIGEN_STRONG_INLINE Packet2d pceil< Packet2d > (const Packet2d &a)
template<>
EIGEN_STRONG_INLINE Packet2d pfloor< Packet2d > (const Packet2d &a)
template<>
EIGEN_STRONG_INLINE Packet4i pabs< Packet4i > (const Packet4i &a)
template<>
EIGEN_STRONG_INLINE Packet2d pabs< Packet2d > (const Packet2d &a)
template<>
EIGEN_STRONG_INLINE Packet4f pabs< Packet4f > (const Packet4f &a)
template<typename FirstType , typename SizeType , typename IncrType >
ArithmeticSequence< Index, typename make_size_type< SizeType >::type, IncrType > makeIndexedViewCompatible (const ArithmeticSequence< FirstType, SizeType, IncrType > &ids, Index size, SpecializedType)
template<typename DstXprType , typename SrcXprType , typename Functor >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void resize_if_allowed (DstXprType &dst, const SrcXprType &src, const Functor &)
template<typename DstXprType , typename SrcXprType , typename T1 , typename T2 >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void resize_if_allowed (DstXprType &dst, const SrcXprType &src, const internal::assign_op< T1, T2 > &)
template<typename DstXprType , typename SrcXprType , typename Functor >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void call_dense_assignment_loop (DstXprType &dst, const SrcXprType &src, const Functor &func)
template<typename DstXprType , typename SrcXprType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void call_dense_assignment_loop (DstXprType &dst, const SrcXprType &src)
template<typename Dst , typename Src >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void call_assignment (Dst &dst, const Src &src)
template<typename Dst , typename Src >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void call_assignment (const Dst &dst, const Src &src)
template<typename Dst , typename Src , typename Func >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void call_assignment (Dst &dst, const Src &src, const Func &func, typename enable_if< evaluator_assume_aliasing< Src >::value, void * >::type=0)
template<typename Dst , typename Src , typename Func >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void call_assignment (Dst &dst, const Src &src, const Func &func, typename enable_if<!evaluator_assume_aliasing< Src >::value, void * >::type=0)
template<typename Dst , template< typename > class StorageBase, typename Src , typename Func >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void call_assignment (NoAlias< Dst, StorageBase > &dst, const Src &src, const Func &func)
template<typename Dst , typename Src , typename Func >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void call_assignment_no_alias (Dst &dst, const Src &src, const Func &func)
template<typename Dst , typename Src >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void call_assignment_no_alias (Dst &dst, const Src &src)
template<typename Dst , typename Src , typename Func >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void call_assignment_no_alias_no_transpose (Dst &dst, const Src &src, const Func &func)
template<typename Dst , typename Src >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void call_assignment_no_alias_no_transpose (Dst &dst, const Src &src)
template<typename Dst , typename Src >
void check_for_aliasing (const Dst &dst, const Src &src)
template<typename Decomposition >
Decomposition::RealScalar rcond_invmatrix_L1_norm_estimate (const Decomposition &dec)
template<typename Decomposition >
Decomposition::RealScalar rcond_estimate_helper (typename Decomposition::RealScalar matrix_norm, const Decomposition &dec)
Reciprocal condition number estimator.
static void check_DenseIndex_is_signed ()
template<int Alignment, typename Derived >
static Index first_aligned (const DenseBase< Derived > &m)
template<typename Derived >
static Index first_default_aligned (const DenseBase< Derived > &m)
template<typename T , int Size>
EIGEN_DEVICE_FUNC void check_static_allocation_size ()
template<typename SrcPacket , typename TgtPacket >
EIGEN_DEVICE_FUNC TgtPacket pcast (const SrcPacket &a)
template<typename SrcPacket , typename TgtPacket >
EIGEN_DEVICE_FUNC TgtPacket pcast (const SrcPacket &a, const SrcPacket &)
template<typename SrcPacket , typename TgtPacket >
EIGEN_DEVICE_FUNC TgtPacket pcast (const SrcPacket &a, const SrcPacket &, const SrcPacket &, const SrcPacket &)
template<typename Packet >
EIGEN_DEVICE_FUNC Packet padd (const Packet &a, const Packet &b)
template<typename Packet >
EIGEN_DEVICE_FUNC Packet psub (const Packet &a, const Packet &b)
template<typename Packet >
EIGEN_DEVICE_FUNC Packet pnegate (const Packet &a)
template<typename Packet >
EIGEN_DEVICE_FUNC Packet pconj (const Packet &a)
template<typename Packet >
EIGEN_DEVICE_FUNC Packet pmul (const Packet &a, const Packet &b)
template<typename Packet >
EIGEN_DEVICE_FUNC Packet pdiv (const Packet &a, const Packet &b)
template<typename Packet >
EIGEN_DEVICE_FUNC Packet pmin (const Packet &a, const Packet &b)
template<typename Packet >
EIGEN_DEVICE_FUNC Packet pmax (const Packet &a, const Packet &b)
template<typename Packet >
EIGEN_DEVICE_FUNC Packet pabs (const Packet &a)
template<typename Packet >
EIGEN_DEVICE_FUNC Packet parg (const Packet &a)
template<typename Packet >
EIGEN_DEVICE_FUNC Packet pand (const Packet &a, const Packet &b)
template<typename Packet >
EIGEN_DEVICE_FUNC Packet por (const Packet &a, const Packet &b)
template<typename Packet >
EIGEN_DEVICE_FUNC Packet pxor (const Packet &a, const Packet &b)
template<typename Packet >
EIGEN_DEVICE_FUNC Packet pandnot (const Packet &a, const Packet &b)
template<typename Packet >
EIGEN_DEVICE_FUNC Packet pload (const typename unpacket_traits< Packet >::type *from)
template<typename Packet >
EIGEN_DEVICE_FUNC Packet ploadu (const typename unpacket_traits< Packet >::type *from)
template<typename Packet >
EIGEN_DEVICE_FUNC Packet pset1 (const typename unpacket_traits< Packet >::type &a)
template<typename Packet >
EIGEN_DEVICE_FUNC Packet pload1 (const typename unpacket_traits< Packet >::type *a)
template<typename Packet >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet ploaddup (const typename unpacket_traits< Packet >::type *from)
template<typename Packet >
EIGEN_DEVICE_FUNC Packet ploadquad (const typename unpacket_traits< Packet >::type *from)
template<typename Packet >
EIGEN_DEVICE_FUNC void pbroadcast4 (const typename unpacket_traits< Packet >::type *a, Packet &a0, Packet &a1, Packet &a2, Packet &a3)
template<typename Packet >
EIGEN_DEVICE_FUNC void pbroadcast2 (const typename unpacket_traits< Packet >::type *a, Packet &a0, Packet &a1)
template<typename Packet >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet plset (const typename unpacket_traits< Packet >::type &a)
template<typename Scalar , typename Packet >
EIGEN_DEVICE_FUNC void pstore (Scalar *to, const Packet &from)
template<typename Scalar , typename Packet >
EIGEN_DEVICE_FUNC void pstoreu (Scalar *to, const Packet &from)
template<typename Scalar , typename Packet >
EIGEN_DEVICE_FUNC Packet pgather (const Scalar *from, Index)
template<typename Scalar , typename Packet >
EIGEN_DEVICE_FUNC void pscatter (Scalar *to, const Packet &from, Index)
template<typename Scalar >
EIGEN_DEVICE_FUNC void prefetch (const Scalar *addr)
template<typename Packet >
EIGEN_DEVICE_FUNC unpacket_traits< Packet >::type pfirst (const Packet &a)
template<typename Packet >
EIGEN_DEVICE_FUNC Packet preduxp (const Packet *vecs)
template<typename Packet >
EIGEN_DEVICE_FUNC unpacket_traits< Packet >::type predux (const Packet &a)
template<typename Packet >
EIGEN_DEVICE_FUNC conditional<(unpacket_traits< Packet >::size%8)==0, typename unpacket_traits< Packet >::half, Packet >::type predux_downto4 (const Packet &a)
template<typename Packet >
EIGEN_DEVICE_FUNC unpacket_traits< Packet >::type predux_mul (const Packet &a)
template<typename Packet >
EIGEN_DEVICE_FUNC unpacket_traits< Packet >::type predux_min (const Packet &a)
template<typename Packet >
EIGEN_DEVICE_FUNC unpacket_traits< Packet >::type predux_max (const Packet &a)
template<typename Packet >
EIGEN_DEVICE_FUNC Packet preverse (const Packet &a)
template<typename Packet >
EIGEN_DEVICE_FUNC Packet pcplxflip (const Packet &a)
template<typename Packet >
EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet psin (const Packet &a)
template<typename Packet >
EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet pcos (const Packet &a)
template<typename Packet >
EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet ptan (const Packet &a)
template<typename Packet >
EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet pasin (const Packet &a)
template<typename Packet >
EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet pacos (const Packet &a)
template<typename Packet >
EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet patan (const Packet &a)
template<typename Packet >
EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet psinh (const Packet &a)
template<typename Packet >
EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet pcosh (const Packet &a)
template<typename Packet >
EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet ptanh (const Packet &a)
template<typename Packet >
EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet pexp (const Packet &a)
template<typename Packet >
EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet pexpm1 (const Packet &a)
template<typename Packet >
EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet plog (const Packet &a)
template<typename Packet >
EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet plog1p (const Packet &a)
template<typename Packet >
EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet plog10 (const Packet &a)
template<typename Packet >
EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet psqrt (const Packet &a)
template<typename Packet >
EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet prsqrt (const Packet &a)
template<typename Packet >
EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet pround (const Packet &a)
template<typename Packet >
EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet pfloor (const Packet &a)
template<typename Packet >
EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet pceil (const Packet &a)
template<typename Packet >
void pstore1 (typename unpacket_traits< Packet >::type *to, const typename unpacket_traits< Packet >::type &a)
template<typename Packet >
EIGEN_DEVICE_FUNC Packet pmadd (const Packet &a, const Packet &b, const Packet &c)
template<typename Packet , int Alignment>
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE Packet ploadt (const typename unpacket_traits< Packet >::type *from)
template<typename Scalar , typename Packet , int Alignment>
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE void pstoret (Scalar *to, const Packet &from)
template<typename Packet , int LoadMode>
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE Packet ploadt_ro (const typename unpacket_traits< Packet >::type *from)
template<int Offset, typename PacketType >
void palign (PacketType &first, const PacketType &second)
template<>
std::complex< float > pmul (const std::complex< float > &a, const std::complex< float > &b)
template<>
std::complex< double > pmul (const std::complex< double > &a, const std::complex< double > &b)
template<typename Packet >
EIGEN_DEVICE_FUNC void ptranspose (PacketBlock< Packet, 1 > &)
template<typename Packet >
EIGEN_DEVICE_FUNC Packet pblend (const Selector< unpacket_traits< Packet >::size > &ifPacket, const Packet &thenPacket, const Packet &elsePacket)
template<typename Packet >
EIGEN_DEVICE_FUNC Packet pinsertfirst (const Packet &a, typename unpacket_traits< Packet >::type b)
template<typename Packet >
EIGEN_DEVICE_FUNC Packet pinsertlast (const Packet &a, typename unpacket_traits< Packet >::type b)
template<typename Derived >
std::ostream & print_matrix (std::ostream &s, const Derived &_m, const IOFormat &fmt)
template<typename T >
T generic_fast_tanh_float (const T &a_x)
EIGEN_CATCH_ASSIGN_XPR_OP_PRODUCT (assign_op, scalar_sum_op, add_assign_op)
EIGEN_CATCH_ASSIGN_XPR_OP_PRODUCT (add_assign_op, scalar_sum_op, add_assign_op)
EIGEN_CATCH_ASSIGN_XPR_OP_PRODUCT (sub_assign_op, scalar_sum_op, sub_assign_op)
EIGEN_CATCH_ASSIGN_XPR_OP_PRODUCT (assign_op, scalar_difference_op, sub_assign_op)
EIGEN_CATCH_ASSIGN_XPR_OP_PRODUCT (add_assign_op, scalar_difference_op, sub_assign_op)
EIGEN_CATCH_ASSIGN_XPR_OP_PRODUCT (sub_assign_op, scalar_difference_op, add_assign_op)
template<typename Dst , typename Lhs , typename Rhs , typename Func >
void outer_product_selector_run (Dst &dst, const Lhs &lhs, const Rhs &rhs, const Func &func, const false_type &)
template<typename Dst , typename Lhs , typename Rhs , typename Func >
void outer_product_selector_run (Dst &dst, const Lhs &lhs, const Rhs &rhs, const Func &func, const true_type &)
std::ptrdiff_t manage_caching_sizes_helper (std::ptrdiff_t a, std::ptrdiff_t b)
void manage_caching_sizes (Action action, std::ptrdiff_t *l1, std::ptrdiff_t *l2, std::ptrdiff_t *l3)
template<typename LhsScalar , typename RhsScalar , int KcFactor, typename Index >
void evaluateProductBlockingSizesHeuristic (Index &k, Index &m, Index &n, Index num_threads=1)
template<typename Index >
bool useSpecificBlockingSizes (Index &k, Index &m, Index &n)
template<typename LhsScalar , typename RhsScalar , int KcFactor, typename Index >
void computeProductBlockingSizes (Index &k, Index &m, Index &n, Index num_threads=1)
Computes the blocking parameters for a m x k times k x n matrix product.
template<typename LhsScalar , typename RhsScalar , typename Index >
void computeProductBlockingSizes (Index &k, Index &m, Index &n, Index num_threads=1)
template<typename CJ , typename A , typename B , typename C , typename T >
EIGEN_STRONG_INLINE void gebp_madd (const CJ &cj, A &a, B &b, C &c, T &t)
template<typename Packet >
DoublePacket< Packet > padd (const DoublePacket< Packet > &a, const DoublePacket< Packet > &b)
template<typename Packet >
const DoublePacket< Packet > & predux_downto4 (const DoublePacket< Packet > &a)
void manage_multi_threading (Action action, int *v)
template<bool Condition, typename Functor , typename Index >
void parallelize_gemm (const Functor &func, Index rows, Index cols, Index depth, bool transpose)
template<typename ExpressionType , typename Scalar >
void stable_norm_kernel (const ExpressionType &bl, Scalar &ssq, Scalar &scale, Scalar &invScale)
template<typename Derived >
NumTraits< typename traits< Derived >::Scalar >::Real blueNorm_impl (const EigenBase< Derived > &_vec)
template<int Mode, bool SetOpposite, typename DstXprType , typename SrcXprType , typename Functor >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void call_triangular_assignment_loop (DstXprType &dst, const SrcXprType &src, const Functor &func)
template<int Mode, bool SetOpposite, typename DstXprType , typename SrcXprType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void call_triangular_assignment_loop (DstXprType &dst, const SrcXprType &src)
template<typename T >
const T::Scalar * extract_data (const T &m)
Index eval_expr_given_size (Index x, Index)
template<int N>
FixedInt< N > eval_expr_given_size (FixedInt< N > x, Index)
template<typename Derived >
Index eval_expr_given_size (const Symbolic::BaseExpr< Derived > &x, Index size)
template<typename T >
Index first (const T &x)
template<typename T , typename Q >
const T & makeIndexedViewCompatible (const T &x, Index, Q)
template<typename T >
enable_if< Symbolic::is_symbolic< T >::value, SingleRange >::type makeIndexedViewCompatible (const T &id, Index size, SpecializedType)
template<typename XprSizeType >
AllRange< get_fixed_value< XprSizeType >::value > makeIndexedViewCompatible (all_t, XprSizeType size, SpecializedType)
template<typename T >
EIGEN_DEVICE_FUNC Index get_runtime_value (const T &x)
template<int N>
EIGEN_DEVICE_FUNC Index get_runtime_value (FixedInt< N >(*)())
bool copy_bool (bool b)
template<typename T >
EIGEN_DEVICE_FUNC void ignore_unused_variable (const T &)
EIGEN_DEVICE_FUNC void throw_std_bad_alloc ()
void * handmade_aligned_malloc (std::size_t size)
void handmade_aligned_free (void *ptr)
void * handmade_aligned_realloc (void *ptr, std::size_t size, std::size_t=0)
EIGEN_DEVICE_FUNC void check_that_malloc_is_allowed ()
EIGEN_DEVICE_FUNC void * aligned_malloc (std::size_t size)
EIGEN_DEVICE_FUNC void aligned_free (void *ptr)
void * aligned_realloc (void *ptr, std::size_t new_size, std::size_t old_size)
template<bool Align>
EIGEN_DEVICE_FUNC void * conditional_aligned_malloc (std::size_t size)
template<>
EIGEN_DEVICE_FUNC void * conditional_aligned_malloc< false > (std::size_t size)
template<bool Align>
EIGEN_DEVICE_FUNC void conditional_aligned_free (void *ptr)
template<>
EIGEN_DEVICE_FUNC void conditional_aligned_free< false > (void *ptr)
template<bool Align>
void * conditional_aligned_realloc (void *ptr, std::size_t new_size, std::size_t old_size)
template<>
void * conditional_aligned_realloc< false > (void *ptr, std::size_t new_size, std::size_t)
template<typename T >
EIGEN_DEVICE_FUNC void destruct_elements_of_array (T *ptr, std::size_t size)
template<typename T >
EIGEN_DEVICE_FUNC T * construct_elements_of_array (T *ptr, std::size_t size)
template<typename T >
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE void check_size_for_overflow (std::size_t size)
template<typename T >
EIGEN_DEVICE_FUNC T * aligned_new (std::size_t size)
template<typename T , bool Align>
EIGEN_DEVICE_FUNC T * conditional_aligned_new (std::size_t size)
template<typename T >
EIGEN_DEVICE_FUNC void aligned_delete (T *ptr, std::size_t size)
template<typename T , bool Align>
EIGEN_DEVICE_FUNC void conditional_aligned_delete (T *ptr, std::size_t size)
template<typename T , bool Align>
EIGEN_DEVICE_FUNC T * conditional_aligned_realloc_new (T *pts, std::size_t new_size, std::size_t old_size)
template<typename T , bool Align>
EIGEN_DEVICE_FUNC T * conditional_aligned_new_auto (std::size_t size)
template<typename T , bool Align>
T * conditional_aligned_realloc_new_auto (T *pts, std::size_t new_size, std::size_t old_size)
template<typename T , bool Align>
EIGEN_DEVICE_FUNC void conditional_aligned_delete_auto (T *ptr, std::size_t size)
template<int Alignment, typename Scalar , typename Index >
EIGEN_DEVICE_FUNC Index first_aligned (const Scalar *array, Index size)
template<typename Scalar , typename Index >
EIGEN_DEVICE_FUNC Index first_default_aligned (const Scalar *array, Index size)
template<typename Index >
Index first_multiple (Index size, Index base)
template<typename T >
EIGEN_DEVICE_FUNC void smart_copy (const T *start, const T *end, T *target)
template<typename T >
void smart_memmove (const T *start, const T *end, T *target)
template<typename T >
void swap (scoped_array< T > &a, scoped_array< T > &b)
void queryCacheSizes (int &l1, int &l2, int &l3)
int queryL1CacheSize ()
int queryTopLevelCacheSize ()
template<typename T >
Index size (const T &x)
template<typename T , std::size_t N>
Index size (const T(&)[N])
template<typename T >
const T * return_ptr ()
template<typename IndexDest , typename IndexSrc >
EIGEN_DEVICE_FUNC IndexDest convert_index (const IndexSrc &idx)
template<typename T >
EIGEN_DEVICE_FUNC T * const_cast_ptr (const T *ptr)
template<typename T1 , typename T2 >
bool is_same_dense (const T1 &mat1, const T2 &mat2, typename enable_if< has_direct_access< T1 >::ret &&has_direct_access< T2 >::ret, T1 >::type *=0)
template<typename T1 , typename T2 >
bool is_same_dense (const T1 &, const T2 &, typename enable_if<!(has_direct_access< T1 >::ret &&has_direct_access< T2 >::ret), T1 >::type *=0)
EIGEN_MEMBER_FUNCTOR (squaredNorm, Size *NumTraits< Scalar >::MulCost+(Size-1)*NumTraits< Scalar >::AddCost)
EIGEN_MEMBER_FUNCTOR (norm,(Size+5)*NumTraits< Scalar >::MulCost+(Size-1)*NumTraits< Scalar >::AddCost)
EIGEN_MEMBER_FUNCTOR (stableNorm,(Size+5)*NumTraits< Scalar >::MulCost+(Size-1)*NumTraits< Scalar >::AddCost)
EIGEN_MEMBER_FUNCTOR (blueNorm,(Size+5)*NumTraits< Scalar >::MulCost+(Size-1)*NumTraits< Scalar >::AddCost)
EIGEN_MEMBER_FUNCTOR (hypotNorm,(Size-1)*functor_traits< scalar_hypot_op< Scalar > >::Cost)
EIGEN_MEMBER_FUNCTOR (sum,(Size-1)*NumTraits< Scalar >::AddCost)
EIGEN_MEMBER_FUNCTOR (mean,(Size-1)*NumTraits< Scalar >::AddCost+NumTraits< Scalar >::MulCost)
EIGEN_MEMBER_FUNCTOR (minCoeff,(Size-1)*NumTraits< Scalar >::AddCost)
EIGEN_MEMBER_FUNCTOR (maxCoeff,(Size-1)*NumTraits< Scalar >::AddCost)
EIGEN_MEMBER_FUNCTOR (all,(Size-1)*NumTraits< Scalar >::AddCost)
EIGEN_MEMBER_FUNCTOR (any,(Size-1)*NumTraits< Scalar >::AddCost)
EIGEN_MEMBER_FUNCTOR (count,(Size-1)*NumTraits< Scalar >::AddCost)
EIGEN_MEMBER_FUNCTOR (prod,(Size-1)*NumTraits< Scalar >::MulCost)
template<typename MatrixType , typename DiagType , typename SubDiagType >
ComputationInfo computeFromTridiagonal_impl (DiagType &diag, SubDiagType &subdiag, const Index maxIterations, bool computeEigenvectors, MatrixType &eivec)
template<int StorageOrder, typename RealScalar , typename Scalar , typename Index >
static EIGEN_DEVICE_FUNC void tridiagonal_qr_step (RealScalar *diag, RealScalar *subdiag, Index start, Index end, Scalar *matrixQ, Index n)
template<typename MatrixType , typename CoeffVectorType >
void tridiagonalization_inplace (MatrixType &matA, CoeffVectorType &hCoeffs)
template<typename MatrixType , typename DiagonalType , typename SubDiagonalType >
void tridiagonalization_inplace (MatrixType &mat, DiagonalType &diag, SubDiagonalType &subdiag, bool extractQ)
Performs a full tridiagonalization in place.
template<typename Scalar , int Dim>
static EIGEN_DEVICE_FUNC Matrix< Scalar, 2, 2 > toRotationMatrix (const Scalar &s)
template<typename Scalar , int Dim, typename OtherDerived >
static EIGEN_DEVICE_FUNC Matrix< Scalar, Dim, Dim > toRotationMatrix (const RotationBase< OtherDerived, Dim > &r)
template<typename Scalar , int Dim, typename OtherDerived >
static EIGEN_DEVICE_FUNC const MatrixBase< OtherDerived > & toRotationMatrix (const MatrixBase< OtherDerived > &mat)
template<typename TriangularFactorType , typename VectorsType , typename CoeffsType >
void make_block_householder_triangular_factor (TriangularFactorType &triFactor, const VectorsType &vectors, const CoeffsType &hCoeffs)
template<typename MatrixType , typename VectorsType , typename CoeffsType >
void apply_block_householder_on_the_left (MatrixType &mat, const VectorsType &vectors, const CoeffsType &hCoeffs, bool forward)
template<typename MatrixType , typename Rhs , typename Dest , typename Preconditioner >
bool bicgstab (const MatrixType &mat, const Rhs &rhs, Dest &x, const Preconditioner &precond, Index &iters, typename Dest::RealScalar &tol_error)
template<typename MatrixType , typename Rhs , typename Dest , typename Preconditioner >
EIGEN_DONT_INLINE void conjugate_gradient (const MatrixType &mat, const Rhs &rhs, Dest &x, const Preconditioner &precond, Index &iters, typename Dest::RealScalar &tol_error)
template<typename VectorV , typename VectorI >
Index QuickSplit (VectorV &row, VectorI &ind, Index ncut)
template<typename MatrixType , typename Rhs , typename Dest , typename Preconditioner >
EIGEN_DONT_INLINE void least_square_conjugate_gradient (const MatrixType &mat, const Rhs &rhs, Dest &x, const Preconditioner &precond, Index &iters, typename Dest::RealScalar &tol_error)
template<typename VectorX , typename VectorY , typename OtherScalar >
EIGEN_DEVICE_FUNC void apply_rotation_in_the_plane (DenseBase< VectorX > &xpr_x, DenseBase< VectorY > &xpr_y, const JacobiRotation< OtherScalar > &j)
template<typename VectorX , typename VectorY , typename OtherScalar >
void apply_rotation_in_the_plane (DenseBase< VectorX > &xpr_x, DenseBase< VectorY > &xpr_y, const JacobiRotation< OtherScalar > &j)
template<typename Derived >
const Derived::Scalar bruteforce_det3_helper (const MatrixBase< Derived > &matrix, int a, int b, int c)
template<typename Derived >
const Derived::Scalar bruteforce_det4_helper (const MatrixBase< Derived > &matrix, int j, int k, int m, int n)
template<typename MatrixType , typename ResultType >
EIGEN_DEVICE_FUNC void compute_inverse_size2_helper (const MatrixType &matrix, const typename ResultType::Scalar &invdet, ResultType &result)
template<typename MatrixType , int i, int j>
EIGEN_DEVICE_FUNC MatrixType::Scalar cofactor_3x3 (const MatrixType &m)
template<typename MatrixType , typename ResultType >
EIGEN_DEVICE_FUNC void compute_inverse_size3_helper (const MatrixType &matrix, const typename ResultType::Scalar &invdet, const Matrix< typename ResultType::Scalar, 3, 1 > &cofactors_col0, ResultType &result)
template<typename Derived >
EIGEN_DEVICE_FUNC const Derived::Scalar general_det3_helper (const MatrixBase< Derived > &matrix, int i1, int i2, int i3, int j1, int j2, int j3)
template<typename MatrixType , int i, int j>
EIGEN_DEVICE_FUNC MatrixType::Scalar cofactor_4x4 (const MatrixType &matrix)
template<typename MatrixType , typename TranspositionType >
void partial_lu_inplace (MatrixType &lu, TranspositionType &row_transpositions, typename TranspositionType::StorageIndex &nb_transpositions)
template<typename MatrixType , typename RealScalar , typename Index >
void real_2x2_jacobi_svd (const MatrixType &matrix, Index p, Index q, JacobiRotation< RealScalar > *j_left, JacobiRotation< RealScalar > *j_right)
template<typename T >
T amd_flip (const T &i)
template<typename T >
T amd_unflip (const T &i)
template<typename T0 , typename T1 >
bool amd_marked (const T0 *w, const T1 &j)
template<typename T0 , typename T1 >
void amd_mark (const T0 *w, const T1 &j)
template<typename StorageIndex >
static StorageIndex cs_wclear (StorageIndex mark, StorageIndex lemax, StorageIndex *w, StorageIndex n)
template<typename StorageIndex >
StorageIndex cs_tdfs (StorageIndex j, StorageIndex k, StorageIndex *head, const StorageIndex *next, StorageIndex *post, StorageIndex *stack)
template<typename Scalar , typename StorageIndex >
void minimum_degree_ordering (SparseMatrix< Scalar, ColMajor, StorageIndex > &C, PermutationMatrix< Dynamic, Dynamic, StorageIndex > &perm)
template<typename IndexType >
IndexType colamd_c (IndexType n_col)
template<typename IndexType >
IndexType colamd_r (IndexType n_row)
template<typename IndexType >
static IndexType init_rows_cols (IndexType n_row, IndexType n_col, Colamd_Row< IndexType > Row[], colamd_col< IndexType > col[], IndexType A[], IndexType p[], IndexType stats[COLAMD_STATS])
template<typename IndexType >
static void init_scoring (IndexType n_row, IndexType n_col, Colamd_Row< IndexType > Row[], colamd_col< IndexType > Col[], IndexType A[], IndexType head[], double knobs[COLAMD_KNOBS], IndexType *p_n_row2, IndexType *p_n_col2, IndexType *p_max_deg)
template<typename IndexType >
static IndexType find_ordering (IndexType n_row, IndexType n_col, IndexType Alen, Colamd_Row< IndexType > Row[], colamd_col< IndexType > Col[], IndexType A[], IndexType head[], IndexType n_col2, IndexType max_deg, IndexType pfree)
template<typename IndexType >
static void order_children (IndexType n_col, colamd_col< IndexType > Col[], IndexType p[])
template<typename IndexType >
static void detect_super_cols (colamd_col< IndexType > Col[], IndexType A[], IndexType head[], IndexType row_start, IndexType row_length)
template<typename IndexType >
static IndexType garbage_collection (IndexType n_row, IndexType n_col, Colamd_Row< IndexType > Row[], colamd_col< IndexType > Col[], IndexType A[], IndexType *pfree)
template<typename IndexType >
static IndexType clear_mark (IndexType n_row, Colamd_Row< IndexType > Row[])
template<typename IndexType >
IndexType colamd_recommended (IndexType nnz, IndexType n_row, IndexType n_col)
Returns the recommended value of Alen.
static void colamd_set_defaults (double knobs[COLAMD_KNOBS])
set default parameters The use of this routine is optional.
template<typename IndexType >
static bool colamd (IndexType n_row, IndexType n_col, IndexType Alen, IndexType *A, IndexType *p, double knobs[COLAMD_KNOBS], IndexType stats[COLAMD_STATS])
Computes a column ordering using the column approximate minimum degree ordering.
template<typename MatrixType >
void ordering_helper_at_plus_a (const MatrixType &A, MatrixType &symmat)
void eigen_pastix (pastix_data_t **pastix_data, int pastix_comm, int n, int *ptr, int *idx, float *vals, int *perm, int *invp, float *x, int nbrhs, int *iparm, double *dparm)
void eigen_pastix (pastix_data_t **pastix_data, int pastix_comm, int n, int *ptr, int *idx, double *vals, int *perm, int *invp, double *x, int nbrhs, int *iparm, double *dparm)
void eigen_pastix (pastix_data_t **pastix_data, int pastix_comm, int n, int *ptr, int *idx, std::complex< float > *vals, int *perm, int *invp, std::complex< float > *x, int nbrhs, int *iparm, double *dparm)
void eigen_pastix (pastix_data_t **pastix_data, int pastix_comm, int n, int *ptr, int *idx, std::complex< double > *vals, int *perm, int *invp, std::complex< double > *x, int nbrhs, int *iparm, double *dparm)
template<typename MatrixType >
void c_to_fortran_numbering (MatrixType &mat)
template<typename MatrixType >
void fortran_to_c_numbering (MatrixType &mat)
template<typename MatrixQR , typename HCoeffs >
void householder_qr_inplace_unblocked (MatrixQR &mat, HCoeffs &hCoeffs, typename MatrixQR::Scalar *tempData=0)
template<typename Lhs , typename Rhs , typename ResultType >
static void conservative_sparse_sparse_product_impl (const Lhs &lhs, const Rhs &rhs, ResultType &res, bool sortedInsertion=false)
template<typename Lhs , typename Rhs , typename ResultType >
static void sparse_sparse_to_dense_product_impl (const Lhs &lhs, const Rhs &rhs, ResultType &res)
template<typename DstXprType , typename SrcXprType >
void assign_sparse_to_sparse (DstXprType &dst, const SrcXprType &src)
template<typename Index , typename IndexVector >
Index etree_find (Index i, IndexVector &pp)
template<typename MatrixType , typename IndexVector >
int coletree (const MatrixType &mat, IndexVector &parent, IndexVector &firstRowElt, typename MatrixType::StorageIndex *perm=0)
template<typename IndexVector >
void nr_etdfs (typename IndexVector::Scalar n, IndexVector &parent, IndexVector &first_kid, IndexVector &next_kid, IndexVector &post, typename IndexVector::Scalar postnum)
template<typename IndexVector >
void treePostorder (typename IndexVector::Scalar n, IndexVector &parent, IndexVector &post)
Post order a tree.
template<typename SparseLhsType , typename DenseRhsType , typename DenseResType , typename AlphaType >
void sparse_time_dense_product (const SparseLhsType &lhs, const DenseRhsType &rhs, DenseResType &res, const AlphaType &alpha)
template<typename InputIterator , typename SparseMatrixType , typename DupFunctor >
void set_from_triplets (const InputIterator &begin, const InputIterator &end, SparseMatrixType &mat, DupFunctor dup_func)
template<int SrcMode, int DstMode, typename MatrixType , int DestOrder>
void permute_symm_to_symm (const MatrixType &mat, SparseMatrix< typename MatrixType::Scalar, DestOrder, typename MatrixType::StorageIndex > &_dest, const typename MatrixType::StorageIndex *perm=0)
template<int Mode, typename MatrixType , int DestOrder>
void permute_symm_to_fullsymm (const MatrixType &mat, SparseMatrix< typename MatrixType::Scalar, DestOrder, typename MatrixType::StorageIndex > &_dest, const typename MatrixType::StorageIndex *perm=0)
template<int Mode, typename SparseLhsType , typename DenseRhsType , typename DenseResType , typename AlphaType >
void sparse_selfadjoint_time_dense_product (const SparseLhsType &lhs, const DenseRhsType &rhs, DenseResType &res, const AlphaType &alpha)
template<int _SrcMode, int _DstMode, typename MatrixType , int DstOrder>
void permute_symm_to_symm (const MatrixType &mat, SparseMatrix< typename MatrixType::Scalar, DstOrder, typename MatrixType::StorageIndex > &_dest, const typename MatrixType::StorageIndex *perm)
template<typename Decomposition , typename Rhs , typename Dest >
enable_if< Rhs::ColsAtCompileTime!=1 &&Dest::ColsAtCompileTime!=1 >::type solve_sparse_through_dense_panels (const Decomposition &dec, const Rhs &rhs, Dest &dest)
template<typename Decomposition , typename Rhs , typename Dest >
enable_if< Rhs::ColsAtCompileTime==1||Dest::ColsAtCompileTime==1 >::type solve_sparse_through_dense_panels (const Decomposition &dec, const Rhs &rhs, Dest &dest)
template<typename Lhs , typename Rhs , typename ResultType >
static void sparse_sparse_product_with_pruning_impl (const Lhs &lhs, const Rhs &rhs, ResultType &res, const typename ResultType::RealScalar &tolerance)
template<typename Scalar >
EIGEN_DONT_INLINE void sparselu_gemm (Index m, Index n, Index d, const Scalar *A, Index lda, const Scalar *B, Index ldb, Scalar *C, Index ldc)
Index LUnumTempV (Index &m, Index &w, Index &t, Index &b)
template<typename Scalar >
Index LUTempSpace (Index &m, Index &w)
template<typename MatrixType >
SluMatrix asSluMatrix (MatrixType &mat)
template<typename Scalar , int Flags, typename Index >
MappedSparseMatrix< Scalar, Flags, Index > map_superlu (SluMatrix &sluMat)
template<typename MatrixType >
void upperbidiagonalization_inplace_unblocked (MatrixType &mat, typename MatrixType::RealScalar *diagonal, typename MatrixType::RealScalar *upper_diagonal, typename MatrixType::Scalar *tempData=0)
template<typename MatrixType >
void upperbidiagonalization_blocked_helper (MatrixType &A, typename MatrixType::RealScalar *diagonal, typename MatrixType::RealScalar *upper_diagonal, Index bs, Ref< Matrix< typename MatrixType::Scalar, Dynamic, Dynamic, traits< MatrixType >::Flags &RowMajorBit > > X, Ref< Matrix< typename MatrixType::Scalar, Dynamic, Dynamic, traits< MatrixType >::Flags &RowMajorBit > > Y)
template<typename MatrixType , typename BidiagType >
void upperbidiagonalization_inplace_blocked (MatrixType &A, BidiagType &bidiagonal, Index maxBlockSize=32, typename MatrixType::Scalar *=0)
Variables
static Packet4ui p4ui_CONJ_XOR = vec_mergeh((Packet4ui)p4i_ZERO, (Packet4ui)p4f_MZERO)
static Packet4f p4f_MZERO = (Packet4f) vec_sl((Packet4ui)p4i_MINUS1, (Packet4ui)p4i_MINUS1)
static Packet4f p4f_ONE = vec_ctf(p4i_ONE, 0)
static Packet4f p4f_COUNTDOWN = { 0.0, 1.0, 2.0, 3.0 }
static Packet4i p4i_COUNTDOWN = { 0, 1, 2, 3 }
static Packet16uc p16uc_REVERSE32 = { 12,13,14,15, 8,9,10,11, 4,5,6,7, 0,1,2,3 }
static Packet16uc p16uc_DUPLICATE32_HI = { 0,1,2,3, 0,1,2,3, 4,5,6,7, 4,5,6,7 }
static Packet16uc p16uc_FORWARD = p16uc_REVERSE32
static Packet16uc p16uc_REVERSE64 = { 8,9,10,11, 12,13,14,15, 0,1,2,3, 4,5,6,7 }
static Packet16uc p16uc_PSET32_WODD = vec_sld((Packet16uc) vec_splat((Packet4ui)p16uc_FORWARD, 1), (Packet16uc) vec_splat((Packet4ui)p16uc_FORWARD, 3), 8)
static Packet16uc p16uc_PSET32_WEVEN = vec_sld((Packet16uc) vec_splat((Packet4ui)p16uc_FORWARD, 0), (Packet16uc) vec_splat((Packet4ui)p16uc_FORWARD, 2), 8)
static Packet16uc p16uc_HALF64_0_16 = vec_sld(vec_splat((Packet16uc) vec_abs(p4i_MINUS16), 0), (Packet16uc)p4i_ZERO, 8)
static Packet16uc p16uc_PSET64_HI = (Packet16uc) vec_mergeh((Packet4ui)p16uc_PSET32_WODD, (Packet4ui)p16uc_PSET32_WEVEN)
static Packet16uc p16uc_PSET64_LO = (Packet16uc) vec_mergel((Packet4ui)p16uc_PSET32_WODD, (Packet4ui)p16uc_PSET32_WEVEN)
static Packet16uc p16uc_TRANSPOSE64_HI = p16uc_PSET64_HI + p16uc_HALF64_0_16
static Packet16uc p16uc_TRANSPOSE64_LO = p16uc_PSET64_LO + p16uc_HALF64_0_16
static Packet16uc p16uc_COMPLEX32_REV = vec_sld(p16uc_REVERSE32, p16uc_REVERSE32, 8)
static Packet16uc p16uc_COMPLEX32_REV2 = vec_sld(p16uc_PSET64_HI, p16uc_PSET64_LO, 8)
static Packet2ul p2ul_CONJ_XOR1 = (Packet2ul) vec_sld((Packet4ui) p2d_ZERO_, (Packet4ui) p2l_ZERO, 8)
static Packet2ul p2ul_CONJ_XOR2 = (Packet2ul) vec_sld((Packet4ui) p2l_ZERO, (Packet4ui) p2d_ZERO_, 8)
static Packet2d p2d_ONE = { 1.0, 1.0 }
static Packet2d p2d_ZERO_ = { -0.0, -0.0 }
static Packet4i p4i_COUNTDOWN = { 0, 1, 2, 3 }
static Packet4f p4f_COUNTDOWN = { 0.0, 1.0, 2.0, 3.0 }
static Packet2d p2d_COUNTDOWN = reinterpret_cast<Packet2d>(vec_sld(reinterpret_cast<Packet16uc>(p2d_ZERO), reinterpret_cast<Packet16uc>(p2d_ONE), 8))
static Packet16uc p16uc_PSET64_HI = { 0,1,2,3, 4,5,6,7, 0,1,2,3, 4,5,6,7 }
static Packet16uc p16uc_DUPLICATE32_HI = { 0,1,2,3, 0,1,2,3, 4,5,6,7, 4,5,6,7 }
static Packet16uc p16uc_FORWARD = { 0,1,2,3, 4,5,6,7, 8,9,10,11, 12,13,14,15 }
static Packet16uc p16uc_REVERSE32 = { 12,13,14,15, 8,9,10,11, 4,5,6,7, 0,1,2,3 }
static Packet16uc p16uc_REVERSE64 = { 8,9,10,11, 12,13,14,15, 0,1,2,3, 4,5,6,7 }
static Packet16uc p16uc_PSET32_WODD = vec_sld((Packet16uc) vec_splat((Packet4ui)p16uc_FORWARD, 0), (Packet16uc) vec_splat((Packet4ui)p16uc_FORWARD, 2), 8)
static Packet16uc p16uc_PSET32_WEVEN = vec_sld(p16uc_DUPLICATE32_HI, (Packet16uc) vec_splat((Packet4ui)p16uc_FORWARD, 3), 8)
static Packet16uc p16uc_PSET64_LO = (Packet16uc) vec_mergel((Packet4ui)p16uc_PSET32_WODD, (Packet4ui)p16uc_PSET32_WEVEN)
static Packet16uc p16uc_TRANSPOSE64_HI = { 0,1,2,3, 4,5,6,7, 16,17,18,19, 20,21,22,23}
static Packet16uc p16uc_TRANSPOSE64_LO = { 8,9,10,11, 12,13,14,15, 24,25,26,27, 28,29,30,31}
const std::ptrdiff_t defaultL1CacheSize = 16*1024
const std::ptrdiff_t defaultL2CacheSize = 512*1024
const std::ptrdiff_t defaultL3CacheSize = 512*1024
Typedef Documentation
typedef std::ptrdiff_t Eigen::internal::IntPtr
typedef __m512 Eigen::internal::Packet16f
typedef __m512i Eigen::internal::Packet16i
typedef __vector unsigned char Eigen::internal::Packet16uc
typedef __vector double Eigen::internal::Packet2d
typedef float32x2_t Eigen::internal::Packet2f
typedef int32x2_t Eigen::internal::Packet2i
typedef __vector long long Eigen::internal::Packet2l
typedef __vector unsigned long long Eigen::internal::Packet2ul
typedef __vector __bool int Eigen::internal::Packet4bi
typedef __m256d Eigen::internal::Packet4d
typedef __m128 Eigen::internal::Packet4f
typedef __vector int Eigen::internal::Packet4i
typedef __vector unsigned int Eigen::internal::Packet4ui
typedef __m512d Eigen::internal::Packet8d
typedef __m256 Eigen::internal::Packet8f
typedef __vector short int Eigen::internal::Packet8i
typedef std::size_t Eigen::internal::UIntPtr
Enumeration Type Documentation
anonymous enum
Enumerator
SDP_AsScalarProduct
SDP_AsCwiseProduct
anonymous enum
Enumerator
SVA_RuntimeSwitch
SVA_Inner
SVA_Outer
anonymous enum
Enumerator
LUNoMarker
anonymous enum
Enumerator
emptyIdxLU
anonymous enum
Enumerator
PreconditionIfMoreColsThanRows
PreconditionIfMoreRowsThanCols
enum Eigen::internal::ComparisonName
Enumerator
cmp_EQ
cmp_LT
cmp_LE
cmp_UNORD
cmp_NEQ
cmp_GT
cmp_GE
enum Eigen::internal::MemType
Enumerator
LUSUP
UCOL
LSUB
USUB
LLVL
ULVL
enum Eigen::internal::PermPermProduct_t
Enumerator
PermPermProduct
enum Eigen::internal::SignMatrix
Enumerator
PositiveSemiDef
NegativeSemiDef
ZeroSign
Indefinite
Function Documentation
static Eigen::internal::_EIGEN_DECLARE_CONST_FAST_Packet2d (ZERO , 0) static
static Eigen::internal::_EIGEN_DECLARE_CONST_FAST_Packet2l (ZERO , 0) static
static Eigen::internal::_EIGEN_DECLARE_CONST_FAST_Packet2l (ONE , 1) static
static Eigen::internal::_EIGEN_DECLARE_CONST_FAST_Packet4f (ZERO , 0) static
static Eigen::internal::_EIGEN_DECLARE_CONST_FAST_Packet4i (ZERO , 0) static
static Eigen::internal::_EIGEN_DECLARE_CONST_FAST_Packet4i (ONE , 1) static
static Eigen::internal::_EIGEN_DECLARE_CONST_FAST_Packet4i (MINUS16 , - 16) static
static Eigen::internal::_EIGEN_DECLARE_CONST_FAST_Packet4i (MINUS1 , - 1) static
static Eigen::internal::_EIGEN_DECLARE_CONST_FAST_Packet4i (ONE , 1) static
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet2d (1 , 1. 0) static
Referenced by pexp< Packet2d >().
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet2d (2 , 2. 0) static
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet2d (half , 0. 5) static
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet2d (exp_hi , 709. 437) static
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet2d (exp_lo , -709. 436139303) static
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet2d (cephes_LOG2EF , 1. 4426950408889634073599) static
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet2d (cephes_exp_p0 , 1.26177193074810590878e- 4) static
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet2d (cephes_exp_p1 , 3.02994407707441961300e- 2) static
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet2d (cephes_exp_p2 , 9.99999999999999999910e- 1) static
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet2d (cephes_exp_q0 , 3.00198505138664455042e- 6) static
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet2d (cephes_exp_q1 , 2.52448340349684104192e- 3) static
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet2d (cephes_exp_q2 , 2.27265548208155028766e- 1) static
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet2d (cephes_exp_q3 , 2. 00000000000000000009e0) static
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet2d (cephes_exp_C1 , 0. 693145751953125) static
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet2d (cephes_exp_C2 , 1.42860682030941723212e- 6) static
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet4f (1 , 1. 0f) static
Referenced by pcos< Packet4f >(), psin< Packet4f >(), and psqrt< Packet2d >().
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet4f (half , 0. 5f) static
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet4f (cephes_SQRTHF , 0. 707106781186547524f) static
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet4f (cephes_log_p0 , 7.0376836292E- 2f) static
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet4f (cephes_log_p1 , -1.1514610310E- 1f) static
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet4f (cephes_log_p2 , 1.1676998740E- 1f) static
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet4f (cephes_log_p3 , -1.2420140846E- 1f) static
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet4f (cephes_log_p4 , +1.4249322787E- 1f) static
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet4f (cephes_log_p5 , -1.6668057665E- 1f) static
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet4f (cephes_log_p6 , +2.0000714765E- 1f) static
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet4f (cephes_log_p7 , -2.4999993993E- 1f) static
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet4f (cephes_log_p8 , +3.3333331174E- 1f) static
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet4f (cephes_log_q1 , -2.12194440e- 4f) static
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet4f (cephes_log_q2 , 0. 693359375f) static
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet4f (exp_hi , 88. 3762626647950f) static
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet4f (exp_lo , -88. 3762626647949f) static
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet4f (cephes_LOG2EF , 1. 44269504088896341f) static
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet4f (cephes_exp_C1 , 0. 693359375f) static
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet4f (cephes_exp_C2 , -2.12194440e- 4f) static
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet4f (cephes_exp_p0 , 1.9875691500E- 4f) static
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet4f (cephes_exp_p1 , 1.3981999507E- 3f) static
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet4f (cephes_exp_p2 , 8.3334519073E- 3f) static
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet4f (cephes_exp_p3 , 4.1665795894E- 2f) static
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet4f (cephes_exp_p4 , 1.6666665459E- 1f) static
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet4f (cephes_exp_p5 , 5.0000001201E- 1f) static
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet4f_FROM_INT (inv_mant_mask , ~ 0x7f800000) static
Referenced by psin< Packet4f >(), and psqrt< Packet2d >().
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet4f_FROM_INT (min_norm_pos , 0x00800000) static
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet4f_FROM_INT (minus_inf , 0xff800000) static
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet4f_FROM_INT (minus_nan , 0xffffffff) static
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet4i (0x7f , 0x7f) static
Referenced by pcos< Packet4f >(), pexp< Packet4d >(), prsqrt< Packet4f >(), and psin< Packet4f >().
static Eigen::internal::_EIGEN_DECLARE_CONST_Packet4i (23 , 23) static
template<typename T > EIGEN_DEVICE_FUNC void Eigen::internal::aligned_delete (T * ptr, std::size_t size) inline
References aligned_free(), and size().
Referenced by Eigen::internal::gemm_blocking_space< StorageOrder, _LhsScalar, _RhsScalar, MaxRows, MaxCols, MaxDepth, KcFactor, false >::~gemm_blocking_space().
EIGEN_DEVICE_FUNC void Eigen::internal::aligned_free (void * ptr) inline
References handmade_aligned_free().
Referenced by aligned_delete(), aligned_new(), conditional_aligned_free(), Eigen::aligned_allocator< T >::deallocate(), and Eigen::internal::aligned_stack_memory_handler< T >::~aligned_stack_memory_handler().
EIGEN_DEVICE_FUNC void* Eigen::internal::aligned_malloc (std::size_t size) inline
References check_that_malloc_is_allowed(), eigen_assert, handmade_aligned_malloc(), and throw_std_bad_alloc().
Referenced by aligned_new(), Eigen::aligned_allocator< T >::allocate(), and conditional_aligned_malloc().
template<typename T > EIGEN_DEVICE_FUNC T* Eigen::internal::aligned_new (std::size_t size) inline
References aligned_free(), aligned_malloc(), construct_elements_of_array(), EIGEN_CATCH, EIGEN_THROW, EIGEN_TRY, and size().
void* Eigen::internal::aligned_realloc (void * ptr, std::size_t new_size, std::size_t old_size) inline
References EIGEN_UNUSED_VARIABLE, handmade_aligned_realloc(), and throw_std_bad_alloc().
Referenced by conditional_aligned_realloc().
template<typename T > T Eigen::internal::amd_flip (const T & i) inline
Referenced by amd_mark(), amd_unflip(), and minimum_degree_ordering().
template<typename T0 , typename T1 > void Eigen::internal::amd_mark (const T0 * w, const T1 & j) inline
References amd_flip().
template<typename T0 , typename T1 > bool Eigen::internal::amd_marked (const T0 * w, const T1 & j) inline
template<typename T > T Eigen::internal::amd_unflip (const T & i) inline
References amd_flip(), and i.
template<typename MatrixType , typename VectorsType , typename CoeffsType > void Eigen::internal::apply_block_householder_on_the_left (MatrixType & mat, const VectorsType & vectors, const CoeffsType & hCoeffs, bool forward)
References Eigen::ColMajor, make_block_householder_triangular_factor(), and Eigen::RowMajor.
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheLeft(), and Eigen::internal::householder_qr_inplace_blocked< MatrixQR, HCoeffs, MatrixQRScalar, InnerStrideIsOne >::run().
template<typename VectorX , typename VectorY , typename OtherScalar > EIGEN_DEVICE_FUNC void Eigen::internal::apply_rotation_in_the_plane (DenseBase< VectorX > & xpr_x, DenseBase< VectorY > & xpr_y, const JacobiRotation< OtherScalar > & j)
Applies the clock wise 2D rotation j to the set of 2D vectors of cordinates x and y:
See also
MatrixBase::applyOnTheLeft(), MatrixBase::applyOnTheRight()
References Eigen::JacobiRotation< Scalar >::c(), eigen_assert, EIGEN_PLAIN_ENUM_MIN, EIGEN_RESTRICT, Eigen::PacketAccessBit, Eigen::JacobiRotation< Scalar >::s(), and size().
Referenced by Eigen::MatrixBase< Derived >::applyOnTheLeft(), Eigen::MatrixBase< Derived >::applyOnTheRight(), llt_rank_update_lower(), and Eigen::JacobiRotation< Scalar >::makeGivens().
template<typename VectorX , typename VectorY , typename OtherScalar > void Eigen::internal::apply_rotation_in_the_plane (DenseBase< VectorX > & xpr_x, DenseBase< VectorY > & xpr_y, const JacobiRotation< OtherScalar > & j)
Applies the clock wise 2D rotation j to the set of 2D vectors of cordinates x and y:
See also
MatrixBase::applyOnTheLeft(), MatrixBase::applyOnTheRight()
References Eigen::JacobiRotation< Scalar >::c(), eigen_assert, EIGEN_PLAIN_ENUM_MIN, EIGEN_RESTRICT, Eigen::PacketAccessBit, Eigen::JacobiRotation< Scalar >::s(), and size().
Referenced by Eigen::MatrixBase< Derived >::applyOnTheLeft(), Eigen::MatrixBase< Derived >::applyOnTheRight(), llt_rank_update_lower(), and Eigen::JacobiRotation< Scalar >::makeGivens().
template<typename DstXprType , typename SrcXprType > void Eigen::internal::assign_sparse_to_sparse (DstXprType & dst, const SrcXprType & src)
References eigen_assert, it, Eigen::half_impl::max(), Eigen::half_impl::min(), Eigen::OuterRandomAccessPattern, and Eigen::RowMajorBit.
Referenced by Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, Sparse2Sparse >::run().
template<typename MatrixType > SluMatrix Eigen::internal::asSluMatrix (MatrixType & mat)
References Eigen::SluMatrix::Map().
Referenced by Eigen::SuperLUBase< _MatrixType, SuperLU< _MatrixType > >::initFactorization().
template<typename MatrixType , typename Rhs , typename Dest , typename Preconditioner > bool Eigen::internal::bicgstab (const MatrixType & mat, const Rhs & rhs, Dest & x, const Preconditioner & precond, Index & iters, typename Dest::RealScalar & tol_error)
References abs(), Eigen::PlainObjectBase< Derived >::cols(), i, and sqrt().
Referenced by Eigen::BiCGSTAB< _MatrixType, _Preconditioner >::_solve_with_guess_impl().
template<typename Derived > NumTraits<typename traits<Derived>::Scalar>::Real Eigen::internal::blueNorm_impl (const EigenBase< Derived > & _vec) inline
References abs(), abs2(), Eigen::EigenBase< Derived >::derived(), it, Eigen::half_impl::max(), Eigen::half_impl::pow(), and sqrt().
Referenced by Eigen::MatrixBase< Derived >::blueNorm(), and Eigen::SparseMatrixBase< Derived >::blueNorm().
template<typename Derived > const Derived::Scalar Eigen::internal::bruteforce_det3_helper (const MatrixBase< Derived > & matrix, int a, int b, int c) inline
References bruteforce_det4_helper().
Referenced by Eigen::internal::determinant_impl< Derived, 3 >::run().
template<typename Derived > const Derived::Scalar Eigen::internal::bruteforce_det4_helper (const MatrixBase< Derived > & matrix, int j, int k, int m, int n)
Referenced by bruteforce_det3_helper(), and Eigen::internal::determinant_impl< Derived, 4 >::run().
template<typename MatrixType > void Eigen::internal::c_to_fortran_numbering (MatrixType & mat)
References i.
Referenced by Eigen::PastixLU< _MatrixType, IsStrSym >::grabMatrix(), Eigen::PastixLLT< _MatrixType, _UpLo >::grabMatrix(), and Eigen::PastixLDLT< _MatrixType, _UpLo >::grabMatrix().
template<typename Dst , typename Src > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::call_assignment (Dst & dst, const Src & src)
References EIGEN_STRONG_INLINE.
Referenced by Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_set(), Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::_solve_impl(), call_assignment(), Eigen::ArrayBase< Derived >::operator*=(), Eigen::DenseBase< Derived >::operator*=(), Eigen::ArrayBase< Derived >::operator+=(), Eigen::MatrixBase< Derived >::operator+=(), Eigen::SparseMatrixBase< Derived >::operator+=(), Eigen::DenseBase< Derived >::operator+=(), Eigen::ArrayBase< Derived >::operator-=(), Eigen::MatrixBase< Derived >::operator-=(), Eigen::SparseMatrixBase< Derived >::operator-=(), Eigen::DenseBase< Derived >::operator-=(), Eigen::ArrayBase< Derived >::operator/=(), Eigen::DenseBase< Derived >::operator/=(), Eigen::ArrayBase< ArrayWrapper< ExpressionType > >::operator=(), Eigen::MatrixBase< Derived >::operator=(), Eigen::DenseBase< Derived >::operator=(), Eigen::DenseBase< Derived >::swap(), and Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::swap().
template<typename Dst , typename Src > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::call_assignment (const Dst & dst, const Src & src)
References call_assignment(), and EIGEN_STRONG_INLINE.
template<typename Dst , typename Src , typename Func > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::call_assignment (Dst & dst, const Src & src, const Func & func, typename enable_if< evaluator_assume_aliasing< Src >::value, void * >::type = 0)
References call_assignment_no_alias(), and EIGEN_STRONG_INLINE.
template<typename Dst , typename Src , typename Func > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::call_assignment (Dst & dst, const Src & src, const Func & func, typename enable_if<!evaluator_assume_aliasing< Src >::value, void * >::type = 0)
References call_assignment_no_alias(), and EIGEN_STRONG_INLINE.
template<typename Dst , template< typename > class StorageBase, typename Src , typename Func > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::call_assignment (NoAlias< Dst, StorageBase > & dst, const Src & src, const Func & func)
References call_assignment_no_alias(), EIGEN_STRONG_INLINE, and Eigen::NoAlias< ExpressionType, StorageBase >::expression().
template<typename Dst , typename Src , typename Func > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::call_assignment_no_alias (Dst & dst, const Src & src, const Func & func)
References EIGEN_CHECK_BINARY_COMPATIBILIY, EIGEN_STATIC_ASSERT_LVALUE, EIGEN_STATIC_ASSERT_SAME_MATRIX_SIZE, EIGEN_STRONG_INLINE, and type.
Referenced by Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_set_noalias(), Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::_solve_impl(), Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, CoeffBasedProductMode >::addTo(), call_assignment(), call_assignment_no_alias(), Eigen::Ref< const TPlainObjectType, Options, StrideType >::construct(), Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, CoeffBasedProductMode >::evalTo(), Eigen::DenseBase< Derived >::lazyAssign(), Eigen::NoAlias< ExpressionType, StorageBase >::operator+=(), Eigen::SparseMatrixBase< Derived >::operator+=(), Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::operator+=(), Eigen::NoAlias< ExpressionType, StorageBase >::operator-=(), Eigen::SparseMatrixBase< Derived >::operator-=(), Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::operator-=(), Eigen::NoAlias< ExpressionType, StorageBase >::operator=(), Eigen::SparseMatrixBase< Derived >::operator=(), Eigen::internal::Assignment< DstXprType, CwiseBinaryOp< internal::scalar_product_op< ScalarBis, Scalar >, const CwiseNullaryOp< internal::scalar_constant_op< ScalarBis >, Plain >, const Product< Lhs, Rhs, DefaultProduct > >, AssignFunc, Dense2Dense >::run(), Eigen::internal::assignment_from_xpr_op_product< DstXprType, OtherXpr, ProductType, Func1, Func2 >::run(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::SparseMatrix(), Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, CoeffBasedProductMode >::subTo(), and Eigen::internal::unary_evaluator< Inverse< ArgType > >::unary_evaluator().
template<typename Dst , typename Src > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::call_assignment_no_alias (Dst & dst, const Src & src)
References call_assignment_no_alias(), and EIGEN_STRONG_INLINE.
template<typename Dst , typename Src , typename Func > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::call_assignment_no_alias_no_transpose (Dst & dst, const Src & src, const Func & func)
References EIGEN_CHECK_BINARY_COMPATIBILIY, EIGEN_STATIC_ASSERT_LVALUE, EIGEN_STATIC_ASSERT_SAME_MATRIX_SIZE, and EIGEN_STRONG_INLINE.
Referenced by call_assignment_no_alias_no_transpose(), Eigen::SparseSelfAdjointView< MatrixType, _Mode >::operator=(), and Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, SparseSelfAdjoint2Sparse >::run().
template<typename Dst , typename Src > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::call_assignment_no_alias_no_transpose (Dst & dst, const Src & src)
References call_assignment_no_alias_no_transpose(), and check_for_aliasing().
template<typename DstXprType , typename SrcXprType , typename Functor > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::call_dense_assignment_loop (DstXprType & dst, const SrcXprType & src, const Functor & func)
References resize_if_allowed().
Referenced by call_dense_assignment_loop(), and Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, Dense2Dense, Weak >::run().
template<typename DstXprType , typename SrcXprType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::call_dense_assignment_loop (DstXprType & dst, const SrcXprType & src)
References call_dense_assignment_loop().
template<int Mode, bool SetOpposite, typename DstXprType , typename SrcXprType , typename Functor > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::call_triangular_assignment_loop (DstXprType & dst, const SrcXprType & src, const Functor & func)
References Eigen::Dynamic, EIGEN_STRONG_INLINE, EIGEN_UNROLLING_LIMIT, Eigen::HugeCost, Eigen::Lower, Eigen::SelfAdjoint, Eigen::UnitDiag, Eigen::Upper, and Eigen::ZeroDiag.
Referenced by Eigen::TriangularBase< Derived >::evalToLazy().
template<int Mode, bool SetOpposite, typename DstXprType , typename SrcXprType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::call_triangular_assignment_loop (DstXprType & dst, const SrcXprType & src)
static void Eigen::internal::check_DenseIndex_is_signed () inline static
template<typename Dst , typename Src > void Eigen::internal::check_for_aliasing (const Dst & dst, const Src & src)
References Eigen::internal::checkTransposeAliasing_impl< Derived, OtherDerived, MightHaveTransposeAliasing >::run().
Referenced by call_assignment_no_alias_no_transpose(), and Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, Dense2Dense, Weak >::run().
template<typename T > EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE void Eigen::internal::check_size_for_overflow (std::size_t size)
References throw_std_bad_alloc().
template<typename T , int Size> EIGEN_DEVICE_FUNC void Eigen::internal::check_static_allocation_size ()
References Eigen::DontAlign, EIGEN_STACK_ALLOCATION_LIMIT, and EIGEN_STATIC_ASSERT.
EIGEN_DEVICE_FUNC void Eigen::internal::check_that_malloc_is_allowed () inline
Referenced by aligned_malloc(), conditional_aligned_malloc< false >(), and handmade_aligned_realloc().
template<typename IndexType > static IndexType Eigen::internal::clear_mark (IndexType n_row, Colamd_Row< IndexType > Row[]) inline static
Referenced by internal::find_ordering().
template<typename _StorageIndex > int Eigen::internal::cm_factorize_p (cholmod_sparse * A, double beta[2], _StorageIndex * fset, std::size_t fsize, cholmod_factor * L, cholmod_common & Common) inline
template<> int Eigen::internal::cm_factorize_p< long > (cholmod_sparse * A, double beta[2], long * fset, std::size_t fsize, cholmod_factor * L, cholmod_common & Common) inline
template<typename _StorageIndex > cholmod_dense* Eigen::internal::cm_solve (int sys, cholmod_factor & L, cholmod_dense & B, cholmod_common & Common) inline
template<> cholmod_dense* Eigen::internal::cm_solve< long > (int sys, cholmod_factor & L, cholmod_dense & B, cholmod_common & Common) inline
template<typename _StorageIndex > cholmod_sparse* Eigen::internal::cm_spsolve (int sys, cholmod_factor & L, cholmod_sparse & B, cholmod_common & Common) inline
template<> cholmod_sparse* Eigen::internal::cm_spsolve< long > (int sys, cholmod_factor & L, cholmod_sparse & B, cholmod_common & Common) inline
template<typename MatrixType , int i, int j> EIGEN_DEVICE_FUNC MatrixType::Scalar Eigen::internal::cofactor_3x3 (const MatrixType & m) inline
References i.
template<typename MatrixType , int i, int j> EIGEN_DEVICE_FUNC MatrixType::Scalar Eigen::internal::cofactor_4x4 (const MatrixType & matrix) inline
References general_det3_helper(), and i.
template<typename IndexType > static bool Eigen::internal::colamd (IndexType n_row, IndexType n_col, IndexType Alen, IndexType * A, IndexType * p, double knobs[COLAMD_KNOBS], IndexType stats[COLAMD_STATS]) static
Computes a column ordering using the column approximate minimum degree ordering.
Computes a column ordering (Q) of A such that P(AQ)=LU or (AQ)'AQ=LL' have less fill-in and require fewer floating point operations than factorizing the unpermuted matrix A or A'A, respectively.
Parameters
n_row number of rows in A
n_col number of columns in A
Alen,size of the array A
A row indices of the matrix, of size ALen
p column pointers of A, of size n_col+1
knobs parameter settings for colamd
stats colamd output statistics and error codes
template<typename IndexType > IndexType Eigen::internal::colamd_c (IndexType n_col) inline
template<typename IndexType > IndexType Eigen::internal::colamd_r (IndexType n_row) inline
template<typename IndexType > IndexType Eigen::internal::colamd_recommended (IndexType nnz, IndexType n_row, IndexType n_col) inline
Returns the recommended value of Alen.
Returns recommended value of Alen for use by colamd. Returns -1 if any input argument is negative. The use of this routine or macro is optional. Note that the macro uses its arguments more than once, so be careful for side effects, if you pass expressions as arguments to COLAMD_RECOMMENDED.
Parameters
nnz nonzeros in A
n_row number of rows in A
n_col number of columns in A
Returns
recommended value of Alen for use by colamd
static void Eigen::internal::colamd_set_defaults (double knobs[COLAMD_KNOBS]) inline static
set default parameters The use of this routine is optional.
Colamd: rows with more than (knobs [COLAMD_DENSE_ROW] * n_col) entries are removed prior to ordering. Columns with more than (knobs [COLAMD_DENSE_COL] * n_row) entries are removed prior to ordering, and placed last in the output column ordering.
COLAMD_DENSE_ROW and COLAMD_DENSE_COL are defined as 0 and 1, respectively, in colamd.h. Default values of these two knobs are both 0.5. Currently, only knobs [0] and knobs [1] are used, but future versions may use more knobs. If so, they will be properly set to their defaults by the future version of colamd_set_defaults, so that the code that calls colamd will not need to change, assuming that you either use colamd_set_defaults, or pass a (double *) NULL pointer as the knobs array to colamd or symamd.
Parameters
knobs parameter settings for colamd
template<typename MatrixType , typename IndexVector > int Eigen::internal::coletree (const MatrixType & mat, IndexVector & parent, IndexVector & firstRowElt, typename MatrixType::StorageIndex * perm = 0)
Compute the column elimination tree of a sparse matrix
Parameters
mat The matrix in column-major format.
parent The elimination tree
firstRowElt The column index of the first element in each row
perm The permutation to apply to the column of mat
References col(), etree_find(), i, it, m, Eigen::half_impl::min(), and row().
Referenced by Eigen::SparseLU< _MatrixType, _OrderingType >::analyzePattern(), Eigen::SparseQR< _MatrixType, _OrderingType >::analyzePattern(), and Eigen::SparseQR< _MatrixType, _OrderingType >::factorize().
template<typename MatrixType , typename ResultType > EIGEN_DEVICE_FUNC void Eigen::internal::compute_inverse_size2_helper (const MatrixType & matrix, const typename ResultType::Scalar & invdet, ResultType & result) inline
Referenced by Eigen::internal::compute_inverse< MatrixType, ResultType, 2 >::run(), and Eigen::internal::compute_inverse_and_det_with_check< MatrixType, ResultType, 2 >::run().
template<typename MatrixType , typename ResultType > EIGEN_DEVICE_FUNC void Eigen::internal::compute_inverse_size3_helper (const MatrixType & matrix, const typename ResultType::Scalar & invdet, const Matrix< typename ResultType::Scalar, 3, 1 > & cofactors_col0, ResultType & result) inline
References Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::coeffRef().
Referenced by Eigen::internal::compute_inverse< MatrixType, ResultType, 3 >::run(), and Eigen::internal::compute_inverse_and_det_with_check< MatrixType, ResultType, 3 >::run().
template<typename MatrixType , typename DiagType , typename SubDiagType > ComputationInfo Eigen::internal::computeFromTridiagonal_impl (DiagType & diag, SubDiagType & subdiag, const Index maxIterations, bool computeEigenvectors, MatrixType & eivec)
References abs(), Eigen::placeholders::end(), i, Eigen::half_impl::min(), Eigen::NoConvergence, Eigen::Success, and std::swap().
Referenced by Eigen::SelfAdjointEigenSolver< _MatrixType >::compute(), and Eigen::SelfAdjointEigenSolver< _MatrixType >::computeFromTridiagonal().
template<typename LhsScalar , typename RhsScalar , int KcFactor, typename Index > void Eigen::internal::computeProductBlockingSizes (Index & k, Index & m, Index & n, Index num_threads = 1)
Computes the blocking parameters for a m x k times k x n matrix product.
Parameters
[in,out] k Input: the third dimension of the product. Output: the blocking size along the same dimension.
[in,out] m Input: the number of rows of the left hand side. Output: the blocking size along the same dimension.
[in,out] n Input: the number of columns of the right hand side. Output: the blocking size along the same dimension.
Given a m x k times k x n matrix product of scalar types LhsScalar and RhsScalar, this function computes the blocking size parameters along the respective dimensions for matrix products and related algorithms.
The blocking size parameters may be evaluated:
either by a heuristic based on cache sizes;
or using fixed prescribed values (for testing purposes).
See also
setCpuCacheSizes
References m, and useSpecificBlockingSizes().
template<typename LhsScalar , typename RhsScalar , typename Index > void Eigen::internal::computeProductBlockingSizes (Index & k, Index & m, Index & n, Index num_threads = 1) inline
References m.
template<typename T , bool Align> EIGEN_DEVICE_FUNC void Eigen::internal::conditional_aligned_delete (T * ptr, std::size_t size) inline
References size().
template<typename T , bool Align> EIGEN_DEVICE_FUNC void Eigen::internal::conditional_aligned_delete_auto (T * ptr, std::size_t size) inline
References size().
template<bool Align> EIGEN_DEVICE_FUNC void Eigen::internal::conditional_aligned_free (void * ptr) inline
References aligned_free().
template<> EIGEN_DEVICE_FUNC void Eigen::internal::conditional_aligned_free< false > (void * ptr) inline
template<bool Align> EIGEN_DEVICE_FUNC void* Eigen::internal::conditional_aligned_malloc (std::size_t size) inline
References aligned_malloc().
template<> EIGEN_DEVICE_FUNC void* Eigen::internal::conditional_aligned_malloc< false > (std::size_t size) inline
References check_that_malloc_is_allowed(), size(), and throw_std_bad_alloc().
template<typename T , bool Align> EIGEN_DEVICE_FUNC T* Eigen::internal::conditional_aligned_new (std::size_t size) inline
References construct_elements_of_array(), EIGEN_CATCH, EIGEN_THROW, EIGEN_TRY, and size().
template<typename T , bool Align> EIGEN_DEVICE_FUNC T* Eigen::internal::conditional_aligned_new_auto (std::size_t size) inline
References construct_elements_of_array(), EIGEN_CATCH, EIGEN_THROW, EIGEN_TRY, and size().
template<bool Align> void* Eigen::internal::conditional_aligned_realloc (void * ptr, std::size_t new_size, std::size_t old_size) inline
References aligned_realloc().
template<> void* Eigen::internal::conditional_aligned_realloc< false > (void * ptr, std::size_t new_size, std::size_t) inline
template<typename T , bool Align> EIGEN_DEVICE_FUNC T* Eigen::internal::conditional_aligned_realloc_new (T * pts, std::size_t new_size, std::size_t old_size) inline
References construct_elements_of_array(), destruct_elements_of_array(), EIGEN_CATCH, EIGEN_THROW, and EIGEN_TRY.
template<typename T , bool Align> T* Eigen::internal::conditional_aligned_realloc_new_auto (T * pts, std::size_t new_size, std::size_t old_size) inline
References construct_elements_of_array(), destruct_elements_of_array(), EIGEN_CATCH, EIGEN_THROW, and EIGEN_TRY.
template<typename MatrixType , typename Rhs , typename Dest , typename Preconditioner > EIGEN_DONT_INLINE void Eigen::internal::conjugate_gradient (const MatrixType & mat, const Rhs & rhs, Dest & x, const Preconditioner & precond, Index & iters, typename Dest::RealScalar & tol_error)
References abs(), Eigen::PlainObjectBase< Derived >::cols(), i, Eigen::Lower, real(), and sqrt().
Referenced by Eigen::ConjugateGradient< _MatrixType, _UpLo, _Preconditioner >::_solve_with_guess_impl().
template<typename Lhs , typename Rhs , typename ResultType > static void Eigen::internal::conservative_sparse_sparse_product_impl (const Lhs & lhs, const Rhs & rhs, ResultType & res, bool sortedInsertion = false) static
References Eigen::ColMajor, ei_declare_aligned_stack_constructed_variable, eigen_assert, i, Eigen::RowMajor, and Eigen::RowMajorBit.
template<typename T > EIGEN_DEVICE_FUNC T* Eigen::internal::const_cast_ptr (const T * ptr) inline
template<typename T > EIGEN_DEVICE_FUNC T* Eigen::internal::construct_elements_of_array (T * ptr, std::size_t size) inline
References destruct_elements_of_array(), EIGEN_CATCH, EIGEN_THROW, EIGEN_TRY, i, NULL, and size().
Referenced by aligned_new(), Eigen::internal::aligned_stack_memory_handler< T >::aligned_stack_memory_handler(), conditional_aligned_new(), conditional_aligned_new_auto(), conditional_aligned_realloc_new(), and conditional_aligned_realloc_new_auto().
template<typename IndexDest , typename IndexSrc > EIGEN_DEVICE_FUNC IndexDest Eigen::internal::convert_index (const IndexSrc & idx) inline
References eigen_internal_assert.
Referenced by Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::conservativeResize(), Eigen::IncompleteLUT< _Scalar, _StorageIndex >::factorize(), Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::insert(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insert(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::insertBackUncompressed(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertCompressed(), and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertUncompressed().
bool Eigen::internal::copy_bool (bool b) inline
template<typename StorageIndex > StorageIndex Eigen::internal::cs_tdfs (StorageIndex j, StorageIndex k, StorageIndex * head, const StorageIndex * next, StorageIndex * post, StorageIndex * stack)
References i.
template<typename StorageIndex > static StorageIndex Eigen::internal::cs_wclear (StorageIndex mark, StorageIndex lemax, StorageIndex * w, StorageIndex n) static
template<typename T > EIGEN_DEVICE_FUNC void Eigen::internal::destruct_elements_of_array (T * ptr, std::size_t size) inline
References size().
Referenced by conditional_aligned_realloc_new(), conditional_aligned_realloc_new_auto(), and construct_elements_of_array().
template<typename IndexType > static void Eigen::internal::detect_super_cols (colamd_col< IndexType > Col[], IndexType A[], IndexType head[], IndexType row_start, IndexType row_length) static
Referenced by internal::find_ordering().
Eigen::internal::EIGEN_CATCH_ASSIGN_XPR_OP_PRODUCT (assign_op , scalar_sum_op , add_assign_op)
Eigen::internal::EIGEN_CATCH_ASSIGN_XPR_OP_PRODUCT (add_assign_op , scalar_sum_op , add_assign_op)
Eigen::internal::EIGEN_CATCH_ASSIGN_XPR_OP_PRODUCT (sub_assign_op , scalar_sum_op , sub_assign_op)
Eigen::internal::EIGEN_CATCH_ASSIGN_XPR_OP_PRODUCT (assign_op , scalar_difference_op , sub_assign_op)
Eigen::internal::EIGEN_CATCH_ASSIGN_XPR_OP_PRODUCT (add_assign_op , scalar_difference_op , sub_assign_op)
Eigen::internal::EIGEN_CATCH_ASSIGN_XPR_OP_PRODUCT (sub_assign_op , scalar_difference_op , add_assign_op)
Eigen::internal::EIGEN_MEMBER_FUNCTOR (squaredNorm , Size *NumTraits< Scalar >::MulCost+(Size-1)*NumTraits< Scalar >::AddCost)
Eigen::internal::EIGEN_MEMBER_FUNCTOR (norm , (Size+5)*NumTraits< Scalar >::MulCost+(Size-1)*NumTraits< Scalar >::AddCost)
Eigen::internal::EIGEN_MEMBER_FUNCTOR (stableNorm , (Size+5)*NumTraits< Scalar >::MulCost+(Size-1)*NumTraits< Scalar >::AddCost)
Eigen::internal::EIGEN_MEMBER_FUNCTOR (blueNorm , (Size+5)*NumTraits< Scalar >::MulCost+(Size-1)*NumTraits< Scalar >::AddCost)
Eigen::internal::EIGEN_MEMBER_FUNCTOR (hypotNorm , (Size-1)*functor_traits< scalar_hypot_op< Scalar > >::Cost)
Eigen::internal::EIGEN_MEMBER_FUNCTOR (sum , (Size-1)*NumTraits< Scalar >::AddCost)
Eigen::internal::EIGEN_MEMBER_FUNCTOR (mean , (Size-1)*NumTraits< Scalar >::AddCost+NumTraits< Scalar >::MulCost)
Eigen::internal::EIGEN_MEMBER_FUNCTOR (minCoeff , (Size-1)*NumTraits< Scalar >::AddCost)
Eigen::internal::EIGEN_MEMBER_FUNCTOR (maxCoeff , (Size-1)*NumTraits< Scalar >::AddCost)
Eigen::internal::EIGEN_MEMBER_FUNCTOR (all , (Size-1)*NumTraits< Scalar >::AddCost)
Eigen::internal::EIGEN_MEMBER_FUNCTOR (any , (Size-1)*NumTraits< Scalar >::AddCost)
Eigen::internal::EIGEN_MEMBER_FUNCTOR (count , (Size-1)*NumTraits< Scalar >::AddCost)
Eigen::internal::EIGEN_MEMBER_FUNCTOR (prod , (Size-1)*NumTraits< Scalar >::MulCost)
void Eigen::internal::eigen_pastix (pastix_data_t ** pastix_data, int pastix_comm, int n, int * ptr, int * idx, float * vals, int * perm, int * invp, float * x, int nbrhs, int * iparm, double * dparm)
References NULL.
Referenced by Eigen::PastixBase< Derived >::_solve_impl(), Eigen::PastixBase< Derived >::analyzePattern(), Eigen::PastixBase< PastixLU< _MatrixType > >::clean(), Eigen::PastixBase< Derived >::factorize(), and Eigen::PastixBase< Derived >::init().
void Eigen::internal::eigen_pastix (pastix_data_t ** pastix_data, int pastix_comm, int n, int * ptr, int * idx, double * vals, int * perm, int * invp, double * x, int nbrhs, int * iparm, double * dparm)
References NULL.
void Eigen::internal::eigen_pastix (pastix_data_t ** pastix_data, int pastix_comm, int n, int * ptr, int * idx, std::complex< float > * vals, int * perm, int * invp, std::complex< float > * x, int nbrhs, int * iparm, double * dparm)
References NULL.
void Eigen::internal::eigen_pastix (pastix_data_t ** pastix_data, int pastix_comm, int n, int * ptr, int * idx, std::complex< double > * vals, int * perm, int * invp, std::complex< double > * x, int nbrhs, int * iparm, double * dparm)
References NULL.
template<typename Index , typename IndexVector > Index Eigen::internal::etree_find (Index i, IndexVector & pp)
Find the root of the tree/set containing the vertex i : Use Path halving
Referenced by coletree().
Index Eigen::internal::eval_expr_given_size (Index x, Index) inline
Referenced by makeIndexedViewCompatible(), and operator()().
template<int N> FixedInt<N> Eigen::internal::eval_expr_given_size (FixedInt< N > x, Index)
template<typename Derived > Index Eigen::internal::eval_expr_given_size (const Symbolic::BaseExpr< Derived > & x, Index size)
References Eigen::Symbolic::BaseExpr< Derived >::derived(), and Eigen::placeholders::last.
Referenced by makeIndexedViewCompatible().
template<typename LhsScalar , typename RhsScalar , int KcFactor, typename Index > void Eigen::internal::evaluateProductBlockingSizesHeuristic (Index & k, Index & m, Index & n, Index num_threads = 1)
References Eigen::numext::div_ceil(), eigen_internal_assert, Eigen::GetAction, m, and manage_caching_sizes().
template<typename T > const T::Scalar* Eigen::internal::extract_data (const T & m)
References Eigen::internal::extract_data_selector< T, HasUsableDirectAccess >::run().
Referenced by Eigen::TriangularViewImpl< MatrixType, Mode, Sparse >::_solve_impl(), Eigen::internal::Assignment< DstXprType, Inverse< XprType >, internal::assign_op< typename DstXprType::Scalar, typename XprType::Scalar >, Dense2Dense >::run(), Eigen::internal::check_transpose_aliasing_run_time_selector< Scalar, DestIsTransposed, OtherDerived >::run(), Eigen::internal::check_transpose_aliasing_run_time_selector< Scalar, DestIsTransposed, CwiseBinaryOp< BinOp, DerivedA, DerivedB > >::run(), and Eigen::internal::checkTransposeAliasing_impl< Derived, OtherDerived, MightHaveTransposeAliasing >::run().
template<typename IndexType > static IndexType Eigen::internal::find_ordering (IndexType n_row, IndexType n_col, IndexType Alen, Colamd_Row< IndexType > Row[], colamd_col< IndexType > Col[], IndexType A[], IndexType head[], IndexType n_col2, IndexType max_deg, IndexType pfree) static
Referenced by internal::colamd().
template<typename T > Index Eigen::internal::first (const T & x)
Referenced by first_aligned(), nr_etdfs(), operator()(), pabs< Packet4f >(), pblend(), predux_max< Packet2d >(), QuickSplit(), and Eigen::seqN().
template<int Alignment, typename Scalar , typename Index > EIGEN_DEVICE_FUNC Index Eigen::internal::first_aligned (const Scalar * array, Index size) inline
References first(), and size().
template<int Alignment, typename Derived > static Index Eigen::internal::first_aligned (const DenseBase< Derived > & m) inline static
References Eigen::DirectAccessBit, and Eigen::internal::first_aligned_impl< Alignment, Derived, JustReturnZero >::run().
template<typename Scalar , typename Index > EIGEN_DEVICE_FUNC Index Eigen::internal::first_default_aligned (const Scalar * array, Index size) inline
References size().
template<typename Derived > static Index Eigen::internal::first_default_aligned (const DenseBase< Derived > & m) inline static
Referenced by Eigen::internal::blas_data_mapper< const Scalar, Index, StorageOrder >::firstAligned(), Eigen::internal::SparseLUImpl< Scalar, StorageIndex >::panel_bmod(), Eigen::internal::selfadjoint_matrix_vector_product< Scalar, Index, StorageOrder, UpLo, ConjugateLhs, ConjugateRhs, Version >::run(), Eigen::internal::LU_kernel_bmod< SegSizeAtCompileTime >::run(), Eigen::internal::redux_impl< Func, Derived, LinearVectorizedTraversal, NoUnrolling >::run(), Eigen::internal::apply_rotation_in_the_plane_selector< Scalar, OtherScalar, SizeAtCompileTime, MinAlignment, true >::run(), sparselu_gemm(), and Eigen::MatrixBase< Derived >::stableNorm().
template<typename Index > Index Eigen::internal::first_multiple (Index size, Index base) inline
Referenced by Eigen::internal::LU_kernel_bmod< SegSizeAtCompileTime >::run().
template<typename MatrixType > void Eigen::internal::fortran_to_c_numbering (MatrixType & mat)
References i.
template<typename IndexType > static IndexType Eigen::internal::garbage_collection (IndexType n_row, IndexType n_col, Colamd_Row< IndexType > Row[], colamd_col< IndexType > Col[], IndexType A[], IndexType * pfree) static
Referenced by internal::find_ordering().
template<typename CJ , typename A , typename B , typename C , typename T > EIGEN_STRONG_INLINE void Eigen::internal::gebp_madd (const CJ & cj, A & a, B & b, C & c, T & t)
References Eigen::internal::gebp_madd_selector< CJ, A, B, C, T >::run().
template<typename Derived > EIGEN_DEVICE_FUNC const Derived::Scalar Eigen::internal::general_det3_helper (const MatrixBase< Derived > & matrix, int i1, int i2, int i3, int j1, int j2, int j3) inline
Referenced by cofactor_4x4(), and Eigen::internal::compute_inverse_and_det_with_check< MatrixType, ResultType, 3 >::run().
template<typename T > T Eigen::internal::generic_fast_tanh_float (const T & a_x)
References pdiv(), pmadd(), pmax(), pmin(), and pmul().
Referenced by ptanh< Packet4f >(), and ptanh< Packet8f >().
template<typename T > EIGEN_DEVICE_FUNC Index Eigen::internal::get_runtime_value (const T & x)
Referenced by block(), bottomLeftCorner(), bottomRightCorner(), bottomRows(), head(), leftCols(), middleCols(), middleRows(), rightCols(), segment(), tail(), topLeftCorner(), topRightCorner(), and topRows().
template<int N> EIGEN_DEVICE_FUNC Index Eigen::internal::get_runtime_value (FixedInt< N > *)()
References N.
void Eigen::internal::handmade_aligned_free (void * ptr) inline
Referenced by aligned_free().
void* Eigen::internal::handmade_aligned_malloc (std::size_t size) inline
References EIGEN_DEFAULT_ALIGN_BYTES.
Referenced by aligned_malloc(), and handmade_aligned_realloc().
void* Eigen::internal::handmade_aligned_realloc (void * ptr, std::size_t size, std::size_t = 0) inline
References check_that_malloc_is_allowed(), eigen_assert, EIGEN_DEFAULT_ALIGN_BYTES, and handmade_aligned_malloc().
Referenced by aligned_realloc().
template<typename MatrixQR , typename HCoeffs > void Eigen::internal::householder_qr_inplace_unblocked (MatrixQR & mat, HCoeffs & hCoeffs, typename MatrixQR::Scalar * tempData = 0)
References Eigen::HouseholderQR< _MatrixType >::cols(), eigen_assert, Eigen::half_impl::min(), Eigen::PlainObjectBase< Derived >::resize(), Eigen::HouseholderQR< _MatrixType >::rows(), and size().
Referenced by Eigen::internal::householder_qr_inplace_blocked< MatrixQR, HCoeffs, MatrixQRScalar, InnerStrideIsOne >::run().
template<typename T > EIGEN_DEVICE_FUNC void Eigen::internal::ignore_unused_variable (const T &)
template<typename IndexType > static IndexType Eigen::internal::init_rows_cols (IndexType n_row, IndexType n_col, Colamd_Row< IndexType > Row[], colamd_col< IndexType > col[], IndexType A[], IndexType p[], IndexType stats[COLAMD_STATS]) static
Referenced by internal::colamd().
template<typename IndexType > static void Eigen::internal::init_scoring (IndexType n_row, IndexType n_col, Colamd_Row< IndexType > Row[], colamd_col< IndexType > Col[], IndexType A[], IndexType head[], double knobs[COLAMD_KNOBS], IndexType * p_n_row2, IndexType * p_n_col2, IndexType * p_max_deg) static
Referenced by internal::colamd().
template<typename T1 , typename T2 > bool Eigen::internal::is_same_dense (const T1 & mat1, const T2 & mat2, typename enable_if< has_direct_access< T1 >::ret &&has_direct_access< T2 >::ret, T1 >::type * = 0)
Referenced by Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::_solve_impl(), Eigen::LLT< _MatrixType, _UpLo >::compute(), Eigen::internal::triangular_solve_retval< Side, TriangularType, Rhs >::evalTo(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::evalTo(), Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, DenseShape >::run(), and Eigen::internal::transposition_matrix_product< ExpressionType, Side, Transposed, ExpressionShape >::run().
template<typename T1 , typename T2 > bool Eigen::internal::is_same_dense (const T1 & , const T2 & , typename enable_if<!(has_direct_access< T1 >::ret &&has_direct_access< T2 >::ret), T1 >::type * = 0)
template<typename MatrixType , typename Rhs , typename Dest , typename Preconditioner > EIGEN_DONT_INLINE void Eigen::internal::least_square_conjugate_gradient (const MatrixType & mat, const Rhs & rhs, Dest & x, const Preconditioner & precond, Index & iters, typename Dest::RealScalar & tol_error)
References abs(), i, m, real(), and sqrt().
Referenced by Eigen::LeastSquaresConjugateGradient< _MatrixType, _Preconditioner >::_solve_with_guess_impl().
template<typename MatrixType , typename VectorType > static Index Eigen::internal::llt_rank_update_lower (MatrixType & mat, const VectorType & vec, const typename MatrixType::RealScalar & sigma) static
References abs2(), apply_rotation_in_the_plane(), eigen_assert, i, Eigen::JacobiRotation< Scalar >::makeGivens(), real(), and sqrt().
Referenced by Eigen::internal::llt_inplace< Scalar, Lower >::rankUpdate().
Index Eigen::internal::LUnumTempV (Index & m, Index & w, Index & t, Index & b) inline
References m, and Eigen::half_impl::max().
Referenced by Eigen::SparseLU< _MatrixType, _OrderingType >::factorize().
template<typename Scalar > Index Eigen::internal::LUTempSpace (Index & m, Index & w) inline
References LUNoMarker.
template<typename TriangularFactorType , typename VectorsType , typename CoeffsType > void Eigen::internal::make_block_householder_triangular_factor (TriangularFactorType & triFactor, const VectorsType & vectors, const CoeffsType & hCoeffs)
References eigen_assert, and i.
Referenced by apply_block_householder_on_the_left().
template<typename T , typename Q > const T& Eigen::internal::makeIndexedViewCompatible (const T & x, Index , Q)
template<typename T > enable_if<Symbolic::is_symbolic<T>::value,SingleRange>::type Eigen::internal::makeIndexedViewCompatible (const T & id, Index size, SpecializedType)
References eval_expr_given_size().
template<typename XprSizeType > AllRange<get_fixed_value<XprSizeType>::value> Eigen::internal::makeIndexedViewCompatible (all_t , XprSizeType size, SpecializedType) inline
References size().
template<typename FirstType , typename SizeType , typename IncrType > ArithmeticSequence<Index,typename make_size_type<SizeType>::type,IncrType> Eigen::internal::makeIndexedViewCompatible (const ArithmeticSequence< FirstType, SizeType, IncrType > & ids, Index size, SpecializedType)
References eval_expr_given_size(), Eigen::ArithmeticSequence< FirstType, SizeType, IncrType >::firstObject(), Eigen::ArithmeticSequence< FirstType, SizeType, IncrType >::incrObject(), size(), and Eigen::ArithmeticSequence< FirstType, SizeType, IncrType >::sizeObject().
Referenced by ivcCol(), ivcRow(), and ivcSize().
void Eigen::internal::manage_caching_sizes (Action action, std::ptrdiff_t * l1, std::ptrdiff_t * l2, std::ptrdiff_t * l3) inline
References eigen_internal_assert, Eigen::GetAction, Eigen::internal::CacheSizes::m_l1, Eigen::internal::CacheSizes::m_l2, Eigen::internal::CacheSizes::m_l3, and Eigen::SetAction.
Referenced by evaluateProductBlockingSizesHeuristic(), Eigen::initParallel(), Eigen::l1CacheSize(), Eigen::l2CacheSize(), Eigen::l3CacheSize(), Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheLeft, Mode, Conjugate, TriStorageOrder, ColMajor >::run(), and Eigen::setCpuCacheSizes().
std::ptrdiff_t Eigen::internal::manage_caching_sizes_helper (std::ptrdiff_t a, std::ptrdiff_t b) inline
References defaultL1CacheSize, defaultL2CacheSize, and defaultL3CacheSize.
Referenced by Eigen::internal::CacheSizes::CacheSizes().
void Eigen::internal::manage_multi_threading (Action action, int * v) inline
References eigen_internal_assert, EIGEN_UNUSED, Eigen::GetAction, and Eigen::SetAction.
Referenced by Eigen::initParallel(), Eigen::nbThreads(), and Eigen::setNbThreads().
template<typename Scalar , int Flags, typename Index > MappedSparseMatrix<Scalar,Flags,Index> Eigen::internal::map_superlu (SluMatrix & sluMat)
View a Super LU matrix as an Eigen expression
References Eigen::ColMajor, eigen_assert, Eigen::SluMatrix::innerInd, Eigen::SluMatrix::outerInd, Eigen::RowMajor, Eigen::SluMatrix::storage, and Eigen::SluMatrix::values.
template<typename Scalar , typename StorageIndex > void Eigen::internal::minimum_degree_ordering (SparseMatrix< Scalar, ColMajor, StorageIndex > & C, PermutationMatrix< Dynamic, Dynamic, StorageIndex > & perm)
References amd_flip(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::cols(), e, ei_declare_aligned_stack_constructed_variable, head(), i, Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex >::indices(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::innerIndexPtr(), Eigen::placeholders::last, Eigen::half_impl::min(), Eigen::SparseCompressedBase< Derived >::nonZeros(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::outerIndexPtr(), Eigen::PermutationBase< Derived >::resize(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::resizeNonZeros(), sqrt(), and W.
template<typename IndexVector > void Eigen::internal::nr_etdfs (typename IndexVector::Scalar n, IndexVector & parent, IndexVector & first_kid, IndexVector & next_kid, IndexVector & post, typename IndexVector::Scalar postnum)
Depth-first search from vertex n. No recursion. This routine was contributed by Cdric Doucet, CEDRAT Group, Meylan, France.
References first().
Referenced by treePostorder().
std::ostream& Eigen::internal::operator<< (std::ostream & s, const Packet16uc & v) inline
References i.
Referenced by pblend().
std::ostream& Eigen::internal::operator<< (std::ostream & s, const Packet4f & v) inline
std::ostream & Eigen::internal::operator<< (std::ostream & s, const Packet4i & v) inline
std::ostream & Eigen::internal::operator<< (std::ostream & s, const Packet4ui & v) inline
std::ostream& Eigen::internal::operator<< (std::ostream & s, const Packet2l & v) inline
References Eigen::internal::Packet::l, and Eigen::internal::Packet::v2l.
std::ostream& Eigen::internal::operator<< (std::ostream & s, const Packet2ul & v) inline
References Eigen::internal::Packet::ul, and Eigen::internal::Packet::v2ul.
std::ostream& Eigen::internal::operator<< (std::ostream & s, const Packet2d & v) inline
References Eigen::internal::Packet::d, and Eigen::internal::Packet::v2d.
template<typename IndexType > static void Eigen::internal::order_children (IndexType n_col, colamd_col< IndexType > Col[], IndexType p[]) inline static
Referenced by internal::colamd().
template<typename MatrixType > void Eigen::internal::ordering_helper_at_plus_a (const MatrixType & A, MatrixType & symmat)
References i, and it.
template<typename Dst , typename Lhs , typename Rhs , typename Func > void Eigen::internal::outer_product_selector_run (Dst & dst, const Lhs & lhs, const Rhs & rhs, const Func & func, const false_type &)
Referenced by Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, OuterProduct >::addTo(), Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, OuterProduct >::evalTo(), Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, OuterProduct >::scaleAndAddTo(), and Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, OuterProduct >::subTo().
template<typename Dst , typename Lhs , typename Rhs , typename Func > void Eigen::internal::outer_product_selector_run (Dst & dst, const Lhs & lhs, const Rhs & rhs, const Func & func, const true_type &)
References i.
uint32x2_t Eigen::internal::p2ui_CONJ_XOR () inline
uint32x4_t Eigen::internal::p4ui_CONJ_XOR () inline
template<typename Packet > EIGEN_DEVICE_FUNC Packet Eigen::internal::pabs (const Packet & a) inline
References abs().
template<> EIGEN_STRONG_INLINE Packet8f Eigen::internal::pabs (const Packet8f & a)
template<> EIGEN_STRONG_INLINE Packet4d Eigen::internal::pabs (const Packet4d & a)
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::pabs (const Packet2d & a)
References EIGEN_STRONG_INLINE, pabs(), pbroadcast4< Packet4f >(), pload< Packet4f >(), and vec4f_swizzle1.
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::pabs (const Packet4f & a)
Referenced by pabs(), pabs< Packet4f >(), Eigen::internal::scalar_abs_op< Scalar >::packetOp(), pblend(), pcos< Packet4f >(), pfirst< Packet4i >(), preverse(), and psin< Packet4f >().
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::pabs (const Packet4i & a)
template<> EIGEN_STRONG_INLINE Packet16f Eigen::internal::pabs (const Packet16f & a)
template<> EIGEN_STRONG_INLINE Packet8d Eigen::internal::pabs (const Packet8d & a)
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::pabs< Packet2d > (const Packet2d & a)
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::pabs< Packet4f > (const Packet4f & a)
References EIGEN_ALIGN16, EIGEN_STRONG_INLINE, first(), pabs(), Eigen::internal::PacketBlock< Packet, N >::packet, padd(), padd< Packet2d >(), padd< Packet4i >(), pblend(), pfirst(), pmax< Packet2d >(), pmax< Packet4i >(), pmin< Packet2d >(), pmin< Packet4i >(), pmul(), predux< Packet2d >(), predux< Packet4f >(), predux< Packet4i >(), predux_max< Packet2d >(), predux_max< Packet4f >(), predux_max< Packet4i >(), predux_min< Packet2d >(), predux_min< Packet4f >(), predux_min< Packet4i >(), predux_mul(), predux_mul< Packet2d >(), predux_mul< Packet4f >(), predux_mul< Packet4i >(), preduxp< Packet2d >(), preduxp< Packet4f >(), preduxp< Packet4i >(), pstore(), ptranspose(), select(), Eigen::internal::Selector< N >::select, and Eigen::internal::Packet4f::v4f.
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::pabs< Packet4i > (const Packet4i & a)
template<typename Packet > EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet Eigen::internal::pacos (const Packet & a)
References acos(), and EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS.
Referenced by Eigen::internal::scalar_acos_op< Scalar >::packetOp().
template<typename Packet > EIGEN_DEVICE_FUNC Packet Eigen::internal::padd (const Packet & a, const Packet & b) inline
Referenced by Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::acc(), Eigen::internal::add_assign_op< DstScalar, SrcScalar >::assignPacket(), Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::madd(), Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::madd(), Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::madd_impl(), Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, _ConjRhs >::madd_impl(), Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::operator()(), pabs< Packet4f >(), Eigen::internal::scalar_sum_op< int, int >::packetOp(), Eigen::internal::linspaced_op_impl< Scalar, Packet, false >::packetOp(), padd(), pcos< Packet4f >(), pdiv< Packet2d >(), pexp< Packet4f >(), pexp< Packet8f >(), plog< Packet4f >(), plog< Packet8f >(), Eigen::internal::conj_helper< Eigen::internal::true_type, Eigen::internal::true_type, ConjLhs, false >::pmadd(), Eigen::internal::conj_helper< std::complex< RealScalar >, RealScalar, Conj, false >::pmadd(), Eigen::internal::conj_helper< RealScalar, std::complex< RealScalar >, false, Conj >::pmadd(), Eigen::internal::conj_helper< Packet4cf, Packet4cf, false, true >::pmadd(), Eigen::internal::conj_helper< Packet4cf, Packet4cf, true, false >::pmadd(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, false, true >::pmadd(), Eigen::internal::conj_helper< Packet4cf, Packet4cf, true, true >::pmadd(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, false >::pmadd(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmadd(), Eigen::internal::conj_helper< Packet2cd, Packet2cd, false, true >::pmadd(), Eigen::internal::conj_helper< Packet1cd, Packet1cd, false, true >::pmadd(), Eigen::internal::conj_helper< Packet2cd, Packet2cd, true, false >::pmadd(), Eigen::internal::conj_helper< Packet2cd, Packet2cd, true, true >::pmadd(), Eigen::internal::conj_helper< Packet1cd, Packet1cd, true, false >::pmadd(), Eigen::internal::conj_helper< Packet1cd, Packet1cd, true, true >::pmadd(), pmadd(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), predux< Packet2cd >(), predux< Packet4cf >(), psin< Packet4f >(), psin< Packet8f >(), ptranspose(), Eigen::internal::quat_product< Architecture::SSE, Derived, OtherDerived, double >::run(), Eigen::internal::gebp_madd_selector< CJ, T, T, T, T >::run(), and Eigen::internal::apply_rotation_in_the_plane_selector< Scalar, OtherScalar, SizeAtCompileTime, MinAlignment, true >::run().
template<typename Packet > DoublePacket<Packet> Eigen::internal::padd (const DoublePacket< Packet > & a, const DoublePacket< Packet > & b)
References Eigen::internal::DoublePacket< Packet >::first, padd(), and Eigen::internal::DoublePacket< Packet >::second.
template<> EIGEN_STRONG_INLINE Packet16f Eigen::internal::padd< Packet16f > (const Packet16f & a, const Packet16f & b)
template<> EIGEN_STRONG_INLINE Packet1cd Eigen::internal::padd< Packet1cd > (const Packet1cd & a, const Packet1cd & b)
Referenced by Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), pscatter< std::complex< double >, Packet1cd >(), and ptranspose().
template<> EIGEN_STRONG_INLINE Packet2cd Eigen::internal::padd< Packet2cd > (const Packet2cd & a, const Packet2cd & b)
template<> EIGEN_STRONG_INLINE Packet2cf Eigen::internal::padd< Packet2cf > (const Packet2cf & a, const Packet2cf & b)
References Eigen::internal::Packet2cf::Packet2cf().
Referenced by pscatter< std::complex< double >, Packet1cd >().
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::padd< Packet2d > (const Packet2d & a, const Packet2d & b)
References EIGEN_STRONG_INLINE, padd< Packet4i >(), and psub< Packet4f >().
Referenced by pabs< Packet4f >(), pblend(), pmadd(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), ptranspose(), and Eigen::internal::palign_impl< Offset, Packet2d >::run().
template<> EIGEN_STRONG_INLINE Packet4cf Eigen::internal::padd< Packet4cf > (const Packet4cf & a, const Packet4cf & b)
References Eigen::internal::Packet4cf::Packet4cf().
template<> EIGEN_STRONG_INLINE Packet4d Eigen::internal::padd< Packet4d > (const Packet4d & a, const Packet4d & b)
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::padd< Packet4f > (const Packet4f & a, const Packet4f & b)
Referenced by pdiv< Packet2cf >(), plset< Packet2d >(), plset< Packet4i >(), pmadd(), pmul< Packet2cf >(), predux< Packet2cf >(), preduxp< Packet2cf >(), pscatter< std::complex< double >, Packet1cd >(), and Eigen::internal::palign_impl< Offset, Packet2d >::run().
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::padd< Packet4i > (const Packet4i & a, const Packet4i & b)
Referenced by pabs< Packet4f >(), padd< Packet2d >(), plset< Packet4i >(), pmadd(), and Eigen::internal::palign_impl< Offset, Packet2d >::run().
template<> EIGEN_STRONG_INLINE Packet8d Eigen::internal::padd< Packet8d > (const Packet8d & a, const Packet8d & b)
template<> EIGEN_STRONG_INLINE Packet8f Eigen::internal::padd< Packet8f > (const Packet8f & a, const Packet8f & b)
template<int Offset, typename PacketType > void Eigen::internal::palign (PacketType & first, const PacketType & second) inline
References Eigen::internal::palign_impl< Offset, PacketType >::run().
template<typename Packet > EIGEN_DEVICE_FUNC Packet Eigen::internal::pand (const Packet & a, const Packet & b) inline
Referenced by plog< Packet4f >(), pmadd(), and ptranspose().
template<> EIGEN_STRONG_INLINE Packet16f Eigen::internal::pand< Packet16f > (const Packet16f & a, const Packet16f & b)
template<> EIGEN_STRONG_INLINE Packet1cd Eigen::internal::pand< Packet1cd > (const Packet1cd & a, const Packet1cd & b)
Referenced by Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), pscatter< std::complex< double >, Packet1cd >(), and ptranspose().
template<> EIGEN_STRONG_INLINE Packet2cd Eigen::internal::pand< Packet2cd > (const Packet2cd & a, const Packet2cd & b)
template<> EIGEN_STRONG_INLINE Packet2cf Eigen::internal::pand< Packet2cf > (const Packet2cf & a, const Packet2cf & b)
References Eigen::internal::Packet2cf::Packet2cf(), and pand< Packet4f >().
Referenced by pscatter< std::complex< double >, Packet1cd >().
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::pand< Packet2d > (const Packet2d & a, const Packet2d & b)
References EIGEN_STRONG_INLINE, pand< Packet4i >(), and por< Packet4f >().
Referenced by pblend(), and pmadd().
template<> EIGEN_STRONG_INLINE Packet4cf Eigen::internal::pand< Packet4cf > (const Packet4cf & a, const Packet4cf & b)
References Eigen::internal::Packet4cf::Packet4cf().
template<> EIGEN_STRONG_INLINE Packet4d Eigen::internal::pand< Packet4d > (const Packet4d & a, const Packet4d & b)
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::pand< Packet4f > (const Packet4f & a, const Packet4f & b)
Referenced by pand< Packet2cf >(), plset< Packet4i >(), pmadd(), pmax< Packet2d >(), and pscatter< std::complex< double >, Packet1cd >().
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::pand< Packet4i > (const Packet4i & a, const Packet4i & b)
Referenced by pand< Packet2d >(), plset< Packet4i >(), and pmadd().
template<> EIGEN_STRONG_INLINE Packet8d Eigen::internal::pand< Packet8d > (const Packet8d & a, const Packet8d & b)
template<> EIGEN_STRONG_INLINE Packet8f Eigen::internal::pand< Packet8f > (const Packet8f & a, const Packet8f & b)
template<typename Packet > EIGEN_DEVICE_FUNC Packet Eigen::internal::pandnot (const Packet & a, const Packet & b) inline
Referenced by pmadd(), and ptranspose().
template<> EIGEN_STRONG_INLINE Packet16f Eigen::internal::pandnot< Packet16f > (const Packet16f & a, const Packet16f & b)
template<> EIGEN_STRONG_INLINE Packet1cd Eigen::internal::pandnot< Packet1cd > (const Packet1cd & a, const Packet1cd & b)
Referenced by Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), pscatter< std::complex< double >, Packet1cd >(), and ptranspose().
template<> EIGEN_STRONG_INLINE Packet2cd Eigen::internal::pandnot< Packet2cd > (const Packet2cd & a, const Packet2cd & b)
template<> EIGEN_STRONG_INLINE Packet2cf Eigen::internal::pandnot< Packet2cf > (const Packet2cf & a, const Packet2cf & b)
References Eigen::internal::Packet2cf::Packet2cf(), and pandnot< Packet4f >().
Referenced by pscatter< std::complex< double >, Packet1cd >().
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::pandnot< Packet2d > (const Packet2d & a, const Packet2d & b)
References EIGEN_DEBUG_ALIGNED_LOAD, EIGEN_STRONG_INLINE, pandnot< Packet4i >(), and pload< Packet4f >().
Referenced by pblend(), and pmadd().
template<> EIGEN_STRONG_INLINE Packet4cf Eigen::internal::pandnot< Packet4cf > (const Packet4cf & a, const Packet4cf & b)
References Eigen::internal::Packet4cf::Packet4cf().
template<> EIGEN_STRONG_INLINE Packet4d Eigen::internal::pandnot< Packet4d > (const Packet4d & a, const Packet4d & b)
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::pandnot< Packet4f > (const Packet4f & a, const Packet4f & b)
Referenced by pandnot< Packet2cf >(), plset< Packet4i >(), pmadd(), pscatter< std::complex< double >, Packet1cd >(), and pxor< Packet2d >().
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::pandnot< Packet4i > (const Packet4i & a, const Packet4i & b)
Referenced by pandnot< Packet2d >(), plset< Packet4i >(), and pmadd().
template<> EIGEN_STRONG_INLINE Packet8d Eigen::internal::pandnot< Packet8d > (const Packet8d & a, const Packet8d & b)
template<> EIGEN_STRONG_INLINE Packet8f Eigen::internal::pandnot< Packet8f > (const Packet8f & a, const Packet8f & b)
template<bool Condition, typename Functor , typename Index > void Eigen::internal::parallelize_gemm (const Functor & func, Index rows, Index cols, Index depth, bool transpose)
References ei_declare_aligned_stack_constructed_variable, EIGEN_UNUSED_VARIABLE, i, Eigen::initParallel(), Eigen::nbThreads(), size(), and std::swap().
template<typename Packet > EIGEN_DEVICE_FUNC Packet Eigen::internal::parg (const Packet & a) inline
References arg().
Referenced by Eigen::internal::scalar_arg_op< Scalar >::packetOp().
template<typename MatrixType , typename TranspositionType > void Eigen::internal::partial_lu_inplace (MatrixType & lu, TranspositionType & row_transpositions, typename TranspositionType::StorageIndex & nb_transpositions)
References Eigen::ColMajor, eigen_assert, Eigen::RowMajor, and Eigen::RowMajorBit.
Referenced by Eigen::PartialPivLU< _MatrixType >::compute().
template<typename Packet > EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet Eigen::internal::pasin (const Packet & a)
References asin(), and EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS.
Referenced by Eigen::internal::scalar_asin_op< Scalar >::packetOp().
template<typename Packet > EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet Eigen::internal::patan (const Packet & a)
References atan(), and EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS.
Referenced by Eigen::internal::scalar_atan_op< Scalar >::packetOp().
template<> EIGEN_STRONG_INLINE Packet2cf Eigen::internal::pblend (const Selector< 2 > & ifPacket, const Packet2cf & thenPacket, const Packet2cf & elsePacket)
References Eigen::internal::Packet2cf::Packet2cf().
template<typename Packet > EIGEN_DEVICE_FUNC Packet Eigen::internal::pblend (const Selector< unpacket_traits< Packet >::size > & ifPacket, const Packet & thenPacket, const Packet & elsePacket) inline
template<> EIGEN_STRONG_INLINE Packet8f Eigen::internal::pblend (const Selector< 8 > & ifPacket, const Packet8f & thenPacket, const Packet8f & elsePacket)
References select(), and Eigen::internal::Selector< N >::select.
template<> EIGEN_STRONG_INLINE Packet4d Eigen::internal::pblend (const Selector< 4 > & ifPacket, const Packet4d & thenPacket, const Packet4d & elsePacket)
References select(), and Eigen::internal::Selector< N >::select.
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::pblend (const Selector< 4 > & ifPacket, const Packet4i & thenPacket, const Packet4i & elsePacket)
References select(), and Eigen::internal::Selector< N >::select.
Referenced by pabs< Packet4f >(), pblend(), pinsertfirst(), pinsertlast(), and ptranspose().
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::pblend (const Selector< 4 > & ifPacket, const Packet4f & thenPacket, const Packet4f & elsePacket)
References _EIGEN_ALIGNED_PTR, Eigen::Aligned16, Eigen::internal::packet_traits< T >::AlignedOnScalar, EIGEN_ALIGN16, EIGEN_DEBUG_ALIGNED_LOAD, EIGEN_DEBUG_ALIGNED_STORE, EIGEN_PPC_PREFETCH, EIGEN_STRONG_INLINE, first(), Eigen::internal::packet_traits< T >::HasAbs, Eigen::internal::packet_traits< T >::HasAdd, Eigen::internal::default_packet_traits::HasBlend, Eigen::internal::default_packet_traits::HasCeil, Eigen::internal::default_packet_traits::HasCos, Eigen::internal::default_packet_traits::HasDiv, Eigen::internal::default_packet_traits::HasExp, Eigen::internal::default_packet_traits::HasFloor, Eigen::internal::packet_traits< T >::HasHalfPacket, Eigen::internal::default_packet_traits::HasLog, Eigen::internal::packet_traits< T >::HasMax, Eigen::internal::packet_traits< T >::HasMin, Eigen::internal::packet_traits< T >::HasMul, Eigen::internal::packet_traits< T >::HasNegate, Eigen::internal::default_packet_traits::HasRound, Eigen::internal::default_packet_traits::HasRsqrt, Eigen::internal::default_packet_traits::HasSin, Eigen::internal::default_packet_traits::HasSqrt, Eigen::internal::packet_traits< T >::HasSub, operator<<(), p2d_COUNTDOWN, p2d_ONE, pabs(), Eigen::internal::PacketBlock< Packet, N >::packet, padd< Packet2d >(), pand< Packet2d >(), pandnot< Packet2d >(), pblend(), pbroadcast4< Packet2d >(), pceil< Packet2d >(), pconj(), pdiv< Packet2d >(), pfirst(), pfirst< Packet2d >(), pfloor< Packet2d >(), pgather< double, Packet2d >(), pload< Packet2d >(), ploaddup< Packet2d >(), ploadu< Packet2d >(), plset< Packet2d >(), pmadd(), pmax(), pmax< Packet2d >(), pmin(), pmin< Packet2d >(), pmul(), pmul< Packet2d >(), pnegate(), por< Packet2d >(), predux< Packet2d >(), predux_max< Packet2d >(), predux_min< Packet2d >(), predux_mul< Packet2d >(), preduxp< Packet2d >(), prefetch< double >(), preverse(), pround< Packet2d >(), pscatter< double, Packet2d >(), pset1< Packet2d >(), pstore< double >(), pstoreu< double >(), psub< Packet2d >(), ptranspose(), pxor< Packet2d >(), select(), Eigen::internal::Selector< N >::select, Eigen::internal::packet_traits< T >::size, and Eigen::internal::packet_traits< T >::Vectorizable.
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::pblend (const Selector< 2 > & ifPacket, const Packet2d & thenPacket, const Packet2d & elsePacket)
References select(), and Eigen::internal::Selector< N >::select.
template<> EIGEN_STRONG_INLINE Packet16f Eigen::internal::pblend (const Selector< 16 > & , const Packet16f & , const Packet16f &)
template<> EIGEN_STRONG_INLINE Packet8d Eigen::internal::pblend (const Selector< 8 > & , const Packet8d & , const Packet8d &)
template<typename Packet > EIGEN_DEVICE_FUNC void Eigen::internal::pbroadcast2 (const typename unpacket_traits< Packet >::type * a, Packet & a0, Packet & a1) inline
References EIGEN_STRONG_INLINE.
template<typename Packet > EIGEN_DEVICE_FUNC void Eigen::internal::pbroadcast4 (const typename unpacket_traits< Packet >::type * a, Packet & a0, Packet & a1, Packet & a2, Packet & a3) inline
Referenced by Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::broadcastRhs(), Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::broadcastRhs(), and Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, _ConjRhs >::broadcastRhs().
template<> EIGEN_STRONG_INLINE void Eigen::internal::pbroadcast4< Packet2d > (const double * a, Packet2d & a0, Packet2d & a1, Packet2d & a2, Packet2d & a3)
References pload< Packet2d >(), and vec2d_swizzle1.
Referenced by pblend(), and Eigen::internal::palign_impl< Offset, Packet2d >::run().
template<> EIGEN_STRONG_INLINE void Eigen::internal::pbroadcast4< Packet4f > (const float * a, Packet4f & a0, Packet4f & a1, Packet4f & a2, Packet4f & a3)
References EIGEN_STRONG_INLINE, and pload< Packet4f >().
Referenced by pabs(), and Eigen::internal::palign_impl< Offset, Packet2d >::run().
template<> EIGEN_STRONG_INLINE void Eigen::internal::pbroadcast4< Packet4i > (const int * a, Packet4i & a0, Packet4i & a1, Packet4i & a2, Packet4i & a3)
References pload< Packet4i >().
Referenced by Eigen::internal::palign_impl< Offset, Packet2d >::run().
template<typename SrcPacket , typename TgtPacket > EIGEN_DEVICE_FUNC TgtPacket Eigen::internal::pcast (const SrcPacket & a) inline
template<typename SrcPacket , typename TgtPacket > EIGEN_DEVICE_FUNC TgtPacket Eigen::internal::pcast (const SrcPacket & a, const SrcPacket &) inline
template<typename SrcPacket , typename TgtPacket > EIGEN_DEVICE_FUNC TgtPacket Eigen::internal::pcast (const SrcPacket & a, const SrcPacket & , const SrcPacket & , const SrcPacket &) inline
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::pcast< Packet2d, Packet4f > (const Packet2d & a, const Packet2d & b)
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::pcast< Packet4f, Packet2d > (const Packet4f & a)
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::pcast< Packet4f, Packet4i > (const Packet4f & a)
References Eigen::internal::type_casting_traits< Src, Tgt >::SrcCoeffRatio, Eigen::internal::type_casting_traits< Src, Tgt >::TgtCoeffRatio, and Eigen::internal::type_casting_traits< Src, Tgt >::VectorizedCast.
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::pcast< Packet4i, Packet4f > (const Packet4i & a)
template<> EIGEN_STRONG_INLINE Packet8i Eigen::internal::pcast< Packet8f, Packet8i > (const Packet8f & a)
template<> EIGEN_STRONG_INLINE Packet8f Eigen::internal::pcast< Packet8i, Packet8f > (const Packet8i & a)
template<typename Packet > EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet Eigen::internal::pceil (const Packet & a)
References ceil().
Referenced by Eigen::internal::scalar_ceil_op< Scalar >::packetOp().
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::pceil< Packet2d > (const Packet2d & a)
References EIGEN_STRONG_INLINE, pfloor< Packet4f >(), and Eigen::internal::Packet4f::v4f.
Referenced by pblend(), and pmax< Packet2d >().
template<> EIGEN_STRONG_INLINE Packet4d Eigen::internal::pceil< Packet4d > (const Packet4d & a)
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::pceil< Packet4f > (const Packet4f & a)
Referenced by pmax< Packet2d >(), and pround< Packet2d >().
template<> EIGEN_STRONG_INLINE Packet8f Eigen::internal::pceil< Packet8f > (const Packet8f & a)
template<> EIGEN_STRONG_INLINE Packet4cf Eigen::internal::pconj (const Packet4cf & a)
References Eigen::internal::Packet4cf::Packet4cf(), and Eigen::internal::Packet4cf::v.
template<> EIGEN_STRONG_INLINE Packet2cf Eigen::internal::pconj (const Packet2cf & a)
References Eigen::internal::Packet2cf::Packet2cf(), pxor< Packet4f >(), and Eigen::internal::Packet2cf::v.
Referenced by Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::acc(), Eigen::internal::scalar_conjugate_op< Scalar >::packetOp(), pblend(), Eigen::internal::conj_if< true >::pconj(), pconj(), pdiv< Packet2cd >(), pdiv< Packet4cf >(), plset< Packet4i >(), Eigen::internal::conj_helper< Packet4cf, Packet4cf, false, true >::pmul(), Eigen::internal::conj_helper< Packet4cf, Packet4cf, true, false >::pmul(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, false, true >::pmul(), Eigen::internal::conj_helper< Packet4cf, Packet4cf, true, true >::pmul(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, false >::pmul(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), Eigen::internal::conj_helper< Packet2cd, Packet2cd, false, true >::pmul(), Eigen::internal::conj_helper< Packet1cd, Packet1cd, false, true >::pmul(), Eigen::internal::conj_helper< Packet2cd, Packet2cd, true, false >::pmul(), Eigen::internal::conj_helper< Packet2cd, Packet2cd, true, true >::pmul(), Eigen::internal::conj_helper< Packet1cd, Packet1cd, true, false >::pmul(), Eigen::internal::conj_helper< Packet1cd, Packet1cd, true, true >::pmul(), pnegate(), pscatter< std::complex< double >, Packet1cd >(), ptranspose(), and Eigen::internal::palign_impl< Offset, Packet2d >::run().
template<> EIGEN_STRONG_INLINE Packet8f Eigen::internal::pconj (const Packet8f & a)
template<> EIGEN_STRONG_INLINE Packet4d Eigen::internal::pconj (const Packet4d & a)
template<> EIGEN_STRONG_INLINE Packet8i Eigen::internal::pconj (const Packet8i & a)
template<typename Packet > EIGEN_DEVICE_FUNC Packet Eigen::internal::pconj (const Packet & a) inline
template<> EIGEN_STRONG_INLINE Packet16f Eigen::internal::pconj (const Packet16f & a)
template<> EIGEN_STRONG_INLINE Packet8d Eigen::internal::pconj (const Packet8d & a)
template<> EIGEN_STRONG_INLINE Packet16i Eigen::internal::pconj (const Packet16i & a)
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::pconj (const Packet2d & a)
References EIGEN_STRONG_INLINE, pconj(), and pmul< Packet4f >().
template<> EIGEN_STRONG_INLINE Packet2cd Eigen::internal::pconj (const Packet2cd & a)
References Eigen::internal::Packet2cd::v.
template<> EIGEN_STRONG_INLINE Packet1cd Eigen::internal::pconj (const Packet1cd & a)
References Eigen::internal::Packet1cd::v.
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::pconj (const Packet4f & a)
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::pconj (const Packet4i & a)
template<typename Packet > EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet Eigen::internal::pcos (const Packet & a)
References cos(), and EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS.
Referenced by Eigen::internal::scalar_cos_op< Scalar >::packetOp().
template<> EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet4f Eigen::internal::pcos< Packet4f > (const Packet4f & _x)
References _EIGEN_DECLARE_CONST_Packet4f(), _EIGEN_DECLARE_CONST_Packet4i(), E, EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS, EIGEN_UNUSED, Eigen::half_impl::min(), pabs(), padd(), pmadd(), pmul(), pset1< Packet4f >(), psqrt< Packet4f >(), and psub().
template<typename Packet > EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet Eigen::internal::pcosh (const Packet & a)
References cosh(), and EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS.
Referenced by Eigen::internal::scalar_cosh_op< Scalar >::packetOp().
EIGEN_STRONG_INLINE Packet2cf Eigen::internal::pcplxflip (const Packet2cf & x)
References Eigen::internal::Packet2cf::Packet2cf(), and vec4f_swizzle1.
Referenced by Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::acc(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), and ptranspose().
template<typename Packet > EIGEN_DEVICE_FUNC Packet Eigen::internal::pcplxflip (const Packet & a) inline
References EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS, imag(), and real().
EIGEN_STRONG_INLINE Packet1cd Eigen::internal::pcplxflip (const Packet1cd & x)
References Eigen::internal::PacketBlock< Packet, N >::packet, preverse(), and ptranspose().
template<> EIGEN_STRONG_INLINE Packet2cd Eigen::internal::pcplxflip< Packet2cd > (const Packet2cd & x)
template<> EIGEN_STRONG_INLINE Packet2cf Eigen::internal::pcplxflip< Packet2cf > (const Packet2cf & x)
References p16uc_COMPLEX32_REV, and Eigen::internal::Packet2cf::Packet2cf().
template<> EIGEN_STRONG_INLINE Packet4cf Eigen::internal::pcplxflip< Packet4cf > (const Packet4cf & x)
References Eigen::internal::Packet4cf::Packet4cf().
template<typename Packet > EIGEN_DEVICE_FUNC Packet Eigen::internal::pdiv (const Packet & a, const Packet & b) inline
Referenced by Eigen::internal::div_assign_op< DstScalar, SrcScalar >::assignPacket(), generic_fast_tanh_float(), Eigen::internal::scalar_quotient_op< LhsScalar, RhsScalar >::packetOp(), Eigen::internal::scalar_inverse_op< Scalar >::packetOp(), pdiv< Packet2cf >(), pexp< Packet2d >(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), prsqrt(), prsqrt< Packet4f >(), and ptranspose().
template<> EIGEN_STRONG_INLINE Packet16f Eigen::internal::pdiv< Packet16f > (const Packet16f & a, const Packet16f & b)
template<> EIGEN_STRONG_INLINE Packet1cd Eigen::internal::pdiv< Packet1cd > (const Packet1cd & a, const Packet1cd & b)
References pmul(), and Eigen::internal::Packet1cd::v.
Referenced by Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), and ptranspose().
template<> EIGEN_STRONG_INLINE Packet2cd Eigen::internal::pdiv< Packet2cd > (const Packet2cd & a, const Packet2cd & b)
References pconj(), pmul(), and Eigen::internal::Packet2cd::v.
template<> EIGEN_STRONG_INLINE Packet2cf Eigen::internal::pdiv< Packet2cf > (const Packet2cf & a, const Packet2cf & b)
References p16uc_COMPLEX32_REV, Eigen::internal::Packet2cf::Packet2cf(), padd< Packet4f >(), pdiv(), pmul(), pmul< Packet4f >(), and Eigen::internal::Packet2cf::v.
Referenced by Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul().
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::pdiv< Packet2d > (const Packet2d & a, const Packet2d & b)
References EIGEN_STRONG_INLINE, padd(), pmadd(), pmin< Packet4f >(), and pmul().
Referenced by pblend(), and Eigen::internal::palign_impl< Offset, Packet2d >::run().
template<> EIGEN_STRONG_INLINE Packet4cf Eigen::internal::pdiv< Packet4cf > (const Packet4cf & a, const Packet4cf & b)
References Eigen::internal::Packet4cf::Packet4cf(), pconj(), pmul(), and Eigen::internal::Packet4cf::v.
template<> EIGEN_STRONG_INLINE Packet4d Eigen::internal::pdiv< Packet4d > (const Packet4d & a, const Packet4d & b)
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::pdiv< Packet4f > (const Packet4f & a, const Packet4f & b)
Referenced by plset< Packet4i >(), pmul< Packet2d >(), and Eigen::internal::palign_impl< Offset, Packet2d >::run().
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::pdiv< Packet4i > (const Packet4i & a, const Packet4i & b)
References eigen_assert, and pset1< Packet4i >().
Referenced by plset< Packet4i >(), and Eigen::internal::palign_impl< Offset, Packet2d >::run().
template<> EIGEN_STRONG_INLINE Packet8d Eigen::internal::pdiv< Packet8d > (const Packet8d & a, const Packet8d & b)
References EIGEN_STRONG_INLINE, and pmadd().
template<> EIGEN_STRONG_INLINE Packet8f Eigen::internal::pdiv< Packet8f > (const Packet8f & a, const Packet8f & b)
template<> EIGEN_STRONG_INLINE Packet8i Eigen::internal::pdiv< Packet8i > (const Packet8i & , const Packet8i &)
References eigen_assert, EIGEN_STRONG_INLINE, pmadd(), and pset1< Packet8i >().
template<int Mode, typename MatrixType , int DestOrder> void Eigen::internal::permute_symm_to_fullsymm (const MatrixType & mat, SparseMatrix< typename MatrixType::Scalar, DestOrder, typename MatrixType::StorageIndex > & _dest, const typename MatrixType::StorageIndex * perm = 0)
References Eigen::SparseMatrixBase< SparseMatrix< _Scalar, _Options, _StorageIndex > >::derived(), i, it, Eigen::Lower, size(), std::swap(), and Eigen::Upper.
template<int SrcMode, int DstMode, typename MatrixType , int DestOrder> void Eigen::internal::permute_symm_to_symm (const MatrixType & mat, SparseMatrix< typename MatrixType::Scalar, DestOrder, typename MatrixType::StorageIndex > & _dest, const typename MatrixType::StorageIndex * perm = 0)
template<int _SrcMode, int _DstMode, typename MatrixType , int DstOrder> void Eigen::internal::permute_symm_to_symm (const MatrixType & mat, SparseMatrix< typename MatrixType::Scalar, DstOrder, typename MatrixType::StorageIndex > & _dest, const typename MatrixType::StorageIndex * perm)
References Eigen::ColMajor, Eigen::SparseMatrixBase< SparseMatrix< _Scalar, _Options, _StorageIndex > >::derived(), i, it, Eigen::Lower, Eigen::half_impl::max(), Eigen::half_impl::min(), Eigen::RowMajor, size(), std::swap(), and Eigen::Upper.
template<typename Packet > EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet Eigen::internal::pexp (const Packet & a)
References EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS, and exp().
Referenced by Eigen::internal::scalar_exp_op< Scalar >::packetOp().
template<> EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet2d Eigen::internal::pexp< Packet2d > (const Packet2d & _x)
References _EIGEN_DECLARE_CONST_Packet2d(), EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS, EIGEN_UNUSED, pdiv(), pmadd(), pmax(), pmin(), pmul(), and psub().
Referenced by prsqrt< Packet4f >().
template<> EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet4d Eigen::internal::pexp< Packet4d > (const Packet4d & _x)
References _EIGEN_DECLARE_CONST_Packet4d, _EIGEN_DECLARE_CONST_Packet4i(), e, EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS, EIGEN_UNUSED, Eigen::half_impl::min(), pmadd(), pmax(), pmin(), pmul(), pset1< Packet8f >(), psqrt< Packet8f >(), and psub().
template<> EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet4f Eigen::internal::pexp< Packet4f > (const Packet4f & _x)
References EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS, EIGEN_UNUSED, padd(), pfloor(), pmadd(), pmax(), pmin(), pmul(), and psub().
template<> EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet8f Eigen::internal::pexp< Packet8f > (const Packet8f & _x)
References _EIGEN_DECLARE_CONST_Packet8f, E, e, EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS, EIGEN_UNUSED, m, padd(), pmadd(), pmax(), pmin(), pmul(), pshiftleft(), and psub().
template<typename Packet > EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet Eigen::internal::pexpm1 (const Packet & a)
References EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS, and expm1().
Referenced by Eigen::internal::scalar_expm1_op< Scalar >::packetOp().
template<typename Packet > EIGEN_DEVICE_FUNC unpacket_traits<Packet>::type Eigen::internal::pfirst (const Packet & a) inline
Referenced by pabs< Packet4f >(), pblend(), pfirst< Packet4cf >(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), predux< Packet1cd >(), predux< Packet2d >(), predux< Packet4f >(), predux< Packet4i >(), predux_max< Packet16f >(), predux_max< Packet4d >(), predux_max< Packet4f >(), predux_max< Packet4i >(), predux_max< Packet8d >(), predux_max< Packet8f >(), predux_min< Packet16f >(), predux_min< Packet4d >(), predux_min< Packet4f >(), predux_min< Packet4i >(), predux_min< Packet8d >(), predux_min< Packet8f >(), predux_mul< Packet16f >(), predux_mul< Packet1cd >(), predux_mul< Packet4d >(), predux_mul< Packet4f >(), predux_mul< Packet8d >(), predux_mul< Packet8f >(), pscatter< std::complex< double >, Packet1cd >(), ptranspose(), and Eigen::numext::sqrt().
template<> EIGEN_STRONG_INLINE float Eigen::internal::pfirst< Packet16f > (const Packet16f & a)
template<> EIGEN_STRONG_INLINE int Eigen::internal::pfirst< Packet16i > (const Packet16i & a)
template<> EIGEN_STRONG_INLINE std::complex< double > Eigen::internal::pfirst< Packet1cd > (const Packet1cd & a)
References EIGEN_ALIGN16.
Referenced by Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), pscatter< std::complex< double >, Packet1cd >(), and ptranspose().
template<> EIGEN_STRONG_INLINE std::complex<double> Eigen::internal::pfirst< Packet2cd > (const Packet2cd & a)
References EIGEN_ALIGN16.
template<> EIGEN_STRONG_INLINE std::complex< float > Eigen::internal::pfirst< Packet2cf > (const Packet2cf & a)
References EIGEN_ALIGN16, and pstore().
Referenced by predux< Packet2cf >(), predux_mul< Packet2cf >(), and pscatter< std::complex< double >, Packet1cd >().
template<> EIGEN_STRONG_INLINE double Eigen::internal::pfirst< Packet2d > (const Packet2d & a)
References EIGEN_STRONG_INLINE, pfirst< Packet4i >(), and preverse().
Referenced by pblend(), pfloor< Packet2d >(), predux< Packet2d >(), predux_max< Packet2d >(), predux_min< Packet2d >(), predux_mul< Packet2d >(), and pstore1< Packet2d >().
template<> EIGEN_STRONG_INLINE std::complex<float> Eigen::internal::pfirst< Packet4cf > (const Packet4cf & a)
References pfirst().
template<> EIGEN_STRONG_INLINE double Eigen::internal::pfirst< Packet4d > (const Packet4d & a)
template<> EIGEN_STRONG_INLINE float Eigen::internal::pfirst< Packet4f > (const Packet4f & a)
References EIGEN_ALIGN16.
Referenced by pfloor< Packet2d >(), predux< Packet2d >(), predux_min< Packet2d >(), predux_mul< Packet2d >(), preduxp< Packet2d >(), prefetch< int32_t >(), and pstore1< Packet2d >().
template<> EIGEN_STRONG_INLINE int32_t Eigen::internal::pfirst< Packet4i > (const Packet4i & a)
References EIGEN_ALIGN16, EIGEN_STRONG_INLINE, pabs(), predux< Packet4f >(), preduxp< Packet4f >(), and preverse().
template<> EIGEN_STRONG_INLINE int Eigen::internal::pfirst< Packet4i > (const Packet4i & a)
References EIGEN_ALIGN16.
Referenced by pfirst< Packet2d >(), pfloor< Packet2d >(), predux< Packet2d >(), predux_max< Packet2d >(), predux_min< Packet2d >(), and pstore1< Packet2d >().
template<> EIGEN_STRONG_INLINE double Eigen::internal::pfirst< Packet8d > (const Packet8d & a)
template<> EIGEN_STRONG_INLINE float Eigen::internal::pfirst< Packet8f > (const Packet8f & a)
template<> EIGEN_STRONG_INLINE int Eigen::internal::pfirst< Packet8i > (const Packet8i & a)
template<typename Packet > EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet Eigen::internal::pfloor (const Packet & a)
References EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS, and floor().
Referenced by Eigen::internal::scalar_floor_op< Scalar >::packetOp(), pexp< Packet4f >(), and prsqrt< Packet4f >().
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::pfloor< Packet2d > (const Packet2d & a)
References EIGEN_ALIGN16, EIGEN_STRONG_INLINE, EIGEN_ZVECTOR_PREFETCH, pfirst< Packet2d >(), pfirst< Packet4f >(), pfirst< Packet4i >(), pload< Packet2d >(), pload< Packet4f >(), pload< Packet4i >(), ploaddup< Packet2d >(), ploaddup< Packet4f >(), ploaddup< Packet4i >(), ploadu< Packet2d >(), ploadu< Packet4f >(), ploadu< Packet4i >(), prefetch< double >(), prefetch< float >(), prefetch< int >(), preverse(), pstore(), pstore< double >(), pstore< float >(), pstore< int >(), pstoreu< double >(), pstoreu< float >(), pstoreu< int >(), and Eigen::internal::Packet4f::v4f.
Referenced by pblend(), and pmax< Packet2d >().
template<> EIGEN_STRONG_INLINE Packet4d Eigen::internal::pfloor< Packet4d > (const Packet4d & a)
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::pfloor< Packet4f > (const Packet4f & a)
References EIGEN_DEBUG_ALIGNED_LOAD, EIGEN_STRONG_INLINE, ploadu< Packet4f >(), and ploadu< Packet4i >().
Referenced by pceil< Packet2d >(), and pmax< Packet2d >().
template<> EIGEN_STRONG_INLINE Packet8f Eigen::internal::pfloor< Packet8f > (const Packet8f & a)
template<typename Scalar , typename Packet > EIGEN_DEVICE_FUNC Packet Eigen::internal::pgather (const Scalar * from, Index) inline
template<> EIGEN_DEVICE_FUNC Packet2d Eigen::internal::pgather< double, Packet2d > (const double * from, Index stride) inline
References pgather< int, Packet4i >(), and pscatter< float, Packet4f >().
Referenced by pblend(), and Eigen::internal::palign_impl< Offset, Packet2d >::run().
template<> EIGEN_DEVICE_FUNC Packet4d Eigen::internal::pgather< double, Packet4d > (const double * from, Index stride) inline
template<> EIGEN_DEVICE_FUNC Packet8d Eigen::internal::pgather< double, Packet8d > (const double * from, Index stride) inline
template<> EIGEN_DEVICE_FUNC Packet16f Eigen::internal::pgather< float, Packet16f > (const float * from, Index stride) inline
template<> EIGEN_DEVICE_FUNC Packet4f Eigen::internal::pgather< float, Packet4f > (const float * from, Index stride) inline
References EIGEN_ALIGN16, and pload< Packet4f >().
Referenced by pstoreu< double >(), pstoreu< int32_t >(), and Eigen::internal::palign_impl< Offset, Packet2d >::run().
template<> EIGEN_DEVICE_FUNC Packet8f Eigen::internal::pgather< float, Packet8f > (const float * from, Index stride) inline
template<> EIGEN_DEVICE_FUNC Packet4i Eigen::internal::pgather< int, Packet4i > (const int * from, Index stride) inline
References EIGEN_ALIGN16, and pload< Packet4i >().
Referenced by pgather< double, Packet2d >(), and Eigen::internal::palign_impl< Offset, Packet2d >::run().
template<> EIGEN_DEVICE_FUNC Packet4i Eigen::internal::pgather< int32_t, Packet4i > (const int32_t * from, Index stride) inline
References pscatter< float, Packet4f >(), and pset1< Packet4i >().
template<> EIGEN_DEVICE_FUNC Packet1cd Eigen::internal::pgather< std::complex< double >, Packet1cd > (const std::complex< double > * from, Index stride EIGEN_UNUSED) inline
References EIGEN_ALIGN16, and pload< Packet1cd >().
template<> EIGEN_DEVICE_FUNC Packet2cd Eigen::internal::pgather< std::complex< double >, Packet2cd > (const std::complex< double > * from, Index stride) inline
References imag(), and real().
template<> EIGEN_DEVICE_FUNC Packet2cf Eigen::internal::pgather< std::complex< float >, Packet2cf > (const std::complex< float > * from, Index stride) inline
References EIGEN_ALIGN16, and pload< Packet2cf >().
template<> EIGEN_DEVICE_FUNC Packet4cf Eigen::internal::pgather< std::complex< float >, Packet4cf > (const std::complex< float > * from, Index stride) inline
References imag(), Eigen::internal::Packet4cf::Packet4cf(), and real().
template<> EIGEN_STRONG_INLINE Packet4cf Eigen::internal::pinsertfirst (const Packet4cf & a, std::complex< float > b)
References Eigen::internal::Packet4cf::Packet4cf(), pset1< Packet4cf >(), and Eigen::internal::Packet4cf::v.
Referenced by Eigen::internal::linspaced_op_impl< Scalar, Packet, false >::packetOp().
template<> EIGEN_STRONG_INLINE Packet2cd Eigen::internal::pinsertfirst (const Packet2cd & a, std::complex< double > b)
References pset1< Packet2cd >(), and Eigen::internal::Packet2cd::v.
template<> EIGEN_STRONG_INLINE Packet2cf Eigen::internal::pinsertfirst (const Packet2cf & a, std::complex< float > b)
References Eigen::internal::Packet2cf::Packet2cf().
template<> EIGEN_STRONG_INLINE Packet1cd Eigen::internal::pinsertfirst (const Packet1cd & , std::complex< double > b)
References pset1< Packet1cd >().
template<typename Packet > EIGEN_DEVICE_FUNC Packet Eigen::internal::pinsertfirst (const Packet & a, typename unpacket_traits< Packet >::type b) inline
References i, pblend(), Eigen::internal::Selector< N >::select, and size().
template<> EIGEN_STRONG_INLINE Packet8f Eigen::internal::pinsertfirst (const Packet8f & a, float b)
References pset1< Packet8f >().
template<> EIGEN_STRONG_INLINE Packet4d Eigen::internal::pinsertfirst (const Packet4d & a, double b)
References pset1< Packet4d >().
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::pinsertfirst (const Packet4f & a, float b)
References pset1< Packet4f >().
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::pinsertfirst (const Packet2d & a, double b)
References pset1< Packet2d >().
template<> EIGEN_STRONG_INLINE Packet4cf Eigen::internal::pinsertlast (const Packet4cf & a, std::complex< float > b)
References Eigen::internal::Packet4cf::Packet4cf(), pset1< Packet4cf >(), and Eigen::internal::Packet4cf::v.
Referenced by Eigen::internal::linspaced_op_impl< Scalar, Packet, false >::packetOp().
template<> EIGEN_STRONG_INLINE Packet2cd Eigen::internal::pinsertlast (const Packet2cd & a, std::complex< double > b)
References pset1< Packet2cd >(), and Eigen::internal::Packet2cd::v.
template<> EIGEN_STRONG_INLINE Packet2cf Eigen::internal::pinsertlast (const Packet2cf & a, std::complex< float > b)
References Eigen::internal::Packet2cf::Packet2cf().
template<> EIGEN_STRONG_INLINE Packet1cd Eigen::internal::pinsertlast (const Packet1cd & , std::complex< double > b)
References pset1< Packet1cd >().
template<typename Packet > EIGEN_DEVICE_FUNC Packet Eigen::internal::pinsertlast (const Packet & a, typename unpacket_traits< Packet >::type b) inline
References i, pblend(), Eigen::internal::Selector< N >::select, and size().
template<> EIGEN_STRONG_INLINE Packet8f Eigen::internal::pinsertlast (const Packet8f & a, float b)
References pset1< Packet8f >().
template<> EIGEN_STRONG_INLINE Packet4d Eigen::internal::pinsertlast (const Packet4d & a, double b)
References pset1< Packet4d >().
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::pinsertlast (const Packet4f & a, float b)
References pset1< Packet4f >().
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::pinsertlast (const Packet2d & a, double b)
References EIGEN_STRONG_INLINE, pmadd(), and pset1< Packet2d >().
template<typename Packet > EIGEN_DEVICE_FUNC Packet Eigen::internal::pload (const typename unpacket_traits< Packet >::type * from) inline
template<typename Packet > EIGEN_DEVICE_FUNC Packet Eigen::internal::pload1 (const typename unpacket_traits< Packet >::type * a) inline
References EIGEN_STRONG_INLINE.
template<> EIGEN_STRONG_INLINE Packet16f Eigen::internal::pload1< Packet16f > (const float * from)
template<> EIGEN_STRONG_INLINE Packet4d Eigen::internal::pload1< Packet4d > (const double * from)
template<> EIGEN_STRONG_INLINE Packet8d Eigen::internal::pload1< Packet8d > (const double * from)
template<> EIGEN_STRONG_INLINE Packet8f Eigen::internal::pload1< Packet8f > (const float * from)
template<> EIGEN_STRONG_INLINE Packet16f Eigen::internal::pload< Packet16f > (const float * from)
References EIGEN_DEBUG_ALIGNED_LOAD.
template<> EIGEN_STRONG_INLINE Packet16i Eigen::internal::pload< Packet16i > (const int * from)
References EIGEN_DEBUG_ALIGNED_LOAD.
template<> EIGEN_STRONG_INLINE Packet1cd Eigen::internal::pload< Packet1cd > (const std::complex< double > * from)
References EIGEN_DEBUG_ALIGNED_LOAD, and pload< Packet2d >().
Referenced by pgather< std::complex< double >, Packet1cd >(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), and ptranspose().
template<> EIGEN_STRONG_INLINE Packet2cd Eigen::internal::pload< Packet2cd > (const std::complex< double > * from)
References EIGEN_DEBUG_ALIGNED_LOAD, and pload< Packet4d >().
template<> EIGEN_STRONG_INLINE Packet2cf Eigen::internal::pload< Packet2cf > (const std::complex< float > * from)
References Eigen::internal::Packet2cf::Packet2cf(), and pload< Packet4f >().
Referenced by pgather< std::complex< float >, Packet2cf >().
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::pload< Packet2d > (const double * from)
References EIGEN_DEBUG_ALIGNED_LOAD, EIGEN_DEBUG_UNALIGNED_LOAD, EIGEN_STRONG_INLINE, pload< Packet4i >(), and ploadu< Packet4f >().
Referenced by pblend(), pbroadcast4< Packet2d >(), pfloor< Packet2d >(), pload< Packet1cd >(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), ptranspose(), and Eigen::internal::palign_impl< Offset, Packet2d >::run().
template<> EIGEN_STRONG_INLINE Packet4cf Eigen::internal::pload< Packet4cf > (const std::complex< float > * from)
References EIGEN_DEBUG_ALIGNED_LOAD, Eigen::internal::Packet4cf::Packet4cf(), and pload< Packet8f >().
template<> EIGEN_STRONG_INLINE Packet4d Eigen::internal::pload< Packet4d > (const double * from)
References EIGEN_DEBUG_ALIGNED_LOAD.
Referenced by pload< Packet2cd >().
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::pload< Packet4f > (const float * from)
References EIGEN_DEBUG_ALIGNED_LOAD.
Referenced by pabs(), pandnot< Packet2d >(), pbroadcast4< Packet4f >(), pfloor< Packet2d >(), pgather< float, Packet4f >(), pload< Packet2cf >(), ploaddup< Packet4f >(), plset< Packet4i >(), pset1< Packet2cf >(), and Eigen::internal::palign_impl< Offset, Packet2d >::run().
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::pload< Packet4i > (const int32_t * from)
References EIGEN_DEBUG_ALIGNED_LOAD, EIGEN_DEBUG_UNALIGNED_LOAD, EIGEN_STRONG_INLINE, and ploadu< Packet4f >().
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::pload< Packet4i > (const int * from)
References EIGEN_DEBUG_ALIGNED_LOAD.
Referenced by pbroadcast4< Packet4i >(), pfloor< Packet2d >(), pgather< int, Packet4i >(), pload< Packet2d >(), ploaddup< Packet4i >(), and Eigen::internal::palign_impl< Offset, Packet2d >::run().
template<> EIGEN_STRONG_INLINE Packet8d Eigen::internal::pload< Packet8d > (const double * from)
References EIGEN_DEBUG_ALIGNED_LOAD.
template<> EIGEN_STRONG_INLINE Packet8f Eigen::internal::pload< Packet8f > (const float * from)
References EIGEN_DEBUG_ALIGNED_LOAD.
Referenced by pload< Packet4cf >().
template<> EIGEN_STRONG_INLINE Packet8i Eigen::internal::pload< Packet8i > (const int * from)
References EIGEN_DEBUG_ALIGNED_LOAD.
template<typename Packet > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet Eigen::internal::ploaddup (const typename unpacket_traits< Packet >::type * from)
template<> EIGEN_STRONG_INLINE Packet16f Eigen::internal::ploaddup< Packet16f > (const float * from)
template<> EIGEN_STRONG_INLINE Packet1cd Eigen::internal::ploaddup< Packet1cd > (const std::complex< double > * from)
References pset1< Packet1cd >().
Referenced by Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), pscatter< std::complex< double >, Packet1cd >(), and ptranspose().
template<> EIGEN_STRONG_INLINE Packet2cd Eigen::internal::ploaddup< Packet2cd > (const std::complex< double > * from)
References pset1< Packet2cd >().
template<> EIGEN_STRONG_INLINE Packet2cf Eigen::internal::ploaddup< Packet2cf > (const std::complex< float > * from)
References pset1< Packet2cf >().
Referenced by ploaddup< Packet4cf >(), and pscatter< std::complex< double >, Packet1cd >().
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::ploaddup< Packet2d > (const double * from)
References EIGEN_DEBUG_ALIGNED_STORE, EIGEN_STRONG_INLINE, ploaddup< Packet4i >(), pset1< Packet2d >(), pstore< float >(), and vec4i_swizzle1.
Referenced by pblend(), and pfloor< Packet2d >().
template<> EIGEN_STRONG_INLINE Packet4cf Eigen::internal::ploaddup< Packet4cf > (const std::complex< float > * from)
References Eigen::internal::Packet4cf::Packet4cf(), ploaddup< Packet2cf >(), and Eigen::internal::Packet2cf::v.
template<> EIGEN_STRONG_INLINE Packet4d Eigen::internal::ploaddup< Packet4d > (const double * from)
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::ploaddup< Packet4f > (const float * from)
References pload< Packet4f >(), and ploadu< Packet4f >().
Referenced by pfloor< Packet2d >(), ploadu< Packet2d >(), and ploadu< Packet4i >().
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::ploaddup< Packet4i > (const int32_t * from)
References EIGEN_DEBUG_ALIGNED_STORE, EIGEN_STRONG_INLINE, and pstore< float >().
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::ploaddup< Packet4i > (const int * from)
References EIGEN_DEBUG_UNALIGNED_STORE, EIGEN_STRONG_INLINE, pload< Packet4i >(), ploadu< Packet4i >(), pstoreu< float >(), and pstoreu< int >().
Referenced by pfloor< Packet2d >(), and ploaddup< Packet2d >().
template<> EIGEN_STRONG_INLINE Packet8d Eigen::internal::ploaddup< Packet8d > (const double * from)
template<> EIGEN_STRONG_INLINE Packet8f Eigen::internal::ploaddup< Packet8f > (const float * from)
template<typename Packet > EIGEN_DEVICE_FUNC Packet Eigen::internal::ploadquad (const typename unpacket_traits< Packet >::type * from) inline
template<> EIGEN_STRONG_INLINE Packet16f Eigen::internal::ploadquad< Packet16f > (const float * from)
template<> EIGEN_STRONG_INLINE Packet8d Eigen::internal::ploadquad< Packet8d > (const double * from)
template<> EIGEN_STRONG_INLINE Packet8f Eigen::internal::ploadquad< Packet8f > (const float * from)
template<typename Packet , int Alignment> EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE Packet Eigen::internal::ploadt (const typename unpacket_traits< Packet >::type * from)
template<typename Packet , int LoadMode> EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE Packet Eigen::internal::ploadt_ro (const typename unpacket_traits< Packet >::type * from)
template<typename Packet > EIGEN_DEVICE_FUNC Packet Eigen::internal::ploadu (const typename unpacket_traits< Packet >::type * from) inline
template<> EIGEN_STRONG_INLINE Packet16f Eigen::internal::ploadu< Packet16f > (const float * from)
References EIGEN_DEBUG_UNALIGNED_LOAD.
template<> EIGEN_STRONG_INLINE Packet16i Eigen::internal::ploadu< Packet16i > (const int * from)
References EIGEN_DEBUG_UNALIGNED_LOAD.
template<> EIGEN_STRONG_INLINE Packet1cd Eigen::internal::ploadu< Packet1cd > (const std::complex< double > * from)
References EIGEN_DEBUG_UNALIGNED_LOAD, and ploadu< Packet2d >().
Referenced by Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), pset1< Packet1cd >(), and ptranspose().
template<> EIGEN_STRONG_INLINE Packet2cd Eigen::internal::ploadu< Packet2cd > (const std::complex< double > * from)
References EIGEN_DEBUG_UNALIGNED_LOAD, and ploadu< Packet4d >().
template<> EIGEN_STRONG_INLINE Packet2cf Eigen::internal::ploadu< Packet2cf > (const std::complex< float > * from)
References Eigen::internal::Packet2cf::Packet2cf(), and ploadu< Packet4f >().
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::ploadu< Packet2d > (const double * from)
References EIGEN_DEBUG_UNALIGNED_LOAD, EIGEN_STRONG_INLINE, ploaddup< Packet4f >(), ploadu< Packet4i >(), and vec4f_swizzle1.
Referenced by pblend(), pfloor< Packet2d >(), ploadu< Packet1cd >(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), and ptranspose().
template<> EIGEN_STRONG_INLINE Packet4cf Eigen::internal::ploadu< Packet4cf > (const std::complex< float > * from)
References EIGEN_DEBUG_UNALIGNED_LOAD, Eigen::internal::Packet4cf::Packet4cf(), and ploadu< Packet8f >().
template<> EIGEN_STRONG_INLINE Packet4d Eigen::internal::ploadu< Packet4d > (const double * from)
References EIGEN_DEBUG_UNALIGNED_LOAD.
Referenced by ploadu< Packet2cd >().
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::ploadu< Packet4f > (const float * from)
References _EIGEN_ALIGNED_PTR, and EIGEN_DEBUG_UNALIGNED_LOAD.
Referenced by pfloor< Packet2d >(), pfloor< Packet4f >(), pload< Packet2d >(), pload< Packet4i >(), ploaddup< Packet4f >(), ploadu< Packet2cf >(), and pset1< Packet2cf >().
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::ploadu< Packet4i > (const int32_t * from)
References EIGEN_DEBUG_UNALIGNED_LOAD, EIGEN_STRONG_INLINE, and ploaddup< Packet4f >().
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::ploadu< Packet4i > (const int * from)
References _EIGEN_ALIGNED_PTR, and EIGEN_DEBUG_UNALIGNED_LOAD.
Referenced by pfloor< Packet2d >(), pfloor< Packet4f >(), ploaddup< Packet4i >(), and ploadu< Packet2d >().
template<> EIGEN_STRONG_INLINE Packet8d Eigen::internal::ploadu< Packet8d > (const double * from)
References EIGEN_DEBUG_UNALIGNED_LOAD.
template<> EIGEN_STRONG_INLINE Packet8f Eigen::internal::ploadu< Packet8f > (const float * from)
References EIGEN_DEBUG_UNALIGNED_LOAD.
Referenced by ploadu< Packet4cf >().
template<> EIGEN_STRONG_INLINE Packet8i Eigen::internal::ploadu< Packet8i > (const int * from)
References EIGEN_DEBUG_UNALIGNED_LOAD.
template<typename Packet > EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet Eigen::internal::plog (const Packet & a)
References EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS, and log().
Referenced by Eigen::internal::scalar_log_op< Scalar >::packetOp().
template<typename Packet > EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet Eigen::internal::plog10 (const Packet & a)
References EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS, and log10().
Referenced by Eigen::internal::scalar_log10_op< Scalar >::packetOp().
template<typename Packet > EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet Eigen::internal::plog1p (const Packet & a)
References EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS, and log1p().
Referenced by Eigen::internal::scalar_log1p_op< Scalar >::packetOp().
template<> EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet4f Eigen::internal::plog< Packet4f > (const Packet4f & _x)
References e, EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS, EIGEN_UNUSED, padd(), pand(), pmadd(), pmax(), pmul(), por(), and psub().
template<> EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet8f Eigen::internal::plog< Packet8f > (const Packet8f & _x)
References _EIGEN_DECLARE_CONST_Packet8f, _EIGEN_DECLARE_CONST_Packet8f_FROM_INT, E, e, EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS, EIGEN_UNUSED, padd(), pmadd(), pmax(), pmul(), pshiftright(), and psub().
template<typename Packet > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet Eigen::internal::plset (const typename unpacket_traits< Packet >::type & a)
template<> EIGEN_STRONG_INLINE Packet16f Eigen::internal::plset< Packet16f > (const float & a)
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::plset< Packet2d > (const double & a)
References EIGEN_STRONG_INLINE, padd< Packet4f >(), plset< Packet4i >(), pset1< Packet2d >(), and pset1< Packet4i >().
Referenced by pblend(), and pmadd().
template<> EIGEN_STRONG_INLINE Packet4d Eigen::internal::plset< Packet4d > (const double & a)
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::plset< Packet4f > (const float & a)
References pset1< Packet4f >().
Referenced by pmadd(), pset1< Packet2d >(), and pset1< Packet4i >().
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::plset< Packet4i > (const int32_t & a)
References eigen_assert, EIGEN_DEBUG_ALIGNED_LOAD, EIGEN_STRONG_INLINE, i, padd< Packet4f >(), padd< Packet4i >(), pand< Packet4f >(), pand< Packet4i >(), pandnot< Packet4f >(), pandnot< Packet4i >(), pconj(), pdiv< Packet4f >(), pdiv< Packet4i >(), pload< Packet4f >(), pmadd(), pmax< Packet4f >(), pmax< Packet4i >(), pmin< Packet4f >(), pmin< Packet4i >(), pmul< Packet4f >(), pmul< Packet4i >(), pnegate(), por< Packet4f >(), por< Packet4i >(), pset1< Packet4i >(), psub< Packet4f >(), psub< Packet4i >(), pxor< Packet4f >(), and pxor< Packet4i >().
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::plset< Packet4i > (const int & a)
References pset1< Packet4i >().
Referenced by plset< Packet2d >(), and pmadd().
template<> EIGEN_STRONG_INLINE Packet8d Eigen::internal::plset< Packet8d > (const double & a)
template<> EIGEN_STRONG_INLINE Packet8f Eigen::internal::plset< Packet8f > (const float & a)
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::pmadd (const Packet4f & a, const Packet4f & b, const Packet4f & c)
Referenced by Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::acc(), Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::acc(), generic_fast_tanh_float(), Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::madd_impl(), Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, _ConjRhs >::madd_impl(), pblend(), pcos< Packet4f >(), pdiv< Packet2d >(), pdiv< Packet8d >(), pdiv< Packet8i >(), pexp< Packet2d >(), pexp< Packet4d >(), pexp< Packet4f >(), pexp< Packet8f >(), pinsertlast(), plog< Packet4f >(), plog< Packet8f >(), plset< Packet4i >(), Eigen::internal::conj_helper< Scalar, Scalar, false, false >::pmadd(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), prsqrt< Packet4f >(), psin< Packet4f >(), psin< Packet8f >(), psqrt< Packet2d >(), psqrt< Packet4d >(), ptranspose(), Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, ColMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::run(), Eigen::internal::palign_impl< Offset, Packet2d >::run(), Eigen::internal::etor_product_packet_impl< RowMajor, UnrollingIndex, Lhs, Rhs, Packet, LoadMode >::run(), Eigen::internal::etor_product_packet_impl< ColMajor, UnrollingIndex, Lhs, Rhs, Packet, LoadMode >::run(), Eigen::internal::etor_product_packet_impl< RowMajor, Dynamic, Lhs, Rhs, Packet, LoadMode >::run(), and Eigen::internal::etor_product_packet_impl< ColMajor, Dynamic, Lhs, Rhs, Packet, LoadMode >::run().
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::pmadd (const Packet4i & a, const Packet4i & b, const Packet4i & c)
template<typename Packet > EIGEN_DEVICE_FUNC Packet Eigen::internal::pmadd (const Packet & a, const Packet & b, const Packet & c) inline
References padd(), and pmul().
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::pmadd (const Packet2d & a, const Packet2d & b, const Packet2d & c)
References EIGEN_STRONG_INLINE, padd< Packet2d >(), padd< Packet4f >(), padd< Packet4i >(), pand(), pand< Packet2d >(), pand< Packet4f >(), pand< Packet4i >(), pandnot(), pandnot< Packet2d >(), pandnot< Packet4f >(), pandnot< Packet4i >(), plset< Packet2d >(), plset< Packet4f >(), plset< Packet4i >(), pmax(), pmax< Packet2d >(), pmax< Packet4f >(), pmax< Packet4i >(), pmin(), pmin< Packet2d >(), pmin< Packet4f >(), pmin< Packet4i >(), por< Packet2d >(), por< Packet4f >(), por< Packet4i >(), pround< Packet4f >(), pset1< Packet2d >(), pset1< Packet4f >(), pset1< Packet4i >(), pxor< Packet2d >(), pxor< Packet4f >(), pxor< Packet4i >(), and Eigen::internal::Packet4f::v4f.
template<typename Packet > EIGEN_DEVICE_FUNC Packet Eigen::internal::pmax (const Packet & a, const Packet & b) inline
Referenced by generic_fast_tanh_float(), Eigen::internal::scalar_max_op< LhsScalar, RhsScalar >::packetOp(), pblend(), pexp< Packet2d >(), pexp< Packet4d >(), pexp< Packet4f >(), pexp< Packet8f >(), plog< Packet4f >(), plog< Packet8f >(), pmadd(), and prsqrt< Packet4f >().
template<> EIGEN_STRONG_INLINE Packet16f Eigen::internal::pmax< Packet16f > (const Packet16f & a, const Packet16f & b)
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::pmax< Packet2d > (const Packet2d & a, const Packet2d & b)
References EIGEN_STRONG_INLINE, pand< Packet4f >(), pceil< Packet2d >(), pceil< Packet4f >(), pfloor< Packet2d >(), pfloor< Packet4f >(), pmax< Packet4i >(), pround< Packet2d >(), and pround< Packet4f >().
Referenced by pabs< Packet4f >(), pblend(), and pmadd().
template<> EIGEN_STRONG_INLINE Packet4d Eigen::internal::pmax< Packet4d > (const Packet4d & a, const Packet4d & b)
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::pmax< Packet4f > (const Packet4f & a, const Packet4f & b)
Referenced by plset< Packet4i >(), pmadd(), and pmin< Packet2d >().
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::pmax< Packet4i > (const Packet4i & a, const Packet4i & b)
Referenced by pabs< Packet4f >(), plset< Packet4i >(), pmadd(), and pmax< Packet2d >().
template<> EIGEN_STRONG_INLINE Packet8d Eigen::internal::pmax< Packet8d > (const Packet8d & a, const Packet8d & b)
template<> EIGEN_STRONG_INLINE Packet8f Eigen::internal::pmax< Packet8f > (const Packet8f & a, const Packet8f & b)
template<typename Packet > EIGEN_DEVICE_FUNC Packet Eigen::internal::pmin (const Packet & a, const Packet & b) inline
Referenced by generic_fast_tanh_float(), Eigen::internal::scalar_min_op< LhsScalar, RhsScalar >::packetOp(), pblend(), pexp< Packet2d >(), pexp< Packet4d >(), pexp< Packet4f >(), pexp< Packet8f >(), pmadd(), and prsqrt< Packet4f >().
template<> EIGEN_STRONG_INLINE Packet16f Eigen::internal::pmin< Packet16f > (const Packet16f & a, const Packet16f & b)
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::pmin< Packet2d > (const Packet2d & a, const Packet2d & b)
References EIGEN_STRONG_INLINE, pmax< Packet4f >(), and pmin< Packet4i >().
Referenced by pabs< Packet4f >(), pblend(), and pmadd().
template<> EIGEN_STRONG_INLINE Packet4d Eigen::internal::pmin< Packet4d > (const Packet4d & a, const Packet4d & b)
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::pmin< Packet4f > (const Packet4f & a, const Packet4f & b)
Referenced by pdiv< Packet2d >(), plset< Packet4i >(), and pmadd().
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::pmin< Packet4i > (const Packet4i & a, const Packet4i & b)
Referenced by pabs< Packet4f >(), plset< Packet4i >(), pmadd(), and pmin< Packet2d >().
template<> EIGEN_STRONG_INLINE Packet8d Eigen::internal::pmin< Packet8d > (const Packet8d & a, const Packet8d & b)
template<> EIGEN_STRONG_INLINE Packet8f Eigen::internal::pmin< Packet8f > (const Packet8f & a, const Packet8f & b)
template<typename Packet > EIGEN_DEVICE_FUNC Packet Eigen::internal::pmul (const Packet & a, const Packet & b) inline
Referenced by Eigen::internal::mul_assign_op< DstScalar, SrcScalar >::assignPacket(), generic_fast_tanh_float(), Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::madd(), Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::madd_impl(), Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, _ConjRhs >::madd_impl(), Eigen::internal::scalar_conj_product_op< LhsScalar, RhsScalar >::operator()(), pabs< Packet4f >(), Eigen::internal::diagonal_product_evaluator_base< Lhs, Rhs::DiagonalVectorType, Product< Lhs, Rhs, LazyProduct >, OnTheRight >::packet_impl(), Eigen::internal::linspaced_op_impl< Scalar, Packet, false >::packetOp(), Eigen::internal::scalar_product_op< LhsScalar, RhsScalar >::packetOp(), Eigen::internal::scalar_abs2_op< Scalar >::packetOp(), Eigen::internal::scalar_conj_product_op< LhsScalar, RhsScalar >::packetOp(), Eigen::internal::scalar_square_op< Scalar >::packetOp(), Eigen::internal::scalar_cube_op< Scalar >::packetOp(), pblend(), pcos< Packet4f >(), pdiv< Packet1cd >(), pdiv< Packet2cd >(), pdiv< Packet2cf >(), pdiv< Packet2d >(), pdiv< Packet4cf >(), pexp< Packet2d >(), pexp< Packet4d >(), pexp< Packet4f >(), pexp< Packet8f >(), plog< Packet4f >(), plog< Packet8f >(), Eigen::internal::conj_helper< Eigen::internal::true_type, Eigen::internal::true_type, ConjLhs, false >::pmadd(), Eigen::internal::conj_helper< std::complex< RealScalar >, std::complex< RealScalar >, false, true >::pmadd(), Eigen::internal::conj_helper< std::complex< RealScalar >, std::complex< RealScalar >, true, false >::pmadd(), Eigen::internal::conj_helper< std::complex< RealScalar >, std::complex< RealScalar >, true, true >::pmadd(), Eigen::internal::conj_helper< std::complex< RealScalar >, RealScalar, Conj, false >::pmadd(), Eigen::internal::conj_helper< RealScalar, std::complex< RealScalar >, false, Conj >::pmadd(), Eigen::internal::conj_helper< Packet4cf, Packet4cf, false, true >::pmadd(), Eigen::internal::conj_helper< Packet4cf, Packet4cf, true, false >::pmadd(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, false, true >::pmadd(), Eigen::internal::conj_helper< Packet4cf, Packet4cf, true, true >::pmadd(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, false >::pmadd(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmadd(), Eigen::internal::conj_helper< Packet2cd, Packet2cd, false, true >::pmadd(), Eigen::internal::conj_helper< Packet1cd, Packet1cd, false, true >::pmadd(), Eigen::internal::conj_helper< Packet2cd, Packet2cd, true, false >::pmadd(), Eigen::internal::conj_helper< Packet2cd, Packet2cd, true, true >::pmadd(), Eigen::internal::conj_helper< Packet1cd, Packet1cd, true, false >::pmadd(), Eigen::internal::conj_helper< Packet1cd, Packet1cd, true, true >::pmadd(), pmadd(), Eigen::internal::conj_helper< Scalar, Scalar, false, false >::pmul(), Eigen::internal::conj_helper< Packet4cf, Packet4cf, false, true >::pmul(), Eigen::internal::conj_helper< Packet4cf, Packet4cf, true, false >::pmul(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, false, true >::pmul(), Eigen::internal::conj_helper< Packet4cf, Packet4cf, true, true >::pmul(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, false >::pmul(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), Eigen::internal::conj_helper< Packet2cd, Packet2cd, false, true >::pmul(), Eigen::internal::conj_helper< Packet1cd, Packet1cd, false, true >::pmul(), Eigen::internal::conj_helper< Packet2cd, Packet2cd, true, false >::pmul(), Eigen::internal::conj_helper< Packet2cd, Packet2cd, true, true >::pmul(), Eigen::internal::conj_helper< Packet1cd, Packet1cd, true, false >::pmul(), Eigen::internal::conj_helper< Packet1cd, Packet1cd, true, true >::pmul(), predux_mul< Packet16f >(), predux_mul< Packet2cd >(), predux_mul< Packet4cf >(), predux_mul< Packet4f >(), predux_mul< Packet8d >(), prsqrt< Packet4f >(), pscatter< std::complex< double >, Packet1cd >(), psin< Packet4f >(), psin< Packet8f >(), psqrt< Packet2d >(), psqrt< Packet4d >(), ptranspose(), Eigen::internal::quat_product< Architecture::SSE, Derived, OtherDerived, double >::run(), Eigen::internal::etor_product_packet_impl< RowMajor, 1, Lhs, Rhs, Packet, LoadMode >::run(), and Eigen::internal::etor_product_packet_impl< ColMajor, 1, Lhs, Rhs, Packet, LoadMode >::run().
template<> std::complex<float> Eigen::internal::pmul (const std::complex< float > & a, const std::complex< float > & b) inline
References imag(), and real().
template<> std::complex<double> Eigen::internal::pmul (const std::complex< double > & a, const std::complex< double > & b) inline
References imag(), and real().
template<> EIGEN_STRONG_INLINE Packet16f Eigen::internal::pmul< Packet16f > (const Packet16f & a, const Packet16f & b)
template<> EIGEN_STRONG_INLINE Packet1cd Eigen::internal::pmul< Packet1cd > (const Packet1cd & a, const Packet1cd & b)
References vec2d_swizzle1.
Referenced by Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), pscatter< std::complex< double >, Packet1cd >(), and ptranspose().
template<> EIGEN_STRONG_INLINE Packet2cd Eigen::internal::pmul< Packet2cd > (const Packet2cd & a, const Packet2cd & b)
template<> EIGEN_STRONG_INLINE Packet2cf Eigen::internal::pmul< Packet2cf > (const Packet2cf & a, const Packet2cf & b)
References p16uc_COMPLEX32_REV, p16uc_PSET32_WEVEN, p16uc_PSET32_WODD, Eigen::internal::Packet2cf::Packet2cf(), padd< Packet4f >(), and pxor().
Referenced by predux_mul< Packet2cf >(), and pscatter< std::complex< double >, Packet1cd >().
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::pmul< Packet2d > (const Packet2d & a, const Packet2d & b)
References EIGEN_STRONG_INLINE, pdiv< Packet4f >(), pmul< Packet4i >(), vec4i_swizzle1, and vec4i_swizzle2.
Referenced by pblend(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), ptranspose(), and Eigen::internal::palign_impl< Offset, Packet2d >::run().
template<> EIGEN_STRONG_INLINE Packet4cf Eigen::internal::pmul< Packet4cf > (const Packet4cf & a, const Packet4cf & b)
References Eigen::internal::Packet4cf::Packet4cf().
template<> EIGEN_STRONG_INLINE Packet4d Eigen::internal::pmul< Packet4d > (const Packet4d & a, const Packet4d & b)
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::pmul< Packet4f > (const Packet4f & a, const Packet4f & b)
Referenced by pconj(), pdiv< Packet2cf >(), plset< Packet4i >(), and Eigen::internal::palign_impl< Offset, Packet2d >::run().
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::pmul< Packet4i > (const Packet4i & a, const Packet4i & b)
Referenced by plset< Packet4i >(), pmul< Packet2d >(), and Eigen::internal::palign_impl< Offset, Packet2d >::run().
template<> EIGEN_STRONG_INLINE Packet8d Eigen::internal::pmul< Packet8d > (const Packet8d & a, const Packet8d & b)
template<> EIGEN_STRONG_INLINE Packet8f Eigen::internal::pmul< Packet8f > (const Packet8f & a, const Packet8f & b)
template<> EIGEN_STRONG_INLINE Packet4cf Eigen::internal::pnegate (const Packet4cf & a)
References Eigen::internal::Packet4cf::Packet4cf(), pnegate(), and Eigen::internal::Packet4cf::v.
template<> EIGEN_STRONG_INLINE Packet2cf Eigen::internal::pnegate (const Packet2cf & a)
References Eigen::internal::Packet2cf::Packet2cf(), and Eigen::internal::Packet2cf::v.
Referenced by Eigen::internal::scalar_opposite_op< Scalar >::packetOp(), pblend(), plset< Packet4i >(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), pnegate(), pscatter< std::complex< double >, Packet1cd >(), psub< Packet2d >(), ptranspose(), and Eigen::internal::palign_impl< Offset, Packet2d >::run().
template<> EIGEN_STRONG_INLINE Packet8f Eigen::internal::pnegate (const Packet8f & a)
template<> EIGEN_STRONG_INLINE Packet4d Eigen::internal::pnegate (const Packet4d & a)
template<typename Packet > EIGEN_DEVICE_FUNC Packet Eigen::internal::pnegate (const Packet & a) inline
template<> EIGEN_STRONG_INLINE Packet16f Eigen::internal::pnegate (const Packet16f & a)
template<> EIGEN_STRONG_INLINE Packet8d Eigen::internal::pnegate (const Packet8d & a)
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::pnegate (const Packet2d & a)
References EIGEN_STRONG_INLINE, pconj(), pnegate(), and psub().
template<> EIGEN_STRONG_INLINE Packet2cd Eigen::internal::pnegate (const Packet2cd & a)
References pnegate(), and Eigen::internal::Packet2cd::v.
template<> EIGEN_STRONG_INLINE Packet1cd Eigen::internal::pnegate (const Packet1cd & a)
References pnegate(), and Eigen::internal::Packet1cd::v.
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::pnegate (const Packet4f & a)
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::pnegate (const Packet4i & a)
template<typename Packet > EIGEN_DEVICE_FUNC Packet Eigen::internal::por (const Packet & a, const Packet & b) inline
Referenced by plog< Packet4f >(), and ptranspose().
template<> EIGEN_STRONG_INLINE Packet16f Eigen::internal::por< Packet16f > (const Packet16f & a, const Packet16f & b)
template<> EIGEN_STRONG_INLINE Packet1cd Eigen::internal::por< Packet1cd > (const Packet1cd & a, const Packet1cd & b)
Referenced by Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), pscatter< std::complex< double >, Packet1cd >(), and ptranspose().
template<> EIGEN_STRONG_INLINE Packet2cd Eigen::internal::por< Packet2cd > (const Packet2cd & a, const Packet2cd & b)
template<> EIGEN_STRONG_INLINE Packet2cf Eigen::internal::por< Packet2cf > (const Packet2cf & a, const Packet2cf & b)
References Eigen::internal::Packet2cf::Packet2cf(), and por< Packet4f >().
Referenced by pscatter< std::complex< double >, Packet1cd >().
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::por< Packet2d > (const Packet2d & a, const Packet2d & b)
References EIGEN_STRONG_INLINE, por< Packet4i >(), and pxor< Packet4f >().
Referenced by pblend(), and pmadd().
template<> EIGEN_STRONG_INLINE Packet4cf Eigen::internal::por< Packet4cf > (const Packet4cf & a, const Packet4cf & b)
References Eigen::internal::Packet4cf::Packet4cf().
template<> EIGEN_STRONG_INLINE Packet4d Eigen::internal::por< Packet4d > (const Packet4d & a, const Packet4d & b)
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::por< Packet4f > (const Packet4f & a, const Packet4f & b)
Referenced by pand< Packet2d >(), plset< Packet4i >(), pmadd(), por< Packet2cf >(), and pscatter< std::complex< double >, Packet1cd >().
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::por< Packet4i > (const Packet4i & a, const Packet4i & b)
Referenced by plset< Packet4i >(), pmadd(), and por< Packet2d >().
template<> EIGEN_STRONG_INLINE Packet8d Eigen::internal::por< Packet8d > (const Packet8d & a, const Packet8d & b)
template<> EIGEN_STRONG_INLINE Packet8f Eigen::internal::por< Packet8f > (const Packet8f & a, const Packet8f & b)
template<typename Packet > EIGEN_DEVICE_FUNC unpacket_traits<Packet>::type Eigen::internal::predux (const Packet & a) inline
References type.
Referenced by Eigen::internal::scalar_sum_op< int, int >::predux(), predux< Packet2cd >(), predux< Packet4cf >(), predux< Packet4d >(), predux< Packet8f >(), predux_mul< Packet2cd >(), Eigen::internal::selfadjoint_matrix_vector_product< Scalar, Index, StorageOrder, UpLo, ConjugateLhs, ConjugateRhs, Version >::run(), and Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, RowMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::run().
template<> EIGEN_STRONG_INLINE float Eigen::internal::predux< Packet16f > (const Packet16f & a)
References predux< Packet8f >().
template<> EIGEN_STRONG_INLINE std::complex< double > Eigen::internal::predux< Packet1cd > (const Packet1cd & a)
References pfirst().
Referenced by Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), pscatter< std::complex< double >, Packet1cd >(), and ptranspose().
template<> EIGEN_STRONG_INLINE std::complex<double> Eigen::internal::predux< Packet2cd > (const Packet2cd & a)
References padd(), and predux().
template<> EIGEN_STRONG_INLINE std::complex< float > Eigen::internal::predux< Packet2cf > (const Packet2cf & a)
References Eigen::internal::Packet2cf::Packet2cf(), padd< Packet4f >(), and pfirst< Packet2cf >().
Referenced by pscatter< std::complex< double >, Packet1cd >().
template<> EIGEN_STRONG_INLINE double Eigen::internal::predux< Packet2d > (const Packet2d & a)
References EIGEN_STRONG_INLINE, pfirst(), pfirst< Packet2d >(), pfirst< Packet4f >(), pfirst< Packet4i >(), predux< Packet4i >(), predux_mul< Packet4f >(), and preduxp< Packet4i >().
Referenced by pabs< Packet4f >(), and pblend().
template<> EIGEN_STRONG_INLINE std::complex<float> Eigen::internal::predux< Packet4cf > (const Packet4cf & a)
References padd(), and predux().
template<> EIGEN_STRONG_INLINE double Eigen::internal::predux< Packet4d > (const Packet4d & a)
References predux().
template<> EIGEN_STRONG_INLINE float Eigen::internal::predux< Packet4f > (const Packet4f & a)
References pfirst().
Referenced by pabs< Packet4f >(), pfirst< Packet4i >(), and preduxp< Packet2d >().
template<> EIGEN_STRONG_INLINE int32_t Eigen::internal::predux< Packet4i > (const Packet4i & a)
References EIGEN_STRONG_INLINE, predux_mul< Packet4f >(), and preduxp< Packet4i >().
template<> EIGEN_STRONG_INLINE int Eigen::internal::predux< Packet4i > (const Packet4i & a)
References pfirst().
Referenced by pabs< Packet4f >(), and predux< Packet2d >().
template<> EIGEN_STRONG_INLINE double Eigen::internal::predux< Packet8d > (const Packet8d & a)
template<> EIGEN_STRONG_INLINE float Eigen::internal::predux< Packet8f > (const Packet8f & a)
References predux().
Referenced by predux< Packet16f >().
template<typename Packet > EIGEN_DEVICE_FUNC conditional<(unpacket_traits<Packet>::size%8)==0,typename unpacket_traits<Packet>::half,Packet>::type Eigen::internal::predux_downto4 (const Packet & a) inline
Referenced by Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::operator()().
template<typename Packet > const DoublePacket<Packet>& Eigen::internal::predux_downto4 (const DoublePacket< Packet > & a)
template<> EIGEN_STRONG_INLINE Packet8f Eigen::internal::predux_downto4< Packet16f > (const Packet16f & a)
template<> EIGEN_STRONG_INLINE Packet4d Eigen::internal::predux_downto4< Packet8d > (const Packet8d & a)
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::predux_downto4< Packet8f > (const Packet8f & a)
template<typename Packet > EIGEN_DEVICE_FUNC unpacket_traits<Packet>::type Eigen::internal::predux_max (const Packet & a) inline
Referenced by Eigen::internal::scalar_max_op< LhsScalar, RhsScalar >::predux().
template<> EIGEN_STRONG_INLINE float Eigen::internal::predux_max< Packet16f > (const Packet16f & a)
References pfirst().
template<> EIGEN_STRONG_INLINE double Eigen::internal::predux_max< Packet2d > (const Packet2d & a)
References EIGEN_ALIGN16, EIGEN_STRONG_INLINE, first(), pfirst< Packet2d >(), pfirst< Packet4i >(), predux_max< Packet4i >(), and pstore().
Referenced by pabs< Packet4f >(), and pblend().
template<> EIGEN_STRONG_INLINE double Eigen::internal::predux_max< Packet4d > (const Packet4d & a)
References pfirst().
template<> EIGEN_STRONG_INLINE float Eigen::internal::predux_max< Packet4f > (const Packet4f & a)
References pfirst().
Referenced by pabs< Packet4f >(), predux_min< Packet2d >(), and predux_min< Packet4i >().
template<> EIGEN_STRONG_INLINE int32_t Eigen::internal::predux_max< Packet4i > (const Packet4i & a)
References Eigen::half_impl::max().
template<> EIGEN_STRONG_INLINE int Eigen::internal::predux_max< Packet4i > (const Packet4i & a)
References pfirst().
Referenced by pabs< Packet4f >(), and predux_max< Packet2d >().
template<> EIGEN_STRONG_INLINE double Eigen::internal::predux_max< Packet8d > (const Packet8d & a)
References pfirst().
template<> EIGEN_STRONG_INLINE float Eigen::internal::predux_max< Packet8f > (const Packet8f & a)
References pfirst().
template<typename Packet > EIGEN_DEVICE_FUNC unpacket_traits<Packet>::type Eigen::internal::predux_min (const Packet & a) inline
Referenced by Eigen::internal::scalar_min_op< LhsScalar, RhsScalar >::predux().
template<> EIGEN_STRONG_INLINE float Eigen::internal::predux_min< Packet16f > (const Packet16f & a)
References pfirst().
template<> EIGEN_STRONG_INLINE double Eigen::internal::predux_min< Packet2d > (const Packet2d & a)
References EIGEN_ALIGN16, EIGEN_STRONG_INLINE, pfirst< Packet2d >(), pfirst< Packet4f >(), pfirst< Packet4i >(), predux_max< Packet4f >(), predux_min< Packet4i >(), and pstore().
Referenced by pabs< Packet4f >(), and pblend().
template<> EIGEN_STRONG_INLINE double Eigen::internal::predux_min< Packet4d > (const Packet4d & a)
References pfirst().
template<> EIGEN_STRONG_INLINE float Eigen::internal::predux_min< Packet4f > (const Packet4f & a)
References pfirst().
Referenced by pabs< Packet4f >(), predux_mul< Packet2d >(), and predux_mul< Packet4i >().
template<> EIGEN_STRONG_INLINE int32_t Eigen::internal::predux_min< Packet4i > (const Packet4i & a)
References EIGEN_STRONG_INLINE, Eigen::half_impl::max(), Eigen::half_impl::min(), and predux_max< Packet4f >().
template<> EIGEN_STRONG_INLINE int Eigen::internal::predux_min< Packet4i > (const Packet4i & a)
References pfirst().
Referenced by pabs< Packet4f >(), and predux_min< Packet2d >().
template<> EIGEN_STRONG_INLINE double Eigen::internal::predux_min< Packet8d > (const Packet8d & a)
References pfirst().
template<> EIGEN_STRONG_INLINE float Eigen::internal::predux_min< Packet8f > (const Packet8f & a)
References pfirst().
template<typename Packet > EIGEN_DEVICE_FUNC unpacket_traits<Packet>::type Eigen::internal::predux_mul (const Packet & a) inline
Referenced by pabs< Packet4f >(), Eigen::internal::scalar_product_op< LhsScalar, RhsScalar >::predux(), and predux_mul< Packet4cf >().
template<> EIGEN_STRONG_INLINE float Eigen::internal::predux_mul< Packet16f > (const Packet16f & a)
References pfirst(), and pmul().
template<> EIGEN_STRONG_INLINE std::complex< double > Eigen::internal::predux_mul< Packet1cd > (const Packet1cd & a)
References pfirst().
Referenced by Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), pscatter< std::complex< double >, Packet1cd >(), and ptranspose().
template<> EIGEN_STRONG_INLINE std::complex<double> Eigen::internal::predux_mul< Packet2cd > (const Packet2cd & a)
References pmul(), and predux().
template<> EIGEN_STRONG_INLINE std::complex< float > Eigen::internal::predux_mul< Packet2cf > (const Packet2cf & a)
References Eigen::internal::Packet2cf::Packet2cf(), pfirst< Packet2cf >(), and pmul< Packet2cf >().
Referenced by pscatter< std::complex< double >, Packet1cd >().
template<> EIGEN_STRONG_INLINE double Eigen::internal::predux_mul< Packet2d > (const Packet2d & a)
References EIGEN_ALIGN16, EIGEN_STRONG_INLINE, pfirst< Packet2d >(), pfirst< Packet4f >(), predux_min< Packet4f >(), predux_mul< Packet4i >(), and pstore().
Referenced by pabs< Packet4f >(), and pblend().
template<> EIGEN_STRONG_INLINE std::complex<float> Eigen::internal::predux_mul< Packet4cf > (const Packet4cf & a)
References pmul(), and predux_mul().
template<> EIGEN_STRONG_INLINE double Eigen::internal::predux_mul< Packet4d > (const Packet4d & a)
References pfirst().
template<> EIGEN_STRONG_INLINE float Eigen::internal::predux_mul< Packet4f > (const Packet4f & a)
References pfirst(), and pmul().
Referenced by pabs< Packet4f >(), predux< Packet2d >(), and predux< Packet4i >().
template<> EIGEN_STRONG_INLINE int32_t Eigen::internal::predux_mul< Packet4i > (const Packet4i & a)
References EIGEN_STRONG_INLINE, Eigen::half_impl::min(), and predux_min< Packet4f >().
template<> EIGEN_STRONG_INLINE int Eigen::internal::predux_mul< Packet4i > (const Packet4i & a)
References EIGEN_ALIGN16, and pstore().
Referenced by pabs< Packet4f >(), and predux_mul< Packet2d >().
template<> EIGEN_STRONG_INLINE double Eigen::internal::predux_mul< Packet8d > (const Packet8d & a)
References pfirst(), and pmul().
template<> EIGEN_STRONG_INLINE float Eigen::internal::predux_mul< Packet8f > (const Packet8f & a)
References pfirst().
template<typename Packet > EIGEN_DEVICE_FUNC Packet Eigen::internal::preduxp (const Packet * vecs) inline
template<> EIGEN_STRONG_INLINE Packet16f Eigen::internal::preduxp< Packet16f > (const Packet16f * vecs)
References EIGEN_EXTRACT_8f_FROM_16f, and EIGEN_INSERT_8f_INTO_16f.
template<> EIGEN_STRONG_INLINE Packet1cd Eigen::internal::preduxp< Packet1cd > (const Packet1cd * vecs)
Referenced by Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), pscatter< std::complex< double >, Packet1cd >(), and ptranspose().
template<> EIGEN_STRONG_INLINE Packet2cd Eigen::internal::preduxp< Packet2cd > (const Packet2cd * vecs)
References Eigen::internal::Packet4cf::v.
template<> EIGEN_STRONG_INLINE Packet2cf Eigen::internal::preduxp< Packet2cf > (const Packet2cf * vecs)
References Eigen::internal::Packet2cf::Packet2cf(), padd< Packet4f >(), and Eigen::internal::Packet2cf::v.
Referenced by pscatter< std::complex< double >, Packet1cd >().
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::preduxp< Packet2d > (const Packet2d * vecs)
References EIGEN_STRONG_INLINE, pfirst< Packet4f >(), and predux< Packet4f >().
Referenced by pabs< Packet4f >(), pblend(), and punpackp().
template<> EIGEN_STRONG_INLINE Packet4cf Eigen::internal::preduxp< Packet4cf > (const Packet4cf * vecs)
References Eigen::internal::Packet4cf::Packet4cf(), and Eigen::internal::Packet4cf::v.
template<> EIGEN_STRONG_INLINE Packet4d Eigen::internal::preduxp< Packet4d > (const Packet4d * vecs)
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::preduxp< Packet4f > (const Packet4f * vecs)
Referenced by pabs< Packet4f >(), pfirst< Packet4i >(), and punpackp().
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::preduxp< Packet4i > (const Packet4i * vecs)
Referenced by pabs< Packet4f >(), predux< Packet2d >(), and predux< Packet4i >().
template<> EIGEN_STRONG_INLINE Packet8d Eigen::internal::preduxp< Packet8d > (const Packet8d * vecs)
template<> EIGEN_STRONG_INLINE Packet8f Eigen::internal::preduxp< Packet8f > (const Packet8f * vecs)
template<typename Scalar > EIGEN_DEVICE_FUNC void Eigen::internal::prefetch (const Scalar * addr) inline
Referenced by Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::operator()(), Eigen::internal::BlasLinearMapper< Scalar, Index, AlignmentType >::prefetch(), and sparselu_gemm().
template<> EIGEN_STRONG_INLINE void Eigen::internal::prefetch< double > (const double * addr)
References EIGEN_STRONG_INLINE, and prefetch< int >().
Referenced by pblend(), pfloor< Packet2d >(), pstore1< Packet16i >(), and pstore1< Packet2d >().
template<> EIGEN_STRONG_INLINE void Eigen::internal::prefetch< float > (const float * addr)
References EIGEN_PPC_PREFETCH.
Referenced by pfloor< Packet2d >(), pscatter< int32_t, Packet4i >(), pstore1< Packet16i >(), pstore1< Packet2d >(), and pstore1< Packet8i >().
template<> EIGEN_STRONG_INLINE void Eigen::internal::prefetch< int > (const int * addr)
References EIGEN_PPC_PREFETCH.
Referenced by pfloor< Packet2d >(), prefetch< double >(), pstore1< Packet16i >(), and pstore1< Packet2d >().
template<> EIGEN_STRONG_INLINE void Eigen::internal::prefetch< int32_t > (const int32_t * addr)
References EIGEN_ALIGN16, EIGEN_ARM_PREFETCH, EIGEN_STRONG_INLINE, and pfirst< Packet4f >().
template<> EIGEN_STRONG_INLINE void Eigen::internal::prefetch< std::complex< double > > (const std::complex< double > * addr)
template<> EIGEN_STRONG_INLINE void Eigen::internal::prefetch< std::complex< float > > (const std::complex< float > * addr)
References EIGEN_PPC_PREFETCH.
template<> EIGEN_STRONG_INLINE Packet4cf Eigen::internal::preverse (const Packet4cf & a)
References Eigen::internal::Packet4cf::Packet4cf(), and Eigen::internal::Packet4cf::v.
template<> EIGEN_STRONG_INLINE Packet2cf Eigen::internal::preverse (const Packet2cf & a)
References p16uc_COMPLEX32_REV2, Eigen::internal::Packet2cf::Packet2cf(), and Eigen::internal::Packet2cf::v.
Referenced by Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::packet(), pblend(), pcplxflip(), pfirst< Packet2d >(), pfirst< Packet4i >(), pfloor< Packet2d >(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), preverse(), pscatter< std::complex< double >, Packet1cd >(), ptranspose(), Eigen::internal::reverse_packet_cond< PacketType, ReversePacket >::run(), Eigen::internal::quat_product< Architecture::SSE, Derived, OtherDerived, double >::run(), and Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::writePacket().
template<> EIGEN_STRONG_INLINE Packet2cd Eigen::internal::preverse (const Packet2cd & a)
References Eigen::internal::Packet2cd::v.
template<> EIGEN_STRONG_INLINE Packet1cd Eigen::internal::preverse (const Packet1cd & a)
template<> EIGEN_STRONG_INLINE Packet8f Eigen::internal::preverse (const Packet8f & a)
template<> EIGEN_STRONG_INLINE Packet4d Eigen::internal::preverse (const Packet4d & a)
template<typename Packet > EIGEN_DEVICE_FUNC Packet Eigen::internal::preverse (const Packet & a) inline
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::preverse (const Packet2d & a)
References EIGEN_STRONG_INLINE, pabs(), and preverse().
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::preverse (const Packet4f & a)
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::preverse (const Packet4i & a)
template<> EIGEN_STRONG_INLINE Packet16f Eigen::internal::preverse (const Packet16f & a)
template<> EIGEN_STRONG_INLINE Packet8d Eigen::internal::preverse (const Packet8d & a)
template<typename Derived > std::ostream & Eigen::internal::print_matrix (std::ostream & s, const Derived & _m, const IOFormat & fmt)
References Eigen::IOFormat::coeffSeparator, Eigen::DontAlignCols, Eigen::IOFormat::flags, Eigen::FullPrecision, i, m, Eigen::IOFormat::matPrefix, Eigen::IOFormat::matSuffix, Eigen::IOFormat::precision, Eigen::IOFormat::rowPrefix, Eigen::IOFormat::rowSeparator, Eigen::IOFormat::rowSpacer, Eigen::IOFormat::rowSuffix, Eigen::internal::significant_decimals_impl< Scalar >::run(), and Eigen::StreamPrecision.
Referenced by Eigen::DenseBase< Derived >::operator<<().
template<typename Packet > EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet Eigen::internal::pround (const Packet & a)
References EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS, and round().
Referenced by Eigen::internal::scalar_round_op< Scalar >::packetOp().
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::pround< Packet2d > (const Packet2d & a)
References EIGEN_STRONG_INLINE, pceil< Packet4f >(), and Eigen::internal::Packet4f::v4f.
Referenced by pblend(), and pmax< Packet2d >().
template<> EIGEN_STRONG_INLINE Packet4d Eigen::internal::pround< Packet4d > (const Packet4d & a)
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::pround< Packet4f > (const Packet4f & a)
Referenced by pmadd(), and pmax< Packet2d >().
template<> EIGEN_STRONG_INLINE Packet8f Eigen::internal::pround< Packet8f > (const Packet8f & a)
template<typename Packet > EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet Eigen::internal::prsqrt (const Packet & a)
References EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS, pdiv(), and psqrt().
Referenced by Eigen::internal::scalar_rsqrt_op< Scalar >::packetOp().
template<> EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet2d Eigen::internal::prsqrt< Packet2d > (const Packet2d & x)
References EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS, EIGEN_UNUSED, and pset1< Packet2d >().
Referenced by prsqrt< Packet4f >().
template<> EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet4d Eigen::internal::prsqrt< Packet4d > (const Packet4d & x)
References _EIGEN_DECLARE_CONST_Packet4d.
template<> EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet4f Eigen::internal::prsqrt< Packet4f > (const Packet4f & x)
References _EIGEN_DECLARE_CONST_Packet4i(), EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS, EIGEN_UNUSED, pdiv(), pexp< Packet2d >(), pfloor(), pmadd(), pmax(), pmin(), pmul(), prsqrt< Packet2d >(), psqrt< Packet2d >(), psqrt< Packet4f >(), and psub().
Referenced by psqrt< Packet2d >().
template<> EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet8f Eigen::internal::prsqrt< Packet8f > (const Packet8f & x)
References _EIGEN_DECLARE_CONST_Packet8f, EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS, and EIGEN_UNUSED.
Referenced by psqrt< Packet4d >().
template<typename Scalar , typename Packet > EIGEN_DEVICE_FUNC void Eigen::internal::pscatter (Scalar * to, const Packet & from, Index) inline
References pstore().
template<> EIGEN_DEVICE_FUNC void Eigen::internal::pscatter< double, Packet2d > (double * to, const Packet2d & from, Index stride) inline
References pscatter< int, Packet4i >().
Referenced by pblend(), and Eigen::internal::palign_impl< Offset, Packet2d >::run().
template<> EIGEN_DEVICE_FUNC void Eigen::internal::pscatter< double, Packet4d > (double * to, const Packet4d & from, Index stride) inline
template<> EIGEN_DEVICE_FUNC void Eigen::internal::pscatter< double, Packet8d > (double * to, const Packet8d & from, Index stride) inline
template<> EIGEN_DEVICE_FUNC void Eigen::internal::pscatter< float, Packet16f > (float * to, const Packet16f & from, Index stride) inline
template<> EIGEN_DEVICE_FUNC void Eigen::internal::pscatter< float, Packet4f > (float * to, const Packet4f & from, Index stride) inline
References EIGEN_ALIGN16, and pstore< float >().
Referenced by pgather< double, Packet2d >(), pgather< int32_t, Packet4i >(), and Eigen::internal::palign_impl< Offset, Packet2d >::run().
template<> EIGEN_DEVICE_FUNC void Eigen::internal::pscatter< float, Packet8f > (float * to, const Packet8f & from, Index stride) inline
template<> EIGEN_DEVICE_FUNC void Eigen::internal::pscatter< int, Packet4i > (int * to, const Packet4i & from, Index stride) inline
References EIGEN_ALIGN16, and pstore< int >().
Referenced by pscatter< double, Packet2d >(), and Eigen::internal::palign_impl< Offset, Packet2d >::run().
template<> EIGEN_DEVICE_FUNC void Eigen::internal::pscatter< int32_t, Packet4i > (int32_t * to, const Packet4i & from, Index stride) inline
References EIGEN_ARM_PREFETCH, EIGEN_STRONG_INLINE, and prefetch< float >().
template<> EIGEN_DEVICE_FUNC void Eigen::internal::pscatter< std::complex< double >, Packet1cd > (std::complex< double > * to, const Packet1cd & from, Index stride EIGEN_UNUSED) inline
References Eigen::internal::Packet2cf::cd, EIGEN_ALIGN16, EIGEN_STRONG_INLINE, EIGEN_ZVECTOR_PREFETCH, p16uc_PSET64_HI, p16uc_PSET64_LO, Eigen::internal::PacketBlock< Packet, N >::packet, Eigen::internal::Packet1cd::Packet1cd(), padd< Packet1cd >(), padd< Packet2cf >(), padd< Packet4f >(), pand< Packet1cd >(), pand< Packet2cf >(), pand< Packet4f >(), pandnot< Packet1cd >(), pandnot< Packet2cf >(), pandnot< Packet4f >(), pconj(), pfirst(), pfirst< Packet1cd >(), pfirst< Packet2cf >(), ploaddup< Packet1cd >(), ploaddup< Packet2cf >(), pmul(), pmul< Packet1cd >(), pmul< Packet2cf >(), pnegate(), por< Packet1cd >(), por< Packet2cf >(), por< Packet4f >(), predux< Packet1cd >(), predux< Packet2cf >(), predux_mul< Packet1cd >(), predux_mul< Packet2cf >(), preduxp< Packet1cd >(), preduxp< Packet2cf >(), preverse(), pset1< Packet1cd >(), pset1< Packet2cf >(), psub< Packet1cd >(), psub< Packet2cf >(), psub< Packet4f >(), ptranspose(), pxor< Packet1cd >(), pxor< Packet2cf >(), pxor< Packet4f >(), Eigen::internal::Packet2cf::v, Eigen::internal::Packet1cd::v, and Eigen::internal::Packet4f::v4f.
template<> EIGEN_DEVICE_FUNC void Eigen::internal::pscatter< std::complex< double >, Packet2cd > (std::complex< double > * to, const Packet2cd & from, Index stride) inline
template<> EIGEN_DEVICE_FUNC void Eigen::internal::pscatter< std::complex< float >, Packet2cf > (std::complex< float > * to, const Packet2cf & from, Index stride) inline
References EIGEN_ALIGN16.
template<> EIGEN_DEVICE_FUNC void Eigen::internal::pscatter< std::complex< float >, Packet4cf > (std::complex< float > * to, const Packet4cf & from, Index stride) inline
template<typename Packet > EIGEN_DEVICE_FUNC Packet Eigen::internal::pset1 (const typename unpacket_traits< Packet >::type & a) inline
template<> EIGEN_STRONG_INLINE Packet16f Eigen::internal::pset1< Packet16f > (const float & from)
Referenced by pstore1< Packet16f >().
template<> EIGEN_STRONG_INLINE Packet16i Eigen::internal::pset1< Packet16i > (const int & from)
Referenced by pstore1< Packet16i >().
template<> EIGEN_STRONG_INLINE Packet1cd Eigen::internal::pset1< Packet1cd > (const std::complex< double > & from)
References ploadu< Packet1cd >().
Referenced by pinsertfirst(), pinsertlast(), ploaddup< Packet1cd >(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), pscatter< std::complex< double >, Packet1cd >(), and ptranspose().
template<> EIGEN_STRONG_INLINE Packet2cd Eigen::internal::pset1< Packet2cd > (const std::complex< double > & from)
Referenced by pinsertfirst(), pinsertlast(), and ploaddup< Packet2cd >().
template<> EIGEN_STRONG_INLINE Packet2cf Eigen::internal::pset1< Packet2cf > (const std::complex< float > & from)
References p16uc_PSET64_HI, pload< Packet4f >(), ploadu< Packet4f >(), and Eigen::internal::Packet2cf::v.
Referenced by ploaddup< Packet2cf >(), and pscatter< std::complex< double >, Packet1cd >().
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::pset1< Packet2d > (const double & from)
References EIGEN_STRONG_INLINE, plset< Packet4f >(), pset1< Packet4f >(), pset1< Packet4i >(), and vec4f_swizzle1.
Referenced by pblend(), pinsertfirst(), pinsertlast(), ploaddup< Packet2d >(), plset< Packet2d >(), pmadd(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), prsqrt< Packet2d >(), Eigen::internal::quat_product< Architecture::SSE, Derived, OtherDerived, double >::run(), and Eigen::internal::palign_impl< Offset, Packet2d >::run().
template<> EIGEN_STRONG_INLINE Packet4cf Eigen::internal::pset1< Packet4cf > (const std::complex< float > & from)
References Eigen::internal::Packet4cf::Packet4cf().
Referenced by pinsertfirst(), and pinsertlast().
template<> EIGEN_STRONG_INLINE Packet4d Eigen::internal::pset1< Packet4d > (const double & from)
Referenced by pinsertfirst(), pinsertlast(), and pstore1< Packet4d >().
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::pset1< Packet4f > (const float & from)
Referenced by pcos< Packet4f >(), pinsertfirst(), pinsertlast(), plset< Packet4f >(), pmadd(), pset1< Packet2d >(), pset1< Packet4i >(), psqrt< Packet2d >(), pstoreu< int32_t >(), and Eigen::internal::palign_impl< Offset, Packet2d >::run().
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::pset1< Packet4i > (const int32_t & from)
References EIGEN_STRONG_INLINE, plset< Packet4f >(), and pset1< Packet4f >().
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::pset1< Packet4i > (const int & from)
References EIGEN_STRONG_INLINE.
Referenced by pdiv< Packet4i >(), pgather< int32_t, Packet4i >(), plset< Packet2d >(), plset< Packet4i >(), pmadd(), pset1< Packet2d >(), and Eigen::internal::palign_impl< Offset, Packet2d >::run().
template<> EIGEN_STRONG_INLINE Packet8d Eigen::internal::pset1< Packet8d > (const double & from)
Referenced by pstore1< Packet8d >().
template<> EIGEN_STRONG_INLINE Packet8f Eigen::internal::pset1< Packet8f > (const float & from)
Referenced by pexp< Packet4d >(), pinsertfirst(), pinsertlast(), and pstore1< Packet8f >().
template<> EIGEN_STRONG_INLINE Packet8i Eigen::internal::pset1< Packet8i > (const int & from)
Referenced by pdiv< Packet8i >(), and pstore1< Packet8i >().
Packet8i Eigen::internal::pshiftleft (Packet8i v, int n) inline
Referenced by pexp< Packet8f >(), and psin< Packet8f >().
Packet8f Eigen::internal::pshiftright (Packet8f v, int n) inline
References EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS, and EIGEN_UNUSED.
Referenced by plog< Packet8f >().
template<typename Packet > EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet Eigen::internal::psin (const Packet & a)
References EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS, and sin().
Referenced by Eigen::internal::scalar_sin_op< Scalar >::packetOp().
template<> EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet4f Eigen::internal::psin< Packet4f > (const Packet4f & _x)
References _EIGEN_DECLARE_CONST_Packet4f(), _EIGEN_DECLARE_CONST_Packet4f_FROM_INT(), _EIGEN_DECLARE_CONST_Packet4i(), E, EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS, EIGEN_UNUSED, pabs(), padd(), pmadd(), pmul(), and psub().
template<> EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet8f Eigen::internal::psin< Packet8f > (const Packet8f & _x)
References _EIGEN_DECLARE_CONST_Packet8f, _EIGEN_DECLARE_CONST_Packet8i, e, EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS, EIGEN_UNUSED, padd(), pmadd(), pmul(), pshiftleft(), and psub().
template<typename Packet > EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet Eigen::internal::psinh (const Packet & a)
References EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS, and sinh().
Referenced by Eigen::internal::scalar_sinh_op< Scalar >::packetOp().
template<typename Packet > EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet Eigen::internal::psqrt (const Packet & a)
References EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS, and sqrt().
Referenced by Eigen::internal::scalar_sqrt_op< Scalar >::packetOp(), and prsqrt().
template<> EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet2d Eigen::internal::psqrt< Packet2d > (const Packet2d & x)
References _EIGEN_DECLARE_CONST_Packet4f(), _EIGEN_DECLARE_CONST_Packet4f_FROM_INT(), EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS, EIGEN_UNUSED, pmadd(), pmul(), prsqrt< Packet4f >(), and pset1< Packet4f >().
Referenced by prsqrt< Packet4f >().
template<> EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet4d Eigen::internal::psqrt< Packet4d > (const Packet4d & x)
References _EIGEN_DECLARE_CONST_Packet8f, _EIGEN_DECLARE_CONST_Packet8f_FROM_INT, EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS, EIGEN_UNUSED, pmadd(), pmul(), and prsqrt< Packet8f >().
template<> EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet4f Eigen::internal::psqrt< Packet4f > (const Packet4f & x)
References EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS, and EIGEN_UNUSED.
Referenced by pcos< Packet4f >(), and prsqrt< Packet4f >().
template<> EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet8f Eigen::internal::psqrt< Packet8f > (const Packet8f & x)
References EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS, and EIGEN_UNUSED.
Referenced by pexp< Packet4d >().
template<typename Scalar , typename Packet > EIGEN_DEVICE_FUNC void Eigen::internal::pstore (Scalar * to, const Packet & from) inline
Referenced by Eigen::internal::gemm_pack_lhs< Scalar, Index, DataMapper, Pack1, Pack2, ColMajor, Conjugate, PanelMode >::operator()(), Eigen::internal::gemm_pack_lhs< Scalar, Index, DataMapper, Pack1, Pack2, RowMajor, Conjugate, PanelMode >::operator()(), pabs< Packet4f >(), pfirst< Packet2cf >(), pfloor< Packet2d >(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), predux_max< Packet2d >(), predux_min< Packet2d >(), predux_mul< Packet2d >(), predux_mul< Packet4i >(), pscatter(), pstore1(), pstore1< Packet16f >(), pstore1< Packet16i >(), pstore1< Packet2d >(), pstore1< Packet4d >(), pstore1< Packet4f >(), pstore1< Packet8d >(), pstore1< Packet8f >(), pstore1< Packet8i >(), pstore< std::complex< double > >(), pstore< std::complex< float > >(), pstoret(), ptranspose(), Eigen::internal::selfadjoint_matrix_vector_product< Scalar, Index, StorageOrder, UpLo, ConjugateLhs, ConjugateRhs, Version >::run(), and Eigen::internal::apply_rotation_in_the_plane_selector< Scalar, OtherScalar, SizeAtCompileTime, MinAlignment, true >::run().
template<typename Packet > void Eigen::internal::pstore1 (typename unpacket_traits< Packet >::type * to, const typename unpacket_traits< Packet >::type & a) inline
References pstore().
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstore1< Packet16f > (float * to, const float & a)
References pset1< Packet16f >(), and pstore().
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstore1< Packet16i > (int * to, const int & a)
References EIGEN_STRONG_INLINE, prefetch< double >(), prefetch< float >(), prefetch< int >(), pset1< Packet16i >(), and pstore().
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstore1< Packet2d > (double * to, const double & a)
References EIGEN_STRONG_INLINE, pfirst< Packet2d >(), pfirst< Packet4f >(), pfirst< Packet4i >(), prefetch< double >(), prefetch< float >(), prefetch< int >(), pstore(), and vec2d_swizzle1.
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstore1< Packet4d > (double * to, const double & a)
References pset1< Packet4d >(), and pstore().
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstore1< Packet4f > (float * to, const float & a)
References pstore(), and vec4f_swizzle1.
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstore1< Packet8d > (double * to, const double & a)
References pset1< Packet8d >(), and pstore().
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstore1< Packet8f > (float * to, const float & a)
References pset1< Packet8f >(), and pstore().
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstore1< Packet8i > (int * to, const int & a)
References EIGEN_STRONG_INLINE, prefetch< float >(), pset1< Packet8i >(), and pstore().
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstore< double > (double * to, const Packet4d & from)
References EIGEN_DEBUG_ALIGNED_STORE.
Referenced by pblend(), pfloor< Packet2d >(), and Eigen::internal::palign_impl< Offset, Packet2d >::run().
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstore< double > (double * to, const Packet2d & from)
References EIGEN_DEBUG_ALIGNED_STORE, EIGEN_STRONG_INLINE, and pstore< int >().
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstore< double > (double * to, const Packet8d & from)
References EIGEN_DEBUG_ALIGNED_STORE.
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstore< float > (float * to, const Packet4f & from)
References EIGEN_DEBUG_ALIGNED_STORE.
Referenced by pfloor< Packet2d >(), ploaddup< Packet2d >(), ploaddup< Packet4i >(), pscatter< float, Packet4f >(), and Eigen::internal::palign_impl< Offset, Packet2d >::run().
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstore< float > (float * to, const Packet8f & from)
References EIGEN_DEBUG_ALIGNED_STORE.
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstore< float > (float * to, const Packet16f & from)
References EIGEN_DEBUG_ALIGNED_STORE.
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstore< int > (int * to, const Packet8i & from)
References EIGEN_DEBUG_ALIGNED_STORE.
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstore< int > (int * to, const Packet4i & from)
References EIGEN_DEBUG_ALIGNED_STORE.
Referenced by pfloor< Packet2d >(), pscatter< int, Packet4i >(), pstore< double >(), and Eigen::internal::palign_impl< Offset, Packet2d >::run().
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstore< int > (int * to, const Packet16i & from)
References EIGEN_DEBUG_ALIGNED_STORE.
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstore< int32_t > (int32_t * to, const Packet4i & from)
References EIGEN_DEBUG_ALIGNED_STORE, EIGEN_DEBUG_UNALIGNED_STORE, EIGEN_STRONG_INLINE, and pstoreu< float >().
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstore< std::complex< double > > (std::complex< double > * to, const Packet2cd & from)
References EIGEN_DEBUG_ALIGNED_STORE, and pstore().
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstore< std::complex< double > > (std::complex< double > * to, const Packet1cd & from)
References EIGEN_DEBUG_ALIGNED_STORE, and pstore().
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstore< std::complex< float > > (std::complex< float > * to, const Packet2cf & from)
References pstore().
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstore< std::complex< float > > (std::complex< float > * to, const Packet4cf & from)
References EIGEN_DEBUG_ALIGNED_STORE, and pstore().
template<typename Scalar , typename Packet , int Alignment> EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE void Eigen::internal::pstoret (Scalar * to, const Packet & from)
References pstore(), and pstoreu().
template<typename Scalar , typename Packet > EIGEN_DEVICE_FUNC void Eigen::internal::pstoreu (Scalar * to, const Packet & from) inline
Referenced by Eigen::internal::gemm_pack_rhs< Scalar, Index, DataMapper, nr, ColMajor, Conjugate, PanelMode >::operator()(), Eigen::internal::gemm_pack_rhs< Scalar, Index, DataMapper, nr, RowMajor, Conjugate, PanelMode >::operator()(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), pstoret(), pstoreu< std::complex< double > >(), pstoreu< std::complex< float > >(), ptranspose(), Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, ColMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::run(), and Eigen::internal::apply_rotation_in_the_plane_selector< Scalar, OtherScalar, SizeAtCompileTime, MinAlignment, true >::run().
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstoreu< double > (double * to, const Packet4d & from)
References EIGEN_DEBUG_UNALIGNED_STORE.
Referenced by pblend(), and pfloor< Packet2d >().
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstoreu< double > (double * to, const Packet2d & from)
References EIGEN_DEBUG_UNALIGNED_STORE, EIGEN_STRONG_INLINE, pgather< float, Packet4f >(), pstoreu< float >(), and pstoreu< int >().
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstoreu< double > (double * to, const Packet8d & from)
References EIGEN_DEBUG_UNALIGNED_STORE.
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstoreu< float > (float * to, const Packet8f & from)
References EIGEN_DEBUG_UNALIGNED_STORE.
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstoreu< float > (float * to, const Packet4f & from)
References _EIGEN_ALIGNED_PTR, and EIGEN_DEBUG_ALIGNED_STORE.
Referenced by pfloor< Packet2d >(), ploaddup< Packet4i >(), pstore< int32_t >(), and pstoreu< double >().
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstoreu< float > (float * to, const Packet16f & from)
References EIGEN_DEBUG_UNALIGNED_STORE.
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstoreu< int > (int * to, const Packet8i & from)
References EIGEN_DEBUG_UNALIGNED_STORE.
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstoreu< int > (int * to, const Packet4i & from)
References _EIGEN_ALIGNED_PTR, and EIGEN_DEBUG_ALIGNED_STORE.
Referenced by pfloor< Packet2d >(), ploaddup< Packet4i >(), and pstoreu< double >().
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstoreu< int > (int * to, const Packet16i & from)
References EIGEN_DEBUG_UNALIGNED_STORE.
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstoreu< int32_t > (int32_t * to, const Packet4i & from)
References EIGEN_DEBUG_UNALIGNED_STORE, pgather< float, Packet4f >(), and pset1< Packet4f >().
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstoreu< std::complex< double > > (std::complex< double > * to, const Packet2cd & from)
References EIGEN_DEBUG_UNALIGNED_STORE, and pstoreu().
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstoreu< std::complex< double > > (std::complex< double > * to, const Packet1cd & from)
References EIGEN_DEBUG_UNALIGNED_STORE, and pstoreu().
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstoreu< std::complex< float > > (std::complex< float > * to, const Packet2cf & from)
References pstoreu().
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstoreu< std::complex< float > > (std::complex< float > * to, const Packet4cf & from)
References EIGEN_DEBUG_UNALIGNED_STORE, and pstoreu().
template<typename Packet > EIGEN_DEVICE_FUNC Packet Eigen::internal::psub (const Packet & a, const Packet & b) inline
Referenced by Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::acc(), Eigen::internal::sub_assign_op< DstScalar, SrcScalar >::assignPacket(), Eigen::internal::scalar_difference_op< LhsScalar, RhsScalar >::packetOp(), pcos< Packet4f >(), pexp< Packet2d >(), pexp< Packet4d >(), pexp< Packet4f >(), pexp< Packet8f >(), plog< Packet4f >(), plog< Packet8f >(), pnegate(), prsqrt< Packet4f >(), psin< Packet4f >(), psin< Packet8f >(), Eigen::internal::quat_product< Architecture::SSE, Derived, OtherDerived, double >::run(), and Eigen::internal::apply_rotation_in_the_plane_selector< Scalar, OtherScalar, SizeAtCompileTime, MinAlignment, true >::run().
template<> EIGEN_STRONG_INLINE Packet16f Eigen::internal::psub< Packet16f > (const Packet16f & a, const Packet16f & b)
template<> EIGEN_STRONG_INLINE Packet1cd Eigen::internal::psub< Packet1cd > (const Packet1cd & a, const Packet1cd & b)
Referenced by Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), pscatter< std::complex< double >, Packet1cd >(), and ptranspose().
template<> EIGEN_STRONG_INLINE Packet2cd Eigen::internal::psub< Packet2cd > (const Packet2cd & a, const Packet2cd & b)
template<> EIGEN_STRONG_INLINE Packet2cf Eigen::internal::psub< Packet2cf > (const Packet2cf & a, const Packet2cf & b)
References Eigen::internal::Packet2cf::Packet2cf().
Referenced by pscatter< std::complex< double >, Packet1cd >().
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::psub< Packet2d > (const Packet2d & a, const Packet2d & b)
References EIGEN_STRONG_INLINE, pnegate(), and psub< Packet4i >().
Referenced by pblend(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), and Eigen::internal::palign_impl< Offset, Packet2d >::run().
template<> EIGEN_STRONG_INLINE Packet4cf Eigen::internal::psub< Packet4cf > (const Packet4cf & a, const Packet4cf & b)
References Eigen::internal::Packet4cf::Packet4cf().
template<> EIGEN_STRONG_INLINE Packet4d Eigen::internal::psub< Packet4d > (const Packet4d & a, const Packet4d & b)
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::psub< Packet4f > (const Packet4f & a, const Packet4f & b)
Referenced by padd< Packet2d >(), plset< Packet4i >(), pscatter< std::complex< double >, Packet1cd >(), and Eigen::internal::palign_impl< Offset, Packet2d >::run().
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::psub< Packet4i > (const Packet4i & a, const Packet4i & b)
Referenced by plset< Packet4i >(), psub< Packet2d >(), and Eigen::internal::palign_impl< Offset, Packet2d >::run().
template<> EIGEN_STRONG_INLINE Packet8d Eigen::internal::psub< Packet8d > (const Packet8d & a, const Packet8d & b)
template<> EIGEN_STRONG_INLINE Packet8f Eigen::internal::psub< Packet8f > (const Packet8f & a, const Packet8f & b)
template<typename Packet > EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet Eigen::internal::ptan (const Packet & a)
References EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS, and tan().
Referenced by Eigen::internal::scalar_tan_op< Scalar >::packetOp().
template<typename Packet > EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet Eigen::internal::ptanh (const Packet & a)
References EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS, and tanh().
Referenced by Eigen::internal::scalar_tanh_op< Scalar >::packetOp().
template<> EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet4f Eigen::internal::ptanh< Packet4f > (const Packet4f & x)
References generic_fast_tanh_float().
template<> EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet8f Eigen::internal::ptanh< Packet8f > (const Packet8f & x)
References EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS, EIGEN_UNUSED, and generic_fast_tanh_float().
EIGEN_STRONG_INLINE void Eigen::internal::ptranspose (PacketBlock< Packet2cf, 2 > & kernel) inline
References Eigen::Aligned16, EIGEN_ALIGN16, EIGEN_MAKE_CONJ_HELPER_CPLX_REAL, EIGEN_PPC_PREFETCH, EIGEN_STRONG_INLINE, p16uc_PSET64_HI, p16uc_PSET64_LO, p16uc_REVERSE64, p16uc_TRANSPOSE64_HI, p16uc_TRANSPOSE64_LO, Eigen::internal::PacketBlock< Packet, N >::packet, padd(), padd< Packet1cd >(), padd< Packet2d >(), pand(), pand< Packet1cd >(), pandnot(), pandnot< Packet1cd >(), pblend(), pconj(), pcplxflip(), pdiv(), pdiv< Packet1cd >(), pfirst(), pfirst< Packet1cd >(), pload< Packet1cd >(), pload< Packet2d >(), ploaddup< Packet1cd >(), ploadu< Packet1cd >(), ploadu< Packet2d >(), pmadd(), pmul(), pmul< Packet1cd >(), pmul< Packet2d >(), pnegate(), por(), por< Packet1cd >(), predux< Packet1cd >(), predux_mul< Packet1cd >(), preduxp< Packet1cd >(), preverse(), pset1< Packet1cd >(), pstore(), pstoreu(), psub< Packet1cd >(), pxor(), pxor< Packet1cd >(), size(), type, Eigen::internal::Packet2cf::v, and Eigen::internal::Packet1cd::v.
Referenced by Eigen::internal::gemm_pack_lhs< Scalar, Index, DataMapper, Pack1, Pack2, RowMajor, Conjugate, PanelMode >::operator()(), Eigen::internal::gemm_pack_rhs< Scalar, Index, DataMapper, nr, ColMajor, Conjugate, PanelMode >::operator()(), pabs< Packet4f >(), pblend(), pcplxflip(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), pscatter< std::complex< double >, Packet1cd >(), ptranspose(), Eigen::internal::inplace_transpose_selector< MatrixType, true, true >::run(), and Eigen::internal::palign_impl< Offset, Packet2d >::run().
EIGEN_STRONG_INLINE void Eigen::internal::ptranspose (PacketBlock< Packet1cd, 2 > & kernel)
References EIGEN_STRONG_INLINE, p16uc_TRANSPOSE64_HI, p16uc_TRANSPOSE64_LO, Eigen::internal::PacketBlock< Packet, N >::packet, pblend(), ptranspose(), Eigen::internal::Selector< N >::select, and Eigen::internal::Packet2cf::v.
EIGEN_DEVICE_FUNC void Eigen::internal::ptranspose (PacketBlock< Packet4cf, 4 > & kernel) inline
References Eigen::internal::PacketBlock< Packet, N >::packet.
EIGEN_DEVICE_FUNC void Eigen::internal::ptranspose (PacketBlock< Packet2cd, 2 > & kernel) inline
References Eigen::internal::PacketBlock< Packet, N >::packet.
EIGEN_DEVICE_FUNC void Eigen::internal::ptranspose (PacketBlock< Packet8f, 8 > & kernel) inline
References Eigen::internal::PacketBlock< Packet, N >::packet.
template<typename Packet > EIGEN_DEVICE_FUNC void Eigen::internal::ptranspose (PacketBlock< Packet, 1 > &) inline
EIGEN_DEVICE_FUNC void Eigen::internal::ptranspose (PacketBlock< Packet8f, 4 > & kernel) inline
References Eigen::internal::PacketBlock< Packet, N >::packet.
EIGEN_DEVICE_FUNC void Eigen::internal::ptranspose (PacketBlock< Packet4d, 4 > & kernel) inline
References Eigen::internal::PacketBlock< Packet, N >::packet.
EIGEN_DEVICE_FUNC void Eigen::internal::ptranspose (PacketBlock< Packet4f, 4 > & kernel) inline
References Eigen::internal::PacketBlock< Packet, N >::packet.
EIGEN_DEVICE_FUNC void Eigen::internal::ptranspose (PacketBlock< Packet4i, 4 > & kernel) inline
References Eigen::internal::PacketBlock< Packet, N >::packet.
EIGEN_DEVICE_FUNC void Eigen::internal::ptranspose (PacketBlock< Packet2d, 2 > & kernel) inline
References EIGEN_STRONG_INLINE, Eigen::internal::PacketBlock< Packet, N >::packet, pblend(), ptranspose(), select(), and Eigen::internal::Selector< N >::select.
EIGEN_DEVICE_FUNC void Eigen::internal::ptranspose (PacketBlock< Packet16f, 16 > & kernel) inline
References EIGEN_EXTRACT_8f_FROM_16f, PACK_OUTPUT, and Eigen::internal::PacketBlock< Packet, N >::packet.
EIGEN_DEVICE_FUNC void Eigen::internal::ptranspose (PacketBlock< Packet16f, 4 > & kernel) inline
References EIGEN_EXTRACT_8f_FROM_16f, PACK_OUTPUT_2, and Eigen::internal::PacketBlock< Packet, N >::packet.
EIGEN_DEVICE_FUNC void Eigen::internal::ptranspose (PacketBlock< Packet8d, 4 > & kernel) inline
References PACK_OUTPUT_D, and Eigen::internal::PacketBlock< Packet, N >::packet.
EIGEN_DEVICE_FUNC void Eigen::internal::ptranspose (PacketBlock< Packet8d, 8 > & kernel) inline
References PACK_OUTPUT_SQ_D, and Eigen::internal::PacketBlock< Packet, N >::packet.
EIGEN_STRONG_INLINE void Eigen::internal::punpackp (Packet4f * vecs)
References EIGEN_STRONG_INLINE, preduxp< Packet2d >(), and preduxp< Packet4f >().
template<typename Packet > EIGEN_DEVICE_FUNC Packet Eigen::internal::pxor (const Packet & a, const Packet & b) inline
Referenced by pmul< Packet2cf >(), ptranspose(), and Eigen::internal::quat_product< Architecture::SSE, Derived, OtherDerived, double >::run().
template<> EIGEN_STRONG_INLINE Packet16f Eigen::internal::pxor< Packet16f > (const Packet16f & a, const Packet16f & b)
template<> EIGEN_STRONG_INLINE Packet1cd Eigen::internal::pxor< Packet1cd > (const Packet1cd & a, const Packet1cd & b)
Referenced by Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), pscatter< std::complex< double >, Packet1cd >(), and ptranspose().
template<> EIGEN_STRONG_INLINE Packet2cd Eigen::internal::pxor< Packet2cd > (const Packet2cd & a, const Packet2cd & b)
template<> EIGEN_STRONG_INLINE Packet2cf Eigen::internal::pxor< Packet2cf > (const Packet2cf & a, const Packet2cf & b)
References Eigen::internal::Packet2cf::Packet2cf(), and pxor< Packet4f >().
Referenced by pscatter< std::complex< double >, Packet1cd >().
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::pxor< Packet2d > (const Packet2d & a, const Packet2d & b)
References EIGEN_STRONG_INLINE, pandnot< Packet4f >(), and pxor< Packet4i >().
Referenced by pblend(), and pmadd().
template<> EIGEN_STRONG_INLINE Packet4cf Eigen::internal::pxor< Packet4cf > (const Packet4cf & a, const Packet4cf & b)
References Eigen::internal::Packet4cf::Packet4cf().
template<> EIGEN_STRONG_INLINE Packet4d Eigen::internal::pxor< Packet4d > (const Packet4d & a, const Packet4d & b)
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::pxor< Packet4f > (const Packet4f & a, const Packet4f & b)
Referenced by pconj(), plset< Packet4i >(), pmadd(), por< Packet2d >(), pscatter< std::complex< double >, Packet1cd >(), and pxor< Packet2cf >().
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::pxor< Packet4i > (const Packet4i & a, const Packet4i & b)
Referenced by plset< Packet4i >(), pmadd(), and pxor< Packet2d >().
template<> EIGEN_STRONG_INLINE Packet8d Eigen::internal::pxor< Packet8d > (const Packet8d & a, const Packet8d & b)
template<> EIGEN_STRONG_INLINE Packet8f Eigen::internal::pxor< Packet8f > (const Packet8f & a, const Packet8f & b)
void Eigen::internal::queryCacheSizes (int & l1, int & l2, int & l3) inline
Referenced by Eigen::internal::CacheSizes::CacheSizes(), queryL1CacheSize(), and queryTopLevelCacheSize().
int Eigen::internal::queryL1CacheSize () inline
References queryCacheSizes().
int Eigen::internal::queryTopLevelCacheSize () inline
References Eigen::half_impl::max(), and queryCacheSizes().
template<typename VectorV , typename VectorI > Index Eigen::internal::QuickSplit (VectorV & row, VectorI & ind, Index ncut)
References abs(), first(), Eigen::placeholders::last, row(), swap(), and std::swap().
Referenced by Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::factorize(), and Eigen::IncompleteLUT< _Scalar, _StorageIndex >::factorize().
template<typename Decomposition > Decomposition::RealScalar Eigen::internal::rcond_estimate_helper (typename Decomposition::RealScalar matrix_norm, const Decomposition & dec)
Reciprocal condition number estimator.
Computing a decomposition of a dense matrix takes O(n^3) operations, while this method estimates the condition number quickly and reliably in O(n^2) operations.
Returns
an estimate of the reciprocal condition number (1 / (||matrix||_1 * ||inv(matrix)||_1)) of matrix, given ||matrix||_1 and its decomposition. Supports the following decompositions: FullPivLU, PartialPivLU, LDLT, and LLT.
See also
FullPivLU, PartialPivLU, LDLT, LLT.
References eigen_assert, and rcond_invmatrix_L1_norm_estimate().
Referenced by Eigen::LLT< _MatrixType, _UpLo >::rcond(), Eigen::PartialPivLU< _MatrixType >::rcond(), Eigen::LDLT< _MatrixType, _UpLo >::rcond(), and Eigen::FullPivLU< _MatrixType >::rcond().
template<typename Decomposition > Decomposition::RealScalar Eigen::internal::rcond_invmatrix_L1_norm_estimate (const Decomposition & dec)
Returns
an estimate of ||inv(matrix)||_1 given a decomposition of matrix that implements .solve() and .adjoint().solve() methods.
This function implements Algorithms 4.1 and 5.1 from http://www.maths.manchester.ac.uk/~higham/narep/narep135.pdf which also forms the basis for the condition number estimators in LAPACK. Since at most 10 calls to the solve method of dec are performed, the total cost is O(dims^2), as opposed to O(dims^3) needed to compute the inverse matrix explicitly.
The most common usage is in estimating the condition number ||matrix||_1 * ||inv(matrix)||_1. The first term ||matrix||_1 can be computed directly in O(n^2) operations.
Supports the following decompositions: FullPivLU, PartialPivLU, LDLT, and LLT.
See also
FullPivLU, PartialPivLU, LDLT, LLT.
References eigen_assert, i, and Eigen::internal::rcond_compute_sign< Vector, RealVector, IsComplex >::run().
Referenced by rcond_estimate_helper().
template<typename MatrixType , typename RealScalar , typename Index > void Eigen::internal::real_2x2_jacobi_svd (const MatrixType & matrix, Index p, Index q, JacobiRotation< RealScalar > * j_left, JacobiRotation< RealScalar > * j_right)
References abs(), abs2(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::coeff(), m, Eigen::JacobiRotation< Scalar >::makeJacobi(), Eigen::half_impl::min(), real(), sqrt(), and Eigen::JacobiRotation< Scalar >::transpose().
Referenced by Eigen::RealQZ< _MatrixType >::compute(), and Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::compute().
template<typename DstXprType , typename SrcXprType , typename Functor > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::resize_if_allowed (DstXprType & dst, const SrcXprType & src, const Functor &)
References eigen_assert, EIGEN_ONLY_USED_FOR_DEBUG, and EIGEN_STRONG_INLINE.
Referenced by call_dense_assignment_loop(), and Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, Sparse2Dense >::run().
template<typename DstXprType , typename SrcXprType , typename T1 , typename T2 > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::resize_if_allowed (DstXprType & dst, const SrcXprType & src, const internal::assign_op< T1, T2 > &)
References eigen_assert.
template<typename T > const T* Eigen::internal::return_ptr ()
template<typename InputIterator , typename SparseMatrixType , typename DupFunctor > void Eigen::internal::set_from_triplets (const InputIterator & begin, const InputIterator & end, SparseMatrixType & mat, DupFunctor dup_func)
References eigen_assert, Eigen::placeholders::end(), it, and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::setZero().
template<typename T > Index Eigen::internal::size (const T & x)
Referenced by Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_resize_to_match(), Eigen::CholmodBase< _MatrixType, _UpLo, CholmodSimplicialLLT< _MatrixType, _UpLo > >::_solve_impl(), Eigen::IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::_solve_impl(), Eigen::SuperLU< _MatrixType >::_solve_impl(), Eigen::SimplicialCholesky< _MatrixType, _UpLo, _Ordering >::_solve_impl(), aligned_delete(), aligned_new(), Eigen::SimplicialCholeskyBase< SimplicialLDLT< _MatrixType, _UpLo, _Ordering > >::analyzePattern(), Eigen::SimplicialCholeskyBase< Derived >::analyzePattern_preordered(), apply_rotation_in_the_plane(), Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex > >::applyTranspositionOnTheLeft(), Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex > >::applyTranspositionOnTheRight(), Eigen::internal::llt_inplace< Scalar, Lower >::blocked(), LinkedList< T >::clear(), Eigen::DenseCoeffsBase< Derived, ReadOnlyAccessors >::coeff(), Eigen::DenseCoeffsBase< Derived, WriteAccessors >::coeffRef(), Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex > >::cols(), Eigen::IndexedView< XprType, RowIndices, ColIndices >::cols(), Eigen::SimplicialCholeskyBase< SimplicialLDLT< _MatrixType, _UpLo, _Ordering > >::compute(), Eigen::GeneralizedEigenSolver< _MatrixType >::compute(), Eigen::LLT< _MatrixType, _UpLo >::compute(), Eigen::LDLT< _MatrixType, _UpLo >::compute(), Eigen::HouseholderQR< _MatrixType >::computeInPlace(), Eigen::FullPivHouseholderQR< _MatrixType >::computeInPlace(), Eigen::ColPivHouseholderQR< _MatrixType >::computeInPlace(), Eigen::RealSchur< _MatrixType >::computeNormOfT(), Eigen::RealQZ< _MatrixType >::computeNorms(), conditional_aligned_delete(), conditional_aligned_delete_auto(), conditional_aligned_malloc< false >(), conditional_aligned_new(), conditional_aligned_new_auto(), Eigen::DenseStorage< T, Dynamic, Dynamic, Dynamic, _Options >::conservativeResize(), Eigen::DenseStorage< T, Dynamic, _Rows, Dynamic, _Options >::conservativeResize(), Eigen::DenseStorage< T, Dynamic, Dynamic, _Cols, _Options >::conservativeResize(), construct_elements_of_array(), LinkedList< T >::contains(), ArgumentParser::count(), Eigen::DenseStorage< Scalar, Base::MaxSizeAtCompileTime, Base::RowsAtCompileTime, Base::ColsAtCompileTime, Options >::DenseStorage(), Eigen::DenseStorage< T, Dynamic, Dynamic, Dynamic, _Options >::DenseStorage(), Eigen::DenseStorage< T, Dynamic, _Rows, Dynamic, _Options >::DenseStorage(), Eigen::DenseStorage< T, Dynamic, Dynamic, _Cols, _Options >::DenseStorage(), destruct_elements_of_array(), Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex > >::determinant(), Eigen::SuperLU< _MatrixType >::determinant(), Eigen::EigenSolver< _MatrixType >::doComputeEigenvectors(), Eigen::SparseMatrixBase< Derived >::dot(), Eigen::MatrixBase< Derived >::dot(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::erase(), Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::evalTo(), Eigen::SuperLUBase< _MatrixType, Derived >::extractData(), Eigen::SimplicialCholeskyBase< SimplicialLDLT< _MatrixType, _UpLo, _Ordering > >::factorize(), Eigen::SimplicialCholeskyBase< Derived >::factorize_preordered(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::finalize(), first_aligned(), first_default_aligned(), Eigen::HessenbergDecomposition< MatrixType >::HessenbergDecomposition(), Eigen::MatrixBase< Derived >::hnormalized(), householder_qr_inplace_unblocked(), Eigen::SuperLUBase< _MatrixType, SuperLU< _MatrixType > >::initFactorization(), Eigen::DenseBase< Derived >::innerSize(), ivcSize(), Eigen::CholmodBase< _MatrixType, _UpLo, CholmodSimplicialLLT< _MatrixType, _UpLo > >::logDeterminant(), Eigen::MatrixBase< Derived >::makeHouseholder(), Eigen::MatrixBase< Derived >::makeHouseholderInPlace(), makeIndexedViewCompatible(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::MapAligned(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::max_size(), Eigen::DenseBase< Derived >::mean(), Eigen::DenseBase< Derived >::nonZeros(), Eigen::DenseBase< Derived >::NullaryExpr(), operator()(), Eigen::internal::tribb_kernel< LhsScalar, RhsScalar, Index, mr, nr, ConjLhs, ConjRhs, UpLo >::operator()(), Eigen::DenseCoeffsBase< Derived, ReadOnlyAccessors >::operator()(), Eigen::DenseCoeffsBase< Derived, WriteAccessors >::operator()(), Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex > >::operator=(), Eigen::DenseCoeffsBase< Derived, ReadOnlyAccessors >::operator[](), Eigen::DenseCoeffsBase< Derived, WriteAccessors >::operator[](), Eigen::SimplicialCholeskyBase< Derived >::ordering(), Eigen::RefBase< Ref< PlainObjectType, Options, StrideType > >::outerStride(), Eigen::Map< SparseMatrix< _Scalar, _Flags, _StorageIndex > >::outerStride(), Eigen::DenseCoeffsBase< Derived, ReadOnlyAccessors >::packet(), parallelize_gemm(), Eigen::RealSchur< _MatrixType >::performFrancisQRStep(), permute_symm_to_fullsymm(), permute_symm_to_symm(), pinsertfirst(), pinsertlast(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), Eigen::DenseBase< Derived >::prod(), ptranspose(), Eigen::LDLT< _MatrixType, _UpLo >::rankUpdate(), Eigen::LDLT< _MatrixType, _UpLo >::reconstructedMatrix(), std::deque< T, EIGEN_ALIGNED_ALLOCATOR< T > >::resize(), std::vector< T, EIGEN_ALIGNED_ALLOCATOR< T > >::resize(), std::list< T, EIGEN_ALIGNED_ALLOCATOR< T > >::resize(), Eigen::DenseBase< Derived >::resize(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::resize(), Eigen::DenseStorage< T, Dynamic, Dynamic, Dynamic, _Options >::resize(), Eigen::DenseStorage< T, Dynamic, _Rows, Dynamic, _Options >::resize(), Eigen::DenseStorage< T, Dynamic, Dynamic, _Cols, _Options >::resize(), Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex > >::rows(), Eigen::IndexedView< XprType, RowIndices, ColIndices >::rows(), Eigen::selfadjoint_rank1_update< Scalar, Index, ColMajor, UpLo, ConjLhs, ConjRhs >::run(), Eigen::internal::selfadjoint_rank2_update_selector< Scalar, Index, UType, VType, Lower >::run(), Eigen::internal::triangular_matrix_vector_product< Index, Mode, LhsScalar, ConjLhs, RhsScalar, ConjRhs, ColMajor, Version >::run(), Eigen::internal::selfadjoint_matrix_vector_product< Scalar, Index, StorageOrder, UpLo, ConjugateLhs, ConjugateRhs, Version >::run(), Eigen::internal::selfadjoint_rank2_update_selector< Scalar, Index, UType, VType, Upper >::run(), Eigen::internal::general_matrix_matrix_triangular_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor, UpLo, Version >::run(), Eigen::selfadjoint_product_selector< MatrixType, OtherType, UpLo, false >::run(), Eigen::internal::triangular_solver_selector< Lhs, Rhs, Side, Mode, NoUnrolling, Dynamic >::run(), Eigen::internal::selfadjoint_product_impl< Lhs, LhsMode, false, Rhs, 0, true >::run(), Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, Diagonal2Sparse >::run(), Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheRight, Mode, Conjugate, TriStorageOrder, ColMajor >::run(), Eigen::internal::trmv_selector< Mode, ColMajor >::run(), Eigen::internal::gemv_dense_selector< OnTheRight, ColMajor, true >::run(), Eigen::internal::redux_impl< Func, Derived, LinearVectorizedTraversal, NoUnrolling >::run(), Eigen::general_product_to_triangular_selector< MatrixType, ProductType, UpLo, false >::run(), Eigen::internal::trmv_selector< Mode, RowMajor >::run(), Eigen::internal::householder_qr_inplace_blocked< MatrixQR, HCoeffs, MatrixQRScalar, InnerStrideIsOne >::run(), Eigen::internal::gemv_dense_selector< OnTheRight, RowMajor, true >::run(), Eigen::internal::product_selfadjoint_matrix< Scalar, Index, LhsStorageOrder, true, ConjugateLhs, RhsStorageOrder, false, ConjugateRhs, ColMajor >::run(), Eigen::internal::apply_rotation_in_the_plane_selector< Scalar, OtherScalar, SizeAtCompileTime, MinAlignment, Vectorizable >::run(), Eigen::internal::apply_rotation_in_the_plane_selector< Scalar, OtherScalar, SizeAtCompileTime, MinAlignment, true >::run(), Eigen::internal::gemv_dense_selector< OnTheRight, ColMajor, false >::run(), Eigen::internal::dense_assignment_loop< Kernel, LinearVectorizedTraversal, NoUnrolling >::run(), Eigen::internal::product_selfadjoint_matrix< Scalar, Index, LhsStorageOrder, false, ConjugateLhs, RhsStorageOrder, true, ConjugateRhs, ColMajor >::run(), Eigen::internal::dense_assignment_loop< Kernel, LinearVectorizedTraversal, CompleteUnrolling >::run(), Eigen::internal::smart_copy_helper< T, true >::run(), Eigen::internal::dense_assignment_loop< Kernel, LinearTraversal, NoUnrolling >::run(), Eigen::internal::smart_memmove_helper< T, true >::run(), Eigen::internal::dense_assignment_loop< Kernel, SliceVectorizedTraversal, NoUnrolling >::run(), Eigen::internal::setIdentity_impl< Derived, true >::run(), Eigen::internal::conservative_resize_like_impl< Derived, OtherDerived, true >::run(), Eigen::internal::transposition_matrix_product< ExpressionType, Side, Transposed, ExpressionShape >::run(), Eigen::internal::scoped_array< T >::scoped_array(), Eigen::seqN(), Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex > >::setIdentity(), Eigen::DenseBase< Derived >::setLinSpaced(), Eigen::BDCSVD< _MatrixType >::setSwitchSize(), Eigen::MatrixBase< Derived >::setUnit(), solve_sparse_through_dense_panels(), Eigen::RealSchur< _MatrixType >::splitOffTwoRows(), Eigen::MatrixBase< Derived >::stableNorm(), Eigen::DenseBase< Derived >::sum(), tail(), Eigen::internal::ldlt_inplace< Lower >::unblocked(), Eigen::internal::llt_inplace< Scalar, Lower >::unblocked(), Eigen::internal::ldlt_inplace< Lower >::updateInPlace(), and upperbidiagonalization_inplace_blocked().
template<typename T , std::size_t N> Index Eigen::internal::size (const T(&)[N])
References N, and type.
template<typename T > EIGEN_DEVICE_FUNC void Eigen::internal::smart_copy (const T * start, const T * end, T * target)
Referenced by Eigen::internal::CompressedStorage< Scalar, StorageIndex >::atWithInsertion(), Eigen::DenseStorage< T, Dynamic, Dynamic, Dynamic, _Options >::DenseStorage(), Eigen::DenseStorage< T, Dynamic, _Rows, Dynamic, _Options >::DenseStorage(), Eigen::DenseStorage< T, Dynamic, Dynamic, _Cols, _Options >::DenseStorage(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::operator=(), Eigen::internal::sparse_matrix_block_impl< const SparseMatrix< _Scalar, _Options, _StorageIndex >, BlockRows, BlockCols >::operator=(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::operator=(), and Eigen::internal::CompressedStorage< Scalar, StorageIndex >::reallocate().
template<typename T > void Eigen::internal::smart_memmove (const T * start, const T * end, T * target)
Referenced by Eigen::internal::CompressedStorage< Scalar, StorageIndex >::atWithInsertion(), and Eigen::internal::sparse_matrix_block_impl< const SparseMatrix< _Scalar, _Options, _StorageIndex >, BlockRows, BlockCols >::operator=().
template<typename Decomposition , typename Rhs , typename Dest > enable_if<Rhs::ColsAtCompileTime!=1 && Dest::ColsAtCompileTime!=1>::type Eigen::internal::solve_sparse_through_dense_panels (const Decomposition & dec, const Rhs & rhs, Dest & dest)
References EIGEN_STATIC_ASSERT, Eigen::half_impl::min(), Eigen::RowMajorBit, and size().
Referenced by Eigen::SparseSolverBase< SimplicialLDLT< _MatrixType, _UpLo, _Ordering > >::_solve_impl(), Eigen::SimplicialCholeskyBase< SimplicialLDLT< _MatrixType, _UpLo, _Ordering > >::_solve_impl(), and Eigen::SimplicialCholesky< _MatrixType, _UpLo, _Ordering >::_solve_impl().
template<typename Decomposition , typename Rhs , typename Dest > enable_if<Rhs::ColsAtCompileTime==1 || Dest::ColsAtCompileTime==1>::type Eigen::internal::solve_sparse_through_dense_panels (const Decomposition & dec, const Rhs & rhs, Dest & dest)
References size().
template<int Mode, typename SparseLhsType , typename DenseRhsType , typename DenseResType , typename AlphaType > void Eigen::internal::sparse_selfadjoint_time_dense_product (const SparseLhsType & lhs, const DenseRhsType & rhs, DenseResType & res, const AlphaType & alpha) inline
References EIGEN_ONLY_USED_FOR_DEBUG, i, Eigen::Lower, Eigen::RowMajorBit, and Eigen::Upper.
template<typename Lhs , typename Rhs , typename ResultType > static void Eigen::internal::sparse_sparse_product_with_pruning_impl (const Lhs & lhs, const Rhs & rhs, ResultType & res, const typename ResultType::RealScalar & tolerance) static
References eigen_assert, it, and Eigen::RowMajorBit.
template<typename Lhs , typename Rhs , typename ResultType > static void Eigen::internal::sparse_sparse_to_dense_product_impl (const Lhs & lhs, const Rhs & rhs, ResultType & res) static
References Eigen::ColMajor, eigen_assert, i, Eigen::RowMajor, and Eigen::RowMajorBit.
template<typename SparseLhsType , typename DenseRhsType , typename DenseResType , typename AlphaType > void Eigen::internal::sparse_time_dense_product (const SparseLhsType & lhs, const DenseRhsType & rhs, DenseResType & res, const AlphaType & alpha) inline
Referenced by Eigen::internal::generic_product_impl< Lhs, Rhs, SparseShape, DenseShape, ProductType >::scaleAndAddTo(), and Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, SparseShape, ProductType >::scaleAndAddTo().
template<typename Scalar > EIGEN_DONT_INLINE void Eigen::internal::sparselu_gemm (Index m, Index n, Index d, const Scalar * A, Index lda, const Scalar * B, Index ldb, Scalar * C, Index ldc)
References Eigen::Aligned, EIGEN_ARCH_DEFAULT_NUMBER_OF_REGISTERS, EIGEN_ASM_COMMENT, eigen_internal_assert, first_default_aligned(), i, m, prefetch(), and WORK.
template<typename ExpressionType , typename Scalar > void Eigen::internal::stable_norm_kernel (const ExpressionType & bl, Scalar & ssq, Scalar & scale, Scalar & invScale) inline
References abs2().
Referenced by Eigen::MatrixBase< Derived >::stableNorm().
template<typename T > void Eigen::internal::swap (scoped_array< T > & a, scoped_array< T > & b)
References Eigen::internal::scoped_array< T >::ptr(), and std::swap().
Referenced by Eigen::internal::swap_assign_op< DstEvaluatorTypeT::Scalar >::assignCoeff(), Eigen::BDCSVD< _MatrixType >::computeSingVals(), Eigen::BDCSVD< _MatrixType >::computeSVDofM(), Eigen::BDCSVD< _MatrixType >::deflation(), Eigen::IncompleteLUT< _Scalar, _StorageIndex >::factorize(), Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::DenseStorage< T, Dynamic, Dynamic, Dynamic, _Options >::operator=(), Eigen::DenseStorage< T, Dynamic, _Rows, Dynamic, _Options >::operator=(), Eigen::DenseStorage< T, Dynamic, Dynamic, _Cols, _Options >::operator=(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::operator=(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::PlainObjectBase(), QuickSplit(), Eigen::internal::inplace_transpose_selector< MatrixType, true, false >::run(), Eigen::internal::inplace_transpose_selector< MatrixType, false, MatchPacketSize >::run(), Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, DenseShape >::run(), Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::solveInPlace(), and Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::swap().
EIGEN_DEVICE_FUNC void Eigen::internal::throw_std_bad_alloc () inline
Referenced by aligned_malloc(), aligned_realloc(), check_size_for_overflow(), conditional_aligned_malloc< false >(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::conservativeResize(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insert(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::reserveInnerVectors(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::resize(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::resize(), and Eigen::internal::check_rows_cols_for_overflow< Dynamic >::run().
template<typename Scalar , int Dim> static EIGEN_DEVICE_FUNC Matrix<Scalar,2,2> Eigen::internal::toRotationMatrix (const Scalar & s) inline static
References EIGEN_STATIC_ASSERT.
Referenced by Eigen::RotationBase< Derived, 3 >::_transformVector(), Eigen::QuaternionBase< Quaternion< _Scalar, _Options > >::dot(), Eigen::AngleAxis< _Scalar >::inverse(), Eigen::RotationBase< Derived, 3 >::operator*(), and Eigen::Rotation2D< _Scalar >::operator*().
template<typename Scalar , int Dim, typename OtherDerived > static EIGEN_DEVICE_FUNC Matrix<Scalar,Dim,Dim> Eigen::internal::toRotationMatrix (const RotationBase< OtherDerived, Dim > & r) inline static
References Eigen::RotationBase< Derived, _Dim >::toRotationMatrix().
template<typename Scalar , int Dim, typename OtherDerived > static EIGEN_DEVICE_FUNC const MatrixBase<OtherDerived>& Eigen::internal::toRotationMatrix (const MatrixBase< OtherDerived > & mat) inline static
References EIGEN_STATIC_ASSERT.
template<typename IndexVector > void Eigen::internal::treePostorder (typename IndexVector::Scalar n, IndexVector & parent, IndexVector & post)
Post order a tree.
Parameters
n the number of nodes
parent Input tree
post postordered tree
References nr_etdfs().
Referenced by Eigen::SparseLU< _MatrixType, _OrderingType >::analyzePattern(), and Eigen::internal::SparseLUImpl< Scalar, StorageIndex >::heap_relax_snode().
template<int StorageOrder, typename RealScalar , typename Scalar , typename Index > static EIGEN_DEVICE_FUNC void Eigen::internal::tridiagonal_qr_step (RealScalar * diag, RealScalar * subdiag, Index start, Index end, Scalar * matrixQ, Index n) static
References abs(), abs2(), Eigen::JacobiRotation< Scalar >::c(), e, Eigen::placeholders::end(), Eigen::JacobiRotation< Scalar >::makeGivens(), and Eigen::JacobiRotation< Scalar >::s().
template<typename MatrixType , typename CoeffVectorType > void Eigen::internal::tridiagonalization_inplace (MatrixType & matA, CoeffVectorType & hCoeffs)
References eigen_assert, and i.
Referenced by Eigen::Tridiagonalization< _MatrixType >::compute(), Eigen::SelfAdjointEigenSolver< _MatrixType >::compute(), Eigen::internal::tridiagonalization_inplace_selector< MatrixType, Size, IsComplex >::run(), and Eigen::Tridiagonalization< _MatrixType >::Tridiagonalization().
template<typename MatrixType , typename DiagonalType , typename SubDiagonalType > void Eigen::internal::tridiagonalization_inplace (MatrixType & mat, DiagonalType & diag, SubDiagonalType & subdiag, bool extractQ)
Performs a full tridiagonalization in place.
Parameters
[in,out] mat On input, the selfadjoint matrix whose tridiagonal decomposition is to be computed. Only the lower triangular part referenced. The rest is left unchanged. On output, the orthogonal matrix Q in the decomposition if extractQ is true.
[out] diag The diagonal of the tridiagonal matrix T in the decomposition.
[out] subdiag The subdiagonal of the tridiagonal matrix T in the decomposition.
[in] extractQ If true, the orthogonal matrix Q in the decomposition is computed and stored in mat.
Computes the tridiagonal decomposition of the selfadjoint matrix mat in place such that where is unitary and a real symmetric tridiagonal matrix.
The tridiagonal matrix T is passed to the output parameters diag and subdiag. If extractQ is true, then the orthogonal matrix Q is passed to mat. Otherwise the lower part of the matrix mat is destroyed.
The vectors diag and subdiag are not resized. The function assumes that they are already of the correct size. The length of the vector diag should equal the number of rows in mat, and the length of the vector subdiag should be one left.
This implementation contains an optimized path for 3-by-3 matrices which is especially useful for plane fitting.
Note
Currently, it requires two temporary vectors to hold the intermediate Householder coefficients, and to reconstruct the matrix Q from the Householder reflectors.
Example (this uses the same matrix as the example in Tridiagonalization::Tridiagonalization(const MatrixType&)):
Output:
See also
class Tridiagonalization
References eigen_assert, and Eigen::internal::tridiagonalization_inplace_selector< MatrixType, Size, IsComplex >::run().
template<typename MatrixType > void Eigen::internal::upperbidiagonalization_blocked_helper (MatrixType & A, typename MatrixType::RealScalar * diagonal, typename MatrixType::RealScalar * upper_diagonal, Index bs, Ref< Matrix< typename MatrixType::Scalar, Dynamic, Dynamic, traits< MatrixType >::Flags &RowMajorBit > > X, Ref< Matrix< typename MatrixType::Scalar, Dynamic, Dynamic, traits< MatrixType >::Flags &RowMajorBit > > Y)
References Eigen::RowMajorBit.
template<typename MatrixType , typename BidiagType > void Eigen::internal::upperbidiagonalization_inplace_blocked (MatrixType & A, BidiagType & bidiagonal, Index maxBlockSize = 32, typename MatrixType::Scalar * = 0)
References Eigen::Dynamic, Eigen::half_impl::min(), Eigen::RowMajorBit, size(), and upperbidiagonalization_inplace_unblocked().
Referenced by Eigen::internal::UpperBidiagonalization< _MatrixType >::compute().
template<typename MatrixType > void Eigen::internal::upperbidiagonalization_inplace_unblocked (MatrixType & mat, typename MatrixType::RealScalar * diagonal, typename MatrixType::RealScalar * upper_diagonal, typename MatrixType::Scalar * tempData = 0)
References Eigen::PlainObjectBase< Derived >::resize().
Referenced by Eigen::internal::UpperBidiagonalization< _MatrixType >::computeUnblocked(), and upperbidiagonalization_inplace_blocked().
template<typename Index > bool Eigen::internal::useSpecificBlockingSizes (Index & k, Index & m, Index & n) inline
References EIGEN_UNUSED_VARIABLE, and m.
Referenced by computeProductBlockingSizes().
template<int element> EIGEN_STRONG_INLINE Packet4f Eigen::internal::vec_splat_packet4f (const Packet4f & from)
References Eigen::internal::Packet4f::v4f.
Variable Documentation
const std::ptrdiff_t Eigen::internal::defaultL1CacheSize = 16*1024
Referenced by manage_caching_sizes_helper(), and Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::operator()().
const std::ptrdiff_t Eigen::internal::defaultL2CacheSize = 512*1024
Referenced by manage_caching_sizes_helper().
const std::ptrdiff_t Eigen::internal::defaultL3CacheSize = 512*1024
Referenced by manage_caching_sizes_helper().
Packet16uc Eigen::internal::p16uc_COMPLEX32_REV = vec_sld(p16uc_REVERSE32, p16uc_REVERSE32, 8) static
Referenced by pcplxflip< Packet2cf >(), pdiv< Packet2cf >(), and pmul< Packet2cf >().
Packet16uc Eigen::internal::p16uc_COMPLEX32_REV2 = vec_sld(p16uc_PSET64_HI, p16uc_PSET64_LO, 8) static
Referenced by preverse().
Packet16uc Eigen::internal::p16uc_DUPLICATE32_HI = { 0,1,2,3, 0,1,2,3, 4,5,6,7, 4,5,6,7 } static
Packet16uc Eigen::internal::p16uc_DUPLICATE32_HI = { 0,1,2,3, 0,1,2,3, 4,5,6,7, 4,5,6,7 } static
Packet16uc Eigen::internal::p16uc_FORWARD = p16uc_REVERSE32 static
Packet16uc Eigen::internal::p16uc_FORWARD = { 0,1,2,3, 4,5,6,7, 8,9,10,11, 12,13,14,15 } static
Packet16uc Eigen::internal::p16uc_HALF64_0_16 = vec_sld(vec_splat((Packet16uc) vec_abs(p4i_MINUS16), 0), (Packet16uc)p4i_ZERO, 8) static
Packet16uc Eigen::internal::p16uc_PSET32_WEVEN = vec_sld((Packet16uc) vec_splat((Packet4ui)p16uc_FORWARD, 0), (Packet16uc) vec_splat((Packet4ui)p16uc_FORWARD, 2), 8) static
Referenced by pmul< Packet2cf >().
Packet16uc Eigen::internal::p16uc_PSET32_WEVEN = vec_sld(p16uc_DUPLICATE32_HI, (Packet16uc) vec_splat((Packet4ui)p16uc_FORWARD, 3), 8) static
Packet16uc Eigen::internal::p16uc_PSET32_WODD = vec_sld((Packet16uc) vec_splat((Packet4ui)p16uc_FORWARD, 1), (Packet16uc) vec_splat((Packet4ui)p16uc_FORWARD, 3), 8) static
Referenced by pmul< Packet2cf >().
Packet16uc Eigen::internal::p16uc_PSET32_WODD = vec_sld((Packet16uc) vec_splat((Packet4ui)p16uc_FORWARD, 0), (Packet16uc) vec_splat((Packet4ui)p16uc_FORWARD, 2), 8) static
Packet16uc Eigen::internal::p16uc_PSET64_HI = { 0,1,2,3, 4,5,6,7, 0,1,2,3, 4,5,6,7 } static
Packet16uc Eigen::internal::p16uc_PSET64_HI = (Packet16uc) vec_mergeh((Packet4ui)p16uc_PSET32_WODD, (Packet4ui)p16uc_PSET32_WEVEN) static
Referenced by pscatter< std::complex< double >, Packet1cd >(), pset1< Packet2cf >(), and ptranspose().
Packet16uc Eigen::internal::p16uc_PSET64_LO = (Packet16uc) vec_mergel((Packet4ui)p16uc_PSET32_WODD, (Packet4ui)p16uc_PSET32_WEVEN) static
Referenced by pscatter< std::complex< double >, Packet1cd >(), and ptranspose().
Packet16uc Eigen::internal::p16uc_PSET64_LO = (Packet16uc) vec_mergel((Packet4ui)p16uc_PSET32_WODD, (Packet4ui)p16uc_PSET32_WEVEN) static
Packet16uc Eigen::internal::p16uc_REVERSE32 = { 12,13,14,15, 8,9,10,11, 4,5,6,7, 0,1,2,3 } static
Packet16uc Eigen::internal::p16uc_REVERSE32 = { 12,13,14,15, 8,9,10,11, 4,5,6,7, 0,1,2,3 } static
Packet16uc Eigen::internal::p16uc_REVERSE64 = { 8,9,10,11, 12,13,14,15, 0,1,2,3, 4,5,6,7 } static
Referenced by Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), and ptranspose().
Packet16uc Eigen::internal::p16uc_REVERSE64 = { 8,9,10,11, 12,13,14,15, 0,1,2,3, 4,5,6,7 } static
Packet16uc Eigen::internal::p16uc_TRANSPOSE64_HI = p16uc_PSET64_HI + p16uc_HALF64_0_16 static
Referenced by ptranspose().
Packet16uc Eigen::internal::p16uc_TRANSPOSE64_HI = { 0,1,2,3, 4,5,6,7, 16,17,18,19, 20,21,22,23} static
Packet16uc Eigen::internal::p16uc_TRANSPOSE64_LO = p16uc_PSET64_LO + p16uc_HALF64_0_16 static
Referenced by ptranspose().
Packet16uc Eigen::internal::p16uc_TRANSPOSE64_LO = { 8,9,10,11, 12,13,14,15, 24,25,26,27, 28,29,30,31} static
Packet2d Eigen::internal::p2d_COUNTDOWN = reinterpret_cast<Packet2d>(vec_sld(reinterpret_cast<Packet16uc>(p2d_ZERO), reinterpret_cast<Packet16uc>(p2d_ONE), 8)) static
Referenced by pblend().
Packet2d Eigen::internal::p2d_ONE = { 1.0, 1.0 } static
Referenced by pblend().
Packet2d Eigen::internal::p2d_ZERO_ = { -0.0, -0.0 } static
Referenced by Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul().
Packet2ul Eigen::internal::p2ul_CONJ_XOR1 = (Packet2ul) vec_sld((Packet4ui) p2d_ZERO_, (Packet4ui) p2l_ZERO, 8) static
Packet2ul Eigen::internal::p2ul_CONJ_XOR2 = (Packet2ul) vec_sld((Packet4ui) p2l_ZERO, (Packet4ui) p2d_ZERO_, 8) static
Packet4f Eigen::internal::p4f_COUNTDOWN = { 0.0, 1.0, 2.0, 3.0 } static
Packet4f Eigen::internal::p4f_COUNTDOWN = { 0.0, 1.0, 2.0, 3.0 } static
Packet4f Eigen::internal::p4f_MZERO = (Packet4f) vec_sl((Packet4ui)p4i_MINUS1, (Packet4ui)p4i_MINUS1) static
Packet4f Eigen::internal::p4f_ONE = vec_ctf(p4i_ONE, 0) static
Packet4i Eigen::internal::p4i_COUNTDOWN = { 0, 1, 2, 3 } static
Packet4i Eigen::internal::p4i_COUNTDOWN = { 0, 1, 2, 3 } static
Packet4ui Eigen::internal::p4ui_CONJ_XOR = vec_mergeh((Packet4ui)p4i_ZERO, (Packet4ui)p4f_MZERO) static