SmartMouse_2018: smartmouse::msgs Namespace Reference
smartmouse::msgs Namespace Reference
Typedefs
typedef std::vector< smartmouse::msgs::WallPoints > maze_walls_t[smartmouse::maze::SIZE][smartmouse::maze::SIZE]
Functions
smartmouse::msgs::Maze Convert (AbstractMaze *maze, std::string name, int size)
AbstractMaze Convert (smartmouse::msgs::Maze maze_msg)
::Direction Convert (smartmouse::msgs::Direction dir_msg)
::Direction Convert (smartmouse::msgs::Direction::Dir dir_enum)
RobotDescription Convert (std::ifstream &fs)
double ConvertSec (ignition::msgs::Time time)
unsigned long ConvertMSec (ignition::msgs::Time time)
void Convert (smartmouse::msgs::Maze maze, maze_walls_t &maze_lines)
std::tuple< double, double, double, double > WallToCoordinates (smartmouse::msgs::Wall wall)
ignition::msgs::Time Convert (int time_millis)
Typedef Documentation
typedef std::vector<smartmouse::msgs::WallPoints> smartmouse::msgs::maze_walls_t[smartmouse::maze::SIZE][smartmouse::maze::SIZE]
Function Documentation
smartmouse::msgs::Maze smartmouse::msgs::Convert (AbstractMaze * maze, std::string name, int size)
References E, i, Node::neighbor(), AbstractMaze::nodes, S, and smartmouse::maze::SIZE.
Referenced by Convert(), Client::LoadDefaultMaze(), Client::LoadDefaultMouse(), Client::LoadNewMaze(), Client::LoadNewMouse(), Client::LoadRandomMaze(), MazeWidget::OnMaze(), Server::OnMaze(), SimMouse::run(), and TEST().
AbstractMaze smartmouse::msgs::Convert (smartmouse::msgs::Maze maze_msg)
References AbstractMaze::connect_all_neighbors_in_maze(), Convert(), AbstractMaze::disconnect_neighbor(), and maze.
Direction smartmouse::msgs::Convert (smartmouse::msgs::Direction dir_msg)
References Convert().
Direction smartmouse::msgs::Convert (smartmouse::msgs::Direction::Dir dir_enum)
RobotDescription smartmouse::msgs::Convert (std::ifstream & fs)
void smartmouse::msgs::Convert (smartmouse::msgs::Maze maze, maze_walls_t & maze_lines)
References smartmouse::maze::SIZE, and WallToCoordinates().
ignition::msgs::Time smartmouse::msgs::Convert (int time_millis)
unsigned long smartmouse::msgs::ConvertMSec (ignition::msgs::Time time)
Referenced by SimTimer::worldStatsCallback().
double smartmouse::msgs::ConvertSec (ignition::msgs::Time time)
Referenced by ControlPlotWidget::ControlCallback(), PIDPlotWidget::PIDCallback(), and TEST().
std::tuple< double, double, double, double > smartmouse::msgs::WallToCoordinates (smartmouse::msgs::Wall wall)
References smartmouse::maze::HALF_WALL_THICKNESS_CU.
Referenced by Convert(), and TEST().