SmartMouse_2018: std Namespace Reference
std Namespace Reference
Classes
class deque< T, EIGEN_ALIGNED_ALLOCATOR< T > >
struct hash< nlohmann::json >
hash value for JSON objects
class list< T, EIGEN_ALIGNED_ALLOCATOR< T > >
struct numeric_limits< Eigen::half >
class vector< T, EIGEN_ALIGNED_ALLOCATOR< T > >
Functions
template<>
void swap (nlohmann::json &j1, nlohmann::json &j2) noexcept(is_nothrow_move_constructible< nlohmann::json >::value andis_nothrow_move_assignable< nlohmann::json >::value)
exchanges the values of two JSON objects
Function Documentation
template<> void std::swap (nlohmann::json & j1, nlohmann::json & j2) inline noexcept
exchanges the values of two JSON objects
Since
version 1.0.0
Referenced by Eigen::BDCSVD< _MatrixType >::allocate(), Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex > >::applyTranspositionOnTheRight(), Eigen::internal::swap_assign_op< DstEvaluatorTypeT::Scalar >::assignCoeff(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::atWithInsertion(), Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::compute(), Eigen::internal::computeFromTridiagonal_impl(), Eigen::ColPivHouseholderQR< _MatrixType >::computeInPlace(), Eigen::BDCSVD< _MatrixType >::computeSingVals(), Eigen::BDCSVD< _MatrixType >::computeSVDofM(), Eigen::BDCSVD< _MatrixType >::deflation(), Eigen::SparseQR< _MatrixType, _OrderingType >::factorize(), Eigen::IncompleteLUT< _Scalar, _StorageIndex >::factorize(), Eigen::DenseStorage< T, Dynamic, Dynamic, Dynamic, _Options >::operator=(), Eigen::DenseStorage< T, Dynamic, _Rows, Dynamic, _Options >::operator=(), Eigen::DenseStorage< T, Dynamic, Dynamic, _Cols, _Options >::operator=(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::operator=(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::operator=(), Eigen::internal::parallelize_gemm(), Eigen::internal::permute_symm_to_fullsymm(), Eigen::internal::permute_symm_to_symm(), Eigen::internal::SparseLUImpl< Scalar, StorageIndex >::pivotL(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::PlainObjectBase(), Eigen::internal::SparseLUImpl< Scalar, StorageIndex >::pruneL(), Eigen::internal::QuickSplit(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::reallocate(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::reserveInnerVectors(), Eigen::ComplexEigenSolver< _MatrixType >::sortEigenvalues(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::swap(), ArgumentParser::Any::swap(), Eigen::DenseStorage< Scalar, Base::MaxSizeAtCompileTime, Base::RowsAtCompileTime, Base::ColsAtCompileTime, Options >::swap(), Eigen::DenseStorage< T, Size, Dynamic, Dynamic, _Options >::swap(), Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::swap(), Eigen::DenseStorage< T, Size, Dynamic, _Cols, _Options >::swap(), Eigen::DenseStorage< T, Size, _Rows, Dynamic, _Options >::swap(), Eigen::DenseStorage< T, Dynamic, Dynamic, Dynamic, _Options >::swap(), Eigen::DenseStorage< T, Dynamic, _Rows, Dynamic, _Options >::swap(), Eigen::numext::swap(), Eigen::DenseStorage< T, Dynamic, Dynamic, _Cols, _Options >::swap(), Eigen::internal::swap(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::swap(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::swap(), Eigen::internal::ldlt_inplace< Lower >::unblocked(), and Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::updateList().