SmartMouse_2018: internal Namespace Reference
internal Namespace Reference
Classes
struct colamd_col
struct Colamd_Row
Functions
template<typename IndexType >
IndexType colamd_c (IndexType n_col)
template<typename IndexType >
IndexType colamd_r (IndexType n_row)
template<typename IndexType >
static IndexType init_rows_cols (IndexType n_row, IndexType n_col, Colamd_Row< IndexType > Row[], colamd_col< IndexType > col[], IndexType A[], IndexType p[], IndexType stats[COLAMD_STATS])
template<typename IndexType >
static void init_scoring (IndexType n_row, IndexType n_col, Colamd_Row< IndexType > Row[], colamd_col< IndexType > Col[], IndexType A[], IndexType head[], double knobs[COLAMD_KNOBS], IndexType *p_n_row2, IndexType *p_n_col2, IndexType *p_max_deg)
template<typename IndexType >
static IndexType find_ordering (IndexType n_row, IndexType n_col, IndexType Alen, Colamd_Row< IndexType > Row[], colamd_col< IndexType > Col[], IndexType A[], IndexType head[], IndexType n_col2, IndexType max_deg, IndexType pfree)
template<typename IndexType >
static void order_children (IndexType n_col, colamd_col< IndexType > Col[], IndexType p[])
template<typename IndexType >
static void detect_super_cols (colamd_col< IndexType > Col[], IndexType A[], IndexType head[], IndexType row_start, IndexType row_length)
template<typename IndexType >
static IndexType garbage_collection (IndexType n_row, IndexType n_col, Colamd_Row< IndexType > Row[], colamd_col< IndexType > Col[], IndexType A[], IndexType *pfree)
template<typename IndexType >
static IndexType clear_mark (IndexType n_row, Colamd_Row< IndexType > Row[])
template<typename IndexType >
IndexType colamd_recommended (IndexType nnz, IndexType n_row, IndexType n_col)
Returns the recommended value of Alen.
static void colamd_set_defaults (double knobs[COLAMD_KNOBS])
set default parameters The use of this routine is optional.
template<typename IndexType >
static bool colamd (IndexType n_row, IndexType n_col, IndexType Alen, IndexType *A, IndexType *p, double knobs[COLAMD_KNOBS], IndexType stats[COLAMD_STATS])
Computes a column ordering using the column approximate minimum degree ordering.
Function Documentation
template<typename IndexType > static IndexType internal::clear_mark (IndexType n_row, Colamd_Row< IndexType > Row[]) inline static
References ROW_IS_ALIVE.
Referenced by colamd_r().
template<typename IndexType > static bool internal::colamd (IndexType n_row, IndexType n_col, IndexType Alen, IndexType * A, IndexType * p, double knobs[COLAMD_KNOBS], IndexType stats[COLAMD_STATS]) static
Computes a column ordering using the column approximate minimum degree ordering.
Computes a column ordering (Q) of A such that P(AQ)=LU or (AQ)'AQ=LL' have less fill-in and require fewer floating point operations than factorizing the unpermuted matrix A or A'A, respectively.
Parameters
n_row number of rows in A
n_col number of columns in A
Alen,size of the array A
A row indices of the matrix, of size ALen
p column pointers of A, of size n_col+1
knobs parameter settings for colamd
stats colamd output statistics and error codes
References colamd_c(), COLAMD_DEBUG0, COLAMD_DEFRAG_COUNT, COLAMD_DENSE_COL, COLAMD_DENSE_ROW, COLAMD_ERROR_A_not_present, COLAMD_ERROR_A_too_small, COLAMD_ERROR_ncol_negative, COLAMD_ERROR_nnz_negative, COLAMD_ERROR_nrow_negative, COLAMD_ERROR_p0_nonzero, COLAMD_ERROR_p_not_present, COLAMD_INFO1, COLAMD_INFO2, COLAMD_KNOBS, COLAMD_OK, colamd_r(), colamd_set_defaults(), COLAMD_STATS, COLAMD_STATUS, Eigen::internal::find_ordering(), i, Eigen::internal::init_rows_cols(), Eigen::internal::init_scoring(), and Eigen::internal::order_children().
template<typename IndexType > IndexType internal::colamd_c (IndexType n_col) inline
Referenced by colamd(), and colamd_recommended().
template<typename IndexType > IndexType internal::colamd_r (IndexType n_row) inline
References clear_mark(), col(), COLAMD_KNOBS, COLAMD_STATS, detect_super_cols(), find_ordering(), garbage_collection(), head(), init_rows_cols(), init_scoring(), and order_children().
Referenced by colamd(), and colamd_recommended().
template<typename IndexType > IndexType internal::colamd_recommended (IndexType nnz, IndexType n_row, IndexType n_col) inline
Returns the recommended value of Alen.
Returns recommended value of Alen for use by colamd. Returns -1 if any input argument is negative. The use of this routine or macro is optional. Note that the macro uses its arguments more than once, so be careful for side effects, if you pass expressions as arguments to COLAMD_RECOMMENDED.
Parameters
nnz nonzeros in A
n_row number of rows in A
n_col number of columns in A
Returns
recommended value of Alen for use by colamd
References colamd_c(), and colamd_r().
static void internal::colamd_set_defaults (double knobs[COLAMD_KNOBS]) inline static
set default parameters The use of this routine is optional.
Colamd: rows with more than (knobs [COLAMD_DENSE_ROW] * n_col) entries are removed prior to ordering. Columns with more than (knobs [COLAMD_DENSE_COL] * n_row) entries are removed prior to ordering, and placed last in the output column ordering.
COLAMD_DENSE_ROW and COLAMD_DENSE_COL are defined as 0 and 1, respectively, in colamd.h. Default values of these two knobs are both 0.5. Currently, only knobs [0] and knobs [1] are used, but future versions may use more knobs. If so, they will be properly set to their defaults by the future version of colamd_set_defaults, so that the code that calls colamd will not need to change, assuming that you either use colamd_set_defaults, or pass a (double *) NULL pointer as the knobs array to colamd or symamd.
Parameters
knobs parameter settings for colamd
References COLAMD_DENSE_COL, COLAMD_DENSE_ROW, COLAMD_KNOBS, and i.
Referenced by colamd().
template<typename IndexType > static void internal::detect_super_cols (colamd_col< IndexType > Col[], IndexType A[], IndexType head[], IndexType row_start, IndexType row_length) static
References col(), COL_IS_ALIVE, COL_IS_DEAD, COLAMD_ASSERT, COLAMD_EMPTY, internal::colamd_col< IndexType >::hash, internal::colamd_col< IndexType >::hash_next, internal::colamd_col< IndexType >::headhash, i, KILL_NON_PRINCIPAL_COL, internal::colamd_col< IndexType >::length, ROW_IS_ALIVE, internal::colamd_col< IndexType >::score, internal::colamd_col< IndexType >::shared2, internal::colamd_col< IndexType >::shared3, internal::colamd_col< IndexType >::shared4, and internal::colamd_col< IndexType >::start.
Referenced by colamd_r(), and order_children().
template<typename IndexType > static IndexType internal::find_ordering (IndexType n_row, IndexType n_col, IndexType Alen, Colamd_Row< IndexType > Row[], colamd_col< IndexType > Col[], IndexType A[], IndexType head[], IndexType n_col2, IndexType max_deg, IndexType pfree) static
References Eigen::internal::clear_mark(), col(), COL_IS_ALIVE, COL_IS_DEAD, COLAMD_ASSERT, COLAMD_DEBUG1, COLAMD_DEBUG2, COLAMD_DEBUG3, COLAMD_DEBUG4, COLAMD_EMPTY, Eigen::internal::detect_super_cols(), Eigen::internal::garbage_collection(), internal::colamd_col< IndexType >::hash, KILL_PRINCIPAL_COL, KILL_ROW, internal::colamd_col< IndexType >::length, order_children(), row(), ROW_IS_ALIVE, ROW_IS_DEAD, ROW_IS_MARKED_DEAD, internal::colamd_col< IndexType >::shared1, and internal::colamd_col< IndexType >::start.
Referenced by colamd_r().
template<typename IndexType > static IndexType internal::garbage_collection (IndexType n_row, IndexType n_col, Colamd_Row< IndexType > Row[], colamd_col< IndexType > Col[], IndexType A[], IndexType * pfree) static
References COL_IS_ALIVE, COLAMD_ASSERT, COLAMD_DEBUG3, KILL_ROW, internal::colamd_col< IndexType >::length, ONES_COMPLEMENT, ROW_IS_ALIVE, and internal::colamd_col< IndexType >::start.
Referenced by colamd_r().
template<typename IndexType > static IndexType internal::init_rows_cols (IndexType n_row, IndexType n_col, Colamd_Row< IndexType > Row[], colamd_col< IndexType > col[], IndexType A[], IndexType p[], IndexType stats[COLAMD_STATS]) static
References col(), COLAMD_DEBUG0, COLAMD_DEBUG1, COLAMD_EMPTY, COLAMD_ERROR_col_length_negative, COLAMD_ERROR_row_index_out_of_bounds, COLAMD_INFO1, COLAMD_INFO2, COLAMD_INFO3, COLAMD_OK_BUT_JUMBLED, COLAMD_STATUS, init_scoring(), internal::colamd_col< IndexType >::length, row(), and internal::colamd_col< IndexType >::shared2.
Referenced by colamd_r().
template<typename IndexType > static void internal::init_scoring (IndexType n_row, IndexType n_col, Colamd_Row< IndexType > Row[], colamd_col< IndexType > Col[], IndexType A[], IndexType head[], double knobs[COLAMD_KNOBS], IndexType * p_n_row2, IndexType * p_n_col2, IndexType * p_max_deg) static
References COL_IS_ALIVE, COL_IS_DEAD, COLAMD_ASSERT, COLAMD_DEBUG1, COLAMD_DEBUG2, COLAMD_DEBUG4, COLAMD_DENSE_COL, COLAMD_DENSE_ROW, COLAMD_EMPTY, internal::Colamd_Row< IndexType >::degree, internal::colamd_col< IndexType >::degree_next, KILL_PRINCIPAL_COL, KILL_ROW, internal::colamd_col< IndexType >::length, internal::colamd_col< IndexType >::order, internal::colamd_col< IndexType >::prev, row(), ROW_IS_DEAD, internal::colamd_col< IndexType >::score, internal::Colamd_Row< IndexType >::shared1, internal::colamd_col< IndexType >::shared2, internal::colamd_col< IndexType >::shared3, internal::colamd_col< IndexType >::shared4, and internal::colamd_col< IndexType >::start.
Referenced by colamd_r(), and init_rows_cols().
template<typename IndexType > static void internal::order_children (IndexType n_col, colamd_col< IndexType > Col[], IndexType p[]) inline static
References COL_IS_DEAD, COL_IS_DEAD_PRINCIPAL, COLAMD_ASSERT, COLAMD_EMPTY, detect_super_cols(), i, internal::colamd_col< IndexType >::order, internal::colamd_col< IndexType >::parent, internal::colamd_col< IndexType >::shared1, and internal::colamd_col< IndexType >::shared2.
Referenced by colamd_r(), and find_ordering().