SmartMouse_2018: Eigen::numext Namespace Reference
Eigen::numext Namespace Reference
Functions
template<>
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE float sqrt (const float &x)
template<>
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE double sqrt (const double &x)
template<typename T >
EIGEN_STRONG_INLINE void swap (T &a, T &b)
template<typename T >
T div_ceil (const T &a, const T &b)
Function Documentation
template<typename T > T Eigen::numext::div_ceil (const T & a, const T & b)
Referenced by Eigen::internal::evaluateProductBlockingSizesHeuristic().
template<> EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE float Eigen::numext::sqrt (const float & x)
References EIGEN_ALWAYS_INLINE, and Eigen::internal::pfirst().
Referenced by Eigen::ColPivHouseholderQR< _MatrixType >::computeInPlace(), Eigen::MatrixBase< Derived >::norm(), Eigen::MatrixBase< Derived >::normalize(), Eigen::MatrixBase< Derived >::normalized(), Eigen::internal::scalar_sqrt_op< Scalar >::operator()(), Eigen::internal::scalar_rsqrt_op< Scalar >::operator()(), Eigen::MatrixBase< Derived >::stableNormalize(), and Eigen::MatrixBase< Derived >::stableNormalized().
template<> EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE double Eigen::numext::sqrt (const double & x)
References Eigen::internal::pfirst().
template<typename T > EIGEN_STRONG_INLINE void Eigen::numext::swap (T & a, T & b)
References std::swap().
Referenced by Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 3, false >::run().