SmartMouse_2018: smartmouse::math Namespace Reference
smartmouse::math Namespace Reference
Functions
double yaw_diff (double y1, double y2)
template<typename T >
T MyMod (T x, T y)
double wrapAngleRad (double angle_rad)
void wrapAngleRadInPlace (double *angle_rad)
Function Documentation
template<typename T > T smartmouse::math::MyMod (T x, T y)
References m.
Referenced by wrapAngleRad(), and wrapAngleRadInPlace().
double smartmouse::math::wrapAngleRad (double angle_rad) inline
References M_PI, and MyMod().
void smartmouse::math::wrapAngleRadInPlace (double * angle_rad) inline
References M_PI, and MyMod().
Referenced by KinematicController::run(), and Server::UpdateRobotState().
double smartmouse::math::yaw_diff (double y1, double y2) inline
References M_PI.
Referenced by smartmouse::kc::DriveStraightState::compute_wheel_velocities(), ArcTurn::execute(), KinematicController::getLocalPose(), TurnInPlace::isFinished(), ArcTurn::isFinished(), KinematicController::run(), and Server::UpdateRobotState().