SmartMouse_2018: profile_encoders.cpp File Reference
profile_encoders.cpp File Reference
#include <real/RealMouse.h>
Functions
unsigned long measure ()
void setup ()
void loop ()
Variables
RealMouse * mouse
unsigned long m = 0
Function Documentation
void loop ()
References RealMouse::left_encoder, measure(), RealMouse::MOTOR_LEFT_A, RealMouse::MOTOR_LEFT_B, RealMouse::MOTOR_RIGHT_A, RealMouse::MOTOR_RIGHT_B, print(), and RealMouse::right_encoder.
unsigned long measure ()
References i.
Referenced by loop().
void setup ()
References KinematicController::enabled, RealMouse::inst(), RealMouse::kinematic_controller, print(), and RealMouse::setup().
Variable Documentation
unsigned long m = 0
Referenced by main(), and smartmouse::math::MyMod().
RealMouse* mouse
This program is for measuring how much CPU encoder counting eats up. We do this by comparing the amount of time a blocking piece of code takes when motors are moving versus stationary. When the motor is stationary, the encoders will not generate any interrupts. When they are moving, the encoder will generate lots of interrupts and the same for loop will take up more time.