SmartMouse_2018: eigen_test.cpp File Reference
real/main/eigen_test.cpp File Reference
#include <common/Eigen/Eigen.h>
#include <common/Eigen/Eigen/Dense>
#include <Arduino.h>
Functions
void print_mtx (const Eigen::Matrix< double, Dynamic, Dynamic > &X)
void setup ()
void loop ()
Function Documentation
void loop ()
void print_mtx (const Eigen::Matrix< double, Dynamic, Dynamic > & X)
References i, and print().
Referenced by setup().
void setup ()
References print(), and print_mtx().