SmartMouse_2018: SimNavTest.cpp File Reference
SimNavTest.cpp File Reference
#include <commands/WaitForStart.h>
#include <commands/Forward.h>
#include <commands/ForwardN.h>
#include <commands/ForwardToCenter.h>
#include <commands/Turn.h>
#include <commands/Stop.h>
Classes
class NavTestCommand
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
References done, SimMouse::inst(), last_t, mouse, NavTestCommand::NavTestCommand(), SimTimer::programTimeMs(), Scheduler::run(), SimMouse::run(), scheduler, SimMouse::simInit(), and SimMouse::timer.