SmartMouse_2018: SimTest.cpp File Reference
SimTest.cpp File Reference
#include <fstream>
#include "gtest/gtest.h"
#include <common/core/AbstractMaze.h>
#include <msgs/direction.pb.h>
#include <msgs/msgs.h>
#include <ignition/transport.hh>
#include <sim/simulator/msgs/server_control.pb.h>
#include <lib/common/TopicNames.h>
#include <sim/simulator/lib/Server.h>
#include <msgs/world_statistics.pb.h>
#include <lib/common/RayTracing.h>
Functions
TEST (MsgsTest, ConvertMillis)
TEST (MsgsTest, ConvertTime)
TEST (MsgsTest, DirectionMsgConversion)
TEST (MsgsTest, DirectionEnumConversion)
TEST (MsgsTest, MazeConversion)
TEST (MsgsTest, WallToCoordinates)
TEST (ServerTest, QuitTest)
TEST (ServerTest, StepTimeTest)
TEST (RayTracingTest, DistanceToWallTest)
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
TEST (MsgsTest , ConvertMillis)
References smartmouse::msgs::Convert().
TEST (MsgsTest , ConvertTime)
References smartmouse::msgs::ConvertSec(), and e.
TEST (MsgsTest , DirectionMsgConversion)
TEST (MsgsTest , DirectionEnumConversion)
References smartmouse::msgs::Convert(), E, N, S, and W.
TEST (MsgsTest , MazeConversion)
References smartmouse::msgs::Convert(), maze, and smartmouse::maze::SIZE.
TEST (MsgsTest , WallToCoordinates)
References smartmouse::maze::HALF_WALL_THICKNESS_CU, and smartmouse::msgs::WallToCoordinates().
TEST (ServerTest , QuitTest)
References TopicNames::kServerControl, and Server::Start().
TEST (ServerTest , StepTimeTest)
References Server::Connect(), Time::GetWallTime(), i, TopicNames::kServerControl, and N.
TEST (RayTracingTest , DistanceToWallTest)
References RayTracing::distance_to_wall(), and e.