SmartMouse_2018: SmartmouseSim.cpp File Reference
SmartmouseSim.cpp File Reference
#include <getopt.h>
#include <cstdio>
#include <cstdlib>
#include <lib/Server.h>
#include <QtWidgets/QApplication>
#include <lib/Client.h>
#include <lib/common/TopicNames.h>
Functions
void PrintVersionInfo ()
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
References Server::Join(), Client::kRestartCode, TopicNames::kServerControl, PrintVersionInfo(), and Server::Start().
void PrintVersionInfo ()
Referenced by main().