SmartMouse_2018: Eigen::internal::tribb_kernel< LhsScalar, RhsScalar, Index, mr, nr, ConjLhs, ConjRhs, UpLo > Struct Template Reference
Eigen::internal::tribb_kernel< LhsScalar, RhsScalar, Index, mr, nr, ConjLhs, ConjRhs, UpLo > Struct Template Reference
#include <GeneralMatrixMatrixTriangular.h>
Public Types
enum { BlockSize = meta_least_common_multiple<EIGEN_PLAIN_ENUM_MAX(mr,nr),EIGEN_PLAIN_ENUM_MIN(mr,nr)>::ret }
typedef gebp_traits< LhsScalar, RhsScalar, ConjLhs, ConjRhs > Traits
typedef Traits::ResScalar ResScalar
Public Member Functions
void operator() (ResScalar *_res, Index resStride, const LhsScalar *blockA, const RhsScalar *blockB, Index size, Index depth, const ResScalar &alpha)
Member Typedef Documentation
template<typename LhsScalar, typename RhsScalar, typename Index, int mr, int nr, bool ConjLhs, bool ConjRhs, int UpLo> typedef Traits::ResScalar Eigen::internal::tribb_kernel< LhsScalar, RhsScalar, Index, mr, nr, ConjLhs, ConjRhs, UpLo >::ResScalar
template<typename LhsScalar, typename RhsScalar, typename Index, int mr, int nr, bool ConjLhs, bool ConjRhs, int UpLo> typedef gebp_traits<LhsScalar,RhsScalar,ConjLhs,ConjRhs> Eigen::internal::tribb_kernel< LhsScalar, RhsScalar, Index, mr, nr, ConjLhs, ConjRhs, UpLo >::Traits
Member Enumeration Documentation
template<typename LhsScalar, typename RhsScalar, typename Index, int mr, int nr, bool ConjLhs, bool ConjRhs, int UpLo> anonymous enum
Enumerator
BlockSize
Member Function Documentation
template<typename LhsScalar, typename RhsScalar, typename Index, int mr, int nr, bool ConjLhs, bool ConjRhs, int UpLo> void Eigen::internal::tribb_kernel< LhsScalar, RhsScalar, Index, mr, nr, ConjLhs, ConjRhs, UpLo >::operator() (ResScalar * _res, Index resStride, const LhsScalar * blockA, const RhsScalar * blockB, Index size, Index depth, const ResScalar & alpha) inline
References Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::data(), i, Eigen::Lower, Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::setZero(), Eigen::internal::size(), and Eigen::Upper.
The documentation for this struct was generated from the following file:
GeneralMatrixMatrixTriangular.h