SmartMouse_2018: Eigen::internal::Assignment< DstXprType, Inverse< ColPivHouseholderQR< MatrixType > >, internal::assign_op< typename DstXprType::Scalar, typename ColPivHouseholderQR< MatrixType >::Scalar >, Dense2Dense > Struct Template Reference
Eigen::internal::Assignment< DstXprType, Inverse< ColPivHouseholderQR< MatrixType > >, internal::assign_op< typename DstXprType::Scalar, typename ColPivHouseholderQR< MatrixType >::Scalar >, Dense2Dense > Struct Template Reference
#include <ColPivHouseholderQR.h>
Public Types
typedef ColPivHouseholderQR< MatrixType > QrType
typedef Inverse< QrType > SrcXprType
Static Public Member Functions
static void run (DstXprType &dst, const SrcXprType &src, const internal::assign_op< typename DstXprType::Scalar, typename QrType::Scalar > &)
Member Typedef Documentation
template<typename DstXprType , typename MatrixType > typedef ColPivHouseholderQR<MatrixType> Eigen::internal::Assignment< DstXprType, Inverse< ColPivHouseholderQR< MatrixType > >, internal::assign_op< typename DstXprType::Scalar, typename ColPivHouseholderQR< MatrixType >::Scalar >, Dense2Dense >::QrType
template<typename DstXprType , typename MatrixType > typedef Inverse<QrType> Eigen::internal::Assignment< DstXprType, Inverse< ColPivHouseholderQR< MatrixType > >, internal::assign_op< typename DstXprType::Scalar, typename ColPivHouseholderQR< MatrixType >::Scalar >, Dense2Dense >::SrcXprType
Member Function Documentation
template<typename DstXprType , typename MatrixType > static void Eigen::internal::Assignment< DstXprType, Inverse< ColPivHouseholderQR< MatrixType > >, internal::assign_op< typename DstXprType::Scalar, typename ColPivHouseholderQR< MatrixType >::Scalar >, Dense2Dense >::run (DstXprType & dst, const SrcXprType & src, const internal::assign_op< typename DstXprType::Scalar, typename QrType::Scalar > &) inline static
References Eigen::Inverse< XprType >::cols(), Eigen::ColPivHouseholderQR< _MatrixType >::householderQ(), Eigen::Inverse< XprType >::nestedExpression(), and Eigen::Inverse< XprType >::rows().
The documentation for this struct was generated from the following file:
ColPivHouseholderQR.h