SmartMouse_2018: Eigen::internal::conj_helper< Packet1cd, Packet1cd, true, false > Struct Template Reference
Eigen::internal::conj_helper< Packet1cd, Packet1cd, true, false > Struct Template Reference
#include <Complex.h>
Public Member Functions
EIGEN_STRONG_INLINE Packet1cd pmadd (const Packet1cd &x, const Packet1cd &y, const Packet1cd &c) const
EIGEN_STRONG_INLINE Packet1cd pmul (const Packet1cd &a, const Packet1cd &b) const
EIGEN_STRONG_INLINE Packet1cd pmadd (const Packet1cd &x, const Packet1cd &y, const Packet1cd &c) const
EIGEN_STRONG_INLINE Packet1cd pmul (const Packet1cd &a, const Packet1cd &b) const
Member Function Documentation
EIGEN_STRONG_INLINE Packet1cd Eigen::internal::conj_helper< Packet1cd, Packet1cd, true, false >::pmadd (const Packet1cd & x, const Packet1cd & y, const Packet1cd & c) const inline
References Eigen::internal::padd(), and Eigen::internal::pmul().
EIGEN_STRONG_INLINE Packet1cd Eigen::internal::conj_helper< Packet1cd, Packet1cd, true, false >::pmadd (const Packet1cd & x, const Packet1cd & y, const Packet1cd & c) const inline
References Eigen::internal::padd(), and Eigen::internal::pmul().
EIGEN_STRONG_INLINE Packet1cd Eigen::internal::conj_helper< Packet1cd, Packet1cd, true, false >::pmul (const Packet1cd & a, const Packet1cd & b) const inline
References Eigen::internal::pconj(), and Eigen::internal::pmul().
EIGEN_STRONG_INLINE Packet1cd Eigen::internal::conj_helper< Packet1cd, Packet1cd, true, false >::pmul (const Packet1cd & a, const Packet1cd & b) const inline
References Eigen::internal::pconj(), Eigen::internal::pmul(), Eigen::internal::Packet1cd::v, and vec2d_swizzle1.
The documentation for this struct was generated from the following file:
SSE/Complex.h