SmartMouse_2018: Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType > Struct Template Reference
Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType > Struct Template Reference
Expression type for return value of FullPivHouseholderQR::matrixQ()
#include <FullPivHouseholderQR.h>
Public Types
typedef FullPivHouseholderQR< MatrixType >::IntDiagSizeVectorType IntDiagSizeVectorType
typedef internal::plain_diag_type< MatrixType >::type HCoeffsType
typedef Matrix< typename MatrixType::Scalar, 1, MatrixType::RowsAtCompileTime, RowMajor, 1, MatrixType::MaxRowsAtCompileTime > WorkVectorType
Public Types inherited from Eigen::ReturnByValue< FullPivHouseholderQRMatrixQReturnType< MatrixType > >
typedef internal::traits< FullPivHouseholderQRMatrixQReturnType< MatrixType > >::ReturnType ReturnType
typedef internal::dense_xpr_base< ReturnByValue >::type Base
Public Member Functions
FullPivHouseholderQRMatrixQReturnType (const MatrixType &qr, const HCoeffsType &hCoeffs, const IntDiagSizeVectorType &rowsTranspositions)
template<typename ResultType >
void evalTo (ResultType &result) const
template<typename ResultType >
void evalTo (ResultType &result, WorkVectorType &workspace) const
Index rows () const
Index cols () const
Public Member Functions inherited from Eigen::ReturnByValue< FullPivHouseholderQRMatrixQReturnType< MatrixType > >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
const Unusable & coeff (Index) const
const Unusable & coeff (Index, Index) const
Unusable & coeffRef (Index)
Unusable & coeffRef (Index, Index)
Protected Attributes
MatrixType::Nested m_qr
HCoeffsType::Nested m_hCoeffs
IntDiagSizeVectorType::Nested m_rowsTranspositions
Detailed Description
template<typename MatrixType>
struct Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >
Expression type for return value of FullPivHouseholderQR::matrixQ()
Template Parameters
MatrixType type of underlying dense matrix
Member Typedef Documentation
template<typename MatrixType > typedef internal::plain_diag_type<MatrixType>::type Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::HCoeffsType
template<typename MatrixType > typedef FullPivHouseholderQR<MatrixType>::IntDiagSizeVectorType Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::IntDiagSizeVectorType
template<typename MatrixType > typedef Matrix<typename MatrixType::Scalar, 1, MatrixType::RowsAtCompileTime, RowMajor, 1, MatrixType::MaxRowsAtCompileTime> Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::WorkVectorType
Constructor & Destructor Documentation
template<typename MatrixType > Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::FullPivHouseholderQRMatrixQReturnType (const MatrixType & qr, const HCoeffsType & hCoeffs, const IntDiagSizeVectorType & rowsTranspositions) inline
Member Function Documentation
template<typename MatrixType > Index Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::cols (void) const inline
template<typename MatrixType > template<typename ResultType > void Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::evalTo (ResultType & result) const inline
template<typename MatrixType > template<typename ResultType > void Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::evalTo (ResultType & result, WorkVectorType & workspace) const inline
References Eigen::PlainObjectBase< Derived >::coeffRef(), Eigen::half_impl::min(), Eigen::PlainObjectBase< Derived >::resize(), and Eigen::internal::size().
template<typename MatrixType > Index Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::rows (void) const inline
Member Data Documentation
template<typename MatrixType > HCoeffsType::Nested Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::m_hCoeffs protected
template<typename MatrixType > MatrixType::Nested Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::m_qr protected
template<typename MatrixType > IntDiagSizeVectorType::Nested Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::m_rowsTranspositions protected
The documentation for this struct was generated from the following file:
FullPivHouseholderQR.h