SmartMouse_2018: Eigen::internal::evaluator< SparseCompressedBase< Derived > > Struct Template Reference
Eigen::internal::evaluator< SparseCompressedBase< Derived > > Struct Template Reference
#include <SparseCompressedBase.h>
Public Types
enum { CoeffReadCost = NumTraits<Scalar>::ReadCost, Flags = Derived::Flags }
typedef Derived::Scalar Scalar
typedef Derived::InnerIterator InnerIterator
typedef DenseCoeffsBase< Derived, ReadOnlyAccessors >::CoeffReturnType CoeffReturnType
Public Types inherited from Eigen::internal::evaluator_base< Derived >
enum
typedef traits< Derived > ExpressionTraits
Public Member Functions
evaluator ()
evaluator (const Derived &mat)
Index nonZerosEstimate () const
operator Derived & ()
operator const Derived & () const
const Scalar & coeff (Index row, Index col) const
Scalar & coeffRef (Index row, Index col)
Public Member Functions inherited from Eigen::internal::evaluator_base< Derived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE evaluator_base ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ~evaluator_base ()
Protected Member Functions
Index find (Index row, Index col) const
Protected Attributes
const Derived * m_matrix
const Scalar m_zero
Member Typedef Documentation
template<typename Derived > typedef DenseCoeffsBase<Derived,ReadOnlyAccessors>::CoeffReturnType Eigen::internal::evaluator< SparseCompressedBase< Derived > >::CoeffReturnType
template<typename Derived > typedef Derived::InnerIterator Eigen::internal::evaluator< SparseCompressedBase< Derived > >::InnerIterator
template<typename Derived > typedef Derived::Scalar Eigen::internal::evaluator< SparseCompressedBase< Derived > >::Scalar
Member Enumeration Documentation
template<typename Derived > anonymous enum
Enumerator
CoeffReadCost
Flags
Constructor & Destructor Documentation
template<typename Derived > Eigen::internal::evaluator< SparseCompressedBase< Derived > >::evaluator () inline
References EIGEN_INTERNAL_CHECK_COST_VALUE.
template<typename Derived > Eigen::internal::evaluator< SparseCompressedBase< Derived > >::evaluator (const Derived & mat) inline explicit
References EIGEN_INTERNAL_CHECK_COST_VALUE.
Member Function Documentation
template<typename Derived > const Scalar& Eigen::internal::evaluator< SparseCompressedBase< Derived > >::coeff (Index row, Index col) const inline
References Eigen::Dynamic.
template<typename Derived > Scalar& Eigen::internal::evaluator< SparseCompressedBase< Derived > >::coeffRef (Index row, Index col) inline
References Eigen::Dynamic, and eigen_assert.
template<typename Derived > Index Eigen::internal::evaluator< SparseCompressedBase< Derived > >::find (Index row, Index col) const inline protected
References col(), Eigen::Dynamic, eigen_assert, eigen_internal_assert, Eigen::placeholders::end(), and row().
template<typename Derived > Index Eigen::internal::evaluator< SparseCompressedBase< Derived > >::nonZerosEstimate () const inline
template<typename Derived > Eigen::internal::evaluator< SparseCompressedBase< Derived > >::operator const Derived & () const inline
template<typename Derived > Eigen::internal::evaluator< SparseCompressedBase< Derived > >::operator Derived & () inline
Member Data Documentation
template<typename Derived > const Derived* Eigen::internal::evaluator< SparseCompressedBase< Derived > >::m_matrix protected
template<typename Derived > const Scalar Eigen::internal::evaluator< SparseCompressedBase< Derived > >::m_zero protected
The documentation for this struct was generated from the following file:
SparseCompressedBase.h