SmartMouse_2018: Eigen::internal::Assignment< DstXprType, Product< Lhs, Rhs, Options >, internal::assign_op< Scalar, Scalar >, Dense2Dense, typename enable_if<(Options==DefaultProduct||Options==AliasFreeProduct)>::type > Struct Template Reference
Eigen::internal::Assignment< DstXprType, Product< Lhs, Rhs, Options >, internal::assign_op< Scalar, Scalar >, Dense2Dense, typename enable_if<(Options==DefaultProduct||Options==AliasFreeProduct)>::type > Struct Template Reference
#include <ProductEvaluators.h>
Public Types
typedef Product< Lhs, Rhs, Options > SrcXprType
Static Public Member Functions
static EIGEN_STRONG_INLINE void run (DstXprType &dst, const SrcXprType &src, const internal::assign_op< Scalar, Scalar > &)
Member Typedef Documentation
template<typename DstXprType , typename Lhs , typename Rhs , int Options, typename Scalar > typedef Product<Lhs,Rhs,Options> Eigen::internal::Assignment< DstXprType, Product< Lhs, Rhs, Options >, internal::assign_op< Scalar, Scalar >, Dense2Dense, typename enable_if<(Options==DefaultProduct||Options==AliasFreeProduct)>::type >::SrcXprType
Member Function Documentation
template<typename DstXprType , typename Lhs , typename Rhs , int Options, typename Scalar > static EIGEN_STRONG_INLINE void Eigen::internal::Assignment< DstXprType, Product< Lhs, Rhs, Options >, internal::assign_op< Scalar, Scalar >, Dense2Dense, typename enable_if<(Options==DefaultProduct||Options==AliasFreeProduct)>::type >::run (DstXprType & dst, const SrcXprType & src, const internal::assign_op< Scalar, Scalar > &) inline static
References Eigen::Product< _Lhs, _Rhs, Option >::cols(), Eigen::Product< _Lhs, _Rhs, Option >::lhs(), Eigen::Product< _Lhs, _Rhs, Option >::rhs(), and Eigen::Product< _Lhs, _Rhs, Option >::rows().
The documentation for this struct was generated from the following file:
ProductEvaluators.h