SmartMouse_2018: Eigen::internal::general_matrix_matrix_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor > Struct Template Reference
Eigen::internal::general_matrix_matrix_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor > Struct Template Reference
#include <GeneralMatrixMatrix.h>
Public Types
typedef gebp_traits< LhsScalar, RhsScalar > Traits
typedef ScalarBinaryOpTraits< LhsScalar, RhsScalar >::ReturnType ResScalar
Static Public Member Functions
static void run (Index rows, Index cols, Index depth, const LhsScalar *_lhs, Index lhsStride, const RhsScalar *_rhs, Index rhsStride, ResScalar *_res, Index resStride, ResScalar alpha, level3_blocking< LhsScalar, RhsScalar > &blocking, GemmParallelInfo< Index > *info=0)
Member Typedef Documentation
template<typename Index , typename LhsScalar , int LhsStorageOrder, bool ConjugateLhs, typename RhsScalar , int RhsStorageOrder, bool ConjugateRhs> typedef ScalarBinaryOpTraits<LhsScalar, RhsScalar>::ReturnType Eigen::internal::general_matrix_matrix_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor >::ResScalar
template<typename Index , typename LhsScalar , int LhsStorageOrder, bool ConjugateLhs, typename RhsScalar , int RhsStorageOrder, bool ConjugateRhs> typedef gebp_traits<LhsScalar,RhsScalar> Eigen::internal::general_matrix_matrix_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor >::Traits
Member Function Documentation
template<typename Index , typename LhsScalar , int LhsStorageOrder, bool ConjugateLhs, typename RhsScalar , int RhsStorageOrder, bool ConjugateRhs> static void Eigen::internal::general_matrix_matrix_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor >::run (Index rows, Index cols, Index depth, const LhsScalar * _lhs, Index lhsStride, const RhsScalar * _rhs, Index rhsStride, ResScalar * _res, Index resStride, ResScalar alpha, level3_blocking< LhsScalar, RhsScalar > & blocking, GemmParallelInfo< Index > * info = 0) inline static
References Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::blockA(), Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::blockB(), ei_declare_aligned_stack_constructed_variable, eigen_internal_assert, EIGEN_UNUSED_VARIABLE, i, Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::kc(), Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::mc(), Eigen::half_impl::min(), and Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::nc().
The documentation for this struct was generated from the following file:
GeneralMatrixMatrix.h