SmartMouse_2018: Eigen::internal::palign_impl< Offset, PacketType > Struct Template Reference
Eigen::internal::palign_impl< Offset, PacketType > Struct Template Reference
#include <GenericPacketMath.h>
Static Public Member Functions
static void run (PacketType &, const PacketType &)
Member Function Documentation
template<int Offset, typename PacketType > static void Eigen::internal::palign_impl< Offset, PacketType >::run (PacketType & , const PacketType &) inline static
Referenced by Eigen::internal::palign(), Eigen::internal::palign_impl< Offset, Packet4cf >::run(), and Eigen::internal::palign_impl< Offset, Packet2cd >::run().
The documentation for this struct was generated from the following file:
GenericPacketMath.h