SmartMouse_2018: Eigen::internal::evaluator< PlainObjectBase< Derived > > Struct Template Reference
Eigen::internal::evaluator< PlainObjectBase< Derived > > Struct Template Reference
#include <CoreEvaluators.h>
Public Types
enum {
IsRowMajor = PlainObjectType::IsRowMajor, IsVectorAtCompileTime = PlainObjectType::IsVectorAtCompileTime, RowsAtCompileTime = PlainObjectType::RowsAtCompileTime, ColsAtCompileTime = PlainObjectType::ColsAtCompileTime,
CoeffReadCost = NumTraits<Scalar>::ReadCost, Flags = traits<Derived>::EvaluatorFlags, Alignment = traits<Derived>::Alignment
}
enum { OuterStrideAtCompileTime }
typedef PlainObjectBase< Derived > PlainObjectType
typedef PlainObjectType::Scalar Scalar
typedef PlainObjectType::CoeffReturnType CoeffReturnType
Public Types inherited from Eigen::internal::evaluator_base< Derived >
enum
typedef traits< Derived > ExpressionTraits
Public Member Functions
EIGEN_DEVICE_FUNC evaluator ()
EIGEN_DEVICE_FUNC evaluator (const PlainObjectType &m)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index row, Index col) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index row, Index col)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index index)
template<int LoadMode, typename PacketType >
EIGEN_STRONG_INLINE PacketType packet (Index row, Index col) const
template<int LoadMode, typename PacketType >
EIGEN_STRONG_INLINE PacketType packet (Index index) const
template<int StoreMode, typename PacketType >
EIGEN_STRONG_INLINE void writePacket (Index row, Index col, const PacketType &x)
template<int StoreMode, typename PacketType >
EIGEN_STRONG_INLINE void writePacket (Index index, const PacketType &x)
Public Member Functions inherited from Eigen::internal::evaluator_base< Derived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE evaluator_base ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ~evaluator_base ()
Protected Attributes
plainobjectbase_evaluator_data< Scalar, OuterStrideAtCompileTime > m_d
Member Typedef Documentation
template<typename Derived > typedef PlainObjectType::CoeffReturnType Eigen::internal::evaluator< PlainObjectBase< Derived > >::CoeffReturnType
template<typename Derived > typedef PlainObjectBase<Derived> Eigen::internal::evaluator< PlainObjectBase< Derived > >::PlainObjectType
template<typename Derived > typedef PlainObjectType::Scalar Eigen::internal::evaluator< PlainObjectBase< Derived > >::Scalar
Member Enumeration Documentation
template<typename Derived > anonymous enum
Enumerator
IsRowMajor
IsVectorAtCompileTime
RowsAtCompileTime
ColsAtCompileTime
CoeffReadCost
Flags
Alignment
template<typename Derived > anonymous enum
Enumerator
OuterStrideAtCompileTime
Constructor & Destructor Documentation
template<typename Derived > EIGEN_DEVICE_FUNC Eigen::internal::evaluator< PlainObjectBase< Derived > >::evaluator () inline
References EIGEN_INTERNAL_CHECK_COST_VALUE.
template<typename Derived > EIGEN_DEVICE_FUNC Eigen::internal::evaluator< PlainObjectBase< Derived > >::evaluator (const PlainObjectType & m) inline explicit
References EIGEN_INTERNAL_CHECK_COST_VALUE, and EIGEN_STRONG_INLINE.
Member Function Documentation
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::evaluator< PlainObjectBase< Derived > >::coeff (Index row, Index col) const inline
References col(), and EIGEN_STRONG_INLINE.
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::evaluator< PlainObjectBase< Derived > >::coeff (Index index) const inline
References EIGEN_STRONG_INLINE.
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::internal::evaluator< PlainObjectBase< Derived > >::coeffRef (Index row, Index col) inline
References col(), and EIGEN_STRONG_INLINE.
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::internal::evaluator< PlainObjectBase< Derived > >::coeffRef (Index index) inline
References EIGEN_STRONG_INLINE.
template<typename Derived > template<int LoadMode, typename PacketType > EIGEN_STRONG_INLINE PacketType Eigen::internal::evaluator< PlainObjectBase< Derived > >::packet (Index row, Index col) const inline
References col(), and EIGEN_STRONG_INLINE.
template<typename Derived > template<int LoadMode, typename PacketType > EIGEN_STRONG_INLINE PacketType Eigen::internal::evaluator< PlainObjectBase< Derived > >::packet (Index index) const inline
References EIGEN_STRONG_INLINE.
template<typename Derived > template<int StoreMode, typename PacketType > EIGEN_STRONG_INLINE void Eigen::internal::evaluator< PlainObjectBase< Derived > >::writePacket (Index row, Index col, const PacketType & x) inline
References col(), and EIGEN_STRONG_INLINE.
template<typename Derived > template<int StoreMode, typename PacketType > EIGEN_STRONG_INLINE void Eigen::internal::evaluator< PlainObjectBase< Derived > >::writePacket (Index index, const PacketType & x) inline
Member Data Documentation
template<typename Derived > plainobjectbase_evaluator_data<Scalar,OuterStrideAtCompileTime> Eigen::internal::evaluator< PlainObjectBase< Derived > >::m_d protected
The documentation for this struct was generated from the following file:
CoreEvaluators.h