SmartMouse_2018: Eigen::internal::quat_conj< Architecture::SSE, Derived, double > Struct Template Reference
Eigen::internal::quat_conj< Architecture::SSE, Derived, double > Struct Template Reference
#include <Geometry_SSE.h>
Public Types
enum { ResAlignment = traits<Quaternion<double> >::Alignment }
Static Public Member Functions
static Quaternion< double > run (const QuaternionBase< Derived > &q)
Member Enumeration Documentation
template<class Derived > anonymous enum
Enumerator
ResAlignment
Member Function Documentation
template<class Derived > static Quaternion<double> Eigen::internal::quat_conj< Architecture::SSE, Derived, double >::run (const QuaternionBase< Derived > & q) inline static
References Eigen::QuaternionBase< Derived >::coeffs(), Eigen::QuaternionBase< Quaternion< _Scalar, _Options > >::x(), and Eigen::QuaternionBase< Quaternion< _Scalar, _Options > >::z().
The documentation for this struct was generated from the following file:
Geometry_SSE.h