SmartMouse_2018: Eigen::internal::kernel_retval< FullPivLU< _MatrixType > > Struct Template Reference
Eigen::internal::kernel_retval< FullPivLU< _MatrixType > > Struct Template Reference
#include <FullPivLU.h>
Public Types
enum { MaxSmallDimAtCompileTime }
Public Types inherited from Eigen::internal::kernel_retval_base< FullPivLU< _MatrixType > >
typedef FullPivLU< _MatrixType > DecompositionType
typedef ReturnByValue< kernel_retval_base > Base
Public Types inherited from Eigen::ReturnByValue< kernel_retval_base< FullPivLU< _MatrixType > > >
typedef internal::traits< kernel_retval_base< FullPivLU< _MatrixType > > >::ReturnType ReturnType
typedef internal::dense_xpr_base< ReturnByValue >::type Base
Public Member Functions
template<typename Dest >
void evalTo (Dest &dst) const
Public Member Functions inherited from Eigen::internal::kernel_retval_base< FullPivLU< _MatrixType > >
kernel_retval_base (const DecompositionType &dec)
Index rows () const
Index cols () const
Index rank () const
const DecompositionType & dec () const
void evalTo (Dest &dst) const
Public Member Functions inherited from Eigen::ReturnByValue< kernel_retval_base< FullPivLU< _MatrixType > > >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
const Unusable & coeff (Index) const
const Unusable & coeff (Index, Index) const
Unusable & coeffRef (Index)
Unusable & coeffRef (Index, Index)
Additional Inherited Members
Protected Attributes inherited from Eigen::internal::kernel_retval_base< FullPivLU< _MatrixType > >
const DecompositionType & m_dec
Index m_rank
Index m_cols
Member Enumeration Documentation
template<typename _MatrixType > anonymous enum
Enumerator
MaxSmallDimAtCompileTime
Member Function Documentation
template<typename _MatrixType > template<typename Dest > void Eigen::internal::kernel_retval< FullPivLU< _MatrixType > >::evalTo (Dest & dst) const inline
References abs(), block(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::coeff(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::coeffRef(), Eigen::FullPivLU< _MatrixType >::cols(), Eigen::Dynamic, eigen_internal_assert, i, m, Eigen::FullPivLU< _MatrixType >::matrixLU(), Eigen::FullPivLU< _MatrixType >::permutationQ(), Eigen::FullPivLU< _MatrixType >::rank(), and tail().
The documentation for this struct was generated from the following file:
FullPivLU.h