SmartMouse_2018: Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true > Struct Template Reference
Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true > Struct Template Reference
#include <Complex.h>
Public Member Functions
EIGEN_STRONG_INLINE Packet2cf pmadd (const Packet2cf &x, const Packet2cf &y, const Packet2cf &c) const
EIGEN_STRONG_INLINE Packet2cf pmul (const Packet2cf &a, const Packet2cf &b) const
EIGEN_STRONG_INLINE Packet2cf pmadd (const Packet2cf &x, const Packet2cf &y, const Packet2cf &c) const
EIGEN_STRONG_INLINE Packet2cf pmul (const Packet2cf &a, const Packet2cf &b) const
EIGEN_STRONG_INLINE Packet2cf pmadd (const Packet2cf &x, const Packet2cf &y, const Packet2cf &c) const
EIGEN_STRONG_INLINE Packet2cf pmul (const Packet2cf &a, const Packet2cf &b) const
EIGEN_STRONG_INLINE Packet2cf pmadd (const Packet2cf &x, const Packet2cf &y, const Packet2cf &c) const
EIGEN_STRONG_INLINE Packet2cf pmul (const Packet2cf &a, const Packet2cf &b) const
Member Function Documentation
EIGEN_STRONG_INLINE Packet2cf Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmadd (const Packet2cf & x, const Packet2cf & y, const Packet2cf & c) const inline
References Eigen::internal::padd(), and Eigen::internal::pmul().
EIGEN_STRONG_INLINE Packet2cf Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmadd (const Packet2cf & x, const Packet2cf & y, const Packet2cf & c) const inline
References Eigen::internal::padd(), and Eigen::internal::pmul().
EIGEN_STRONG_INLINE Packet2cf Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmadd (const Packet2cf & x, const Packet2cf & y, const Packet2cf & c) const inline
References Eigen::internal::padd(), and Eigen::internal::pmul().
EIGEN_STRONG_INLINE Packet2cf Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmadd (const Packet2cf & x, const Packet2cf & y, const Packet2cf & c) const inline
References Eigen::internal::padd(), and Eigen::internal::pmul().
EIGEN_STRONG_INLINE Packet2cf Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul (const Packet2cf & a, const Packet2cf & b) const inline
References EIGEN_MAKE_CONJ_HELPER_CPLX_REAL, EIGEN_STRONG_INLINE, Eigen::internal::Packet2cf::Packet2cf(), Eigen::internal::pconj(), Eigen::internal::pdiv< Packet2cf >(), Eigen::internal::pmul(), and vec4f_swizzle1.
EIGEN_STRONG_INLINE Packet2cf Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul (const Packet2cf & a, const Packet2cf & b) const inline
References EIGEN_MAKE_CONJ_HELPER_CPLX_REAL, Eigen::internal::pconj(), and Eigen::internal::pmul().
EIGEN_STRONG_INLINE Packet2cf Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul (const Packet2cf & a, const Packet2cf & b) const inline
References Eigen::Aligned16, EIGEN_ALIGN16, EIGEN_ARM_PREFETCH, EIGEN_DEBUG_ALIGNED_LOAD, EIGEN_DEBUG_ALIGNED_STORE, EIGEN_DEBUG_UNALIGNED_LOAD, EIGEN_DEBUG_UNALIGNED_STORE, EIGEN_MAKE_CONJ_HELPER_CPLX_REAL, EIGEN_STRONG_INLINE, imag(), Eigen::internal::PacketBlock< Packet, N >::packet, Eigen::internal::Packet2cf::Packet2cf(), Eigen::internal::padd(), Eigen::internal::padd< Packet1cd >(), Eigen::internal::padd< Packet2d >(), Eigen::internal::pand< Packet1cd >(), Eigen::internal::pandnot< Packet1cd >(), Eigen::internal::pconj(), Eigen::internal::pcplxflip(), Eigen::internal::pdiv(), Eigen::internal::pdiv< Packet1cd >(), Eigen::internal::pdiv< Packet2cf >(), Eigen::internal::pfirst(), Eigen::internal::pfirst< Packet1cd >(), Eigen::internal::pload< Packet1cd >(), Eigen::internal::pload< Packet2d >(), Eigen::internal::ploaddup< Packet1cd >(), Eigen::internal::ploadu< Packet1cd >(), Eigen::internal::ploadu< Packet2d >(), Eigen::internal::pmadd(), Eigen::internal::pmul(), Eigen::internal::pmul< Packet1cd >(), Eigen::internal::pmul< Packet2d >(), Eigen::internal::pnegate(), Eigen::internal::por< Packet1cd >(), Eigen::internal::predux< Packet1cd >(), Eigen::internal::predux_mul< Packet1cd >(), Eigen::internal::preduxp< Packet1cd >(), Eigen::internal::preverse(), Eigen::internal::pset1< Packet1cd >(), Eigen::internal::pset1< Packet2d >(), Eigen::internal::pstore(), Eigen::internal::pstoreu(), Eigen::internal::psub< Packet1cd >(), Eigen::internal::psub< Packet2d >(), Eigen::internal::ptranspose(), Eigen::internal::pxor< Packet1cd >(), real(), Eigen::internal::size(), type, Eigen::internal::Packet2cf::v, and Eigen::internal::Packet1cd::v.
EIGEN_STRONG_INLINE Packet2cf Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul (const Packet2cf & a, const Packet2cf & b) const inline
References Eigen::internal::Packet2cf::cd, EIGEN_MAKE_CONJ_HELPER_CPLX_REAL, EIGEN_STRONG_INLINE, Eigen::internal::p16uc_REVERSE64, Eigen::internal::p2d_ZERO_, Eigen::internal::Packet1cd::Packet1cd(), Eigen::internal::pconj(), Eigen::internal::pcplxflip(), Eigen::internal::pdiv(), Eigen::internal::pdiv< Packet1cd >(), Eigen::internal::pdiv< Packet2cf >(), Eigen::internal::pmul(), Eigen::internal::preverse(), and Eigen::internal::Packet1cd::v.
The documentation for this struct was generated from the following file:
AltiVec/Complex.h