SmartMouse_2018: Eigen::internal::pardiso_run_selector< IndexType > Struct Template Reference
Eigen::internal::pardiso_run_selector< IndexType > Struct Template Reference
#include <PardisoSupport.h>
Static Public Member Functions
static IndexType run (_MKL_DSS_HANDLE_t pt, IndexType maxfct, IndexType mnum, IndexType type, IndexType phase, IndexType n, void *a, IndexType *ia, IndexType *ja, IndexType *perm, IndexType nrhs, IndexType *iparm, IndexType msglvl, void *b, void *x)
Member Function Documentation
template<typename IndexType> static IndexType Eigen::internal::pardiso_run_selector< IndexType >::run (_MKL_DSS_HANDLE_t pt, IndexType maxfct, IndexType mnum, IndexType type, IndexType phase, IndexType n, void * a, IndexType * ia, IndexType * ja, IndexType * perm, IndexType nrhs, IndexType * iparm, IndexType msglvl, void * b, void * x) inline static
References error().
Referenced by Eigen::PardisoImpl< Derived >::_solve_impl(), Eigen::PardisoImpl< Derived >::analyzePattern(), Eigen::PardisoImpl< Derived >::compute(), Eigen::PardisoImpl< Derived >::factorize(), and Eigen::PardisoImpl< PardisoLU< MatrixType > >::pardisoRelease().
The documentation for this struct was generated from the following file:
PardisoSupport.h