SmartMouse_2018: Eigen::internal::symm_pack_rhs< Scalar, Index, nr, StorageOrder > Struct Template Reference
Eigen::internal::symm_pack_rhs< Scalar, Index, nr, StorageOrder > Struct Template Reference
#include <SelfadjointMatrixMatrix.h>
Public Types
enum { PacketSize = packet_traits<Scalar>::size }
Public Member Functions
void operator() (Scalar *blockB, const Scalar *_rhs, Index rhsStride, Index rows, Index cols, Index k2)
Member Enumeration Documentation
template<typename Scalar, typename Index, int nr, int StorageOrder> anonymous enum
Enumerator
PacketSize
Member Function Documentation
template<typename Scalar, typename Index, int nr, int StorageOrder> void Eigen::internal::symm_pack_rhs< Scalar, Index, nr, StorageOrder >::operator() (Scalar * blockB, const Scalar * _rhs, Index rhsStride, Index rows, Index cols, Index k2) inline
References Eigen::half_impl::max(), Eigen::half_impl::min(), and real().
The documentation for this struct was generated from the following file:
SelfadjointMatrixMatrix.h