SmartMouse_2018: Eigen::EigenBase< Derived > Class Template Reference
Eigen::EigenBase< Derived > Class Template Reference
#include <EigenBase.h>
Public Types
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< Derived >::StorageKind StorageKind
Public Member Functions
EIGEN_DEVICE_FUNC Derived & derived ()
EIGEN_DEVICE_FUNC const Derived & derived () const
EIGEN_DEVICE_FUNC Derived & const_cast_derived () const
EIGEN_DEVICE_FUNC const Derived & const_derived () const
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
EIGEN_DEVICE_FUNC Index size () const
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
Detailed Description
template<typename Derived>
class Eigen::EigenBase< Derived >
Common base class for all classes T such that MatrixBase has an operator=(T) and a constructor MatrixBase(T).
In other words, an EigenBase object is an object that can be copied into a MatrixBase.
Besides MatrixBase-derived classes, this also includes special matrix classes such as diagonal matrices, etc.
Notice that this class is trivial, it is only used to disambiguate overloaded functions.
See also
TopicClassHierarchy
Member Typedef Documentation
template<typename Derived> typedef Eigen::Index Eigen::EigenBase< Derived >::Index
The interface type of indices.
To change this, #define the preprocessor symbol EIGEN_DEFAULT_DENSE_INDEX_TYPE.
Deprecated:
Since Eigen 3.3, its usage is deprecated. Use Eigen::Index instead.
See also
StorageIndex, TopicPreprocessorDirectives.
template<typename Derived> typedef internal::traits<Derived>::StorageKind Eigen::EigenBase< Derived >::StorageKind
Member Function Documentation
template<typename Derived> template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::addTo (Dest & dst) const inline
template<typename Derived> template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::applyThisOnTheLeft (Dest & dst) const inline
template<typename Derived> template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::applyThisOnTheRight (Dest & dst) const inline
template<typename Derived> EIGEN_DEVICE_FUNC Index Eigen::EigenBase< Derived >::cols (void) const inline
Returns
the number of columns.
See also
rows(), ColsAtCompileTime
Referenced by Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_resize_to_match(), Eigen::EigenBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::addTo(), Eigen::internal::BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options >::BandMatrixWrapper(), Eigen::RealSchur< _MatrixType >::compute(), Eigen::ComplexEigenSolver< _MatrixType >::compute(), Eigen::ComplexSchur< _MatrixType >::compute(), Eigen::EigenSolver< _MatrixType >::compute(), Eigen::LLT< _MatrixType, _UpLo >::compute(), Eigen::LDLT< _MatrixType, _UpLo >::compute(), Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::diagonal(), Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::diagonalLength(), Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::evalTo(), Eigen::EigenBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::size(), Eigen::EigenBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::subTo(), and Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::toDenseMatrix().
template<typename Derived> EIGEN_DEVICE_FUNC Derived& Eigen::EigenBase< Derived >::const_cast_derived () const inline
Referenced by Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::swap().
template<typename Derived> EIGEN_DEVICE_FUNC const Derived& Eigen::EigenBase< Derived >::const_derived () const inline
template<typename Derived> EIGEN_DEVICE_FUNC Derived& Eigen::EigenBase< Derived >::derived () inline
Returns
a reference to the derived object
Referenced by Eigen::IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::analyzePattern(), Eigen::MatrixBase< Derived >::applyOnTheLeft(), Eigen::MatrixBase< Derived >::applyOnTheRight(), Eigen::EigenBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::applyThisOnTheLeft(), Eigen::EigenBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::applyThisOnTheRight(), Eigen::internal::blueNorm_impl(), Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::coeffs(), Eigen::ColPivHouseholderQR< TransposeTypeWithSameStorageOrder >::ColPivHouseholderQR(), Eigen::EigenBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::cols(), Eigen::CompleteOrthogonalDecomposition< _MatrixType >::CompleteOrthogonalDecomposition(), Eigen::ComplexEigenSolver< _MatrixType >::ComplexEigenSolver(), Eigen::ComplexSchur< MatrixType >::ComplexSchur(), Eigen::FullPivLU< _MatrixType >::compute(), Eigen::PartialPivLU< _MatrixType >::compute(), Eigen::HessenbergDecomposition< MatrixType >::compute(), Eigen::Tridiagonalization< _MatrixType >::compute(), Eigen::HouseholderQR< TransposeTypeWithSameStorageOrder >::compute(), Eigen::IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::compute(), Eigen::RealSchur< _MatrixType >::compute(), Eigen::ComplexEigenSolver< _MatrixType >::compute(), Eigen::ComplexSchur< _MatrixType >::compute(), Eigen::EigenSolver< _MatrixType >::compute(), Eigen::SelfAdjointEigenSolver< _MatrixType >::compute(), Eigen::LLT< _MatrixType, _UpLo >::compute(), Eigen::FullPivHouseholderQR< _MatrixType >::compute(), Eigen::ColPivHouseholderQR< _MatrixType >::compute(), Eigen::LDLT< _MatrixType, _UpLo >::compute(), Eigen::EigenSolver< _MatrixType >::EigenSolver(), Eigen::EigenBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::evalTo(), Eigen::IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::factorize(), Eigen::FullPivHouseholderQR< TransposeTypeWithSameStorageOrder >::FullPivHouseholderQR(), Eigen::FullPivLU< _MatrixType >::FullPivLU(), Eigen::internal::generic_matrix_wrapper< MatrixType, false >::grab(), Eigen::UmfPackLU< _MatrixType >::grab(), Eigen::HouseholderQR< TransposeTypeWithSameStorageOrder >::HouseholderQR(), Eigen::LDLT< _MatrixType, _UpLo >::LDLT(), Eigen::LLT< _MatrixType, _UpLo >::LLT(), Eigen::RotationBase< Derived, 3 >::operator*(), Eigen::Translation< _Scalar, _Dim >::operator*(), Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex > >::operator*(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator*(), Eigen::operator*(), Eigen::MatrixBase< Derived >::operator*=(), Eigen::SparseMatrixBase< Derived >::operator+=(), Eigen::DenseBase< Derived >::operator+=(), Eigen::SparseMatrixBase< Derived >::operator-=(), Eigen::DenseBase< Derived >::operator-=(), Eigen::SparseMatrixBase< Derived >::operator=(), Eigen::MatrixBase< Derived >::operator=(), Eigen::DenseBase< Derived >::operator=(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator=(), Eigen::Map< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex >, _PacketAccess >::operator=(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::operator=(), Eigen::SparseMatrix< Scalar, RowMajor, StorageIndex >::operator=(), Eigen::PartialPivLU< _MatrixType >::PartialPivLU(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::PlainObjectBase(), Eigen::RealSchur< MatrixType >::RealSchur(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::resizeLike(), Eigen::EigenBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::rows(), Eigen::SelfAdjointEigenSolver< _MatrixType >::SelfAdjointEigenSolver(), Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::subs(), Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::supers(), and Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::Transform().
template<typename Derived> EIGEN_DEVICE_FUNC const Derived& Eigen::EigenBase< Derived >::derived () const inline
Returns
a const reference to the derived object
template<typename Derived> template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::evalTo (Dest & dst) const inline
Referenced by Eigen::EigenBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::addTo(), and Eigen::EigenBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::subTo().
template<typename Derived> EIGEN_DEVICE_FUNC Index Eigen::EigenBase< Derived >::rows (void) const inline
Returns
the number of rows.
See also
cols(), RowsAtCompileTime
Referenced by Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_resize_to_match(), Eigen::EigenBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::addTo(), Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::col(), Eigen::HessenbergDecomposition< MatrixType >::compute(), Eigen::Tridiagonalization< _MatrixType >::compute(), Eigen::RealSchur< _MatrixType >::compute(), Eigen::ComplexEigenSolver< _MatrixType >::compute(), Eigen::ComplexSchur< _MatrixType >::compute(), Eigen::EigenSolver< _MatrixType >::compute(), Eigen::LLT< _MatrixType, _UpLo >::compute(), Eigen::LDLT< _MatrixType, _UpLo >::compute(), Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::diagonal(), Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::diagonalLength(), Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::evalTo(), Eigen::HessenbergDecomposition< MatrixType >::HessenbergDecomposition(), Eigen::EigenBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::size(), Eigen::EigenBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::subTo(), and Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::toDenseMatrix().
template<typename Derived> EIGEN_DEVICE_FUNC Index Eigen::EigenBase< Derived >::size () const inline
Returns
the number of coefficients, which is rows()*cols().
See also
rows(), cols(), SizeAtCompileTime.
Referenced by Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_resize_to_match(), Eigen::internal::partial_lu_impl< Scalar, StorageOrder, PivIndex >::blocked_lu(), Eigen::PartialPivLU< _MatrixType >::compute(), Eigen::FullPivLU< _MatrixType >::computeInPlace(), and Eigen::internal::partial_lu_impl< Scalar, StorageOrder, PivIndex >::unblocked_lu().
template<typename Derived> template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::subTo (Dest & dst) const inline
The documentation for this class was generated from the following file:
EigenBase.h