SmartMouse_2018: Eigen::internal::lpNorm_selector< Derived, p > Struct Template Reference
Eigen::internal::lpNorm_selector< Derived, p > Struct Template Reference
#include <Dot.h>
Public Types
typedef NumTraits< typename traits< Derived >::Scalar >::Real RealScalar
Static Public Member Functions
static EIGEN_DEVICE_FUNC RealScalar run (const MatrixBase< Derived > &m)
Member Typedef Documentation
template<typename Derived , int p> typedef NumTraits<typename traits<Derived>::Scalar>::Real Eigen::internal::lpNorm_selector< Derived, p >::RealScalar
Member Function Documentation
template<typename Derived , int p> static EIGEN_DEVICE_FUNC RealScalar Eigen::internal::lpNorm_selector< Derived, p >::run (const MatrixBase< Derived > & m) inline static
References Eigen::MatrixBase< Derived >::cwiseAbs(), and Eigen::half_impl::pow().
Referenced by Eigen::MatrixBase< Derived >::lpNorm().
The documentation for this struct was generated from the following file:
Dot.h