SmartMouse_2018: Eigen::internal::quat_product< Arch, Derived1, Derived2, Scalar > Struct Template Reference
Eigen::internal::quat_product< Arch, Derived1, Derived2, Scalar > Struct Template Reference
#include <Quaternion.h>
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Quaternion< Scalar > run (const QuaternionBase< Derived1 > &a, const QuaternionBase< Derived2 > &b)
Member Function Documentation
template<int Arch, class Derived1 , class Derived2 , typename Scalar > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Quaternion<Scalar> Eigen::internal::quat_product< Arch, Derived1, Derived2, Scalar >::run (const QuaternionBase< Derived1 > & a, const QuaternionBase< Derived2 > & b) inline static
References EIGEN_STRONG_INLINE, Eigen::QuaternionBase< Derived >::w(), Eigen::QuaternionBase< Derived >::x(), Eigen::QuaternionBase< Derived >::y(), and Eigen::QuaternionBase< Derived >::z().
The documentation for this struct was generated from the following file:
Quaternion.h