SmartMouse_2018: Eigen::internal::Assignment< DstXprType, CwiseBinaryOp< internal::scalar_product_op< ScalarBis, Scalar >, const CwiseNullaryOp< internal::scalar_constant_op< ScalarBis >, Plain >, const Product< Lhs, Rhs, DefaultProduct > >, AssignFunc, Dense2Dense > Struct Template Reference
Eigen::internal::Assignment< DstXprType, CwiseBinaryOp< internal::scalar_product_op< ScalarBis, Scalar >, const CwiseNullaryOp< internal::scalar_constant_op< ScalarBis >, Plain >, const Product< Lhs, Rhs, DefaultProduct > >, AssignFunc, Dense2Dense > Struct Template Reference
#include <ProductEvaluators.h>
Public Types
typedef CwiseBinaryOp< internal::scalar_product_op< ScalarBis, Scalar >, const CwiseNullaryOp< internal::scalar_constant_op< ScalarBis >, Plain >, const Product< Lhs, Rhs, DefaultProduct > > SrcXprType
Static Public Member Functions
static EIGEN_STRONG_INLINE void run (DstXprType &dst, const SrcXprType &src, const AssignFunc &func)
Member Typedef Documentation
template<typename DstXprType , typename Lhs , typename Rhs , typename AssignFunc , typename Scalar , typename ScalarBis , typename Plain > typedef CwiseBinaryOp<internal::scalar_product_op<ScalarBis,Scalar>, const CwiseNullaryOp<internal::scalar_constant_op<ScalarBis>,Plain>, const Product<Lhs,Rhs,DefaultProduct> > Eigen::internal::Assignment< DstXprType, CwiseBinaryOp< internal::scalar_product_op< ScalarBis, Scalar >, const CwiseNullaryOp< internal::scalar_constant_op< ScalarBis >, Plain >, const Product< Lhs, Rhs, DefaultProduct > >, AssignFunc, Dense2Dense >::SrcXprType
Member Function Documentation
template<typename DstXprType , typename Lhs , typename Rhs , typename AssignFunc , typename Scalar , typename ScalarBis , typename Plain > static EIGEN_STRONG_INLINE void Eigen::internal::Assignment< DstXprType, CwiseBinaryOp< internal::scalar_product_op< ScalarBis, Scalar >, const CwiseNullaryOp< internal::scalar_constant_op< ScalarBis >, Plain >, const Product< Lhs, Rhs, DefaultProduct > >, AssignFunc, Dense2Dense >::run (DstXprType & dst, const SrcXprType & src, const AssignFunc & func) inline static
References Eigen::internal::call_assignment_no_alias(), Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::lhs(), and Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::rhs().
The documentation for this struct was generated from the following file:
ProductEvaluators.h