SmartMouse_2018: Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, SparseShape > Struct Template Reference
Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, SparseShape > Struct Template Reference
#include <SparsePermutation.h>
Public Types
enum { SrcStorageOrder = MatrixTypeCleaned::Flags&RowMajorBit ? RowMajor : ColMajor, MoveOuter = SrcStorageOrder==RowMajor ? Side==OnTheLeft : Side==OnTheRight }
typedef nested_eval< ExpressionType, 1 >::type MatrixType
typedef remove_all< MatrixType >::type MatrixTypeCleaned
typedef MatrixTypeCleaned::Scalar Scalar
typedef MatrixTypeCleaned::StorageIndex StorageIndex
typedef internal::conditional< MoveOuter, SparseMatrix< Scalar, SrcStorageOrder, StorageIndex >, SparseMatrix< Scalar, int(SrcStorageOrder)==RowMajor?ColMajor:RowMajor, StorageIndex > >::type ReturnType
Static Public Member Functions
template<typename Dest , typename PermutationType >
static void run (Dest &dst, const PermutationType &perm, const ExpressionType &xpr)
Member Typedef Documentation
template<typename ExpressionType , int Side, bool Transposed> typedef nested_eval<ExpressionType, 1>::type Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, SparseShape >::MatrixType
template<typename ExpressionType , int Side, bool Transposed> typedef remove_all<MatrixType>::type Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, SparseShape >::MatrixTypeCleaned
template<typename ExpressionType , int Side, bool Transposed> typedef internal::conditional<MoveOuter, SparseMatrix<Scalar,SrcStorageOrder,StorageIndex>, SparseMatrix<Scalar,int(SrcStorageOrder)==RowMajor?ColMajor:RowMajor,StorageIndex> >::type Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, SparseShape >::ReturnType
template<typename ExpressionType , int Side, bool Transposed> typedef MatrixTypeCleaned::Scalar Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, SparseShape >::Scalar
template<typename ExpressionType , int Side, bool Transposed> typedef MatrixTypeCleaned::StorageIndex Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, SparseShape >::StorageIndex
Member Enumeration Documentation
template<typename ExpressionType , int Side, bool Transposed> anonymous enum
Enumerator
SrcStorageOrder
MoveOuter
Member Function Documentation
template<typename ExpressionType , int Side, bool Transposed> template<typename Dest , typename PermutationType > static void Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, SparseShape >::run (Dest & dst, const PermutationType & perm, const ExpressionType & xpr) inline static
References Eigen::PlainObjectBase< Derived >::coeff(), Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex >::indices(), it, Eigen::OnTheLeft, Eigen::OnTheRight, Eigen::PlainObjectBase< Derived >::setZero(), and Eigen::PermutationBase< Derived >::transpose().
The documentation for this struct was generated from the following file:
SparsePermutation.h