SmartMouse_2018: Eigen::internal::Assignment< DstXprType, Inverse< XprType >, internal::assign_op< typename DstXprType::Scalar, typename XprType::Scalar >, Dense2Dense > Struct Template Reference
Eigen::internal::Assignment< DstXprType, Inverse< XprType >, internal::assign_op< typename DstXprType::Scalar, typename XprType::Scalar >, Dense2Dense > Struct Template Reference
#include <InverseImpl.h>
Public Types
typedef Inverse< XprType > SrcXprType
Static Public Member Functions
static void run (DstXprType &dst, const SrcXprType &src, const internal::assign_op< typename DstXprType::Scalar, typename XprType::Scalar > &)
Member Typedef Documentation
template<typename DstXprType , typename XprType > typedef Inverse<XprType> Eigen::internal::Assignment< DstXprType, Inverse< XprType >, internal::assign_op< typename DstXprType::Scalar, typename XprType::Scalar >, Dense2Dense >::SrcXprType
Member Function Documentation
template<typename DstXprType , typename XprType > static void Eigen::internal::Assignment< DstXprType, Inverse< XprType >, internal::assign_op< typename DstXprType::Scalar, typename XprType::Scalar >, Dense2Dense >::run (DstXprType & dst, const SrcXprType & src, const internal::assign_op< typename DstXprType::Scalar, typename XprType::Scalar > &) inline static
References Eigen::Inverse< XprType >::cols(), eigen_assert, EIGEN_ONLY_USED_FOR_DEBUG, EIGEN_PLAIN_ENUM_MIN, Eigen::internal::extract_data(), Eigen::Inverse< XprType >::nestedExpression(), Eigen::Inverse< XprType >::rows(), and Eigen::internal::compute_inverse< MatrixType, ResultType, Size >::run().
The documentation for this struct was generated from the following file:
InverseImpl.h