SmartMouse_2018: Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased > Struct Template Reference
Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased > Struct Template Reference
#include <CoreEvaluators.h>
Public Types
enum { CoeffReadCost = evaluator<ArgType>::CoeffReadCost, Flags = evaluator<ArgType>::Flags ^ RowMajorBit, Alignment = evaluator<ArgType>::Alignment }
typedef Transpose< ArgType > XprType
typedef XprType::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
Public Types inherited from Eigen::internal::evaluator_base< Transpose< ArgType > >
enum
typedef traits< Transpose< ArgType > > ExpressionTraits
Public Member Functions
EIGEN_DEVICE_FUNC unary_evaluator (const XprType &t)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index row, Index col) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index row, Index col)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE XprType::Scalar & coeffRef (Index index)
template<int LoadMode, typename PacketType >
EIGEN_STRONG_INLINE PacketType packet (Index row, Index col) const
template<int LoadMode, typename PacketType >
EIGEN_STRONG_INLINE PacketType packet (Index index) const
template<int StoreMode, typename PacketType >
EIGEN_STRONG_INLINE void writePacket (Index row, Index col, const PacketType &x)
template<int StoreMode, typename PacketType >
EIGEN_STRONG_INLINE void writePacket (Index index, const PacketType &x)
Public Member Functions inherited from Eigen::internal::evaluator_base< Transpose< ArgType > >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE evaluator_base ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ~evaluator_base ()
Protected Attributes
evaluator< ArgType > m_argImpl
Member Typedef Documentation
template<typename ArgType > typedef XprType::CoeffReturnType Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::CoeffReturnType
template<typename ArgType > typedef XprType::Scalar Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::Scalar
template<typename ArgType > typedef Transpose<ArgType> Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::XprType
Member Enumeration Documentation
template<typename ArgType > anonymous enum
Enumerator
CoeffReadCost
Flags
Alignment
Constructor & Destructor Documentation
template<typename ArgType > EIGEN_DEVICE_FUNC Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::unary_evaluator (const XprType & t) inline explicit
Member Function Documentation
template<typename ArgType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::coeff (Index row, Index col) const inline
References EIGEN_STRONG_INLINE.
template<typename ArgType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::coeff (Index index) const inline
References EIGEN_STRONG_INLINE.
template<typename ArgType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::coeffRef (Index row, Index col) inline
References EIGEN_STRONG_INLINE.
template<typename ArgType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE XprType::Scalar& Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::coeffRef (Index index) inline
References EIGEN_STRONG_INLINE.
template<typename ArgType > template<int LoadMode, typename PacketType > EIGEN_STRONG_INLINE PacketType Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::packet (Index row, Index col) const inline
References col(), EIGEN_STRONG_INLINE, and row().
template<typename ArgType > template<int LoadMode, typename PacketType > EIGEN_STRONG_INLINE PacketType Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::packet (Index index) const inline
References EIGEN_STRONG_INLINE.
template<typename ArgType > template<int StoreMode, typename PacketType > EIGEN_STRONG_INLINE void Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::writePacket (Index row, Index col, const PacketType & x) inline
References col(), EIGEN_STRONG_INLINE, and row().
template<typename ArgType > template<int StoreMode, typename PacketType > EIGEN_STRONG_INLINE void Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::writePacket (Index index, const PacketType & x) inline
Member Data Documentation
template<typename ArgType > evaluator<ArgType> Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::m_argImpl protected
The documentation for this struct was generated from the following file:
CoreEvaluators.h