SmartMouse_2018: Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > > Struct Template Reference
Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > > Struct Template Reference
#include <CoreEvaluators.h>
Public Types
enum {
IsRowMajor = XprType::IsRowMajor, IsColMajor = !IsRowMajor, ReverseRow = (Direction == Vertical) || (Direction == BothDirections), ReverseCol = (Direction == Horizontal) || (Direction == BothDirections),
ReversePacket, CoeffReadCost = evaluator<ArgType>::CoeffReadCost, Flags0 = evaluator<ArgType>::Flags, LinearAccess,
Flags = int(Flags0) & (HereditaryBits | PacketAccessBit | LinearAccess), Alignment = 0
}
typedef Reverse< ArgType, Direction > XprType
typedef XprType::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
Public Types inherited from Eigen::internal::evaluator_base< Reverse< ArgType, Direction > >
enum
typedef traits< Reverse< ArgType, Direction > > ExpressionTraits
Public Member Functions
EIGEN_DEVICE_FUNC unary_evaluator (const XprType &reverse)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index row, Index col) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index row, Index col)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index index)
template<int LoadMode, typename PacketType >
EIGEN_STRONG_INLINE PacketType packet (Index row, Index col) const
template<int LoadMode, typename PacketType >
EIGEN_STRONG_INLINE PacketType packet (Index index) const
template<int LoadMode, typename PacketType >
EIGEN_STRONG_INLINE void writePacket (Index row, Index col, const PacketType &x)
template<int LoadMode, typename PacketType >
EIGEN_STRONG_INLINE void writePacket (Index index, const PacketType &x)
Public Member Functions inherited from Eigen::internal::evaluator_base< Reverse< ArgType, Direction > >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE evaluator_base ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ~evaluator_base ()
Protected Attributes
evaluator< ArgType > m_argImpl
const variable_if_dynamic< Index, ReverseRow?ArgType::RowsAtCompileTime:1 > m_rows
const variable_if_dynamic< Index, ReverseCol?ArgType::ColsAtCompileTime:1 > m_cols
Member Typedef Documentation
template<typename ArgType , int Direction> typedef XprType::CoeffReturnType Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::CoeffReturnType
template<typename ArgType , int Direction> typedef XprType::Scalar Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::Scalar
template<typename ArgType , int Direction> typedef Reverse<ArgType, Direction> Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::XprType
Member Enumeration Documentation
template<typename ArgType , int Direction> anonymous enum
Enumerator
IsRowMajor
IsColMajor
ReverseRow
ReverseCol
ReversePacket
CoeffReadCost
Flags0
LinearAccess
Flags
Alignment
Constructor & Destructor Documentation
template<typename ArgType , int Direction> EIGEN_DEVICE_FUNC Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::unary_evaluator (const XprType & reverse) inline explicit
References EIGEN_STRONG_INLINE.
Member Function Documentation
template<typename ArgType , int Direction> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::coeff (Index row, Index col) const inline
References col(), EIGEN_STRONG_INLINE, and row().
template<typename ArgType , int Direction> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::coeff (Index index) const inline
References EIGEN_STRONG_INLINE.
template<typename ArgType , int Direction> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::coeffRef (Index row, Index col) inline
References col(), EIGEN_STRONG_INLINE, and row().
template<typename ArgType , int Direction> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::coeffRef (Index index) inline
References EIGEN_STRONG_INLINE.
template<typename ArgType , int Direction> template<int LoadMode, typename PacketType > EIGEN_STRONG_INLINE PacketType Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::packet (Index row, Index col) const inline
References col(), EIGEN_STRONG_INLINE, and row().
template<typename ArgType , int Direction> template<int LoadMode, typename PacketType > EIGEN_STRONG_INLINE PacketType Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::packet (Index index) const inline
References EIGEN_STRONG_INLINE, and Eigen::internal::preverse().
template<typename ArgType , int Direction> template<int LoadMode, typename PacketType > EIGEN_STRONG_INLINE void Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::writePacket (Index row, Index col, const PacketType & x) inline
References col(), EIGEN_STRONG_INLINE, and row().
template<typename ArgType , int Direction> template<int LoadMode, typename PacketType > EIGEN_STRONG_INLINE void Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::writePacket (Index index, const PacketType & x) inline
References Eigen::internal::preverse().
Member Data Documentation
template<typename ArgType , int Direction> evaluator<ArgType> Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::m_argImpl protected
template<typename ArgType , int Direction> const variable_if_dynamic<Index, ReverseCol ? ArgType::ColsAtCompileTime : 1> Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::m_cols protected
template<typename ArgType , int Direction> const variable_if_dynamic<Index, ReverseRow ? ArgType::RowsAtCompileTime : 1> Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::m_rows protected
The documentation for this struct was generated from the following file:
CoreEvaluators.h