SmartMouse_2018: Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, false, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version > Struct Template Reference
Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, false, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version > Struct Template Reference
#include <TriangularMatrixMatrix.h>
Public Types
enum { SmallPanelWidth = EIGEN_PLAIN_ENUM_MAX(Traits::mr,Traits::nr), IsLower = (Mode&Lower) == Lower, SetDiag = (Mode&(ZeroDiag|UnitDiag)) ? 0 : 1 }
typedef gebp_traits< Scalar, Scalar > Traits
Static Public Member Functions
static EIGEN_DONT_INLINE void run (Index _rows, Index _cols, Index _depth, const Scalar *_lhs, Index lhsStride, const Scalar *_rhs, Index rhsStride, Scalar *res, Index resStride, const Scalar &alpha, level3_blocking< Scalar, Scalar > &blocking)
Member Typedef Documentation
template<typename Scalar , typename Index , int Mode, int LhsStorageOrder, bool ConjugateLhs, int RhsStorageOrder, bool ConjugateRhs, int Version> typedef gebp_traits<Scalar,Scalar> Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, false, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >::Traits
Member Enumeration Documentation
template<typename Scalar , typename Index , int Mode, int LhsStorageOrder, bool ConjugateLhs, int RhsStorageOrder, bool ConjugateRhs, int Version> anonymous enum
Enumerator
SmallPanelWidth
IsLower
SetDiag
Member Function Documentation
template<typename Scalar , typename Index , int Mode, int LhsStorageOrder, bool ConjugateLhs, int RhsStorageOrder, bool ConjugateRhs, int Version> EIGEN_DONT_INLINE void Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, false, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >::run (Index _rows, Index _cols, Index _depth, const Scalar * _lhs, Index lhsStride, const Scalar * _rhs, Index rhsStride, Scalar * res, Index resStride, const Scalar & alpha, level3_blocking< Scalar, Scalar > & blocking) static
References Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::blockA(), Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::blockB(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::coeffRef(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::data(), ei_declare_aligned_stack_constructed_variable, EIGEN_MAX_ALIGN_BYTES, Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::kc(), Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::mc(), Eigen::half_impl::min(), Eigen::Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >::outerStride(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::setOnes(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::setZero(), and Eigen::ZeroDiag.
The documentation for this struct was generated from the following file:
TriangularMatrixMatrix.h