SmartMouse_2018: Eigen::internal::palign_impl< Offset, Packet2d > Struct Template Reference
Eigen::internal::palign_impl< Offset, Packet2d > Struct Template Reference
#include <PacketMath.h>
Static Public Member Functions
static EIGEN_STRONG_INLINE void run (Packet2d &first, const Packet2d &second)
static EIGEN_STRONG_INLINE void run (Packet2d &first, const Packet2d &second)
Member Function Documentation
template<int Offset> static EIGEN_STRONG_INLINE void Eigen::internal::palign_impl< Offset, Packet2d >::run (Packet2d & first, const Packet2d & second) inline static
References EIGEN_ALIGN16, EIGEN_DEBUG_ALIGNED_LOAD, EIGEN_DEBUG_ALIGNED_STORE, EIGEN_STRONG_INLINE, Eigen::internal::padd< Packet2d >(), Eigen::internal::padd< Packet4f >(), Eigen::internal::padd< Packet4i >(), Eigen::internal::pbroadcast4< Packet2d >(), Eigen::internal::pbroadcast4< Packet4f >(), Eigen::internal::pbroadcast4< Packet4i >(), Eigen::internal::pconj(), Eigen::internal::pdiv< Packet2d >(), Eigen::internal::pdiv< Packet4f >(), Eigen::internal::pdiv< Packet4i >(), Eigen::internal::pgather< double, Packet2d >(), Eigen::internal::pgather< float, Packet4f >(), Eigen::internal::pgather< int, Packet4i >(), Eigen::internal::pload< Packet2d >(), Eigen::internal::pload< Packet4f >(), Eigen::internal::pload< Packet4i >(), Eigen::internal::pmadd(), Eigen::internal::pmul< Packet2d >(), Eigen::internal::pmul< Packet4f >(), Eigen::internal::pmul< Packet4i >(), Eigen::internal::pnegate(), Eigen::internal::pscatter< double, Packet2d >(), Eigen::internal::pscatter< float, Packet4f >(), Eigen::internal::pscatter< int, Packet4i >(), Eigen::internal::pset1< Packet2d >(), Eigen::internal::pset1< Packet4f >(), Eigen::internal::pset1< Packet4i >(), Eigen::internal::pstore< double >(), Eigen::internal::pstore< float >(), Eigen::internal::pstore< int >(), Eigen::internal::psub< Packet2d >(), Eigen::internal::psub< Packet4f >(), Eigen::internal::psub< Packet4i >(), Eigen::internal::Packet::v2d, Eigen::internal::Packet4f::v4f, and Eigen::internal::Packet::v4i.
template<int Offset> static EIGEN_STRONG_INLINE void Eigen::internal::palign_impl< Offset, Packet2d >::run (Packet2d & first, const Packet2d & second) inline static
References Eigen::internal::PacketBlock< Packet, N >::packet, and Eigen::internal::ptranspose().
The documentation for this struct was generated from the following file:
SSE/PacketMath.h