SmartMouse_2018: Eigen::internal::Assignment< DstXprType, Inverse< FullPivLU< MatrixType > >, internal::assign_op< typename DstXprType::Scalar, typename FullPivLU< MatrixType >::Scalar >, Dense2Dense > Struct Template Reference
Eigen::internal::Assignment< DstXprType, Inverse< FullPivLU< MatrixType > >, internal::assign_op< typename DstXprType::Scalar, typename FullPivLU< MatrixType >::Scalar >, Dense2Dense > Struct Template Reference
#include <FullPivLU.h>
Public Types
typedef FullPivLU< MatrixType > LuType
typedef Inverse< LuType > SrcXprType
Static Public Member Functions
static void run (DstXprType &dst, const SrcXprType &src, const internal::assign_op< typename DstXprType::Scalar, typename MatrixType::Scalar > &)
Member Typedef Documentation
template<typename DstXprType , typename MatrixType > typedef FullPivLU<MatrixType> Eigen::internal::Assignment< DstXprType, Inverse< FullPivLU< MatrixType > >, internal::assign_op< typename DstXprType::Scalar, typename FullPivLU< MatrixType >::Scalar >, Dense2Dense >::LuType
template<typename DstXprType , typename MatrixType > typedef Inverse<LuType> Eigen::internal::Assignment< DstXprType, Inverse< FullPivLU< MatrixType > >, internal::assign_op< typename DstXprType::Scalar, typename FullPivLU< MatrixType >::Scalar >, Dense2Dense >::SrcXprType
Member Function Documentation
template<typename DstXprType , typename MatrixType > static void Eigen::internal::Assignment< DstXprType, Inverse< FullPivLU< MatrixType > >, internal::assign_op< typename DstXprType::Scalar, typename FullPivLU< MatrixType >::Scalar >, Dense2Dense >::run (DstXprType & dst, const SrcXprType & src, const internal::assign_op< typename DstXprType::Scalar, typename MatrixType::Scalar > &) inline static
References Eigen::Inverse< XprType >::cols(), Eigen::Inverse< XprType >::nestedExpression(), and Eigen::Inverse< XprType >::rows().
The documentation for this struct was generated from the following file:
FullPivLU.h