SmartMouse_2018: Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased > Struct Template Reference
Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased > Struct Template Reference
#include <CoreEvaluators.h>
Public Types
enum { RowsAtCompileTime = XprType::RowsAtCompileTime }
typedef Block< ArgType, BlockRows, BlockCols, InnerPanel > XprType
typedef XprType::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
Public Types inherited from Eigen::internal::evaluator_base< Block< ArgType, BlockRows, BlockCols, InnerPanel > >
enum
typedef traits< Block< ArgType, BlockRows, BlockCols, InnerPanel > > ExpressionTraits
Public Member Functions
EIGEN_DEVICE_FUNC unary_evaluator (const XprType &block)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index row, Index col) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index row, Index col)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index index)
template<int LoadMode, typename PacketType >
EIGEN_STRONG_INLINE PacketType packet (Index row, Index col) const
template<int LoadMode, typename PacketType >
EIGEN_STRONG_INLINE PacketType packet (Index index) const
template<int StoreMode, typename PacketType >
EIGEN_STRONG_INLINE void writePacket (Index row, Index col, const PacketType &x)
template<int StoreMode, typename PacketType >
EIGEN_STRONG_INLINE void writePacket (Index index, const PacketType &x)
Public Member Functions inherited from Eigen::internal::evaluator_base< Block< ArgType, BlockRows, BlockCols, InnerPanel > >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE evaluator_base ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ~evaluator_base ()
Protected Attributes
evaluator< ArgType > m_argImpl
const variable_if_dynamic< Index,(ArgType::RowsAtCompileTime==1 &&BlockRows==1)?0:Dynamic > m_startRow
const variable_if_dynamic< Index,(ArgType::ColsAtCompileTime==1 &&BlockCols==1)?0:Dynamic > m_startCol
Member Typedef Documentation
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> typedef XprType::CoeffReturnType Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::CoeffReturnType
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> typedef XprType::Scalar Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::Scalar
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> typedef Block<ArgType, BlockRows, BlockCols, InnerPanel> Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::XprType
Member Enumeration Documentation
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> anonymous enum
Enumerator
RowsAtCompileTime
Constructor & Destructor Documentation
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> EIGEN_DEVICE_FUNC Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::unary_evaluator (const XprType & block) inline explicit
Member Function Documentation
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::coeff (Index row, Index col) const inline
References col(), EIGEN_STRONG_INLINE, and row().
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::coeff (Index index) const inline
References EIGEN_STRONG_INLINE.
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::coeffRef (Index row, Index col) inline
References col(), EIGEN_STRONG_INLINE, and row().
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::coeffRef (Index index) inline
References EIGEN_STRONG_INLINE.
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> template<int LoadMode, typename PacketType > EIGEN_STRONG_INLINE PacketType Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::packet (Index row, Index col) const inline
References col(), EIGEN_STRONG_INLINE, and row().
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> template<int LoadMode, typename PacketType > EIGEN_STRONG_INLINE PacketType Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::packet (Index index) const inline
References EIGEN_STRONG_INLINE.
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> template<int StoreMode, typename PacketType > EIGEN_STRONG_INLINE void Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::writePacket (Index row, Index col, const PacketType & x) inline
References col(), EIGEN_STRONG_INLINE, and row().
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> template<int StoreMode, typename PacketType > EIGEN_STRONG_INLINE void Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::writePacket (Index index, const PacketType & x) inline
Member Data Documentation
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> evaluator<ArgType> Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::m_argImpl protected
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> const variable_if_dynamic<Index, (ArgType::ColsAtCompileTime == 1 && BlockCols==1) ? 0 : Dynamic> Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::m_startCol protected
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> const variable_if_dynamic<Index, (ArgType::RowsAtCompileTime == 1 && BlockRows==1) ? 0 : Dynamic> Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::m_startRow protected
The documentation for this struct was generated from the following file:
CoreEvaluators.h