SmartMouse_2018: Eigen::internal::conj_helper< LhsScalar, RhsScalar, ConjLhs, ConjRhs > Struct Template Reference
Eigen::internal::conj_helper< LhsScalar, RhsScalar, ConjLhs, ConjRhs > Struct Template Reference
#include <BlasUtil.h>
Public Types
typedef ScalarBinaryOpTraits< LhsScalar, RhsScalar >::ReturnType Scalar
Public Member Functions
EIGEN_STRONG_INLINE Scalar pmadd (const LhsScalar &x, const RhsScalar &y, const Scalar &c) const
EIGEN_STRONG_INLINE Scalar pmul (const LhsScalar &x, const RhsScalar &y) const
Member Typedef Documentation
template<typename LhsScalar, typename RhsScalar, bool ConjLhs, bool ConjRhs> typedef ScalarBinaryOpTraits<LhsScalar,RhsScalar>::ReturnType Eigen::internal::conj_helper< LhsScalar, RhsScalar, ConjLhs, ConjRhs >::Scalar
Member Function Documentation
template<typename LhsScalar, typename RhsScalar, bool ConjLhs, bool ConjRhs> EIGEN_STRONG_INLINE Scalar Eigen::internal::conj_helper< LhsScalar, RhsScalar, ConjLhs, ConjRhs >::pmadd (const LhsScalar & x, const RhsScalar & y, const Scalar & c) const inline
Referenced by Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::madd(), Eigen::internal::selfadjoint_matrix_vector_product< Scalar, Index, StorageOrder, UpLo, ConjugateLhs, ConjugateRhs, Version >::run(), Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, ColMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::run(), and Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, RowMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::run().
template<typename LhsScalar, typename RhsScalar, bool ConjLhs, bool ConjRhs> EIGEN_STRONG_INLINE Scalar Eigen::internal::conj_helper< LhsScalar, RhsScalar, ConjLhs, ConjRhs >::pmul (const LhsScalar & x, const RhsScalar & y) const inline
Referenced by Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::madd(), Eigen::internal::selfadjoint_matrix_vector_product< Scalar, Index, StorageOrder, UpLo, ConjugateLhs, ConjugateRhs, Version >::run(), Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, ColMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::run(), and Eigen::internal::apply_rotation_in_the_plane_selector< Scalar, OtherScalar, SizeAtCompileTime, MinAlignment, true >::run().
The documentation for this struct was generated from the following file:
BlasUtil.h