SmartMouse_2018: Eigen::internal::conj_helper< std::complex< RealScalar >, std::complex< RealScalar >, false, true > Struct Template Reference
Eigen::internal::conj_helper< std::complex< RealScalar >, std::complex< RealScalar >, false, true > Struct Template Reference
#include <BlasUtil.h>
Public Types
typedef std::complex< RealScalar > Scalar
Public Member Functions
EIGEN_STRONG_INLINE Scalar pmadd (const Scalar &x, const Scalar &y, const Scalar &c) const
EIGEN_STRONG_INLINE Scalar pmul (const Scalar &x, const Scalar &y) const
Member Typedef Documentation
template<typename RealScalar > typedef std::complex<RealScalar> Eigen::internal::conj_helper< std::complex< RealScalar >, std::complex< RealScalar >, false, true >::Scalar
Member Function Documentation
template<typename RealScalar > EIGEN_STRONG_INLINE Scalar Eigen::internal::conj_helper< std::complex< RealScalar >, std::complex< RealScalar >, false, true >::pmadd (const Scalar & x, const Scalar & y, const Scalar & c) const inline
References Eigen::internal::pmul().
template<typename RealScalar > EIGEN_STRONG_INLINE Scalar Eigen::internal::conj_helper< std::complex< RealScalar >, std::complex< RealScalar >, false, true >::pmul (const Scalar & x, const Scalar & y) const inline
References imag(), and real().
The documentation for this struct was generated from the following file:
BlasUtil.h