SmartMouse_2018: Eigen::internal::conj_helper< Packet2cd, Packet2cd, true, true > Struct Template Reference
Eigen::internal::conj_helper< Packet2cd, Packet2cd, true, true > Struct Template Reference
#include <Complex.h>
Public Member Functions
EIGEN_STRONG_INLINE Packet2cd pmadd (const Packet2cd &x, const Packet2cd &y, const Packet2cd &c) const
EIGEN_STRONG_INLINE Packet2cd pmul (const Packet2cd &a, const Packet2cd &b) const
Member Function Documentation
EIGEN_STRONG_INLINE Packet2cd Eigen::internal::conj_helper< Packet2cd, Packet2cd, true, true >::pmadd (const Packet2cd & x, const Packet2cd & y, const Packet2cd & c) const inline
References Eigen::internal::padd(), and Eigen::internal::pmul().
EIGEN_STRONG_INLINE Packet2cd Eigen::internal::conj_helper< Packet2cd, Packet2cd, true, true >::pmul (const Packet2cd & a, const Packet2cd & b) const inline
References EIGEN_MAKE_CONJ_HELPER_CPLX_REAL, Eigen::internal::pconj(), and Eigen::internal::pmul().
The documentation for this struct was generated from the following file:
AVX/Complex.h