SmartMouse_2018: Eigen::half Struct Reference
Eigen::half Struct Reference
#include <Half.h>
Public Types
typedef half_impl::__half_raw __half_raw
Public Member Functions
EIGEN_DEVICE_FUNC half ()
EIGEN_DEVICE_FUNC half (const __half_raw &h)
EIGEN_DEVICE_FUNC half (const half &h)
EIGEN_DEVICE_FUNC half (bool b)
template<class T >
EIGEN_DEVICE_FUNC half (const T &val)
EIGEN_DEVICE_FUNC half (float f)
EIGEN_DEVICE_FUNC EIGEN_EXPLICIT_CAST (bool) const
EIGEN_DEVICE_FUNC EIGEN_EXPLICIT_CAST (signed char) const
EIGEN_DEVICE_FUNC EIGEN_EXPLICIT_CAST (unsigned char) const
EIGEN_DEVICE_FUNC EIGEN_EXPLICIT_CAST (short) const
EIGEN_DEVICE_FUNC EIGEN_EXPLICIT_CAST (unsigned short) const
EIGEN_DEVICE_FUNC EIGEN_EXPLICIT_CAST (int) const
EIGEN_DEVICE_FUNC EIGEN_EXPLICIT_CAST (unsigned int) const
EIGEN_DEVICE_FUNC EIGEN_EXPLICIT_CAST (long) const
EIGEN_DEVICE_FUNC EIGEN_EXPLICIT_CAST (unsigned long) const
EIGEN_DEVICE_FUNC EIGEN_EXPLICIT_CAST (long long) const
EIGEN_DEVICE_FUNC EIGEN_EXPLICIT_CAST (unsigned long long) const
EIGEN_DEVICE_FUNC EIGEN_EXPLICIT_CAST (float) const
EIGEN_DEVICE_FUNC EIGEN_EXPLICIT_CAST (double) const
EIGEN_DEVICE_FUNC half & operator= (const half &other)
Public Member Functions inherited from Eigen::half_impl::half_base
EIGEN_DEVICE_FUNC half_base ()
EIGEN_DEVICE_FUNC half_base (const half_base &h)
EIGEN_DEVICE_FUNC half_base (const __half_raw &h)
Public Member Functions inherited from Eigen::half_impl::__half_raw
EIGEN_DEVICE_FUNC __half_raw ()
EIGEN_DEVICE_FUNC __half_raw (unsigned short raw)
Additional Inherited Members
Public Attributes inherited from Eigen::half_impl::__half_raw
unsigned short x
Member Typedef Documentation
typedef half_impl::__half_raw Eigen::half::__half_raw
Constructor & Destructor Documentation
EIGEN_DEVICE_FUNC Eigen::half::half () inline
EIGEN_DEVICE_FUNC Eigen::half::half (const __half_raw & h) inline
EIGEN_DEVICE_FUNC Eigen::half::half (const half & h) inline
EIGEN_DEVICE_FUNC Eigen::half::half (bool b) inline explicit
template<class T > EIGEN_DEVICE_FUNC Eigen::half::half (const T & val) inline explicit
EIGEN_DEVICE_FUNC Eigen::half::half (float f) inline explicit
Member Function Documentation
EIGEN_DEVICE_FUNC Eigen::half::EIGEN_EXPLICIT_CAST (bool) const inline
References Eigen::half_impl::__half_raw::x.
EIGEN_DEVICE_FUNC Eigen::half::EIGEN_EXPLICIT_CAST (signed char) const inline
References Eigen::half_impl::half_to_float().
EIGEN_DEVICE_FUNC Eigen::half::EIGEN_EXPLICIT_CAST (unsigned char) const inline
References Eigen::half_impl::half_to_float().
EIGEN_DEVICE_FUNC Eigen::half::EIGEN_EXPLICIT_CAST (short) const inline
References Eigen::half_impl::half_to_float().
EIGEN_DEVICE_FUNC Eigen::half::EIGEN_EXPLICIT_CAST (unsigned short) const inline
References Eigen::half_impl::half_to_float().
EIGEN_DEVICE_FUNC Eigen::half::EIGEN_EXPLICIT_CAST (int) const inline
References Eigen::half_impl::half_to_float().
EIGEN_DEVICE_FUNC Eigen::half::EIGEN_EXPLICIT_CAST (unsigned int) const inline
References Eigen::half_impl::half_to_float().
EIGEN_DEVICE_FUNC Eigen::half::EIGEN_EXPLICIT_CAST (long) const inline
References Eigen::half_impl::half_to_float().
EIGEN_DEVICE_FUNC Eigen::half::EIGEN_EXPLICIT_CAST (unsigned long) const inline
References Eigen::half_impl::half_to_float().
EIGEN_DEVICE_FUNC Eigen::half::EIGEN_EXPLICIT_CAST (long long) const inline
References Eigen::half_impl::half_to_float().
EIGEN_DEVICE_FUNC Eigen::half::EIGEN_EXPLICIT_CAST (unsigned long long) const inline
References Eigen::half_impl::half_to_float().
EIGEN_DEVICE_FUNC Eigen::half::EIGEN_EXPLICIT_CAST (float) const inline
References Eigen::half_impl::half_to_float().
EIGEN_DEVICE_FUNC Eigen::half::EIGEN_EXPLICIT_CAST (double) const inline
References Eigen::half_impl::half_to_float().
EIGEN_DEVICE_FUNC half& Eigen::half::operator= (const half & other) inline
References Eigen::half_impl::operator!=(), Eigen::half_impl::operator*(), Eigen::half_impl::operator*=(), Eigen::half_impl::operator+(), Eigen::half_impl::operator+=(), Eigen::half_impl::operator-(), Eigen::half_impl::operator-=(), Eigen::half_impl::operator/(), Eigen::half_impl::operator/=(), Eigen::half_impl::operator<(), Eigen::half_impl::operator<=(), Eigen::half_impl::operator==(), Eigen::half_impl::operator>(), Eigen::half_impl::operator>=(), and Eigen::half_impl::__half_raw::x.
The documentation for this struct was generated from the following file:
Half.h