SmartMouse_2018: Eigen::internal::Assignment< DstXprType, SparseSymmetricPermutationProduct< MatrixType, Mode >, internal::assign_op< Scalar, typename MatrixType::Scalar >, Sparse2Sparse > Struct Template Reference
Eigen::internal::Assignment< DstXprType, SparseSymmetricPermutationProduct< MatrixType, Mode >, internal::assign_op< Scalar, typename MatrixType::Scalar >, Sparse2Sparse > Struct Template Reference
#include <SparseSelfAdjointView.h>
Public Types
typedef SparseSymmetricPermutationProduct< MatrixType, Mode > SrcXprType
typedef DstXprType::StorageIndex DstIndex
Static Public Member Functions
template<int Options>
static void run (SparseMatrix< Scalar, Options, DstIndex > &dst, const SrcXprType &src, const internal::assign_op< Scalar, typename MatrixType::Scalar > &)
template<typename DestType , unsigned int DestMode>
static void run (SparseSelfAdjointView< DestType, DestMode > &dst, const SrcXprType &src, const internal::assign_op< Scalar, typename MatrixType::Scalar > &)
Member Typedef Documentation
template<typename DstXprType , typename MatrixType , int Mode, typename Scalar > typedef DstXprType::StorageIndex Eigen::internal::Assignment< DstXprType, SparseSymmetricPermutationProduct< MatrixType, Mode >, internal::assign_op< Scalar, typename MatrixType::Scalar >, Sparse2Sparse >::DstIndex
template<typename DstXprType , typename MatrixType , int Mode, typename Scalar > typedef SparseSymmetricPermutationProduct<MatrixType,Mode> Eigen::internal::Assignment< DstXprType, SparseSymmetricPermutationProduct< MatrixType, Mode >, internal::assign_op< Scalar, typename MatrixType::Scalar >, Sparse2Sparse >::SrcXprType
Member Function Documentation
template<typename DstXprType , typename MatrixType , int Mode, typename Scalar > template<int Options> static void Eigen::internal::Assignment< DstXprType, SparseSymmetricPermutationProduct< MatrixType, Mode >, internal::assign_op< Scalar, typename MatrixType::Scalar >, Sparse2Sparse >::run (SparseMatrix< Scalar, Options, DstIndex > & dst, const SrcXprType & src, const internal::assign_op< Scalar, typename MatrixType::Scalar > &) inline static
References Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex >::indices(), Eigen::SparseSymmetricPermutationProduct< MatrixType, Mode >::matrix(), and Eigen::SparseSymmetricPermutationProduct< MatrixType, Mode >::perm().
template<typename DstXprType , typename MatrixType , int Mode, typename Scalar > template<typename DestType , unsigned int DestMode> static void Eigen::internal::Assignment< DstXprType, SparseSymmetricPermutationProduct< MatrixType, Mode >, internal::assign_op< Scalar, typename MatrixType::Scalar >, Sparse2Sparse >::run (SparseSelfAdjointView< DestType, DestMode > & dst, const SrcXprType & src, const internal::assign_op< Scalar, typename MatrixType::Scalar > &) inline static
References Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex >::indices(), Eigen::SparseSelfAdjointView< MatrixType, _Mode >::matrix(), Eigen::SparseSymmetricPermutationProduct< MatrixType, Mode >::matrix(), and Eigen::SparseSymmetricPermutationProduct< MatrixType, Mode >::perm().
The documentation for this struct was generated from the following file:
SparseSelfAdjointView.h