SmartMouse_2018: Test.cpp File Reference
Test.cpp File Reference
#include <common/core/AbstractMaze.h>
#include <common/core/Direction.h>
#include <console/ConsoleMouse.h>
#include <common/core/Mouse.h>
#include <fstream>
#include <common/core/WallFollow.h>
#include <common/core/Flood.h>
#include <common/core/Node.h>
#include "gtest/gtest.h"
Functions
TEST (NodeTest, OutOfBoundsGetNode)
TEST (NodeTest, InBoundsGetNode)
TEST (NeighborTest, NeighborTest)
TEST (NeighborTest, NeighborOfNeighborIsMyself)
TEST (ConnectMazeTest, ConnectAllNeighbors)
TEST (ConnectMazeTest, RemoveNeighbors)
TEST (FloodFillTest, EmptyMaze)
TEST (FloodFillTest, StripedMaze)
TEST (SolveMazeTest, WallFollowSolve)
TEST (SolveMazeTest, FloodSolve)
TEST (SolveMazeTest, RandSolve)
TEST (DirectionTest, DirectionLogic)
TEST (RouteUtilTest, RouteUtilAddBack)
TEST (RouteUtilTest, RouteUtilAddFront)
TEST (RouteStringTest, RouteStringText)
int main (int argc, char **argv)
Variables
const char * FLOOD_SLN = "1E3S2E2S1W3S2E2N1E1N1E2S2E1S"
const char * WALL_FOLLOW_SLN
Function Documentation
int main (int argc, char ** argv)
TEST (NodeTest , OutOfBoundsGetNode)
References AbstractMaze::get_node(), maze, Node::OUT_OF_BOUNDS, and smartmouse::maze::SIZE.
TEST (NodeTest , InBoundsGetNode)
References AbstractMaze::get_node(), and maze.
TEST (NeighborTest , NeighborTest)
References AbstractMaze::connect_neighbor(), AbstractMaze::get_node(), maze, Node::neighbor(), and S.
TEST (NeighborTest , NeighborOfNeighborIsMyself)
References AbstractMaze::connect_all_neighbors(), AbstractMaze::connect_neighbor(), AbstractMaze::get_node(), maze, N, Node::neighbor(), NULL, and S.
TEST (ConnectMazeTest , ConnectAllNeighbors)
References AbstractMaze::connect_all_neighbors_in_maze(), E, AbstractMaze::get_node(), i, maze, N, Node::neighbor(), NULL, S, smartmouse::maze::SIZE, and W.
TEST (ConnectMazeTest , RemoveNeighbors)
References AbstractMaze::connect_all_neighbors_in_maze(), AbstractMaze::disconnect_neighbor(), AbstractMaze::get_node(), AbstractMaze::get_node_in_direction(), maze, N, Node::neighbor(), NULL, and S.
TEST (FloodFillTest , EmptyMaze)
References Node::assign_weights_to_neighbors(), i, in, maze, NULL, smartmouse::maze::SIZE, and Node::weight.
TEST (FloodFillTest , StripedMaze)
References Node::assign_weights_to_neighbors(), i, in, maze, NULL, smartmouse::maze::SIZE, and Node::weight.
TEST (SolveMazeTest , WallFollowSolve)
References in, ConsoleMouse::inst(), maze, route_to_string(), ConsoleMouse::seedMaze(), WallFollow::setup(), WallFollow::solve(), WallFollow::teardown(), and WALL_FOLLOW_SLN.
TEST (SolveMazeTest , FloodSolve)
References FLOOD_SLN, in, ConsoleMouse::inst(), maze, route_to_string(), ConsoleMouse::seedMaze(), Flood::setup(), Flood::solve(), and Flood::teardown().
TEST (SolveMazeTest , RandSolve)
References AbstractMaze::gen_random_legal_maze(), i, ConsoleMouse::inst(), Solver::isSolvable(), maze, ConsoleMouse::seedMaze(), Flood::setup(), Flood::solve(), and Flood::teardown().
TEST (DirectionTest , DirectionLogic)
References E, N, S, and W.
TEST (RouteUtilTest , RouteUtilAddBack)
References E, insert_motion_primitive_back(), N, route_to_string(), and S.
TEST (RouteUtilTest , RouteUtilAddFront)
References E, insert_motion_primitive_front(), N, route_to_string(), and S.
TEST (RouteStringTest , RouteStringText)
References E, N, route_to_string(), S, and W.
Variable Documentation
const char* FLOOD_SLN = "1E3S2E2S1W3S2E2N1E1N1E2S2E1S"
Referenced by TEST().
const char* WALL_FOLLOW_SLN
Initial value:
=
"9E1W1S1N1W2S2N1W3S2E1N1E1N1S1W1S1E2S3E1N2W2E3N1W2S1W1N1S1E2N1W1N1S1E1N1S1E1N3E10S5N1W2S3W1S2W2N2W2N2S1E2N2S1E2S1E2N3E1N1S3W2S1E1N3E3N1W1E1N1W1E1N1W1N1S1E3S1E5N1W1S1N2W5S3W2N3W1S4N1W2S1N1W1S3W1S2E1S1E1N1E1S1N1W1S1W1S1E1W2S2N1W3S2E2N1E1N1E2S1E"
Referenced by TEST().