SmartMouse_2018: time_test.cpp File Reference
time_test.cpp File Reference
#include <sim/lib/SimMouse.h>
#include <simulator/lib/common/TopicNames.h>
Functions
int main (int argc, const char **argv)
Function Documentation
int main (int argc, const char ** argv)
References TopicNames::kWorldStatistics, print(), ArduinoTimer::programTimeMs(), Command::setTimerImplementation(), timer, and SimTimer::worldStatsCallback().