SmartMouse_2018: util.cpp File Reference
util.cpp File Reference
#include <cstdarg>
#include <cstdio>
Functions
void print (const char *fmt,...)
void csv_print (std::vector< double > values)
int _getpid ()
int _kill (int pid, int sig)
void _write_r ()
Variables
global_program_settings_t GlobalProgramSettings
Function Documentation
int _getpid ()
int _kill (int pid, int sig)
void _write_r ()
void csv_print (std::vector< double > values)
void print (const char * fmt, ...)
Referenced by AbstractMaze::AbstractMaze(), End::end(), SolveMaze::end(), loop(), main(), AbstractMaze::print_dist_maze(), AbstractMaze::print_maze(), Mouse::print_maze_mouse(), print_mtx(), AbstractMaze::print_neighbor_maze(), AbstractMaze::print_pointer_maze(), AbstractMaze::print_weight_maze(), setup(), and SimMouse::simInit().
Variable Documentation
global_program_settings_t GlobalProgramSettings
Referenced by SolveCommand::initialize(), SolveCommand::isFinished(), main(), and setup().